### ISSUE TITLE
Deleting mat-tab-link from links array removes selected tab's focus

### ISSUE THREAD

**Issue by ryboucher** [angular/components#16971] opened 2019-09-04 13:42 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-cjny6b
Steps to reproduce:
1. Third tab "TestActiveTab" is currently active.
2. Click "Delete Index(1)" to delete second tab.
3. Tab "TestActiveTab" is no longer displayed as active.
 
 
#### Expected Behavior

What behavior were you expecting to see?
When the tab before "TestActiveTab" was deleted, I expected "TestActiveTab" to remain active since activeLink is still set to "TestActiveTab".

#### Actual Behavior

What behavior did you actually see?
Looking at [tab-nav-bar.ts](https://github.com/angular/components/blob/master/src/material/tabs/tab-nav-bar/tab-nav-bar.ts) 
```
 @Input()
  get active(): boolean { return this._isActive; }
  set active(value: boolean) {
    if (value !== this._isActive) {
      this._isActive = value;
      this._tabNavBar.updateActiveLink(this.elementRef);
    }
  }
```
The tabnavbar is only prompted to update when this._isActive !== value. So in our case, we have "TestActiveTab" tab set to active at index(2). Then we delete the second tab. "TestActiveTab" now has an index of 1 but the selected index is still set to 2. Since TestActiveTab's value never changed, the tabNavBar never changes it's selected index and "TestActiveTab" does not appear active, even though it's active property is still set to true. 

#### Environment

- Angular: 8.2.4
- CDK/Material: 8.1.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by ryboucher** [comment] 2019-09-04 13:46
My workaround `was` to introduce a deleting property in the active boolean. 
```
<nav mat-tab-nav-bar [backgroundColor]="background">
  <a mat-tab-link *ngFor="let link of links"
     (click)="activeLink = link"
     [active]="activeLink == link && !deleting"> {{link}} </a>
</nav>
```
The deleting property is toggled within a setTimeout, causing "TestActiveTab"'s active to toggle off and on as well. It works but feels wrong.

**Comment by ryboucher** [comment] 2019-09-04 14:46
My workaround as of right now was to view the MatTabNav
`@ViewChild(MatTabNav, { static: false }) _tabNavBar: MatTabNav;`
and update the tabNavBar manually, with a timeout. But is there a cleaner solution to this issue?
```
deleteTab(navIndex: number) {
    this.links.splice(navIndex, 1);
    console.log(this.activeLink);
    setTimeout(() => {
      this._tabNavBar.updateActiveLink();
    });
  }
```

**Comment by crisbeto** [comment] 2019-09-04 15:52
I couldn't reproduce it against master. I believe that https://github.com/angular/components/pull/16624 should've fixed it which should be in the next release. I'm closing the issue, but it can be reopened if the issue is still there after the next release.

**Closed by crisbeto** 2019-09-04 15:52 UTC

**Comment by ryboucher** [comment] 2019-09-04 17:09
This line from your commit seems to fix it. I'll look forward to the next release, thank you!
```
this._items.changes.pipe(startWith(null), takeUntil(this._destroyed)).subscribe(() => {
      this.updateActiveLink();
    });
```
