### ISSUE TITLE
help(COMPONENT): Strange Dotted Line in Angular Material Documentation 

### ISSUE THREAD

**Issue by donqq** [angular/components#21481] opened 2020-12-30 15:39 UTC
I see this strange dotted line in the Angular Material documentation
https://i.imgur.com/JVZUJBe.png
https://material.angular.io/components/dialog/overview
Saw it when the browser window was resized too. The weird thing is the location of the dots of the line change when the page is being scrolled up or down. I didn't see that strange line in any other site, only in this Angular material documentation.

**Comment by crisbeto** [comment] 2021-01-04 11:08
I wasn't able to reproduce it on a few different browsers on Windows and Mac. Closing the issue, because this looks like some sort of rendering artifact caused by the specific setup.

**Closed by crisbeto** 2021-01-04 11:08 UTC
Labels: needs triage, troubleshooting
