### ISSUE TITLE
Fix a typo in the input documentation of angular.io

### ISSUE THREAD

**Issue by ngjoni** [angular/components#21373] opened 2020-12-16 11:13 UTC
# 📚 Docs or angular.io bug report

### Description

I got an error after using the code snippet at the first example:

-> Type 'Event' is not assignable to type 'string'.  ngModel caused the error, but if you replace it with value it works.

### What's the affected URL?**
https://material.angular.io/components/input/examples

## 🔥 Exception or Error
<pre><code>

    14                    [(ngModel)]="value">
                                       ~~~~~~~
    15             <button mat-button

</code></pre>


## 🌍  Your Environment

### Browser info

### Anything else relevant?
Angular Version: 11.0.4

**Comment by annieyw** [comment] 2020-12-21 07:03
I can't seem to reproduce the error, can you clarify when you are seeing this error (eg. when you open up in stackblitz, example is not loading on the page etc).

**Comment by crisbeto** [comment] 2021-07-28 17:27
Closing since there hasn't been any feedback. The issue can be reopened if we get more information.

**Closed by crisbeto** 2021-07-28 17:27 UTC
Labels: cannot reproduce, needs clarification
