### ISSUE TITLE
[Tooltip] Tooltip doesn't always hide when mouse leaves trigger element if trigger element is moved by an animation

### ISSUE THREAD

**Issue by benelliott** [angular/components#9922] opened 2018-02-13 14:41 UTC
#### Bug, feature request, or proposal:

Sometimes a tooltip will not disappear when the mouse leaves the trigger element if there are animations and delays involved elsewhere in the component.

#### What is the expected behavior?

The tooltip should always hide when the host element is not hovered.

#### What is the current behavior?

The tooltip will sometimes get "stuck".

#### What are the steps to reproduce?

This is the closest I can come to reproducing the issue: https://stackblitz.com/edit/angular-material2-issue-scrjcu?file=app/app.component.ts

Try clicking around to reproduce the issue as seen in this gif: https://gfycat.com/AdorableMiserableGrison

#### What is the use-case or motivation for changing an existing behavior?

Bug

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest Stackblitz template, Chrome 64.0.3282.140 64 bit, Windows 10

#### Is there anything else we should know?

Could be a browser issue.

I would guess that the issue is related to a layout change that occurs while the trigger element is hovered - perhaps this causes no `mouseleave` event to be emitted when the cursor is then moved off the element or something similar.

**Comment by andrewseguin** [comment] 2018-02-13 23:09
Can't seem to get this to reproduce. Can anyone else verify the issue?

**Comment by benelliott** [comment] 2018-02-14 09:48
@andrewseguin FWIW I can reproduce this issue on Firefox 58.0, as well as on Chrome on other computers than mine. It can take a minute or so of clicking around to find a case where the tooltip fails to disappear.

**Comment by mmalerba** [comment] 2022-12-02 18:21
I'm also unable to reproduce this, therefore closing the issue. Feel free to open a new issue if you can still reproduce in the latest version of Angular Material

**Closed by mmalerba** 2022-12-02 18:21 UTC
Labels: P4, area: material/tooltip
