### ISSUE TITLE
bug(google-map): Map Marker Icon was not pinned to correct location

### ISSUE THREAD

**Issue by patatas** [angular/components#26376] opened 2023-01-06 17:59 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Map Marker - google.maps.icon is being rendered to wrong position/location when zoomed-out/default zoom level, but when I zoom-in the map, the icon is now pinned to the correct position. 

I'm currenly using svg path to create a custom icon. I'm not encountering this issue before when I'm using a png file for the icon.

Sample scenario:
Custom svg icon looks to be over the lake
![image](https://user-images.githubusercontent.com/16602605/211068163-fde0cc09-445a-44b6-9a7c-200250f886e9.png)

But when you zoom in it is not 
![image](https://user-images.githubusercontent.com/16602605/211068347-26f32a4a-3a47-4d25-9f2f-391633ebb3f3.png)

Here's my implementation:

In html, I'm using the _map-marker_ component inside google-map element
![image](https://user-images.githubusercontent.com/16602605/211069699-c364bff9-840c-40c6-8ec0-c26f6f5aee8a.png)

This is how I'm creating the marker icon
![image](https://user-images.githubusercontent.com/16602605/211069824-7f2b1df3-4de2-47dc-9f9d-e7d4741a7c2d.png)

DirectionIconPath: 'M19.13,17.763,7.4,21.229,13.265,12.7,19.4,3.9l5.865,8.8,5.865,8.531Z' 

This is how I'm setting the position of the marker
![image](https://user-images.githubusercontent.com/16602605/211070255-26cf9a5d-db1c-41dc-bddc-41923808e6fc.png)

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

Map Marker - google.maps.icon should be rendered to correct position/location when zoomed-out/default zoom level 
or the icon should be in the same position whether the map is zoom-in/out.

### Actual Behavior

Map Marker - google.maps.icon is being rendered to wrong position/location when zoomed-out/default zoom level

### Environment

- Angular: 11
- Google-maps

**Comment by marcopinato** [comment] 2023-05-16 15:06
@patatas I'm having the same issue: did you manage to solve this?

**Comment by amysorto** [comment] 2023-05-19 19:24
@patatas Can you provide a stackblitz link so we can reproduce your issue to help debug?

**Comment by amysorto** [comment] 2023-08-08 22:20
I am closing this issue since there hasn't been a response. @patatas @marcopinato if this issue still persists for you please open a new issue with a stackblitz. Thanks!

**Closed by amysorto** 2023-08-08 22:20 UTC
Labels: P4, needs: clarification, area: google-maps

**Comment by marcopinato** [comment] 2023-09-02 10:53
Just leaving this here for future visitors: make sure you offset the icon by using the `anchor` attribute to center it.

E.g. if `w` and `h` are respectively your icon's width and height:
```typescript
anchor: new google.maps.Point(w/2, h/2)
```

https://developers.google.com/maps/documentation/javascript/reference/marker#Symbol
