### ISSUE TITLE
We need support to contain both complex mat-label and complex mat-content in mat-tab.

### ISSUE THREAD

**Issue by changezzz** [angular/components#26238] opened 2022-12-12 03:35 UTC
### Documentation Feedback

We need support to contain both complex mat-label and complex mat-content in mat-tab.
![image](https://user-images.githubusercontent.com/17760511/206954841-4567043d-1f41-4f85-9c1f-1a9cebc0fbd3.png)

For now, we can just take a workaround, use another router to replace the content, so that can make tab contain icon.

### Affected documentation page

https://material.angular.io/components/tabs/api#MatTabLabel

**Comment by mmalerba** [comment] 2022-12-12 23:05
This issue needs more information:
- Is it a bug or a feature request?
- What are you seeing vs what do you expect to see?
- Please provide a stackblitz reproduction rather than a screenshot of code

**Comment by wagnermaciel** [comment] 2023-05-03 18:23
Closing since no additional information was provided after our request.

**Closed by wagnermaciel** 2023-05-03 18:23 UTC
Labels: docs, needs: clarification, needs triage
