### ISSUE TITLE
feat(material/paginator): Allow user to directly navigate to specific page using field Goto:

### ISSUE THREAD

**Issue by nishchay7pixels** [angular/components#27186] opened 2023-05-27 06:06 UTC
### Feature Description

I see there is a this respective Issue still open: bug(table): Table data does not get updated when paginator pageIndex is modified #26890 

Not sure if anyone still working on it.

But I propose that will it not be better to have a dropdown like '**Items per page:**' that says '**Goto:**' which allow user to directly select a page from dropdown or an input field that let user enter the exact page index they want to land on.

Something like below.
![image](https://github.com/angular/components/assets/24619269/d3c68fa0-5153-4f7a-ad78-bba9df64414a)

Just like Items Per Page, Got page dropdown will also be controlled by a boolean flag which if enabled will display it as part of paginator and if disabled will hide it.

### Use Case

In case of hundreds of records which leads to a lot of pages, this will will allow user to directly navigate to the page that interest them. This can be some page they found have information that they might need while they are scrolling through all the pages and once they are done with all the pages they can directly goto the pages they marked as relevant.

**Comment by crisbeto** [comment] 2023-05-28 06:41
Duplicate of https://github.com/angular/components/issues/7615.

**Closed by crisbeto** 2023-05-28 06:41 UTC
Labels: feature, needs triage
