### ISSUE TITLE
feat(stepper): support lazy rendering of steps

### ISSUE THREAD

**Issue by snebjorn** [angular/components#12817] opened 2018-08-24 09:38 UTC
#### Bug, feature request, or proposal:
feature request-ish

#### What is the expected behavior?
Each step in the stepper should have the option to be lazily rendered

#### What is the current behavior?
Currently every step is initialized when the stepper is loaded

#### What is the use-case or motivation for changing an existing behavior?
Inactive steps can have logic that fetches data or does some work that isn't relevant to the current step. 

Currently there isn't any mention of how to achieve this in the stepper. However it can be done via `<ng-container *ngIf="condition">`, not sure if there are any side effects.

```
<mat-horizontal-stepper>
  <mat-step>
    <ng-container *ngIf="condition">
      ...
    </ng-container>
  </mat-step>
</mat-horizontal-stepper>
```

The expansion panel supports lazy rendering "officially" https://material.angular.io/components/expansion/overview#lazy-rendering

```
<mat-expansion-panel>
  <mat-expansion-panel-header>
    This is the expansion title
  </mat-expansion-panel-header>

  <ng-template matExpansionPanelContent>
    Some deferred content
  </ng-template>
</mat-expansion-panel>
```

Why is there a difference? If the `<ng-container>` is a perfectly fine solution why doesn't the expansion panel do it the same way? Why is there no mention of lazy rendering in the stepper doc?

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.2
Node: 9.10.1
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.7.1
@angular-devkit/build-optimizer   0.7.1
@angular-devkit/build-webpack     0.7.1
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cdk                      6.4.2
@angular/cli                      6.1.2
@angular/flex-layout              6.0.0-beta.17
@angular/material                 6.4.2
@ngtools/webpack                  6.1.1
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
```

**Comment by Splaktar** [comment] 2018-09-23 19:57
Yes, I need this as well for a project. I tried a number of approaches but they don't seem to be supported by the current implementation.

**Comment by Splaktar** [comment] 2018-10-28 09:31
Here's a nice (related) [example](https://github.com/alsami/etdb-webclient-angular/blob/master/src/app/custom-controls/container/mat-stepper-extended.component.html) of using `ng-container *ngTemplateOutlet` inside of `*ngIf` and `*ngFor`.

**Comment by olaf89** [comment] 2018-12-05 13:09
It would be really cool if its supported out of the box

**Comment by akvaliya** [comment] 2019-03-28 11:38
Is there any update on when feature will be available?

**Comment by akvaliya** [comment] 2019-03-28 11:58
@matthiaswelz  I have a linear form like below. How can i implement your approach in this?

```
<mat-horizontal-stepper [linear]="true" #stepper [selectedIndex]="0">
  <mat-step [stepControl]="step1.stepFormGroup">
    <ng-template matStepLabel>Step 1</ng-template>
    <app-step-one #step1></app-step-one>
  </mat-step>
  <mat-step [stepControl]="step2.stepFormGroup">
    <ng-template matStepLabel>Step 2</ng-template>
    <app-step-two #step2 ></app-step-two>
  </mat-step>
  <mat-step [stepControl]="step3.stepFormGroup">
    <ng-template matStepLabel>Step 3</ng-template>
    <app-step-three #step3 ></app-step-three>
  </mat-step>
  <mat-step>
    <ng-template matStepLabel>Done</ng-template>
    You are now done.
    <div>
      <button mat-button matStepperPrevious>Back</button>
    </div>
  </mat-step>
</mat-horizontal-stepper>
```

If i try to add `<app-step-one #step1></app-step-one>` inside `ng-container` with `*ngIf` then i am unable to get `[stepControl]="step1.stepFormGroup"` from working.

**Comment by Flashunt** [comment] 2019-07-24 07:17
Is there any update?

**Comment by russcarver** [comment] 2019-08-06 22:46
I tried @matthiaswelz solution, but it still seems to be loading all 3 components. I can verify this by removing the 2nd & 3rd components and watch the load time of the first step go down from 10 seconds to 2 seconds. The components in each of my three steps are not huge, but not trivial either.

**Comment by hossameldeen** [comment] 2019-10-26 06:33
@akvaliya A workaround that I haven't tried:

- Create `step1FormGroup`, `step2FormGroup`, and `step3FormGroup` in the parent component you have here.
- Pass them down to `app-step-one`, ... etc.

Yup, not so clean. Also: not sure if a `FormGroup` must be initialized when constructed or not, but it must, then it's even not-cleaner, as the parent component will now know too much about the children.

**Comment by Hallah-94** [comment] 2019-12-16 16:37
You can use use <router-outlet> to load content of steps and in routes' file, use lazy loading for loading modules in each step

**Comment by tatsujb** [comment] 2020-01-28 08:08
@matthiaswelz "CdkStep and TemplateRef have no overlap".

**Comment by colby2** [comment] 2020-07-21 16:59
matthiaswelz no longer works. On material 9 and there still seems to be no way to implement this.

**Comment by hartmair** [comment] 2020-12-21 08:33
Next level of @matthiaswelz's workaround in order to get the collapse animation right: Render the previous step 225ms longer.
```html
<mat-vertical-stepper (selectionChange)="selectionChange($event)">
  <mat-step #step1>
    <ng-container *ngIf="renderStep('default') || renderStep(step1)">
      ...
    </ng-container>
  </mat-step>
  <mat-step #step2>
    <ng-container *ngIf="renderStep(step2)">
      ...
    </ng-container>
  </mat-step>
```
```ts
private _renderStep: CdkStep[] = [];
renderStep(step: CdkStep | 'default'): boolean {
  // workaround for https://github.com/angular/components/issues/12817#issuecomment-457314797
  return step === 'default' ? this._renderStep.length === 0 : this._renderStep.includes(step);
}
selectionChange(event: StepperSelectionEvent) {
  this._renderStep.push(event.selectedStep);
  // see https://github.com/angular/components/blob/master/src/material/stepper/stepper-animations.ts
  setTimeout(() => this._renderStep = [event.selectedStep], 225);
}
```

**Comment by rafaelss95** [comment] 2021-02-13 20:17
It looks like a duplicate of #12339, which has been closed due to the merge of the #15817.

@crisbeto, Btw, this feature will only be available in version 11.3.0, right?

**Comment by jelbourn** [comment] 2021-08-12 17:23
Duplicate of #12339

**Closed by jelbourn** 2021-08-12 17:23 UTC
Labels: feature, perf, P4, area: cdk/stepper

**Comment by snebjorn** [comment] 2021-08-13 08:10
@jelbourn #12339 is "locked due to inactivity" meaning it's completely dead
