### ISSUE TITLE
bug(COMPONENT): TITLE Moving the mouse over the mat sort header will continuously trigger the functions used by ngclass

### ISSUE THREAD

**Issue by maozhenhua2** [angular/components#29524] opened 2024-07-31 18:37 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

"dependencies": {
  "@angular/animations": "^16.2.0",
  "@angular/cdk": "^16.2.14",
  "@angular/common": "^16.2.0",
  "@angular/compiler": "^16.2.0",
  "@angular/core": "^16.2.0",
  "@angular/forms": "^16.2.0",
  "@angular/material": "^16.2.14",
  "@angular/platform-browser": "^16.2.0",
  "@angular/platform-browser-dynamic": "^16.2.0",
  "@angular/router": "^16.2.0",
  "@ngx-translate/core": "^15.0.0",
  "@ngx-translate/http-loader": "^8.0.0",
  "rxjs": "~7.8.0",
  "tslib": "^2.3.0",
  "zone.js": "~0.13.0"
},
"devDependencies": {
  "@angular-devkit/build-angular": "^16.2.14",
  "@angular/cli": "^16.2.14",
  "@angular/compiler-cli": "^16.2.0",
  "@types/jasmine": "~4.3.0",
  "jasmine-core": "~4.6.0",
  "karma": "~6.4.0",
  "karma-chrome-launcher": "~3.2.0",
  "karma-coverage": "~2.2.0",
  "karma-jasmine": "~5.1.0",
  "karma-jasmine-html-reporter": "~2.1.0",
  "typescript": "~5.1.3"
}
### Description

Moving the mouse over the mat sort header will continuously trigger the functions used by ngclass

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-sgormr?file=src%2Fapp%2Fpages%2Ftable%2Ftable.component.ts
Steps to reproduce:
1. Moving the mouse over the mat sort header
2. View console output 'getStatus'

### Expected Behavior

When the mouse moves to mat sort header, the getStatus function of ngclass is not triggered

### Actual Behavior

Moving the mouse over the mat sort header will continuously trigger the functions used by ngclass

### Environment

- Angular:  18.0.0
- CDK/Material: 18.1.2
- Browser(s): 127.0.6533.73
- Operating System (e.g. Windows, macOS, Ubuntu): window 10 22H2

**Comment by crisbeto** [comment] 2024-08-03 08:17
Duplicate of https://github.com/angular/components/issues/19441.

**Closed by crisbeto** 2024-08-03 08:17 UTC
Labels: P4, area: material/table
