### ISSUE TITLE
Dynamic value for datepicker min breaks component

### ISSUE THREAD

**Issue by calebegg** [angular/components#20278] opened 2020-08-12 15:47 UTC
Clicking on dates does nothing in this example:

https://stackblitz.com/edit/angular-4ywmkp?file=src/app/datepicker-min-max-example.ts

**Comment by crisbeto** [comment] 2020-08-12 16:35
It's because you're returning a new date object on every change detection which causes Angular to run an infinite change detection loop. It should work if you put the value into a property instead.

**Comment by calebegg** [comment] 2020-08-12 16:56
This used to work up until about a month ago.

How can I diagnose this kind of issue in the future? Normally when there's an infinite change detection loop there's some sort of console logging in dev mode, right?

**Comment by crisbeto** [comment] 2020-08-13 04:10
I'm guessing that it may have started as a result of https://github.com/angular/components/pull/19973 which marks related components for check when the inputs change. We've had other reports about this, but decided not to fix it because we'd only be hiding your performance issue from you (see https://github.com/angular/components/issues/19907). Closing as a duplicate of https://github.com/angular/components/issues/19907.

**Closed by crisbeto** 2020-08-13 04:10 UTC
