### ISSUE TITLE
Multiple Drag and drop with drag and drop cdk

### ISSUE THREAD

**Issue by Hema95** [angular/components#16970] opened 2019-09-04 12:11 UTC
#### Feature Description

With the new Angular 7 feature cdk drag and drop right now it is unable to select multiple elements and the drag those and drop it. 

#### Use Case

While drag and drop it would be good to have multiple elements dragged
 and dropped in the list

**Comment by crisbeto** [comment] 2019-09-04 16:06
Duplicate of https://github.com/angular/components/issues/14702.

**Closed by crisbeto** 2019-09-04 16:06 UTC
Labels: feature
