### ISSUE TITLE
bug(mat-checkbox): noop clickAction doesn't have accent theme by default

### ISSUE THREAD

**Issue by antoinebrault** [angular/components#19694] opened 2020-06-19 01:18 UTC
#### Reproduction

https://stackblitz.com/edit/mat-checkbox-noop-theme
 
#### Expected Behavior

Both checkboxes should be checked, with accent theme.

As stated in the doc:
By default, checkboxes use the theme's accent color. This can be changed to 'primary' or 'warn'.

#### Actual Behavior

First checkbox is checked, but doesn't have mat-accent class, so it appears to be unchecked.

#### Environment

- Angular: 9.1.1
- CDK/Material: 9.2.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2020-06-19 06:42
Duplicate of https://github.com/angular/components/issues/18465 which already has a fix.

**Closed by crisbeto** 2020-06-19 06:42 UTC
Labels: P3, area: material/checkbox, good first issue, help wanted
