### ISSUE TITLE
docs-bug(mat-select): Remove 'disableOptionCentering' input option from API documentation

### ISSUE THREAD

**Issue by eevardone** [angular/components#28304] opened 2023-12-18 17:21 UTC
### Documentation Feedback

Update API documentation to remove the 'disableOptionCentering' input property as it is no longer supported since Angular v15 (per alignment with Material technical spec).

![Screenshot 2023-12-18 at 9 18 18 AM](https://github.com/angular/components/assets/23624775/f82b2a9b-9246-4724-a49c-8b7548854a1e)

Latest:
https://material.angular.io/components/select/api

v16:
https://v16.material.angular.io/components/select/api

v15:
https://v15.material.angular.io/components/select/api

### Affected documentation page

https://material.angular.io/components/select/api

**Comment by crisbeto** [comment] 2023-12-18 21:40
Duplicate of https://github.com/angular/components/issues/28303.

**Closed by crisbeto** 2023-12-18 21:40 UTC
Labels: docs, needs triage
