### ISSUE TITLE
bug(COMPONENT): google-maps /map-marker-clusterer

### ISSUE THREAD

**Issue by wandaatest** [angular/components#29530] opened 2024-08-01 02:02 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

https://github.com/angular/components/tree/main/src/google-maps/map-marker-clusterer
```
<map-marker-clusterer #markerClusterer
                          [imagePath]="markerClustererImagePath"
                          [gridSize]="30"
                          [clusterClass]="clusterStyle"
                          [zoomOnClick]="false">
      @for (position of markerPositions; track position) {
      <map-marker #marker
                  [position]="position" />
      }
 ```

the error shows in console
markerclusterer.js:74 This version of the marker clusterer has been deprecated, and will be removed from service on August 1, 2024.
  We recommend updating your code to use @googlemaps/markerclusterer instead.
  More information is available at https://github.com/googlemaps/js-markerclusterer.

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

no errors

### Actual Behavior

the error shows in console
markerclusterer.js:74 This version of the marker clusterer has been deprecated, and will be removed from service on August 1, 2024.
  We recommend updating your code to use @googlemaps/markerclusterer instead.
  More information is available at https://github.com/googlemaps/js-markerclusterer.

### Environment

- Angular:18.1.0
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):
-  "@angular/google-maps": "^18.1.0",
-  "@googlemaps/markerclusterer": "^2.5.3",
- "@types/google.maps": "^3.55.11",

**Comment by crisbeto** [comment] 2024-08-01 05:55
Duplicate of https://github.com/angular/components/issues/23695.

**Closed by crisbeto** 2024-08-01 05:55 UTC
Labels: needs triage
