### ISSUE TITLE
bug(mat-expansion-panel): Nested expansion panels will break the lazy rendering

### ISSUE THREAD

**Issue by MatsKockmeyer** [angular/components#19260] opened 2020-05-05 11:46 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://components-issue-yzmq99.stackblitz.io

Steps to reproduce:
1. Open Expansion Panel `Header A`
2. Look at the text displayed under the second level expansion panels. Here you can see the content of the expansion panel of `Item A1` 
 
 
#### Expected Behavior
Each nested expansion panel should only display and render its own content when opened (lazy rendering).

#### Actual Behavior
By nesting two expansion panels, the content of the `<ng-template>` tag is already displayed when the outer expansion panel is opened.

#### Environment

- Angular: 9.1.2
- CDK/Material: 9.2.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2020-05-05 13:11
Duplicate of https://github.com/angular/components/issues/14365.

**Closed by crisbeto** 2020-05-05 13:11 UTC
Labels: needs triage
