### ISSUE TITLE
Checkbox: UI bug when implementing "select all" functionality

### ISSUE THREAD

**Issue by christianlundberg** [angular/components#17794] opened 2019-11-23 01:11 UTC
#### Reproduction
This is simply a fork of the example for adding checkboxes to a table from the docs. The only thing I changed was I added the ELEMENT_DATA as the initial selected value to simulate the case in which all rows start out as checked.

https://stackblitz.com/edit/angular-vxmvu6?file=src/app/table-selection-example.ts
 
 
#### Expected Behavior

I should be able to select/deselect rows

#### Actual Behavior
The "select all" checkbox displays a bug for a split second. To replicate the bug simply deselect any of the rows but look at the "select all" checkbox, it'll turn to unchecked instead of indeterminate for a brief second, then it will correctly settle on indeterminate. 

I've noticed this bug only occurs the first time, and it'll also not occur if your first action is to toggle "select all" instead of any of the rows. 

I am also positive the bug is not from the cdk as I had initially implemented this without the the cdk collection helper, and that's when I came across the error.

**Comment by PerezArmando** [comment] 2019-11-23 13:11
Did this happen in a specific browser? I was testing on Google Chrome Version 78.0.3904.97 (Official Build) (64-bit) on Mac OS and I was not able to see that issue.

**Comment by christianlundberg** [comment] 2019-11-23 16:20
@PerezArmando could it be specific to windows? I tested on Chrome Version 78.0.3904.108 (Official Build) (64-bit) and Firefox and I see the same bug.

**Comment by PerezArmando** [comment] 2019-11-27 13:13
Interesting. I did it on Windows 10 and I was able to see the issue.

**Comment by mmalerba** [comment] 2022-12-02 21:11
Here's an updated version of the stackblitz for v15: https://stackblitz.com/edit/angular-lt4efx. I don't have access to a windows machine at the moment, but we should confirm whether its still an issue given that checkbox and table have been re-implemented based on MDC

**Comment by amysorto** [comment] 2024-05-07 19:06
Tested on Chrome on Mac and Windows with components in 17.3 (MDC are now the default ones), and I cannot reproduce the issue. Closing this issue

**Closed by amysorto** 2024-05-07 19:06 UTC
Labels: P4, area: material/table, Fixed in MDC
