### ISSUE TITLE
feat(MatTimePicker): Add the Time picker component

### ISSUE THREAD

**Issue by Yar-s** [angular/components#29046] opened 2024-05-14 14:26 UTC
### Feature Description

Please, add the time picker component.
It's described in both [M2](https://m2.material.io/components/time-pickers#specs) and [M3](https://m3.material.io/components/time-pickers/overview) specs.

![image](https://github.com/angular/components/assets/17651943/cf1237fb-b5f7-422b-a939-30578b14ab7d)

There two features the specs lack that would be awesome to introduce:
* add seconds in the time picker (should be customisable)
* add an option to use the time picker inside the date picker to enter both date and time

Unfortunately, there's no way to enter time using Angular Material yet.

### Use Case

* Table data may contain numerous records per day. It would be great to have a filter that allows specifying the time range.
* A user may need to set time for some event, schedule sth.

**Comment by crisbeto** [comment] 2024-05-14 21:02
Duplicate of https://github.com/angular/components/issues/5648.

**Closed by crisbeto** 2024-05-14 21:02 UTC
Labels: feature, needs triage

**Comment by Yar-s** [comment] 2024-05-15 08:15
Sorry for the duplicate 😔
