### ISSUE TITLE
DropList created with DragDrop.createDropList is broken

### ISSUE THREAD

**Issue by tornaia** [angular/components#16961] opened 2019-09-03 16:50 UTC
#### Reproduction

https://stackblitz.com/edit/angular-8-drag-and-drop-dynamic-components

Steps to reproduce:
1. Click on the add item a few times 
2. Try to drag-and-drop these items
 
 
#### Expected Behavior

The order of the items can be changed

#### Actual Behavior

The order of the items remains always the same and the "dropped" event previousIndex and currentIndex properties have always the same value.

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.1.4
- Browser(s): Chrome 76 (but its not a browser specific issue)
- Operating System: Windows

**Comment by crisbeto** [comment] 2019-09-03 18:36
It looks like the issue is because we accidentally left the `sortingDisabled` flag on which means that sorting is disabled by default. It'll be fixed by #16963, but until they you can rework it for your case case by adding `this.dropListRef.sortingDisabled = false`.

**Comment by tornaia** [comment] 2019-09-03 18:50
Hi @crisbeto,

Thank you for the prompt reply!

I've applied the suggested workaround and it looks a bit better now: the dropped event has now the correct previousIndex and currentIndex value - unfortunately the order of the items are still always the same - despite the use of moveItemInArray.

Please find here the updated repro case:
https://stackblitz.com/edit/angular-8-drag-and-drop-dynamic-components-with-workaround

**Comment by crisbeto** [comment] 2019-09-03 18:54
The `moveItemInArray` only moves the items inside of your internal array, it won't move the elements in the DOM for you. Usually you'd have an `ngFor` that renders out the items so that when you change the data, Angular will move the items for you.

**Comment by tornaia** [comment] 2019-09-03 18:56
I see now - thanks!

**Closed** 2019-09-09 14:12 UTC
Labels: P2, has pr
