### ISSUE TITLE
Mat-Chip-List: Option to disable keyboard focus

### ISSUE THREAD

**Issue by soshochang** [angular/components#20883] opened 2020-10-26 04:07 UTC
This is a duplicate of this issue which was previously automatically closed.
https://github.com/angular/components/issues/6069

I would like to use a mat-chip for display purposes only and would not like it to be keyboard focusable. At present when I assign tabindex="-1" to the mat-chip-list it gets overwritten, and is allowed to take focus.

**Comment by annieyw** [comment] 2020-10-26 21:16
Seems like setting the tab index to -1 is working:
https://stackblitz.com/edit/angular-fgmzyx?file=src/app/chips-overview-example.html

**Comment by chivesrs** [comment] 2020-12-14 22:47
I see. The issue is that there's an undocumented [tabIndex] (note the capital I) binding, where as sosho was using the browser tabindex which is lowercase i.

**Comment by ahsan-invozone** [comment] 2021-06-18 08:25
> It's working when we put on the main tag [tabIndex]="-1". Following sample of working code. Please close this issue.
`<mat-chip-list [tabIndex]="-1">
       <mat-chip *ngFor="let val of results; let i = index">
          {{ val }}
       <i (click)="remove(i)" class="material-icons pointer">clear</i>
       </mat-chip>
  </mat-chip-list>`

**Comment by ahsanjutt01** [comment] 2021-06-18 08:33
> It's **working** when we put on the main tag [tabIndex]="-1" following sample of working code. Please close this issue.

        <mat-chip-list [tabIndex]="-1">
          <mat-chip>
            some value
            <i class="material-icons pointer">clear</i>
          </mat-chip>
        </mat-chip-list>

**Comment by zarend** [comment] 2022-10-28 21:09
Closing as it appears this is no longer an issue.

**Closed by zarend** 2022-10-28 21:09 UTC
Labels: feature, cannot reproduce, area: material/chips
