### ISSUE TITLE
mat-form-field: outline gap is wrong in rtl dir when changing routes

### ISSUE THREAD

**Issue by kyoz** [angular/components#17832] opened 2019-11-28 04:56 UTC
#### Reproduction

StackBlitz to reproduce this issue: [StackBlitz Link](https://stackblitz.com/edit/material2-mat-form-field-outline-rtl-issue-uptsyj) (With latest angular & components)

Steps to reproduce: Inside StackBlitz reproduce example

I'v open this issue once at [#14944 ](https://github.com/angular/components/issues/14944) but it seem doesn't fix anything.

#### Expected Behavior

When changing route or reload the app, if the current dir is rtl. MatFormField with outline appearance should recalculate (or do something) to update the gap in the correct position

![image](https://user-images.githubusercontent.com/29815830/69778157-e7082b80-11d5-11ea-9bfe-e8e4449469e1.png)

#### Actual Behavior

![image](https://user-images.githubusercontent.com/29815830/69778163-ebccdf80-11d5-11ea-8bbf-fb8bfe7bdcab.png)

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): Brave, Chrome, Firefox, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): Arch, OSX

**Comment by crisbeto** [comment] 2019-11-29 10:01
Looks like a duplicate of https://github.com/angular/components/issues/17390.

**Closed by crisbeto** 2019-11-29 10:01 UTC
