### ISSUE TITLE
bug(mat-select): Does not reflect null value

### ISSUE THREAD

**Issue by inorganik** [angular/components#28203] opened 2023-11-29 12:36 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If a form control is set with a null value, mat-select cannot reflect that by displaying the correct mat-option with value set to null, but it works with a native select.

This behavior is important, because for example if you are building form controls for filtering some data displayed in a UI, you must be able to have a state where all controls are empty, and thus nothing is filtered. The null option can display "All" or something similar - indicating to the user that nothing is filtered. e.g.:

```html
<mat-option [value]="null">All</mat-option>
```

This issue has existed at least as far back as v 14.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/4mzrpg?file=src%2Fexample%2Fselect-overview-example.html
Steps to reproduce:
1. Witness how the mat-select does not display the null option, but the native select does.

### Expected Behavior

Mat-select should correctly reflect a null value like a native select

### Actual Behavior

Mat-select shows no option selected

### Environment

- Angular: 17.0.0
- CDK/Material: 17.0.1
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2023-11-29 13:38
Duplicate of https://github.com/angular/components/issues/25120.

**Closed by crisbeto** 2023-11-29 13:38 UTC
Labels: needs triage
