### ISSUE TITLE
Menu: keyboard interaction doesn't work correctly after calling item's focus method

### ISSUE THREAD

**Issue by RandomNonameDude** [angular/components#17809] opened 2019-11-25 15:47 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-sferxh

Steps to reproduce:
1. Open the menu in the example
2. Third item should be focused and visually, it seems to be
3. Press `arrow-down` key
4. See that the focus moves to the _second_ item instead of fourth item
 
 
#### Expected Behavior

Keyboard interaction should work after calling item's `focus `method.

#### Actual Behavior

Keyboard interaction features should reflect when user calls item's `focus` method.

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s):  tested on Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): tested on Windows 10

**Comment by crisbeto** [comment] 2019-11-27 14:45
Duplicate of https://github.com/angular/components/issues/17761.

**Closed by crisbeto** 2019-11-27 14:45 UTC
