### ISSUE TITLE
MatTabGroup animations are jumpy in RTL

### ISSUE THREAD

**Issue by ormoyal** [angular/components#15381] opened 2019-03-05 12:05 UTC
#### What is the expected behavior?
if you try to give <mat-tab-group> dir="RTL", you see the tab not work properly

#### What is the current behavior?
the animation stuck, there also little jumps of the view

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/core": "~7.2.0",
"@angular/material": "^7.2.1",
"typescript": "~3.2.2"

#### Is there anything else we should know?
yes, you did great job.
thanks.

**Comment by jelbourn** [comment] 2019-05-11 00:16
I confirmed on our docs site that the animations are indeed jumpy when in RTL.

**Comment by crisbeto** [comment] 2024-10-09 10:17
Closing since I can't reproduce this anymore and there hasn't been much activity on the issue.

**Closed by crisbeto** 2024-10-09 10:17 UTC
Labels: help wanted, P4, animation, area: material/tabs
