### ISSUE TITLE
Dense text fields

### ISSUE THREAD

**Issue by Toso82** [angular/components#17588] opened 2019-11-02 17:03 UTC
#### Feature Description

Possibility to add Dence text field as Material Spect

https://material.io/components/text-fields/#outlined-text-field

#### Use Case

Actualy use this when there is not label 

```css
.mat-form-field:not(.mat-form-field-has-label) .mat-form-field-infix {
  border-top-width: 0;
}
```

**Comment by jelbourn** [comment] 2019-11-02 21:43
Duplicate of #4597

**Closed by jelbourn** 2019-11-02 21:43 UTC
Labels: feature

**Comment by Toso82** [comment] 2019-11-03 09:43
@jelbourn  Maybe cold be the same but it is more easy to solve. I mean to add features when i don't have input labels the extra space upper

**Comment by jelbourn** [comment] 2019-11-06 09:28
We plan to address density in general for all of the components rather than adding individual options to each component
