### ISSUE TITLE
feat(paginator): Ability to change page size appearance 

### ISSUE THREAD

**Issue by mrmokwa** [angular/components#20349] opened 2020-08-18 12:53 UTC
#### Feature Description

Ability yo customize the appearance (MatFormFieldAppearance) of paginator page size options.

`<mat-paginator appearance="standard">`

#### Use Case

If you set a default appearance with `MatFormFieldDefaultOptions`, this will reflect to paginator, and there's no way to set it manualy back to default.

#### Observations

It will be really nice if we could have it in MatPaginatorDefaultOptions also. 
So we could do this to override the appearance for paginator.

```
providers: [
   {
      provide: MAT_FORM_FIELD_DEFAULT_OPTIONS,
      useValue: { appearance: 'outline' },
   },
   {
      provide: MAT_PAGINATOR_DEFAULT_OPTIONS,
      useValue: { appearance: 'standard' },
   },
],
```

**Comment by mrmokwa** [comment] 2020-08-18 12:55
Ref #13907

**Comment by jelbourn** [comment] 2020-08-20 21:50
Duplicate of #13907

**Closed by jelbourn** 2020-08-20 21:50 UTC
Labels: feature, needs triage
