### ISSUE TITLE
feat(Stepper): Enable/Disable Steps

### ISSUE THREAD

**Issue by engmajo** [angular/components#20099] opened 2020-07-26 17:01 UTC
#### Feature Description

We need a new feature to enable or disable the steps as some of them might not be available for the user based on the access rights or the needed action.

**Comment by jelbourn** [comment] 2020-07-30 22:34
You can disable a tab, so it makes sense to disable a stepper step (which is really just a tab, semantically).

**Comment by jelbourn** [comment] 2021-08-12 17:52
Duplicate of #17294

**Closed by jelbourn** 2021-08-12 17:52 UTC
Labels: feature, P5, area: cdk/stepper
