### ISSUE TITLE
Increased initial main.js bundle size in v9 - mainly due to @angular/material packages

### ISSUE THREAD

**Issue by bri1990** [angular/components#19610] opened 2020-02-07 08:47 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

yes,

### Description

Our initial bundle increased after the upgrade to angular v9.  Below 2 screenshots made with webpack-bundle-analyzer, both are build with the --prod tag on. The complete size of our app decreased in size, but the main bundle increased slightly.

reporting this
@filipesilva who mentioned the following
> If you see your bundles increasing in size with Ivy, we want to know. Please open a new issue with a reproduction if possible. If you can’t publicly share your reproduction, consider sharing it privately instead.

In our case the initial bundle from the @angular module in angular 9.0.0 is increased by 170 kb (parsed) compared to the build size in angular 8.3.20

ANGULAR 9.0.0 bundle overview
<img width="640" alt="Screenshot 2020-02-07 at 09 21 38" src="https://user-images.githubusercontent.com/39996339/74013512-e5ed3a80-498c-11ea-9a95-d7cf6dd2292e.png">

ANGULAR 8.3.20 bundle overview
<img width="488" alt="Screenshot 2020-02-07 at 09 21 49" src="https://user-images.githubusercontent.com/39996339/74013516-e71e6780-498c-11ea-8d4f-19c819ba5d1b.png">

## 🔬 Minimal Reproduction
its a private repo, but can share an bitbucket account via a private message if needed

## 🔥 Exception or Error
budle size difference

Angular 9:

<pre><code>
chunk {33} polyfills-es2015.5bbe6128ce574187632a.js (polyfills) 97.3 kB [initial] [rendered]
chunk {34} polyfills-es5.7489d086305aa2ccf313.js (polyfills-es5) 188 kB [initial] [rendered]
--
chunk {18} runtime-es2015.7b3c2daa7eda967f9d4b.js (runtime) 4.55 kB [entry] [rendered]
chunk {18} runtime-es5.7b3c2daa7eda967f9d4b.js (runtime) 4.54 kB [entry] [rendered]
--
chunk {32} main-es2015.7771c8f8f77604a6a0fb.js (main) 1.13 MB [initial] [rendered]
chunk {32} main-es5.7771c8f8f77604a6a0fb.js (main) 1.32 MB [initial] [rendered]
--
chunk {35} styles.96f30aa09bf98d520a7b.css (styles) 403 kB [initial] [rendered]
</code></pre>
Angular 8:

<pre><code>
chunk {20} runtime-es2015.8dcc6cc63434c93fc456.js (runtime) 4.68 kB [entry] [rendered]
chunk {20} runtime-es5.8dcc6cc63434c93fc456.js (runtime) 4.67 kB [entry] [rendered]
--
chunk {40} polyfills-es2015.c6262141f4f874e78e85.js (polyfills) 98.1 kB [initial] [rendered]
chunk {41} polyfills-es5.468b140bd31c7a429390.js (polyfills-es5) 185 kB [initial] [rendered]
--
chunk {39} main-es2015.d68e6e1b9429135d5faf.js (main) 1.02 MB [initial] [rendered]
chunk {39} main-es5.d68e6e1b9429135d5faf.js (main) 1.19 MB [initial] [rendered]
--
chunk {42} styles.38056460a1b2b723be01.css (styles) 397 kB [initial] [rendered]

</code></pre>

## 🌍 Your Environment
<pre><code>
ngular CLI: 9.0.0
Node: 13.3.0
OS: darwin x64

Angular: 9.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0
@angular-devkit/build-angular     0.900.0
@angular-devkit/build-optimizer   0.900.0
@angular-devkit/build-webpack     0.900.0
@angular-devkit/core              9.0.0
@angular-devkit/schematics        9.0.0
@angular/flex-layout              9.0.0-beta.28
@ngtools/webpack                  9.0.0
@schematics/angular               9.0.0
@schematics/update                0.900.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.5

</code></pre>

**Anything else relevant?**

Similar issues: https://github.com/angular/angular-cli/issues/16989

**Comment by IgorMinar** [comment] 2020-06-11 15:36
I'm transferring this to the components repo because most of the actions need to be taken in the @angular/material and @angular/cdk codebases (in addition to landing angular/angular#37506 in the core)

**Comment by devversion** [comment] 2020-06-17 19:17
@naveedahmed1 Do you have any application we could look into? @filipesilva's investigation on list seems correct, but I'd like to double-check on other components you mentioned. e.g. tabs

**Comment by naveedahmed1** [comment] 2020-06-17 19:22
Thanks @devversion I think you are already added to https://github.com/naveedahmed1/Mustakbil-Angular , will it work?

**Comment by naveedahmed1** [comment] 2020-06-17 19:23
Thanks @devversion I have added you to a private repo, will it work?

**Comment by devversion** [comment] 2020-06-17 19:24
@naveedahmed1 yeah, that will work! Thank you! I wasn't sure whether this is the app you were testing the bundle size against.

**Comment by naveedahmed1** [comment] 2020-06-17 21:56
@devversion if you receive error of No Providers for MatDialog, it would be due to this issue https://github.com/angular/components/issues/19335, just add MatDialogModule and it should work.

**Comment by devversion** [comment] 2020-06-18 14:15
@naveedahmed1 I looked into it. Thanks for sharing your numbers and app. It looks like View Engine and Ivy deviate that much in your comparison because factories are directly attached to the classes, while View Engine had a separate chunk for factories (e.g. `24-es2015.x.js` in your app). if we sum these numbers up for tabs, we'll only see a size difference of ~4kb, compared to the mentioned ~29kb.

Percentage-wise, these 4kb are still noticeable as that signifies a ~12% increase. The actual size differences come from factories being generated for directives. This wasn't the case in View Engine as there weren't any factories for directives. Instead, host bindings, DI etc. were directly inlined to the host factory if a directive is used. A directive factory in Ivy by average seems to be larger by around ~450b (compared to the VE inlined code). There seem to be 9 directive (base) classes in tabs, resulting in the ~4kb increase. The actual size benefit with Ivy surfaces here as multiple use of, for example `MatTabLabel` is not resulting in multiple inlined factory code as with View Engine. Instead the attached factory is re-used in Ivy. That should definitely offset the 4kb, and should signify a larger size reduction in your overall application. I can definitely observe this in your application. e.g. reduction of around 15% gzipped (and lot more without gzip).

**Comment by naveedahmed1** [comment] 2020-06-20 12:51
@devversion thank you so much for your time and looking in to this, really appreciate.

**Comment by devversion** [comment] 2020-06-29 19:15
@naveedahmed1 Anytime! Thanks again for the great information/reproduction you provided! 🎉 

I'm going to close this issue as we landed our refactor changes in Angular Components. See #19576. Other than that, a slight increase in Angular Components chunks might be noticeable "at first glance", but in reality this is due to Ivy's architecture which later on results in overall size benefits (due to reduced factory code duplication etc.). Please see my comment above for a concrete example.

Also if you continue to discover any significant size impact, please create a new issue! We'd love to look into it!

**Closed by devversion** 2020-06-29 19:15 UTC
Labels: area: build, in progress
