### ISSUE TITLE
bug(mat-date-range-picker): column header given to the table are not associated with respective data cells

### ISSUE THREAD

**Issue by sourabhsoni0711** [angular/components#22884] opened 2021-06-04 10:08 UTC
#### Reproduction

Steps to reproduce:
1. Open the URL https://material.angular.io/components/datepicker/examples
2. Open date range picker in example 1
3. Navigate to the date using table shortcuts keys
4. Observe the screen reader announcement
 
 
#### Expected Behavior

1. Associate the table cells with respective column headers
2. Provide appropriate labels to the column headers (Sunday, Monday, ........)

#### Actual Behavior

1.Table headers are not associated with the data cells
2.Texts provided on the table column header are not descriptive enough for SR users. SR will read it as “M”, “T”, “W” etc. which is not meaningful enough for users.

#### Environment

- Angular: 11.0.3
- CDK/Material: 11.0.3
- Browser(s): Chrome browser 90.0.4430.100
- Operating System (e.g. Windows, macOS, Ubuntu): Google Chrome OS

**Comment by crisbeto** [comment] 2021-06-08 14:00
Duplicate of https://github.com/angular/components/issues/21357.

**Closed by crisbeto** 2021-06-08 14:00 UTC
Labels: needs triage
