### ISSUE TITLE
feat: Create a fab-speed-dial component

### ISSUE THREAD

**Issue by mmalerba** [angular/components#23654] opened 2021-09-28 19:34 UTC
#### Feature Description

The spec allows for FABs to be arranged in a [speed-dial](https://material.io/components/buttons-floating-action-button#types-of-transitions). We should discuss if this is something we want to add built-in support for.

**Comment by crisbeto** [comment] 2021-09-28 19:40
Duplicate of https://github.com/angular/components/issues/860.

**Closed by crisbeto** 2021-09-28 19:40 UTC
Labels: feature, needs discussion, needs triage

**Comment by mmalerba** [comment] 2021-09-28 19:51
I thought there was an open issue for that somewhere, I couldn't find it though. Thanks!
