### ISSUE TITLE
Datepicker: Can we show multiple calendars?

### ISSUE THREAD

**Issue by mahendar-ui** [angular/components#20885] opened 2020-10-26 15:33 UTC
#### Feature Description

I am searching for show multiple calendars in date-picker pop-up . Unfortunately I didn't found in this library
Is this feature exist?
#### Use Case
Whenever we click Date input , now we show only 1 calendar month. Instead  of that I need to show Current Month, Previous Month and Next Month. As like ng-bootstrap Date picker. Attached link here
https://stackblitz.com/run?file=app/datepicker-multiple.ts

Please help me

**Comment by annieyw** [comment] 2020-10-26 21:10
duplicate of https://github.com/angular/components/issues/20613

**Closed by annieyw** 2020-10-26 21:10 UTC
Labels: feature, needs triage
