### ISSUE TITLE
Material Design 3 support

### ISSUE THREAD

**Issue by sasafister** [angular/components#24395] opened 2022-02-10 13:00 UTC
### Feature Description

Is there any way to use Material Design 3 (Material You) in Angular Material?

### Use Case

I would like to use new design from cards, to button while using the same API from Angular Material

**Comment by crisbeto** [comment] 2022-02-21 16:40
Duplicate of https://github.com/angular/components/issues/22738.

**Closed by crisbeto** 2022-02-21 16:40 UTC
Labels: feature, needs triage
