### ISSUE TITLE
bug(datepicker): closing datepicker on monthSelected shows day view briefly

### ISSUE THREAD

**Issue by JaxonWright** [angular/components#25191] opened 2022-06-29 20:20 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

At least 8.2.3

### Description

Sometimes you might want to have a datepicker that, at its lowest level, selects a month and then closes. My use-case is that I am on a view with a calendar on a view showing an entire month. Since I am showing a month, picking a day is irrelevant

To get around the datepicker going to a day view when clicking on a month, you can add a function that runs on the `(monthSelected)` event and calls `datepicker.close()` when fired. This works, but it flashes the day view for a split second before closing. It should just close right away.

### Reproduction

Use the example at the very bottom of the official Material docs for the datepicker:
https://material.angular.io/components/datepicker/examples

### Expected Behavior

Use this example that uses Angular Material 8.2.3
https://stackblitz.com/angular/ekjvrbglvnb?file=src%2Fapp%2Fdatepicker-views-selection-example.ts

The datepicker closes immediately upon selecting a month. 

This is just one that I found when researching this issue. It is possible that versions later than this also work.

### Actual Behavior

The datepicker switches to the day view and then closes.

### Environment

- Angular: 14.0.2
- CDK/Material: 14.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment] 2022-08-12 11:27
Duplicate of https://github.com/angular/components/issues/20904.

**Closed by crisbeto** 2022-08-12 11:27 UTC
Labels: needs triage
