### ISSUE TITLE
Mat-form-field outline rendered incorrectly when direction='rtl'

### ISSUE THREAD

**Issue by mihaionduma** [angular/components#18857] opened 2020-03-18 16:33 UTC
**What's the bug:**

When changing the direction of a matFormField, the outline gap doesn't render correctly. 

**Steps to reproduce:**
1. Build a form with a mat-form-field in it
2. Add a mat-label tag with a string inside it
3. add a span tag with a prefix attribute
4. Change the direction of the mat-form-field to rtl

or 

See https://stackblitz.com/edit/angular-vwwrbm-8xrx3b 
 
 
#### Expected Behavior

I was expecting the outline and its label to be rendered correctly, even with the prefix and suffix labels inside the mat-form-field.

#### Actual Behavior

When changing the direction of a mat-form-field, the outline gap doesn't render correctly, there's a gap where the mat-label should be. Also this is affected by having a prefix inside the mat-form-field, somehow the prefix's width decrements the outline label left positioning instead of increasing it.

Also the outline itself of the mat-form-file is not rendered correctly.

Also the MatFormField updateOutlineGap() doesn't update the material correctly, when the direction is rtl. I'm calling updateOutlineGap everytime the direction changes, ltr works ok but rtl is out of place.

#### Environment

- Angular: 9.0.0
- CDK/Material: 9.1.3
- Browser(s): Chrome 80.0.3987.132 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment] 2020-03-18 17:30
In general Material components don't respond to the CSS `direction` property, because there's no way for us to detect it. You should use the `dir` HTML attribute instead.

**Comment by mybrainquit** [comment] 2020-03-18 18:32
> In general Material components don't respond to the CSS `direction` property, because there's no way for us to detect it. You should use the `dir` HTML attribute instead.

Thank you for your speedy reply. 
I've modified the stackblitz to have dir in its html attribute, the bug is still there.

https://stackblitz.com/edit/angular-vwwrbm-8xrx3b

**Comment by crisbeto** [comment] 2020-03-18 18:43
The example you linked is the same as the original one, but here's something that works: https://stackblitz.com/edit/angular-vwwrbm-dtrw7y

**Comment by mybrainquit** [comment] 2020-03-19 08:44
I've managed to reproduce the problem in your example. The problem is that if the [dir] receives only a string and not a expression the initial outline is not rendered correctly.

https://stackblitz.com/edit/angular-vwwrbm-srpxkk

**Comment by crisbeto** [comment] 2020-03-19 19:42
Thank you, now I see it. We have an incorrect calculation that I've fixed in #18867.

**Closed** 2020-03-21 05:06 UTC
Labels: P2, has pr
