### ISSUE TITLE
Chips Autocomplete

### ISSUE THREAD

**Issue by atulsingh001** [angular/components#12621] opened 2018-08-10 12:40 UTC
#### Bug, feature request, or proposal:

Application does not display  Permissions in dropdown in Choose Permission field if user types first character
When user enters first character for first time it suggests.On selecting a value when user again selects first charcter it does not display the dropdown. The user has to press backspace and press character again

#### What is the expected behavior?
Whenever user enters first character for first time chips autocomplete filter is working as per requirement. we selected chips as required, but , just after that if we 
try to enters first character, then it is not working as it was working in first time, if we will press backspace then enters first character, then it is working as per requirement

#### What is the current behavior?
it is isssue in chips autocomplete

#### What are the steps to reproduce?
Step 1 :  data = ['Afganistan','Albania','Andorra','Angola','Argentine','Armenia','Australia'];
Step 2 : enter first charactor 'A'
Step 3 : Select country 'Afganistan' in chip
Step 4 : Again enter first charactir 'A'

Now filter is not working.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/core: ^5.2.0
@angular/material: ^5.2.0
typescript: ~2.6.2

**Comment by jelbourn** [comment] 2018-08-10 16:36
Are you able to share a live reproduction w/ the latest version of the library?

**Comment by josephperrott** [comment] 2018-08-10 16:41
It looks like the issue that is being seen is that the first character typed in the input after selection of a chip does not trigger the autocomplete, however the second keystroke does.  See this [stackblitz](https://stackblitz.com/edit/angular-jbgfxv?file=app/chips-autocomplete-example.html).

If you select `apple` from the autocomplete (either by clicking or via keyboard selection), then type `a` the autocomplete does not show, but upon typing `p` after the `a` it works as expected.  It seems the first keystroke is not triggering the necessary events.

**Comment by atulsingh001** [comment] 2018-08-23 04:34
As we have verified above given link "https://stackblitz.com/edit/angular-jbgfxv?file=app/chips-autocomplete-example.html", it is giving same result, which i reported to you. We are waiting for your response please.

in case-any query, please revert.
Thanks
Atul Singh.

**Comment by HirenBypt** [comment] 2020-05-05 04:58
I have same issue. Is this fixed already?

**Comment by zarend** [comment] 2023-01-12 22:23
Cannot reproduce. I believe this was fixed in v15.

**Closed by zarend** 2023-01-12 22:23 UTC
Labels: P4, area: material/autocomplete
