### ISSUE TITLE
Autocomplete with Id & Value, displayWith, & Reactive form.  DisplayWith does not display value

### ISSUE THREAD

**Issue by evanstj** [angular/components#11796] opened 2018-06-14 22:15 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The reactive form field is the Id and is what the database is expecting.  The display to the user should be the value.  

#### What is the current behavior?
The displayWith function does find and return the value but I think because the input is associated with the Id, it persists in displaying the Id.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-qqbxbt 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular & Material 5

**Comment by josephperrott** [comment] 2018-06-25 15:50
Can you expand a bit on the issue you are seeing?  After reading through your report, I am not quite sure of the issue you are encountering.

**Comment by evanstj** [comment] 2018-06-25 16:16
Hi Joseph,

Sorry, I should have gone back and expounded a bit more.  I continued to work with the issue I was having.  I was trying to add an Autocomplete select form control to a Reactive form.  I could not use formControlName in my html, I had to change it to use a formControl then manually move the data back and forth.

In the stackBlitz I attached I have two autocomplete fields.  The first one uses formControlName but it does not work as expected.  If you select a warehouse from the drop down, the warehouseId field = the whole warehouse object not the warehouseId value (see the Form Value display at the bottom of the screen).  If I change the [value]=”w”  to [value]=”w.warehouseId” then I cannot get the warehouse name to display to the user.

The second autocomplete field does work and is what I have been using to move forward but I have to create a separate FormControl field for each autocomplete field on my page and manually move data when an option is selected.

Maybe this isn’t a bug but instead a feature request.  It would be nice if the autocomplete worked with the Reactive form’s formControlName.

Please let me know if I still didn’t give enough detail.

Thanks,
Tracy.

Tracy Evans | Senior Systems Analyst | Charleston Water System | 843-727-6928

**Comment by evanstj** [comment] 2018-06-25 16:20
Hi Joseph,

Sorry, I should have gone back and expounded a bit more.  I continued to work with the issue I was having.  I was trying to add an Autocomplete select form control to a Reactive form.  I could not use formControlName in my html, I had to change it to use a formControl then manually move the data back and forth.

In the stackBlitz I attached I have two autocomplete fields.  The first one uses formControlName but it does not work as expected.  If you select a warehouse from the drop down, the warehouseId field = the whole warehouse object not the warehouseId value (see the Form Value display at the bottom of the screen).  If I change the [value]=”w”  to [value]=”w.warehouseId” then I cannot get the warehouse name to display to the user.

The second autocomplete field does work and is what I have been using to move forward but I have to create a separate FormControl field for each autocomplete field on my page and manually move data when an option is selected.

Maybe this isn’t a bug but instead a feature request.  It would be nice if the autocomplete worked with the Reactive form’s formControlName.

Please let me know if I still didn’t give enough detail.

**Comment by jelbourn** [comment] 2020-07-23 22:13
Going to close this as a duplicate of #12144 since that would cover this use-case

**Closed by jelbourn** 2020-07-23 22:13 UTC
Labels: area: material/autocomplete, needs triage
