### ISSUE TITLE
matMenu throws an error when using Ivy

### ISSUE THREAD

**Issue by tzachov** [angular/components#16287] opened 2019-06-13 11:08 UTC
#### Reproduction

Clone https://github.com/tzachov/mat-menu-ivy

-- OR --

Steps to reproduce:
1. `ng new mat-menu-ivy --enableIvy`
2. `ng add @angular/material`
3. Import MatMenuModule into AppModule:
```typescript
import {MatMenuModule} from '@angular/material/menu';
```
4. Add MatMenu to `app.component.html`:
```html
<mat-menu #appMenu="matMenu">
  <button mat-menu-item>Settings</button>
  <button mat-menu-item>Help</button>
</mat-menu>

<button mat-icon-button [matMenuTriggerFor]="appMenu">
  <span>Open Menu</span>
</button>
```
 
#### Expected Behavior

Menu should open

#### Actual Behavior

Error in console:
```
ERROR TypeError: Cannot read property 'createEmbeddedView' of undefined
    at ViewContainerRef_.createEmbeddedView (core.js:20114)
    at DomPortalOutlet.attachTemplatePortal (portal.js:343)
    at DomPortalOutlet.attach (portal.js:225)
    at OverlayRef.attach (overlay.js:926)
    at MatMenuTrigger.openMenu (menu.js:1184)
    at MatMenuTrigger.toggleMenu (menu.js:1166)
    at MatMenuTrigger._handleClick (menu.js:1511)
    at MatMenuTrigger_click_HostBindingHandler (menu.js:1575)
    at executeListenerWithErrorHandling (core.js:16053)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:16088)
```

#### Environment

- Angular: 8.0.0
- CDK/Material: 8.0.1/8.0.1
- Browser(s): Chrome 74.0.3729.169 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by josephperrott** [comment] 2019-06-13 15:12
Closing per https://github.com/angular/components/issues/16028#issuecomment-500867907

**Closed by josephperrott** 2019-06-13 15:12 UTC

**Comment by icecoldfire** [comment] 2019-07-02 09:29
I have the same issue:

```
core.js:7187 ERROR TypeError: Cannot read property 'createEmbeddedView' of undefined
    at ViewContainerRef_.createEmbeddedView (core.js:20128)
    at DomPortalOutlet.attachTemplatePortal (portal.js:343)
    at DomPortalOutlet.attach (portal.js:225)
    at OverlayRef.attach (overlay.js:926)
    at MatMenuTrigger.openMenu (menu.js:1184)
    at MatMenuTrigger.toggleMenu (menu.js:1166)
    at MatMenuTrigger._handleClick (menu.js:1511)
    at MatMenuTrigger_click_HostBindingHandler (menu.js:1575)
    at executeListenerWithErrorHandling (core.js:16028)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:16063)
```

with the following package file:

```
{
  "name": "client",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "8.0.3",
    "@angular/cdk": "8.0.1",
    "@angular/common": "8.0.3",
    "@angular/compiler": "8.0.3",
    "@angular/core": "8.0.3",
    "@angular/forms": "8.0.3",
    "@angular/material": "8.0.1",
    "@angular/platform-browser": "8.0.3",
    "@angular/platform-browser-dynamic": "8.0.3",
    "@angular/router": "8.0.3",
    "rxjs": "6.4.0",
    "tslib": "1.10.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.800.6",
    "@angular/cli": "8.0.4",
    "@angular/compiler-cli": "8.0.3",
    "@angular/language-service": "8.0.3",
    "@types/node": "8.9.4",
    "@types/jasmine": "3.3.8",
    "@types/jasminewd2": "2.0.3",
    "codelyzer": "5.0.0",
    "jasmine-core": "3.4.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.0",
    "protractor": "5.4.0",
    "ts-node": "7.0.0",
    "tslint": "5.15.0",
    "typescript": "3.4.3"
  }
}
```

**Comment by devversion** [comment] 2019-07-02 09:41
The issue was caused by a ngcc bug. Therefore the fix is not coupled to a release of Angular Material. The ngcc fix landed in the following versions of Angular already: 8.1.0-rc.0, 8.1.0-next.3, 8.1.0-next.2.

Please see: https://github.com/angular/angular/commit/2b4d5c75486534decef4030d4166806878929e4c
