### ISSUE TITLE
Nested menu goes out of screen on mobile

### ISSUE THREAD

**Issue by jbojcic1** [angular/components#7688] opened 2017-10-10 18:12 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Nested menu should stay on screen if possible or main menu should be closed or something

#### What is the current behavior?
See screenshot below

#### What are the steps to reproduce?
Create nested menu and open it on mobile

#### What is the use-case or motivation for changing an existing behavior?
Using nested submenu on mobile devices

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?

![screen shot 2017-10-10 at 8 06 18 pm](https://user-images.githubusercontent.com/10374826/31402859-8fa28a6e-adf7-11e7-8564-3e6727df7172.png)

**Comment by crisbeto** [comment] 2017-10-10 18:32
In this case it looks like none of the positions would've fit on screen. This is the one that shows the largest area of the element. We're working on some improvements to the connected positioning that should allow for content to be pushed into the viewport.

**Comment by jbojcic1** [comment] 2017-10-10 18:40
@crisbeto is there a way to close main menu like it was working before introducing nested menu? That would be better than this

**Comment by kaziupir** [comment] 2017-11-02 22:28
I have the same problem, even if submenu can fit into window. It never overlaps main menu. Looks like bug for me.

**Comment by TimPWright** [comment] 2017-12-07 17:04
This is an issue not only on mobile. I have a desktop menu that has quite a few items in it, the menu will open but cut off the first entries. 

![screenshot from 2017-12-07 09-57-51](https://user-images.githubusercontent.com/1966467/33727478-63018238-db35-11e7-893e-a41a83238a80.png)

Notice the menu is behind the browser bar and notice it shows Cabin 12 as the first entry. Cabin 1-11 are behind the bar. I can make a hack fix by adding a max-height to the mat-menu-panel but that does not seem the best solution.

**Comment by netkovedar** [comment] 2017-12-12 13:24
Can I get an info about the status of this bug please? @kara @crisbeto

**Comment by lemoinem** [comment] 2018-12-03 16:03
This **seems** to have been fixed as of Angular Material 7
Is anyone still having this issue?

**Comment by zarend** [comment] 2024-03-29 18:45
Hello @aeslinger0 ,

Thank you for this information. I suggest filing a new issue report for click behavior between nested menu and top menu. That way it can get more attention and the information may be more clear to library maintainers. If you can reproduce with [Menu examples on docs site](https://material.angular.io/components/menu/overview), that would be really helpful.

Since the reported issue appears to have been fixed, I'll mark this issue as closed.

Best Regards,

Zach

**Closed by zarend** 2024-03-29 18:45 UTC
Labels: P3, area: material/menu
