### ISSUE TITLE
bug(cdk/drag-and-drop): Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by michalgrzegorczyk-dev** [angular/components#25963] opened 2022-11-12 06:33 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

During drag I'm getting 'Unable to preventDefault inside passive event listener invocation.' in the console. 

### Reproduction

Steps to reproduce:
1. Open https://material.angular.io/cdk/drag-drop/overview
2. Drag any of the example
3. Open console

### Expected Behavior

It shouldn't display so many errors in the console.

### Actual Behavior

It dispolays many errors during drag in the console.

### Environment

- Angular: 14
- CDK/Material: CDK drag and drop
- Browser(s): Chrome Version 107.0.5304.87 (Official Build) (arm64)
- Operating System macOS Ventura 13.0

**Comment by crisbeto** [comment] 2022-11-14 08:12
I'm not seeing this on my end. Since we explicitly bind all the appropriate events as active in the `drag-drop` module, the warning is likely caused by another script on your page (e.g. a browser extension). Duplicate of https://github.com/angular/components/issues/24979.

**Closed by crisbeto** 2022-11-14 08:12 UTC
Labels: needs triage
