### ISSUE TITLE
bug(_MatMenuBase): Class '_MatMenuBase' incorrectly implements interface 'MatMenuPanel<MatMenuItem>'

### ISSUE THREAD

**Issue by csAjayNayak** [angular/components#25519] opened 2022-08-24 09:12 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Error in compilation with "strictNullChecks": true in tsconfig.json
![image](https://user-images.githubusercontent.com/81223156/186377161-c44b5e3e-8ae0-4dbd-8a14-ec8c4c91dab7.png)

### Reproduction

Steps to reproduce:
1.  Add Angular Material [14.1.3] Library
2. Set "strictNullChecks": true in tsconfig.json
3.  Try to Compile Angular App

### Expected Behavior

Angular App Successfully Compile

### Actual Behavior

Angular App Compile Error

### Environment

- Angular: 14
- CDK/Material: 14.1.3
- Browser(s): Chrome 104
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Pro

**Comment by crisbeto** [comment] 2022-08-24 14:10
What version of TypeScript are you using? We have `strictNullChecks` enabled in our repo and this hasn't shown up in our build.

**Comment by csAjayNayak** [comment] 2022-08-25 09:35
Typescript "^4.7.4" @crisbeto

**Comment by vonAnden** [comment] 2022-08-26 08:49
I got the same error when enabling exactOptionalPropertyTypes after updating from Angular 12 -> Angular 13 with typescript 4.6.4. (tried to enable exactOptionalPropertyTypes as it is recommeded but ran into this problem)

**Comment by crisbeto** [comment] 2022-08-27 10:01
Duplicate of https://github.com/angular/components/issues/24078.

**Closed by crisbeto** 2022-08-27 10:01 UTC
Labels: needs triage
