### ISSUE TITLE
[Drag and Drop] cdkDragHandle still ignored when it is placed inside a child component

### ISSUE THREAD

**Issue by william-fargues** [angular/components#27247] opened 2023-06-07 01:15 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

As the title say, when a cdkDragHandle is used inside a child component, it's ignored and we can still drag the whole element. Also, cdkDragHandle is working correctly when defined in the same component as the cdkDrag element.

I've seen this issue: [https://github.com/angular/components/issues/13784](https://github.com/angular/components/issues/13784) but using `<ng-content>` is not an ideal solution. Also, [crisbeto](https://github.com/crisbeto) mentionned in the same issue that the Angular team was working on a fix (using a `dragRef` ?). So I don't know what exactly to do to cleanly fix this problem.

### Reproduction

[https://stackblitz.com/edit/components-issue-t5n33x](https://stackblitz.com/edit/components-issue-t5n33x)

### Expected Behavior

Able to move the card only using the handle.

### Actual Behavior

The card can be dragged using itself (the handle is ignored).

### Environment

Angular CLI: 14.2.10
Node: 16.10.0
Package Manager: npm 7.24.0
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.7
@angular/cli                    14.2.10
@schematics/angular             14.2.10
rxjs                            7.4.0
typescript                      4.8.4

**Comment by crisbeto** [comment] 2023-06-07 07:47
Duplicate of https://github.com/angular/components/issues/13784. There haven't been any changes since then.

**Closed by crisbeto** 2023-06-07 07:47 UTC
Labels: needs triage
