### ISSUE TITLE
Ripple DOM elements are not garbage collected

### ISSUE THREAD

**Issue by mackelito** [angular/components#15322] opened 2019-02-27 07:24 UTC
#### What is the expected behavior?
Number of nodes should be the same

#### What is the current behavior?
DOM nodes increase on every toggle of SideNav

#### What are the steps to reproduce?
https://angular-axmnmp.stackblitz.io/
Open up dev-tools and look at the Performance Monitor tab
The number of DOM Nodes increases on each klick of "Cart" button in the header

#### Is there anything else we should know?
Not sure this is actually a bug or if I'm missing something but found the behaviour strange :)

![kapture 2019-02-27 at 8 26 59](https://user-images.githubusercontent.com/598463/53473027-a1151000-3a69-11e9-9314-a953f6ed3199.gif)

**Comment by macjohnny** [comment] 2019-02-27 09:27
this could be due to the animation, see https://github.com/angular/angular/issues/26133

**Comment by Sriharish** [comment] 2019-03-05 06:00
@mackelito I think the issue is with the ripples becoming detached nodes and never properly being garbage collected. You can observe this even from clicking the left menu repeatedly as well. [This](https://github.com/angular/material2/pull/8864) is the closest discussion I could find for it so far. Keep in mind if the route changes, the nodes are wiped.

**Comment by jelbourn** [comment] 2019-05-12 15:56
Potentially related to #15225

**Comment by flemgs** [comment] 2020-03-06 17:18
When will it be fixed ? Is there a workaround to delete them manually ? Thanks.

**Comment by flemgs** [comment] 2020-03-10 16:14
Would it be fixed by this pull request ? [fix(animations): leaking detached nodes when parent has a leave transition #34409 ?](https://github.com/angular/angular/pull/34409)

**Comment by jelbourn** [comment] 2022-08-12 22:17
@viniciusschuelter thanks for checking this! I will close this. For anyone else following this issue, feel free to open a new issue with reproduction steps if a problem is still occurring.

**Closed by jelbourn** 2022-08-12 22:17 UTC
Labels: P2, perf, help wanted, area: material/core, area: material/sidenav

**Comment by sunitadhamankar** [comment] 2022-09-07 11:09
which version this was fixed?

**Comment by viniciusschuelter** [comment] 2022-09-07 12:59
Probably 14+ https://github.com/angular/components/commit/dbb6dc09b452c126ddf612c1731595615e505e27

**Comment by sunitadhamankar** [comment] 2022-09-09 09:58
> Probably 14+ [dbb6dc0](https://github.com/angular/components/commit/dbb6dc09b452c126ddf612c1731595615e505e27)

Thanks..will check.
