### ISSUE TITLE
Anchor within URL doesn't make the browser scrolling to the anchored section at all.

### ISSUE THREAD

**Issue by thariqnu-ifm** [angular/components#17981] opened 2019-12-17 00:38 UTC
Trying to open https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings using Chrome browser.

The browser should scroll to the "Choosing a date implementation and date format settings" section.
But currently, it doesn't scroll at all. The browser stays on the top-most part of the page.

P.s. this URL is obtained through copying the link provided in the left side of the section's title.

**Comment by mikyaj** [comment] 2019-12-22 10:12
@jelbourn If no one is working on it, I can give it a try.

**Comment by mikyaj** [comment] 2020-01-02 17:03
Seems like this issue has already been fixed in master branch. I checked out latest from [material.angular.io](https://github.com/angular/material.angular.io) and by running on local machine I can't reproduce it in but I was able to reproduce it in branch 8.x.

**Comment by abhilive** [comment] 2020-01-04 07:38
Hi! @thariqnu-ifm & @mikyaj  I can witness this issue but with a bit different behavior, once I open this link https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings in new tab/widnow, first it scrolls to that particular section and once browser finishes loading it scrolls to the top. 
Chrome Version 79.0.3945.88
Windows 7 (64-bit)

**Comment by Drdobrovolny** [comment] 2020-02-04 05:25
I see this happening with all anchored links, when navigating to them from offsite. Will look into

**Comment by n4ns** [comment] 2020-04-20 11:03
HI iam new to contributing in github. i want to replicate the issue in my local.
i have done checkout of angular/components project and did installation using yarn.
Can anyone help me in running in my local the same.

**Comment by jelbourn** [comment] 2021-05-25 23:52
This appears to be fixed in the latest version of the site.

**Closed by jelbourn** 2021-05-25 23:52 UTC
Labels: P3, area: material.angular.io, docs, good first issue, help wanted
