### ISSUE TITLE
drag-drop: make the view scroll when trying to move a draggable outside the current view

### ISSUE THREAD

**Issue by lfroment0** [angular/components#13588] opened 2018-10-12 12:16 UTC
#### Bug, feature request, or proposal:

When trying to drag a cdkDragItem outside of the view, it does not scroll to show the rest of the cdkDrop div / the rest of the page.  

#### What is the expected behavior?

The view should scroll towards the direction in which the element is being dragged to reveal the rest of the page.

#### What is the current behavior?

The view doesn't scroll, the droppable item cannot move out of the current view 

#### What are the steps to reproduce?
In the following stackblitz, try to drag an item from the start of the list to the bottom of the list.
https://stackblitz.com/edit/angular-emaoau

#### What is the use-case or motivation for changing an existing behavior?

The current behaviour feels very restrictive. you could have to take multiple steps if you want to drag and drop an element in a larger list.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

- Angular Cdk 7.0.0 beta to 7.0.0-rc.1

**Comment by sanketi** [comment] 2018-10-26 19:17
Is there any intermediate way to make it work with dom-autoscroller until TODO is addressed?

**Comment by JohnKis** [comment] 2018-11-16 11:01
@crisbeto I've implemented auto scrolling on CdkDropList in my private fork. It doesn't cover scenarios  where the drop list is wider/taller than its scroll parent but it works fine when the drop list fits on the screen. If you think it'd be useful, I can set aside some time to prepare a PR.

**Comment by crisbeto** [comment] 2018-11-17 09:09
@JohnKis the scrolling logic here isn't really the issue. We've held back on implementing it until now, because it's tricky knowing which element we're supposed to scroll.

**Comment by JohnKis** [comment] 2018-11-17 09:14
@crisbeto Understood, just figured I’d ask. Thanks

**Comment by abdulkareemnalband** [comment] 2018-11-19 06:12
@crisbeto I think we could use cdk-scrollable as marker for element to scroll

**Comment by aidvb** [comment] 2018-11-28 08:39
Hi guys. Any ideas on when to expect the fix?

**Comment by rimvydas-urbonas** [comment] 2018-11-28 14:53
Hey, any update on this thread?

**Comment by lfroment0** [comment] 2018-11-29 12:42
The cdkDropListEntered event would be nice, but wouldn't solve the problem.

eg. the case where your dropzones are in a scrollable container and the height of a drop zone is greater than the one of the container, so as only one dropZone is displayed. The supposed cdkDropListEntered event will never be emitted.

Would it be possible to make a CdkdropListGroup aware of it's container, so that it can be conscious of how it should behave when moving an item towards the displayed edges of that container?

**Comment by agent0** [comment] 2018-11-29 14:34
I have been trying to come up with a work-around that does not rely on specific functionality by the component library. My approach was to add transparent divs at the top and the bottom of the scrollable container und to watch for mouseenter/mouseleave events to scroll the container. Unfortunately, this did not work as the framework stops the propagation of these events. I don't know if this behavior could be chanhged more easily than coming up with brand new concepts to deal with the matter.

**Comment by aidvb** [comment] 2018-11-30 09:43
Any updates so far?

**Comment by aidvb** [comment] 2018-12-04 08:47
> I have been trying to come up with a work-around that does not rely on specific functionality by the component library. My approach was to add transparent divs at the top and the bottom of the scrollable container und to watch for mouseenter/mouseleave events to scroll the container. Unfortunately, this did not work as the framework stops the propagation of these events. I don't know if this behavior could be chanhged more easily than coming up with brand new concepts to deal with the matter.

Can you just watch for window.height and window.width and check, if the container extends further, then if it is drag action, then if mouse is down (meaning something is being dragged), then scroll the page accordingly?

**Comment by abdulkareemnalband** [comment] 2018-12-04 09:42
@aidvb I have a solution but it comes with its own problems
see repro example in #14098

**Comment by agent0** [comment] 2018-12-04 10:06
@aidvb Maybe this would work with scrolling the entire page, in my use case, however, I woul dlike to scroll individual divs. Also, I am not sure if I need browser events to capture the mouse actions and since material cancels the event popagation, I would end up where I started.

**Comment by aidvb** [comment] 2018-12-07 12:18
@agent0 How's it going to solve the problem?

**Comment by agent0** [comment] 2018-12-16 07:53
@aidvd I would not solve the problem as such but it would enable me to implement my own scrolling trigger to scroll the underlying div manually. As it stands now, I cannot detect that the drag in hovering a border area of the div.

**Comment by rbdv159** [comment] 2018-12-18 10:40
+1 for this

**Comment by aidvb** [comment] 2018-12-20 13:16
Any progress on solving this issue?

**Comment by techy2493** [comment] 2018-12-21 21:12
Definitely going to +1 this. We're getting ready to implement a work-around using the cdkDragMoved event but that feels like a really poor decision for long run.

**Comment by codeweazel** [comment] 2019-01-04 13:43
Would love to have a solution for this. Need to scroll something out of the viewport.

**Comment by TheKeymaster** [comment] 2019-01-07 21:00
Is there any workaround for this? I really need this because I have not that much space and I want to allow users to drag and drop inside a small container that is scrollable.

**Comment by techy2493** [comment] 2019-01-10 15:33
@TheKeymaster The CDK drag&Drop currently calculates drop position in such a way that moving the scroll position of the container while dragging interferes with this calculation. Any work-around to detect the hover position of the drug object is limited by that. If you are There is an open issue to address that concern #14098 as well.

**Comment by shyamal890** [comment] 2019-01-13 10:55
+1 Any temporary fix for this?

**Comment by abdulkareemnalband** [comment] 2019-01-14 06:07
@shyamal890 
you can use repro code from #14098 as starting point
also follow up with this https://github.com/angular/material2/issues/14098#issuecomment-450958865

**Comment by aidvb** [comment] 2019-01-18 13:47
How are the things going? Any chances this issue gonna be fixed?

**Comment by techy2493** [comment] 2019-01-25 22:38
Would love to hear anything about this. Is there any feedback we can provide to help answer any use case questions? Is this not moving because of a priority thing or are there still open questions that need to be answered before the Angular team can move forward that we could be addressing?

**Comment by oliwin** [comment] 2019-02-01 15:31
I figured out, that drag zone is escaped when exist scroll in parent list block. To move need drag element in invisible area under scroll

**Comment by aidvb** [comment] 2019-02-05 15:12
So did anyone manage to come up with a solution in two months time?

**Comment by aidvb** [comment] 2019-02-06 07:52
@techy2493 Very nice to hear that. Is your update gonna be merged into future release sometime soon?

**Comment by techy2493** [comment] 2019-02-06 16:10
@aidvb I doubt it. My use case doesn't encompass every scenario raised here. In my case I have a single container which is scollable and a single drop list, it's pretty minimal. There are some great questions raised here that the Angular team has to consider, what does happen if there are two scrollable lists, which done do you scroll? How do you switch between them? What if those in turn turn out to be in a scrollable container? It might be nice to see some basic functionality added that doesn't take these things into consideration and see if anyone can come up with additional  input or maybe some sample code that would help the more complex use cases.

@crisbeto I could put in a PR with the requite additional tests and documentation if that would allow others to more easily get sample solutions set up as example for how this might be tackled if that would be helpful?

**Comment by willbeaufoy** [comment] 2019-02-12 16:45
+1 for this

**Comment by ansarisufiyan777** [comment] 2019-02-13 12:15
Did anyone get the solution?

**Comment by volser** [comment] 2019-02-19 09:31
@crisbeto any news about auto-scrolling functionality?
it's really breaking issue, thx

**Comment by volser** [comment] 2019-02-19 09:42
> Is there any intermediate way to make it work with dom-autoscroller until TODO is addressed?
> https://github.com/hollowdoor/dom_autoscroller

I tried, dom_autoscroller doesn't work here (
I guess because some events are prevented

**Comment by aidvb** [comment] 2019-02-19 10:32
@crisbeto Really, what's the update on this issue? Why no one at Angular team solving this problem?

**Comment by volser** [comment] 2019-02-27 19:10
Anybody has workaround solution?
I'm able to scroll when drag, but can't to fix positions.
Tried to recalc `_itemPositions` but looks like it's not enough (

**Comment by volser** [comment] 2019-03-03 15:51
My workaround solution (not finished):
https://stackblitz.com/edit/angular-drag-scroll1

Its not perfect but works.

tried to fix next issues:
1. Scroll while dragging
2 .Incorrect item position when drag between vertical positioned containers
https://github.com/angular/material2/issues/15227
3. D&d does not work correctly when change data while dragging (drops and drags)
 https://github.com/angular/material2/issues/15343

feel free to fix issues found or propose better solutions

**Comment by wilgert** [comment] 2019-03-13 08:01
> My workaround solution (not finished):
> https://stackblitz.com/edit/angular-drag-scroll1
> 
> Its not a perfect solution but could be a good start point.
> 
> tried to fix next issues:
> 
> 1. Scroll while dragging
> 2. Incorrect item position when drag between vertical positioned containers
>    #15227
> 3. D&d does not work correctly when change data while dragging (drop containers and drag items)
>    #15343
> 
> feel free to fix issues found or propose better solutions
> Need to implement correct `syncItems` logic

If you put the code of your solution in a public repo on GitHub we can collaborate on it!

**Comment by elirenato** [comment] 2019-03-19 14:39
+1

**Comment by volser** [comment] 2019-03-20 11:57
pushed here https://github.com/volser/cdk-drag-scroll as is

**Comment by sgibson53** [comment] 2019-03-28 15:26
Any update on this? It's a fundamental feature for drag/drop

**Comment by DaanSchoukens** [comment] 2019-04-03 16:57
+1

**Comment by Matheusqf** [comment] 2019-04-03 17:02
+1

**Comment by Musuel** [comment] 2019-04-03 23:27
Hello,

To suit my needs, I developped a directive allowing a drop list to automatically scroll horizontally/vertically and refresh drop positions. Simply put the dropListScroller directive on the CdkDropList.
_Note that I had to use a private property of DropListRef: \_itemPositions._

Here is the stackblitz: [drop-list-scroller](https://stackblitz.com/edit/angular-9oeppz?embed=1&file=src/index.html)

Limitations: Dragging items from another list isn't supported. See @volser previous posts and interesting work. I'll try to have a look on this if I find some time.

@crisbeto Do you think it would be possible to make _itemPositions public in DropListRef ? What do you think about this kind of directive ?

**Comment by aidvb** [comment] 2019-04-04 11:11
Wonderful! When is this going to be merged?

**Comment by volser** [comment] 2019-04-04 13:15
also added a directive `vsDragScroll`


```
npm install --save cdk-drag-scroll
```
use:

```html
<div
  *ngFor="let item of items"
   cdkDrag
   vsDragScroll
   [vsDragScrollContainer]="scrollContainer"
   [cdkDragData]="item">
   ...
</div>
```

**Comment by yatz3000** [comment] 2019-04-12 13:59
Has anybody worked out a solution that does not use dragDropList? @volser 's solution looks pretty good, but my use case cannot use dragDropList.

When will this feature be merged into Angular?

**Comment by Ben5501** [comment] 2019-04-24 15:48
Hello,

has anyone an idea how to get a **reference to the dragged preview** element, when it is a copy of the original or general?

The problem I try to solve is that if you drag an element and scroll the page the drag preview 
position is not at the position where the mouse position is any more.

i.e. if I scroll the page 500px while dragging the offset between drag preview and mouse/touch point is 500px. 

My goal is to at least update the preview position after scrolling to the current mouse/touch point.

**Comment by harellevy** [comment] 2019-04-28 14:23
> also added a directive `vsDragScroll`
> https://github.com/volser/cdk-drag-scroll
> 
> ```
> npm install --save cdk-drag-scroll
> ```
> use:
> 
> ```
> <div
>   *ngFor="let item of items"
>    cdkDrag
>    vsDragScroll
>    [vsDragScrollContainer]="scrollContainer"
>    [cdkDragData]="item">
>    ...
> </div>
> ```

this would work on scrollable window? or dnd container must have overflow?

**Comment by volser** [comment] 2019-04-28 16:22
currently only container, but it easily could be adapted for window

**Comment by rajibhasan11** [comment] 2019-05-02 07:04
Hi Volser,

Using the cdk-drag-scroll making the drag item slow in our application. In the demo it is not feelable as it had a simple list.

**Comment by aidvb** [comment] 2019-05-03 07:39
What about original solution and when will it be implemented in Angular?

**Comment by alvarosaburido** [comment] 2019-05-07 15:27
I tried @volser solution and it works fine if the scrollable container with fixed height, but doesn't work for the window scroll. (I guess is not meant for that)

We have any update on an official feature, even if it's on todo list?

**Comment by harellevy** [comment] 2019-05-15 14:36
> currently only container, but it easily could be adapted for window

If you can give an example of how you'd use it or implement it with window scroll (knowing that the list might be starting at the unknown position in the scroll and not exactly starting and ending at the top or bottom of the page.)

i guess you can find the list offset from the window container and calculate it.

**Comment by daiyis** [comment] 2019-05-17 05:40
hi @volser , can this work two scroll containers? vertically in the cdkDropList and horizontally within the cdkDropListGroup (like in a trello board ).

**Comment by mxswat** [comment] 2019-05-17 15:18
+1 from Italy with love

**Comment by volser** [comment] 2019-05-19 09:57
use https://github.com/volser/cdk-drag-scroll/issues please, to discuss library related stuff

**Comment by Diemauerdk** [comment] 2019-05-20 14:07
We are waiting for a solution for this too! :)

**Comment by quikvans** [comment] 2019-05-21 15:03
+1 from Switzerland!

**Comment by vincentdsf** [comment] 2019-05-23 06:25
+1 from Berlin

**Comment by AnisTss** [comment] 2019-05-23 08:35
+1 from Tunisia

**Comment by aidvb** [comment] 2019-05-23 08:52
+1 from Lithuania.

**Comment by harellevy** [comment] 2019-05-26 00:26
+1 from Israel

**Comment by honzamelena** [comment] 2019-05-30 11:01
Hey guys, Angular 8 is out, great work! Hope it means the team is back on Angular material (or should I say Angular components).

This looks like a great opportunity to start discussing new component features (& bugs) we desperately are waiting for. This is certainly one of them. When I filter the P2 priority issues with most reactions / comments, this is the first one. 

Would be awesome to make this thread "buzzing" again.

**Comment by TrietPham96** [comment] 2019-05-31 03:22
. from VietNam

**Comment by varminas** [comment] 2019-05-31 06:09
Without this functionality our application is in certain situations unused. I have tried all the above listed workarounds, directives, etc, but scrollable elements inside window (outside container) doesn't work. So, big plus from Swiss.

**Comment by dimitrov9** [comment] 2019-05-31 09:04
+1 from North Macedonia

**Comment by Diemauerdk** [comment] 2019-05-31 10:39
@varminas I agree, we are in same situation. For now we are waiting but this is essential for us too.

**Comment by sherwopj** [comment] 2019-05-31 16:19
+1 from the Shires, UK

**Comment by TrietPham96** [comment] 2019-06-03 04:50
This works well for me, good day
https://stackblitz.com/edit/cdk-drop-list-scroll

**Comment by TrietPham96** [comment] 2019-06-03 05:02
This works well for me. Have a nice day
https://stackblitz.com/edit/cdk-drop-list-scroll

**Comment by prom00** [comment] 2019-06-03 06:07
> This works well for me. Have a nice day
> https://stackblitz.com/edit/cdk-drop-list-scroll

This doesn't scroll on the parent element(s). It scrolls inside the CDK drop list.

**Comment by sandeepsuvit** [comment] 2019-06-05 06:34
Hi i have tried using this library for my projects [ngx-smooth-dnd](https://kutlugsahin.github.io/ngx-smooth-dnd/). Work really well with dnd support and drag on scroll as-well. I have made a sample demo app here ```https://github.com/sandeepsuvit/angular-dnd-survey-creator```. Here is a working [demo](https://angular-dnd-survey-creator.netlify.com/) of the app that i created using ```ngx-smooth-dnd```. Hope this helps someone until this issue is fixed :)

**Comment by Diemauerdk** [comment] 2019-06-07 06:24
@sandeepsuvit. This seems great and it works and behaves as we also want it to.

It can probably solve some peoples scenarios but **we would still vote very high for this feature being in the angular cdk.** 

The problem is that this npm package is not that popular(maybe it will be) and is only in version 0.3.0. We have a very large application and we need bigger teams behind the npm packages.

I still don't understand why this feature is not prioritized more in the angular cdk since this small library made by 1 person can do this even before it's in version 1.x :D

**Comment by prom00** [comment] 2019-06-07 06:28
> @sandeepsuvit. This seems great and it works and behaves as we also want it to.
> 
> It can probably solve some peoples scenarios but **we would still vote very high for this feature being in the angular cdk.**
> 
> The problem is that this npm package is not that popular(maybe it will be) and is only in version 0.3.0. We have a very large application and we need bigger teams behind the npm packages.
> 
> I still don't understand why this feature is not prioritized more in the angular cdk since this small library made by 1 person can do this even before it's in version 1.x :D

This is the biggest reason why we don't use alot of "custom" modules too. They often stop getting (critical) updates after a while. We've learned it's best to go with only 100% original modules, or bigger ones, supported by Angular.

**Comment by kflo** [comment] 2019-06-10 03:50
**BUMP**

someone, please...

**Comment by woteska** [comment] 2019-06-15 22:54
Any update on this? https://github.com/angular/components/issues/14273#issuecomment-442201350

**Comment by MFStapert** [comment] 2019-06-20 21:49
Also looking forward to this feature :)

**Comment by Ninjetsu** [comment] 2019-06-21 10:08
Implemented CDK DnD and then found out this feature is missing... can we have a projection as off when this will be implemented?

**Closed** 2019-07-09 15:16 UTC
Labels: P2, has pr

**Comment by TheKeymaster** [comment] 2019-07-09 16:14
Finally, that‘s all what we‘ve been waiting for!! Great that this is fixed now.

**Comment by woteska** [comment] 2019-07-09 19:23
@crisbeto , when will it be released?

**Comment by crisbeto** [comment] 2019-07-09 19:25
It should be in 8.2.0.

**Comment by neryortez** [comment] 2019-07-16 20:22
How to make it work?
The update is released, but I cannot see anything changed.

**Comment by Achilles1515** [comment] 2019-07-17 12:01
@crisbeto Do you have a StackBlitz example showing how to use this feature? I can't seem to make it work on 8.1.1.

**Comment by crisbeto** [comment] 2019-07-17 12:03
@Achilles1515 it depends on which is your scrollable element. At the moment it's set up to only scroll the window or the list itself.

**Comment by neryortez** [comment] 2019-07-17 12:06
@crisbeto I got it working as you say: scroll just the list itself.
To make it work one has to make the list scrollable (fixed height and/or overflow set to `auto`).
Is there a way to enable scrolling also in the viewport?

**Comment by Achilles1515** [comment] 2019-07-17 12:58
@crisbeto
I also got it to work. In the gif below, is auto-scroll supposed to stop like it does when getting close to the left edge of the container? This does not happen on the right.
https://stackblitz.com/edit/angular-dggptq

![GIF](https://user-images.githubusercontent.com/23387905/61377357-09298e80-a871-11e9-8a9b-00e6bfa17475.gif)

**Comment by woteska** [comment] 2019-07-17 13:46
Unfortunately it does not work within a Material Table. :(

**Comment by rajibhasan11** [comment] 2019-07-25 09:45
Unfortunately it does not work within nested cdkDropList. In my case I need mainly vertical auto scroll. In the attached image red circled scorllbar should be scrolled automatically when I try to drop a field in a form section.

![circled_scrollbar](https://user-images.githubusercontent.com/5672879/61864355-18ed4680-aef3-11e9-9cef-f80ea5c92b21.jpg)

**Comment by digaus** [comment] 2019-07-28 22:19
Should be able to add directive to the container which we want to be able to scroll y and scroll x

**Comment by nkartchner** [comment] 2019-07-29 20:13
Trying to build a Kanban board and dragging a card won't scroll the parent container horizontally.

https://stackblitz.com/edit/angular-dbp5r5
![chrome-capture](https://user-images.githubusercontent.com/39930903/62078877-ccfc1380-b20a-11e9-8ade-49a07c11dc20.gif)

**Comment by fatmaE19** [comment] 2019-07-30 13:12
but this works only with drop list if i have a box inside a container  div when i drag the box it's container is not scrolling ! :/

**Comment by dawda92** [comment] 2019-08-15 10:44
When grabbing a scrollable item and going past the bottom of the viewport or past the top of the viewport, the browser window doesn't scroll. (the container is larger than the browser viewport.) 
Is there a way to do this? I want the same functionality but within a container that is larger than the viewport. (So that the window automatically starts scrolling up or down & no extra scroll bar, just the windows scrollbar.) 
This seems like something that should just work out of the box?

**Comment by crisbeto** [comment] 2019-08-15 10:50
That might be because the scroll regions are overlapping. I've got https://github.com/angular/components/pull/16675 to help with it.

**Comment by htreb** [comment] 2019-08-20 11:31
+1 for @nkartchner 's stakblitz example. Even if you manually scroll the board when the ticket is being dragged the drop containers do not 'register' so when they scroll into view you still can't drop the ticket on them

**Comment by healydwya** [comment] 2019-09-05 21:36
@crisbeto hi! are there plans to make this possible for mobile as well?

**Comment by crisbeto** [comment] 2019-09-05 21:52
It should work on mobile already.

**Comment by healydwya** [comment] 2019-09-09 18:39
@crisbeto it does, but only on iOS from my testing so far - were you able to test it on Android as well? Maybe it is just incompatible with my version?

**Comment by tchpowdog** [comment] 2019-09-19 00:59
Works for me but only for nearest scrollable parent it seems.  Also, is there a way to set the scroll speed?

`<div>   -- has horizontal scroll (new drag scroll feature does not work here)
    <div>    -- has vertical scroll (new drag scroll feature works here)
        <element>
    </div>
</div>`

**Comment by hb1998** [comment] 2019-09-22 07:24
> Works for me but only for nearest scrollable parent it seems. Also, is there a way to set the scroll speed?
> 
> ```
> <div>  -- has horizontal scroll (new drag scroll feature does not work here)
>     <div>    -- has vertical scroll (new drag scroll feature works here)
>         <element>  -- draggable
>     </div>
> </div>
> ```

need a way to set scroll speed, especially when the list is too long

**Comment by Anzil-Aufait** [comment] 2019-10-15 06:17
**`DND auto scroll`** is not working on **`custom scroll(ngx-scrollbar)`**.

**Comment by Mustafa-Omran** [comment] 2019-11-06 09:49
Inject Document and set id to container for all drag list items to move the horizontal scrollbar when emitting dragMove event 

`
import { DOCUMENT } from '@angular/common';
import { Inject } from '@angular/core';
`

`
  constructor(
    @Inject(DOCUMENT) private document: Document
  ) {
  }
`

`
  /**
   * 
   * @param event 
   */
  onDragMoved(event) {
    if (event.delta.x === 1) {
        this.document.getElementById('container').scrollLeft += 10;
    } else {
        this.document.getElementById('container').scrollLeft -= 10;
    }
  }
`

**Comment by SurjithP** [comment] 2019-11-19 09:28
@Mustafa-Omran  can you explain bit more ?

**Comment by KevynTD** [comment] 2019-11-24 10:31
I had made this code, but I just found that it works if updating haha
It works only with overflow:hidden case.

I will stay here if anyone wants to do this in older versions.

This is an object that you place in the document where dragMoved is in function, and call part of it inside dragMoved to work:

`	//AUTOSCROLL IMPLEMENTATION
	autoScrollSetup = {
		isOnEdge:false,
		itsStarted:false,
		scroll(side:any,elContainer:any,everyXms:any,stepPx:any,direction:any):any{
			if(this.isOnEdge){ // Mouse in the edge enough to scroll?
				if(!this.itsStarted){ // Event already started?
					this.itsStarted = true;

					// Check the direction
					let elScroll:any;elScroll;
					if(direction==="horizontal"){
						elScroll = "scrollLeft";
					}
					else
					if(direction==="vertical"){
						elScroll = "scrollTop";
					}

					// Runs from time to time
					setTimeout(() => {
						if(side==="leftOrTop")     {elContainer![elScroll] -= stepPx} // It's on the left side (if it's horizontal) or top (if it's vertical) ?
						else
						if(side==="rightOrBottom") {elContainer![elScroll] += stepPx} // It's on the right side (if it's horizontal) or bottom (if it's vertical) ?
						this.itsStarted = false;	// Finish
						this.scroll(side,elContainer,everyXms,stepPx,direction); // Rerun
					}, everyXms);
				}
			}
		},
		autoScroll(objConfig:any){
			// Set default values
			var {event,lateralTolerancePx=40,stepPx=5,everyXms=30,direction='horizontal'} = objConfig;
			
			// Get element Container and this position
			var elContainer = event.source.dropContainer.element.nativeElement;
			var elContainerBCR = elContainer!.getBoundingClientRect();

			// Check direction
			let elContainer1:any;
			let elContainer2:any;
			let xy:any;
			if(direction==="horizontal"){
				elContainer1 = elContainerBCR.left;
				elContainer2 = elContainerBCR.right;
				xy = 'x';
			}
			else
			if(direction==="vertical"){
				elContainer1 = elContainerBCR.top;
				elContainer2 = elContainerBCR.bottom;
				xy = 'y';
			}

			if(event.pointerPosition[xy] <= elContainer1+lateralTolerancePx){ // Is mouse position left/top enough to start scrolling?
				this.isOnEdge = true;
				this.scroll("leftOrTop",elContainer,everyXms,stepPx,direction);
			}
			else if(event.pointerPosition[xy] >= elContainer2-lateralTolerancePx){ // Is mouse position right/bottom enough to start scrolling?
				this.isOnEdge = true;
				this.scroll("rightOrBottom",elContainer,everyXms,stepPx,direction);
			}
			else{
				this.isOnEdge = false;
			}
		}
	}`

Inside dragMoved:
`	dragMoved(event: CdkDragMove<string[]>){
//Auto Scroll: event*(required), direction(horizontal or vertical), lateralTolerancePx, stepPx, everyXms
			this.autoScrollSetup.autoScroll({'event':event,'direction':'horizontal'})
	}`

besides calling dragMoved inside each list element.
It worked well with me and I tried to make it very easy to deploy.

**Comment by Mustafa-Omran** [comment] 2019-11-25 12:05
> @Mustafa-Omran can you explain bit more ?

> HTML

`<div class="container" id="container">
    <h4 class="title">Itmes</h4>
    <div class="overflow-container" cdkDropList (cdkDropListDropped)="onDropItem($event)" [cdkDropListData]="items">
        <ul *ngFor="let item of items" class="item" [cdkDragData]="item" cdkDrag
            (cdkDragMoved)="onDragMoved($event)">
            <app-item [item]="item">
            </app-item>
        </ul>
    </div>
</div>`

> TS
`onDragMoved(event) {
    if (event.delta.x === 1) {
        this.document.getElementById('container').scrollLeft += 10;
    } else {
        this.document.getElementById('container').scrollLeft -= 10;
    }
}`

**Comment by Mustafa-Omran** [comment] 2019-11-25 12:08
> @Mustafa-Omran can you explain bit more ?

**HTML**

`<div class="container" id="container">
    <h4 class="title">Itmes</h4>
    <div class="overflow-container" cdkDropList (cdkDropListDropped)="onDropItem($event)" 
        [cdkDropListData]="items">
        <ul *ngFor="let item of items" class="item" [cdkDragData]="item" cdkDrag
            (cdkDragMoved)="onDragMoved($event)">
            <app-item [item]="item">
            </app-item>
        </ul>
    </div>
</div>`
**TS**

`onDragMoved(event) {
    if (event.delta.x === 1) {
        this.document.getElementById('container').scrollLeft += 10;
    } else {
        this.document.getElementById('container').scrollLeft -= 10;
    }
}`

**Comment by andreypelykh** [comment] 2019-12-19 07:55
@Mustafa-Omran 
_cdkDragMove_ instead of _cdkDragMove_**d** event.

**Comment by crisbeto** [comment] 2020-01-01 14:11
#18082 will allow for elements that aren't the list or the viewport to be scrolled.
