### ISSUE TITLE
bug(DragAndDrop): Not working with row wrap

### ISSUE THREAD

**Issue by Dreathorian** [angular/components#24709] opened 2022-03-31 00:13 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

the list bugs out

### Reproduction

Steps to reproduce:
1. 
2.
https://stackblitz.com/edit/angular-isjqv6-31dqhl?file=src/app/cdk-drag-drop-horizontal-sorting-example.css

### Expected Behavior

position gets calculated and previewed properly horizontally and vertically

### Actual Behavior

chips move around erraitcally and item is placed by good luck

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2022-03-31 05:36
Duplicate of https://github.com/angular/components/issues/13372.

**Closed by crisbeto** 2022-03-31 05:36 UTC
Labels: needs triage
