### ISSUE TITLE
bug(Autocomplete): does not lock scroll other than to its panel if opened

### ISSUE THREAD

**Issue by RobinKamps** [angular/components#26048] opened 2022-11-21 22:39 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

This may sound familiar as it is a long known issue - but perhaps with a new suggestion how to fix it. 

The autocomplete panel position is bound to body/html scroll events for performance reasons. 
However adding `cdkScrollable` on a parent scrollable div can fix the issue (may result in performance loss/flickering).
But even if the autocomplete is in a scrollable scope the scrolling may lead to bad side effects (z-index, etc.): e.g. the demo for 15.0.0: 
![image](https://user-images.githubusercontent.com/27373333/203170482-79349e0c-b28e-448b-9b44-c5acdf5a2603.png)

Since all other components (menu, select etc.) lock the scrolling of the body/underlaying scroll div, when opened - the same user experience for the autocomplete panel would be great.

### Reproduction

Steps to reproduce:
1. https://material.angular.io/components/autocomplete/examples -> open panel and scroll
2. https://material.angular.io/components/select/examples -> open panel and scroll

### Expected Behavior

autocomplete should have a similar scrolling behaviour as other components

### Actual Behavior

autocomplete does not prevent scrolling the underlying element

### Environment

- Angular: 15
- CDK/Material: 15

**Comment by AurelienLoyer** [comment] 2022-12-02 17:15
Same issue here, looking for a solution 😢
![Dec-02-2022 18-14-32](https://user-images.githubusercontent.com/3717296/205348346-f8b027e1-bbda-4dfc-a993-9f13b3ee547c.gif)

**Comment by amysorto** [comment] 2023-05-19 21:42
Duplicate of #26484

**Closed by amysorto** 2023-05-19 21:42 UTC
Labels: needs triage
