### ISSUE TITLE
bug(MatDialogTitle): Whitespace rendered when content of enclosing tag is wrapped

### ISSUE THREAD

**Issue by Ollitod** [angular/components#26896] opened 2023-04-07 13:23 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

We basically wrap the content of every tag in our source code. After upgrading Material to v15, we noticed that the whitespaces which are rendered around the content of an element annotated with mat-dialog-title are also visible on the UI. This was not the case in Material v14. In both versions when inspecting the DOM, you can see that whitespaces are visible around the text. The following example illustrates the problem:

This ...
```
<h2 mat-dialog-title>
  Text content
</h2>
```

... will be rendered as " Text content " in the DOM.

In Material v14 these whitespaces were simply ignored in by the MatDialogTitle, but since v15 they are actually visible on the UI as described above.

Material v14:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/50339686/230615884-d14ea354-3a5c-4b30-a024-d1ec26c4de97.png">

Material v15:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/50339686/230616041-836a79fa-8a62-49dd-b4f7-2585662334e9.png">

### Reproduction

Steps to reproduce:
1. Wrap content of a tag annotated with mat-dialog-title
2. Inspect the DOM in the browser (Chrome)
3. See the rendered whitespace in front of the text

### Expected Behavior

The whitespaces are ignored by MatDialogTitle

### Actual Behavior

The whitespaces are visible on the UI like " Text content "

### Environment

- Angular: 15.2.4
- CDK/Material: 15.2.4
- Browser(s): Chrome (110.0.5481.177 (Offizieller Build) (x86_64))
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Ventura

**Comment by crisbeto** [comment] 2023-05-03 17:59
Duplicate of https://github.com/angular/components/issues/26539.

**Closed by crisbeto** 2023-05-03 17:59 UTC
Labels: needs triage
