### ISSUE TITLE
bug(DatePicker): Not working with [(ngModel)] anymore

### ISSUE THREAD

**Issue by leonandroid** [angular/components#27308] opened 2023-06-14 23:55 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

11.2.12

### Description

When using Angular Material Datepicker with model (using ngModel) the values are not set in the variable when the date is finally picked.

Using the code in the example, I added the ngModel:
```

<mat-form-field>
  <mat-label>Choose a date</mat-label>
  <input matInput [matDatepicker]="picker" [(ngModel)]="someDate">
  <mat-hint>MM/DD/YYYY</mat-hint>
  <mat-datepicker-toggle matIconSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
```

The someDate value will never have the value from the picker after it is chosen.
The same code works fine in previous versions of Angular Material.

btw, the workaround I came up is this:
Replace `[(ngModel)]="someDate"` with
```
[value]="someDate"
(dateChange)="someValue = $event. Value"
```

### Reproduction

Steps to reproduce:
1. Create an example with the code provided, using datepicker
2. Add a variable to bind it to ngModel
3. Pick a date
4. Inspect the variable

### Expected Behavior

The variable should have the value from the picker.

### Actual Behavior

The variable is empty.

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chromium
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by wartab** [comment] 2023-06-15 07:42
You should provide a minimal reproduction of your issue, because it's not actually broken as can be seen here:
https://stackblitz.com/edit/components-issue-v18atm?file=src%2Fapp%2Fexample-component.ts,src%2Fapp%2Fexample-component.html

**Comment by mmalerba** [comment] 2023-06-15 16:42
@wartab thanks for creating the stackblitz, closing since it appears to be working

**Closed by mmalerba** 2023-06-15 16:42 UTC
Labels: needs triage
