### ISSUE TITLE
bug(mat-select): mat-select-trigger disappeared if no mat-option to iterate

### ISSUE THREAD

**Issue by akaNightmare** [angular/components#27754] opened 2023-09-01 14:52 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello,
when implementing the loaded list, I'm facing situation that when some options were already selected and then filtered, the mat-select-trigger disappears, although the control that is responsible for storing data is available and has the selected data options.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-mat-select-hide-placeholder-if-value-exis-a4qafe?file=src%2Fapp%2Fselect-custom-trigger-example.html
Steps to reproduce:
1. Add few toppings
2. Make sure that the selected toppings are selected and displayed as expected
3. Type any (3-4) chars in "Search toppings" to filter toppings list

### Expected Behavior

Selected value(s) MUST NOT be disappeared

### Actual Behavior

Selected value(s) disappeared (_toppings_ still have selected values as expected)

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2023-09-08 11:46
I couldn't reproduce it in the demo. I tried selecting "Onion", "Sausage" and "Pepperoni" and typing in the input field, and the select was preserving the selected value.

**Comment by akaNightmare** [comment] 2023-09-08 13:53
@crisbeto 
![image](https://github.com/angular/components/assets/4151616/03b6b27b-084c-4234-9dae-cc758a792f27)

**Comment by crisbeto** [comment] 2023-09-08 14:17
That's because you're filtering out the options. `mat-select` only shows options that are present in the DOM. Closing since it's working as expected.

**Closed by crisbeto** 2023-09-08 14:17 UTC
Labels: needs triage

**Comment by JWess** [comment] 2023-09-08 14:50
> That's because you're filtering out the options. `mat-select` only shows options that are present in the DOM. Closing since it's working as expected.

This implementation is not ideal, as it prohibits a couple important features inside mat-selects:

- If I want to use CDK virtual scroll for the options in my <mat-select>, the selections don't show up in mat-select-trigger if their <mat-option> doesn't fall in the displayed portion of the <mat-option>'s.
- If I want to have any sort of search/filter box inside my <mat-select> panel, the same issue exists

**Comment by akaNightmare** [comment] 2023-09-08 21:10
@crisbeto values already exist in model/formcontlrol, and it can be displayed, no matter which options are available or not.
It's completely different things...

**Comment by crisbeto** [comment] 2023-09-08 21:18
`mat-select` isn't really set up for filtering at the moment, because that's a completely different ARIA pattern and we generally build components around their accessibility story. As for virtual scrolling, it's something we have in the backlog: https://github.com/angular/components/issues/10122
