### ISSUE TITLE
bug(mat-menu): Don't focus first element on open menu programmatically.

### ISSUE THREAD

**Issue by infacto** [angular/components#25869] opened 2022-10-26 16:23 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

![demo](https://user-images.githubusercontent.com/60390085/198079674-df9a8625-2910-40f2-bdb8-5c92153b1f5a.gif)

Ref. #15936 (closed but not accepted.) Allow an option for this if you insist. You can focus the mat-menu without focus an item.

### Reproduction

Steps to reproduce:
1. Create mat-menu.
2. Open it in ts file with ViewChild on MatMenuTrigger.

[Demo](https://stackblitz.com/edit/angular-cxsudr-ebngfx?file=app/nested-menu-example.html)

### Expected Behavior

Never focus an item on menu open. There is no primary item we want. You can always use the keyboard to focus. There is no need to focus an item. And if you really want it, why are no items focused when open via button matMenuTriggerFor? The first focused item looks ugly and confused the user.

### Actual Behavior

When I click on a `button` with `matMenuTriggerFor` the menu opens without any item is focused. Great.
But if I open the same menu via the MatMenuTrigger from ts-file (`openMenu`), the first item is focused.

### Environment

- Angular: 14
- CDK/Material: 14
- Browser(s): Chrome 106
- Operating System: Windows 10

**Comment by zarend** [comment] 2022-10-27 16:23
Hello @infacto ,

This is a duplicate of #15936, which was already closed. That's because ARIA requires focusing the first menu item when opening. I checked the [ARIA WAI best practices for menu interaction pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menu/) again:

> When a menu opens, or when a menubar receives focus, keyboard focus is placed on the first item.

We're required to follow ARIA, and there is no requirement to not focus anything when the menu opens. For that reason, this is working as intended.

We hope the menu meets your needs. If you have specific requirements that are not satisfied, considering using the select component or a CDK primitive and building your own custom menu.

Please do not open another issue for this. If you believe this is closed in error, you can create a discussion and we can reconsider if there is enough feedback from the community.

-Zach

**Closed by zarend** 2022-10-27 16:23 UTC
Labels: needs triage
