### ISSUE TITLE
Time Picker

### ISSUE THREAD

**Issue by MohamedAymenHADDAD** [angular/components#16496] opened 2019-07-11 09:12 UTC
The Angular Material Library provides a DatePicker, but still missing a TimePicker.
Is there any plans to have this component soon ?

**Comment by Vorlif** [comment] 2019-07-11 18:18
Duplicate of #5648. Look in the issue. There are alternatives.

**Comment by jelbourn** [comment] 2019-07-11 23:20
Duplicate of #5648

**Closed by jelbourn** 2019-07-11 23:20 UTC
Labels: feature
