### ISSUE TITLE
md-button-toggle [checked] input doesn't work when we click inside the tag class "label-content"

### ISSUE THREAD

**Issue by dimitribocquet** [angular/components#5256] opened 2017-06-20 18:09 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When we click inside a "md-button-toggle" element, the [checked] input should be done, regardless the position where we click.

#### What is the current behavior?
If we click inside the "label-content", the [checked] input doesn't change. But if we click outside (between "md-button-toggle" tag and "label-content"), it works. 

#### What are the steps to reproduce?

[Here my plunker](http://plnkr.co/edit/CcPgMpI8mpYYTy8Aqbya?p=preview). Click on the green area to see when it works, then click on the red area to see when it fails.

**Comment by dimitribocquet** [comment] 2018-03-13 21:34
Still have this bug, with version 5.2.2

**Comment by crisbeto** [comment] 2021-04-23 14:06
I wasn't able to reproduce it with the latest version. Closing since this hasn't had any activity in a while.

**Closed by crisbeto** 2021-04-23 14:06 UTC
Labels: P3, area: material/button-toggle
