### ISSUE TITLE
Datepicker doesn't clear input when it has an invalid value

### ISSUE THREAD

**Issue by Lertis** [angular/components#22209] opened 2021-03-12 10:07 UTC
#### Repo

Here is a StackBlitz with a min required code:
https://stackblitz.com/edit/angular-mat-datepicker-clear-input-uzdtjz?file=app/datepicker-overview-example.ts

--- 

**Case №1:**

Steps to reproduce:
1. Insert "a1" into an input field
2. Click the X button to clear.
 
#### Expected Behavior
Expect: to see an empty field with a placeholder.

#### Actual Behavior
Actual: an empty field with a placeholder.

![#92f792](https://via.placeholder.com/15/92f792/000000?text=+)  **Passed** 

--- 
**Case №2:**

Steps to reproduce:
1. Insert "1" into an input field
2. Click the X button to clear.
 
#### Expected Behavior
Expect: to see an empty field with a placeholder.

#### Actual Behavior
Actual: for a moment input field displays the 1/1/2001 date and then we are able to see an empty field with a placeholder.

![#fa7373](https://via.placeholder.com/15/fa7373/000000?text=+)  **Failed** 

--- 
#### Additional Information
If there any issue with input values into a field - refresh a page.
![image](https://user-images.githubusercontent.com/24374130/110925120-7c77f200-832b-11eb-81b9-68b44bb48fec.png)

#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by crisbeto** [comment] 2021-07-06 20:12
I was looking into this and I think that it has nothing to do with Material. The problem is that you try to clear the value by assigning `null`, but if the value is already `null`, change detection won't pick it up and notify the datepicker. If you switch between `null` and `undefined` it works. https://stackblitz.com/edit/angular-mat-datepicker-clear-input-jv7267?file=app%2Fdatepicker-overview-example.ts

Closing the issue since we can't do much about it.

**Closed by crisbeto** 2021-07-06 20:12 UTC
Labels: P3, area: material/datepicker

**Comment by Lertis** [comment] 2021-07-07 07:03
@crisbeto the field value isn't the same as the date picker value?

**Comment by crisbeto** [comment] 2021-07-07 07:10
The value only gets assigned to the datepicker's model if it's a valid date. E.g. `a1` and `a2` both get assigned as `null`, because they're invalid.
