### ISSUE TITLE
bug(MatSlider): Thumb label behaviour is inconsistent across different browsers

### ISSUE THREAD

**Issue by alexander-goncharuk** [angular/components#26472] opened 2023-01-23 13:28 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In Chrome selecting a value on the slider label stays there until the selected mark is focused (until you click outside). 
In Safari the label shown for a fraction of second (arguably for not long enough to read the content) and disappears. You need to hold the mouse to keep it displayed. 

Slider has changed significantly in version 15 so I'm not sure if this should be considered a regression.

### Reproduction

Steps to reproduce:
1. Just open this example from the Slider Showroom https://material.angular.io/components/slider/overview#formatting-the-thumb-label in both Chrome and Safari
2. Try clicking on the slider marks and observe the difference 

### Expected Behavior

Label behaviour is consistent across popular browsers.

### Actual Behavior

Label behaviour is inconsistent.

### Environment

Angular: 15.0.4
CDK/Material: 15.1.1
Browser(s): Chrome 109.0.5414.87, Safari 15.4
Operating System: macOS

**Comment by crisbeto** [comment] 2023-01-24 09:05
I looked into it briefly, but couldn't find an easy workaround. The problem is that we rely on the focused state of the underlying native `input` to know if the slider has focus, but Safari doesn't allow focus to land on an `input[type="range"]`. See https://stackoverflow.com/questions/68731734/is-there-a-way-to-make-an-html5-input-range-receive-focus-in-safari-when-its-us

**Comment by wagnermaciel** [comment] 2023-03-03 17:13
@crisbeto you correct. Using the native `input[type="range"]` under the hood means we inherit all of the inconsistencies between browser implementations. Do you feel this something we should try to reconcile?

**Comment by wagnermaciel** [comment] 2023-08-28 00:37
After discussing with the team, we've decided to close this issue. I will do my best to outline why here

The mat-slider label is meant to be visible when the slider is in an `active`, `pressed`, or `focused` state. The first problem is that the slider is working as intended, in that it is showing/hiding the slider label based on the `input` state as described by the material design spec. The divergence in behavior comes from the fact that, as @crisbeto mentioned, the focus state of the native `input` on Safari does not allow focus to land on an `input [type="range"]`. The second problem is, if we want to try and change this on our end would require implementing our own fake "focus" state inside of the slider which would end up being a hacky mess

**Closed by wagnermaciel** 2023-08-28 00:37 UTC
Labels: P3, needs: discussion, area: material/slider

**Comment by alexander-goncharuk** [comment] 2023-08-30 07:55
Ok thanks for the explanation. Sad to realize, but I get the rationale behind your decision.
