### ISSUE TITLE
Exiting Menu Component via screen-reader for iOS jumps user to top/bottom of page

### ISSUE THREAD

**Issue by naomicarroll** [angular/components#17951] opened 2019-12-12 15:24 UTC
#### Reproduction

Issue is easily reproducible in the Angular Material documentation using iOS VoiceOver: https://material.angular.io/components/menu/overview

Steps to reproduce:
1. Navigate to https://material.angular.io/components/menu/overview using an iOS device with the VoiceOver native screen reader enabled.
2. Swipe-navigate to the component example for the Menu (see screenshot at end of section).
3. Double-tap to activate and open menu - focus will move to first item of the menu (on occasion, the menu immediately closes instead).
4a. Swipe back once to navigate back out of the menu - observe that focus is moved to the bottom of the DOM.
4b. OR swipe forward twice to navigate past the last menu item to move past menu to next part of the document - observe that focus is instead directed to the top of the DOM.

![image](https://user-images.githubusercontent.com/1666565/70722343-1b471600-1cc5-11ea-805c-8391b4ffddab.png) 
 
#### Expected Behavior

What behavior were you expecting to see?
1. Swipe-navigating back out of the menu should allow a user to either navigate back to the menu button they activated, or focus should select the menu element, which can close on double tap as the menu functions using Android TalkBack.
2. Swipe-navigating past the last item of the menu should move the user's focus to the next element in the DOM past the original menu item.

#### Actual Behavior

What behavior did you actually see?
When opening the Menu Component using iOS VoiceOver, the only means of navigating away from the menu are:
1. Navigate to the top of the DOM
2. Navigate to the bottom of the DOM
3. Tap off the menu to select another part of the document (users who depend on screen readers would lose place in document)

#### Environment

- Angular: 8.2.14 (assuming this is what is used on the Angular Material documentation)
- CDK/Material: 8.2.3
- Browser(s): Chrome 79.0.3945.73 for iOS, Safari 13 for iOS
- Operating System (e.g. Windows, macOS, Ubuntu): iOS 13.3

#### Technical Notes
This is due to the menu being generated dynamically at the bottom of the DOM, instead of placement relative to the host element. This interrupts normal tab flow throughout the document, which would create confusion for users.

Possible solutions would be to implement the same functionality seen using Android TalkBack (menu element as a whole is selectable when swiping back, and closable on double-tap), or to relocate the menu's generation to be relative to the host menu button.

**Comment by jelbourn** [comment] 2020-05-29 01:57
Duplicate of #19253

**Closed by jelbourn** 2020-05-29 01:57 UTC
Labels: needs triage
