### ISSUE TITLE
bug(MatDialogClose): Focus Restoration does not work correctly

### ISSUE THREAD

**Issue by alEX860111** [angular/components#21675] opened 2021-01-22 09:33 UTC
#### Reproduction

- https://stackblitz.com/angular/byebkkagkor?file=src%2Fapp%2Fdialog-overview-example.ts

Steps to reproduce:
1. Open the dialog by clicking "Pick one" button
2. Close the dialog by clicking "Ok" button
 
 
#### Expected Behavior

The "Pick one" button should have "focused" styling after the dialog is closed.

#### Actual Behavior

The "Pick one" button does not have "focused" styling after the dialog is closed, although the button seems to be focused technically.

#### More Information

When closing the dialog by pressing the "No Thanks" button, the "Pick one" button has the correct styling.

The "Ok" button uses the MatDialogClose directive, whereas the "No Thanks" button uses the MatDialogRef to close the dialog.

Why is the behavior different?

#### Environment

- Angular: 11.1.0
- CDK/Material: 11.1.0
- Browser(s): Chrome 87.0.4280.141
- Operating System Windows 10

**Comment by crisbeto** [comment] 2021-01-22 10:14
We restore focus depending on how you closed the dialog and we usually don't show the focus styling when focus was received using the mouse. You should be able to see it if you close the dialog using your keyboard.

**Comment by alEX860111** [comment] 2021-01-22 12:13
But why does it make a difference whether you close the dialog using the MatDialogClose directive or using the close-Method on the MatDialogRef? I would expect the same visual behaviour.

**Comment by crisbeto** [comment] 2021-01-25 16:37
It's because we can detect within the `MatDialogClose` how it was closed, whereas the `close` method falls back to the default. Here's where the detection happens: https://github.com/angular/components/blob/master/src/material/dialog/dialog-content-directives.ts#L80

I'd say that this is working as expected, but we could provide a way of specifying the close focus origin.

**Comment by jelbourn** [comment] 2021-07-22 17:19
Closing this as working as intended- our focus treatment works similarly to the native `:focus-visible` behavior

**Closed by jelbourn** 2021-07-22 17:19 UTC
Labels: P4, area: material/dialog, feature
