### ISSUE TITLE
bug(material): Angular 10 - Columns cannot be dragged and dropped in Material Table anymore

### ISSUE THREAD

**Issue by jornfranke** [angular/components#20495] opened 2020-09-03 21:56 UTC
#### Reproduction

Steps to reproduce:
1.  In Angular 7 one can make the columns of a material table drag and drop-able to change their display order: https://stackblitz.com/edit/angular-mat-table-columns-draggable
This works fine in Angular 7
2.  In Angular 10 the approach does not work anymore:
https://stackblitz.com/edit/angular-jnnkb2?file=src%2Fapp%2Ftable-basic-example.ts
3. It seems that in Angular 10 for some reason the drop event is not triggered anymore (the drag event is triggered)
 
 
#### Expected Behavior

What behavior were you expecting to see?
I expect to see the same behavior as in the Angular 7 example. Columns can be dragged and dropped to change their order in the table.

#### Actual Behavior

What behavior did you actually see?
The columns can be dragged in Angular 10, but the drop event is never triggered. This means the logic to reorder the columns in a table is not triggered and thus their order is not changed. Even worse, the column header seem to hang around somewhere.

#### Environment

- Angular: 10.1
- CDK/Material: 10.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows, Macos. Ubuntu not tested

**Comment by Kotlin-Native** [comment] 2020-09-05 19:08
duplicated: https://github.com/angular/components/issues/19924

**Comment by crisbeto** [comment] 2020-09-06 07:19
Closing as a duplicate of #19924.

**Closed by crisbeto** 2020-09-06 07:19 UTC
Labels: needs triage
