### ISSUE TITLE
Chips Autocomplete not working properly

### ISSUE THREAD

**Issue by ayushsultania** [angular/components#16024] opened 2019-05-14 10:54 UTC
#### What is the expected behavior?
When we select first value from drop down list. The list should automatically populate again until we click outside.

#### What is the current behavior?
When we select first value from drop down list, drop down doesn't appear again even after clicking again. But when we click outside and come again or we change focus by clicking the already selected items, drop down start appearing.

#### What are the steps to reproduce?
StackBlitz starter: https://stackblitz.com/angular/galmvmeklqe?file=app%2Fchips-autocomplete-example.ts
step 1: data = ['Apple', 'Lemon', 'Lime', 'Orange', 'Strawberry'];
Step 2 : select any data from drop down
Step 3 : click or type something inside same scope
Step 4 : click outside or click selected chip and then back, drop down appears.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material: ^7.3.7

#### Is there anything else we should know?
Please respond soon.

**Comment by jelbourn** [comment] 2019-05-14 21:39
Duplicate of #15899

**Closed by jelbourn** 2019-05-14 21:39 UTC

**Comment by ayushsultania** [comment] 2019-05-15 04:26
No my query is different. Please read completely.
