### ISSUE TITLE
mat-select: panel is partially off screen making some options unselectable (mobile)

### ISSUE THREAD

**Issue by tanner-wisniewski** [angular/components#17191] opened 2019-09-24 14:22 UTC
#### Reproduction

Steps to reproduce:
1. Create a mat-select with a dozen or so options
2. View page on mobile device in landscape
3. Open mat-select
4. Try to select the last option without first selecting another option.
 
A StackBlitz with the issue can be found [here](https://angular-pf1cch.stackblitz.io) ([source](https://stackblitz.com/edit/angular-pf1cch)).  If you view it the page on an iPhone X or other similarly sized phone in landscape, the 12th option is not selectable without first selecting a different option. 

#### Expected Behavior

If there is not enough space for the panel, it should either move up or shrink so that all options are able to be scrolled onto the screen

#### Actual Behavior

In some cases, on short screens such as smaller phones in landscape, the panel for mat-select can shift such that either the top or the bottom of the panel is off screen.  This prevents users from selecting the first or last option of the list. 

#### Environment

- Angular: 8.2.7
- CDK/Material: 8.2
- Browser(s): Chrome 78/Safari on iOS 12
- Operating System (e.g. Windows, macOS, Ubuntu): iOS12 , Windows 10, Android 10

**Comment by egdraper** [comment] 2020-02-21 23:10
I am seeing the same issue. We have struggled to find a CSS workaround. Does anyone have a suggestion?

**Comment by jelbourn** [comment] 2020-05-28 21:27
(revisiting older issues as part of a triaging fix-it)

I can confirm that this happens when the screen height is _very_ small (on a desktop browser), though not for any real-life devices. It's caused by the select's unique positioning that puts the selected item in the overlay over the matching text in the trigger, which is overriding the overlay's normal mechanism for keeping the panel on-screen. This should get fixed when we build an MDC-web version of the select, which won't have this same overlay positioning behavior.

**Comment by rbalet** [comment] 2020-10-15 08:27
On my `2560x1440` screen device, it still happen when I have a `mat-select` within a `MatDialog`

**Comment by buddamus** [comment] 2021-08-16 20:39
What worked for me was limiting the height of div that enclosed the options.

Try putting the following in styles.scss (**it won't work** in the component .scss file)
`div[role="listbox"]{
    max-height: 65vh !important;
}`

**Comment by amysorto** [comment] 2024-05-07 18:51
Fixed in the MDC based components (now the default)

**Closed by amysorto** 2024-05-07 18:51 UTC
Labels: P4, area: material/select, Fixed in MDC
