### ISSUE TITLE
cdk  drag drop `@output(cdkDropListDropped)`  does not give correct current and previous Index when used on transculded element.

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/components#16533] opened 2019-07-16 11:35 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-tcsq7s
or
**This is alternate solution but still not working , even though it is generating correct DOM structuring**
https://stackblitz.com/edit/angular-tcsq7s-tpjwcm
Steps to reproduce:
1. Drag one country  let say `Sri Lanka` and drop at index 1 
2.  Now again drag `Sri Lanka` and drop at index 4. it does not work and place the `Sri Lanka` at index 4.

@output() cdkDropListDropped does not give correct index for source and target.
Only it works first time and then it does not give correct index.
 
 
#### Expected Behavior

What behavior were you expecting to see?
It `(@output() cdkDropListDropped )` should give correct index and drop at desired location

#### Actual Behavior

What behavior did you actually see?
`(@output() cdkDropListDropped )` should not give correct index and does not drop at desired location after first attempt.

#### Environment

- Angular: 8.1.1
- CDK/Material: 8.0.2
- Browser(s): chrome Version 75.0.3770.100 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 7

**Comment by sandeeppatidar30** [comment] 2019-07-24 11:49
Any update on this issue?

**Comment by crisbeto** [comment] 2020-07-05 10:30
I can't reproduce it against the latest version https://stackblitz.com/edit/angular-tcsq7s-vpf244. Closing.

**Closed by crisbeto** 2020-07-05 10:30 UTC
Labels: P3, area: cdk/drag-drop
