### ISSUE TITLE
material tooltips reposition issue

### ISSUE THREAD

**Issue by markkoo** [angular/components#16489] opened 2019-07-10 04:43 UTC
#### Reproduction
[https://stackblitz.com/github/markkoo/material-tooltips-reposition-issue](https://stackblitz.com/github/markkoo/material-tooltips-reposition-issue)

Steps to reproduce:
![gif](https://user-images.githubusercontent.com/4880701/60939907-1e9c3700-a30c-11e9-92e2-34f5c480d4b0.gif)

open tooltips then scroll down, the position will change from right to left, it should remain on the right side.
 
#### Expected Behavior
It should remain on the right side.

#### Actual Behavior
It display on left side.

#### Environment
- Angular: 8.1.0
- CDK/Material: 8.1.0
- Browser(s): chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

Remark
After i check in source code, I found that 
In file flexible-connected-position-strategy.ts
```
// If the current preferred position does not fit on the screen, remember the position
// if it has more visible area on-screen than we've seen and move onto the next preferred
// position.
if (!fallback || fallback.overlayFit.visibleArea < overlayFit.visibleArea) {
   fallback = {overlayFit, overlayPoint, originPoint, position: pos, overlayRect};
}
```

main = right
fallback = left
When the main visibleArea less that fallback visibleArea, the fallback will be used.
When the tooltip start, the main visibleArea is bigger than fallback visibleArea (so the main show), but when we scroll down until both side invisible, both visibleArea will become negative and the fallback visibleArea is less than main visibleArea. (so the fallback show)

The visibleArea calc by this function
```
// Calculate how well the overlay would fit into the viewport with this point.
    let overlayFit = this._getOverlayFit(overlayPoint, overlayRect, viewportRect, pos);
```

```
/** Gets how well an overlay at the given point will fit within the viewport. */
  private _getOverlayFit(point: Point, overlay: ClientRect, viewport: ClientRect,
    position: ConnectedPosition): OverlayFit {

    let {x, y} = point;
    let offsetX = this._getOffset(position, 'x');
    let offsetY = this._getOffset(position, 'y');

    // Account for the offsets since they could push the overlay out of the viewport.
    if (offsetX) {
      x += offsetX;
    }

    if (offsetY) {
      y += offsetY;
    }

    // How much the overlay would overflow at this position, on each side.
    let leftOverflow = 0 - x;
    let rightOverflow = (x + overlay.width) - viewport.width;
    let topOverflow = 0 - y;
    let bottomOverflow = (y + overlay.height) - viewport.height;

    // Visible parts of the element on each axis.
    let visibleWidth = this._subtractOverflows(overlay.width, leftOverflow, rightOverflow);
    let visibleHeight = this._subtractOverflows(overlay.height, topOverflow, bottomOverflow);
    let visibleArea = visibleWidth * visibleHeight;

    return {
      visibleArea,
      isCompletelyWithinViewport: (overlay.width * overlay.height) === visibleArea,
      fitsInViewportVertically: visibleHeight === overlay.height,
      fitsInViewportHorizontally: visibleWidth == overlay.width,
    };
  }
```

My suggestion
I think visibleArea should not be negatif when both prefered position are negative, the last position should be use, then if no last position, the primary position should be use

**Comment by jelbourn** [comment] 2019-07-11 23:22
Duplicate of #16220

**Closed by jelbourn** 2019-07-11 23:22 UTC

**Comment by markkoo** [comment] 2019-07-13 00:44
Are the tooltip should hide when origin element scroll over the viewport, i got it.

**Comment by keatkeat87** [comment] 2019-07-15 23:45
@jelbourn  This is not just a problem with tooltips (this is Overlay issue, not duplicate of #16220 ), The point is that when you use "withPush", the scroll position should not change to the wrong position. 
please check with above source code, the calculation way causes problem.
