### ISSUE TITLE
bug([mat-menu]): screenreader navigation order not logical

### ISSUE THREAD

**Issue by soshochang** [angular/components#19253] opened 2020-05-04 19:18 UTC
#### Reproduction
Stackblitz: https://angular-mat-menu-screen-reader.stackblitz.io
Editor: https://stackblitz.com/edit/angular-mat-menu-screen-reader

This behavior also exists on the angular material website:
https://material.angular.io/components/menu/overview

Steps to reproduce:
*must navigate with VO commands to reproduce, not keyboard tab
1. turn on mac voiceover (system preferences -> accessibility -> voiceover --> enable voiceover) 
2.  > at url above use voiceover to navigate to the menu button
> select the menu button 
> navigate to next element
(you will traverse to the heading "Fruit" instead of the menu item)

*Voiceover command == VO == caps lock key or control + option by default
VO + shift +  down arrow == enter the element to navigate children of element
VO + space == select the element
VO + left/right arrow == navigate to prev/next element

#### Expected Behavior

What behavior were you expecting to see?
-after selecting the menu button, VO should take us to the first menu-item element
#### Actual Behavior

What behavior did you actually see?
-instead you move to the next dom element, in this case the the "Fruit" header.
If you continue to navigate the remaining elements, you will eventually get to the menu-items at the bottom of the page, indicating that they are at the end of the DOM rather than being inserted directly after the menu button.

#### Environment

- Angular: 9.1.0
- CDK/Material:  9.2.2
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by jelbourn** [comment] 2020-05-14 21:22
@crisbeto I tried this out and VoiceOver indeed doesn't "see" the menuitem elements when using the screenreader's nav instead of tab navigation on Chrome (it does work with Safari). The interaction works fine in ChromeVox and NVDA. I'm not sure what else we could do to make VoiceOver + Chrome happy here, since we are correctly setting focus for the menu. Any thoughts?

**Comment by soshochang** [comment] 2020-05-15 18:14
Perhaps we can try the following:
-Right now when the mat-menu is opened it creates the menu items inside a div with the class cdk-overlay-container which is at the bottom of the DOM.
If we were to move the cdk-overlay-container to be directly after the mat-menu button in the DOM, I think the screenreader would naturally navigate to the menu items after the mat-menu button.
-I did a test where I moved/dragged the cdk-overlay-container in chrome dev tools to directly after the mat-menu button and that did cause VoiceOver to correctly navigate to the menu-items immediately after the mat-menu button

**Comment by jelbourn** [comment] 2020-05-15 18:24
The overlay container is always attached directly to the document body to avoid the problem of clipping by `overflow: hidden` container elements (such as dialogs).

**Comment by tp1906** [comment] 2020-09-15 15:17
Is this also causing the issue of the first menu item from not being announced by the reader?  It always says "menu item one of three" but never reads the label unless i move forward and then back to that item.  This is happens in Chrome using chromevox.

**Comment by jelbourn** [comment] 2020-10-02 00:04
@soshochang I just revisited this issue and found that with Chrome + VoiceOver today everything actually works. I'm thinking a recent VoiceOver update might have fixed this. Can you check whether this is still an issue?

**Comment by jelbourn** [comment] 2020-10-28 17:06
Closing this since I believe it has been fixed. Feel free to open a new issue if you're still able to reproduce.

**Closed by jelbourn** 2020-10-28 17:06 UTC
Labels: G, P3, a11y, area: material/menu
