### ISSUE TITLE
 CDK as a peer dependency breaking Karma (dasherize__.component.spec.ts is missing from the TypeScript compilation.)

### ISSUE THREAD

**Issue by ryandegruyter** [angular/components#16286] opened 2019-06-13 09:55 UTC
#### What are you trying to do?

ng test

#### What troubleshooting steps have you tried?

```
HeadlessChrome 74.0.3723 (Mac OS X 10.13.6) ERROR
  Uncaught Error: Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
  Error: /Users/.../node_modules/@angular/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
  The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
      at AngularCompilerPlugin.getCompiledFile (/Users/.../node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:835:23)
      at plugin.done.then (/Users/.../node_modules/@ngtools/webpack/src/loader.js:41:31)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  at http://localhost:9876/_karma_webpack_/vendor.js:2274:1
```  

#### Environment

- Angular: 8
- CDK/Material: 8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2019-06-13 13:51
The issue is that whatever is looking for TS files in your build is also trying to compile the CDK schematic files. We've landed some changes to switch the extension of all schematics to be `.template`, but until it is released, you can work around it by excluding the files under `schematics`.

**Closed by crisbeto** 2019-06-13 13:51 UTC
Labels: troubleshooting

**Comment by ryandegruyter** [comment] 2019-06-13 15:30
Thanks @crisbeto

**Comment by ryandegruyter** [comment] 2019-06-13 15:32
The solution was to edit the regex, responsible for loading all the .spec files, to exclude any path containing 'cdk'

`const context = require.context('../', true, /^((?!cdk).)+(\.spec|globals)\.ts$/);`
