### ISSUE TITLE
bug(MatSelect): MatSelect doesnt work properly when placed inside html dialog element

### ISSUE THREAD

**Issue by naveedahmed1** [angular/components#28169] opened 2023-11-22 09:05 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the MatSelect component inside the HTML Dialog element, the select options are rendered outside the dialog component.

Please have a look at the below example:

https://stackblitz.com/edit/dqnjyo?file=src%2Fexample%2Fselect-overview-example.ts

Click the select list and you will notice that options list is rendered outisde the dialog element.

### Reproduction

https://stackblitz.com/edit/dqnjyo?file=src%2Fexample%2Fselect-overview-example.ts

### Expected Behavior

The matselect should work properly when placed inside the HTML Dialog.

### Actual Behavior

The options list is displayed outside the dialog component.

### Environment

Angular CLI: 17.0.3
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.1.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cdk                    17.0.1
@angular/cli                    17.0.3
@angular/fire                   16.0.0
@angular/google-maps            17.0.1
@angular/material               17.0.1
@angular/pwa                    17.0.3
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0

**Comment by crisbeto** [comment] 2023-11-22 13:12
Duplicate of https://github.com/angular/components/issues/25799.

**Closed by crisbeto** 2023-11-22 13:12 UTC
Labels: needs triage
