### ISSUE TITLE
getting  NullInjectorError: No provider for InjectionToken DocumentToken! from angular/cdk modules

### ISSUE THREAD

**Issue by gggiiia** [angular/components#20079] opened 2020-07-23 21:18 UTC
#### Reproduction

i'm lost don't know why i'm getting this error out of nowhere, please help.

Steps to reproduce:
unkown
 
#### Expected Behavior

What behavior were you expecting to see?
it just works

#### Actual Behavior

What behavior did you actually see?
```
NullInjectorError: StaticInjectorError(AppModule)[DragDrop -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[DragDrop -> InjectionToken DocumentToken]: 
    NullInjectorError: No provider for InjectionToken DocumentToken!
    at NullInjector.push.../../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:4200/vendor.js:61178:25)
    at resolveToken (http://localhost:4200/vendor.js:72402:24)
    at tryResolveToken (http://localhost:4200/vendor.js:72346:16)
    at StaticInjector.push.../../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:72240:20)
    at resolveToken (http://localhost:4200/vendor.js:72402:24)
    at tryResolveToken (http://localhost:4200/vendor.js:72346:16)
    at StaticInjector.push.../../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:72240:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:82127:29)
    at NgModuleRef_.push.../../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (http://localhost:4200/vendor.js:82728:16)
    at injectInjectorOnly (http://localhost:4200/vendor.js:61063:33)
client:52 [WDS] Live Reloading enabled.

```
#### Environment

- Angular: 9.0.7
- CDK/Material: 9.0.1 both
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): fedora

**Comment by jelbourn** [comment] 2020-07-23 21:40
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Relevant application code

(this is a canned response)

**Comment by devversion** [comment] 2020-08-07 11:06
Hey. I'm closing this because not sufficient information has been provided. Your issue might surface because the browser platform is not used? https://cs.opensource.google/angular/angular/+/master:packages/platform-browser/src/browser.ts;l=42?q=platformBrowser&ss=angular

The platform would be responsible for providing the `DOCUMENT` injection token.

**Closed by devversion** 2020-08-07 11:06 UTC
Labels: needs clarification
