### ISSUE TITLE
Why does EventEmitter not working on mat-menu?

### ISSUE THREAD

**Issue by zinzinday** [angular/components#17591] opened 2019-11-03 04:55 UTC
What is the expected behavior?

The purpose is that I want to reconfirm whether the customer really wants to delete the content.
I have created custom directive `AlertConfirmDirective`. 
_When you click the button (delete), open a dialog to verify that it is no / yes. If Yes, it will emit to event (onConfirmed)_
It's working fine normal component 
but when using it on `mat-menu` with **lazy** list item. it do not working.
I have tired to try with change-detection strategy, setTimeout,... but all not working for me.

#### Reproduction
What are the steps to reproduce?
I have deployed my mini repo to : [Stackblitz](https://stackblitz.com/edit/angular-f4ms3d)

```html
<mat-menu #itemActions="matMenu">
  <ng-template matMenuContent let-item="item">
    <button mat-menu-item>{{item.name}}</button>
    <button mat-menu-item 
    alert-confirm 
    name="banking" 
    (onConfirmed)="onDelete(item)">
      Delete
    </button>
  </ng-template>
</mat-menu>
```
Directive called and dialog open but EventEmiter (onConfirmed) not working.
Please review my repo and help me.

Thanks advaced

#### Environment
Angular CLI: 8.3.14
Node: 10.17.0
OS: linux x64
Angular: 8.2.12
@angular/material/ cdk    8.2.3
- Browser(s): Chrome latest stable
- Operating System:  Ubuntu 16.04

**Comment by ngnam** [comment] 2019-11-04 04:40
change ng-template to ng-container

**Comment by jelbourn** [comment] 2019-11-06 10:02
I took a look and I don't see anything wrong with the example. @crisbeto does anything stand out to you?

**Comment by devversion** [comment] 2020-05-26 12:52
I think the issue is that the menu items are detached and Angular unsubscribes from the output in that case. Hence the `onConfirmed` output does not fire.

Similar issue would be observable with basic `*ngIf`. Here is an example: https://stackblitz.com/edit/angular-swgksg?file=src/app/app.component.html.

I'm closing this as the menu detaches on list-item click and this is the expected behavior.

**Closed by devversion** 2020-05-26 12:52 UTC
Labels: needs triage, troubleshooting
