### ISSUE TITLE
Table matNoDataRow missing "mdc-data-table__row"

### ISSUE THREAD

**Issue by leomayer** [angular/components#26790] opened 2023-03-14 17:01 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When the table row selector `matNoDataRow` is hit it doesn't include the class `mdc-data-table__row`. I guess that's the default class for a row!

The quite similar bug #26162 was reported as well - at least the start and the conclusion was the same!

### Reproduction

https://stackblitz.com/run?file=src%2Fapp%2Ftable-filtering-example.html
1) Enter any kind of invalid data

### Expected Behavior

`matNoDataRow` should automatically inject class `mdc-data-table__row` 

### Actual Behavior

`matNoDataRow` is NOT inject class `mdc-data-table__row` . One needs to do it manually - with the risk of an internal change of the class names!

### Environment

Angular CLI: 15.2.1
Node: 19.7.0 (Unsupported)
Package Manager: npm 9.5.0
OS: linux x64

Angular: 15.2.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.1
@angular-devkit/build-angular   15.2.1
@angular-devkit/core            15.2.1
@angular-devkit/schematics      15.2.1
@schematics/angular             15.2.1
rxjs                            7.8.0
typescript                      4.9.5

**Comment by wagnermaciel** [comment] 2023-03-17 20:39
Hi @leomayer, I can't access the stackblitz link you provided. Is it publicly visible?

**Comment by leomayer** [comment] 2023-03-18 07:48
I thought it is but perhaps...

You can use the public example from the documentation of Angular Material
https://material.angular.io/components/table/examples#table-filtering

Labeled with `Table with filtering` and filter something which isn't found.

**Comment by crisbeto** [comment] 2023-05-04 08:45
Duplicate of https://github.com/angular/components/issues/26162.

**Closed by crisbeto** 2023-05-04 08:45 UTC
Labels: needs: clarification
