### ISSUE TITLE
Cannot adjust the min-width of MatSelect select panel

### ISSUE THREAD

**Issue by YuriyDetsyk** [angular/components#14515] opened 2018-12-14 07:18 UTC
#### What is the expected behavior?
When trying to adjust `min-width` property of the select panel, it should be overriden properly for customization purposes: `.mat-select-panel { min-width: 100% !important; }`.

#### What is the current behavior?
After applying changed `min-width` property, the select panel has "jumping" width when showing/hiding.

#### What are the steps to reproduce?
Min-width override causes jumping: https://stackblitz.com/edit/angular-mat-select-issue
Temporary fix that I made: https://stackblitz.com/edit/angular-mat-select-issue-tempfix

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
`"@angular/material": "7.0.1",`
`"@angular/animations": "7.0.1"`
`"@angular/cdk": "7.0.1"`

#### Is there anything else we should know?
`Details`
I found that the most possible reason for such "jumping" effect is the "transformPanel" animation
(_see @angular/material/esm2015/select.js, lines 45..65_)
It uses breakpoints with different `minWidth` values. After commenting them out I was able to remove the "jumping" effect.

`Workaround`
- My temporary workaround uses some dirty CSS hacks by hiding the overflow on the `.cdk-overlay-pane`, so it affects clipping of scrollbar, and that's not good at all.
- Another possible hack might be overriding the animation, but it's also not clean at all.
- **It will be really great to see a working solution, when we talk about customizable width of select panel.**

**Comment by schroedermarius** [comment] 2019-04-12 07:15
Bumping this, because it is still a big problem.

**Comment by efagerberg** [comment] 2019-04-24 15:23
I am also struggling with this problem. It seems like `disableOptionCentering` is not as much of an option when this bug exists. For now people can see this workaround https://stackoverflow.com/questions/48563447/angular-material2-select-component-alignment, which is not ideal as it strips animations and requires either `!important` usage or using a global style sheet.

**Comment by prajaktashah** [comment] 2019-07-11 06:28
still not working with following specifications:
 "@angular/animations": "^7.2.13",
    "@angular/cdk": "^7.2.2",
    "@angular/core": "^7.2.13",
    "@angular/material": "^7.2.2",

**Comment by Debxit** [comment] 2019-09-13 08:31
Bumping this, because it is still a big problem.

**Comment by yBussi** [comment] 2019-09-25 13:29
Any solution how to solve width 'Jumping' in Chrome?

**Comment by AshwinMahatkar** [comment] 2019-10-14 05:55
Hello guys
Did you get any solution on 'Jumping' problem in chrome?

**Comment by YuriyDetsyk** [comment] 2019-10-14 06:21
@AshwinMahatkar, I have previously added a temp fix in the issue description, it might help you:
https://stackblitz.com/edit/angular-mat-select-issue-tempfix

**Comment by AshwinMahatkar** [comment] 2019-10-16 11:50
@YuriyDetsyk , I got it Thanks. 
There is one issue with chrome browse.
After this changes I am getting panel jumping problem. Opening panel is getting jump from right to left. Do you have any idea about this one?

**Comment by Nikolay-Uvarov** [comment] 2019-11-07 15:35
I have faced as well. 
I have found a solution: https://stackoverflow.com/questions/53092399/mat-select-panel-min-width

**Comment by King2231** [comment] 2019-11-22 12:17
Facing the same issue.  I tried removing animation for avoiding jumping problem but then the select dropdown does not open in edge and safari.

**Comment by ahnpnl** [comment] 2019-12-14 16:12
I ran into the jumping issue as well. The workaround from stackblitz works pretty well but I would love to see a fix from angular material team.

**Comment by Spawnrad** [comment] 2020-05-27 18:34
Same issue for me jumping left side :(

**Comment by mmalerba** [comment] 2020-05-28 22:09
Can someone provide a stackblitz that better demonstrates the issue? I tried comparing the broken one with the fix one given in the original post, but I couldn't really see any jumping. The only difference I saw was that the panel had been moved below the input in the "fixed" version

**Comment by marchica** [comment] 2020-07-19 04:26
In case it helps, I can no longer reproduce the issue either. I've taken the hacky workaround out of my app and it's all good now. I wonder if it could have been a Chrome rendering issue that's been resolved in a recent update.

**Comment by mmalerba** [comment] 2020-07-20 18:29
Closing since it seems to be fixed

**Closed by mmalerba** 2020-07-20 18:29 UTC
Labels: area: material/select, cannot reproduce, needs clarification
