### ISSUE TITLE
bug(matDatepickerFilter): No date clickable if matDatepickerFilter is set with ".bind(this, params)"

### ISSUE THREAD

**Issue by pionas** [angular/components#22037] opened 2021-02-26 13:20 UTC
#### Reproduction

https://stackblitz.com/edit/components-issue-cjthe5?file=src%2Fapp%2Fexample-component.ts

Steps to reproduce:
1. Click on calender Icon
 
#### Expected Behavior

I would expect to see the clicked date

#### Actual Behavior

Calendar is empty and in console we can see errors.

#### Environment

- Angular: Angular 11
- CDK/Material: 11
- Browser(s): Current Firefox, Current Chrome
- Operating System: Windows

**Comment by crisbeto** [comment] 2021-02-26 14:02
Duplicate of https://github.com/angular/components/issues/21929.

**Closed by crisbeto** 2021-02-26 14:02 UTC
Labels: needs triage
