### ISSUE TITLE
The clickable area of ​​the button tag with a misspelled but matched front mat-icon is enlarged.

### ISSUE THREAD

**Issue by goonishida** [angular/components#12893] opened 2018-08-29 17:44 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
The clickable area should be the same as the button area.

#### What is the current behavior?
The clickable area of ​​the button tag with a misspelled but matched front mat-icon is enlarged.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-material-icon-miss-spell?file=src%2Fapp%2Fapp.component.html

#### What is the use-case or motivation for changing an existing behavior?
mat-icon keyword front match is nice, but this bug is horrible.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.4, Material 6.4.6, macOS 10.13.6, TypeScript 2.9.2, Chrome 68.0.3440.106

#### Is there anything else we should know?
Right-clicking the enlarged clickable area on stackblitz will include the "search pause_miss_spell" menu in the context menu. Perhaps there is an invisible mat icon keyword string in the expanded clickable area.

**Comment by julianobrasil** [comment] 2018-08-30 10:59
@goonishida, this is not a bug. `pause_miss_spell` is not a real material icon name (https://material.io/tools/icons/?style=baseline). Internally, apparently `mat_icon` takes what is written until the first font ligature ("_") or blank space as the icon name, in this case, the word **pause**. But it messes up with the icon representation when it splits it:

![image](https://user-images.githubusercontent.com/25405143/44847593-5cc7c500-ac2a-11e8-83f0-e031d7724ecc.png)

**Comment by julianobrasil** [comment] 2018-08-30 11:10
But I agree that it would be better if nothing was shown when a nonexistent icon name was found.

**Comment by goonishida** [comment] 2018-09-03 12:56
@julianobrasil Thank you for your reply. 
> But I agree that it would be better if nothing was shown when a nonexistent icon name was found.
That is not what I pointed out. Did you click around stop button? At that time the pause button will work. This is what I called bug.

**Comment by crisbeto** [comment] 2020-05-25 17:53
Duplicate of https://github.com/angular/components/issues/11826.

**Closed by crisbeto** 2020-05-25 17:53 UTC
Labels: area: material/icon
