### ISSUE TITLE
Angular Material MatTabNav incorrectly scrolls into view of active tab-link

### ISSUE THREAD

**Issue by brylkovskyi** [angular/components#23763] opened 2021-10-15 14:32 UTC
**Overview of the Issue**
In case MatTabNav pagination is active and active tab was set programmatically to some ending tab (ex. last is active),
on component init MatTabNav scrolls into view of active tab but after animation tab is still hidden.

**Screenshot**
![image](https://user-images.githubusercontent.com/36629180/137504441-459c5981-2aba-4a24-a93d-be121c8fa28b.png)

**Demo**
Please see the stackblits demo of issue
https://stackblitz.com/edit/angular-material-v12-rc-view-engine-h4cst5?file=src/app/badge-overview-example.ts

**Env**
@angular/animations 12.0.0-rc.3
@angular/cdk 12.0.0-rc.2
@angular/common 12.0.0-rc.3
@angular/compiler 12.0.0-rc.3
@angular/core 12.0.0-rc.3
@angular/material 12.0.0-rc.2
@angular/material-moment-adapter 12.0.0-rc.2
@angular/platform-browser 12.0.0-rc.3
@angular/platform-browser-dynamic 12.0.0-rc.3

**Comment by crisbeto** [comment] 2021-10-18 05:59
I suspect that this has the same root cause as https://github.com/angular/components/issues/23724 which has a pending PR.

**Comment by crisbeto** [comment] 2021-11-07 06:07
Closing as a dupe of #23724.

**Closed by crisbeto** 2021-11-07 06:07 UTC
Labels: needs triage
