### ISSUE TITLE
MatStepper `tabpanel` element should not have `tabindex="0"`

### ISSUE THREAD

**Issue by Wloclawek** [angular/components#19574] opened 2020-06-09 07:26 UTC
#### Reproduction

Steps to reproduce:
1. Open: https://material.angular.io/components/stepper/api
2. Use tab and go to first input.
 
 
#### Expected Behavior

Focus should always be visible (users using only the keyboard). 

A11Y / WCAG / accessibility

#### Actual Behavior

Between the first step (tab) and the first field, the focus disappears.

#### Environment

- Angular: 8.
- Angular Material: 9.2.4
- Browser(s): Firefox 77, Chrome 83
- Operating System: Windows 10.

**Comment by jelbourn** [comment] 2020-06-11 21:52
Looked at this, the `role="tabpanel"` here has `tabindex="0"` which shouldn't be the case.

**Comment by crisbeto** [comment] 2020-06-12 15:21
We've got a PR for this already https://github.com/angular/components/pull/16809. Also closing as a duplicate of https://github.com/angular/components/issues/16692.

**Closed by crisbeto** 2020-06-12 15:21 UTC
Labels: P2, a11y, area: material/stepper
