### ISSUE TITLE
feat(CLIPBOARD): Being able to reset the clipboard

### ISSUE THREAD

**Issue by GitHubish** [angular/components#19883] opened 2020-07-07 12:20 UTC
I wanted to reset the clipboard by going: 

`this.clipboard.copy("");`

But it doesn't work. It would be at least interesting if it was possible or if there was an explicit "reset" method.

Is that possible? 
Thanks

**Comment by crisbeto** [comment] 2020-07-07 15:15
In order to support all browsers, our current copying approach works by creating a `textarea`, inserting the text in it and triggering a copy command. From what I can tell, this won't work for an empty string since the browser just won't copy anything. You should be able to work around it by copying a string with a single space, e.g. `this.clipboard.copy(" ");`.

**Comment by jelbourn** [comment] 2020-07-09 21:57
Closed as working as intended; we _could_ add a reset method that does `copy(' ')`, but then people would just file bugs about that weird space being in there.

**Closed by jelbourn** 2020-07-09 21:57 UTC
Labels: feature, needs triage
