### ISSUE TITLE
bug(@angular/google-maps): (zoomChanged) returns undefined

### ISSUE THREAD

**Issue by anuj9196** [angular/components#24888] opened 2022-05-06 06:22 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Using the following
```
<div *ngIf="apiLoaded | async">
        <google-map #gMap
          width="100%"
          height="23rem"
          [zoom]="currentMapData?.zoom || defaultZoom"
          (mapClick)="addMarker($event)" 
          (zoomChanged)="onZoomChange($event)">

          <map-marker
            [position]="markerPosition"
            [options]="markerOptions">
          </map-marker>
        </google-map>
 </div>
```

The `onZoomChange()` method to get the zoom level changed
```
  onZoomChange($event: any) {
    console.log('zoom: ', $event);
  }
```

But it outputs `undefined`. Expected should be the new zoom level.

### Reproduction

Steps to reproduce:
1. Check https://components-issue-s2dfny.stackblitz.io
2. Check the console for the output of the zoom event.

### Expected Behavior

It should give the current zoom level of the map

### Actual Behavior

Zoom value is `undefined`

### Environment

- Angular: 13.2
- CDK/Material:
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Mac OS

**Comment by volvachev** [comment] 2022-05-07 17:14
Hi, this is not a bug. Google maps work like that. Angular Material just proxies [`zoom_changed`](https://developers.google.com/maps/documentation/javascript/reference/map#Map.zoom_changed) call without arguments(and also `zoomChanged` a has type `Observable<void>`).

**Comment by crisbeto** [comment] 2022-07-06 18:26
Closing since this works as expected, indicated by the `Observable<void>` type.

**Closed by crisbeto** 2022-07-06 18:26 UTC
Labels: P4, area: google-maps
