### ISSUE TITLE
bug(cdkDrag): Click events don't bubble up from cdkDrag items

### ISSUE THREAD

**Issue by lschuft** [angular/components#21027] opened 2020-11-12 15:02 UTC
#### Reproduction

StackBlitz: https://stackblitz.com/edit/components-issue-wdnqmc

Steps to reproduce:
1. Place the [CDK Drag and Drop connected sorting group example](https://stackblitz.com/angular/kbgbenlxerm?file=src%2Fapp%2Fcdk-drag-drop-connected-sorting-group-example.ts) in the page.
2. Subscribe to a [RxJS fromEvent](https://rxjs-dev.firebaseapp.com/api/index/function/fromEvent) that listens for mousedown events. This is used in some third party libraries like NgBootstrap (I included two examples from that library in the StackBlitz for demonstration purposes). You can also use Angular's own [@HostListener](https://angular.io/api/core/HostListener) (left a commented block if someone wants to try it).
3. Click anywhere on the page, and see the click counter rise. 
4. Now, click on the enabled cdkDrag items. 
 
#### Expected Behavior

The click counter should detect the clicks. Open dropdowns and popovers should close on clicks outside of them.

#### Actual Behavior

The click counter does not detect the clicks. Open dropdowns and popovers remain open:

![GIF 11-12-2020 12-01-06 PM](https://user-images.githubusercontent.com/20956972/98956450-d03e1000-24de-11eb-9b14-752ffe94b99a.gif)

#### Environment

- Angular: 10.1.1
- CDK/Material: 10.2.1
- Browser(s): Chrome, Firefox, Edge, Chrome for Android.
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Android (couldn't check others)

**Comment by crisbeto** [comment] 2020-11-16 17:29
Duplicate of #19333.

**Closed by crisbeto** 2020-11-16 17:29 UTC
Labels: needs triage
