### ISSUE TITLE
Allow easier overriding of theme background and foreground colors

### ISSUE THREAD

**Issue by spiotr12** [angular/components#19935] opened 2020-07-10 11:14 UTC
#### Reproduction

Steps to reproduce:
1. Create angular application (using custom theme)
2. Set theme map using the new `mat-light-theme($config)` mixin
3. Remap background configuration
```
$light-background-config: map.get($light-theme, background);
$light-background-config: map.merge($light-background-config, (background: red));
$light-theme: map.merge($light-theme, (background: $light-background-config));
// ...
@include angular-material-theme($light-theme);
```
4. Observe - background has not change

I've debug the _theming.scss and something overrides theme.background.background: xxx color back to white (or black, depending on light/dark theme).

If I use the legacy `mat-light-theme($primary, $accent, $warn)` I am able to override the background color.
 
 
#### Expected Behavior

Being able to override configs like background/foreground

#### Actual Behavior

background/foreground colors are reset to light/dark default

#### Environment

- Angular: 10.0.2
- CDK/Material: 10.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by grizzm0** [comment] 2020-07-13 14:58
The background has been moved to color.background.
You could do something like this to override it.

```
$app-light-theme: mat-light-theme((
  color: (
    primary: mat-palette($color-black),
    accent: mat-palette($mat-pink, A200, A100, A400)
  ),
  typography: $app-typography
));

$app-light-theme: map-merge(
    $app-light-theme,
    (
      color: map-merge(
          map-get($app-light-theme, color),
          (
            background: map-merge(
                $mat-light-theme-background,
                (
                  background: #fff
                )
            )
          )
      )
    )
);
```

This seems a bit ugly tho.. I would suggest that we add map-merge support inside the theme builder mixins instead. So we could use the following.

```
$app-light-theme: mat-light-theme((
  color: (
    primary: mat-palette($color-black),
    accent: mat-palette($mat-pink, A200, A100, A400),
    background: (
      background: #fff
    )
  ),
  typography: $app-typography
));
```

**Comment by grizzm0** [comment] 2020-07-13 15:25
We could possibly do it in mat-light-theme/mat-dark-theme after _mat-create-light-color-config/_mat-create-light-color-config.

Check if `map_get($color-settings, background)` or `map_get($color-settings, foreground)` exists and if so merge them into `$result.color.background` and `$result.color.foreground`.

**Comment by twerske** [comment] 2021-05-21 18:18
Closing as a duplicate of #6244

**Closed by twerske** 2021-05-21 18:18 UTC
Labels: P4, area: theming, feature
