### ISSUE TITLE
bug(MatSelect): MatSelect not allowing page scrolling underneath

### ISSUE THREAD

**Issue by Martinspire** [angular/components#29366] opened 2024-07-02 13:37 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

I spotted an issue with the current Material Select where you can open a mat-select to show options but when its open, you can no longer scroll the page. Behavior seems similarly broken with some but not all other similar components.

The weird thing is that it doesn't work on the current Material Examples page, but it does work on the stackblitzes connected to them.

I have a similar problem in my own repo, but could not really reproduce it in the stackblitz. I do see that they all have the reposition scrollstrategy and I've tried it with the noop one too but it just doesn't seem to work properly.

I've only recently migrated to 18, but 17 also has the issue present as that is our current production version.

I don't have a workaround yet either. Setting the Scroll Strategy doesn't work and when you remove the pointer-events you can no longer close the dropdown. Behavior seems fine with MatAutocomplete examples, but also broken with MatMenu on examples page. Or at the very least overriding default behavior doesn't seem to work.

### Reproduction

Broken: https://material.angular.io/components/select/examples

Stackblitz that works: https://stackblitz.com/edit/dpyucv?file=src%2Fexample%2Fselect-optgroup-example.html

Examples page from similar component that works: https://material.angular.io/components/autocomplete/examples

Other example that is broken: https://material.angular.io/components/menu/examples

### Expected Behavior

When dropdown is shown I can still scroll the page below it

### Actual Behavior

Scrolling is blocked while the dropdown is open.

### Environment

- Angular: 18.0.3 myself and 18.0.5 from material examples site
- CDK/Material: 18.0.x
- Browser(s): Edge, Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2024-07-04 14:35
Duplicate of https://github.com/angular/components/issues/6927.

**Closed by crisbeto** 2024-07-04 14:35 UTC
Labels: needs triage

**Comment by Martinspire** [comment] 2024-07-08 09:44
@crisbeto i see that it also didn't have a workaround yet (and no progress now that M3 has been delivered). Any suggestions?
