### ISSUE TITLE
CSS zoom makes the options panel block the input field for mat-autocomplete

### ISSUE THREAD

**Issue by SL-nicholas-tan** [angular/components#17621] opened 2019-11-06 01:32 UTC
#### Reproduction

https://stackblitz.com/edit/angular-mypou7?file=src/styles.scss

Steps to reproduce:
1. Focus on autocomplete input field so that the options panel appear (might appear and disappear immediately if it's trying to float above the input, scroll all the way down for it to work normally)

2. With the panel visible, scroll up and down.
 
 
#### Expected Behavior

mat-autocomplete input field always visible 
![image](https://user-images.githubusercontent.com/52024868/68260557-49a75500-0078-11ea-8fb6-a273af3585c6.png)

#### Actual Behavior

mat-autocomplete input field gets blocked by the options panel instead of floating above the input field when a css zoom value is applied to the body

![angular-mypou7 - StackBlitz](https://user-images.githubusercontent.com/52024868/68260134-f254b500-0076-11ea-9b17-cb42c53dd45f.gif)

#### Environment

- Angular: 8+
- CDK/Material: 8+
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2019-11-10 22:50
This is something that has come up in the past, although I'm having a hard time digging up the issue. The problem is that we use `getBoundingClientRect` to figure out where to position the dropdown, however it doesn't account for browser zoom so the numbers we get back from the browser will be incorrect. There are ways around it, but they'd be expensive in terms of performance so we decided not to do them.

**Closed** 2019-11-11 07:05 UTC
Labels: P5
