### ISSUE TITLE
bug(COMPONENT): TITLE  hijri date picker is missedup

### ISSUE THREAD

**Issue by moeali1010** [angular/components#29154] opened 2024-05-31 00:54 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

this my html
  <mat-form-field appearance="outline">
                     
                        <input matInput [matDatepicker]="shareUpdateDate" formControlName="shareUpdateDate">
                        <mat-datepicker-toggle matSuffix [for]="shareUpdateDate"></mat-datepicker-toggle>
                        <mat-datepicker #shareUpdateDate></mat-datepicker>
                    </mat-form-field>
                    
                    
                    this my ts 
                    
           import { DateAdapter } from '@angular/material/core';         
                      ngOnInit() { 
                          this.dateAdapter.setLocale('ar-SA');
                        }
                        
                        my problem is 
                    it display current month and current today wrong , also when you click on any day it display another one in input field , for example when click on 3 Ramadan , it display 16 Moharam 
                    
                    is there any setting to fix it ?
                    

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

when click on 3 Ramadan it should display 3 Ramadan i input

### Actual Behavior

when click on 3 Ramadan it should display 16 Moharam

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2024-05-31 07:52
Looks like a duplicate of https://github.com/angular/components/issues/27429.

**Closed by crisbeto** 2024-05-31 07:52 UTC
Labels: needs triage
