### ISSUE TITLE
bug(npm): `@angular/material@17.0.4` is inconsistent with source code

### ISSUE THREAD

**Issue by nzbin** [angular/components#28296] opened 2023-12-17 15:41 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

source code: https://github.com/angular/components/tree/17.0.x/src/material/form-field
npm: https://www.npmjs.com/package/@angular/material?activeTab=code

The `_form-field-density.scss` still in the 17.0.4 but can't find in the source code (`_mdc-text-field-density-overrides.scss`).

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

publish the source code 17.0.4

### Actual Behavior

17.0.4 is still not latest

### Environment

- Angular: 17.0.7
- CDK/Material: 17.0.4
- Browser(s): Chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2023-12-18 06:39
That change will be in the 17.1.0-next release. The source code for the patch releases is in the 17.0.x branch.

**Closed by crisbeto** 2023-12-18 06:39 UTC
Labels: needs triage

**Comment by nzbin** [comment] 2023-12-18 06:52
@crisbeto Please check the docs@17.0.4 https://material.angular.io/components/form-field/examples
It already has the density tokens, but we can't get it with the npm version
![image](https://github.com/angular/components/assets/20625845/2c031066-5dad-4934-a363-5e197ae7f13c)

**Comment by crisbeto** [comment] 2023-12-18 06:55
@devversion can confirm if this is the expected behavior, but the intention is for this change to go out in 17.1.0.

**Comment by devversion** [comment] 2023-12-18 11:07
@crisbeto Not sure what commit this is about- but the assumption is that, if code lands into the patch branch, it's neither a feature, nor a breaking change etc, so it can be deployed always for the most recent commit in `17.0.x`.

**Comment by crisbeto** [comment] 2023-12-18 12:36
Ah right, so it's working as expected. I merged in the changes that introduce the density tokens into the patch (see #28273), but the ones that add it to M3 are in the minor (see #28295). I think the `_form-field-density.scss` is in 17.04, but not in the main branch, because I merged in my changes right after the release. See 
<img width="652" alt="image" src="https://github.com/angular/components/assets/4450522/489609f1-099a-43c4-8bb4-d3f652f38fab">
