### ISSUE TITLE
Expansion panel FOUC when contained in dialog

### ISSUE THREAD

**Issue by SamuelMS** [angular/components#13870] opened 2018-10-30 01:55 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Expansion panels currently render with a flash of unstyled content (FOUC) when nested in a dialog -- they always temporarily appear as expanded, regardless of what the "expanded" attribute is set to. After a moment, all expansion panels that have been explicitly set to closed collapse.

This only occurs in **Angular / Material 7**.

## Expected behavior

Expansion panels should appear as collapsed when the dialog opens when `expanded=false` instead of briefly appearing as expanded, then collapsing after a delay.

## Minimal reproduction of the problem with instructions

Click the button and note the flash of unstyled content in the dialog in Angular 7.

**Angular 7** (bugged): https://angular-egzwfw.stackblitz.io
**Angular 6** (correct): https://angular-eepzxs.stackblitz.io

## What is the motivation / use case for changing the behavior?

Flashes of unstyled content are jarring and feel very buggy.

## Environment

<pre><code>
Angular version: 7.0.1
Material version: 7.0.2
TypeScript: 3.1.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by crisbeto** [comment] 2018-10-30 20:18
Might potentially be solved by https://github.com/angular/material2/pull/11778.

**Comment by crisbeto** [comment] 2018-10-30 20:33
I tried it out and it doesn't look like it'll be fixed by #11778.

**Comment by josephperrott** [comment] 2018-11-20 18:18
Reopening as the fix was reverted.

This seems to be a larger issue across our library as our components use animations to set state quite frequently.

**Comment by SamuelMS** [comment] 2019-02-05 16:35
@crisbeto Hate to be that guy, but has there been any traction on this issue since November -- looks like it might be blocked by a larger issue, per comments in the PR?

**Comment by yy670010378** [comment] 2019-03-05 09:23
Also encountered this problem [](https://github.com/angular/material2/issues/14200)

**Comment by StavM** [comment] 2019-03-06 07:37
Hope this issue gets the attention it deserves. definitely shouldn't be a "P4" priority.
this is probably one of the top reasons to stay with 6.4.7.

**Comment by BobBDE** [comment] 2019-03-12 14:20
Hi guys,

It's a workaround but you can use the lazy rendering of the expansion panel to prevent the animation ( with ng-template matExpansionPanelContent).

**Comment by ThomasTheJohnson** [comment] 2019-04-08 14:07
@crisbeto @josephperrott, Is there a timeline for this fix being worked into a release? Asking so we know whether to move forward with workarounds.

**Comment by FONFAAS** [comment] 2019-04-11 12:45
hello! is there an ETA on this?

**Comment by NaveenAmresh** [comment] 2019-04-26 19:37
Write this following code you may solve this issue
ngOnInit() {
this.href = this.router.url;
console.log(this.href);
}

[expanded]="[this.href === 'routelink']"

**Comment by DaGLiMiOuX** [comment] 2019-05-17 08:28
As per [#11765](https://github.com/angular/components/issues/11765#issuecomment-447991348), there is a workaround styling expansion panels when being animated. Maybe it has something to do the way of inserting the dynamic content inside dialogs using components that uses Material components in them. If you use regular HTML content like paragraphs or anything else, everything works fine.

I don't know if it is related to how the content is loaded, the load speed or the styles. Even if these styles fixes the problem "temporarily", there must be a solution somewhere.

If I have different material accordions stylings that I use for multiple dialog components and non-dialog components at the same time, It will be hard to global styling.

**Comment by matze1234** [comment] 2019-06-05 14:20
I hope this will be solved soon.

**Comment by Hextar** [comment] 2019-06-05 15:33
Also waiting for it to be solved.

**Comment by karansinghneu** [comment] 2019-06-07 19:58
Facing the same issue. Any leads ?

**Comment by dcrouch79** [comment] 2019-06-14 11:21
Another workaround is to disable all animations until `ngAfterViewInit` using the `[@.disabled]` property on a parent element.

[https://stackblitz.com/edit/angular-jcli63]()

**Comment by JalmariO** [comment] 2019-06-17 09:36
@dcrouch79 This workaround works nicely until official fix. Cheers!

**Comment by ricardofct** [comment] 2019-06-25 17:20
Hi there, this worked for me =>[img1](https://ibb.co/yP7gfhb) [img2](https://ibb.co/fvSqj7w)

I put an initial height to fix that issue in my case worked.
ty

**Comment by EzyBakeOven** [comment] 2019-07-03 02:45
> Another workaround is to disable all animations until `ngAfterViewInit` using the `[@.disabled]` property on a parent element.
> 
> https://stackblitz.com/edit/angular-jcli63

@dcrouch79 your stackblitz link is broken D:

**Comment by dcrouch79** [comment] 2019-07-04 12:12
@EzyBakeOven I accidentally deleted it! I've created a new one with a more obvious name this time. The original link has been updated.

**Comment by stanislavKostenko** [comment] 2019-07-11 06:41
Temporary fix with animation saving:

**Comment by stanislavKostenko** [comment] 2019-07-11 06:43
Temporary fix with animation saving:
```<mat-accordion [@.disabled]="isAnimationDisabled">```
```export class AccordionComponent implements OnInit {
  isAnimationDisabled: boolean = true;

  constructor() {
  }

  ngOnInit() {
    this.enableAnimation();
  }

  enableAnimation() {
    setTimeout(() => this.isAnimationDisabled = false, 0);
  }
}
```

**Comment by george-sarji** [comment] 2019-10-09 12:45
Has there been any update for an official fix for this? I'm also having the same issue.

**Comment by tdao7** [comment] 2019-10-18 01:28
> Another workaround is to disable all animations until `ngAfterViewInit` using the `[@.disabled]` property on a parent element.
> 
> https://stackblitz.com/edit/angular-issue13870-workaround

Greate solution. Thanks!

**Comment by nsteeves** [comment] 2019-10-21 19:02
> 
> 
> Another workaround is to disable all animations until `ngAfterViewInit` using the `[@.disabled]` property on a parent element.
> 
> https://stackblitz.com/edit/angular-issue13870-workaround

best solution on here!

**Comment by skrtheboss** [comment] 2020-03-06 11:43
Problem still persists in v9.1.0
https://stackblitz.com/edit/angular-issue13870-workaround-ytbs1x

**Comment by jardelsimao** [comment] 2020-05-04 19:57
> Another workaround is to disable all animations until `ngAfterViewInit` using the `[@.disabled]` property on a parent element.
> 
> https://stackblitz.com/edit/angular-issue13870-workaround

thanks alot!

**Comment by Joshanity17** [comment] 2020-07-04 16:47
Still persist on Angular Material 10.0.1

**Comment by mindscratch** [comment] 2021-01-03 16:01
Still persist with Angular Material 11.0.x

**Comment by Akxe** [comment] 2021-01-11 15:37
The skackblitz links in the issue are not opening. Here is mine for Angular v11 https://stackblitz.com/edit/components-issue-1fvgvm

**Comment by waseemw** [comment] 2021-01-12 07:14
I'm still having this issue as well with Angular Material 11

**Comment by adarsh-thakur** [comment] 2021-01-13 06:52
> Another workaround is to disable all animations until `ngAfterViewInit` using the `[@.disabled]` property on a parent element.
> 
> https://stackblitz.com/edit/angular-issue13870-workaround

Thanks alot. You Saved the Day.

**Comment by liesahead** [comment] 2021-02-15 11:31
I think the problem is inside dialog itself, because I noticed that all content is jumping when dialog is opening. To reproduce that you can open any dialog in angular material dialog example page. The content jumps a little. We have separated dialog header and footer (actions) and now content jumping became very noticeable. At first thought that there is a bug in our project, but then decided to check the material dialog example page.

**Comment by Synzed** [comment] 2021-03-16 08:54
Same thing happens with an expansion panel inside a mat-menu .. problem still persists

**Comment by VladislavKhlystun** [comment] 2021-06-08 10:38
Still persist with Angular Material 12.0.x

**Comment by vgt-benjaminh** [comment] 2021-12-08 12:44
bug still persists. also happens when the expansion panel is placed inside a stepper

**Comment by pranav-js** [comment] 2022-02-14 07:19
give this issue some attention please. this is serious glitch and I spent so much time thinking I was doing something wrong! but it seems to be there since 2018!

**Comment by steffenhees** [comment] 2022-02-20 16:08
If this is not fixed yet, please fix it!!! Thank you!!!

Had the same problem. With the workaround from @dcrouch79 it works for now. Thanks!

**Closed** 2022-03-06 16:24 UTC
Labels: P2, has pr, animation, area: material/dialog, area: material/expansion
