### ISSUE TITLE
feat(Datepicker): Timepicker

### ISSUE THREAD

**Issue by Skycader** [angular/components#26310] opened 2022-12-22 09:10 UTC
### Feature Description

I wonder why there's a great datepicker but nor it has a timepicker option but there is no such component at all.
When will this component be available in Angular Material? Please add ;)

### Use Case

During my project I had to implement a time picker so I searched for such a component in Angular Material docs, but was quite surprised there was none.

**Comment by crisbeto** [comment] 2022-12-23 11:19
Duplicate of https://github.com/angular/components/issues/5648.

**Closed by crisbeto** 2022-12-23 11:19 UTC
Labels: feature, needs triage
