### ISSUE TITLE
MatAutocomplete: I have problem with default selected element

### ISSUE THREAD

**Issue by dsavke** [angular/components#23300] opened 2021-08-03 12:50 UTC
I have form with mat-autocomplete element, and below this form there is mat-table.

In mat-table, I am getting data from API and I have condition in mat-table template like this:

```
<mat-table
  class="mat-elevation-z8"
  [dataSource]="dataSource"
  *ngIf="dataSource?.data?.length > 0"
>
.....
</mat-table>
```

Above this table, there is my mat-autocomplete, he has getting data from API, and when data comes I need to show default option.

I have in TypeScript file, functionality for adding mat-option for mat-autocomplete when data comes, and also giving default value. That everything works, but problem is with property [displayWith]. When all comes and I add to mat-autocomplete it doesn't refresh.

But when I delete a question mark (?) from *ngIf in mat-table, it throws error:

```
RROR TypeError: Cannot read property 'data' of undefined
    atEditComponent_Template (edit.component.html:170)
    at executeTemplate (core.js:9544)
    at refreshView (core.js:9413)
    at refreshComponent (core.js:10579)
    at refreshChildComponents (core.js:9210)
    at refreshView (core.js:9463)
    at refreshEmbeddedViews (core.js:10533)
    at refreshView (core.js:9437)
    at refreshComponent (core.js:10579)
    at refreshChildComponents (core.js:9210)
```

but then property displayWith on mat-autocomplete works and shows default display value on mat-autocomplete.

Does someone knows why this is happening and why this approach works?

**Comment by crisbeto** [comment] 2021-08-04 16:07
It sounds like the approach works, because the entire component is re-rendered when the data changes. It's hard to tell what could be going on without the full code. If you can put together a smaller repro case, we can investigate it further.

**Comment by dsavke** [comment] 2021-08-05 06:24
It's really hard to reproduce, because this is just a small part of huge application. I am getting my data from API and I have async function before I initializing default value for mat-autocomplete. And I have keyword await for async call, because I need data from that call, and after that is just logic to update value for mat-autocomplete and add list of possible data.

But when I delete keyword await and let all to be sync without waiting call (just adding some hardcoded values), then all works great.

**Comment by mmalerba** [comment] 2023-09-25 21:37
Closing since we don't have a way to reproduce / test this

**Closed by mmalerba** 2023-09-25 21:37 UTC
Labels: P3, needs: clarification, troubleshooting, area: material/autocomplete
