### ISSUE TITLE
MatTab not activating pagination on width change

### ISSUE THREAD

**Issue by angelaki** [angular/components#23682] opened 2021-10-04 12:15 UTC
As you can see in this Stackblitz (https://stackblitz.com/edit/angular-selecting-mattab-law8y3?file=src%2Fapp%2Fapp.component.html, by hitting the button) the pagination elements don't get visible if the container size changes. Guess this is due to not unnecessarily observing it's container, but if I have this use-case - can the component's width be _re-checked_?

Sorry if I miss an already existing method.

**Comment by lekhmanrus** [comment] 2021-10-04 17:08
As a workaround - you could trigger resize event:
```ts
  public setWidth(width): void {
    this.width = `${width}px`;
    window.dispatchEvent(new Event('resize'));
  }
```

See [StackBlitz](https://stackblitz.com/edit/angular-selecting-mattab-uanmqj?file=src%2Fapp%2Fapp.component.ts).

**Comment by angelaki** [comment] 2021-10-04 17:14
Thank you for this workaround. Since it is not really a bug and per definition no way around this, I guess this can be closed?

**Comment by crisbeto** [comment] 2021-10-05 12:04
Duplicate of https://github.com/angular/components/issues/19562.

**Closed by crisbeto** 2021-10-05 12:04 UTC
Labels: needs triage
