### ISSUE TITLE
Pls update luxon to 3.0.1 for @angular/material-luxon-adapter

### ISSUE THREAD

**Issue by alvipeo** [angular/components#25465] opened 2022-08-15 14:45 UTC
### Feature Description

Please update `luxon` to v.3.0.1 for @angular/material-luxon-adapter.
Thanks!

**Comment by crisbeto** [comment] 2022-08-15 14:52
Duplicate of https://github.com/angular/components/issues/25408.

**Closed by crisbeto** 2022-08-15 14:52 UTC
Labels: feature, needs triage
