### ISSUE TITLE
Improve mat-form-field layout according to specs

### ISSUE THREAD

**Issue by ilyakonrad** [angular/components#22477] opened 2021-04-14 10:29 UTC
I'm talking specifically about `<mat-form-field appearance="outline">` with text input inside but I guess it may be relevant for other types of form components as well.

Here's what we have in [specs](https://material.io/components/text-fields):
1. Nicely vertically aligned input...
2. which covers whole .mdc-text-field block...
3. which has correct height of 56px...
4. which has correctly positioned prefix icon...
5. which doesn't affect position of label when the field has focus or value...
6. etc...

![image](https://user-images.githubusercontent.com/25200186/114692130-021f0100-9d21-11eb-893d-df0b5ca48610.png)

Here's what we currently have in Angular Material:
1. Weird structure.
2. Incorrect height of 58.76px.
3. Prefix icon without any margin/padding...
4. which affects position of the label in "active" state...
5. etc...

![image](https://user-images.githubusercontent.com/25200186/114694012-d43abc00-9d22-11eb-93a3-2fbd9a50e8ba.png)

I think it's important for such essential form component to meet specs. Until then it brings troubles of hack-fixing layout things just to make it look fine or be similar to Material components from other libraries that follow specs.

It's probably duplication of [similar issue](https://github.com/angular/components/issues/11513) which is going to celebrate 3 years with status "open" next month 😞

**Comment by jelbourn** [comment] 2021-04-15 21:40
Yes this is a duplicate of #11513. 

Our MDC-based version of the form-field currently in `@angular/material-experimental` should be much on-spec.

**Closed by jelbourn** 2021-04-15 21:40 UTC
Labels: needs triage
