### ISSUE TITLE
bug(mat-select): selected options removed when filtering and selecting options

### ISSUE THREAD

**Issue by danzrou** [angular/components#20090] opened 2020-07-25 13:28 UTC
#### Reproduction

https://stackblitz.com/edit/mat-select-filtered

Steps to reproduce:
1. Select 1+ options
2. Search for an option which is not selected
3. Select the option 
4. Clear search
 
 
#### Expected Behavior

Previous selected options are kept

#### Actual Behavior

Previous selected options are not selected anymore

#### Environment

- Angular: 10.0.1
- CDK/Material: 10.1.0

**Comment by crisbeto** [comment] 2020-07-26 08:30
Duplicate of https://github.com/angular/components/issues/9038.

**Closed by crisbeto** 2020-07-26 08:30 UTC
Labels: area: material/select

**Comment by danzrou** [comment] 2020-07-27 07:48
@crisbeto I am not sure its a duplicate of that issue.
The problem is not that its not emitting the values, but rather of not keeping them after options changed.

**Comment by crisbeto** [comment] 2020-07-27 08:52
The underlying issue is the same: options aren't removed from the selection when they're destroyed. The selection matches up with the model value.
