### ISSUE TITLE
Changing options of MatButtonToggleGroup causes it to lose its currently displayed value

### ISSUE THREAD

**Issue by biltongza** [angular/components#16423] opened 2019-07-02 13:06 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-7-mat-button-toggle-loses-displayed-value

Steps to reproduce:
1. Create a MatButtonToggleGroup with some options
2. Select a value, observe that it sets its value correctly
3. Update the options of it, ensuring that the currently selected option is still in the options array
4. Observe that the button toggle group no longer displays its selected value
 
 
#### Expected Behavior

What behavior were you expecting to see?
The currently selected value is still a valid option so it should still be displayed as the selected option.

#### Actual Behavior

What behavior did you actually see?
The currently selected value is not displayed as the selected option, and the button group appears as if it has been reset.

#### Environment

- Angular: 7.2.15
- CDK/Material: 7.3.7
- Browser(s): Google Chrome 75.0.3770.100 (Official Build) (64-bit), Firefox 67.0.4 (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 1903 64 bit (18362.207)

**Comment by BeanHeaDza** [comment] 2019-07-03 06:09
A workaround we did for now, but causes flickering and is ugly as hell: https://stackblitz.com/edit/angular-7-mat-button-toggle-loses-displayed-value-jkbzwe

**Comment by crisbeto** [comment] 2019-07-03 20:54
I wasn't able to reproduce it against the latest version. It should've been fixed by https://github.com/angular/components/pull/15508.

**Closed by crisbeto** 2019-07-03 20:54 UTC

**Comment by biltongza** [comment] 2019-07-04 08:23
Will this make it into a 7.x release or will we need to upgrade to 8?

**Comment by crisbeto** [comment] 2019-07-04 08:26
You'll most likely have to update since we don't backport fixes, unless they're something major like security.
