### ISSUE TITLE
feat(youtube-player): add option to hide controls or pass `playerVars` options

### ISSUE THREAD

**Issue by lautarojgarcia177** [angular/components#19427] opened 2020-05-22 23:38 UTC
#### Feature Description

Youtube's player hide controls

#### Use Case

I want to hide the player's controls and provide my own

**Comment by devversion** [comment] 2020-05-25 11:49
It looks like these options could be set through the `playerVars` option when we construct the `Yt.Player`. We could provide a way for consumers to pass these options, or have convenience inputs (though that might be verbose to maintain).

cc. @YourDeveloperFriend

**Comment by devversion** [comment] 2020-05-26 10:36
Closing this as a duplicate of https://github.com/angular/components/issues/19267

**Closed by devversion** 2020-05-26 10:36 UTC
Labels: P3, area: youtube-player, feature
