### ISSUE TITLE
Range slider for from and to values

### ISSUE THREAD

**Issue by ranbuch** [angular/components#16936] opened 2019-09-01 09:11 UTC
#### Feature Description
As described on the [material design guidelines](https://material.io/components/sliders/#usage)

#### Use Case

Let the user specify 2 values like `from price` and `to price` when the second one is always greater then the first one.

**Comment by AdditionAddict** [comment] 2019-09-19 14:44
Duplicate of #1331

**Comment by devversion** [comment] 2020-05-28 23:25
Yes. Closing as a duplicate. Thanks @AdditionAddict

**Closed by devversion** 2020-05-28 23:25 UTC
Labels: feature, needs triage
