### ISSUE TITLE
feat(MatTable): infinite scrolling for mat-table

### ISSUE THREAD

**Issue by carboncs16** [angular/components#23314] opened 2021-08-05 12:02 UTC
#### Feature Description

There should be infinite scrolling available for mat-table

#### Use Case

I recently faced a scenario where we were rendering 1000+ records in the table and it had to be shown without any pagination. Rendering the whole table all at once was a bit slow. It was solved by OnPush change detection, but it would still be a good feature to use Infinite scrolling to make the table more optimized.

**Comment by jelbourn** [comment] 2021-08-05 21:21
Duplicate of #10122

**Closed by jelbourn** 2021-08-05 21:21 UTC
Labels: feature, needs triage
