### ISSUE TITLE
[Tabs] Allow users ability to disable pagination

### ISSUE THREAD

**Issue by cbjerg** [angular/components#2236] opened 2016-12-15 12:14 UTC
#### Bug, feature request, or proposal:

Can't find a way to disable scrolling of tabs. Missing (or fail to apply) the md-no-pagination from material1

#### Which versions of Angular, Material, OS, browsers are affected?

alpha 11 on latest angular

**Comment by PTC-JoshuaMatthews** [comment] 2016-12-21 07:42
On the same note, a way to turn on scrolling of tabs would be nice. Seems scrolling doesn't enable unless thhere are over a certain number of tabs, but it would be nice to have the option of enabling it if the tab control is in a small container as well.

**Comment by aarmora** [comment] 2017-02-10 15:44
Are you guys having issues with the pagination arrows showing up on page load? I have as basic of an implemenation as is possible and the pagination arrows show up on page load but disappear when I click a tab.

**Comment by JordanSliz** [comment] 2017-03-09 21:12
Is there any update on this?  This is a pretty frustrating problem for me.  I have four tabs of width: 25%, but even though they fit within the container, the pagination activates, and as you say, it doesn't seem like md-no-pagination="true" does anything on the ng2 components.

**Comment by aarmora** [comment] 2017-03-09 21:47
@JordanSliz My workaround hack is this:

```
.mat-tab-header-pagination.mat-tab-header-pagination-disabled {
    display: none !important;
}
```

Though I haven't tested it in a situation where we would want pagination tabs.

**Comment by JordanSliz** [comment] 2017-03-09 22:15
@aarmora 

This doesn't seem to actually affect anything for me.  The buttons still shift into overflow, and the arrows still show up until it realizes that the 4 tabs are able to stay within the boundaries, and then disappears them and snaps back to normal.  If I click the 4th tab, they all shift into overflow (partially disappear to the left) with the 4th tab centered in the md-tab-header, with the arrows apparent.

Is there a change I can make to the source?  Some code I can comment out?

**Comment by JordanSliz** [comment] 2017-03-10 01:19
A lot of the problem for styling comes from min-width, in this case, which cases based on breakpoints and such.

minwidth = 0 !important;

and the tabs themselves with:

width: 25%;  (or whatever quotient of 100%/number of tabs)

**Comment by andrewseguin** [comment] 2017-03-14 17:44
It would be very helpful if you can provide a plunker that demonstrates the issue so we can work through what the right solution would be. Here's an example you can start with: https://plnkr.co/edit/BBMBXOspUAChJzoaJJZw?p=preview

**Comment by bdonald25** [comment] 2017-03-15 20:56
@aarmora I had the same issue as you with the arrows showing up on page load. For me I tracked it down to this line in my scss. Once I removed it, I no longer had that issue. Are you using roboto font as well?
`@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500,700');`

**Comment by JordanSliz** [comment] 2017-03-15 22:30
Well, I am using Roboto, which is standard Material guidelines, and also just a damned solid font.  But for me, the problem came down to minimum width.  I searched and searched for the problem, but because browsers don't group "min-width" into "width" when displaying calculated values, but does reflect the min-width, I had thought it must be something within ng2 using JS to resize the fields.

**Comment by JordanSliz** [comment] 2017-03-15 22:30
That being said, the ng1 pagination commands do nothing in ng2, as yet.

**Comment by andrewseguin** [comment] 2017-03-15 22:36
Regarding the primary issue, can you help me understand the use case of disabling pagination? Why restrict the user from scrolling across the tabs?

**Comment by agatsoh** [comment] 2017-04-10 11:52
Any update when this no-pagination feature will be included ?

**Comment by JordanSliz** [comment] 2017-04-10 17:18
As I see it, it's useful for making tighter UI elements, when the space is meant to be solid.  The way that the tabs become partially visible is fine if you're designing a Material-standard page, but for those of us using it as a platform to build on, having that bit of customization is useful if you're willing to take responsibility for responsive changes onto yourself.

**Comment by lax20attack** [comment] 2017-06-02 02:03
I am having the same issue as @aarmora. After spending a couple hours trying, I could not reproduce it easily in plunker. 

I am using md-tab-group in a md-grid-tile in an md-grid-list, which uses absolute position and flex.

Potentially related -https://github.com/angular/material/issues/5439

**Comment by tarasbobak** [comment] 2017-11-07 16:20
Here is a plnk showing a related issue. Mat tab labels width is set to 50%. There are two tabs. And when you click between them or  click several times on second tab. pagination becomes visible. 
http://plnkr.co/edit/sFKPyuakCFenhbvsfl3s?p=preview

Reproducible on Edge, IE10, 11.

**Comment by NejcCarl** [comment] 2018-03-03 09:40
I had a similar problem to the one described by others. I had two mat-tabs with 50% each, so the navigation should not appear. Indeed, it did not appear when coming from one route, but it did appear when coming from another. Upon clicking on the tab, the navigation disappeared (as it should).  

The issue (I think) was change detection on mat-tabs. I logged the width of component and navigation appeared when towards the end of loading the component stretches for ~30px. For me, the issue was gone after putting this into ngOnInit:
`setTimeout(() => {
        window.dispatchEvent(new Event('resize'));
      }, 20);`

**Comment by switch120** [comment] 2018-03-19 15:41
@NejcCarl - clever workaround; but I dare say to the Material team that it's certainly hacky and for my use-case it causes an unacceptable screen flash of those pagination arrows. I have tabs that are dynamically added based on a (locale) selection, and when changing from several tabs to a single (or just fewer), the arrows appear. I needed at least a 150ms timeout on your solution to make this work so unfortunately it's not deliverable in that state. Would be great to have the ability to just disable the pagination altogether instead of an event timeout or CSS hack. Thanks!

**Comment by karthickDhanapal** [comment] 2018-03-29 11:30
@NejcCarl I am having the same problem but why mat tabs are not change detected , when i open my developer tools  the pagination automatically disappear and working fine as expected

**Comment by Harmonickey** [comment] 2019-04-05 16:48
When you opened your developer tools, that initiates a resize event, which itself is fixing the problem temporarily.  Kind of like how @NejcCarl is hitting the resize trigger every 20 ticks.

**Comment by r0b3r70** [comment] 2019-06-20 13:03
> @NejcCarl - clever workaround; but I dare say to the Material team that it's certainly hacky and for my use-case it causes an unacceptable screen flash of those pagination arrows. I have tabs that are dynamically added based on a (locale) selection, and when changing from several tabs to a single (or just fewer), the arrows appear. I needed at least a 150ms timeout on your solution to make this work so unfortunately it's not deliverable in that state. Would be great to have the ability to just disable the pagination altogether instead of an event timeout or CSS hack.
> 
> FWIW, here's how I got rid of them:
> 
> ```
> ::ng-deep .mat-tab-header-pagination {
>     display: none !important;
> }
> ```

::ng-deep will be depricated

**Comment by austinwk** [comment] 2019-07-30 19:39
I also had this issue. In my case I had 4 tabs, each consuming 25% of the width of the parent. Adding `min-width: 0;` to `.mat-tab-link` fixed it for me.

I then had another issue with the pagination controls appearing _after_ a tab was clicked. Adding `padding: 0;` fixed that.

To answer another question from this thread, I am using Roboto.

```
.mat-tab-link {
  min-width: 0;
  padding: 0;
  width: 25%;
}
```

**Comment by ArDotWeb** [comment] 2019-09-15 17:12
If we see the following tabs in the mobile's browser, there are two buttons [**pagination controls**] (the first one is on the right side and the other is on the left side)

```
<mat-tab-group mat-stretch-tabs class="example-stretched-tabs mat-elevation-z4">
    <mat-tab label="Item-1"> Content 1 </mat-tab>
    <mat-tab label="Item-2"> Content 2 </mat-tab>
    <mat-tab label="Item-3"> Content 3 </mat-tab>
    <mat-tab label="Item-4"> Content 4 </mat-tab>
    <mat-tab label="Item-5"> Content 5 </mat-tab>
    <mat-tab label="Item-6"> Content 6 </mat-tab>
    <mat-tab label="Item-7"> Content 7 </mat-tab>
    <mat-tab label="Item-8"> Content 8 </mat-tab>
    <mat-tab label="Item-9"> Content 9 </mat-tab>
    <mat-tab label="Item-10"> Content 10 </mat-tab>
</mat-tab-group>
```
![Scroll](https://user-images.githubusercontent.com/21160242/64925002-d7489000-d7ff-11e9-8805-52d7dcafd402.png)


after removing the two buttons with the following code :
```
::ng-deep .mat-tab-header-pagination {
    display: none !important;
}

.mat-tab-label-container {
    display: flex;
    flex-grow: 1;
    overflow: hidden;
    z-index: 1;
    overflow-x: scroll !important;
}
```
 when we select item-10 we can not scroll left!
where is my problem? 

[DEMO](https://stackblitz.com/edit/angular-h3zh6s) (For testing first scroll right and then select item-10)

**Comment by fiscusmatt** [comment] 2019-10-01 04:48
Try unsetting the following CSS:

.mat-tab-list {
    transform: unset !important;
}

To scroll as the user selects a mat-tab-label a transform is applied to scroll the header:

transform: translateX(-75px);

**Comment by ArDotWeb** [comment] 2019-10-01 09:54
> Try unsetting the following CSS:
> 
> .mat-tab-list {
> transform: unset !important;
> }
> 
> To scroll as the user selects a mat-tab-label a transform is applied to scroll the header:
> 
> transform: translateX(-75px);

I did, but It does not work
[DEMO](https://angular-h3zh6s.stackblitz.io/)

**Comment by dksdheeraj** [comment] 2019-11-05 13:47
Hi ArDotWeb,

Having the same issue. Did anybody find the solution?

**Comment by jelbourn** [comment] 2019-11-07 14:00
This was done in #17409

**Closed by jelbourn** 2019-11-07 14:00 UTC
Labels: P3, feature
