### ISSUE TITLE
feat(cdkDrag): Specify drag clone location 

### ISSUE THREAD

**Issue by geometricpanda** [angular/components#20536] opened 2020-09-10 18:01 UTC
#### Feature Description

When dragging an element using cdkDrag, a clone is appended to body [see here](https://github.com/angular/components/blob/f951bf405ca0da9047afe558aaf2c74e5139b87a/src/cdk/drag-drop/drag-ref.ts#L734) 

Whilst end of body is a sensible default location, it'd be great if this were configurable to a DOM Element or ElementRef.

#### Use Case

We have an Angular component library which is built against a "global" CSS package.

Each selector in the global CSS package is selector scoped against a data attribute describing which brand is belongs to, such as `[data-theme="blue"] .button`

This enables a single microfrontend to be easily theme switched based on user / channel context.
Our `<body>` looks something akin to:
```html
...
<body>

    <div data-theme="blue">
        <app-one-root>
            <button class="button">Button</button>
        </app-one-root>
    <div>

    <div data-theme="red">
        <app-two-root>
            <button class="button">Button</button>
        </app-two-root>
    <div>

</body>
...
```
When using the Drag and Drop module, the clone is created outside either of the scoped themes so therefore the clone is unstyled so you get something like this:

```html
...
<body>

    <div data-theme="blue">
        <app-one-root>
            <button class="button">Button</button>
        </app-one-root>
    <div>

    <div data-theme="red">
        <app-two-root>
            <button class="button">Button</button>
        </app-two-root>
    <div>

    <button class="button cdk-drag cdk-drag-dragging">Button</button> <--- Outside of CSS scope

</body>
...
```

Whilst this problem doesn't happen when using style encapsulated components, we're unable to achieve the desired multi-theming thanks to having to support IE11 and it's lack of support for custom properties.

The only solution I can think of is similar to the CDK Portal, being able to control where it embeds.

**Comment by Achilles1515** [comment] 2020-09-10 20:52
This issue is being tracked here:
https://github.com/angular/components/issues/13288

**Comment by crisbeto** [comment] 2020-09-10 21:33
Closing as a duplicate of #13288.

**Closed by crisbeto** 2020-09-10 21:33 UTC
Labels: feature, needs triage
