### ISSUE TITLE
Make MatSlider Touch area bigger on small screens

### ISSUE THREAD

**Issue by hisham** [angular/components#15488] opened 2019-03-14 21:57 UTC
#### What is the expected behavior?

Should be easy to drag slider when on mobile. Sometimes when I drag slider when it's in beginning of range the slider does not engage and page wants to scroll horizontally instead. 

#### What is the current behavior?

The thumb/touch area of the slider seems too small. 

#### What are the steps to reproduce?
Play around with the basic slider at https://material.angular.io/components/slider/overview using an iPhone. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest

**Comment by jelbourn** [comment] 2019-05-12 15:46
Duplicate of #8000

**Closed by jelbourn** 2019-05-12 15:46 UTC
