### ISSUE TITLE
MatSelect `focused` property is incorrect

### ISSUE THREAD

**Issue by swseverance** [angular/components#14491] opened 2018-12-12 21:38 UTC
#### What is the expected behavior?

MatSelect's `focused` property should be `false` when a `blur` callback is triggered after clicking outside of the options panel.

#### What is the current behavior?

MatSelect's `focused` property is `true` when the `blur` callback is triggered after clicking outside of the options panel. However, `focused` is then `false` after a short period of time has elapsed.

#### What are the steps to reproduce?
Visit the following Stackblitz: https://stackblitz.com/edit/angular-891tlg
1. Click outside the options panel to close the MatSelect
2. The `onBlur` callback is invoked. Observe how `FOCUSED` is logged immediately, and `not focused` is logged after 1 second.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material 7.1.1

**Comment by nigel5** [comment] 2018-12-24 04:02
Good issue.

Is this the expected behaviour though? There is a test for it,
https://github.com/angular/material2/blob/d22f48c742c0bbdc971f79ea1261ec5c20d15a69/src/lib/select/select.spec.ts#L1149-L1150

Anyway, when the backdrop is clicked to close MatSelect, `this._focused` is indeed false, but `this._panelOpen` is still true probably due to the animation. Since the OR operator is used, `get focused()` will return true until the panel closes.

https://github.com/angular/material2/blob/d22f48c742c0bbdc971f79ea1261ec5c20d15a69/src/lib/select/select.ts#L320-L322

Can one of the Members take a look at this please?

**Comment by crisbeto** [comment] 2019-01-01 15:30
This is the intended behavior. The `focused` property is used mostly for telling the `MatFormField` how it should look and we want it to be highlighted while the panel is open.

**Comment by swseverance** [comment] 2019-01-03 12:07
Thanks for clarifying @crisbeto. The workaround I'm now using to determine if a user is truly no longer engaged with `MatSelect` involves checking the `relatedTarget` property when the `blur` event occurs. For example:

```typescript
onBlur(event: FocusEvent) {
  const relatedTarget = <HTMLElement>event.relatedTarget;
  const isMatOption = relatedTarget && relatedTarget.nodeName === 'MAT-OPTION';

  this.engaged = isMatOption ? true : false;
}
```

The assumption is that if the `relatedTarget` was the native element corresponding to a `MatOption` then the user is actually still engaged with the `MatSelect` even though a `blur` event occurred.

[Here's a StackBlitz that uses this approach](https://stackblitz.com/edit/angular-8xqwmn)

Do you think it would be appropriate to encapsulate this approach into an event emitter on `MatSelect` that emits when the user is no longer engaged with the control? Or perhaps my use case is too specific and this is not warranted.

**Comment by crisbeto** [comment] 2020-05-25 18:56
Closing since the mentioned property works as expected.

**Closed by crisbeto** 2020-05-25 18:56 UTC
Labels: area: material/select
