### ISSUE TITLE
bug(COMPONENT): TITLE Sticky does not stick in Angular 10

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#20094] opened 2020-07-25 18:32 UTC
#### Reproduction

We thought we had this solved here: https://github.com/angular/components/issues/19872

The stackblitz solution does not work in Angular 10. I reproduced the issue here:

https://github.com/fireflysemantics/mat-table-sticky

I can't do a Stackblitz, because it has to have an Angular 10 environment to be reproduced.

The rest of the issue is documented here:

https://stackoverflow.com/questions/63082745/getting-sticky-to-stick-without-sliding-over-in-angular-material-data-table

And here:

https://github.com/angular/components/issues/19872

**Comment by wagnermaciel** [comment] 2020-08-06 23:11
Duplicate of #19872
The issue you referenced is still open.

**Closed by wagnermaciel** 2020-08-06 23:11 UTC
Labels: area: material/table, needs triage
