### ISSUE TITLE
Allow dragged cdkDrag to stay visible in source list when entering another cdkDropList

### ISSUE THREAD

**Issue by Harpush** [angular/components#17838] opened 2019-11-29 10:42 UTC
#### Feature Description

Currently when dragging an item from a cdkDropList to another the item will get removed (visually) from the source list and enter the target list.
I want an option to allow the item to stay visible in the source list even when appearing in the target list.
The basics are already there - we can disable sorting and use the copy helper method but the missing part is the visual part.
Seems to me like instead of appending (remove from source and add to target) a new option for "copy" can be added.

#### Use Case

In my case i want something like a repository allowing to drag elements from one list to another while the source list doesn't get modified. The idea is having a list of possible controls which i can drag and each control can be dragged multiple times so it makes no sense to remove it visually and add it back once the item is placed.

Here is an example that theoretically works but when the preview is small and the lists are one on top of the other the dragging measurements are wrong (exactly the size of the inserted item):

https://stackblitz.com/edit/angular-o8exzv

**Comment by jelbourn** [comment] 2020-06-26 18:00
Duplicate of #13906

**Closed by jelbourn** 2020-06-26 18:00 UTC
Labels: area: cdk/drag-drop, feature, needs triage
