### ISSUE TITLE
bug(Date range selection): a form contain mat-date-range-input will trigger valueChanges 4 times

### ISSUE THREAD

**Issue by didididi2** [angular/components#20117] opened 2020-07-28 17:00 UTC
#### Reproduction

https://stackblitz.com/edit/angular-jm3fw2

Steps to reproduce:
1. Update the start or end date 
2.  see console : the form statusChanges  or valueChanges  triggers 4 times
 
 
#### Expected Behavior

one trigger

#### Actual Behavior

statusChanges or     valueChanges triggers 4 times

#### Environment

- Angular: 10.1
- CDK/Material: 10.1
- Browser(s): chrome 84
- Operating System (e.g. Windows, macOS, Ubuntu):  windows 10

**Comment by crisbeto** [comment] 2020-08-02 08:55
Duplicate of https://github.com/angular/components/issues/19776.

**Closed by crisbeto** 2020-08-02 08:55 UTC
Labels: area: material/datepicker
