### ISSUE TITLE
Cant make deep nested mat-options inside mat-select

### ISSUE THREAD

**Issue by Agonec-bozhij** [angular/components#10379] opened 2018-03-12 17:50 UTC
#### Bug, feature request, or proposal:
*ngTemplateOutlet not working with ng-container in mat-select

#### What is the expected behavior?
i expect to see mat-options generated in template in mat-select

#### What is the current behavior?
mat-select havnt any options

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/edit/angular-5fnbkr?embed=1&file=app/app.component.html

#### What is the use-case or motivation for changing an existing behavior?
to make available the creation of nested options inside mat-select

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
all info in stackblitz example provided above
https://stackblitz.com/edit/angular-5fnbkr?embed=1&file=app/app.component.html

rxjs: 5.5.6
core-js: 2.5.3
zone.js: 0.8.20
hammerjs: 2.0.8
@angular/cdk: 5.2.4
@angular/platform-browser-dynamic: 5.2.8
@angular/core: 5.2.8
@angular/http: 5.2.8
@angular/forms: 5.2.8
@angular/common: 5.2.8
@angular/router: 5.2.8
@angular/compiler: 5.2.8
@angular/material: 5.2.4
@angular/animations: 5.2.8
@angular/platform-browser: 5.2.8

**Comment by Frozen-byte** [comment] 2018-04-13 13:26
Very useable to have dynamic Grouping for your items, currently i need to copy-paste the <mat-option> Element through my code.

**Comment by LoganDupont** [comment] 2018-09-13 09:33
Is there a workaround for this problem at the moment?

**Comment by DenisSemionov** [comment] 2019-07-05 12:31
No updates?

**Comment by mmalerba** [comment] 2020-05-29 22:14
Unless I'm missing something, you should be able to acheive the same thing using `mat-optgroup` and `mat-option`, like this: https://stackblitz.com/angular/dljkbmrqvja?file=src%2Fapp%2Fselect-optgroup-example.html

**Comment by LoganDupont** [comment] 2020-06-03 07:42
@mmalerba I'm not sure but I thought that this issue was created because we don't have an option to create nested mat-options as `mat-optgroup` is not selectable. 

For example in my case I had some brands and each brand has multiple stores. The client should have the option to see the data (ex. number of visitors)  collected for one store or all the stores by selecting just the brand name. The reason why this should be nested is because we still want to give the client some structure so they can find their stores in an easy way.
![image](https://user-images.githubusercontent.com/6780720/83607925-52afc480-a57c-11ea-860f-be96e526cb90.png)

I am ofcourse not sure if this is the way to go to handle such things.

**Comment by mmalerba** [comment] 2020-06-03 19:57
Hmm ok, I didn't realize you wanted the groups to be selectable. I'll reopen this as a feature request, but we'll need to verify whether this actually makes sense from an accessibility standpoint

**Comment by crisbeto** [comment] 2021-04-12 17:09
Duplicate of https://github.com/angular/components/issues/8703.

**Closed by crisbeto** 2021-04-12 17:09 UTC
Labels: P5, area: material/select, feature, needs discussion
