### ISSUE TITLE
feat(DatePicker): Include Timepicker

### ISSUE THREAD

**Issue by vijhhh2** [angular/components#23950] opened 2021-11-11 08:48 UTC
### Feature Description

Hi Team,
Add Time picker component to the component list.
Current Issue is we need to reach out third party package for TimePicker with material design which is no guarantee when they will stop maintaining the project one I am using is stopped maintain and because of that one component its difficult for to update the my angular projects.

### Use Case

Time picker is used to pick time along with date picker component which eliminates the third party dependency for that particular component

**Comment by crisbeto** [comment] 2021-11-11 14:06
Duplicate of https://github.com/angular/components/issues/5648.

**Closed by crisbeto** 2021-11-11 14:06 UTC
Labels: feature, needs triage
