### ISSUE TITLE
bug(material-experimental/mdc-list): cannot compile scss after update to 11.2.2

### ISSUE THREAD

**Issue by debuggerpk** [angular/components#22409] opened 2021-04-06 13:02 UTC
Unable to compile scss after upgrading to `angular/core`, `angular/material` & `@angular/material-experiemental` with error

```
17 │ ┌       @include mdc-list-deprecated-item-disabled-text-color(
18 │ │         $mdc-list-deprecated-text-disabled-color, $query: $mat-theme-styles-query);
   │ └──────────────────────────────────────────────────────────────────────────────────^
```

#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:

```
ng update @angular/core
ng update @angular/material --force
yarn remove @angular/material-experimental material-components-web
yarn add @angular/material-experimental material-components-web
ng serve
``` 
 
 
#### Expected Behavior

What behavior were you expecting to see?
It should compile succesfully.

#### Actual Behavior

Throws out a scss error.

```
Error: ./apps/ng-outpost/src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
   ╷
17 │ ┌       @include mdc-list-deprecated-item-disabled-text-color(
18 │ │         $mdc-list-deprecated-text-disabled-color, $query: $mat-theme-styles-query);
   │ └──────────────────────────────────────────────────────────────────────────────────^
   ╵
  node_modules/@angular/material-experimental/mdc-core/option/_option-theme.scss 17:7  @content
  node_modules/@angular/material-experimental/mdc-helpers/_mdc-helpers.scss 228:3      mat-using-mdc-theme()
  node_modules/@angular/material-experimental/mdc-core/option/_option-theme.scss 12:3  mat-mdc-option-color()
  node_modules/@angular/material-experimental/mdc-core/option/_option-theme.scss 72:7  @content
  node_modules/@angular/material/core/theming/_theming.scss 342:3                      mat-private-check-duplicate-theme-styles()
  node_modules/@angular/material-experimental/mdc-core/option/_option-theme.scss 66:3  mat-mdc-option-theme()
  node_modules/@angular/material-experimental/mdc-core/_core-theme.scss 12:5           @content
  node_modules/@angular/material/core/theming/_theming.scss 342:3                      mat-private-check-duplicate-theme-styles()
  node_modules/@angular/material-experimental/mdc-core/_core-theme.scss 11:3           mat-mdc-core-theme()
  node_modules/@angular/material-experimental/mdc-theming/_all-theme.scss 27:5         @content
  node_modules/@angular/material/core/theming/_theming.scss 342:3                      mat-private-check-duplicate-theme-styles()
  node_modules/@angular/material-experimental/mdc-theming/_all-theme.scss 26:3         angular-material-mdc-theme()
  apps/ng-outpost/src/styles.scss 196:1                                                root stylesheet
```

My `styles.scss` at line 196.1 is

```scss
@include angular-material-mdc-theme($theme);
```

usual stuff going in the `scss` file.

```scss
$theme: mat-light-theme(
  (
    color: (
      primary: $theme-primary,
      accent: $theme-accent,
      // warn: $slogr-warn,
    ),
    typography: $typography-config,
    density: minimum,
  )
);

// Theme Init
@include angular-material-theme($theme);
@include angular-material-mdc-theme($theme);


```

#### Environment

- Angular: 11.2.7
- CDK/Material: 11.2.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2021-04-06 15:07
Can you try installing `material-components-web@11.0.0-canary.0cde52f5a.0`? We had an issue where the version published to npm had the wrong dependency. It has since been resolved, but there are a few versions on npm that may be incorrect.

**Comment by crisbeto** [comment] 2021-04-12 16:47
Can you try updating to version `11.2.8`? The build error I mentioned above should be resolved there.

**Comment by debuggerpk** [comment] 2021-04-12 23:56
Thanks @crisbeto, still getting the same error

```log
SassError: SassError: Undefined mixin.
   ╷
17 │ ┌       @include mdc-list-deprecated-item-disabled-text-color(
18 │ │         $mdc-list-deprecated-text-disabled-color, $query: $mat-theme-styles-query);
   │ └──────────────────────────────────────────────────────────────────────────────────^
```

i cannot find the text `mdc-list-deprecated` anywhere in the code repo, both here and on web-components.

For furthur triage, i am pasting the rest of my scss

```scss
/**
* Generated theme by Material Theme Generator
* https://materialtheme.arcsine.dev
*/

@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');

// Custom Theming for Angular Material
// For more information: https://material.angular.io/guide/theming
@import '~@angular/material/theming';
@import '~@angular/material-experimental/mdc-theming/all-theme';
@import './styles/main.scss';
// Include the common styles for Angular Material. We include this here so that you only
// have to load a single css file for Angular Material in your app.

// Fonts
@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');

$typography-config: mat-typography-config(
  $font-family: 'Inter, sans-serif',
  $display-4: mat-typography-level(93px, 93px, 300, 'Inter', -0.0134em),
  $display-3: mat-typography-level(58px, 58px, 300, 'Inter', -0.0089em),
  $display-2: mat-typography-level(47px, 47px, 400, 'Inter', 0em),
  $display-1: mat-typography-level(33px, 40px, 400, 'Inter', 0.0074em),
  $headline: mat-typography-level(23px, 30px, 400, 'Inter', 0em),
  $title: mat-typography-level(19px, 30px, 500, 'Inter', 0.0075em),
  $subheading-2: mat-typography-level(16px, 28px, 400, 'Inter', 0.0094em),
  $subheading-1: mat-typography-level(14px, 24px, 500, 'Inter', 0.0067em),
  $body-2: mat-typography-level(14px, 20px, 500, 'Inter', 0.0179em),
  $body-1: mat-typography-level(14px, 24px, 400, 'Inter', 0.0179em),
  $button: mat-typography-level(16px, 14px, 500, 'Inter', 0.0893em),
  $caption: mat-typography-level(12px, 20px, 400, 'Inter', 0.0333em),
  $input: mat-typography-level(inherit, 1.125, 400, 'Inter', 1.5px),
);

// Foreground Elements

// Light Theme Text
$dark-text: #000000;
$dark-primary-text: rgba($dark-text, 0.87);
$dark-accent-text: rgba($dark-primary-text, 0.54);
$dark-disabled-text: rgba($dark-primary-text, 0.38);
$dark-dividers: rgba($dark-primary-text, 0.12);
$dark-focused: rgba($dark-primary-text, 0.12);

$mat-light-theme-foreground: (
  base: black,
  divider: $dark-dividers,
  dividers: $dark-dividers,
  disabled: $dark-disabled-text,
  disabled-button: rgba($dark-text, 0.26),
  disabled-text: $dark-disabled-text,
  elevation: black,
  secondary-text: $dark-accent-text,
  hint-text: $dark-disabled-text,
  accent-text: $dark-accent-text,
  icon: $dark-accent-text,
  icons: $dark-accent-text,
  text: $dark-primary-text,
  slider-min: $dark-primary-text,
  slider-off: rgba($dark-text, 0.26),
  slider-off-active: $dark-disabled-text,
);

// Dark Theme text
$light-text: #ffffff;
$light-primary-text: $light-text;
$light-accent-text: rgba($light-primary-text, 0.7);
$light-disabled-text: rgba($light-primary-text, 0.5);
$light-dividers: rgba($light-primary-text, 0.12);
$light-focused: rgba($light-primary-text, 0.12);

$mat-dark-theme-foreground: (
  base: $light-text,
  divider: $light-dividers,
  dividers: $light-dividers,
  disabled: $light-disabled-text,
  disabled-button: rgba($light-text, 0.3),
  disabled-text: $light-disabled-text,
  elevation: black,
  hint-text: $light-disabled-text,
  secondary-text: $light-accent-text,
  accent-text: $light-accent-text,
  icon: $light-text,
  icons: $light-text,
  text: $light-text,
  slider-min: $light-text,
  slider-off: rgba($light-text, 0.3),
  slider-off-active: rgba($light-text, 0.3),
);

// Background config
// Light bg
$light-background: #fafafa;
$light-bg-darker-5: darken($light-background, 5%);
$light-bg-darker-10: darken($light-background, 10%);
$light-bg-darker-20: darken($light-background, 20%);
$light-bg-darker-30: darken($light-background, 30%);
$light-bg-lighter-5: lighten($light-background, 5%);
$dark-bg-tooltip: lighten(#2c2c2c, 20%);
$dark-bg-alpha-4: rgba(#2c2c2c, 0.04);
$dark-bg-alpha-12: rgba(#2c2c2c, 0.12);

$mat-light-theme-background: (
  background: $light-background,
  status-bar: $light-bg-darker-20,
  app-bar: $light-bg-darker-5,
  hover: $dark-bg-alpha-4,
  card: $light-bg-lighter-5,
  dialog: $light-bg-lighter-5,
  tooltip: $dark-bg-tooltip,
  disabled-button: $dark-bg-alpha-12,
  raised-button: $light-bg-lighter-5,
  focused-button: $dark-focused,
  selected-button: $light-bg-darker-20,
  selected-disabled-button: $light-bg-darker-30,
  disabled-button-toggle: $light-bg-darker-10,
  unselected-chip: $light-bg-darker-10,
  disabled-list-option: $light-bg-darker-10,
);

// Dark bg
$dark-background: #2c2c2c;
$dark-bg-lighter-5: lighten($dark-background, 5%);
$dark-bg-lighter-10: lighten($dark-background, 10%);
$dark-bg-lighter-20: lighten($dark-background, 20%);
$dark-bg-lighter-30: lighten($dark-background, 30%);
$light-bg-alpha-4: rgba(#fafafa, 0.04);
$light-bg-alpha-12: rgba(#fafafa, 0.12);

// Background palette for dark themes.
$mat-dark-theme-background: (
  background: $dark-background,
  status-bar: $dark-bg-lighter-20,
  app-bar: $dark-bg-lighter-5,
  hover: $light-bg-alpha-4,
  card: $dark-bg-lighter-5,
  dialog: $dark-bg-lighter-5,
  tooltip: $dark-bg-lighter-20,
  disabled-button: $light-bg-alpha-12,
  raised-button: $dark-bg-lighter-5,
  focused-button: $light-focused,
  selected-button: $dark-bg-lighter-20,
  selected-disabled-button: $dark-bg-lighter-30,
  disabled-button-toggle: $dark-bg-lighter-10,
  unselected-chip: $dark-bg-lighter-20,
  disabled-list-option: $dark-bg-lighter-10,
);

// Compute font config
@include mat-core($typography-config);

$mat-primary: (
  main: $slogr-primary-main,
  lighter: $slogr-primary-lighter,
  darker: $slogr-primary-darker,
  // For slide toggle,
  contrast:
    (
      main: $light-primary-text,
      lighter: $dark-primary-text,
      darker: $light-primary-text,
    ),
);

$theme-primary: mat-palette($mat-primary, main, lighter, darker);

$mat-accent: (
  main: #aeed00,
  lighter: #e4ff54,
  darker: #79ba00,
  // For slide toggle,
  contrast:
    (
      main: $dark-primary-text,
      lighter: $dark-primary-text,
      darker: $dark-primary-text,
    ),
);
$theme-accent: mat-palette($mat-accent, main, lighter, darker);

$theme: mat-light-theme(
  (
    color: (
      primary: $theme-primary,
      accent: $theme-accent,
      // warn: $slogr-warn,
    ),
    typography: $typography-config,
    density: minimum,
  )
);

// Theme Init
@include angular-material-theme($theme);
@include angular-material-mdc-theme($theme);
```

There are only two mixins that i am using,

```scss
@mixin align-center() {
  display: flex;
  justify-content: center;
  align-items: center;
}

@mixin shadow($type) {
  @if $type== 'icon' {
    box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.14), 0px 1px 3px rgba(0, 0, 0, 0.2);
  }

  @if $type== 'card' {
    box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.14), 0px 2px 1px rgba(0, 0, 0, 0.12), 0px 1px 3px rgba(0, 0, 0, 0.2);
  }
}
```

Please advise.

**Comment by debuggerpk** [comment] 2021-04-13 00:47
if we go by this [file](https://github.com/angular/components/blob/master/src/material-experimental/mdc-core/option/_option-theme.scss)  and [line 20](https://github.com/angular/components/blob/master/src/material-experimental/mdc-core/option/_option-theme.scss#L20) .. then we should have a mixin as `deprecated-item-disabled-text-color` in `@material/list`.

```scss
@use './mixins';
@include mixins.deprecated-core-styles;
```

The above code is from [@material/list/mdc-list.scss](https://github.com/material-components/material-components-web/blob/5f0fc444a706626a106c2b36116a56e9dc5b8c79/packages/mdc-list/mdc-list.scss). On close inspection of `deprecated-core-styles` from [@material/list/_mixins.scss](https://github.com/material-components/material-components-web/blob/5f0fc444a706626a106c2b36116a56e9dc5b8c79/packages/mdc-list/_mixins.scss#L738)], we can find this 

```scss
@mixin deprecated-item-disabled-text-color(
  $color,
  $query: feature-targeting.all()
) {
  $feat-color: feature-targeting.create-target($query, color);

  .mdc-deprecated-list-item--disabled {
    .mdc-deprecated-list-item__text,
    .mdc-deprecated-list-item__primary-text,
    .mdc-deprecated-list-item__secondary-text {
      @include feature-targeting.targets($feat-color) {
        @include theme.prop(color, $color);
      }
    }
  }
}

I have recloned my repo, cleared my yarn cache, removed yarn.lock just to make sure that something is not wrong with my setup .. but i still have the issue. 
```

**Comment by lqc** [comment] 2021-04-27 13:56
The material-experimental SCSS is currently broken. Since @angular/components v11.2.2, the code tries to use mixins that are only present in MCW v11.0.0 - but if you upgrade to that version, the mdc-checkbox SCSS stops working because v11 moved deprecated styles that it uses.

So it seems there are no released @angular/components and MCW versions that you can make work.

**Comment by Splaktar** [comment] 2021-04-30 01:45
It would be really helpful if someone could provide a StackBlitz that demonstrates this issue.

**Comment by Splaktar** [comment] 2021-04-30 02:02
I took a [cut at it](https://stackblitz.com/edit/material-experimental-v11?file=src%2Fstyles.scss), but it blows up with
```
Error in src/styles.scss
Error: ENOENT: No such file or directory., '/dev/null'
```
That does away and I get errors if I comment out
```
// @import '~@angular/material-experimental/mdc-theming/all-theme';
```
And it works if I remove all references to `material-experimental`: https://stackblitz.com/edit/material-experimental-v11-ogu6ky?file=src%2Fstyles.scss

**Comment by Splaktar** [comment] 2021-04-30 19:47
Here's a GitHub-based reproduction using material.angular.io's 11.x branch: https://github.com/DevIntent/material.angular.io/tree/11.x-with-experimental-theme

```scss
Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
   ╷
17 │ ┌       @include mdc-list-deprecated-item-disabled-text-color(
18 │ │         $mdc-list-deprecated-text-disabled-color, $query: $mat-theme-styles-query);
   │ └──────────────────────────────────────────────────────────────────────────────────^
   ╵
  node_modules/@angular/material-experimental/mdc-core/option/_option-theme.scss 17:7  @content
  node_modules/@angular/material-experimental/mdc-helpers/_mdc-helpers.scss 228:3      mat-using-mdc-theme()
  node_modules/@angular/material-experimental/mdc-core/option/_option-theme.scss 12:3  mat-mdc-option-color()
  node_modules/@angular/material-experimental/mdc-core/option/_option-theme.scss 72:7  @content
  node_modules/@angular/material/core/theming/_theming.scss 342:3                      mat-private-check-duplicate-theme-styles()
  node_modules/@angular/material-experimental/mdc-core/option/_option-theme.scss 66:3  mat-mdc-option-theme()
  node_modules/@angular/material-experimental/mdc-core/_core-theme.scss 12:5           @content
  node_modules/@angular/material/core/theming/_theming.scss 342:3                      mat-private-check-duplicate-theme-styles()
  node_modules/@angular/material-experimental/mdc-core/_core-theme.scss 11:3           mat-mdc-core-theme()
  node_modules/@angular/material-experimental/mdc-theming/_all-theme.scss 27:5         @content
  node_modules/@angular/material/_theming.scss 1755:3                                  mat-private-check-duplicate-theme-styles()
  node_modules/@angular/material-experimental/mdc-theming/_all-theme.scss 26:3         angular-material-mdc-theme()
  src/styles.scss 12:1                                                                 root stylesheet
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/splaktar/Git/angular/material.angular.io/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:91135:16)
    at _render_closure1.call$2 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:80011:12)
    at _RootZone.runBinary$3$3 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:27197:18)
    at _FutureListener.handleError$1 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:25725:19)
    at _Future__propagateToListeners_handleError.call$0 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:26022:49)
    at Object._Future__propagateToListeners (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:4543:77)
    at _Future._completeError$2 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:25855:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:25198:12)
    at Object._asyncRethrow (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:4292:17)
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:13200:20
    at _wrapJsFunctionForAsync_closure.$protected (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:4317:15)
```

**Comment by Splaktar** [comment] 2021-04-30 19:52
The above repro was using `"material-components-web": "10.0.0-canary.2ed2d829b.0",` and the StackBlitz I posted is using `"material-components-web": "9.0.0",` and [here's one](https://stackblitz.com/edit/material-experimental-v11-qv3x9h?file=src%2Fstyles.scss) with `"material-components-web": "10.0.0",` and [another](https://stackblitz.com/edit/material-experimental-v11-yeemtu?file=src%2Fstyles.scss) with `"material-components-web": "11.0.0",`.

**Comment by Splaktar** [comment] 2021-05-01 02:47
The 11.2.x branch of `angular/components` uses `"material-components-web": "^11.0.0-canary.3201cae47.0"` (from PR https://github.com/angular/components/pull/21968) for development but when `"@angular/material-experimental": "^11.2.11"` is installed in a project it comes with the following
```json
  "peerDependencies": {
    "@angular/core": "^11.0.0 || ^12.0.0-0",
    "@angular/material": "11.2.11",
    "material-components-web": "^9.0.0-canary.419e03572.0"
  },
```
This is due to https://github.com/angular/components/blob/28a6d0c818e607682df39c2c1c4fe1324e49ba6c/packages.bzl#L5

[This StackBlitz](https://stackblitz.com/edit/material-experimental-v11-gejayu?file=src%2Fstyles.scss) uses `"material-components-web": "^11.0.0-canary.3201cae47.0",` but it has the same issue with building. If I try this version in material.angular.io, I get a different error:
```scss
Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import '@material/chips/mixins.import';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/@angular/material-experimental/mdc-chips/_chips-theme.scss 1:9         @forward
  node_modules/@angular/material-experimental/mdc-chips/_chips-theme.import.scss 1:1  @import
  node_modules/@angular/material-experimental/mdc-theming/_all-theme.scss 6:9         @import
  src/styles.scss 2:9                                                                 root stylesheet
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/splaktar/Git/angular/material.angular.io/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:91135:16)
    at _render_closure1.call$2 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:80011:12)
    at _RootZone.runBinary$3$3 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:27197:18)
    at _FutureListener.handleError$1 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:25725:19)
    at _Future__propagateToListeners_handleError.call$0 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:26022:49)
    at Object._Future__propagateToListeners (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:4543:77)
    at _Future._completeError$2 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:25855:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:25198:12)
    at Object._asyncRethrow (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:4292:17)
    at /Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:13200:20
    at _wrapJsFunctionForAsync_closure.$protected (/Users/splaktar/Git/angular/material.angular.io/node_modules/sass/sass.dart.js:4317:15)
````

If I change material.angular.io to use `"material-components-web": "^9.0.0"` or `"material-components-web": "9.0.0-canary.419e03572.0"`, I get the same error as the OP and https://github.com/angular/components/issues/22409#issuecomment-830342198.

**Comment by Splaktar** [comment] 2021-05-01 03:23
To fix the above issue with the chips `mixins.import`, I can install `"@material/chips": "11.0.0-canary.3201cae47.0"` into the project. It was already there, but without it being explicitly in the `package.json`, the import of `@import '@material/chips/mixins.import';` doesn't work since it doesn't have a `~` at the start. Installing the package explicitly removed the need for that.

**Comment by Splaktar** [comment] 2021-05-01 03:31
On the deprecated list styles issue, PR https://github.com/angular/components/pull/21968 is what renamed those mixin references and updated to `"material-components-web": "^11.0.0-canary.3201cae47.0"`.

**Comment by Splaktar** [comment] 2021-05-01 03:52
OK, this regression was introduced in `11.2.2`. So if you install `@angular/material-experimental: "11.2.1"` then you shouldn't see this issue.

**Comment by Splaktar** [comment] 2021-05-01 04:31
> The material-experimental SCSS is currently broken. Since @angular/components v11.2.2, the code tries to use mixins that are only present in MCW v11.0.0 - but if you upgrade to that version, the mdc-checkbox SCSS stops working because v11 moved deprecated styles that it uses.
> 
> So it seems there are no released @angular/components and MCW versions that you can make work.

@lqc it would be helpful if you could open a separate issue for the `mdc-checkbox` Sass issue and link it here. I am not able to reproduce that atm with `"material-components-web": "^11.0.0-canary.3201cae47.0"`.

**Comment by Splaktar** [comment] 2021-05-01 04:35
The following combo should work
- `"material-components-web": "11.0.0-canary.3201cae47.0"`
- `"@angular/material-experimental": "11.2.11",`

PR https://github.com/angular/components/pull/22608 updates the `peerDependencies` in 11.2.x to be `"material-components-web": "^11.0.0-canary.3201cae47.0"`.

**Comment by lqc** [comment] 2021-05-01 18:41
@Splaktar Ok, I'll do that (did you try with just "^11.0.0" version?)

**Comment by Splaktar** [comment] 2021-05-01 21:01
Just 11.0.0 won't work as far as I remember.

**Comment by Splaktar** [comment] 2021-05-13 18:12
This is fixed in https://github.com/angular/components/commit/b5224ea4a99b55678faed5d6b8546007b820d39b which should be part of `11.2.11`.

**Comment by debuggerpk** [comment] 2021-05-14 03:47
Thanks Splaktar

**Comment by mmalerba** [comment] 2021-05-14 13:59
I don't think we're planning to do another 11 patch release actually

**Comment by Splaktar** [comment] 2021-05-19 21:05
Fixed in https://github.com/angular/components/releases/tag/11.2.13

**Closed by Splaktar** 2021-05-19 21:05 UTC
Labels: P2, area: theming, has pr
