### ISSUE TITLE
bug(COMPONENT): MAT-LIST-ITEM Meta button not clickable

### ISSUE THREAD

**Issue by alexcibotari** [angular/components#26093] opened 2022-11-26 17:08 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

mat-list-item button located in matListItemMeta is not clickable anymore

https://m2.material.io/components/lists#usage

```
<mat-nav-list>
  <mat-list-item *ngFor="let component of components">
    <mat-icon matListItemIcon>{{component .icon}}</mat-icon>
    <span matListItemTitle>{{component.name}}</span>
    <span matListItemLine>{{component.displayName}}</span>
    <span matListItemMeta>
      <button mat-icon-button (click)="delete($event)">
        <mat-icon>delete</mat-icon>
      </button>
      <mat-icon>navigate_next</mat-icon>
    </span>
  </mat-list-item>
</mat-nav-list>
```

### Reproduction

Steps to reproduce:
1.  Add a button in the list-item meta
2. Click on the button

### Expected Behavior

button event triggered

### Actual Behavior

button event is not triggered

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.0
- Browser(s): Any
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment] 2022-11-26 18:28
Duplicate of https://github.com/angular/components/issues/26011.

**Closed by crisbeto** 2022-11-26 18:28 UTC
Labels: needs triage
