### ISSUE TITLE
[Tabs] Add ability to disable animations

### ISSUE THREAD

**Issue by ciesielskico** [angular/components#2706] opened 2017-01-18 10:52 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
I would like to disable the slide-in animation

#### What is the current behavior?
The slide-in animation cannot be disabled.

#### What is the use-case or motivation for changing an existing behavior?
I have a couple of tabs, which are rendered using `*ngFor`. 

The data is retrieved from `ngrx/store` and upon any change of state, the tabs get rerendered and slide-in again, which sucks for UX.

#### Which versions of Angular, Material, OS, browsers are affected?
@angular/material: 2.0.0-beta.1

**Comment by fxck** [comment] 2017-01-18 13:09
Have you tried adding `trackBy` to that `*ngFor`?

**Comment by ciesielskico** [comment] 2017-01-19 08:00
Yes but it works only partially.

I have a nested `md-tab-group` (one inside the other) and the `trackBy` helps on the parent `md-tab-group`. 
The inner tab-group still gets rerendered on every change.

**Comment by fxck** [comment] 2017-01-19 08:01
Even if you put trackBy on both?

**Comment by ciesielskico** [comment] 2017-01-19 08:05
Yes, even with two trackBys

```
<md-tab-group>
    <md-tab [label]="group.name" *ngFor="let group of groups | async; trackBy group?.id">

        <md-tab-group>
            <md-tab [label]="table.name" *ngFor="let table of group.tables; trackBy table?.id">

                <!-- ... -->

            </md-tab>
        </md-tab-group>

    </md-tab>
</md-tab-group>
```

I work with ngrx and the table gets rebuilt and sorted on every change, will have to rethink my data structure.

**Comment by ciesielskico** [comment] 2017-01-19 08:53
Ok my bad, I have been googling trackBy a little more and I implemented it incorrectly.
I've changed the group?.id to `trackByFn` and in my controller I have:

```
trackByFn(index, item) { return item.id; }
```

The tabs don't get rerendered anymore, thanks.

**Comment by mateuszwitkowski** [comment] 2017-02-17 12:48
Anyone knows how can I turn those animations off? I have "heavy" content inside tabs . It is fetched (and need to be fetched) from backend one every switch between tabs. Without animations it worked well but now it jam and freeze. I thought I could overrie CSS styles but it's defined inside Component decorator in tab-body.

**Comment by evanjmg** [comment] 2017-02-20 16:15
+1

**Comment by geshort** [comment] 2017-04-12 01:22
+1

**Comment by BrunnerLivio** [comment] 2017-05-09 11:52
+1

**Comment by sharpevo** [comment] 2017-05-12 03:36
@BrunnerLivio Awesome, I made some changes for the new version:

```
<md-tab-group [(selectedIndex)]="selectedIndex">
    <md-tab label="one"></md-tab>
    <md-tab label="two"></md-tab>
    <md-tab label="three"></md-tab>
</md-tab-group>
<section *ngIf="selectedIndex === 0">ONE</section>
<section *ngIf="selectedIndex === 1">TWO</section>
<section *ngIf="selectedIndex === 2">THREE</section>
```

**Comment by MikeInSwitzerland** [comment] 2017-06-20 08:22
Yup, it's a bit bizarre that this option wasn't provided.  It looks great the first time you see the animation, but soon drives you mad...

**Comment by m98** [comment] 2017-06-28 11:19
@jelbourn 
Any progress on this feature request? I don't mean trick, something like `animation="false"`

**Comment by VasilenkoAlex** [comment] 2017-07-19 13:55
+1.
I encountered need for animation switch when i tried to put element with fixed position into <md-tab-body>. In latest chrome fixed position will not work if any of parent elements have transform CSS property.

**Comment by lokeshdaiya** [comment] 2017-07-28 09:07
@mateuszwitkowski @jelbourn  You can disable animation using @.disbaled property which is introduced in angular 4.3.1.
Here is working  plnkr https://plnkr.co/edit/sVJM8H?p=preview

**Comment by m98** [comment] 2017-08-09 10:35
Thanks @lokeshdaiya 
`@.disabled` works as expected for me! But actually I don't understand how does it work :thinking: 

Because the tab buttons still have animations, but the tab content animation disabled as well! 

I wonder if there is any performance concern for using `@.disabled`!

**Comment by rich4756** [comment] 2017-09-20 22:43
`[@.disabled]="true"` works nicely for me as well. Can someone explain how this works?

**Comment by andrewseguin** [comment] 2017-10-19 18:19
The tabs use the Angular animations framework for its animations. By using `@.disabled`, you are telling the framework not to perform animations for the tabs, which is as performant as you can get.

**Comment by tw3** [comment] 2017-10-27 14:12
We should point out that certain components fail to work if you disable animation using the @.disabled property.  E.g. the mat-sidenav component stops working:

https://stackblitz.com/edit/angular-material2-sidenav-disable-animation-issue

**Comment by tarasbobak** [comment] 2017-11-06 16:36
I'm facing issues with this approach. When I set [@.disabled]="true" for mat-tab-group and have a nested tab-group inside it disables animation for both, while I want only for the parent. Animation is also disabled for the expansion panel inside the second md-tab-group.
It look like I'll have to use the previously stated ngIf approach.

**Comment by MigCoder** [comment] 2017-11-16 06:40
[@.disabled]="true" works for components like tabs, but not works for Select component, any ideas?

**Comment by gotstu** [comment] 2017-11-28 21:46
+1 works for me and now how a new thing to learn in [@.disabled]="true". Thanks

**Comment by finalxcode** [comment] 2017-12-01 08:46
cool

**Comment by zijianhuang** [comment] 2017-12-18 06:40
lokeshdaiya had suggested a good solution. However, this feature should not be closed, because mat-tab-nav-bar + mat-tab-link does not have the sliding animation. It makes sense that matTab and matLink are consistent with or without sliding animation effect. Please reopen this feature request.

**Comment by aldo-roman** [comment] 2017-12-26 18:26
`[@.disabled]="true"` is not legible

Any new developer to the codebase will understand this attribute disables the tab component behavior, not the animations. Can we re-discuss implementing something like `[enableAnimations=false]`

**Comment by viksakshum** [comment] 2018-01-10 06:23
also as mentioned earlier that this breaks the sidenav component,

**Comment by dhniels** [comment] 2018-02-07 17:50
@aldo-roman has a good solution. It'd be nice to have a global and/or component level setting to disable all of material's animations. +1 for this feature, or a way to do this easily.

**Comment by craftyInstigator** [comment] 2018-02-18 07:28
[@.disabled] is not a valid solution. Using [@.disabled] on mat-tab-group disabled all animations inside tabs.

**Comment by dhniels** [comment] 2018-03-13 17:49
im unable to get [@.disabled]="true" working on mat-menu items. seems like this solution only works on certain elements...

**Comment by arsyed04** [comment] 2018-04-08 12:15
Any update on disabling animations in tabs?

**Comment by androidovshchik** [comment] 2018-05-03 11:43
Another approach is a hackie with route navigation
```
this.router.routeReuseStrategy.shouldReuseRoute = function() {
    return false;
};
this.router.navigate(['your-page']);
```
This will be same as `*ngIf` condition and also it's important to define a route param, e.g. `:tab`
```
{
   path: 'your-path/:tab',
   component: YourComponent
}
```

**Comment by simeyla** [comment] 2018-05-18 00:32
I just find this astonishingly obtuse.

The property `disableRipple` is all over the place, so how hard is it to just add `disableTabSlide` or something similar. It's a very nice effect sometimes, but some types of content just look awful and confusing with a slide animation. 

Something so simple and obviously sought after shouldn't take a year and a half of discussion :-(

**Comment by mstawick** [comment] 2018-05-25 01:03
If using the [@.disabled] workaround, is there a way to re-enable animations for components inside tabs? I've tried adding [@.disabled]="false" inside, but to no avail.

**Comment by babeal** [comment] 2018-06-05 20:38
I am going to second this as well.  On large full page tabs, the animation is pretty poor.  We should have the ability to turn them off explicitly or even better to assign animations and transitions to use with a noop animation to turn them off.

**Comment by CodySchrank** [comment] 2018-06-16 07:46
Got sick of looking at those animations.  Hopefully this is enough.

**Comment by wynhou** [comment] 2018-08-29 18:16
Please add a toggle to disable animations, we deal with massive pages and having the entire page scroll either slows down the animation or makes it absolutely unusable.

Using disabled = true doesn't work as it disables all animation inside the tab.

Huge defect in my opinion.

**Comment by stephengardner** [comment] 2018-09-11 18:07
Still an open issue.  Please re-open

**Comment by CodySchrank** [comment] 2018-09-11 18:47
I tried to write a PR for this a couple months ago, honestly this issue isn't going to be resolved unless the mat-tab is rewritten from the ground up.  It was designed only with the animations in mind, and unfortunately angular doesn't provide a way to disable animations for one component without it propagating down to other ones.

**Comment by simeyla** [comment] 2018-09-11 18:57
@CodySchrank Thanks for the additional info. Helpful for some insight into the implementation, it's always easy for us on the outside to assume something is super easy when it isn't.

With that said it's not that we want to DISABLE an animation using angular's funky [@.disabled] notation - it's that we just don't want the animation there in the first place. Surely that can't be so difficult. The tab isn't animating itself of its own free will - there's code there to do it! 

In fact - here I just fixed it in 30 seconds. This is all people are asking for :

```

@Input('disableSlideEffect') disableSlideEffect

<div class="mat-tab-body-content" #content
     [@translateTab]="disableSlideEffect ? null : _position"
     (@translateTab.start)="_onTranslateTabStarted($event)"
     (@translateTab.done)="_onTranslateTabComplete($event)">
  <ng-template matTabBodyHost></ng-template>
</div>
```

I really don't want to duplicate the whole mat-tab control just to make this change. I have one tab control where people would routinely tab back and forth between two 'screens' and it's just a disaster for it to be animated. Still hoping for a change before I have to release it though. But what to say to my boss when he says 'make it not slide'. That's a days worth of work.... :-/

Really hope you can help make this happen :-) Thanks

**Comment by andrei-ilyukovich** [comment] 2018-10-18 07:54
@simeyla unfortunately your example doesn't work properly. Setting to null [@translateTab] property completely turns off animation and no more @translateTab.start and @translateTab.done events are fired. But it is bad as component code make some computation based on these events.

**Comment by mik01aj** [comment] 2018-10-31 15:59
See issue #13428 and PR #13505. The option is already there. This bug can be closed.

**Comment by babeal** [comment] 2018-10-31 18:02
Ugh we just duplicated the material tab and remove animations :(.

**Comment by leopardy** [comment] 2019-01-08 04:47
What are valid values for animationDuration? I was trying to have no animation happen.

I used `<mat-tab-group mat-stretch-tabs [animationDuration]="0" id="tab-group">`

and received error
```
Unable to process animations due to the following failed trigger transitions
 @translateTab has failed due to:

- The provided timing value "0 cubic-bezier(0.35, 0, 0.25, 1)" is invalid.
```

I thought maybe I needed '0ms' but then I received `Parser Error: Unexpected token 'ms' at column 2 in [0ms]`

**Comment by leopardy** [comment] 2019-01-08 13:49
> What are valid values for animationDuration? I was trying to have no animation happen.
> 
> I used `<mat-tab-group mat-stretch-tabs [animationDuration]="0" id="tab-group">`
> 
> and received error
> 
> ```
> Unable to process animations due to the following failed trigger transitions
>  @translateTab has failed due to:
> 
> - The provided timing value "0 cubic-bezier(0.35, 0, 0.25, 1)" is invalid.
> ```
> I thought maybe I needed '0ms' but then I received `Parser Error: Unexpected token 'ms' at column 2 in [0ms]`

*facepalm*. I was just missing using both quotes . This worked [animationDuration]="'0ms'"

**Comment by zijianhuang** [comment] 2019-01-30 05:48
`<mat-tab-group animationDuration="0">` should fix the problem. This case can be closed now.

@leopardy, animationDuration is a string property, you should use what I had illustrated above, or 
use `[animationDuration]="'0ms'"` that you had found.

Since you just want to disable animation, the first form with a string constant is simpler thus preferred. 

animationDuration was released with https://github.com/angular/material2/issues/13428, however, not documented in the changelog somehow, until v7.3 while I am using 7.2.1.

**Comment by jelbourn** [comment] 2019-10-31 17:17
This was done a while back

**Closed by jelbourn** 2019-10-31 17:17 UTC
Labels: P4, feature
