### ISSUE TITLE
Drag and Drop in nested DropLists

### ISSUE THREAD

**Issue by tlorenz9** [angular/components#14939] opened 2019-01-24 09:14 UTC
I've got a problem with the Drag and Drop Feature. I'm trying to use nested DropLists which can be nested arbitrary deep. It is not possible to drag items into the third level of the DropLists.
In addition to this the items jump back and forth when dragging from the first to the second level.

The workaround from [here](https://stackoverflow.com/questions/53271834/nested-drag-and-drop-in-with-angular-7-material-cdk) fixed the issue with the jumping items from the first to levels. But it doesn't fix the issue of dropping items into the third layer.

I've coded a minimal and a more complex example to show the problems.

[Code](https://stackblitz.com/edit/draganddropexample)

In the complex example removing the items from the DropLists doesn't work (seems to be a problem with the model not refreshing the UI, so nevermind. I'm trying to fix it soon.). The complex example includes more encapsulated components. The simple one is just two components that are handling the Drag and Drop. The simple example includes the workaround mentioned above, which fixes the jumping between the first and the second level. 

I expect, when dragging the _2_ in the simple example to the drop-area of _Composite 1.1_ (between _Leaf 1.1.1_ and _Leaf 1.1.2_), the item to drop into _Composite 1.1_. But this does not happen. In addition to that the item jumps back and forth, when its over the _Composite 1.1_ box. Maybe someone has an idea how to fix this...

**Comment by alfredomoreira** [comment] 2019-01-24 14:58
I am also experiencing the same issue with nested lists. I propose to add the following to code fix the issue temporarily:

**drop-list.ts: class definition - new member**
```typescript
@ContentChildren(forwardRef(() => CdkDropList), 
 { descendants: true }) _childLists: QueryList<CdkDropList>;
```

**drop-lists.ts:  method _syncInputs - change code**
```typescript
ref
.setChildLists(this._childLists.map(child => child._dropListRef))
        .connectedTo(siblings.filter(drop => drop && drop !== this).map(list => list._dropListRef))
        .withOrientation(this.orientation)
        .withItems(this._draggables.map(drag => drag._dragRef));
```

**drop-list-ref.ts: class definition - new method**
```typescript
setChildLists(childLists: DropListRef[]): this {
    this._childLists = childLists;
    return this;
}
```

**drop-list-ref.ts: method _canReceive - add code**
```typescript
if (this._childLists) {
      for (const list of this._childLists) {
        if (list === this) {
          continue;
        }
        if (isInsideClientRect(list._clientRect, x, y)) {
          return false;
        }
      }
    }
```
This code is far away from being optimal but it can solve at least the concurrency problem inside nested lists. At border of the lists it will still exist some jitter that can be reduced by adding a <div> with some height.

**Comment by SantiagoIlli** [comment] 2019-05-21 13:59
Check this stack blitz solution, it may help you to find a work around https://stackblitz.com/edit/nested-connected-lists

**Comment by tlorenz9** [comment] 2019-05-22 06:36
The problem I need to solve, is dragging a group into another group. Dragging items into other groups is not such a big problem when not having Groups in Groups.

**Comment by crisbeto** [comment] 2020-07-12 09:41
Duplicate of https://github.com/angular/components/issues/16671.

**Closed by crisbeto** 2020-07-12 09:41 UTC
Labels: area: cdk/drag-drop, needs triage
