### ISSUE TITLE
help(CDK/drag and drop): CDK drop and drop mixing up, down, left and right

### ISSUE THREAD

**Issue by yiquanchaoren** [angular/components#22077] opened 2021-03-02 02:38 UTC
#### What are you trying to do?

When I drag and drop columns from one list to another drop list, the drop area have up to 3 columns per row, and can add the whole rows. I hope the droped control can run around the implementation of an existing control.

![image](https://user-images.githubusercontent.com/35981627/109588956-88ea9680-7b44-11eb-9741-9c607163fa9c.png)

#### What troubleshooting steps have you tried?

I checked the CDK document, the drag and drop samples only support up and down, or left and right with two list. 
There are no examples of mixing up, down, left and right.

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: 
- Components: https://stackblitz.com/fork/components-issue 
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. Drag one of the left control list
2. The droped control can't run around the implementation of an existing control
  
#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2021-03-02 08:17
Duplicate of https://github.com/angular/components/issues/13372.

**Closed by crisbeto** 2021-03-02 08:17 UTC
Labels: needs triage, troubleshooting

**Comment by yiquanchaoren** [comment] 2021-03-02 10:01
> Duplicate of #13372.
Sorry, You misunderstood me.

I want to achieve the following GIF effect. Can angular CDK be implemented?

![draganddrop](https://user-images.githubusercontent.com/35981627/109631653-22379e00-7b81-11eb-9936-ce5e414cbd29.gif)

**Comment by yiquanchaoren** [comment] 2021-03-02 10:04
The droped control can be the left, right ,up or down sides of the existing control.

**Comment by yiquanchaoren** [comment] 2021-03-03 01:24
> ok, I see. You should be able to implement that example by having multiple lists that the item can be dropped into (one for each row of fields).

Yes.
Any idear ?
