### ISSUE TITLE
bug(Chips): WAVE error in mat-chips input control

### ISSUE THREAD

**Issue by IConstructor** [angular/components#20901] opened 2020-10-28 12:45 UTC
#### Reproduction
Steps to reproduce:
1.  Go to https://stackblitz.com/angular/oaxdlnpkrpk?file=src%2Fapp%2Fchips-autocomplete-example.ts
2. Click button "Open in new window"
3. In the new window turn on WAVE
4. WAVE showing "Missing form label" error.
 
 
#### Expected Behavior

WAVE not showing any errors in the control.

#### Actual Behavior

WAVE showing "Missing form label" error.

#### Environment

- Angular: 8
- CDK/Material: Material
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2020-10-29 18:27
It's probably, because the docs example doesn't have a `mat-label` inside the `mat-form-field`.

**Comment by IConstructor** [comment] 2020-11-06 09:37
@crisbeto , does it make sense to add it ? I believe it is not right if it will be empty.

**Comment by Xender007** [comment] 2021-03-06 22:31
@IConstructor This issue already resolved. Please close this issue !

![image](https://user-images.githubusercontent.com/40244430/110222654-cb6ff280-7ef9-11eb-8826-aa1d128f646e.png)

**Comment by mmalerba** [comment] 2021-05-25 19:20
Confirmed this issue is resolved, the examples have a `mat-label` now

**Closed by mmalerba** 2021-05-25 19:20 UTC
Labels: P4, area: material/chips, docs, good first issue, help wanted
