### ISSUE TITLE
bug(mat-form-field): Formfield-Label is displayed fuzzy

### ISSUE THREAD

**Issue by RobinBomkamp** [angular/components#26461] opened 2023-01-19 14:15 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.0

### Description

The label of a MatFormField is displayed fuzzy, after switching between tabs. Before switching the tab the label is displayed sharp. Unfortunately it is difficult to see.

https://stackblitz.com/edit/components-issue-2pmhb4?file=src%2Fapp%2Fexample-component.html

### Reproduction

Steps to reproduce:
1. Open the stackblitz.
2. Switch to another tab.
3. Go back to the previous tab. Now the label is shown fuzzy.

### Expected Behavior

I expect the label to be shown sharp.

### Actual Behavior

The label is displayed fuzzy or blurred.

### Environment

Angular CLI: 15.0.4
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    15.0.3
@angular/material               15.0.3
@schematics/angular             15.0.4
ng-packagr                      15.0.3
rxjs                            7.5.7
typescript                      4.8.4

**Comment by iraviguggilam** [comment] 2023-01-23 13:46
![image](https://user-images.githubusercontent.com/118201312/214054993-82203358-56e9-4239-b3ec-1a76ab982fa4.png)

I'm using mat-form-field without label. It is showing like this.

**Comment by amysorto** [comment] 2023-05-11 22:44
@RobinBomkamp  I cannot reproduce using that StackBlitz so I'll be closing this issue.
@iraviguggilam This seems unrelated to the original issue, please [create a new issue](https://github.com/angular/components/issues/new/choose) with more context.

**Closed** 2023-05-11 22:44 UTC
Labels: needs triage
