### ISSUE TITLE
bug(Mat Select): Keeps throwing FOR / ID error, when ID is given and visible in HTML

### ISSUE THREAD

**Issue by dreamstar-enterprises** [angular/components#28943] opened 2024-04-23 20:32 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When i assign an ID to mat-select

<mat-select
            id="jobTitle"

I get the error, in Chrome

The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.

<img width="736" alt="Screenshot 2024-04-23 at 21 33 08" src="https://github.com/angular/components/assets/39380005/7010f99e-021e-481f-b4bd-28392df4437e">

But the element with the id is clearly there (regularSiteOfWorking)

<img width="400" alt="Screenshot 2024-04-23 at 21 32 02" src="https://github.com/angular/components/assets/39380005/8c6d456b-155b-4758-8794-83ad70688ea9">

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

See above

### Actual Behavior

See above

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2024-04-24 07:41
Duplicate of https://github.com/angular/components/issues/27241.

**Closed by crisbeto** 2024-04-24 07:41 UTC
Labels: needs triage

**Comment by dreamstar-enterprises** [comment] 2024-04-24 17:25
Thank you, but the other thread is closed, and the issue hasn't really been resolved if you read through the thread
