### ISSUE TITLE
MatTab: Provide option to preserve material tab content when switching tabs

### ISSUE THREAD

**Issue by honzajde** [angular/components#20420] opened 2020-08-26 12:47 UTC
#### Feature Description

Provide option to preserve material tab content when user is switching tabs (do not reinstantiate content) in material tab group.

#### Use Case

Use cases are well described here:
https://github.com/angular/components/issues/16065

For example a list of items as a first tab and details opening in the other tabs.
Often detail tab is an edit form, state of which consists of model state and some temporary form state - I really would need to avoid persisting all that.

At least for me preserving behavior is more intuitive and expected when it comes to thinking of how tabs are used.
So please at least document your chosen behavior.

**Comment by crisbeto** [comment] 2020-08-26 13:31
Duplicate of https://github.com/angular/components/issues/19480.

**Closed by crisbeto** 2020-08-26 13:31 UTC
Labels: feature, needs triage
