### ISSUE TITLE
Menu is not aware of menu items nested within child components

### ISSUE THREAD

**Issue by kbondsj** [angular/components#18617] opened 2020-02-25 20:20 UTC
Reproduction

Use StackBlitz to reproduce your issue:
https://stackblitz.com/edit/angular-7-mat-menu (works)
https://stackblitz.com/edit/angular-9-mat-menu (broken)

Steps to reproduce:

    Set up a button to be used with a mat-menu
    In the mat-menu, use 2 buttons as well as use a custom component that has just a button
    Using the keyboard, tab to your button and then open it, try to navigate using arrows
    Only the 2 buttons explicitly listed in the template will navigate, the button from the component will not allow keyboard navigation. The manuData is missing for that element.

Expected Behavior

What behavior were you expecting to see?
This was working before we upgraded to version 9. I have created 2 stackblitzes with the same example. @angular 7 works, @angular 8 and 9 do not.
Actual Behavior

What behavior did you actually see?
The items that are listed as direct children are properly navigated to using arrow keys. The ones rendered from custom component are skipped.
Environment

    Angular: 9.0.2
    CDK/Material: 8.2.3
    Browser(s): Chrome
    Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by devversion** [comment] 2020-05-26 17:29
I was able to confirm this regression. cc. @crisbeto if you want to have a look.

**Comment by fredericotoptal** [comment] 2020-07-23 09:57
Any news on this issue ?

**Comment by crisbeto** [comment] 2020-07-26 09:18
Combining this with https://github.com/angular/components/issues/16457 since it's older and has more activity.

**Comment by crisbeto** [comment] 2020-07-26 09:19
Got confused, it's not the same issue. Reopening.

**Comment by nirkai** [comment] 2020-08-25 19:03
Anything new?

The [_allItems](https://github.com/angular/components/blob/f0c7a25e0d58440029b4129188baa77d88ce5fc6/src/material/menu/menu.ts#L472) received the items on the [ngAfterContentInit](https://github.com/angular/components/blob/f0c7a25e0d58440029b4129188baa77d88ce5fc6/src/material/menu/menu.ts#L265), which happens before the child component init. 

So I have an ugly work around on [stackblitz](https://stackblitz.com/edit/angular-npkkpp?file=src/app/menu-overview-example.ts), but hope to find soon a better solution. 

There is a better work-around but it not suitable for my case, because I must use `ng-template` outside the `mat-menu` which have the same issue as the child component.

**Comment by jelbourn** [comment] 2020-11-25 00:18
I'm closing this because the behavior before Angular v9 was actually a bug. In Angular's component model, a component is meant to be a black box; parent components aren't supposed to be aware of its contents. The v9 change makes this work the way it's supposed to.

**Closed by jelbourn** 2020-11-25 00:18 UTC
Labels: P4, area: material/menu, regression
