### ISSUE TITLE
IE inconsitent formcontrol behaviour (touched, dirty, pristine)

### ISSUE THREAD

**Issue by robindijkhof** [angular/components#16331] opened 2019-06-19 12:21 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. https://github.com/robindijkhof/materialformcontrol

Basically I have the following formcontrols

    <form>
        <input  [placeholder]="'Favorite food'" [formControl]="form0">
    </form>
  
    <form>
      <mat-form-field>
        <input matInput placeholder="Favorite food" [formControl]="form1">
      </mat-form-field>
    </form>
  
    <form>
      <mat-form-field>
        <input matInput [placeholder]="'Favorite food'" [formControl]="form2">
      </mat-form-field>
    </form>
  
    <form>
      <mat-form-field>
        <input matInput [placeholder]="'Favoritë food'" [formControl]="form3">
      </mat-form-field>
    </form>
 
 
#### Expected Behavior

I'd expect touched, dirty and pristine would be equal over all form controls.

#### Actual Behavior

![materialbug](https://user-images.githubusercontent.com/22224763/59764854-f1281480-929c-11e9-9e40-eaf7e564383a.png)

#### Environment

- Angular: 7.2.13
- CDK/Material: 7.3.7
- Browser(s): IE
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by macjohnny** [comment] 2019-06-19 13:36
might be related to https://github.com/angular/components/issues/3256
and https://github.com/angular/angular/issues/14667

**Comment by robindijkhof** [comment] 2019-06-19 14:24
Looks like it. Though, did not read anything about that `ë`

**Comment by macjohnny** [comment] 2019-06-19 14:33
@robindijkhof the `ë` issue is very strange indeed

**Comment by jelbourn** [comment] 2020-05-28 22:38
Duplicate of https://github.com/angular/angular/issues/14440

**Closed by jelbourn** 2020-05-28 22:38 UTC
Labels: needs triage
