### ISSUE TITLE
Checkbox not obeying parent fieldset disabled state

### ISSUE THREAD

**Issue by moniuch** [angular/components#2763] opened 2017-01-23 13:13 UTC
#### Bug, feature request, or proposal:
Bug: - but I am not sure it's a bug in your component or an incomplete accessor. 
I have reported it here: https://github.com/angular/angular/issues/13856

I am just looking out for answer how to implement disabling a component upon fieldset disabled change and whether it can be achieved with current API (Angular 2.4.4)

#### What is the expected behavior?
Component should be notified of its parent fieldset disabled state.

#### What are the steps to reproduce?
See this forked plunker of your checkbox - please refer to the new section I created "Fieldset test": https://plnkr.co/edit/MmQU0KLVUMFSzFgwTK9t?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Provide compliance with w3 standards. 

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2.4.4, all browsers

#### Is there anything else we should know?
I haven't tested whether the misbehavior afects also other controls but I would guess so. It's probably the matter of the NG_VALUE_ACCESSOR shape.

**Comment by arlowhite** [comment] 2017-04-11 19:08
Not sure if related. But I encountered a bug when using FormControl.disable()
https://github.com/angular/material2/issues/4037
To reproduce it with material2 demo, I had to click the disabled check.
But in my own app with a ReactiveForm, the checkbox is broken after `disable()`/`enable()` even without interacting with it.

**Comment by mmacfadden** [comment] 2017-04-11 19:56
I am having a similar issue. Calling disabled() disables the checkbox and it is grayed out. Calling enable() darkens the checkbox and it looks enabled, but you can't actually click on it any more.

**Comment by kaldmaster** [comment] 2017-05-02 11:36
We are experiencing the same issue as well. Disabling the checkbox works as expected, but when it's enabled again it looks enabled but is not clickable. This is when using the FormControl.disable/enable(). Using the checkbox's [disabled]-binding works as expected though, so it is possible to use that as a workaround for now.

**Comment by jelbourn** [comment] 2017-06-07 00:17
this is a feature that should probably live in `@angular/forms`

**Comment by Splaktar** [comment] 2018-02-18 08:48
Seems to be tracked in https://github.com/angular/angular/issues/13856.

**Comment by jelbourn** [comment] 2021-02-23 23:32
Closing this since the underlying issue is tracked on https://github.com/angular/angular/issues/35309

**Closed by jelbourn** 2021-02-23 23:32 UTC
Labels: P5, area: material/checkbox, feature, forms
