### ISSUE TITLE
$color: var(--primary-default) is not a color

### ISSUE THREAD

**Issue by artepic** [angular/components#26032] opened 2022-11-19 09:30 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

SassError: $color: var(--primary-default) is not a color.
   ╷
16 │     track-color: color.adjust(mdc-theme-color.prop-value($color), $alpha: -0.75),
   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Reproduction

Steps to reproduce:

$theme-primary: (
  default: var(--primary-default),
...
...
);

$my-theme: (
  primary: $theme-primary,
...
...
...
);

@include mat.all-component-themes($my-theme);

after short inspection, generated by:
@include progress-bar-theme.theme($theme-or-color-config);

### Expected Behavior

supported var(--xyz) 

### Actual Behavior

Compiled with problems

### Environment

- Angular: 15 
- CDK/Material: 15
- Browser(s):
-
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2022-11-19 10:33
Duplicate of https://github.com/angular/components/issues/25981.

**Closed by crisbeto** 2022-11-19 10:33 UTC
Labels: needs triage
