### ISSUE TITLE
bug(MatDialog): [MatDialogRef -> MatDialogRef -> MatDialogRef]:    NullInjectorError: No provider for MatDialogRef!

### ISSUE THREAD

**Issue by weirdyang** [angular/components#23060] opened 2021-06-24 13:20 UTC
#### Reproduction
```
core.js:6456 ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[MatDialogRef -> MatDialogRef -> MatDialogRef]: 
  NullInjectorError: No provider for MatDialogRef!
NullInjectorError: R3InjectorError(AppModule)[MatDialogRef -> MatDialogRef -> MatDialogRef]: 
```
I am using the dialog to open a component and using the dialogRef in the registerComponent to close and pass data;

```

  openRegisterDialog() {
    this.dialogRef = this.dialog.open(RegisterComponent, {
      width: '450px',
      disableClose: true
    })
    this.dialogSubscription = this.dialogRef
      .afterClosed()
      .subscribe(result => {
        if (result) {
          this.snackBar.open(result, 'OK');
        }
      });
  }
```
```
 export class RegisterComponent implements OnInit, OnDestroy {
  constructor(
    private snackBar: MatSnackBar,
    private overlay: OverlayContainer,
    private themingService: ThemingService,
    private fb: FormBuilder,
    private authService: AuthService,
    public dialogRef: MatDialogRef<RegisterComponent>) {

```
I've imported the MatDialogModule in both the shell component module and the actual component module. And have tried importing it in the app module as suggested in this [issue](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi60eXprLDxAhXJfn0KHUd-DOYQFjABegQIAhAE&url=https%3A%2F%2Fgithub.com%2Fangular%2Fcomponents%2Fissues%2F19335&usg=AOvVaw1sHeU4RKvuvRUjTUftkHDM), but I am still getting the error.
 
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LayoutModule } from '@angular/cdk/layout';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { NavBarComponent } from './nav-bar.component';
import { RouterModule } from '@angular/router';
import { MatMenuModule } from '@angular/material/menu';
import { MatTooltipModule } from '@angular/material/tooltip';
import { RegisterModule } from '../profile/register/register.module';
import { LoginModule } from '../profile/login/login.module';
import { MatDialogModule } from '@angular/material/dialog';
@NgModule({
  declarations: [NavBarComponent],
  imports: [
    CommonModule,
    LayoutModule,
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    RouterModule,
    MatMenuModule,
    MatTooltipModule,
    RegisterModule,
    LoginModule,
  ],
  exports: [NavBarComponent, MatButtonModule, MatDialogModule]
})
export class NavBarModule { }



import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { RegisterRoutingModule } from './register-routing.module';
import { RegisterComponent } from './register.component';
import { MatDialogModule } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatOptionModule } from '@angular/material/core';
import { MatSelectModule } from '@angular/material/select';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatInputModule } from '@angular/material/input';
import { MatSnackBarModule } from '@angular/material/snack-bar';
@NgModule({
  declarations: [
    RegisterComponent
  ],
  imports: [
    CommonModule,
    RegisterRoutingModule,
    MatDialogModule,
    MatIconModule,
    MatButtonModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    FormsModule,
    ReactiveFormsModule,
    MatInputModule,
    MatSnackBarModule,
  ],
  exports: [
    RegisterComponent,
    CommonModule,
    RegisterRoutingModule,
    MatDialogModule,
    MatIconModule,
    MatButtonModule,
    MatFormFieldModule,
    MatOptionModule,
    MatSelectModule,
    FormsModule,
    ReactiveFormsModule,
    MatInputModule,
    MatSnackBarModule
  ]
})
export class RegisterModule { }
```

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NavBarModule } from './nav-bar/nav-bar.module';
import { LayoutModule } from '@angular/cdk/layout';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { ProfileModule } from './profile/profile.module';
import { HttpClientModule } from '@angular/common/http';
import { MatDialogModule } from '@angular/material/dialog';

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    NavBarModule,
    LayoutModule,
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    ProfileModule,
    HttpClientModule,
    MatDialogModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by psoares-resilient** [comment] 2021-06-24 17:56
See this: https://material.angular.io/components/dialog/examples

I think you are injecting the wrong thing...  

```
public dialogRef: MatDialogRef<RegisterComponent>) {
```

Should be: 

```
 public dialog: MatDialog) {
```

And then you call open on it, and it will return the ref: `const dialogRef = dialog.open(RegisterComponent, {...})`.

Hope it helps :D

**Comment by weirdyang** [comment] 2021-06-25 04:11
Hi

I’m injecting the right service.

RegisterComponent is to be opened in a dialog.

https://material.angular.io/components/dialog/overview

I am calling open in another component, I’ve shared that code block too

**Comment by psoares-resilient** [comment] 2021-06-28 09:44
> Hi I’m injecting the right service. RegisterComponent is to be opened in a dialog. https://material.angular.io/components/dialog/overview I am calling open in another component, I’ve shared that code block too
> […](#)

I'm sorry, I now realise I grossly misunderstood your problem. In this cases is helpful to share a Stackblitz with it being reproduced then versions, setup and behaviour are all locked up and easily identifiable. It'll probably help the team to have one at hand?

**Comment by crisbeto** [comment] 2021-07-02 20:00
It's hard to tell what is going on without a reproduction. We've had similar issue reports in the past which were due to folks putting `MatDialogRef` in the `providers` array of an `NgModule`, or when trying to render a dialog component outside of a dialog.

**Comment by jelbourn** [comment] 2021-07-22 17:04
Closing this since we don't have a reproduction. Feel free to open a new issue if you're able to share a reproduction.

**Closed by jelbourn** 2021-07-22 17:04 UTC
Labels: area: material/dialog, needs clarification
