### ISSUE TITLE
Jaws Screen reader announcement is not working in IE using Jaws 2019

### ISSUE THREAD

**Issue by SadhuSa** [angular/components#18344] opened 2020-01-30 19:46 UTC
#### Expected Behavior

What behavior were you expecting to see?

Angular material select component accessibility features are not announcing using jaws 2019 screen reader version.  Expecting to hear the required field validation error message announcement in IE.

#### Actual Behavior

What behavior did you actually see?

Able to hear the announcement of Required field validation message in chrome and firefiox. Using jaws 2019 version for chrome brower and NVDA screen reader for firefox. Reuirement is to hear validation message on submit button click without selecting anything from dropdown.

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment] 2020-02-06 23:14
Duplicate of #11083  (which covers MatSelect a11y in general)

**Closed by jelbourn** 2020-02-06 23:14 UTC
