### ISSUE TITLE
Button click handler firing twice in IE11 with AOT compilation

### ISSUE THREAD

**Issue by dberthia** [angular/components#12602] opened 2018-08-09 17:23 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
In IE11, using AOT compile, mat-button click handler should only fire once

#### What is the current behavior?
In IE11, using AOT compile, mat-button click handler firing twice

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
https://stackblitz.com/edit/angular-wudcgj
Can't provide a true working example, but this is basically the code causing the issue. Only happens in IE11, and only when using AOT compile. Workaround is to add an event.preventDefault() in the click handler.
[angular-wudcgj.zip](https://github.com/angular/material2/files/2275163/angular-wudcgj.zip)

#### What is the use-case or motivation for changing an existing behavior?
Handler should not fire more than once per click

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
IE11, Angular 6, Material 2

**Comment by devversion** [comment] 2020-05-28 10:39
Hello! I was unable to reproduce this on my end. Could you please double-check if this is still an issue for you? Closing this in the meanwhile as this is issue is quite old and most likely not up-to-date anymore (sorry for us taking so long!)

**Closed by devversion** 2020-05-28 10:39 UTC
Labels: needs investigation, needs triage
