### ISSUE TITLE
bug(CDK): Drag and drop: Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by anton-white** [angular/components#27692] opened 2023-08-22 09:22 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi guys,

We are constantly facing production issues reported by Sentry.
Here is the screenshot:
<img width="836" alt="image" src="https://github.com/angular/components/assets/3082531/01555090-655e-4ac4-8f40-75983232d305">

The problem occurs on https://github.com/angular/components/blob/main/src/cdk/drag-drop/dom/styling.ts#L77C18-L77C18

It looks like it happens on Chrome OS only:
<img width="362" alt="image" src="https://github.com/angular/components/assets/3082531/094654f6-f1b9-498c-8f0e-29cfabd0966b">

Affected browser versions:
<img width="365" alt="image" src="https://github.com/angular/components/assets/3082531/27b8571d-8928-4da2-977a-7c964e83b001">

This is a real problem for us, because this error crashes the entire app and users have to refresh the browser and sign in again to bypass it.

Please hint us where to look at. 

### Reproduction

Unfortunately we cannot reproduce this error locally. Neither we were able to identify conditions that are causing it. 

### Expected Behavior

No error and no browser crash.

### Actual Behavior

Error and browser crash.

### Environment

```
Angular CLI: 16.2.0
Node: 18.16.0
Package Manager: npm 9.6.6
OS: darwin x64

Angular: 16.2.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cdk                    16.1.4
@angular/cli                    16.2.0
@angular/material               16.1.4
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.3
zone.js                         0.13.0
```

**Comment by crisbeto** [comment] 2023-08-22 11:05
Can you provide information on how to reproduce the issue?

**Comment by mmalerba** [comment] 2023-09-25 21:40
Closing since we are unable to reproduce

**Closed by mmalerba** 2023-09-25 21:40 UTC
Labels: needs: clarification, area: cdk/drag-drop
