### ISSUE TITLE
bug(form-field): cut off outline title 

### ISSUE THREAD

**Issue by jwbaart** [angular/components#28507] opened 2024-01-31 08:19 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When placing a outline form field within a element with `overflow: hidden` the outline title at the top of the form field will be cut off.
![Screenshot 2024-01-31 at 09 11 27](https://github.com/angular/components/assets/78362609/d5f46169-9909-4405-a8be-0cb605c8106f)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/components-issue-hbqrhv
Steps to reproduce:
1. Click on form field
2. Cut off outline title will be shown above input

### Expected Behavior

Complete outline title visible

### Actual Behavior

Cut off outline title

### Environment

- Angular: 17
- CDK/Material: 17
- Browser(s): ALL
- Operating System (e.g. Windows, macOS, Ubuntu): ALL

**Comment by amysorto** [comment] 2024-02-01 13:31
Duplicate of #27764

**Closed by amysorto** 2024-02-01 13:31 UTC
Labels: needs triage
