### ISSUE TITLE
bug(Table): weird rendering glitch on chrome

### ISSUE THREAD

**Issue by krskrs** [angular/components#23926] opened 2021-11-08 23:03 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm facing a rather weird issue, but only on Chrome. I'd almost argue that this could be a Chrome issue.. but since this is the first time I have seen such behavior and I have seen it with an angular table, I will start by reporting it here. 

### Reproduction

https://stackblitz.com/edit/angular-rcsy5u

open 'full screen' ( https://angular-rcsy5u.stackblitz.io/ ), maximize Chrome window and refresh multiple times, each time scrolling to the end and checking the last buttons (I mean the buttons in the last rows). You should start seeing soon incomplete renders, like these:

![image](https://user-images.githubusercontent.com/2150068/140830882-4ce6437c-16fe-4e1e-90b3-384f5f330e46.png)

or these: 

![image](https://user-images.githubusercontent.com/2150068/140830992-01366f62-5233-429f-825f-536c9a1a4c68.png)

IMPORTANT: if you just click on a button, or resize the browser window, triggering a 'redraw', missing buttons will suddendly be rendered and will show.

### Expected Behavior

All buttons normally rendered up to the last ones.

### Actual Behavior

please see screenshots in the Reproduction section above

### Environment

- Angular: 12.2.x (please check stackblitz project)
- CDK/Material: 12.2.12
- Browser(s): Latest Chrome ( 95.0.4638.69  (64 bit))
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by jelbourn** [comment] 2021-11-18 22:54
@krskrs I also tried this on Chrome 96.0.4664.45 on Windows 10 and I wasn't able to reproduce. Any other information you can provide here?

**Comment by ajafff** [comment] 2021-11-24 21:38
Seems related to https://bugs.chromium.org/p/chromium/issues/detail?id=1273431

**Comment by crisbeto** [comment] 2021-12-07 09:17
Closing since this is likely a browser rendering issue that we can't do much about.

**Closed by crisbeto** 2021-12-07 09:17 UTC
Labels: cannot reproduce, needs clarification, needs triage
