### ISSUE TITLE
MatMenu positioning wrong when scale != 100%

### ISSUE THREAD

**Issue by Malex** [angular/components#15845] opened 2019-04-17 07:36 UTC
#### What is the expected behavior?
The MatMenu positions itself on the trigger as expected

#### What is the current behavior?
Normally it positions correctly, BUT if screen scaling is applied (either by Windows screen setting or by using Chrome scaling with CTRL+"+" or CTRL+"-") it positions itself quite randomly.
I debugged it a little bit and the viewPort ruler/rect variables are set correct (i.e. 1536x756 on a 1920x1080 resolution with 125% scaling; which is pretty standard on laptops), but when it sets the pixels on style attribute, it top and left position are scaled to 1920px.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.13, Angular Material 7.2.2 and 7.3.7 (tried both), Windows 10, "Chrome 73.0.3683.103 (Official Build) (64-bit)", Typescript 3.1.6

#### Is there anything else we should know?
The menu component is builded dynamically (with ComponentFactoryResolver etc) and the same menu might be attached to multiple triggers positioned in different positions.
Also such triggers are inside foreignObjects created on a d3.js graph

**Comment by andrewseguin** [comment] 2019-05-09 21:39
I'm having trouble reproducing this with a normal menu - https://material.angular.io/components/menu/overview

No matter the scale, it seems to be connected to the trigger consistently in the same location. Can you provide a bit more information on reproducing your issue?

**Comment by Malex** [comment] 2019-06-26 13:32
Hi, sorry for the late answer, had to switch project for a while and just came back to this. You are right, in normal circumstances it connect correctly (in my application as well) except when the trigger is inside an SVG (more precisely, inside a foreignObject inside ad svg). Using component factory and d3 I put my component inside the foreignObject, and everything works fine *except* matmenu positioning when scale changes. If the scale is 100% it works fine.

**Comment by Malex** [comment] 2019-06-26 13:34
Basically it seems rescaling for the menu happens using screen corner as center, whereas the svg uses another center for rescaling

**Comment by assafsun** [comment] 2019-07-25 06:03
Hi,

Is this issue still relevant? I'm having a similar problem of loading a mat-menu inside foreignObject.
The menu itself loads and looks good but the position is far from the trigger point.
I tried to override the CSS properties cdk-overlay-pane but it affect it.

I will appreciate any update on this issue.

Thanks!

**Comment by crisbeto** [comment] 2020-08-16 07:30
This is something that comes up once in a while, but unfortunately we can't do much about it. We use some browser APIs (`getBoundingClientRect`) to figure out where the trigger is on the screen so that we can position the overlay, but the browser reports incorrect dimensions if something is zoomed. Duplicate of https://github.com/angular/components/issues/10924.

**Closed by crisbeto** 2020-08-16 07:30 UTC
Labels: P4, area: material/menu, needs triage
