### ISSUE TITLE
mat-expansion-panel within mat-dialog-content: weird behavior

### ISSUE THREAD

**Issue by manueledones** [angular/components#16956] opened 2019-09-03 11:17 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-yltxip

Steps to reproduce:
1. Open the dialog
 
 
#### Expected Behavior

I'm expecting the expansion-panel to be initialized as closed

#### Actual Behavior

When the modal dialog is opened, the expansion-panel seems opened and it's closing very fast

#### Environment

- Angular: 8.2.4
- CDK/Material: 8.1.4
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2019-09-03 15:16
See https://github.com/angular/components/pull/13888 and https://github.com/angular/components/pull/14127.

**Comment by josephperrott** [comment] 2020-05-26 18:50
Closing as duplicate of #13870

**Closed by josephperrott** 2020-05-26 18:50 UTC
Labels: needs triage
