### ISSUE TITLE
`MatCheckbox`'s `disabled`  property has `any` type

### ISSUE THREAD

**Issue by AlexElin** [angular/components#22311] opened 2021-03-22 19:46 UTC
#### Documentation Feedback

 `MatCheckbox`'s `disabled`  has `any` type in the docs

![disabled not boolean](https://user-images.githubusercontent.com/13061803/112049185-5854b600-8b60-11eb-9b70-34c4f74adfdc.jpg)
**Affected documentation page:** https://material.angular.io/components/checkbox/api#MatCheckbox

**Comment by crisbeto** [comment] 2021-03-22 20:07
It's not a docs bug since we'll have to change the type of the property. The problem is that doing so now will be a breaking change.

**Comment by muneebkq** [comment] 2023-07-27 06:50
@crisbeto [disabled] ="true" doesn't work

**Comment by crisbeto** [comment] 2024-12-03 07:25
This should be resolved by #27744.

**Closed by crisbeto** 2024-12-03 07:25 UTC
Labels: P3, area: material/checkbox
