### ISSUE TITLE
bug(MatSlider): The value from valueChange event is not in sync with the value indicator from UI

### ISSUE THREAD

**Issue by MariaBulboaca** [angular/components#27467] opened 2023-07-17 08:59 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.*.*

### Description

Having a mat slider with **valueChange** event, the value emitted is not in sync with UI value when we move the thumb with mouse.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/psdykz-s8ozkk?file=src%2Fapp%2Fslider-formatting-example.html
Steps to reproduce:
1. Move thumb to the right using mouse.
2. And then move thumb to the left, until reach the 0 value.
![bug-slider](https://github.com/angular/components/assets/108864526/0ea652e8-f6e2-4d3d-b9d3-b3a9d809fb6b)

### Expected Behavior

The value should be updated to **0**

### Actual Behavior

The value is not updated to 0 even if the value from indicator is 0.
![image](https://github.com/angular/components/assets/108864526/a749eafa-1cad-4859-890f-147dea1dce0d)

### Environment

- Angular: 15.2.9
- CDK/Material: 15.2.9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by wagnermaciel** [comment] 2023-07-17 13:38
Duplicate of issue #27208

**Closed by wagnermaciel** 2023-07-17 13:38 UTC
Labels: needs triage
