### ISSUE TITLE
bug(various): ReferenceError Cannot access 'X' before initialization

### ISSUE THREAD

**Issue by mcalmus** [angular/components#19461] opened 2020-05-27 13:03 UTC
#### Reproduction

Steps to reproduce:
I have not yet been able to reproduce this using a trivial case in Stackblitz.

After updating to version  10.0.0-next.2 (from  10.0.0-next.1) I am seeing instances similar to:

ReferenceError: Cannot access 'MatSelectionList' before initialization
    at list.js:589
    at Module../node_modules/@angular/material/__ivy_ngcc__/fesm2015/list.js (list.js:649)
 
I have seen this in one module as above and another where 'MatCalendar' is the component. The broken page then fails to load regardless of whether it was accessed directly through a URL or via a router link from another module.
 
#### Expected Behavior
Page should load without error.

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?
Page fails to load with ReferenceError

#### Environment

- Angular: 10.0.0-rc.0
- CDK/Material: 10.0.0-next.2
- Browser(s): Chrome, FF, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2020-05-27 13:13
Duplicate of https://github.com/angular/components/issues/19454.

**Closed by crisbeto** 2020-05-27 13:13 UTC
Labels: needs triage
