### ISSUE TITLE
Can't drop into same DropList in hierarchy (because DropList is filter out before call ref.connectedTo)

### ISSUE THREAD

**Issue by petr-kostelansky** [angular/components#18450] opened 2020-02-10 11:17 UTC
I have a hierarchy of items. 
<img src="https://user-images.githubusercontent.com/33530495/74142994-446b2080-4bfa-11ea-8c20-2ac1f2616007.PNG" width="300" />

**I would like to change order of item (Child item 3) in the same DropList (droplist of Parent item 1), just change order not move into another DropList. But I can not do that**, because:
In _CdkDropList_ is method __setupInputSyncSubscription(ref)_ and in this method is subscription _ref.beforeStarted.subscribe(...)_ in which is called  
```
            ref.connectedTo(siblings.filter((
            drop => drop && drop !== this)).map(...)
```
but the **filter** method filter out **.filter(drop => drop && drop !== this)** the origin DropList (**this**) of dragged item and than **I am not able to drop back into same DropList to reorder items**.

***

And I know that there is a method __updateActiveDropContainer(...)_ on _DragRef_ that is trying to handle sorting if I dropping into same DropList but this works just for Parents. Because just if 

```let newContainer = this._initialContainer._getSiblingContainerFromPosition(this, x, y);```

_newContainer_ is _undefined_ then sorting ((this._dropContainer))._sortItem(...)) can happend. But I want to drop back into DropList of children (Parent item 1) and I always get in _newContainer_ DropList of parents and not DropList of children (Parent item 1) because the DropList  of children (Parent item 1) was removed in **siblings.filter((drop => drop && drop !== this))** as I mentioned above.

I can not place the item where red lines are cause the _this._initialContainer._getSiblingContainerFromPosition(this, x, y)_ always return DropList of children (red arrow)
<img src="https://user-images.githubusercontent.com/33530495/74143474-281bb380-4bfb-11ea-8cd6-e3813dfc3ae1.PNG" width="300" />

or DropList of Parents (red arrow)
<img src="https://user-images.githubusercontent.com/33530495/74143665-7f218880-4bfb-11ea-9105-922f7dd49548.PNG" width="300" />

Can you remove for next version the filter that removes origin DropList (droplist where dragged item was placed)? Or is there some reason why the filter is there?

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.1.3
- Browser(s): Chrome Version 80.0.3987.87
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment] 2020-02-10 13:39
The filter is there, because it doesn't make sense to connect a list to itself. It sounds like you might be hitting a different issue, because the list allows dragging within itself by default.

**Comment by petr-kostelansky** [comment] 2020-02-10 14:23
> The filter is there, because it doesn't make sense to connect a list to itself. It sounds like you might be hitting a different issue, because the list allows dragging within itself by default.

By default yes, but just for flat list. If the list is somewhere in hierarchy (droplist in another droplist), than the filter cause this issue.

**Comment by crisbeto** [comment] 2020-07-12 09:47
Sounds like this falls into the category of "Issues with nested drop lists". Closing as a duplicate of https://github.com/angular/components/issues/16671.

**Closed by crisbeto** 2020-07-12 09:47 UTC
Labels: area: cdk/drag-drop, needs triage
