### ISSUE TITLE
MatCalendar should be publicly available

### ISSUE THREAD

**Issue by VeeteshJain** [angular/components#16583] opened 2019-07-22 10:46 UTC
#### Feature Description
We need to build a date range picker component which can be placed on the page or in the popup.

#### Problem Statement
Reduce the number of clicks from **8 -> 2-3 clicks** to select 1st quarter (1st Jan to 31st Apr) when the current date is 1st May because of very high usage.

**currently, it takes 8 clicks**
1 click to open the start date popup.
3 clicks to go back to 3rd last month.
1 more click to select the 1st date of the month.
1 click to open the end date popup.
1 click to go back to the last month.
1 more click to select the 1st date of the month.

**current implementation using matDatepicker**
![Screenshot 2019-07-22 at 3 52 11 PM](https://user-images.githubusercontent.com/6864682/61626535-27d9bc00-ac9b-11e9-95b9-b9df49bd39af.png)

we want to achieve something close to date range picker shown below **for which publically exported MatCalendar would be really helpful.**
<img width="718" alt="Screenshot 2019-07-22 at 3 50 48 PM" src="https://user-images.githubusercontent.com/6864682/61626593-463fb780-ac9b-11e9-88fe-bda48aa2dbcd.png">

**Comment by deanapeterson** [comment] 2020-10-25 14:22
Any movement on this? I'm having to do the same thing with the date range picker.

**Comment by deanapeterson** [comment] 2020-10-27 14:44
For reference it might be easier providing an 'inline' configuration.  The following 3rd-party library does this: https://github.com/kekeh/angular-mydatepicker

**Comment by tsmith-swiss** [comment] 2021-07-20 14:37
This would be very nice to have in the CDK.

**Comment by crisbeto** [comment] 2022-08-12 11:26
Duplicate of https://github.com/angular/components/issues/8812.

**Closed by crisbeto** 2022-08-12 11:26 UTC
Labels: feature, P3, area: material/datepicker
