### ISSUE TITLE
Screen reader announces table header twice.

### ISSUE THREAD

**Issue by staffordp** [angular/components#18703] opened 2020-03-04 12:08 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: [https://stackblitz.com/angular/xekbmvlqeqj?file=src%2Fapp%2Ftable-sorting-example.html]

Steps to reproduce:
1. Create a table with sorting as dpcumented here: https://material.angular.io/components/sort/overview 
 - or - click the Stackblitz example on the same page
2. Ensure NVDA Reader is installed and enabled (https://www.nvaccess.org/) 
3. Use the provided example for a sorting table on the same page and watch the NVDA speech output when you click a header name. [https://stackblitz.com/angular/xekbmvlqeqj?file=src%2Fapp%2Ftable-sorting-example.html]
 
#### Expected Behavior

What behavior were you expecting to see?
It announce the column once like "Change sorting for name  column 2  clickable"

#### Actual Behavior
NVDA reader announces the element twice as "Change sorting for name  column 2  clickable  Change sorting for name  button"

What behavior did you actually see?
See above for actual nehavior

#### Environment

- Angular:
- CDK/Material: 9.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by andrewseguin** [comment] 2020-05-26 18:22
Duplicate of #13012

**Closed by andrewseguin** 2020-05-26 18:22 UTC
Labels: needs triage
