### ISSUE TITLE
Sidenav 'openedChange' event is fired when default value is 'opened=true'

### ISSUE THREAD

**Issue by llorenspujol** [angular/components#18431] opened 2020-02-07 11:27 UTC
#### Reproduction

Here is an StackBlitz reproducing the issue: https://stackblitz.com/edit/angular-t2dksh
 
#### Expected Behavior

I expect Sidenav openedChange event to not be fired when default value is opened=true. 

#### Actual Behavior

openedChange event is fired when the Input property opened is set to true on init.

#### Explanation

I don't know if that functionality is by design, but in my opinion, this shouldn't be the expected behaviour. If we set that the init value is 'opened=true', for me there is no reason that openedChange event emits... it has not changed, simply the start value is opened=true. It has not changed from opened=false to opened=true.

#### Environment

- Angular: 9.0.0-rc.6
- CDK/Material: 9.0.0-rc.5
- Browser(s): Chrome (latest)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2020-02-07 13:41
The default state is `false` so setting it to `true` is a change. If you want to respond only to changes from the user, you should be able to implement it yourself since you're the one controlling which elements can toggle the sidenav.

**Comment by llorenspujol** [comment] 2020-02-07 17:35
Yes, I could fix easily on my code, is not big deal, but I simply found strange the behavior.

I am thinking about the possible use cases of listening `openedChange`, and I think most library users that listen to it are doing it for resizing manually some content when open/close animation ends (since `openedChange` emits when the animation finishes). For this use case is useless that `openedChange` emits when the default value is `opened=true`.
I actually I can't figure out any use case where one library user would like to listen and react to that `openedChange` event that emits for the default value `opened=true`. 

Actually, non emitting the first default value is a practice that some components implement, like `MatTabGroup` with `selectedIndex`. The `selectedIndex` default value is null and it doesn't emit any change event for the first start value.

Code example (from MatTabGroup):

```
const isFirstRun = this._selectedIndex == null;
if (!isFirstRun) {
      this.selectedIndexChange.emit(indexToSelect);
}
```
As I said, is not big deal (it can be easily patched), but for me this behavior is not the expected one.
I could make a PR if you think that this behavior could be changed.

**Comment by crisbeto** [comment] 2020-05-27 18:52
Closing since it's working as intended.

**Closed by crisbeto** 2020-05-27 18:52 UTC
Labels: area: material/sidenav
