### ISSUE TITLE
tabs: nested tabs do not accurately position the ink bar

### ISSUE THREAD

**Issue by Robouste** [angular/components#3335] opened 2017-02-28 13:54 UTC
#### Bug, feature request, or proposal:

Bug
This is a bit complicated to explain for a non native english speaker but you can check the plunkr below.

#### What is the expected behavior?

Nested tabs should always have its first tab active 

#### What is the current behavior?

It works for the first nested tab but not the others

#### What are the steps to reproduce?

http://plnkr.co/edit/r2QxMeW0WkMAgo4zpwqD?p=preview 

In the first tab group, if you click on Main Tab 2, the Nested Tab 1 will not be active.
In the second tab group, Nested Tab 1 is active because it's inside the first Main Tab

#### What is the use-case or motivation for changing an existing behavior?

Being able to nest tabs group

#### Which versions of Angular, Material, OS, browsers are affected?
All (tried on different projects)

#### Is there anything else we should know?
Yes, I love Material Design

**Comment by andrewseguin** [comment] 2017-03-14 21:26
The issue here is not that the tabs are not active, but the ink bar is not properly positions.

Root Cause: The nested tabs are initialized outside of the DOM. When the nested tabs tell the ink bar to position itself, the ink bar looks for the active tab's label position and width, which is non-existent at the time.

Workaround: Add the nested tabs once their host tab is activated. See this plunker for an example: http://plnkr.co/edit/2RoXVgL6dUY8xjcsa28n?p=preview

We'll need to consider the implications of not adding tab content to the DOM immediately once the tab group is initalized. The reason we only add the active tab right now is that we optimize performance, but we don't have numbers to compare the extent of the benefits.

**Comment by amcdnl** [comment] 2017-08-13 17:07
This is a side effect of this issue: https://github.com/angular/material2/issues/1854

**Comment by matze1234** [comment] 2020-09-24 13:19
for nested mat-tab-groups with dynamicHeights works with this workaround using *ngFor : 

```
<mat-tab-group [dynamicHeight]="true">
    <mat-tab #tab>
            <mat-tab-group *ngFor="let workaround of [tab.isActive]" [dynamicHeight]="true">
            ...

```

**Comment by Splaktar** [comment] 2021-01-10 00:51
From the [tabs platement docs](https://material.io/components/tabs#placement):

> **Caution** Avoid nesting a tab within another tab.

**Comment by Splaktar** [comment] 2021-01-10 02:49
Here's an updated [demo](https://stackblitz.com/edit/nested-mat-tab-groups-inkbar?file=src/app/tab-group-basic-example.html) that shows this is still reproducible.

**Comment by Splaktar** [comment] 2021-01-10 02:50
This will be fixed with the new MDC-based tabs (currently in `@angular/material-experimental`): [Demo](https://stackblitz.com/edit/nested-mdc-tab-groups-inkbar?file=src/app/tab-group-basic-example.html)

**Comment by amysorto** [comment] 2022-11-14 23:29
This is still an issue with the current components in v14. Although the new MDC based tab component coming soon in v15 does not have this issue.

**Closed by amysorto** 2022-11-14 23:29 UTC
Labels: P3, area: material/tabs, Fixed in MDC
