### ISSUE TITLE
Text not vertical aligned with md-icon in md-menu-item

### ISSUE THREAD

**Issue by ocarreterom** [angular/components#4773] opened 2017-05-24 14:41 UTC
#### Bug, feature request, or proposal:
Bug.

#### What is the expected behavior?
The text of `md-menu-item` should be vertical aligned with the left icon.

#### What is the current behavior?
The text is not vertical aligned with the icon.

#### What are the steps to reproduce?
Demo: http://plnkr.co/edit/RnTWx1YRY2qNwv6NniQO

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material: 2.0.0-beta.5-eecf897

#### Is there anything else we should know?
Wrapping the text with `<span [style.vertical-align]="'middle'">Text aligned</span>` solves the problem.

**Comment by donroyco** [comment] 2017-07-19 18:45
Tried to see if this is resolved in the latest beta of Material2, but apparently[ the issue is still there](http://plnkr.co/edit/zse8PtVJvsAqIFLrUQ3u?p=preview) (forked from the issue template).

**Comment by jelbourn** [comment] 2021-02-23 23:38
Closing since this appears to have been fixed some time ago

**Closed by jelbourn** 2021-02-23 23:38 UTC
Labels: P3, area: material/icon, area: material/menu
