### ISSUE TITLE
[bug] OverlayService does not consider different platforms

### ISSUE THREAD

**Issue by flash-me** [angular/components#17623] opened 2019-11-06 08:11 UTC
#### Reproduction

Repro repo: https://github.com/flash-me/cdk-overlay-issue 

Steps in repo description 

![](https://raw.githubusercontent.com/flash-me/cdk-overlay-issue/master/overlay_issue.gif)
 
 
#### Expected Behavior
**tl;dr** 
`OverlayContainer` should only mind about its own business :smile: 

#### Actual Behavior

When working with multiple platforms, the `OverlayContainer` Service of the current bootstrapped `platform`
deletes the references of the previous <div class="cdk-overlay-container></div>, so their overlays will not work anymore.

#### Environment

- Angular: 9.0.0-rc.0, but also happens with 8.x.x
- CDK/Material: same
- Browser(s): latest Chrome

**Comment by flash-me** [comment] 2019-11-06 08:24
Workaround:
https://gist.github.com/flash-me/3fef8b072c3e7c815ad1357bc0d4bffb

**Comment by crisbeto** [comment] 2019-11-06 12:17
What are you referring to when you say "different platforms"? Is it containers that were created during server-side rendering?

**Comment by flash-me** [comment] 2019-11-06 13:57
Simplest example:
2 Angular Elements Projects that are loaded within the same page
Typically created in `main.ts`:
![image](https://user-images.githubusercontent.com/5240450/68304265-b422ba00-00a5-11ea-81c4-4518380e3c8d.png)

**Comment by flash-me** [comment] 2019-11-06 14:00
I call them "platform" due to their method names, which are used in behind:
- [getPlatform](https://github.com/angular/angular/blob/master/packages/core/src/application_ref.ts#L204)
- [createPlatform](https://github.com/angular/angular/blob/master/packages/core/src/application_ref.ts#L125)

**Comment by flash-me** [comment] 2019-11-06 15:37
There is already a PR for it
https://github.com/angular/components/issues/16851

**Comment by crisbeto** [comment] 2019-11-06 21:19
Yes, it'll be fixed by the linked PR. Closing as a duplicate of https://github.com/angular/components/issues/16851.

**Closed by crisbeto** 2019-11-06 21:19 UTC
