### ISSUE TITLE
help(Form-Field): custom more compact form-field without label and hint using density?

### ISSUE THREAD

**Issue by diuming** [angular/components#26364] opened 2023-01-04 16:29 UTC
### What are you trying to do?

Is it possible to custom more compact form-field?

.my-mat-form-field-density-5 is working.
.my-mat-form-field-density-8 not working.
SassError: "mdc-density: height must be between 36px and 56px (inclusive), but received 24px."

```
<mat-form-field class="my-mat-form-field-density-8">
       <input matInput  [(ngModel)]="value">
 </mat-form-field>
```

```
@use '@angular/material' as mat;

@mixin my-form-field-density($density) {
    $field-typography: mat.define-typography-config(
        $body-1: mat.define-typography-level(12px, 24px, 400),
    );
    @include mat.typography-level($field-typography, 'body-1');
    @include mat.form-field-density($density);
    margin-bottom: -18px;   //  leaving a bottom margin 8px
}

.my-mat-form-field-density-5 {
    @include my-form-field-density(-5);
}

.my-mat-form-field-density-8 {
    @include my-form-field-density(-8);
}
```

### What troubleshooting steps have you tried?

```
.my-mat-form-field-density-8 {
    @include my-form-field-density(-8);
}
```

### Reproduction

@use '@angular/material' as mat;

@mixin my-form-field-density($density) {
    $field-typography: mat.define-typography-config(
        $body-1: mat.define-typography-level(12px, 24px, 400),
    );
    @include mat.typography-level($field-typography, 'body-1');
    @include mat.form-field-density($density);
    margin-bottom: -18px;   //  leaving a bottom margin 8px
}

.my-mat-form-field-density-5 {
    @include my-form-field-density(-5);
}

.my-mat-form-field-density-8 {
    @include my-form-field-density(-8);
}
```


### Environment

Angular: 15.0.4
CDK/Material: 15.0.3
Browser(s): Safari 16.2
Operating System: macOS

**Comment by workcomped** [comment] 2023-01-12 23:00
I'm also looking for this.

Currently, the lowest mat-form-field density that will compile is -2 although if you do that [you will lose your labels if you have a fill appearance (the default appearance)](https://github.com/angular/components/issues/26185) which is simply untenable for our application.

Unfortunately, our business wanted slightly smaller fields for these internal applications so this migration is going to be interesting!

**Comment by mrmokwa** [comment] 2023-01-25 20:08
If I use
`@include mat.all-component-densities(-2);`
And
`appearance: 'fill'`

Placeholder is not shown:

![image](https://user-images.githubusercontent.com/12090931/214677610-42952f78-afcd-43a6-9b5c-feb0690a22f3.png)

Using 
@include mat.all-component-densities(0);
or 
@include mat.all-component-densities(-1);

Then the placeholders are displayed 

![image](https://user-images.githubusercontent.com/12090931/214677837-96ac6ade-d600-42c0-a192-84c16606262e.png)

**Comment by NachmanBerkowitz** [comment] 2023-05-15 22:48
See https://github.com/angular/components/issues/26579

**Comment by wagnermaciel** [comment] 2023-05-19 19:25
+1 to what @NachmanBerkowitz said. Closing this as a duplicate of https://github.com/angular/components/issues/26579

**Closed by wagnermaciel** 2023-05-19 19:25 UTC
Labels: troubleshooting, needs triage
