### ISSUE TITLE
bug([mat-checkbox]): Checkbox animation is not rendered properly in multi-column layout

### ISSUE THREAD

**Issue by jayzelenkov** [angular/components#19089] opened 2020-04-16 23:11 UTC
#### Reproduction

https://stackblitz.com/edit/angular-hcasdt?file=src%2Fapp%2Fcheckbox-overview-example.html

Steps to reproduce:
1. Create an unordered list with each checkbox being wrapped by a list item tag
2. Set `column-count: 2;` on the unordered list
3. Observe the first checkbox of every column, starting with the second one, doesn't properly animate on toggle (animation effects are rendered at the bottom of the previous column)

 
#### Expected Behavior

Checkbox at the top of every column should animate.

#### Actual Behavior

Checkbox at the top of every column (starting with the second one) doesn't animate.

#### Environment

- Angular: 9.1.2
- CDK/Material: 9.2.1/v1.1.21 
- Browser(s): Chrome 80.0.3987.163
- Operating System (e.g. Windows, macOS, Ubuntu): macOS, Ubuntu

**Comment by jelbourn** [comment] 2020-05-29 22:12
Confirmed that there's a weird flow/rendering issue in Chrome and Safari only (Firefox and Edge work fine). It also seems to be fixed in the MDC version of the checkbox.

**Comment by crisbeto** [comment] 2022-06-30 11:58
Duplicate of #25153 which has a pending fix.

**Closed by crisbeto** 2022-06-30 11:58 UTC
Labels: P5, area: material/checkbox, Fixed in MDC
