### ISSUE TITLE
Fixed Sidenav is clipped by mat-sidenav-container in Safari

### ISSUE THREAD

**Issue by annsk** [angular/components#16491] opened 2019-07-10 07:30 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/angular/bbylpommldm?file=app%2Fsidenav-fixed-example.ts (it's link from Angular Material documentation.

Steps to reproduce:
1. Select checkbox "fixed"
 
#### Expected Behavior

The sidenav should be over the header and footer in Safari.

![Adnotacja 2019-07-10 092837](https://user-images.githubusercontent.com/533432/60949305-33b99b80-a2f5-11e9-8e28-81a25a0d4111.png)

#### Actual Behavior

What behavior did you actually see?
In Safari the sidenav is below the header and footer in Safari.

![Adnotacja 2019-07-10 092907](https://user-images.githubusercontent.com/533432/60949325-3c11d680-a2f5-11e9-8da4-dc02a2b7c7e0.png)

#### Environment

- Angular: 8.1.0
- CDK/Material: 8.0.2
- Browser(s): Safari 12.0.1, 
- Operating System (e.g. Windows, macOS, Ubuntu): macOS, iOS

**Comment by Brhav** [comment] 2019-09-09 07:00
+1

**Comment by Brhav** [comment] 2019-09-15 10:46
This only occurs when using [fixedInViewport]. Workaround is not using this.

**Comment by jelbourn** [comment] 2020-05-27 23:35
Duplicate of #11715

**Closed by jelbourn** 2020-05-27 23:35 UTC
Labels: P2, area: material/sidenav
