### ISSUE TITLE
bug(material/tabs): ripple effect not apply to full width with mat-stretch-tabs

### ISSUE THREAD

**Issue by mouisaac** [angular/components#23051] opened 2021-06-23 17:27 UTC
First time reporting a bug, please kindly let me know if I miss anything or if it is not actually a bug. I have posted this issue in SO but didn't get an answer yet (https://stackoverflow.com/questions/68079434/angular-material-tab-ripple-effect-on-click-does-not-apply-to-full-tab-after-str).

#### Reproduction

StackBlitz:
https://stackblitz.com/edit/angular11-mat-stretch-tabs-ripple-not-apply-to-full-tab?file=src/app/app.component.ts

Steps to reproduce:
1. Just click between the tabs (label 1 and label 2) and look at the ripple effect on the second tab.
 
<img width="326" alt="rocKI" src="https://user-images.githubusercontent.com/25886568/123141744-b37b9a80-d426-11eb-82b1-6193b11a1ffd.png">
 
#### Expected Behavior

The ripple effect should apply to the full tab width. It should work with the 'mat-stretch-tabs' directive.

#### Actual Behavior

The ripple effect only applies to the initial tab width.

#### Environment

- Angular:
- CDK/Material: 11.2.12/11.2.13/11.2.14
- Browser(s): Chrome Version 91.0.4472.114
- Operating System: macOS Catalina

**Comment by crisbeto** [comment] 2021-06-23 18:25
Thank you for the reproduction case, but I'll have to close the issue. For performance reasons we only measure the size of the ripple trigger on the first ripple. Since it resizes after the first click, the dimensions will be outdated. I don't think that we should change this, because it's an edge case and handling it could degrade performance.

**Closed by crisbeto** 2021-06-23 18:25 UTC
Labels: needs triage
