### ISSUE TITLE
bug(mat-datepicker): Restrict MatCalendarView

### ISSUE THREAD

**Issue by angelaki** [angular/components#24915] opened 2022-05-12 12:44 UTC
### Feature Description

I'd like to be able to disable some MatCalendarView options.

### Use Case

I'm using the picker as a month picker. When changing the view the user get irritated by being able to select a day since the picker usualy closes on month selection (via `(monthSelected)`).

**Comment by zarend** [comment] 2022-05-20 16:49
Hello @angelaki , I think we have instructions for what you are trying to accomplish in [Datepicker emulating a Year and month picker
](https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months).

Could you please take a look at the above documentation and let us know if the datepicker meets your needs?

Thanks,
Zach

**Comment by angelaki** [comment] 2022-05-23 06:13
Hey @zarend in this example you can still toggle to `month` view, what is a bit irritating:

![image](https://user-images.githubusercontent.com/38611461/169754879-3a6fe5a8-3bc6-4456-911b-708602ecdf57.png)

**Comment by zarend** [comment] 2022-05-27 16:33
Interesting, I'm not able to toggle to `month` view in the [Datepicker emulating a Year and month picker](https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months) example...

How are you able to do that? What steps did you take?

## Environment
 - Chrome Version 102.0.5005.61 (Official Build) (x86_64)
 - macOS 12.4 (21F79)

**Comment by angelaki** [comment] 2022-05-30 07:06
Actually quite easy, just click the years: 
![image](https://user-images.githubusercontent.com/38611461/170936001-353d7f94-7663-4819-8189-04817159e2ad.png)

Next you are able to select a day in the month.

**Comment by zarend** [comment] 2022-05-31 17:38
Thanks for reporting; I can reproduce. This looks to me like an issue with the example, rather than the date-picker itself. I should be able to look into fixing the example later.

**Comment by angelaki** [comment] 2022-05-31 21:20
Actually I don't know what should keep the picker from allowing it. It has an initial view and catches the month selected event. I guess that use-case just isn't supported (yet)?

**Comment by angelaki** [comment] 2022-05-31 23:25
Just saw you also responded to my issue https://github.com/angular/components/issues/24914. Guess it's pretty related.

**Comment by zarend** [comment] 2022-06-06 23:35
Well, clicking on the period button is supposed to change the view present, but not select anything. The calendar doesn't know that it's not supposed to show the month view in this case. I don't see any quick fix to fix this example.

A work-around for this is to use a custom calendar header. I will follow up with this, but it seems like the built-in header is not designed for being used as a month-year picker, or a year picker.

For now, a work-around is [customizing the calendar header](https://material.angular.io/components/datepicker/overview#customizing-the-calendar-header). That would be creating a header that handles switching between year and multi-year view, but doesn't switch to month view.

@crisbeto and @mmalerba, do you have context on the intended direction for the month-year picker example? This seems to be more of a limitation of specifically the header to me.

**Comment by zarend** [comment] 2022-06-17 17:29
Hello, so I'm triaging this as a bug.

The fix here is to provide a custom header. The header would need appropriate navigation for next/previous on the year and multi-year views. It would also need appropriate navigation for switch between year and multi-year view. A good place to start is looking at the [customizing the calendar header](https://material.angular.io/components/datepicker/overview#customizing-the-calendar-header) example.

We welcome contributions if you are interested :).

**Comment by mmalerba** [comment] 2022-06-23 16:43
You should be able to run our dev app with `yarn dev-app` and then navigate to http://localhost:4200/examples to see a list of all examples. The code for our datepicker examples lives under src/components-examples/material/datepicker

**Comment by csisy** [comment] 2022-11-28 07:20
+1 for this feature.

> Hello @angelaki , I think we have instructions for what you are trying to accomplish in [Datepicker emulating a Year and month picker ](https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months).
> 
> Could you please take a look at the above documentation and let us know if the datepicker meets your needs?
> 
> Thanks, Zach

The example is a bid awkward. When you click on a month, first the view is changed, then the picker is closed. This causes a flash into the month view before closing.

**Closed** 2023-02-21 08:06 UTC
Labels: docs, P4, good first issue, area: material/datepicker
