### ISSUE TITLE
bug(Expansion Panel): style DOM search/find is hiding collapsed UI element

### ISSUE THREAD

**Issue by zombaki** [angular/components#25513] opened 2022-08-22 18:55 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Never tested in previous element

### Description

when an expansion panel is collapsed , if we inspect and search for an existing element/ keyword string . Expansion title and expansion buttons disappears.

### Reproduction

Steps to reproduce:
1. Create a component with expansion panel with title
2. Create a label in expansion panel body with static text and html ID 
3. Run application
4. make sure expansion panel is in collapsed state
![image](https://user-images.githubusercontent.com/15192370/185997061-ab67d8aa-5957-4f2e-bf41-b7355edf66ee.png)

5. inspect page and ctrl+f ,find labelId
![image](https://user-images.githubusercontent.com/15192370/185997497-fbd09c81-299e-4d82-909e-fac2bb6f3c2d.png)

6. title and expansion button is not visible

### Expected Behavior

We should be able to find the DOM element on find with id

### Actual Behavior

application is hiding whole expansion panel

### Environment

- Angular: 12.1.2
- CDK/Material: 12.1.2
- Browser(s): chrome / edge
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by geromegrignon** [comment] 2022-08-23 07:55
Hi @zombaki,
I can't reproduce it and might miss some information, please provide a Stackblitz reproduction.

**Comment by crisbeto** [comment] 2022-08-31 09:50
Can you try it with the latest version of Material? I wasn't able to reproduce it here: https://material.angular.io/components/expansion/overview

**Comment by crisbeto** [comment] 2022-09-27 12:15
Closing the issue since I wasn't able to reproduce it and there hasn't been a response.

**Closed by crisbeto** 2022-09-27 12:15 UTC
Labels: needs triage
