### ISSUE TITLE
Stackblitz demos are not working

### ISSUE THREAD

**Issue by hishamhafeel** [angular/components#23144] opened 2021-07-11 04:42 UTC
#### Reproduction

Steps to reproduce:
1. Open https://angular-ivy-wdb4jy.stackblitz.io/
2. The attached image is seen. The page stays like that and then crashes.
![image](https://user-images.githubusercontent.com/48839088/125182980-3f1b6680-e230-11eb-8a4a-6a64f8e61af1.png)

 
 
#### Expected Behavior

The application must run successfully.

#### Actual Behavior

Application crashes without any errors.

#### Environment

- Angular: 12.1.0
- CDK/Material:12.1.0
- Browser(s): Google Chrome Version 91.0.4472.124
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by crisbeto** [comment] 2021-07-11 05:26
I could reproduce it from your link as well, but a few random examples from the docs worked as expected. Does this happen on all examples for you or a specific one?

**Comment by frunjik** [comment] 2021-07-15 11:53
https://stackblitz.com/angular/rebkdnjnvdg?file=src%2Fapp%2Fpaginator-harness-example.ts
One more failing demo (different reason ?)

**Comment by crisbeto** [comment] 2021-07-21 18:54
The text harness issue is known and should be fixed by https://github.com/angular/material.angular.io/pull/1009. I'm closing the issue since there hasn't been any feedback.

**Closed by crisbeto** 2021-07-21 18:54 UTC
Labels: needs triage
