### ISSUE TITLE
mat-outline-gap width not true calculate when use material drag and drop

### ISSUE THREAD

**Issue by hediehrafiee** [angular/components#21726] opened 2021-01-28 00:04 UTC
I have list accordion than i drag and drop this list with Angular material .
![1](https://user-images.githubusercontent.com/22467829/106070579-f8bacb00-6119-11eb-813c-fef0c2e9f0d9.png)

I use mat-form-field in this each mat-accordion , before drag and drop its true work!
![2](https://user-images.githubusercontent.com/22467829/106070646-14be6c80-611a-11eb-9510-90fe8397cd8f.png)

but when I drag and drop my accordions 
my mat-outline-gap width not true calculate , why ?

![3](https://user-images.githubusercontent.com/22467829/106070889-8991a680-611a-11eb-8801-937fe7344764.png)

ــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــــ
**It is very interesting that if I don't open the accordions and drag, there will be no problem**

**Comment by crisbeto** [comment] 2021-02-01 16:00
It's difficult to tell what could be going on without a reproduction. Can you post a Stackblitz that shows the issue?

**Comment by crisbeto** [comment] 2021-07-28 17:25
Closing since there hasn't been any feedback. The issue can be reopened if we get more information.

**Closed by crisbeto** 2021-07-28 17:25 UTC
Labels: area: cdk/drag-drop, area: material/form-field, needs clarification
