### ISSUE TITLE
bug(mat-tab-group): loosing focus if selected tab is disabled

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#25334] opened 2022-07-25 12:35 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In `mat-tab-group`, if selected index is set to disabled mat-tab, then the `mat-tab-group` is completely loosing the focus. 
There is no way to select another tab via keyboard. 

### Reproduction

Steps to reproduce:
1. Visit https://stackblitz.com/edit/angular-36rzue?file=src/app/tab-group-basic-example.html
2. Click on button `ABC`
3. Now press tab and check if focus is moving inside mat-tab-group

### Expected Behavior

Focus should move to different/nearest enabled tab of `mat-tab-group`

### Actual Behavior

Focus is not moving to different/nearest enabled tab of `mat-tab-group`

### Environment

- Angular: ~14.0.0
- CDK/Material: 14.1.0
- Browser(s): Chrome/Edge 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by zarend** [comment] 2022-07-25 17:10
I believe this is working as intended.  Having [selectedIndex] set to a disabled tab is an invalid state.

In the provided stackblitz, the selectedIndex is set to 1 and the tab at index 1 is disabled.

```
<mat-tab-group [selectedIndex]="1">
  <mat-tab label="First"> Content 1 </mat-tab>
  <mat-tab label="Second" disabled> Content 2 </mat-tab>
  <mat-tab label="Third"> Content 3 </mat-tab>
</mat-tab-group>
```

The fix is for the developer to reassign `selectedIndex` if the tab it points to becomes disabled.

**Closed by zarend** 2022-07-25 17:10 UTC
Labels: needs triage
