### ISSUE TITLE
Input mask 

### ISSUE THREAD

**Issue by zarija-gavrilovic** [angular/components#23629] opened 2021-09-23 18:29 UTC
#### Feature Description

it would be grate if you could make input mask, date-picker with input mask etc...

### Example with date-picker:
1. Untouched
![image](https://user-images.githubusercontent.com/58690622/134563007-e7eb8a7a-7361-4ffc-8707-7bdf7b0ab57a.png)
 
2. Touched 
![image](https://user-images.githubusercontent.com/58690622/134563123-1686ab25-81c5-4e7c-85a7-ca1e14a9ca11.png)

3. Start writing
![image](https://user-images.githubusercontent.com/58690622/134563199-5f13ac33-04aa-425c-a361-74429739139e.png)

4. Finish 
![image](https://user-images.githubusercontent.com/58690622/134563328-c8005984-1696-45c2-b72e-62272cf61962.png)

**Comment by lekhmanrus** [comment] 2021-09-24 00:52
It looks like described functionality already achievable thanks to [@angular/material/datepicker](https://material.angular.io/components/datepicker/api) in conjunction with [ngx-mask](https://github.com/JsDaddy/ngx-mask). 🙂

**Comment by zarija-gavrilovic** [comment] 2021-09-24 06:36
Yes I know, There is one catch. I had tried that way and its not what I want, just because of that I wrote ticket. I would be awesome to avoid installing other libraries.

**Comment by crisbeto** [comment] 2021-09-28 20:29
Duplicate of https://github.com/angular/components/issues/7645.

**Closed by crisbeto** 2021-09-28 20:29 UTC
Labels: feature, needs triage
