### ISSUE TITLE
Add option to reset md-progress-bar value without animation

### ISSUE THREAD

**Issue by wulfsberg** [angular/components#3502] opened 2017-03-08 16:09 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
When resetting the value of an md-progress-bar to 0 (starting a new task), the bar jumps directly to zero and increases from there.

#### What is the current behavior?
The bar slides backwards towards zero and starts increasing from wherever the animation reached.

#### What are the steps to reproduce?
http://plnkr.co/edit/XsN52k?p=preview

#### What is the use-case or motivation for changing an existing behavior?
It seems reasonable to reuse a progress bar, say, to indicate background loads of map tiles. The current behavior creates the visual impression that the progress bar is re-estimating the time for an already-ongoing task, rather than tracking a new one.

Possibly, a reasonable behavior would be to never use animation when setting the value to 0. This is a bit of a "magic corner case" but I think it would be what people intuitively expects.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular Material 2.0.0 beta 2

**Comment by M-a-c** [comment] 2017-03-14 22:36
Took a look at your code, there were some things that looked out of place.
this.percentage was not being reset to 0 when you clicked the button and when the 'download' finished.
and you were not removing this.timerHandle if you re-clicked the button.

http://plnkr.co/edit/7CwGk99baBS6tO0KL6qW?p=preview

**Comment by wulfsberg** [comment] 2017-03-14 22:43
I tried to keep the code to an absolute minimum to show the "animated slide back" behavior as the salient point.
Zeroing the percentage as the task completes just makes the bar slides backwards while it fades out at the end, which looks equally screwy.

**Comment by M-a-c** [comment] 2017-03-15 19:38
If you are strictly talking about hitting the button again yeah.. its how the code manages any delta, forward or backward it does bounce back. Google drive spawns a new bar for each download instead of using the same one. I see your point, the code I believe works as intended. but yeah maybe there should be something like a hardReset feature to allow just completely restarting without the animations, a clean slate sort of thing.

**Comment by michaeljota** [comment] 2017-07-29 21:31
Does this currently have a workaround or something?

**Comment by jelbourn** [comment] 2020-04-28 17:37
Closing this since I don't think realistically this would ever make it high enough on the priority queue to address.

**Closed by jelbourn** 2020-04-28 17:37 UTC
Labels: feature, needs discussion
