### ISSUE TITLE
Cross-Origin Request - https://material.angular.io/

### ISSUE THREAD

**Issue by John361** [angular/components#15699] opened 2019-04-03 12:21 UTC
#### What is the expected behavior?
All icons on the website should be show correctly but there is a problem with CORS

#### What is the current behavior?
All icons on the website are blocked because of the CORS and others errors in the web console

![Angular component website](https://user-images.githubusercontent.com/20155208/55478121-e78ef900-562b-11e9-8666-7d61529f29e5.png)

![Angular component website 2](https://user-images.githubusercontent.com/20155208/55478173-0ee5c600-562c-11e9-9902-b81dfe9c8b0b.png)

#### What are the steps to reproduce?
- Navigate on the https://material.angular.io website on Firefox (I did not test on other browsers)
- I have a website on my localhost, using Angular 7, Material components with icons and the problem is the same

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
- Angular 7
- Mozilla Firefox

#### Is there anything else we should know?
- I use Firefox plugin : CORS Everywhere

**Comment by jelbourn** [comment] 2019-05-10 22:28
It's not a CORS problems, it's just that those icons don't exist. Duplicate of https://github.com/angular/material.angular.io/issues/463

**Closed by jelbourn** 2019-05-10 22:28 UTC
