### ISSUE TITLE
Meterial Dialog and SideNav doesn't work on Chrome Extension

### ISSUE THREAD

**Issue by QuanJingHong** [angular/components#22907] opened 2021-06-06 14:04 UTC
The dialog should be closed when I call function close of MatDialogRef instance, but It doesn't.

I have a module called ShareModule, that contains HeaderCompose, and LoginComponent. HeaderComponent using LoginComponent to dialog.

```
<div class="HomeHeader-userinfo-2-nbm"><img class="HomeHeader-portrait-xqqY2"
            src="/assets/img/header-portrait.png"><span class="HomeHeader-login-D2hkS"
            style="color: rgb(253, 85, 83);"><span (click)="openDialog()">Login</span> | <span
                (click)="openDialog()">Register</span></span>
    </div>

constructor(public dialog: MatDialog) { }

openDialog(): void {
    const dialogRef = this.dialog.open(LoginComponent, {
      panelClass: 'custom-dialog-container',
      data: {name: 'alo', animal: 'dog'}
    });
    dialogRef.afterClosed().subscribe(result => {
      console.log('The dialog was closed');
    });
  }
```

In LoginComponent I have a button like this:
```
<div class="Login-close-j_-2T" [mat-dialog-close]="true" (click)="onNoClick()"><img src="/assets/img/login-close.png"></div>
constructor(public dialogRef: MatDialogRef<LoginComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any) { }

onNoClick(): void {
    this.dialogRef.close();
  }

```

I import ShareModuel to a module called HomeModule and using HeaderComponent.

When I press a button the Dialog show, But when I press close button, It should be closed but It doesn't. I have tried [mat-dialog-close] but It still doesn't work.

Environment

Angular: 11.0.2
CDK/Material:11.2.13
Browser(s): Chrome, Edge
Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2021-06-08 07:47
It's hard to tell what is going on without a reproduction, but it sounds like your code is running outside of the `NgZone`. Have you tried wrapping the calls in `NgZone.run`?

**Comment by QuanJingHong** [comment] 2021-06-08 11:45
> It's hard to tell what is going on without a reproduction, but it sounds like your code is running outside of the `NgZone`. Have you tried wrapping the calls in `NgZone.run`?

I want to run my code on Chrome Extension. I using have tried the code work be fine in Web, but when I compile the code for Chrome Extension It doesn't work well. Some thing doesn't work.

**Comment by jelbourn** [comment] 2021-07-22 17:05
Closing this since we don't have a reproduction. Feel free to open a new issue if you're able to share a reproduction.

**Closed by jelbourn** 2021-07-22 17:05 UTC
Labels: area: material/dialog, area: material/sidenav, needs clarification
