### ISSUE TITLE
md-overlay-container duplicated with angular-hmr

### ISSUE THREAD

**Issue by aminebizid** [angular/components#749] opened 2016-06-23 16:17 UTC
#### Bug:

When using Hot Module Reload and
 `provide(OVERLAY_CONTAINER_TOKEN, {useValue: createOverlayContainer()}),`
each reload duplicates md-overlay-container overlay div
#### What is the expected behavior?

Only one overlay div
#### What is the current behavior?

Overlay div duplicated
![image](https://cloud.githubusercontent.com/assets/7827225/16310933/c2f6ba56-396e-11e6-9b06-503ae2fa88dd.png)

**Comment by jimitndiaye** [comment] 2016-08-10 10:46
@zigzag95 Out of curiousity, which date picker is that? I thought the material date picker hadn't been implemented yet. Looks alot like material-ui's datepicker.

**Comment by zigzag95** [comment] 2016-08-10 13:15
@jimitndiaye https://github.com/zigzag95/DatePicker

**Comment by jimitndiaye** [comment] 2016-08-11 02:58
@zigzag95 thanks

**Comment by eslammahgoub** [comment] 2016-11-24 12:59
It's happen with me too with MdTooltip when I route from one to another route it's Overlay div duplicated many time any temp solution

**Comment by borislemke** [comment] 2017-04-22 10:19
I've only switched to using HMR (thank god I found it) and this issue seems to still be present.
When you leave a dialog open and edit your code, the overlay will not go away and you can't interact with your app unless:

- [x] You delete the active overlay through the chrome dev tools
- [x] Reload your browser

**Comment by AsafAgranat** [comment] 2017-12-21 21:05
I'm experiencing the same as @borislemke reports. I added HMR to my project and if there's a dialog open, a ghost overlay-container is added.

More importantly, **the dialog loses it's bind to the styles**. If you look at the `<head> `section of the document, among the injected `<styles>` tags you can find the specific `<style>` dedicated to `mat-dialog-container `. After a save (with hmr enabled), this style tag disappears. **Angular "forgets" to inject the style back to the document**.

To reproduce:
1. Enable HMR on a project with Angular Material 2
2. Set up a Material Dialog and open it
3. Inspect the `mat-dialog-container` element
4. In the inspector, click on the `<style>…</style>` link to the right of the `mat-dialog-container` class name - It'll take you to the <head> section and focus you on the relevant `<style>` tag
5. Change anything in your code - a TS, HTML or SCSS of any component, and save
6. Hot loading occurs without errors
7. The dialog corrupts as its relevant `<style>` tag in the head disappears. 
8. More than this is happening, as you can notice that elements in the dialog are not clickable (even when you get to them with the inspector's help)

I hope someone can get to the bottom of this. As I work on dialogs at the moment, I have to disable HMR as it makes it impossible to save any changes without a manual reload of the page.

**Before** HMR reload
![screenshot - 21_12_2017 22_57_42](https://user-images.githubusercontent.com/22475067/34274715-7d557c3e-e6a2-11e7-835e-6fad579058c4.png)

**After** HMR reload
![screenshot - 21_12_2017 22_58_09](https://user-images.githubusercontent.com/22475067/34274729-9212258c-e6a2-11e7-9275-3f36c0dcb7f2.png)

**Comment by stephengardner** [comment] 2017-12-22 04:17
I'm chiming in on this issue as well.  I had opened a SO issue [here](https://stackoverflow.com/questions/47700026/angular-material-dialog-hot-module-reload?noredirect=1#comment82833626_4770002, so far no answers.  Subbed to this thread.

**Comment by jeffrey-igaw** [comment] 2018-02-26 16:27
Please, HMR is reaaaaaaaaaaaaaaaallly necessary feature for us, EVERY DAY!

Dear Material team, Could you make HMR work properly with material 2?

**Comment by Yerkon** [comment] 2018-02-26 16:41
For them, it’s nice to have feature. No more no less

**Comment by RicardoVaranda** [comment] 2018-06-28 09:35
Any update on this issue, it's been over two years and to be honest while the 'hack solution' suggested by seabass223 works it's quite cumbersome and should not be required.

**Comment by yutsengwei** [comment] 2018-06-29 10:46
also facing this problem, its quite annoying me, is there any update? 
HMR is a nice feature, I need it!!! but with this problem... I just disabled it.

**Comment by elixiao** [comment] 2018-07-26 10:43
As mentioned in this [isssue](https://github.com/angular/angular-cli/issues/9600): Successful hot module replacement requires the components to be designed.  Really hope this problem could be resolved soon.

**Comment by jelbourn** [comment] 2018-07-26 15:21
If anyone wants to contribute a PR for this I'll be happy to take a look

**Comment by torabian** [comment] 2018-11-23 11:07
You can use amazing time picker (amazing-time-picker) for this purpose, and it is fully compatible with Angular 2-7 and Material design:

https://github.com/owsolutions/amazing-time-picker

Live demo:
https://owsolutions.github.io/amazing-time-picker

Thanks.

**Comment by stephengardner** [comment] 2018-11-23 11:21
@torabian dude beat it with the completely unrelated self promotion

**Comment by wnvko** [comment] 2019-02-18 14:14
I was trying to reproduce this with angular 7.2.5, angular cli 7.3.1 on Windows 10 and was not able to reproduce it. On each HMR reload the dialog closes and overlay div disappears  from the page. I also tried steps @AsafAgranat suggested and styles did not break. Attached is the sample I have tested this. To test with my sample do the following:
- inzip
- npm install
- npm run start

This will start the application with HMR.

Are there any additional steps needed to reproduce this? 

[dialog-with-hmr.zip](https://github.com/angular/material2/files/2875955/dialog-with-hmr.zip)

**Comment by jelbourn** [comment] 2019-02-19 22:13
It might be fixed now if the HMR is smart enough to invoke the `ngOnDestroy` of the loaded NgModules / providers.

**Comment by fergardi** [comment] 2019-06-07 10:01
@jelbourn what is the default setting for this to work correctly? Something like this does not work for my if a hot module reload is performed:

```js
export class ExampleComponent implements OnInit, OnDestroy {
  constructor(
    private dialog: MatDialog
  }
  ...
  ngOnDestroy {
    this.dialog.closeAll()
  }
}
```

**Comment by crisbeto** [comment] 2022-06-28 11:12
We're in the process of cleaning up our backlog. Given that this issue hasn't had any activity in two years, I'm assuming that it was resolved. If that's not the case, it can be reopened.

**Closed by crisbeto** 2022-06-28 11:12 UTC
Labels: P5, help wanted, area: cdk/overlay
