### ISSUE TITLE
bug(expansion-panel): Contents pop in before are hidden

### ISSUE THREAD

**Issue by westlakem** [angular/components#21838] opened 2021-02-08 16:15 UTC
Steps to reproduce:
1.  Create an expansion panel as follows:
```
<div>
  <mat-accordion>
    <mat-expansion-panel>
      <mat-expansion-panel-header>
        <mat-panel-title> Instructions </mat-panel-title>
      </mat-expansion-panel-header>
      <ol>
        <li>step 1 </li>
        <li>step 2 </li>
      </ol>
      <div>
        <img alt="picture of instructions" src="assets/instructions.png">
      </div>
    </mat-expansion-panel>
  </mat-accordion>
</div>
```

2. Load component
 
 
#### Expected Behavior

accordion to load closed

#### Actual Behavior

image and instructions flash on the screen before being hidden

#### Environment

"dependencies": {
    "@angular/animations": "~11.1.0",
    "@angular/cdk": "^11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "~11.1.0",
    "@angular/core": "~11.1.0",
    "@angular/forms": "~11.1.0",
    "@angular/material": "^11.1.0",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/router": "~11.1.0",
    "realm-web": "^1.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },

**Comment by crisbeto** [comment] 2021-02-08 16:49
I couldn't reproduce it based on the provided instructions, the accordion loaded as expected. It might be caused by something else from your app which is interfering with the expansion panel. Closing the issue for now, but it can be reopened if there's a reproduction the bug.

**Closed by crisbeto** 2021-02-08 16:49 UTC
Labels: needs triage
