### ISSUE TITLE
bug(COMPONENT): Not able to set width in Material 3 dialog 

### ISSUE THREAD

**Issue by steveareeno** [angular/components#29662] opened 2024-08-29 13:17 UTC
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Material 2

### Description

I upgraded to material 3 and it seems the "width" property on the dialog is ignored. I have to set the minWidth property to get the dialog to size properly:

`    return this.dialog.open(SuretyDocumentUploadDialogComponent, {
      width: '600px', -- ignored
      height: '80vh',
      minWidth: '600px', -- works
      autoFocus: false,
      data: {
        title,
        id,
        applicationId,
        suretyModel,
        documentTypeId,
        modelTypeEnum,
      },
    });
`

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. call the dialog open method, specifying the width property alone. The dialog width is not changed
2. add the minWidth property and call it again. The width is changed

### Expected Behavior

I expect that width would set the dialog width

### Actual Behavior

It does not seem to set the width

### Environment

- Angular: 18.2.1
- CDK/Material: 18.2.0
- Browser(s): Chrome, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2024-08-30 07:07
The problem is that the dialog needs to support both M2 and M3. In M2 it had no min width/height, but to match M3 it has to have minimum and maximum. Since the switch happens only through CSS while the width is controlled through JS, it gets a bit tricky to override the default. For your example you'd have to set `minWidth: 0, maxWidth: '100%', width: '600px'`. Closing since this is basically the same as #29384.

**Closed by crisbeto** 2024-08-30 07:07 UTC
Labels: needs triage
