### ISSUE TITLE
feat(selection-list): Add support to radio like mat-selection-lit

### ISSUE THREAD

**Issue by Totati** [angular/components#20922] opened 2020-10-29 17:41 UTC
#### Feature Description

Currently `<mat-selection-list multiple="false"></mat-selection-list>` behaviour is far from ideal. It should support radio button style like it supports checkboxes, and when used as single selection, the value shound not be an array. It should work like `radio-button-group` with a style of selection list.

#### Use Case

Ceating a single selection-list that properly indicates it's single selectable.

#### Demo

[(Stackblitz)](https://stackblitz.com/edit/angular-pxnamm?file=src%2Fapp%2Flist-selection-example.html) I've hacked the current selection list arund with style and so, but it's quite ugly. I'll understand it this issue get low prio, beacuse of [mdc](https://material-components.github.io/material-components-web-catalog/#/component/list), but this issue is not just about styling, but behaviour too.

**Comment by crisbeto** [comment] 2020-10-29 18:39
Duplicate of https://github.com/angular/components/issues/7157.

**Closed by crisbeto** 2020-10-29 18:39 UTC
Labels: feature, needs triage

**Comment by Totati** [comment] 2020-10-29 19:25
Ohh, thank you, I've searched for this, but could not find it.
