### ISSUE TITLE
CDK Overlay - Panel position incorrect after applying transform: scale

### ISSUE THREAD

**Issue by ThisIsArnab** [angular/components#20181] opened 2020-08-04 14:21 UTC
#### Reproduction

https://stackblitz.com/edit/angular-ivy-ceaw9i

Steps to reproduce:
1.  Use any Angular material component having panel (such as select)
2.  Apply transform: scale on the page (for cross-browser zooming purpose)
 
 
#### Expected Behavior

Panel of the component should be positioned accordingly after applying scaling

#### Actual Behavior

Panel is positioned incorrectly.

#### Environment

- Angular: 10.0.1
- CDK/Material: 10.1.2
- Browser(s): Google Chrome  84.0.4147.105
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

![cdk-overlay-issue](https://user-images.githubusercontent.com/13291820/89305044-c90b9880-d68b-11ea-8306-eec244bfb95b.png)

**Comment by crisbeto** [comment] 2020-08-16 07:31
Closing as a duplicate of https://github.com/angular/components/issues/10924 since it's the same root cause.

**Closed by crisbeto** 2020-08-16 07:31 UTC
Labels: P5, area: cdk/overlay
