### ISSUE TITLE
select and de-select all options in mat-select dropdown

### ISSUE THREAD

**Issue by zeeshan9** [angular/components#26615] opened 2023-02-13 10:33 UTC
### Feature Description

There should be a built in feature to in select dropdown in angular material to select and deselect all option in dropdown. Currently we have to custom code this feature using mat-select-trigger like below code.

### Feature Description

There should be a built in feature to in select dropdown in angular material to select and deselect all option in dropdown. Currently we have to custom code this feature using mat-select-trigger like below code. 

### Use Case

There are numerous example where this feature is needed. This is quite a general feature which is needed most of the time in case of multiple selection. For example like below code, we can have multiple boarding option for user accounts app for admin, if he want to select all option, he needed to select all one by one, base on which our api is called. If some cases option are so much that its hard and time consuming to select or deselect all of them.
Currently there a lot of extra line of code need to be implemented to have this feature, and in some sites there can be lot of dropdowns especially in CMS sites. Built in feature for this save a lot of extra effort for this.

**Html File**
```
<mat-form-field class="ml-lg-auto mr-2 width-200">
                      <mat-select placeholder="Filter by Onboarding State"   [(ngModel)]="selectedOnboardingStates"
                           [compareWith]="compareSelectOptions" multiple >
                      <mat-select-trigger>
                        <mat-label *ngIf="selectedOnboardingStates && onBoardingStates.length !== 1 && 
                                     selectedOnboardingStates.length === onBoardingStates.length">All</mat-label>
                        <ng-container *ngIf="selectedOnboardingStates && selectedOnboardingStates.length !== 
                           onBoardingStates.length">{{selectedOnboardingStates[0] ? selectedOnboardingStates[0].name : ''}}<span *ngIf="selectedOnboardingStates.length > 1" class="example-additional-selection">
                            (+{{selectedOnboardingStates.length - 1}} {{selectedOnboardingStates.length === 2 ? 'other' : 'others'}})
                          </span>
                        </ng-container>
                      </mat-select-trigger> 
                      
                      <div class="mat-option" *ngIf="onBoardingStates && onBoardingStates.length !== 1">
                        <mat-checkbox color="primary" (change)="$event ? masterToggle() : null"
                          [indeterminate]="isAnySelected() && !isAllSelected()" [formControl]="masterToggleCheckbox"
                          class="qa-checkbox-master"
                          [ngClass]="selectToolTip() !== 'Select All' ? 'fas-font-green' : 'text-dark'">
                          Select All
                        </mat-checkbox>
                      </div>

                      <mat-option *ngFor="let item of onBoardingStates" [value]="item.id">
                        {{item.name}}
                      </mat-option>

                      </mat-select>
                    </mat-form-field>
```
**Model.ts File**
```
            export enum OnBoardingStates {
              PENDING = 0,
              ONBOARDED = 100
            }
```

**TS File**
```
// these method needed in code for above code work
       onBoardingStates: IStatus[] = [
            { name: 'Pending', id: OnBoardingStates.PENDING },
            { name: 'Onboarded', id: OnBoardingStates.ONBOARDED },
            { name: 'Cancel', id: OnBoardingStates.CANCEL}
          ];
       selectedAccountTypes: any[] = [];
       masterToggleCheckbox: FormControl = new FormControl(true);

       selectToolTip(): string {
    return this.isAllSelected() ? 'Deselect All' : 'Select All';
  }

  isAllSelected(): boolean {
    this.masterToggleCheckbox.setValue(this.onBoardingStates && this.selectedOnboardingStates?.length === this.onBoardingStates.length);
    return this.onBoardingStates && this.selectedOnboardingStates?.length === this.onBoardingStates.length;
  }

  isAnySelected(): boolean {
    return this.onBoardingStates && this.selectedOnboardingStates?.length < this.onBoardingStates.length && this.selectedOnboardingStates.length > 0;
  }

  masterToggle(): void {
    if (this.isAllSelected()) {
      this.selectedOnboardingStates = [];
    } else {
      const ids = this.onBoardingStates.map((item) => {
        return item.id;
      });
      this.selectedOnboardingStates = ids;
    }
  }
```

**Comment by amysorto** [comment] 2023-05-04 22:08
Duplicate of #9149

**Closed by amysorto** 2023-05-04 22:08 UTC
Labels: feature, area: material/select
