### ISSUE TITLE
bug: IntelliSense is broken for v18 in both VSCode and Visual Studio

### ISSUE THREAD

**Issue by IliaPodolko** [angular/components#29537] opened 2024-08-02 22:19 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

Installation of angular/material v18 breaks IntelliSense/Suggestions for some types from node_modules in VSCode and VS. I tried the same repo steps using angular v17 and everything works fine.

### Reproduction

Repo with this error https://github.com/IliaPodolko/vscode-imports
Steps to reproduce:
1. Create new angular app
    ng new my-angular-project
2. Go to app.component.ts and try add FormsModule, you will see suggestions
3. Install material
    npm install @angular/material
4. Go to app.component.ts and try add FormsModule, you will NOT see suggestions
5. Uninstall @angular/material and restart VSCode and after that suggestions work again.

### Expected Behavior

User should see suggestions in VS and VSCode
![image](https://github.com/user-attachments/assets/947462f0-056d-486e-b9cc-4cb569ef82ce)

### Actual Behavior

User does not see suggestions in VS and VSCode when using angular v18 with angular/material
<img width="562" alt="1" src="https://github.com/user-attachments/assets/64e222da-8b15-46fb-8356-52fac3a962c7">

### Environment

- Angular: 18.1.3 / also tried 18..0.0 - same issue
- CDK/Material: 18.1.3
- Operating System: Windows_NT x64 10.0.19045
- VS: 17.9.7
- VSCode: 1.92.0 (2024-07-31T23:26:45.634Z)
- Node: 18.20.2, also tried with v20 on another PC - same issue

**Comment by crisbeto** [comment] 2024-08-03 08:11
I couldn't reproduce it and I don't think we format of the code we push to npm has changed for v18 so this is likely an issue on your end. cc @devversion to confirm for the npm artifcats.

**Comment by IliaPodolko** [comment] 2024-08-03 21:38
I saw this issue on 3 PC.

I think I found the solution here https://www.reddit.com/r/angular/comments/1c4lsyl/how_to_set_up_vscode_intellisense_for_angular/

User PickleLips64151 says:
_...Once you make the initial manual import Intellisense picks up that import for future imports in that repo..._ 

and it helped!

**Comment by crisbeto** [comment] 2024-08-12 12:15
Closing since this sounds like it's just how vscode works.

**Closed by crisbeto** 2024-08-12 12:15 UTC
Labels: needs triage
