### ISSUE TITLE
DrawingManager for Maps

### ISSUE THREAD

**Issue by Innomalist** [angular/components#18599] opened 2020-02-24 17:06 UTC
#### Documentation Feedback

Couldn't find any information in regard to how to use `DrawingMananger` with Maps component.
I have tried following snippet but it neither works or throws any error:
```
this.drawingManager = new google.maps.drawing.DrawingManager({
      drawingMode: google.maps.drawing.OverlayType.POLYGON,
      drawingControl: true,
      drawingControlOptions: {
        position: google.maps.ControlPosition.TOP_CENTER,
        drawingModes: [google.maps.drawing.OverlayType.POLYGON]
      }
});
this.drawingManager.setMap(this.map._googleMap);
```
I have already added `libraries=drawing` in maps import of index.html too.

https://stackblitz.com/edit/angular-vvwbdg

**Comment by philip-firstorder** [comment] 2020-04-16 15:16
You must use the ngAfterViewInit function instead of ngOnInit, to give time for the google map to render in the DOM first.

**Comment by crisbeto** [comment] 2020-05-29 18:38
I can confirm that switching it to `ngAfterViewInit` resolve the issue. Closing since the component seems to work as expected.

**Closed by crisbeto** 2020-05-29 18:38 UTC
Labels: area: google-maps
