### ISSUE TITLE
Unable to get selected value out of dynamically created mat-select without falling back to NativeControl

### ISSUE THREAD

**Issue by dcolakchile** [angular/components#15374] opened 2019-03-03 12:55 UTC
# What is the expected behavior?

Being able to get the selected value out of a dynamically created mat-select control with document.getNativeElement or any other way

**WITHOUT USING NATIVECONTROL**, as it is being drawn completely different from the mat-select!

Using NativeControl **IS NOT THE SOLUTION!**

# What is the current behavior?
NativeElement created by mat-select does not hold the selected value

# What are the steps to reproduce?

```
<mat-form-field>
<mat-select id={{column.columnName}} placeholder="{{column.columnName|translate|capitalize}}">
<mat-option *ngFor="let foreignRow of foreignDataMap[getForeignTableName(column.columnName)]" [value]="foreignRow.uid">
 {{foreignRow.value}}
</mat-option>
</mat-select>
</mat-form-field>
```
```
var element = document.getElementById( column.columnName ) as HTMLInputElement;

element.value <-- does not exist
```
# Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All latest.

# Is there anything else we should know?

Yes, please **STOP CLOSING** this issue **without providing the bugfix**! 

Mixing nativeControl with mat controls is **unacceptable**, UI looks absolutely wrong.

**Comment by agpreynolds** [comment] 2019-03-04 07:58
See response https://github.com/angular/material2/issues/15341#issuecomment-469151248 please try and keep all comments on a single issue, even if that issue has been closed. If you make your case well enough the issue will be reopened.

**Comment by dcolakchile** [comment] 2019-03-06 18:18
Please stop closing issues without providing the solution and I'll stay in that single issue. :-) 👍

**Comment by josephperrott** [comment] 2019-06-04 18:50
Closing as duplicate of #15334

As noted in the other issues you have opened, this is working as expected.  Because the value is held in Angular's representation of the data structure, it is not stored in the DOM element.

Because our `MatSelect` is not built on top of the native `<select>`, the `value` property does not event exist on the `<mat-select>` element.  Since the underlying DOM object for `<mat-select>` element is not `HTMLSelectElement` (it is instead an `HTMLElement`), all of the properties that are available to interact with for a native `<select>` are not present.  This results in what you are looking to do in your description not being possible, it is a limitation caused how renders make rendering determinations with the `HTMLSelectElement`, preventing us from using it.

Instead you will need to, as noted in #15334, get a reference to the `MatSelect` instance either with a `ViewChild` or a template reference.  From there you will be able to get the value for the element.  I understand this is not the answer you are looking for on this issue, however this is the position we find ourselves in with the limitations of browsers.


Please note:  As has been mentioned in the other issues you have opened for this topic, It is not appropriate to continue opening multiple issues for the same request.  If you would like to continue discussion, please do so in the original issue that is opened for a request/issue.  Opening multiple issues for the same thing only works to fragment the discussion and make it more difficult for us to support and provides response/answers/solutions.

**Closed by josephperrott** 2019-06-04 18:50 UTC
