### ISSUE TITLE
bug(mat-chip-row): NG0100 mat-focused error

### ISSUE THREAD

**Issue by amri04** [angular/components#29411] opened 2024-07-10 12:44 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a chip connected to an input field, when clicking on the chip i open a mat dialog.
This results in a NG0100  ExpressionChangedAfterItHasBeenCheckedError. (Expression has changed after it was checked. Previous value for 'mat-focused': 'true'. Current value: 'false')

### Reproduction

StackBlitz link: https://stackblitz.com/edit/catwnq?file=src%2Fexample%2Fchips-input-example.html
Steps to reproduce:
1. click on the chip => NG0100: ExpressionChangedAfterItHasBeenCheckedError (see console)

### Expected Behavior

No error

### Actual Behavior

NG0100  ExpressionChangedAfterItHasBeenCheckedError:  Expression has changed after it was checked. Previous value for 'mat-focused': 'true'. Current value: 'false'

### Environment

- Angular: 18.1.3
- CDK/Material: 18.1.3
- Browser(s): Chrome
- Operating System: WIndows

**Comment by S-Prosper05** [comment] 2024-08-02 11:01
Hi @amri04, I tested with the latest version of Material 18.1.3 and it seems like the problem was fixed with the form field focus.

**Comment by amri04** [comment] 2024-08-02 11:50
Hi @S-Prosper05, the issue still exists, i just updated the dependencies to angular 18.1.3

**Comment by S-Prosper05** [comment] 2024-08-05 06:44
Hi  @amri04, I will take a look at it again

**Comment by crisbeto** [comment] 2024-12-24 06:40
I can't reproduce it with the latest code at head. Closing.

**Closed by crisbeto** 2024-12-24 06:40 UTC
Labels: P3, area: material/chips
