### ISSUE TITLE
bug(typography): Incorrect upgrade of mat-typography-config for v12

### ISSUE THREAD

**Issue by DenysVuika** [angular/components#22788] opened 2021-05-25 10:08 UTC
During the upgrade from v11 to v12, the component scss files are incorrectly updated in terms of typography configuration fetch.
 
#### Expected Behavior

As per the official guide <https://material.angular.io/guide/theming-your-components#reading-typography-values>,
should change `$config: mat-typography-config();` to `$config: mat.get-typography-config($theme)`

#### Actual Behavior

Changes `$config: mat-typography-config();` in each component style to `$config: mat.define-typography-config();`

**Comment by crisbeto** [comment] 2021-05-25 17:25
I'm not sure that the described expected behavior is correct here. `mat-typography-config` has always been used to define a typography config, the new API just renames it to make it clearer. We used to have `mat-get-typography-config` which turned into `mat.get-typography-config` with the new API, but it isn't even part of the migration.

**Comment by jelbourn** [comment] 2021-05-27 17:33
Closing since this does seem to be intended, and perhaps illustrates why the rename was useful- it was not really intuitive that `mat-typography-config()` _defined_ a config, not read one.

**Closed by jelbourn** 2021-05-27 17:33 UTC
Labels: needs triage
