### ISSUE TITLE
STACKBLITZ EXAMPLES NOT WORKING IN DOCUMENTATION!

### ISSUE THREAD

**Issue by davejacobs777** [angular/components#20284] opened 2020-08-12 21:42 UTC
#### Documentation Feedback

NONE OF THE STACKBLITZ EXAMPLES ARE WORKING IN THE DOCUMENTATION!!

**Comment by crisbeto** [comment] 2020-08-13 03:40
I tried a few and they seem to be working. Can you give an example?

**Comment by LeaBergerCH** [comment] 2020-08-13 09:35
https://stackblitz.com/angular/nqyvakemvvr?file=src%2Fapp%2Fsidenav-position-example.ts

Sidenav examples doesn't work for me

**Comment by crisbeto** [comment] 2020-08-13 09:39
It looks like the same issue as https://github.com/angular/components/issues/20271.

**Comment by devversion** [comment] 2020-08-13 21:11
Yeah. Closing as a duplicate of https://github.com/angular/components/issues/20271.

**Closed by devversion** 2020-08-13 21:11 UTC
Labels: docs, needs triage
