### ISSUE TITLE
error TS2322: Type 'MatMenu' is not assignable to type 'MatMenuPanel<any>'

### ISSUE THREAD

**Issue by splincode** [angular/components#24126] opened 2021-12-21 10:06 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

```ts
 <button mat-button [matMenuTriggerFor]="menu">{{ price | currency }}</button>
<mat-menu #menu="matMenu">
    <button mat-menu-item>EUR</button>
    <button mat-menu-item>DOL</button>
</mat-menu>
```

When I enable in `tsconfig.json` exactOptionalPropertyTypes I have problem 
```
"exactOptionalPropertyTypes": true,
```

Error

```
Error: integration/apps/virtual-table/src/samples/sample-second/sample-second.component.html:253:41 - error TS2322: Type 'MatMenu' is not assignable to type 'MatMenuPanel<any>'.
  Types of property 'hasBackdrop' are incompatible.
    Type 'boolean | undefined' is not assignable to type 'boolean'.
      Type 'undefined' is not assignable to type 'boolean'.

253                     <button mat-button [matMenuTriggerFor]="menu">{{ price | currency }}</button>
                                            ~~~~~~~~~~~~~~~~~

  integration/apps/virtual-table/src/samples/sample-second/sample-second.component.ts:21:18
    21     templateUrl: './sample-second.component.html',
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component SampleSecondComponent.

```

### Reproduction

Git clone https://github.com/angular-ru/angular-ru-sdk/

replace `<button mat-button [matMenuTriggerFor]="$any(menu)">{{ price | currency }}</button>`
to `<button mat-button [matMenuTriggerFor]="menu">{{ price | currency }}</button>`

### Expected Behavior

```
Error: integration/apps/virtual-table/src/samples/sample-second/sample-second.component.html:253:41 - error TS2322: Type 'MatMenu' is not assignable to type 'MatMenuPanel<any>'.
  Types of property 'hasBackdrop' are incompatible.
    Type 'boolean | undefined' is not assignable to type 'boolean'.
      Type 'undefined' is not assignable to type 'boolean'.

253                     <button mat-button [matMenuTriggerFor]="menu">{{ price | currency }}</button>
                                            ~~~~~~~~~~~~~~~~~

  integration/apps/virtual-table/src/samples/sample-second/sample-second.component.ts:21:18
    21     templateUrl: './sample-second.component.html',
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component SampleSecondComponent.

```

### Actual Behavior

No error

### Environment

- Angular: 12
- CDK/Material: 12
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2021-12-21 13:27
Duplicate of https://github.com/angular/components/issues/24078. You should be able to work around it by disabling `exactOptionalPropertyTypes`.

**Closed by crisbeto** 2021-12-21 13:27 UTC
Labels: needs triage
