### ISSUE TITLE
bug(cdkDropList/mat-tab-nav-bar): Wrong container for cdkPlaceHolder/cdkDrag after drag/hover from other list

### ISSUE THREAD

**Issue by gkrzysztofbury** [angular/components#29140] opened 2024-05-29 15:13 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The issue occurs when a button from the second nav-bar is dragged very slowly into the first one from the right side.

This happens because the `mat-tab-nav-bar` is not a single `<div>`, but consists of several layers:

```html
<div mat-tab-nav-bar cdkDropList>
  <button class="mat-mdc-tab-header-pagination-chevron"></button>
  <div class="mat-mdc-tab-link-container">
    <div class="mat-mdc-tab-list">
      <div class="mat-mdc-tab-links">
        <!-- content, "Tab 1", etc -->
      </div>
    </div>
  </div>
  <button class="mat-mdc-tab-header-pagination-chevron"></button>
  <!-- "Tab 5" lands here in the video --> 
</div>
```

When the dragged button enters another nav-bar, this function is called: [single-axis-sort-strategy.ts#L175](https://github.com/angular/components/blob/main/src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts#L175). Since it does not find `newPositionReference`, the base `cdkDropList` element is used as the parent of the placeholder: [single-axis-sort-strategy.ts#L213](https://github.com/angular/components/blob/main/src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts#L213).

### Reproduction

**Video:** [YouTube](https://youtu.be/aIcEy0thSfU)  
**StackBlitz:** [Example](https://stackblitz.com/edit/stackblitz-starters-6wobe5?file=src%2Ftabs_container.ng.html)

### Expected Behavior

Dragged button lands along with others 

### Actual Behavior

Dragged button lands in wrong container

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by crisbeto** [comment] 2024-05-30 05:02
Duplicate of https://github.com/angular/components/issues/29124.

**Closed** 2024-06-19 17:28 UTC
Labels: feature, P3, area: cdk/drag-drop
