### ISSUE TITLE
bug(mat-chip-option): overflows the content of a chip not respecting the width of the parent container (in version 14 it worked)

### ISSUE THREAD

**Issue by AdamsContreras999** [angular/components#26519] opened 2023-01-28 01:45 UTC
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

the content of a chip overflows when the content is sufficiently long, overflowing the text 

![image](https://user-images.githubusercontent.com/90850547/215234942-07eaef5c-223d-4f49-94b7-fc6adc8a29a3.png)
In this version works good 14.2.7

![image](https://user-images.githubusercontent.com/90850547/215234950-64949194-fa69-403c-b62e-aa8152c9de0d.png)
But in this version the material not work good 15.1.2

### Reproduction

Steps to reproduce:
1. Load a chip with enough text (even long enough to exceed the width of the parent container).
2. See what overflows in the current version of angular material 15.1.2

### Expected Behavior

The chip should cover the text by modifying its height, and covering all the text downwards without overflowing the parent container as it did in the angular 14.2.7 version.

### Actual Behavior

The text inside a chip in angular version 15.1.2 overflows.

### Environment

    "@angular/animations": "^15.1.2",
    "@angular/cdk": "^15.1.2",
    "@angular/common": "^15.1.2",
    "@angular/compiler": "^15.1.2",
    "@angular/core": "^15.1.2",
    "@angular/forms": "^15.1.2",
    "@angular/material": "^15.1.2",
    "@angular/platform-browser": "^15.1.2",
    "@angular/platform-browser-dynamic": "^15.1.2",
    "@angular/router": "^15.1.2",

**Comment by Siddhu-K** [comment] 2023-01-29 08:18
I had the same issue, I used the following to get the old behaviour https://github.com/angular/components/issues/26177#issuecomment-1348149300

**Comment by MikaStark** [comment] 2023-02-07 18:05
It's caused by this css rule. IMO, it should be removed.

```css
.mat-mdc-standard-chip .mdc-evolution-chip__cell--primary,
.mat-mdc-standard-chip .mdc-evolution-chip__action--primary,
.mat-mdc-standard-chip .mat-mdc-chip-action-label {
    overflow: visible;
}
```

**Comment by crisbeto** [comment] 2023-05-04 08:16
Duplicate of https://github.com/angular/components/issues/26584.

**Closed by crisbeto** 2023-05-04 08:16 UTC
Labels: needs triage
