### ISSUE TITLE
bug(MatCommonModule): Cannot read properties of undefined (reading '_applyBodyHighContrastModeCssClasses')

### ISSUE THREAD

**Issue by sireeshap** [angular/components#24185] opened 2022-01-11 14:26 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

8.0

### Description

I am really pity of the developer who closed a bug related to this without finding root cause [.]

(https://github.com/angular/components/issues/22250) 

The feature which implemented is targeting very rare use of IE, or some other nonfamous browsers as well as for limited users. But that is causing to blocking of an entire angular material framework usage for normal applications which target most of the customers. 

as per https://material.angular.io/cdk/a11y/api
"IE, Edge, and Firefox currently support this mode. Chrome does not support Windows High Contrast Mode. This service does not detect high-contrast mode as added by the Chrome "High Contrast" browser extension."
<img width="1345" alt="Screen Shot 2022-01-11 at 7 42 32 PM" src="https://user-images.githubusercontent.com/11473330/148958669-f439d8d5-fe5c-45e6-a0a6-697ab4db017f.png">

If it is not supported, the framework developer should make it an optional variable or need to take careful steps not to break anything.  But this causes blocker for entire application usage and not able to import material itself in angular app.

**This is araising in console, not during compilation time.**  

My Package.json is below
dependencies:
 "@angular/animations": "~11.1.0",
    "@angular/cdk": "^11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "~11.1.0",
    "@angular/core": "^11.1.0",
    "@angular/fire": "^6.1.5",
    "@angular/forms": "~11.1.0",
    "@angular/localize": "~11.1.1",
    "@angular/material": "^11.1.0",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/router": "~11.1.0",

devDependencies:
 "@angular-devkit/architect": "^0.1102.13",
    "@angular-devkit/build-angular": "^0.1102.5",
    "@angular-devkit/build-ng-packagr": "^0.1002.0",
    "@angular/cli": "~11.1.0",
    "@angular/compiler-cli": "~11.1.0",
<img width="894" alt="Screen Shot 2022-01-11 at 7 55 52 PM" src="https://user-images.githubusercontent.com/11473330/148961693-a0824b5a-9f08-4955-9095-f063296ee96c.png">

### Reproduction

Steps to reproduce:
1.  Try to use the version provided in bug and use chrome.
2. 

### Expected Behavior

Angular material should work flawlessly with all the latest versions(V8-V13), at least from above angular 8. Should not force the developer to degrade their versions.

### Actual Behavior

Tried with the below combinations. 
Angular 11- Material 11,
Angular 10-Material 10, 
Angular 12- Material 12, 
Angular 13 -Material13

None of them resolved this issue. 
Even Tried in Opera(Version:82.0.4227.43 (x86_64))- Same issue
Tried in Fire Fox(96.0b9)- Same issue.

![Uploading Screen Shot 2022-01-11 at 7.55.52 PM.png…]()

### Environment

- Angular: 11
- CDK/Material:11
- Browser(s):Chrome, Firefox, Mozilla
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs

**Comment by crisbeto** [comment] 2022-01-24 08:01
Duplicate of https://github.com/angular/components/issues/22250.

**Closed by crisbeto** 2022-01-24 08:01 UTC
Labels: needs triage

**Comment by sireeshap** [comment] 2022-01-25 04:14
@crisbeto  Did you read my comments well. I clearly mentioned that, even the bug which you mention #22250 also not solved & closed abruptly with out having proper solution. Again now you closed current bug based on that with out providing proper solution. Is this right way of  solving bug or mechanism introduced to escape a bug? Please reopen the bug & address if this library really mean for developers purpose.

**Comment by crisbeto** [comment] 2022-01-26 11:40
1. The information in the issue report isn't enough to be able to debug this.
2. While the docs state that this is primarily for non-Chrome browsers, it doesn't mean that it'll throw an error everywhere else. We have tests running across all browsers showing that it's not the case.
3. This code is run any time an Angular Material module is imported. Given the amount of users we have both externally and internally in Google, we should've seen much more than the 3 reports we've had so far. This leads me to believe that it's an issue somewhere in your setup.
