### ISSUE TITLE
tabs: nested tabs don't show selected md-tab

### ISSUE THREAD

**Issue by craigsh** [angular/components#5503] opened 2017-07-05 03:46 UTC
#### Bug, feature request, or proposal:

Bug: An md-tab-group inside an md-tab-group doesn't show the selected md-tab if the top-level md-tab isn't initially selected.

#### What is the expected behavior?

The md-tab should show its selected state even if not initially visible.

#### What is the current behavior?

The md-tab is not showing its selection.

#### What are the steps to reproduce?

Run the following plunker and click on Main tab two. 

http://embed.plnkr.co/lnZAqze9h6aLTvstcyet/

#### What is the use-case or motivation for changing an existing behavior?

The tab's contents are shown even though it's not showing as selected. Confusing for the user to know which tab they're looking at.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 4.2.5
Material 2.0.0-beta.6
Windows 10
Typescript 2.3.4
Chrome

#### Is there anything else we should know?
Nope

**Comment by willshowell** [comment] 2017-09-26 14:30
Updated plunker http://plnkr.co/edit/OC4GzLKZ6oiDowG2mUEy?p=preview.

As @julianobrasil mentioned in #7274, resizing the browser triggers showing of the ink, and the root cause is likely https://github.com/angular/material2/issues/5269.

**Comment by julianobrasil** [comment] 2017-09-26 14:35
As #5269 has lots of messages, I'd refer specially to https://github.com/angular/material2/issues/5269#issuecomment-310112634

**Comment by MaximoB** [comment] 2019-05-17 19:36
I am also experiencing this issue. Any updates?

**Comment by am-awais** [comment] 2019-06-17 10:32
please fix that bug for God sake,
Mostly forums of angular material were ignored or just said its the copy of this copy of that, and no one gives the correct answer I don't know why the community is ignoring these major open issues.

**Comment by manast** [comment] 2020-09-12 15:28
wow, just got hit by this issue, annoying, and even forcing a selected tab with ```selectedIndex``` does not work :/

**Comment by Splaktar** [comment] 2021-01-10 00:49
From the [tabs platement docs](https://material.io/components/tabs#placement):

> **Caution** Avoid nesting a tab within another tab.

**Comment by Splaktar** [comment] 2021-01-10 02:10
The above Plunkers are very out of date and broken. Here's a [StackBlitz repro](https://stackblitz.com/edit/nested-mat-tabs-index-issue?file=src%2Fapp%2Ftab-group-basic-example.html) of this issue which still exists.

**Comment by Splaktar** [comment] 2021-01-10 02:17
This will be fixed with the new MDC-based tabs (currently in `@angular/material-experimental`): [Demo](https://stackblitz.com/edit/nested-mdc-tabs-index?file=src%2Fapp%2Ftab-group-basic-example.html)

**Comment by amysorto** [comment] 2022-11-14 23:44
Confirming this is fixed in the new MDC based tab component coming in v15 soon.

**Closed by amysorto** 2022-11-14 23:44 UTC
Labels: P3, area: material/tabs, Fixed in MDC
