### ISSUE TITLE
Screen reader is announcing entire mat-datepicker component instead focused element upon launch

### ISSUE THREAD

**Issue by kesava885** [angular/components#16315] opened 2019-06-18 13:14 UTC
#### Expected Behavior
Recommendation would be that focus be set to the first control within the mat-datepicker.

#### Actual Behavior

When launching the  mat-datepicker with the screen reader running, the screen reader will announce the entire control after it is opened.  This is confusing to the end user since the announcement of the entire control does not provide the context in a clear manner.

#### Environment

- Screen Reader: JAWS
- Angular: 7
- CDK/Material: 7
- Browser(s): IE 11, Chrome
- Operating System: Windows

**Comment by crisbeto** [comment] 2019-06-18 19:19
We do set focus on the on the active cell on init, but it's up to the screen reader how to announce it. E.g. with NVDA I just get "June 18, 2019, row 4, column 3".

**Comment by kesava885** [comment] 2019-06-18 19:52
> We do set focus on the on the active cell on init, but it's up to the screen reader how to announce it. E.g. with NVDA I just get "June 18, 2019, row 4, column 3".

Its happening on IE 11, I have just tested it.

**Comment by jelbourn** [comment] 2019-06-18 21:20
I can confirm that it does focus the correct cell. It looks like JAWS and VoiceOver read the whole dialog anyway, while NVDA and ChromeVox just read the active cell. 

Closing since we're focusing the right element and we don't have anything else we can do to influence the screen-reader behavior.

**Closed by jelbourn** 2019-06-18 21:20 UTC
