### ISSUE TITLE
Mat Autocomplete not working with ViewEncapsulation set to Native

### ISSUE THREAD

**Issue by tuckerjt07** [angular/components#16599] opened 2019-07-24 15:26 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-qbntx6

Steps to reproduce:
1. Click on the input that says Pick One
2. The autocomplete options box may or may not show. If it does show it will just be a quick flash before it disappears.
3. Shift tab to blur out of the input
4. Tab to focus on the input
5. The autocomplete options will now remain on the screen
 
 
#### Expected Behavior

What behavior were you expecting to see?
I would expect that the behaviors would be the same between a click to focus and a tab to focus on the input element

#### Actual Behavior

What behavior did you actually see?
The autocomplete only works as expected when tab is used to focus. Clicking to focus results in the options box appearing and quickly disappearing. When ViewEncapsulation is set to None the autocomplete behaves as expected.

#### Environment

- Angular: ^8.0.0
- CDK/Material: ^8.0.0
- Browser(s): Only tested in Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Only checked on macOS

**Comment by crisbeto** [comment] 2019-07-24 19:03
Closing as a duplicate of https://github.com/angular/components/issues/15606 which has a pending PR.

**Closed by crisbeto** 2019-07-24 19:03 UTC
