### ISSUE TITLE
MatExpansionPanel cannot be opened when inside animated container and [expanded] binding is used

### ISSUE THREAD

**Issue by pshurygin** [angular/components#16052] opened 2019-05-17 15:15 UTC
#### What is the expected behavior?
Expansion panel is opened by mouse click

#### What is the current behavior?
Expansion panel cannot be opened

#### What are the steps to reproduce?
Here is a reproduction. Try opening first panel.
https://stackblitz.com/edit/angular-13oq4e

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.15
Angular Material 7.3.7
Latest Chrome and Firefox browsers are affected

#### Is there anything else we should know?
Please see stackblitz reproduction. I beleive this is the same issue described here:
https://github.com/angular/components/issues/11765#issuecomment-465404702

**Comment by josephperrott** [comment] 2019-06-04 15:03
Closing as duplicate of #11765

**Closed by josephperrott** 2019-06-04 15:03 UTC
