### ISSUE TITLE
fr([cdk/drag-drop]): [TITLE]

### ISSUE THREAD

**Issue by dota2Pro** [angular/components#19024] opened 2020-04-08 18:43 UTC
#### Feature Description

Right now CDK Drag Drop module only works for a list i.e either Horizontally or Vertically, it would be very helpful to add a option to support Drag and Drop rearrange inside a Grid Structure.

We have a workaround for this, but a feature would be nice

See https://stackoverflow.com/questions/53675661/angular-material-7-use-grid-with-drag-and-drop
https://stackblitz.com/edit/angular-nuiviw?file=src%2Fapp%2Fapp.component.html

#### Use Case

Rearranging mat-cards inside a container

**Comment by crisbeto** [comment] 2020-04-09 08:11
Duplicate of https://github.com/angular/components/issues/13372.

**Closed by crisbeto** 2020-04-09 08:11 UTC
Labels: feature, needs triage
