### ISSUE TITLE
Quick Append/remove Item of virtual scroll cause critical error of Item Service Call

### ISSUE THREAD

**Issue by tranthoai** [angular/components#18559] opened 2020-02-20 10:21 UTC
My Virtual Scroll template:

`<cdk-virtual-scroll-viewport
    itemSize="350"
    class="example-viewport">

  <div
      *cdkVirtualFor="let feedback of allFeedbacks"
      class="example-item">

    <div>
      SOME OTHER CONTENT
    </div>
    
    <div>

      <app-feedback-comment
          class="{{'feedback-' + feedback?.id}}"
          [data]="{
              room: 'feedback-' + feedback?.id, 
              feedback: feedback
            }">
      </app-feedback-comment>

    </div>

  </div>

</cdk-virtual-scroll-viewport>`

My app-feedback-comment component:

import {Component, OnChanges, OnDestroy, OnInit, SimpleChanges} from "@angular/core";

@Component({
  selector: 'app-feedback-comment',
  templateUrl: './feedback-comment.component.html',
  styleUrls: ['./feedback-comment.component.scss']
})
export class FeedbackCommentComponent implements OnInit, OnChanges, OnDestroy {

  public privacyUsers = [];

  constructor(
    public feedbackService: FeedbackService
  ) {
  }

  ngOnChanges(changes: SimpleChanges) {

    // Others code

    if (this.data.feedback != undefined) {

      this.feedbackService.getRespectiveManagers(forUser.id).subscribe(
        (respectiveManagersData: any) => {

          let _privacyUsers = [];
          // Other code
          let respectiveManagers = _.get(respectiveManagersData, 'respectiveManagers', []);

          respectiveManagers.forEach(
            (x: any) => {

              let idx = _privacyUsers.indexOf(x.id);

              if (idx > -1) {
                this.privacyUsers.push(x.name);
              }

            });

          this.privacyUsers.push(this.data.feedback.user.name);

        });

    }

  }

}

My app-feedback-comment template example:

`<div *ngFor="let privacyUser of privacyUsers">
  {{privacyUser?.name}}
</div>`

When we scroll fast, It append/remove Virtual Scroll Item while getRespectiveManagers service call terninated, and it push new data to privacyUsers array error. It cause show privacyUsers data to HTML template wrong completely.

**Comment by mmalerba** [comment] 2020-08-13 22:27
Please update this issue description to include a reproduction in stackblitz (you can use our template to get starte https://stackblitz.com/edit/components-issue) as well as clear steps to reproduce and the actual result you are seeing vs what was expected

**Comment by crisbeto** [comment] 2021-05-06 19:38
Closing since the issue didn't have a reproduction to begin with and it hasn't been updated in a long time.

**Closed by crisbeto** 2021-05-06 19:38 UTC
Labels: area: cdk/scrolling, cannot reproduce, needs clarification
