### ISSUE TITLE
bug(cdk/table): sticky cells not updated when filtering

### ISSUE THREAD

**Issue by mhaertwig** [angular/components#26543] opened 2023-02-01 12:21 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the CDK table together with a filter, the sticky style is not updated correctly.

![image](https://user-images.githubusercontent.com/3184240/216034061-fa057b56-41b5-4d92-86bb-bcb3406f0657.png)

I tried to fix this bug in the CDK, however I wasn't successful so far. Here are my findings:

1. The `CdkTable` calls the [updateStickyColumns()](https://github.com/angular/components/blob/main/src/cdk/table/sticky-styler.ts#L104) method of the `StickyStyler` correctly.
2. The `StickyStyler` adds the task to the `CoalescedStyleReducer` [here](https://github.com/angular/components/blob/main/src/cdk/table/sticky-styler.ts#L134).
3. In the `CoalescedStyleReducer` the last [this._getScheduleObservable()](https://github.com/angular/components/blob/main/src/cdk/table/coalesced-style-scheduler.ts#L75) event is not emitted until I trigger the next change detection cycle, e.g. by clicking on the table. The last state of [this._ngZone.isStable](https://github.com/angular/components/blob/main/src/cdk/table/coalesced-style-scheduler.ts#L97) is `false`.

Let me know if you have any ideas how to solve this.

### Reproduction

Steps to reproduce:
1. Open [Stackblitz](https://stackblitz.com/edit/angular-i94eq2?file=src%2Fapp%2Ftable-filtering-example.html).
2. Type `10` in the filter field.
3. Press backspace, so the filter results in `1` >> Some cells (3,4 and 7) are not sticky.
4. Trigger the next change detection cycle, e.g. by clicking on the table >> Sticky cells are displayed correct again.

### Expected Behavior

The sticky cells are updated when changing the filter value from `10` to `1`.

### Actual Behavior

Some cells (3, 4 and 7) do not have a sticky style.

### Environment

- Angular: 15.1.0
- CDK/Material: 15.1.0
- Browser(s): Chrome Version 109.0.5414.120
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Ubuntu

**Comment by andrewseguin** [comment] 2023-05-07 11:56
Something changed recently where the sticky scheduler is not running correctly - it doesnt seem to perform the latest update

Closing as a duplicate of #25396

**Closed by andrewseguin** 2023-05-07 11:56 UTC
Labels: needs triage
