### ISSUE TITLE
bug(cdk/drag): DOM freeze while dragging

### ISSUE THREAD

**Issue by AvoMMH** [angular/components#24489] opened 2022-02-28 08:46 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version
- [x] I have not used this before

### Description

When dragging an element from one drop-list to another the receiving droplist can not be display: none or height: 0.
When I set one of those properties and reset them with .cdk-drop-list-receiving and .cdk-drop-list-dragging to be visible the dragged element cant be dropped into the target list, because the dom state when i started dragging is used to determine the dropzones. 

### Reproduction

Steps to reproduce:
1. create two connected cdk-drop-lists
2. add a draggable element to the source list
3. add hint for the user that he can drop stuff here (icon, text, etc.)
4. set display: none or height: 0 and visibility: hidden to the target list
5. add css to reset to display: block or visibility:hidden and height: unset on .cdk-drop-list-receiving and .cdk-drop-list-dragging
6. Try dragging the element from the source list to the target list

Note:
- I can't create a StackBlitz since I am in my organisations network
- If you dont modify the display or height value everything works as expected

### Expected Behavior

I expect the target droplist to accept the element within the targets current display state and size while dragging and not with the reduced variant before dragging.

### Actual Behavior

I cant drop the element to the target list since it seems to use the dimensions of the target list before I started dragging

### Environment

- Angular: 13.2.0
- CDK/Material: 13.2.1
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Win10 1909

**Comment by crisbeto** [comment] 2022-02-28 10:09
This is currently working as intended. For performance reasons, we only measure the elements in a few key moments (dragging starts, item enters a new list), otherwise we'd have to do it for each pixel you drag which will cause layout thrashing.

**Comment by AvoMMH** [comment] 2022-02-28 10:57
Okay, but I need to hide the drop area while not dragging (because it is quite huge). Is there a way to do this?

**Comment by crisbeto** [comment] 2022-02-28 12:12
There is no way to do this at the moment, but there are some workarounds in https://github.com/angular/components/issues/14703. I'm closing this issue as a duplicate.

**Closed by crisbeto** 2022-02-28 12:12 UTC
Labels: needs triage
