### ISSUE TITLE
Multi Column MatSort

### ISSUE THREAD

**Issue by samie67** [angular/components#19448] opened 2020-05-26 20:07 UTC
#### What are you trying to do?
I am a junior developer and this is my first time posting a request so please forgive me if any mistakes.
Trying to achieve sorting on multiple columns using matsort

#### What troubleshooting steps have you tried?
I am checking to see if there is any possibility to achieve it
What are you seeing that does not match your expectations? 

#### Reproduction

 I reproduced a table with some sample data where I want to sort on Priority column and keep the results and again sort on Name column and get the results. Please refer to the link.
https://gxnyjaqgeje.angular.stackblitz.io/
Expected behaviour:
I am trying to achieve multi column sorting using matsort which means I should be able to sort on two(multi) columns at the same time. I highly appreciate your help.
  
#### Environment

- Angular: Angular 9
- CDK/Material: 9.2.3/ 9.2.3
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by andrewseguin** [comment] 2020-05-26 20:33
Duplicate of #7226

Unfortunately its not yet supported but something we'd like to add

**Closed by andrewseguin** 2020-05-26 20:33 UTC
Labels: needs triage, troubleshooting
