### ISSUE TITLE
bug(mat-radio-group): Problems with name attribute

### ISSUE THREAD

**Issue by EliseoPlunker** [angular/components#26307] opened 2022-12-22 07:08 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Credits to find bug to [@RedHeadEmile](https://stackoverflow.com/users/7520453/redheademile)

The mat-radio-group create input type="radio" with the same name that the parameter "name" in mat-radio-group
```
    <mat-radio-group name="test" >
      <mat-radio-button [value]="..."></mat-radio-button>
      ...
    </mat-radio-group>
```
This makes that if you have a component like
```
   <mat-radio-group name="test" [(ngModel)]="variable">
      <mat-radio-button [value]="false">False</mat-radio-button>
      <mat-radio-button [value]="true">True</mat-radio-button>
    </mat-radio-group>]
```

You can **not** use two times in a component
```
<fool-component></fool-component>
<fool-component></fool-component>
```

See the [SO discussion](https://stackoverflow.com/questions/74868192/agular-same-component-conflict)

### Reproduction

Steps to reproduce:
1. See the behaviour fool-component in this [stackblitz](https://stackblitz.com/edit/angular-znltyj-ufbmer?file=src%2Fapp%2Ffool.component.ts)
2. When you select one of the radio buttons, deselect the radio buttons of the another component

### Expected Behavior

You can select the radio-buttons independiently

### Actual Behavior

You can **not** select the radio-buttons independiently
Possible solution: change the [_updateRadioButtonNames](https://github.com/angular/components/blob/25d9217fd19cdc404ad5370975afe36fe4a14ce7/src/material/radio/radio.ts#L251) function adding the `nextUniqueId `to the name of the radios

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.3
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by Totati** [comment] 2022-12-23 11:22
I think it's working as intended. Changing _updateRadioButtonNames woud include a breaking change. Radio buttons are scoped globally even in native html. It's the developer's responsibility to define unique names for different radio-groups.

[Your example with native radio buttons produces the same result.](https://stackblitz.com/edit/angular-znltyj-xu2e4y?file=src%2Fapp%2Ffool.component.ts,src%2Fapp%2Fradio-overview-example.html)

**Comment by EliseoPlunker** [comment] 2022-12-23 11:59
Totati, in my opinion, has no sense that the name of the created radio buttons depends if I use the "name" in the mat-group or not. Who matter this names to?

**Comment by Totati** [comment] 2022-12-23 13:20
Then use ReactiveForms so you don't have to provide a name :) TemplateDrivenFroms requires you to name your controls (you even get an error when you don't), so it's your responsibility to name them correctly. MatRadioGroup makes it easier to name your radios as you don't have to name them individually, it takes care of this. Yes they use a generated unique name when you don't provide one, so if you don't have to care about the name (when you use ReactiveForms, or use standalone ngModels), you can ignore it. The same could happen with id-s. If you hardcode an id in a component and you repeat that component, well, you designed your component badly as it would produce invalid HTML. You should not think about the solution (which has been accepted on SO) as a hack, because that's what HTML and TemplateDrivenForms requires you to do.

**Comment by crisbeto** [comment] 2023-05-20 07:41
Closing since this is how native radio buttons work as well. It's up to the consumer to provide an appropriate name or leave the `name` blank which will allow Material to auto-generate one for you.

**Closed by crisbeto** 2023-05-20 07:41 UTC
Labels: needs triage
