### ISSUE TITLE
bug(SCSS): @use

### ISSUE THREAD

**Issue by GlauberF** [angular/components#22977] opened 2021-06-15 00:04 UTC
Steps to reproduce:
1. repository: https://github.com/GlauberF/report-bug-angular-material-v12
 
 
#### Expected Behavior
After updating to the latest version of angular, I got several undefined variable errors, however much I make use of  `@use '~@angular/material' as mat;`

```
./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
9 │         500: mat.$dark-primary-text
  │              ^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/app/app.theme.scss 9:14  @import
  src/styles.scss 20:9         root stylesheet
    at processResult (/var/www/html/pwa_vimbo(copiar)/node_modules/webpack/lib/NormalModule.js:703:19)
    at /var/www/html/pwa_vimbo(copiar)/node_modules/webpack/lib/NormalModule.js:809:5
    at /var/www/html/pwa_vimbo(copiar)/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /var/www/html/pwa_vimbo(copiar)/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/var/www/html/pwa_vimbo(copiar)/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.callback (/var/www/html/pwa_vimbo(copiar)/node_modules/sass-loader/dist/index.js:54:7)
    at Worker.<anonymous> (/var/www/html/pwa_vimbo(copiar)/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:134:25)
    at Worker.emit (events.js:315:20)
    at MessagePort.<anonymous> (internal/worker.js:207:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
```

![Captura de Tela_selecionar área_20210614183132](https://user-images.githubusercontent.com/11314585/121972635-eef4d580-cd51-11eb-93d7-990e6f2a7b1f.png)

#### Environment
<pre><code>
Angular CLI: 12.0.4
Node: 14.16.1
Package Manager: npm 6.14.12
OS: linux x64

Angular: 12.0.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1200.4
@angular-devkit/build-angular     12.0.4
@angular-devkit/build-optimizer   0.1101.4
@angular-devkit/core              12.0.4
@angular-devkit/schematics        12.0.4
@angular/material                  12.0.4
@angular/flex-layout              12.0.0-beta.34
@nguniversal/builders             12.0.2
@nguniversal/express-engine       12.0.2
@schematics/angular               12.0.4
rxjs                              6.6.7
typescript                        4.2.4

</code></pre>

**Comment by crisbeto** [comment] 2021-06-16 16:05
Duplicate of https://github.com/angular/components/issues/22859.

**Closed by crisbeto** 2021-06-16 16:05 UTC
Labels: needs triage

**Comment by GlauberF** [comment] 2021-06-16 18:29
So @crisbeto ,
you commented it on another issue.

> Previously these variables were exposed by accident. We used the `@use` migration as a chance to clean up accidental public APIs like these. You can either copy over the values [from here](https://github.com/angular/components/blob/master/src/material/core/theming/_palette.scss#L29) or access them through one of the theme palettes.

However you can see that in the image I do the @use and access via `mat.`, but still it is undefined.
In this example of the image above, what should I call it so I can use it?

**Comment by crisbeto** [comment] 2021-06-16 18:43
What I meant by the comment is that these variables were exposed by accident in the old API that was using `@import`. They're no longer available with `@use`. If you need to use them, you can copy the over the values from https://github.com/angular/components/blob/master/src/material/core/theming/_palette.scss#L29.
