### ISSUE TITLE
bug(CdkTextareaAutosize): cdkAutosizeMinRows and cdkAutosizeMaxRows settings not working as expected

### ISSUE THREAD

**Issue by ddzingielewski** [angular/components#28786] opened 2024-03-27 16:01 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

8.2

### Description

Hi, Following first example in angular material docs: https://v15.material.angular.io/cdk/text-field/overview where settings are:
`
            cdkAutosizeMinRows="1"
            cdkAutosizeMaxRows="5"
`

I can only provide 3 rows and component stops expanding showing inner scroll after 4 row input. 

### Reproduction

StackBlitz link: https://stackblitz.com/run?file=src%2Fapp%2Ftext-field-autosize-textarea-example.ts
Steps to reproduce:
1. Set 5 rows inside textarea control

### Expected Behavior

I would expect component to expand to 5 rows and show inner scroll after input of 6th row. I found that it worked as expected on some old version of angular: https://stackblitz.com/angular/pbadbpbgyog?file=app%2Ftext-field-autosize-textarea-example.css

### Actual Behavior

Component stops expanding after 3rd row and on 4th shows inner scroll.

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows Pro 10

**Comment by amysorto** [comment] 2024-06-05 14:41
This seems to be a duplicate of #26233. Closing this issue

**Closed by amysorto** 2024-06-05 14:41 UTC
Labels: needs triage
