### ISSUE TITLE
Mat-expansion panel is opened while been animated

### ISSUE THREAD

**Issue by frct1** [angular/components#16534] opened 2019-07-16 13:20 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Add enter animation to mat-accordion
2. https://components-issue-wabdrn.stackblitz.io
 
 
#### Expected Behavior

While user see animation of entering mat-accordion: content of mat-expansion-panel should be hidden = panel should be closed.

#### Actual Behavior

Content of mat-expansion panel is opened in animation. After animation completed it's closing...

#### Environment

- Angular: 8.0.0 (same with 8.1.0)
- CDK/Material: 
- Browser(s): Chrome 75
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by andrewseguin** [comment] 2019-07-17 22:21
Root cause seems to be due to Angular's priority of executing parent animations before children animations, which means the expansion panel waits to set itself up. It makes sense to me to do a better job of initializing the expansion panel outside of animations to avoid this.

**Comment by frct1** [comment] 2019-07-17 22:26
Hello there
Thank you for the answer. I will glad to see it fixed in next updates ;)

**Comment by emmbee7806** [comment] 2020-07-13 18:22
Same issue, having an expansion panel in a mat-dialog. When opening the dialog the expansion opens first and then closes.

**Comment by emmbee7806** [comment] 2020-07-13 18:37
Possible duplicate of [#11765](https://github.com/angular/components/issues/11765)

**Comment by hi-im-branx** [comment] 2020-07-22 23:19
Same here.

**Comment by emmbee7806** [comment] 2020-07-22 23:39
Here’s an easy workaround that solved it for me https://github.com/angular/components/issues/11765#issuecomment-447991348

**Closed** 2024-12-05 12:53 UTC
Labels: P3, area: material/expansion
