### ISSUE TITLE
bug(mat-tooltip): tooltip shows up even if the trigger was left before the show delay

### ISSUE THREAD

**Issue by preda7or** [angular/components#25298] opened 2022-07-18 14:22 UTC
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.13

### Description

When `matTooltipShowDelay` is used and mouse entered and left the trigger element, the tooltip will still briefly show up after the delay time.

### Reproduction

Steps to reproduce:
1. open tooltip example StackBlitz (https://material.angular.io/components/tooltip/examples#tooltip-delay): https://stackblitz.com/run?file=src%2Fapp%2Ftooltip-delay-example.ts
2. enter and leave the `Action` button with your mouse
3. wait till the delay expires
4. see the tooltip blink in and out of existence

### Expected Behavior

If the mouse leaves the trigger before the enter animation starts (before the show delay) then the tooltip will not show at all.

### Actual Behavior

The tooltip will show briefly after the delay even if the mouse entered the trigger and left immediately.

### Environment

- Angular: 14.0.0
- CDK/Material: 14.0.5
- Browser(s): Chrome 103.0.5060.114
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Business Version 21H2 OS build 19044.1826 x64

**Comment by crisbeto** [comment] 2022-07-19 07:09
Duplicate of https://github.com/angular/components/issues/24614.

**Closed by crisbeto** 2022-07-19 07:09 UTC
Labels: needs triage
