### ISSUE TITLE
bug(COMPONENT): cdkDragHandle not work in mat-table td

### ISSUE THREAD

**Issue by xylplm** [angular/components#30111] opened 2024-12-01 10:38 UTC
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

My table rows can be dragged. But I don't want the entire row to trigger dragging. Use cdkDragHandle to specify a drag button on td to achieve row dragging.
But cdkDragHandle did not take effect, and now the entire row can still trigger dragging。

### Reproduction

StackBlitz link: https://stackblitz.com/edit/w368zz?file=src%2Fexample%2Ftable-basic-example.html
Steps to reproduce:
1. 
2.

### Expected Behavior

Only buttons can be dragged, other positions in the row cannot be dragged

### Actual Behavior

Both rows and buttons can trigger dragging

### Environment

- Angular:18/19
- CDK/Material:18/19
- Browser(s):edge
- Operating System (e.g. Windows, macOS, Ubuntu):win11

**Comment by crisbeto** [comment] 2024-12-03 07:19
Duplicate of https://github.com/angular/components/issues/29475.

**Closed by crisbeto** 2024-12-03 07:19 UTC
Labels: needs triage
