### ISSUE TITLE
help(mat-tree-node): Dynamically filling the tree using service cause 1 "selected" object to disappear from screen

### ISSUE THREAD

**Issue by profeciak** [angular/components#20122] opened 2020-07-29 11:20 UTC
#### What are you trying to do?

I want to use mat-tree-node to present selected nodes from main tree, also as trees. I'm getting the values using Subscription like : 
this.chosenProjectsPhasesOrTasksService.getListOfChosenElements().subscribe((value: TreeDataModel[]) => {
            console.log(value)
            this.dataSource.data = [];
            console.log(this.dataSource.data)
            this.dataSource.data = JSON.parse(JSON.stringify(value));
            console.log(this.dataSource.data)
        });
and I can see for example that this.dataSource.data has 4 elements, but on the screen there are only 3

#### What troubleshooting steps have you tried?

After choosing first value I got it on screen - It's ok. But when I choose more values, then the first one disappears from the screen even though it's still in this.dataSource.data as I've checked in console.log

  
#### Environment

- Angular: 7.2.0
- CDK/Material: 7.2.0
- Browser(s): chrome, firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by wagnermaciel** [comment] 2020-07-30 22:25
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment
(this is a canned response)

**Comment by wagnermaciel** [comment] 2020-08-13 22:46
Closing because no clarification was provided.

**Closed by wagnermaciel** 2020-08-13 22:46 UTC
Labels: needs clarification, troubleshooting
