### ISSUE TITLE
Updating data doesnt expand the data tree

### ISSUE THREAD

**Issue by StefaniToto** [angular/components#25836] opened 2022-10-20 09:17 UTC
### What are you trying to do?

Im trying to build a table with nested tree folder inside. 
Table has multiple columns and tree contain nested folders.

### What troubleshooting steps have you tried?

During the adding new data to the datasource data teh model is updated but not reflected ont he tree view and expand is not working anymore. 

### Reproduction

[Steps to reproduce:]
https://stackblitz.com/edit/angular-table-tree-example-k2zqmt?file=app%2Ftable-basic-example.ts&file=app%2Ftable-basic-example.html,app%2Ftable-basic-example.ts

### Environment

- Angular:
- Material Table
- Material tree system

**Comment by Cubelaster** [comment] 2022-10-29 07:14
I'm having the same issue. 
Seems like entire tree is full of bugs. 
Generally the state of the component is not handled correctly.

**Comment by StefaniToto** [comment] 2022-10-31 07:57
Check out here. 
Have already managed to give some solution:

https://stackoverflow.com/questions/74137439/updating-data-doesnt-expand-the-data-tree-inside-material-table/74164923?noredirect=1#comment130991989_74164923

**Comment by Cubelaster** [comment] 2022-10-31 10:31
Check this one, it seems to pinpoint the problem correctly.
[Root issue](https://github.com/angular/components/issues/11381)

**Comment by amysorto** [comment] 2023-05-12 18:09
Duplicate of #11381

**Closed by amysorto** 2023-05-12 18:09 UTC
Labels: troubleshooting, needs triage
