### ISSUE TITLE
bug(Menu): Up and down arrow keys do not cycle through all options

### ISSUE THREAD

**Issue by davimiku** [angular/components#26662] opened 2023-02-20 20:16 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

[StackBlitz reproduction](https://stackblitz.com/edit/angular-zsnfkb-zklan5?file=src/app/app.component.ts)

When using keyboard navigation (up and down arrows) on the options on a Material Menu, in the reproduction example above, the arrow keys do not reach all items.

GIF:

Pressing the Down or Up arrow keys never reaches the "Feature A" item, it just cycles back to the top.

https://user-images.githubusercontent.com/36610621/220189514-bbcac50f-2ae1-4582-8549-ece2a4649fdd.mp4

HTML of the Material Menu and menu items. The 3rd button can't be navigated to using the keyboard up and down arrows.

![image](https://user-images.githubusercontent.com/36610621/220189760-434b6718-ba56-4fa0-bf4f-9a8dbb714cd7.png)

In this case, the issue happens when Menu Items (`mat-menu-item`) are added to the Menu (`mat-menu`) with a `<ng-content select="...">` directive .

The use case (minimally demonstrated in the example) is a common menu shared across multiple features, and each feature will add their own option to the menu.

### Reproduction

[StackBlitz reproduction](https://stackblitz.com/edit/angular-zsnfkb-zklan5?file=src/app/app.component.ts)

Steps to reproduce:
1. Open the StackBlitz above
2. Navigate to one of the Material Menu trigger buttons using the keyboard
3. Open the menu using the keyboard (Enter or Space)
4. Use Up and Down arrows to navigate through the menu options
5. Note that the last menu option cannot be selected with the keyboard

### Expected Behavior

Up and down arrow keys move through the menu items, as documented in [Menu keyboard interaction](https://material.angular.io/components/menu/overview#keyboard-interaction).

### Actual Behavior

Up and down arrow keys do not navigate through all the menu options

### Environment

- Angular: 15.1.2
- CDK/Material: 15.1.2
- Browser(s): Edge, Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2023-02-25 07:07
Duplicate of https://github.com/angular/components/issues/26243.

**Closed by crisbeto** 2023-02-25 07:07 UTC
Labels: needs triage

**Comment by davimiku** [comment] 2023-02-28 23:50
Thanks @crisbeto !

Is this a documentation issue then? The [Angular Material Menu documentation](https://material.angular.io/components/menu/overview#keyboard-interaction) implies that this works unconditionally, it doesn't mention that the keyboard accessibility sometimes works and sometimes not. This is important for us for accessibility compliance, the menu options are not reachable by keyboard/screen reader.

I'm happy to submit a PR to add this information to the documentation page!

**Comment by crisbeto** [comment] 2023-03-02 13:47
I think the problem with calling this out in the docs is that it isn't really something specific to Material, it's just how content projection works on the framework level. There are several more Material components that depend on `ContentChildren` queries that would have to be called out.

**Comment by davimiku** [comment] 2023-03-03 13:48
Thanks! 

> There are several more Material components that depend on ContentChildren queries that would have to be called out.

For me, the fact that it is widespread is **more** reason to document it, not less. Or are you saying it's better to not document in @angular/material but instead in @angular/angular, like on this page? https://angular.io/guide/content-projection

**Comment by crisbeto** [comment] 2023-03-03 13:58
Yeah I think that this is more a matter of documenting how content projection works rather than how Material works.
