### ISSUE TITLE
bug(MatCheckboxHarness): isChecked() returns false right after check()

### ISSUE THREAD

**Issue by camueller** [angular/components#19063] opened 2020-04-13 10:13 UTC
#### Reproduction
`MatCheckboxHarness.isChecked()` does not return true right after `check()` has been called on the harness:
```
const checkbox = await loader.getHarness(MatCheckboxHarness.with({selector: [formControlName="myFormControl"]})); 
await checkbox.check();
expect(await checkbox.isChecked()).toBeTruthy();
```
If the checkbox gets checked some other controls will be displayed. There is another test testing successfully for these controls after the call to `MatCheckboxHarness.check()`. Therefore I'm sure that `check()` is working okay but `isChecked()` does not worked as intended.

#### Expected Behavior
`MatCheckboxHarness.isChecked()` returns true right after check() has been called

#### Actual Behavior
`MatCheckboxHarness.isChecked()` returns false right after check() has been called

#### Environment

- Angular/CDK/Material:
$ npm list --depth 0
smartapplianceenabler@0.0.0 /data/IdeaProjects/SmartApplianceEnabler/src/main/angular
├── @angular-devkit/build-angular@0.901.1
├── @angular/animations@9.1.1
├── @angular/cdk@9.2.0
├── @angular/cli@9.1.1
├── @angular/common@9.1.1
├── @angular/compiler@9.1.1
├── @angular/compiler-cli@9.1.1
├── @angular/core@9.1.1
├── @angular/flex-layout@9.0.0-beta.29
├── @angular/forms@9.1.1
├── @angular/language-service@9.1.1
├── @angular/material@9.2.0
├── @angular/platform-browser@9.1.1
├── @angular/platform-browser-dynamic@9.1.1
├── @angular/router@9.1.1
├── @ngx-translate/core@10.0.2
├── @ngx-translate/http-loader@3.0.1
├── @types/jest@24.9.1
├── @types/node@12.12.35
├── clockpicker@0.0.7
├── include-media@1.4.9
├── UNMET PEER DEPENDENCY jest@24.9.0
├── jest-preset-angular@8.1.3
├── jquery@3.5.0
├── moment@2.24.0
├── rxjs@6.5.5
├── ts-node@7.0.1
├── tslib@1.11.1
├── tslint@5.11.0
├── typescript@3.8.3
└── zone.js@0.10.3

- Operating System (e.g. Windows, macOS, Ubuntu):
Ubuntu 18.04

**Comment by crisbeto** [comment] 2020-04-13 10:16
That's odd since we have a [test which is identical to yours](https://github.com/angular/components/blob/master/src/material/checkbox/testing/shared.spec.ts#L138). What does your test component look like?

**Comment by camueller** [comment] 2020-04-13 10:26
The test in line 173 fails:
https://github.com/camueller/SmartApplianceEnabler/blob/material/src/main/angular/src/app/control/http/control-http.component.spec.ts

**Comment by camueller** [comment] 2020-04-14 15:48
I had a look at your test case but did not find difference I could point to.
Therefore I created another test using a rather simple component (no parent from group like in the previous test case), but results are the same:

https://github.com/camueller/SmartApplianceEnabler/blob/a4cff69e027cecfe66735e80183c6f6a6970d1b7/src/main/angular/src/app/appliance/appliance.component.spec.ts#L160

I have a checkbox that is not checked initially. It is checked in line 159. If I verify in line 160 that it is checked, it fails. In line 161 I successfully verify the impact of the checked checkbox: input field "minOnTime" is no longer disabled.

Again, checking the checkbox works, but querying the checkbox state does no work.
Your API is well designed and does not leave much room for wrong usage. However, there are not many code snippets to be found using MatCheckboxHarness. Perhaps it only works in your test but not elsewhere.

**Comment by devversion** [comment] 2020-05-25 17:38
@camueller I'd be happy to look at your issue. Would you be able to share a small reproduction that demonstrates the problem? [here is an example stackblitz that could be used](https://stackblitz.com/edit/components-issue-igqsix?file=src/app/example-test.spec.ts)

**Comment by devversion** [comment] 2020-05-25 17:52
@camueller I looked more into it, but wasn't able to reproduce this in a StackBlitz either. You are saying that the checkbox is clearly checked. The harness determines the checked state by looking at the native `<input>` element in the checkbox.

Would you be able to check if that input has the `checked` attribute set? Also it might be good to know against which browser you ran these tests?

**Comment by camueller** [comment] 2020-05-25 17:56
Don't you think the unit test https://github.com/camueller/SmartApplianceEnabler/blob/a4cff69e027cecfe66735e80183c6f6a6970d1b7/src/main/angular/src/app/appliance/appliance.component.spec.ts#L160
is simple enough?
You only have to
- clone this revision of the repo
- run `npm i`
- enable line 160
- run the test:
```
$ node_modules/jest/bin/jest.js --verbose "--testNamePattern=^ApplianceComponent create a new appliance fields minOnTime is enabled if interruptionsAllowed$" --runTestsByPath /data/IdeaProjects/SmartApplianceEnabler/src/main/angular/src/app/appliance/appliance.component.spec.ts
```

**Comment by devversion** [comment] 2020-05-25 18:18
@camueller It looks like this is a `jsdom` issue. JSDOM does not properly refresh the `checked` content attribute. Here is an example snippet that highlighted the issue:

```ts
const {JSDOM}= require("jsdom");

const dom = new JSDOM(`<!DOCTYPE html><input type="checkbox">`);
const checkbox = dom.window.document.querySelector("input");

console.log(checkbox.getAttribute("checked")); // false
console.log(checkbox.checked); // false

checkbox.click();

console.log(checkbox.getAttribute("checked")); // null
console.log(checkbox.checked); // true
```

We don't see this issue since we test against real browsers.

**Comment by camueller** [comment] 2020-05-25 18:22
Great - looks like you found the source of the problem :-)

**Comment by devversion** [comment] 2020-05-25 18:23
We can make this more robust by relying on the `checked` property from within the harness, but it might be good to report that upstream in `jsdom`. I'll mark this as P4.

**Comment by camueller** [comment] 2020-05-26 14:43
After your analysis I checked `jsdom` issues and found related fixes. I realized, that `jsdom` is used in version 11.12.0 by `jest` 24.9.0. `jsdom` 11.12.0 is about 2 years old. After upgrading `jest` to 26.0.1 it uses `jsdom` 16.2.2 and the issue with refresh issue of the `checked` property is gone. The test runs fine now! You may close this issue.

**Comment by devversion** [comment] 2020-05-26 15:59
Yeah. Closing this. Thanks for reporting back! It looks like https://github.com/jsdom/jsdom/issues/2367 was the root cause.

**Closed by devversion** 2020-05-26 15:59 UTC
Labels: P4, area: material/checkbox
