### ISSUE TITLE
docs-bug(Github README): Update "What we're working on" section

### ISSUE THREAD

**Issue by anisabboud** [angular/components#26069] opened 2022-11-23 15:18 UTC
### Documentation Feedback

The project README ["What we're working on now (Q4 2021)"](https://github.com/angular/components#what-were-working-on-now-q4-2021) section hasn't been updated in the past year.

I think it's important to keep the main [README](https://github.com/angular/components) up-to-date, to avoid misleading new developers who might think the project isn't updated even though it's very active with major recent changes.

Maybe add links to recent posts/videos:
- https://material.angular.io/guide/mdc-migration Migrating to MDC-based Angular Material Components
- https://youtu.be/XlPtyPb3Hmw What's new in Angular Material and the CDK in Angular v15
- https://youtu.be/d6FJg2MW-lI Building accessible Angular apps

### Affected documentation page

https://github.com/angular/components

**Comment by crisbeto** [comment] 2022-11-25 12:47
Duplicate of https://github.com/angular/components/issues/25652.

**Closed by crisbeto** 2022-11-25 12:47 UTC
Labels: docs, needs triage
