### ISSUE TITLE
feat(Angular Material): Add Support for type="file" for MatInput or Create Mat File Chooser component

### ISSUE THREAD

**Issue by ekow-mensah** [angular/components#25231] opened 2022-07-06 02:59 UTC
### Feature Description

I would like to request for adding support for type="file" for MatInput. So currently Angular material does not have a file chooser meaning I have to use an external library which is not great. I tried using 

<input matInput placeholder="Select profile picture" type="file"> 

and an error message was displayed showing "Input type "file" isn't supported by matInput."

Will it be possible to add support for type file or create a file chooser component?

### Use Case

A typical use case is where I want to upload files. Currently there's no way to do this using angular material because Angular material does not have a file chooser component. So we could.

1. Add support for type="file"
2. You could create a <mat-file-chooser> component which will support file uploads

**Comment by hhsissi** [comment] 2022-07-26 23:58
Like a lot of people, still waiting for this one for some years now...

**Comment by crisbeto** [comment] 2022-08-11 09:57
Duplicate of https://github.com/angular/components/issues/24044.

**Closed by crisbeto** 2022-08-11 09:57 UTC
Labels: feature, needs triage
