### ISSUE TITLE
data table paginator error 

### ISSUE THREAD

**Issue by alexfung888** [angular/components#13053] opened 2018-09-09 14:27 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
When list is changed, it is displayed correctly and paginator updated.

#### What is the current behavior?
I have seen two problems, but have only demo code for one of them.
Both involves first paging to page 2 (or later), and switch data to a shorter list.
Start with a list of say 18 entries. Set page size to 10. Move to page 2 to see entries 11-18/18.
Then switch to a small list. Say 5 entries.
1) The 5 new items are shown, but they are called 11-18/18 by the paginator. This can be seen in the demo.
2) No items are visible (!), but the paginator correctly says 1-5/5. This is when happens in my own application (which I cannot yet build a sample code to demonstrate. 

In either case, if you change the page size (10 -> 20), the listed items and the paginator numbers will become correct.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
use this one:
https://stackblitz.com/edit/angular-makxax
it is a fork from the material data table demo.

It shows 18 entries with page size 10. 
Switch to page 2 to see 11-18/18
click the "go" button. It changes the source to a small list of 6 entries.
paginator will read 11-18/18 (so it doesn't know things are changed),
but the table rows are shown correctly.

#### What is the use-case or motivation for changing an existing behavior?
i switch the source list to different things depending on several other controls on the page.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
core@6.1.7
material@6.4.7
TS@2.9.2 (that is what I'm using, I don't know what stackblitz is using.

#### Is there anything else we should know?
I can live with problem 1 (the one demonstrated), but problem 2 is really annoying.

**Comment by julianobrasil** [comment] 2018-09-09 19:03
@alexfung888, by running your demo, I couldn't reproduce the first issue:

![record_2018_09_09_16_01_45_445](https://user-images.githubusercontent.com/25405143/45267780-d2f9d200-b449-11e8-8129-df0fe2d2dc85.gif)

**Comment by manklu** [comment] 2018-09-09 21:12
> The 5 new items are shown, but they are called 11-18/18 by the paginator.

You should attach the paginator to the data source
```javascript
public go() {
  this.dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA.slice(5,11));
  this.dataSource.paginator = this.paginator;
}

public reset() {
  this.dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA.slice(0,18));
  this.dataSource.paginator = this.paginator;
}
```
The other problem is that the paginator doesn't automatically adjust itself if the current page is greater than the number of pages. You must do that manually.

**Comment by alexfung888** [comment] 2018-09-10 07:37
@manklu
1) I need to reassign the paginator every time I assign a new list, even though it is the same value (the same element)?
2) that means I have to monitor the paginator events myself? I think the component should do this itself making sure at least the paginator output (item number, total) is consistent with the rows displayed.

**Comment by alexfung888** [comment] 2018-09-10 07:46
after adding`
    this.dataSource.paginator = this.paginator;
`
as suggested, I successfully demonstrated my the second of my original problems. The list is empty although the paginator says 'item 1-6 of 6'

Demo:
https://stackblitz.com/edit/angular-makxax-5ix6tp
same as before: go to page 2 (11-18), click go.

**Comment by julianobrasil** [comment] 2018-09-10 09:37
> I need to reassign the paginator every time I assign a new list, even though it is the same value (the same element)?

Yeah... as it is attached to the `datasource` which was changed in you demo, it makes sense having to assign it to the new one.... 

To change this behavior in a consistent way I think the role of the datasource within `MatTable` would have to be redesigned.

**Comment by alexfung888** [comment] 2018-09-10 10:26
Actually I find it strange that I need to give it a list. I expected it to accept an observable.

**Comment by manklu** [comment] 2018-09-10 16:30
@alexfung888

> need to reassign the paginator every time I assign a new list, even though it is the same value (the same element)?

No, you could simply assign new values to the datasource.
```javascript
public go() {
  this.dataSource.data = ELEMENT_DATA.slice(5,11);
}
public reset() {
  this.dataSource.data = ELEMENT_DATA.slice(0,18);
}
```

> that means I have to monitor the paginator events myself? I think the component should do this itself making sure at least the paginator output (item number, total) is consistent with the rows displayed.

No, you only need to adjust the current page if the new number of pages is smaller.

**Comment by alexfung888** [comment] 2019-01-29 09:22
It is strange that this error persists in 7.3.0, which should fix this when closing 12586

**Comment by andrewseguin** [comment] 2020-05-28 17:59
If you change the data in the data source, it does not know what page you intend it to be on. This is something you should control through a binding to the paginator. For example, perhaps the new data is entirely new and should go to page 1, or perhaps data has been removed and it should go to the previous page. Since the answer is not clear, we leave it to the user to set

**Closed by andrewseguin** 2020-05-28 17:59 UTC
Labels: needs triage
