### ISSUE TITLE
a11y - dialog closes silently when opened from a menu component

### ISSUE THREAD

**Issue by petematt** [angular/components#9323] opened 2018-01-10 16:57 UTC
#### Bug, feature request, or proposal:
Bug verified on chromevox next and voiceover.

#### What is the expected behavior?
Given a page with a button.  The button opens a menu component.  A button in the menu component opens a dialog.

When a dialog closes, the screen reader should read "exited dialog" (or similar) and return focus at the last focusable element used.

#### What is the current behavior?
Given a page with a button.  The button opens a menu component.  A button in the menu component opens a dialog.

When the dialog closes, the screen reader reads nothing.  If the user hits tab, they navigate to the next tabindex after the button that spawns the menu.

Note that shift tab after closing the dialog sets focus to the expected location, calls out "exited dialog", and reads the label of the button.

#### What are the steps to reproduce?
See details in plnkr link: http://plnkr.co/edit/76CdtijrwVxeEnBhc9Z2

A workaround is included, but it becomes rather cumbersome when there's a menu for each element in a repeated field.

#### What is the use-case or motivation for changing an existing behavior?
Users who depend on screen readers can easily lose context of where they are when closing dialogs, especially if esc is pressed because there is no notification that the dialog is gone and no notification that the focus changed.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.0.4-303e004

**Comment by jelbourn** [comment] 2018-01-11 22:58
I'm guessing that the element that triggered the dialog opening (menu-item) no longer exists at the point the dialog close, so it doesn't know where to return the focus.

**Comment by petematt** [comment] 2018-01-12 00:23
Thats what I was assuming.  When the mat-menu gets created, it inserts some tab indexes and then when a menu-item is selected those indices go away.  This explains why tab moves forward to the next element after whatever created the mat-menu and shift+tab moves backward to whatever element created the menu.

**Comment by jelbourn** [comment] 2020-11-25 00:01
Duplicate of #17962

**Closed by jelbourn** 2020-11-25 00:01 UTC
Labels: P3, a11y, area: material/dialog, area: material/menu
