### ISSUE TITLE
bug(MatSelectionList): Falsy Multiple Attribute Omits Checkboxes 

### ISSUE THREAD

**Issue by kristian-favorlogic** [angular/components#18847] opened 2020-03-17 09:27 UTC
#### Reproduction

StackBlitz snippet : https://stackblitz.com/edit/angular-r13hpx?file=src%2Fapp%2Flist-selection-example.html

Steps to reproduce:
1. create mat-selection-list;
2. bind multiple attribute (input) to falsy value.

#### Expected Behavior

Displays checkable list of options with unchecked checkboxes out of which only one option is checkable.

#### Actual Behavior

Checkboxes are not being rendered due to ngIf wrapper reflecting the multiple attribute value.

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  macOS

**Comment by kseamon** [comment] 2020-03-17 12:18
Working as intended

**Comment by kristian-favorlogic** [comment] 2020-03-17 12:26
@kseamon Checkboxes should not be displayed for (?):

`
<mat-selection [multiple]="false">
...
`
That sounds as a pretty bad design if this was done on purpose. Can you please pinpont feature description when such behaviour is described?

> Working as intended
> […](#)
> On Mar 17, 2020, at 5:28 AM, kristian-favorlogic ***@***.***> wrote: ﻿ Reproduction StackBlitz snippet : https://stackblitz.com/edit/angular-r13hpx?file=src%2Fapp%2Flist-selection-example.html Steps to reproduce: create mat-selection-list; bind multiple attribute (input) to falsy value. Expected Behavior Displays checkable list of options with unchecked checkboxes out of which only one option is checkable. Actual Behavior Checkboxes are not being rendered due to ngIf wrapper reflecting the multiple attribute value. Environment Angular: CDK/Material: Browser(s): Chrome Operating System (e.g. Windows, macOS, Ubuntu): macOS — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kseamon** [comment] 2020-03-17 15:30
The design is meant to mimic the contents of mat-select, which shows
checkboxes for multiple mode and highlight with no checkbox for single
selection, per the Material spec.

Feel free to phrase this as a feature request for an option to show
indicators in addition to the highlight (but for single selection, that
should be radio buttons or perhaps just a check mark on the currently
selected item, not checkboxes).

Note that I'm not part of the core Components team but I did contribute the
[multiple]=false feature as it exists now. It will be up to the component
owners whether they want to add this feature or not.

**Comment by kristian-favorlogic** [comment] 2020-03-17 16:19
Oh, OK, now I get your point. Thanks for claryfying! Hm. Should be better documented then I guess. So this is personal choice thing after all. I agreee that radios group is more consistant with Material Design principles. I am not a big fan of Material Design though. Angular's only importance is for enteprise solutions and these clients (or their UI designers) just ask developers to provide anything regardless Google's view on UI. Sure, we can achive that with custom solution, but then angular as ecosystem is loosing on its promised "easy prototyping and fast delivery". I would also argue that modality introduced by !!multiple vs. !multiple is not predicable and practical. I do not see the benefit of !multiple. We have a list, we have a multiselect list, we have group of radios ... fair enough ... but to opt in for a multiselect list that appears as an ordinary list or grid and requires more hacking to make it user friendly so it behaves like single select option list ... it all does not really sounds like an added value to me. Phu ... Anyway. Cheers, enjoy, peace.

**Comment by crisbeto** [comment] 2020-04-12 09:40
Seems like this has been resolved. Closing.

**Closed by crisbeto** 2020-04-12 09:40 UTC
Labels: needs triage
