### ISSUE TITLE
bug(Material forms): No directive found with exportAs 'matMenu' in angular 16.0.3

### ISSUE THREAD

**Issue by cristal2431** [angular/components#27222] opened 2023-06-02 08:51 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

I have below code which works find in angular version 13, however in latest version I am getting the error mentioned here..

```
<mat-menu #failedDiscussion="matMenu">
</mat-menu>
```

### Reproduction

<mat-menu #failedDiscussion="matMenu">
</mat-menu>

### Expected Behavior

No error

### Actual Behavior

bug(Material forms): No directive found with exportAs 'matMenu' in angular 16.0.3

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by amysorto** [comment] 2023-06-02 17:18
I am closing this bug since there is [no provided reproduction](https://github.com/angular/components/blob/main/CONTRIBUTING.md#-found-an-issue).

Although, based on that error there is probably something configured incorrectly in your app module.

**Closed by amysorto** 2023-06-02 17:18 UTC
Labels: needs triage
