### ISSUE TITLE
Material tooltip has warning after upgrade angular 11 to angular 12

### ISSUE THREAD

**Issue by suaha** [angular/components#23009] opened 2021-06-18 06:38 UTC
#### Reproduction

Steps to reproduce:
1.  Upgrade app from angular 11 to angular 12
2.  Use material tooltip
 
 
#### Expected Behavior

What behavior were you expecting to see?
No warning was thrown out

#### Actual Behavior

What behavior did you actually see?
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($handset-target-height - $handset-font-size, 2)
More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
13 │     ($handset-target-height - $handset-font-size) / 2;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\@angular\material\tooltip\_tooltip-theme.scss 13:5           @use
    node_modules\@angular\material\core\typography\_all-typography.scss 32:1  @use
    node_modules\@angular\material\core\_core.scss 8:1                        @forward
    node_modules\@angular\material\core\_core-legacy-index.scss 1:1           @forward
    node_modules\@angular\material\_theming.scss 9:1                          @import
    projects\portal\src\app\themes\_mf-palette.scss 1:9                       @import
    projects\portal\src\app\themes\override.scss 3:9                          root stylesheet

#### Environment

- Angular: 12.0.4
- CDK/Material: 12.0.4
- Browser(s): Compile time error
- Operating System (e.g. Windows, macOS, Ubuntu): windows 10

**Comment by crisbeto** [comment] 2021-06-18 10:19
Duplicate of https://github.com/angular/components/issues/22936.

**Closed by crisbeto** 2021-06-18 10:19 UTC
Labels: needs triage
