### ISSUE TITLE
MdTextareaAutosize: value not rendered with display:none style at initialization of component

### ISSUE THREAD

**Issue by mitch-berg** [angular/components#3346] opened 2017-03-01 01:53 UTC
#### Bug, feature request, or proposal:

Bug:  When the resizing functionality is used on a textarea within an element whose style contains 'display:none' at initialization the value of the textarea is not rendered to the user.  When a user enters the field and begins to provide input the existing data value is then rendered in full.

#### What is the expected behavior?

Pre-populated data values are displayed to the user when the component becomes visible even if the wrapping container is set to 'display:none' at initialization.

#### What is the current behavior?

When the container is toggled visible to the user the data value is not displayed.  The height of the component appears to be set to 0px by MdTextareaAutosize.  Once a user begins to enter more data it triggers another resize and the field populates with the data and resizes.

#### What are the steps to reproduce?

Plunker template: https://plnkr.co/edit/d6s5aOGvS1ZGLNQR7hSJ?p=preview

This example has two wrapper 'div' elements whose display property is manipulated by a button.  One is set to 'display:none' at load and demonstrates the problem of data not being visible when you toggle the 'div' that contains the textarea to be visible. 

The second 'div' just demonstrates that the data is present on load as expected when the wrapping 'div' does not have 'display:none' set. 

#### What is the use-case or motivation for changing an existing behavior?

Support pre-populated data in components which require resize on load but may not be visible to users at initialization.

#### Is there anything else we should know?

Material 1 did some state checking and had a watcher out there that resized when the component became visible based on criteria. 

https://github.com/angular/material/blob/v1.1.1/src/components/input/input.js#L604

**Comment by rscottfree** [comment] 2017-03-06 21:00
Unsurprisingly, this also affects MdTextareaAutosize text areas inside of mdTabs.

While not ideal, a quick fix to overwrite the `height: 0` could be:
```
@ViewChild(MdTextareaAutosize, {read: ViewContainerRef})
myTextArea: ViewContainerRef;

ngAfterViewInit() {
    this.myTextArea.element.nativeElement.style.height = 'auto';
}
```

**Comment by programmersharp** [comment] 2017-04-27 13:30
I tried this solution but the problem is that when the initial value is multi line, then the default scroll bars appear for textarea.

**Comment by gedclack** [comment] 2017-06-05 06:35
`+1` :+1: 
This problem occurs especially when `mdTextareaAutosize` is present.

**Comment by jsitu** [comment] 2017-07-18 18:25
@programmersharp I had the same issue regarding displaying the initial value which is multi-line, did you solve this issue?

**Comment by programmersharp** [comment] 2017-07-19 21:41
@jsitu no, I didn't

**Comment by jsitu** [comment] 2017-07-19 23:20
@programmersharp, I found a workaround for the issue:
`this.yourTextArea.nativeElement.style.height = `${this.yourTextArea.nativeElement.scrollHeight}px`;`

I have it declared within the `ngOnInit` lifecycle hook. Kind of hacky but it does the job.

**Comment by amcdnl** [comment] 2017-08-23 23:48
One suggestion might be using `*ngIf` rather than `display: none`.

**Comment by jelbourn** [comment] 2020-04-28 17:30
Closing this since I don't think there's a viable way for the directive to know about visibility changes like this.

**Closed by jelbourn** 2020-04-28 17:30 UTC
Labels: feature
