### ISSUE TITLE
MatSnackBar to show in a specified container

### ISSUE THREAD

**Issue by jagomf** [angular/components#14351] opened 2018-12-02 15:59 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
SnackBar should be shown in a specified container / viewContainerRef

#### What is the current behavior?
SnackBar is always shown in the bottom of page. That can cause accessibility violations like covering a navigation bottom bar.

#### What are the steps to reproduce?
Stackblitz 1: https://stackblitz.com/edit/angular-hoeafv
Stackblitz 2 (as provided in #11038): https://stackblitz.com/edit/angular-material2-issue-1jgbvq

#### What is the use-case or motivation for changing an existing behavior?
Currently a SnackBar popping up would cover a bottom navigation bar. Being able to specify the container / viewContainerRef would allow to specify the main container, thus avoiding the bottom navigation bar.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?
Misleading info in https://material.angular.io/components/snack-bar/api#MatSnackBarConfig

**Comment by thw0rted** [comment] 2018-12-21 15:20
@josephperrott technically, not allowing the snackbar to appear relative to main content (above a hypothetical bottom toolbar) is a violation of the [spec placement guidelines](https://material.io/design/components/snackbars.html#placement), so shouldn't this be tagged as spec compliance?

As an aside, I feel like the spec used to provide for top-oriented snackbars and now it doesn't.  Was that a change with the last major Material revision?

**Comment by totszwai** [comment] 2019-07-02 14:03
This is more of a critical bug than a feature request... According to the doc, we are supposed to be able to pass a viewContainerRef to it (see: https://material.angular.io/components/snack-bar/api#MatSnackBarConfig). However it doesn't work right now, since Overlay simply hardcoded the positionStrategy to global, in addition, during the creation of the OverlayComponent it doesn't really use the `ViewContainerRef` nor does it pass copy the SnackBarConfig's `ViewContainerRef` over to the `OverlayConfig`.

**Comment by mtaran-google** [comment] 2020-01-22 22:34
@jelbourn ping on the status of this? should it be deduped with #7764? is there a known desirable solution/way forward that's just waiting for someone (like me if need be) to send a PR, or is there more discussion necessary as to the right approach/api?

**Comment by jelbourn** [comment] 2020-01-22 23:17
Duplicate of #7764

Closing this one as a duplicate since the other issue has more votes. That said, we don't have any plans to actively work on this since AFAIK the Material Design spec prescribes exclusively global snackbars. Happy to discuss use cases on the referenced issue, though (or in person if you _happen_ to work in the same building :sunglasses:).

**Closed by jelbourn** 2020-01-22 23:17 UTC
Labels: P5, feature
