### ISSUE TITLE
docs-bug(TYPOGRAPHY): Docs should use the 2018 typography config format

### ISSUE THREAD

**Issue by Maximaximum** [angular/components#22377] opened 2021-03-31 13:29 UTC
#### Documentation Feedback

Currently the docs mention typography levels defined by the outdated 2014 Material Design spec. However, the Angular Material scss API seems to support both formats (2014 and 2018). While the 2014 format might still be useful for ongoing legacy projects (and it would be useful to mention this option in the docs), the 2018 format should be the primary format in the docs (even though internally Angular Material might still convert the 2018 configs into 2014 format). The users creating new projects shouldn't be forced to use the outdated format, especially given that the new format is supported anyway, just the docs need to be updated.

**Affected documentation page:** https://material.angular.io/guide/typography#what-is-typography

**Comment by jelbourn** [comment] 2021-04-02 19:12
Duplicate of #12974

**Closed by jelbourn** 2021-04-02 19:12 UTC
Labels: docs, needs triage
