### ISSUE TITLE
feat(select/testing): Implement harness support for native select

### ISSUE THREAD

**Issue by mmalerba** [angular/components#20514] opened 2020-09-08 19:42 UTC
Currently we don't have a harness for the native select, we should design a solution for this. It's not entirely clear which harness should be responsible. Some options:
1. `MatSelectHarness` - Seems to be the intuitive place users would think to look, though it may not be feasible to support the full API of `MatSelectHarness` when working with a native select
1. `MatInputHarness` -  Not intuitive for users, but `MatInput` is actually the component that deals with the native select
1. `MatNativeSelectHarness` - Could just make an entirely new harness
1. Don't have a harness for it, but have a better way for the user to get back to working with native elements when necessary (e.g. such as when working with a native select)

**Comment by crisbeto** [comment] 2020-09-08 20:36
Duplicate of https://github.com/angular/components/issues/20005.

**Closed by crisbeto** 2020-09-08 20:36 UTC
Labels: P2, area: material/select, area: material/testing, feature
