### ISSUE TITLE
MatMenu html validity and accessibility consequences

### ISSUE THREAD

**Issue by sakhram** [angular/components#16451] opened 2019-07-04 13:32 UTC
#### Reproduction

Steps to reproduce:
1.  navigate to https://material.angular.io/components/menu/overview
2. inspect the basic menu example code (menu-overview-example)
 
#### Expected Behavior

The html code should be valid: no "div" tag inside a "button" tag

#### Actual Behavior

There are two "div" tags inside the "button" tag, which breaks W3C validator :
 Error: Element div not allowed as child of element button in this context.

It also breaks accessibility criterias as html code is supposed to be correct

#### Environment

https://material.angular.io/components/menu/overview website

**Comment by jerome-nelson** [comment] 2019-07-04 15:05
Thanks for the submit, this issue was addressed in 
https://github.com/angular/components/issues/16350

And has a PR to address it :-)

**Comment by crisbeto** [comment] 2019-07-04 15:30
Closing as a duplicate of https://github.com/angular/components/issues/16350.

**Closed by crisbeto** 2019-07-04 15:30 UTC
