### ISSUE TITLE
Make MatSelectionList configurable for Multiselect = ON/OFF

### ISSUE THREAD

**Issue by gatsbys** [angular/components#17236] opened 2019-09-30 13:27 UTC
#### Feature Description

Would be great if we can set on MatSelectionList the multiselect status like : 

` <mat-selection-list #myList [multiselect]="true">
`
#### Use Case

If we wan to to create a list that only allow a single selected item.

**Comment by crisbeto** [comment] 2019-09-30 18:55
Closing as a duplicate of https://github.com/angular/components/issues/16097.

**Closed by crisbeto** 2019-09-30 18:55 UTC
Labels: feature
