### ISSUE TITLE
bug(mat-chip): overflow of container element

### ISSUE THREAD

**Issue by ftaffelt** [angular/components#28947] opened 2024-04-24 07:37 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Mat-Chips overflow it's containing block:
![image](https://github.com/angular/components/assets/25500398/adcf4a11-b93f-4883-853b-337ff99fdf39)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/qw8gjm?file=src%2Fexample%2Fchips-overview-example.html

### Expected Behavior

The accent fish chip should be either:
* shown with clipped ellipsis style
* wrap overflowing text content to next line

### Actual Behavior

The accent fish chip overflows/breaks the containing block.

### Environment

- Angular:17.3.1
- CDK/Material: 17.3.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2024-04-24 10:31
Duplicate of https://github.com/angular/components/issues/26584.

**Closed by crisbeto** 2024-04-24 10:31 UTC
Labels: needs triage
