### ISSUE TITLE
Undocumented attributes - mat-subheader, mat-line, mat-list-icon

### ISSUE THREAD

**Issue by akunaatrium** [angular/components#18606] opened 2020-02-25 07:44 UTC
I am looking at the example source code of List component on this page: https://material.angular.io/components/list/examples and am a bit confused as to where some of the used attributes come from.

The example looks like this:
```
<mat-list>
  <h3 mat-subheader>Folders</h3>
  <mat-list-item *ngFor="let folder of folders">
    <mat-icon mat-list-icon>folder</mat-icon>
    <h4 mat-line>{{folder.name}}</h4>
    <p mat-line> {{folder.updated | date}} </p>
  </mat-list-item>
  <mat-divider></mat-divider>
  <h3 mat-subheader>Notes</h3>
  <mat-list-item *ngFor="let note of notes">
    <mat-icon mat-list-icon>note</mat-icon>
    <h4 mat-line>{{note.name}}</h4>
    <p mat-line> {{note.updated | date}} </p>
  </mat-list-item>
</mat-list>
```

I can't find documentation about the `mat-subheader` attribute used in the example, as well as `mat-line` and `mat-list-icon`. Is there any? I just started to use Angular, so I could as well be overlooking something.

**Comment by thw0rted** [comment] 2020-03-03 15:35
I found this issue because I have both `mat-list-icon` and `matListIcon` in my code and both seem to work.  If one or the other is canonically correct -- especially, if there's a good reason *why* one or the other is correct here -- I haven't found it.  Closest I've come is #3125 which says "`@Components` are dash-case and `@Directives` are camelCase".  I guess `mat-list-icon` is a Directive so it's supposed to be camel-cased, but they still support dash-case some years later.  Should I switch all my "legacy" directives over?

**Comment by atn832** [comment] 2020-05-12 02:10
This page doesn't list everything but it lists some more classes related to typography: https://material.angular.io/guide/typography#what-is-typography-

**Comment by thw0rted** [comment] 2020-05-12 08:48
That's a good page -- I've used it extensively -- but as far as I can tell it's all CSS classes, not directives, which is what the OP is asking about.

**Comment by devversion** [comment] 2020-05-27 18:35
It looks like we excluded those styling directives from the docs. See: https://github.com/angular/components/commit/0a7e29345e137944d2253dd1292a06f47a98c8a9.

Though we have each of the disabled one explicitly mentioned/described in the list overview. See: https://material.angular.io/components/list/overview.

I'm closing this as these attributes are considered documented. Happy to re-open when someone has strong feelings that this could be improved, or that we need them show up in the API as actual directive.

**Closed by devversion** 2020-05-27 18:35 UTC
Labels: docs, needs triage

**Comment by thw0rted** [comment] 2020-05-28 10:44
@devversion Looking back at the OP, maybe the actual resolution is that this is effectively a duplicate of #3125.  That issue more directly address the problem.
