### ISSUE TITLE
feat(BooleanInput): make types more strict

### ISSUE THREAD

**Issue by jeroni** [angular/components#24983] opened 2022-05-27 10:14 UTC
### Feature Description

Change BooleanInput type in the cdk/coercion module to avoid potential typo based bugs to:
```ts
export type BooleanInput = 'true' | 'false' | boolean | null | undefined;
```

### Use Case

As any string value diferent from `'false'` would become `true`, a simple typo could lead to unexpected behaviours:

```html
<mybutton disabled='flase'></mybutton>
```
Observe de typo 'flase' instead of 'false'. With stricter types typescript would fire an error in the template.

**Comment by wagnermaciel** [comment] 2022-05-27 16:27
There are valid uses of BooleanInputs where users are checking if for example an object is defined

Making a change like this would almost certainly break components for many teams so I will close this as it is working as intended

**Closed by wagnermaciel** 2022-05-27 16:27 UTC
Labels: feature, needs triage
