### ISSUE TITLE
Progress bar(determinate mode) animation shake

### ISSUE THREAD

**Issue by qazq** [angular/components#17399] opened 2019-10-15 03:51 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-2c3xc2

Steps to reproduce:
1.  use a progress bar of determinate mode 
2.  set a timer to update progress value every 200ms
 
 
#### Expected Behavior

The animation runs smoothly.

#### Actual Behavior

The animation doesn't run smoothly. It looks like fall back and go forward.

![progress bar animation shake](https://user-images.githubusercontent.com/997727/66798677-694bd180-ef41-11e9-9d25-725a2ced6025.gif)

#### Environment

- Angular: 8.0
- CDK/Material: 8.0
- Browser(s): Chrome 77.0.3865.90
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by dexster** [comment] 2019-12-09 10:49
You need to set your update to 250 ms or more

https://github.com/angular/components/issues/15138

**Comment by josephperrott** [comment] 2020-05-27 18:23
Closing as duplicate of #15138

**Closed by josephperrott** 2020-05-27 18:23 UTC
