### ISSUE TITLE
bug(Datepicker): DatepickerFilter is not behaving if using a getter for the filter

### ISSUE THREAD

**Issue by Varatnar** [angular/components#22545] opened 2021-04-22 19:31 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/components-issue-zahr8d?file=src/app/example-component.html

Steps to reproduce:
1. Use a getter as the filter in code (see [stackblitz](https://stackblitz.com/edit/components-issue-zahr8d?file=src/app/example-component.html
))
2. Open dialog menu for the `Datepicker`
3. Attempt to click one of the non greyed-out options.
 
 
#### Expected Behavior

Possible to select any date valid (as per the date filter)

#### Actual Behavior

Impossible to pick a date that is not filtered out.

#### Environment

- Angular: 11.2
- CDK/Material: 11.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 

#### Extra notes

The same code was working previously with version 9 of angular

**Comment by crisbeto** [comment] 2021-04-23 13:11
Duplicate of https://github.com/angular/components/issues/21929.

**Closed by crisbeto** 2021-04-23 13:11 UTC
Labels: needs triage
