### ISSUE TITLE
mat-select swallows click outside when open

### ISSUE THREAD

**Issue by neonguru** [angular/components#15416] opened 2019-03-07 22:02 UTC
#### What is the expected behavior?
Clicking anything outside the mat-select (when open) should receive the click event.

#### What is the current behavior?
mat-select is swallowing the click event when it is open.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
Can reproduce on the material site:
https://material.angular.io/components/select/overview

open Basic mat-select by clicking it.
now click the Basic native select box.
It closes the Basic mat-select but does not open the Basic native select.
you have to click it twice to register the click on the Basic native select.

But now open the Basic native select, then click the Basic mat-select box.
one click closes the Basic native select and opens the basic mat-select - as expected.

My particular use case involves the multi-select mat-select box, where the user selects an option and the dropdown is not closed. Then they click on an accept changes button. They have to click it twice to register the click on the button while the mat-select dropdown is still open.
#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.3.1 is showing on the angular material site at:
https://material.angular.io/components/select/overview

#### Is there anything else we should know?
My particular use case involves the multi-select mat-select box, where the user selects an option and the dropdown is not closed. Then they click on an accept changes button. They have to click it twice to register the click on the button while the mat-select dropdown is still open.

**Comment by neonguru** [comment] 2019-03-07 22:05
As a work around, I have a mat-select openedChange handler that disables my button when the mat-select box is open, and re-enables it when closed.

But this is still a less than ideal user experience.

**Comment by josephperrott** [comment] 2019-06-04 18:07
Closing as this is working as intended.  As with native selects, our selection pattern holds that when click occurs outside of the selection box, the overlay backdrop captures the click and causes the selection box to close.

**Closed by josephperrott** 2019-06-04 18:07 UTC
