### ISSUE TITLE
Drag-drop: Drag delay (cdkDragStartDelay) does not allow scrolling on mobile Firefox

### ISSUE THREAD

**Issue by KlausHans** [angular/components#18695] opened 2020-03-03 15:41 UTC
#### Reproduction

Steps to reproduce:
1. Open https://material.angular.io/cdk/drag-drop/overview#delayed-dragging on mobile Firefox 68.5.0, e.g. on tablet or mobile phone
2. Try to scroll with the starting point over the dragable.
 
 
#### Expected Behavior

I can scroll.

#### Actual Behavior

I can't scroll.

#### Environment

- Angular: 9.0.4
- CDK/Material: 9.1.0
- Browser(s): mobile Firefox 68.5.0
- Operating System (e.g. Windows, macOS, Ubuntu): Android 8.1.0

Works fine on mobile Chrome. Issue is exact the same as the closed and locked https://github.com/angular/components/issues/16224 that is marked as fixed. Apparently it is not fixed for Firefox.

**Comment by KlausHans** [comment] 2020-03-03 15:57
Just tested it with Safari on an iPad. Does not work there ether.

**Comment by Achilles1515** [comment] 2020-03-03 16:50
https://github.com/angular/components/issues/17923

**Comment by crisbeto** [comment] 2020-05-27 18:57
Closing as a duplicate of https://github.com/angular/components/issues/17923.

**Closed by crisbeto** 2020-05-27 18:57 UTC
Labels: area: cdk/drag-drop
