### ISSUE TITLE
bug(material/datepicker): form state not correct with existing data

### ISSUE THREAD

**Issue by nerumo** [angular/components#20896] opened 2020-10-27 12:00 UTC
#### Reproduction
I use a date range picker with reactive forms. If I have an existing value that is bound to the start/end input, the form control will automatically turn dirty.
Here's a stackblitz: https://stackblitz.com/edit/angular-ai7kcs-mm7zyj?file=src/app/date-range-picker-forms-example.ts
 
 
#### Expected Behavior
The FormControl should be dirty=false.

#### Actual Behavior
`dirty` is always set to true after initialization.

#### Environment
- Angular: 10.2.0
- CDK/Material: 10.2.5
- Browser(s): Chrome (latest stable)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment] 2020-10-29 18:09
Duplicate of https://github.com/angular/components/issues/20213.

**Closed by crisbeto** 2020-10-29 18:09 UTC
Labels: needs triage
