### ISSUE TITLE
bug(Radio & Checkbox): Not enabled anymore after assigning a new (enabled) FormControl

### ISSUE THREAD

**Issue by daniel-seitz** [angular/components#22825] opened 2021-05-27 15:26 UTC
#### Reproduction

https://stackblitz.com/edit/components-issue-xsxwwq?devtoolsheight=33&file=src/app/example-component.html

Steps to reproduce:
1. click the button a few times
2. radio and checkbox are not enabled anymore but other inputs like text do
 
 
#### Expected Behavior

The Components should reflect the en-/disabled state

#### Actual Behavior

The components are disabled but not enabled anymore

#### Environment

- Angular: v11
- CDK/Material: >= v11
- Browser(s): Chrome, Edge, Firefox, probably all

I tried injecting the ChangeDetectorRef and calling detectChanges/markForCheck but didnt work either. Please have a look.

**Comment by jelbourn** [comment] 2021-05-27 17:27
Duplicate of https://github.com/angular/angular/issues/35309

**Closed by jelbourn** 2021-05-27 17:27 UTC
Labels: needs triage
