### ISSUE TITLE
Fixed Sidenav is clipped by mat-sidenav-container in Safari

### ISSUE THREAD

**Issue by lucferbux** [angular/components#11715] opened 2018-06-08 13:03 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
mat-sidenav element to display fixed in Safari, this sidenav is the one generated with Angular CLI.
`ng generate @angular/material:material-nav --name=my-nav-example`

#### What is the current behavior?
Works fine in Google Chrome, but it's hidden in Safari 11.1. (See snapshots below)

#### What are the steps to reproduce?
In a new project generate the sidnav.
`ng generate @angular/material:material-nav --name=my-nav-example`
Place it in app.component.html.

I have build the project into production and the issue still persists.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
"@angular/material": {
      "version": "6.0.2",
      "resolved": "https://registry.npmjs.org/@angular/material/-/material-6.0.2.tgz",
      "integrity": "sha512-928g7cnnRIJJx9/pC5GWqypcxrKkfijTCrCC6yeypvcgab1pmsk7m+1uE8VSFGIsUb6x8W3CF5nJUT1viuBIZg==",
      "requires": {
        "tslib": "^1.7.1"
      }

#### Google Chrome
![screen shot 2018-06-08 at 14 54 48](https://user-images.githubusercontent.com/16117276/41159452-dd3645fc-6b2c-11e8-9525-377c1483a4bd.png)

#### Safari
![screen shot 2018-06-08 at 14 54 55](https://user-images.githubusercontent.com/16117276/41159453-dd52c538-6b2c-11e8-904c-3b562bd76e26.png)

**Comment by lucferbux** [comment] 2018-06-08 13:08
I have check that the issue is opened in #11392 
But I don't see a real fix in the suggested ones, I will leave the issue open for more info.

**Comment by amcdnl** [comment] 2018-06-15 15:50
Fixed by - https://github.com/angular/material2/pull/11191/files#diff-98cc0250d23a2ee2df9c0b956a89c124R84

**Comment by ssgriffen** [comment] 2018-06-22 16:33
Hey @amcdnl Is the fix in prod? I've upgraded to 6.3.0 and am still having this issue?

**Comment by lucferbux** [comment] 2018-06-27 14:29
Same here @amcdnl I've upgraded my project to 6.3.0 and it's still broken. The fix is in that version?

**Comment by visyan** [comment] 2018-07-25 10:16
Hi, facing this issue as well even after update to @angular/material 6.4.1. What do you mean by 're-generate the schematic' ?

**Comment by Mischazz** [comment] 2018-07-30 18:04
'.mat-drawer-container{
  overflow: visible;
}'
I added this as temporary fix. That worked for me

**Comment by t0rsch** [comment] 2018-09-22 09:07
@Mischazz thanks a lot for that! I think it has to be
`.mat-drawer-container{ overflow: visible; }`
though, just for anyone wondering in the future.

**Comment by olefrank** [comment] 2019-03-12 08:31
This doesn't seem to be fixed yet (7.0.0-beta.23) ??

**Comment by vegaskev** [comment] 2019-03-29 17:00
`mat-drawer-container { overflow: visible; }` did not solve the issue for me.  I'm running 7.2.0

**Comment by kesavik** [comment] 2019-04-29 19:47
@vegaskev try .mat-drawer-container{ overflow: visible; }. It worked for me.

**Comment by GeoffMahugu** [comment] 2019-05-09 08:34
@Mischazz Having the same issue and  .mat-drawer-container{ overflow: visible; } didn't work for me
I'm currently in "@angular/material": "^7.3.6"

**Comment by dheeraj-kawatra** [comment] 2019-09-07 12:21
.mat-drawer-container{
    position: fixed;
    overflow: visible;
    height: 75px;

    .mat-drawer-backdrop {
        height: 100vh;
    }
} 

This met my requirements. tweak for your own.

**Comment by Brhav** [comment] 2019-09-13 18:11
If somebody is looking into this, it may be interesting to also look at #16491 which seems to be closely related

**Comment by jelbourn** [comment] 2020-05-27 23:35
This is caused by a WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=160953

`mat-sidenav-container` is `overflow: hidden` and has a `z-index`. This triggers the bug in Safari that incorrectly causes the `position: fixed` `mat-sidenav` element to be clipped by the containing `mat-sidenav-container`.

Since the WebKit bug has been open since 2016, we should probably work around this on our end.

**Comment by aleperfetti81** [comment] 2020-06-16 10:36
Hi Guys,

is this problem fixed? I've tried with @vegaskev solution but it didn't worked. can you help me?
I face the problem only on safari and chrome on IOS.

Thank you very much for your help!

**Comment by lukekroon** [comment] 2020-09-13 16:38
I have the same problem on Angular Material 10.2. The mentioned suggestions does not work for me. Any other workarounds?

**Comment by aleperfetti81** [comment] 2020-10-23 13:04
Hi guys, any solution?

**Closed** 2021-06-14 07:33 UTC
Labels: G, P2, area: material/sidenav
