### ISSUE TITLE
bug(google-map): MapEventManager.destroy fails

### ISSUE THREAD

**Issue by houbi56** [angular/components#26242] opened 2022-12-12 11:59 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

After an API-error such as : Google Maps JavaScript API error: InvalidKeyMapError the maps component gets an error on destroy. 

Tried removing the (mapClick) event but it still happens.

We get the following error in the component
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'remove')
TypeError: Cannot read properties of undefined (reading 'remove')
    at MapEventManager._clearListeners (google-maps.mjs:26:22)
    at MapEventManager.destroy (google-maps.mjs:66:14)
    at MapMarker.ngOnDestroy (google-maps.mjs:1677:28)
    at executeOnDestroys (core.mjs:7372:32)
    at cleanUpView (core.mjs:7275:9)
    at destroyViewTree (core.mjs:7101:21)
    at destroyLView (core.mjs:7253:9)
    at RootViewRef.destroy (core.mjs:21252:9)
    at ComponentRef.destroy (core.mjs:21654:23)
    at RouterOutlet.deactivate (router.mjs:2503:28)
    at ActivateRoutes.deactivateRouteAndOutlet (router.mjs:2097:28)
    at ActivateRoutes.deactivateRouteAndItsChildren (router.mjs:2070:18)
    at ActivateRoutes.deactivateRoutes (router.mjs:2059:22)
    at router.mjs:2031:18
    at Array.forEach (<anonymous>)
    at resolvePromise (zone.js:1213:1) [angular]
    at resolvePromise (zone.js:1167:1) [angular]
    at polyfills.js:5587:17 [angular]
    at Object.onInvokeTask (core.mjs:25561:33) [angular]
    at drainMicroTaskQueue (zone.js:582:1) [<root>]
    at ZoneTask.invokeTask [as invoke] (zone.js:491:1) [<root>]
    at invokeTask (zone.js:1600:1) [<root>]
    at HTMLDivElement.globalZoneAwareCallback (zone.js:1626:1) [<root>]
defaultErrorLogger @ core.mjs:6500
handleError @ core.mjs:6547
next @ core.mjs:26109
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.mjs:22441
(anonymous) @ core.mjs:25600
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25473
onHandleError @ core.mjs:25600
handleError @ zone.js:376
runGuarded @ zone.js:147
api.microtaskDrainDone @ zone.js:1074
drainMicroTaskQueue @ zone.js:589
invokeTask @ zone.js:491
invokeTask @ zone.js:1600
globalZoneAwareCallback @ zone.js:1626

### Reproduction

  <google-map [options]="mapOptions" [center]="mapOptions.center" height="70vh" width="100%" (mapClick)="onMapClick($event)">
    <map-marker #marker="mapMarker" (mapClick)="openInfoWindow(marker)" [position]="markerPosition" [options]="markerOptions"></map-marker>
    <map-info-window>
      Longitud: {{ this?.longitude }} <br />
      Latitud: {{ this?.latitude }}
    </map-info-window>
  </google-map>

### Expected Behavior

No console errors

### Actual Behavior

Errors in the console

### Environment

- Angular: 13.2.6
- CDK/Material: 13.2.6
- Browser(s): chrome

**Comment by crisbeto** [comment] 2022-12-15 08:44
I wasn't able to reproduce the issue even if I force a load error like providing an invalid API key.

**Comment by crisbeto** [comment] 2023-01-23 08:06
Closing since I couldn't reproduce the issue and there hasn't been any new information.

**Closed by crisbeto** 2023-01-23 08:06 UTC
Labels: needs triage
