### ISSUE TITLE
bug(ListKeyManager): active item reference remains although the child component is already deleted

### ISSUE THREAD

**Issue by justi7n** [angular/components#22249] opened 2021-03-16 12:51 UTC
#### Reproduction

https://stackblitz.com/edit/active-item-reference?file=src/app/app.component.html

Steps to reproduce:
1.  Click 'Fill List'
2.  Click 'Clear List'
 

#### Expected Behavior

It should display the message 'ActiveItem: null', because the `activeItem` should be null, when there are no items.

#### Actual Behavior

It displays the message 'ActiveItem: "0"'.   
It has no items, but the `activeItem` still contains a reference of a deleted node.

#### Environment

- Angular: 11.0.4
- CDK/Material: 11.2.4
- Browser(s): Chrome
- Operating System: Windows

**Comment by crisbeto** [comment] 2021-03-16 17:13
Duplicate of https://github.com/angular/components/issues/14345 which has a pending PR #14471.

**Closed by crisbeto** 2021-03-16 17:13 UTC
Labels: needs triage
