### ISSUE TITLE
Customisable select panel height

### ISSUE THREAD

**Issue by RudolfFrederiksen** [angular/components#15803] opened 2019-04-12 16:42 UTC
#### Please describe the feature you would like to request.

Configuration of the panel height for MatSelect.

#### What is the use-case or motivation for this proposal?

- display more select options to the user if screen estate allows it
- fix repositioning of clicked option when the panel is opened with select:multiple

#### Is there anything else we should know?

This is part **feature**, part **fix** as my main use case was the following:
- use a select with multiple choice
- display more options by overriding the panel max-height style [as suggested in #11780](https://github.com/angular/material2/issues/11780#issuecomment-400011421)

This suggestion works, but adds a weird repositioning of the selected option if it is below the hardcoded 256px limit.
It is reproducible with all versions below angular-material 7.3.7 (and including master).

Reproductible test case: https://stackblitz.com/edit/angular-select-panel
video: https://streamable.com/g0z7k

This snippet is based on the multiple select example from the documentation. I simply added a class to increase the height of the select panel.
If you select anything below the `Leek` option, the scrollbar is moved to make the option "visible" in the panel.
The option is obviously visible to us, but as the height of the panel is hardcoded at 256px, it is considered out of it by the computation of MatSelect component.

I initially only wanted to fix the issue I just described, but after reviewing the component's code, I thought it would be cleaner to freely configure the panel's height.
Depending on screen space availability, people can decide how big they want the panel to be.
Additionally it can also be dynamically set if one wants to support multiple screen sizes.

This would fix:
- the issue described above
- #11780
- #15192

**Comment by pcurrivan** [comment] 2019-06-27 01:04
Thanks for working on this.

So with your PR, we would use the input instead of css?  Or would we still need css that matches the input?  Also why not do all of the hard-coded dimensions while you are at it? SELECT_ITEM_HEIGHT_EM specifically is what I really want to change.  Maybe once your PR gets merged we can do the rest?

**Comment by RudolfFrederiksen** [comment] 2019-06-27 08:44
1) With this PR, we can configure the height of the panel with the input only.
No need for custom css anymore, but we can still override it.
It's not breaking previous custom `max-height` overrides.

2) `why not do all of the hard-coded dimensions`
My initial goal with this PR was to fix some bugs with the panel `max-height` css override.
The problem was that the css value was not taken into account for overlay and scroll positioning computations (as it was an hardcoded value) and lead to weird scroll jumping behavior when using multiple selection. (check my reproduction case above)
I fixed that and add a parameter for the panel height as it seemed neater.

`SELECT_ITEM_HEIGHT_EM specifically is what I really want to change.`
I agree it would be nice to have that kind of configuration without overriding css everywhere.
From what I can see in the source, this value is only used once:
https://github.com/angular/components/blob/aa2236820da4b14fb4fd9e6a57a05660b615da2c/src/material/select/select.ts#L1315

It seems pretty simple to change as long as we still use EM values.
But should we use that only? or px values? both?
That's definitely part of an other issue.

Also technically, we don't need this issue's PR to implement this feature as `_getItemHeight()` is well isolated from other computations :)

**Comment by amysorto** [comment] 2022-11-03 17:30
Duplicate of #15192. Height can be configured by overriding the CSS in the new MDC based select component in v15.

**Closed by amysorto** 2022-11-03 17:30 UTC
Labels: feature, P3, area: material/select, Fixed in MDC
