### ISSUE TITLE
bug(mat-form-field): Form control error is removed after template based form field added 

### ISSUE THREAD

**Issue by galwa** [angular/components#21497] opened 2021-01-05 15:58 UTC
I am utilizing an inline table edit scenario where the form field is added conditionally ( on cell click)

```html
<ng-container *ngIf="!state.edit;else elseEditTest">element.controls.test.value</ng-container>

<ng-template #elseEditTest>
    {{log(element.controls.input_audio_index)}}
    <mat-form-field><input matInput formControlName="test">
    <mat-error>{{element.controls.test?.errors?.server}}</mat-error>
    </mat-form-field>
    {{log(element.controls.test)}}
</ng-template>
```

Note, state edit is set to true when the control have an error 

the log function prints the controller with Object.assign

The issue seen :
1st print have controll.error have error value assigned ( returned from backend )
2nd print have error set to null

"@angular/cdk": "^10.2.7",
"@angular/common": "^10.2.1",
"@angular/compiler": "^10.2.1",
"@angular/core": "^10.2.1",
"@angular/flex-layout": "^11.0.0-beta.33",
"@angular/forms": "^10.2.1",
"@angular/localize": "^10.2.1",
"@angular/material": "^10.1.2",

**Comment by wagnermaciel** [comment] 2021-01-07 21:41
This issue doesn't have enough information for the team to investigate. Please include a reproduction of the issue (preferably via StackBlitz)

**Comment by crisbeto** [comment] 2021-07-28 17:25
Closing since there hasn't been any feedback. The issue can be reopened if we get more information.

**Closed by crisbeto** 2021-07-28 17:25 UTC
Labels: needs clarification, troubleshooting
