### ISSUE TITLE
mat-label overflows matSuffix content

### ISSUE THREAD

**Issue by Ben555555** [angular/components#30176] opened 2024-12-12 14:46 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a text is longer than the input field it overflows the matSuffix content (icons etc.):

### Reproduction

```
<mat-form-field style="width:100px">
  <mat-label>Very very very very long text</mat-label>
  <input matInput />
  <span matSuffix>
    <mat-icon>cancel</mat-icon>
  </span>
</mat-form-field>
```

![Image](https://github.com/user-attachments/assets/3966282c-425f-4593-9d17-35f5e1539d34)

### Expected Behavior

ellipsis are displayed when overflowing the matSuffix content.

### Actual Behavior

The input field label overflows the matSuffix content (icons etc.):

### Environment

- Angular: 18.2.14
- CDK/Material: 18.2.14
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by amysorto** [comment] 2024-12-16 16:22
Duplicate of #28743

**Closed by amysorto** 2024-12-16 16:22 UTC
Labels: needs triage
