### ISSUE TITLE
feat(datepicker): stand-alone/inline calendar component usage should be documented

### ISSUE THREAD

**Issue by hakimio** [angular/components#20931] opened 2020-10-30 13:03 UTC
#### Feature Description

While it's possible to use the calendar component without the date input, its usage is not documented. Documentation explaining how to use it in single and date range selection modes should be introduced so that people wouldn't have to look into project sources to figure out how it's supposed to be used.
Even single selection mode is pretty straight-forward and there are comments explaining what the inputs and outputs do, it's not trivial to figure out how to use it in date range selection mode.
[Calendar date range selection example](https://stackblitz.com/edit/angular-dfqwce?file=src/app/date-range-picker-overview-example.html)

#### Use Case

- Custom date range picker with predefined date range types and other features:
![custom date range picker](https://user-images.githubusercontent.com/768105/97707936-4d698e00-1ab8-11eb-8c5e-8b098e5e94ca.PNG)
- Use it in a dashboard to show current date
- Appointment booking application where it would be used to show available appointment dates
- Some event scheduling application

**Comment by crisbeto** [comment] 2020-10-30 16:57
Duplicate of https://github.com/angular/components/issues/15353.

**Closed by crisbeto** 2020-10-30 16:57 UTC
Labels: feature, needs triage
