### ISSUE TITLE
docs-bug(stepper): stepper errors not working in documentation 

### ISSUE THREAD

**Issue by troywweber7** [angular/components#19407] opened 2020-05-21 00:05 UTC
#### Documentation Feedback

The following example is not showing the messages in the example code: https://material.angular.io/components/stepper/overview#error-state

This could be a general bug as I can't get errors to show in my own project either.

**Affected documentation page:** https://material.angular.io/components/stepper/overview#error-state

**Comment by crisbeto** [comment] 2020-05-21 19:34
The example is mostly set up correctly, the problem is that the stepper is marked as `linear` which means that you can't move off of the current step in order to see the error. I've submitted a PR to make it non-linear and expand the example description.

**Closed** 2020-06-12 17:09 UTC
Labels: P3, area: material.angular.io, area: material/stepper, docs, has pr
