### ISSUE TITLE
bug(mat-select): mat-select is breaking the page on modal popup

### ISSUE THREAD

**Issue by garvraj** [angular/components#28585] opened 2024-02-13 19:33 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a mat-select which opens up on modal popup, whenever I select the option and click outside , the page gets broken

### Reproduction

       <mat-form-field class="example-full-width" appearance="outline">
                    <mat-label>Class</mat-label>
                    <mat-select multiple required name="class" [(ngModel)]="selectedEnrollment">
                        <mat-option *ngFor="let class of cloneClassList" [value]="class">
                            {{class.grade?.name}} 
                        </mat-option>
                       
                    </mat-select>
                </mat-form-field>
                
                this is the dropdown code which shows on a popup
                
                
                   const modalRef1 = this.modalService.open(BulkEnrollmentComponent);
    modalRef1.componentInstance.data = { students: payload.students, classList: this.classList };
    modalRef1.result.then((result: any) => {
      this.reloadList();
      this.getClassList();
    }, reason => {
      console.log('Modal dismissed with reason:', reason);
    });
    
 this is the code I am using to open the modal popup where the dropdown shows

### Expected Behavior

The dropdown selection should work fine

### Actual Behavior

After selecting something on dropdown , I am getting this screen

<img width="1512" alt="image" src="https://github.com/angular/components/assets/41892368/24452217-6407-43d8-a6cf-583101c1b719">

### Environment

- Angular:11.2.5
- CDK/Material: 11.2.5
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):Windows, macOS

**Comment by crisbeto** [comment] 2024-02-13 20:11
This isn't enough information to reproduce the issue. Can you post an example that shows it breaking? Also worth noting that you're on a really old version of Angular that isn't getting new fixes.

**Comment by Foxhgf** [comment] 2024-02-15 00:40
https://github.com/angular/angular/security

**Comment by crisbeto** [comment] 2024-02-18 07:21
Closing since this isn't enough information for us to investigate. It can be reopened if there's a way to reproduce it.

**Closed by crisbeto** 2024-02-18 07:21 UTC
Labels: needs: clarification, needs triage

**Comment by KJSteffen** [comment] 2024-02-21 16:55
I'm seeing a similar issue that just appeared in the last week

**Comment by KJSteffen** [comment] 2024-02-22 03:30
deleting package-lock.json and npm install did the trick for me

**Comment by garvraj** [comment] 2024-02-22 04:07
> deleting package-lock.json and npm install did the trick for me

what if this happens in production ?

**Comment by KJSteffen** [comment] 2024-02-22 04:14
Fixed if for me locally and in my dev and tst deployments. My pipelines do not generate package-lock.json, so fixing locally and committing and deploying the "fixed" package-lock.json seems to be working

**Comment by ramanaamerica** [comment] 2024-02-26 18:11
The same issue is happening also with angular material 14.2.7 and especially in Google Chrome browser version 121

**Comment by KJSteffen** [comment] 2024-02-26 19:59
Yeah the problem is back for me.  I have not been able to make a simple project that reproduces the error.

**Comment by garvraj** [comment] 2024-02-27 04:04
This needs to be reopened , To unblock the users I had to convert all my mat-select to bootstrap dropdown

**Comment by crisbeto** [comment] 2024-02-27 06:14
@garvraj we can't do much about it without a way to reproduce the issue.

**Comment by ramanaamerica** [comment] 2024-02-27 14:33
@garvraj , Can you confirm your chrome browser version is it 121?

**Comment by garvraj** [comment] 2024-02-27 14:35
121.0.6167.184 @ramanaamerica

**Comment by ramanaamerica** [comment] 2024-02-27 14:39
Thank you. Same issue happing here also..

**Comment by garvraj** [comment] 2024-02-27 14:44
There is an issue definitely, its just I am not able to create a sample in stackblitz etc

**Comment by garvraj** [comment] 2024-02-27 14:47
@ramanaamerica can you update the chrome to 122.0.6261.69 and see if you are still seeing the issue, in this latest version of chrome I don't see the issue happening

**Comment by ramanaamerica** [comment] 2024-02-27 14:49
Like i said earlier, Chrome 122 and other browsers are working fine. Most of my clients are still using chrome 121 and they got impacted.

**Comment by ramanaamerica** [comment] 2024-02-28 15:17
@garvraj , found same issue in Microsoft Edge browser 121 version.

**Comment by garvraj** [comment] 2024-02-29 06:18
@ramanaamerica Haven't tried on Edge but in safari it works fine
