### ISSUE TITLE
feat(MAT-PROGRESS-BAR): Add properties height && border-radius in mat-progress-bar component.

### ISSUE THREAD

**Issue by Vic-rider** [angular/components#27178] opened 2023-05-26 08:17 UTC
### Feature Description

In mat-progress-bar component : https://material.angular.io/components/progress-bar/api it will be useful to have more properties like :

- An input variable for the height's value of mat-progress-bar component

- An input variable for the border-radius's value of mat-progress-bar component

### Use Case

In the case of specific templates we need to use mat-progress-bar with its existing properties, but also to make changes to the styles.

like this 👇🏾
![image](https://github.com/angular/components/assets/40070368/eb6ba50a-00da-4eb8-9857-5d2f1c0248c2)

**Comment by Vic-rider** [comment] 2023-05-26 11:37
Or something like this 👇🏾 : 
![image](https://github.com/angular/components/assets/40070368/102904ce-2d7d-45b7-8eb9-2d4a04035ee5)

**Comment by Vic-rider** [comment] 2023-05-26 12:30
When i try to raise the height of mat-progress-bar in all of existing mode, i have this 

![image](https://github.com/angular/components/assets/40070368/924a3f86-b9a1-4ebb-938d-f169a4a66254)

The dot in buffer mode are curved. And when i check it up, it's a inherited behavior from https://github.com/material-components/material-components-web.

Also, the dot is made of a circle image. What make impossible to look like rectangle or square when we raise it's height.

**Comment by andrewseguin** [comment] 2023-05-30 15:24
We're currently working on a CSS variable theming API to make it easier to customize these styles

**Comment by crisbeto** [comment] 2023-05-31 04:36
Closing this as a duplicate of https://github.com/angular/components/issues/4352 since we already have tokens for the size and shape of the progress bar.

**Closed by crisbeto** 2023-05-31 04:36 UTC
Labels: feature, P3, area: material/progress-bar
