### ISSUE TITLE
feat(CdkDropList): Add Harness to make it easier to test CdkDropList implementations

### ISSUE THREAD

**Issue by ChrTall** [angular/components#27045] opened 2023-05-05 16:55 UTC
### Feature Description

Currently it is really hard to test custom implementations of the CdkDropList.
It would be a nice to have a TestHarness similar to the TestHarnesses in the Material library.

### Use Case

Testing components that utilize CdkDropList.

**Comment by crisbeto** [comment] 2023-05-09 06:35
Duplicate of https://github.com/angular/components/issues/22067.

**Closed by crisbeto** 2023-05-09 06:35 UTC
Labels: feature, needs triage
