### ISSUE TITLE
bug(MatChipList): Cannot set selectable of mat-chip with Angular Material

### ISSUE THREAD

**Issue by hasancansaral** [angular/components#25410] opened 2022-08-08 08:32 UTC
### Description

Using `mat-chip-list` as a multi select with fixed `mat-chips` and using selected as values do not seem to work:

```
<mat-form-field
    floatLabel="always"
    appearance="outline">
    <mat-chip-list multiple
                   required
                   name="roles"
                   [ngModel]="user.roles">
      <mat-chip
        [selectable]="true"
        [removable]="false"
        *ngFor="let option of options"
        (click)="addRole(option )"
        [selected]="user?.roles?.includes(option )">
        <span [outerText]="role"></span>
        <button
          *ngIf="user?.roles?.includes(option )"
          (click)="removeRole(option )"
          matChipRemove>
          <mat-icon>cancel</mat-icon>
        </button>
      </mat-chip>
    </mat-chip-list>
</mat-form-field>
```

and in `.ts`:

```
addRole = (role: string): void => {
    if (!this.user?.roles ?.some(auth => auth == role)) this.user?.roles ?.push(role);
    this.user.roles = [...this.user.roles];
  }

  removeRole = (role: string): void => {
    if (this.user?.roles?.some(auth => auth == role)) this.user.roles = this.user.roles?.filter(auth => auth != role);
    this.user.roles = [...this.user.roles];
  }
```

event with `[selected]="true"` on `mat-chip` it is not selected. If I don't clone with `this.user.roles = [...this.user.roles];` the `ngModel` stops updating, and required validator is always invalid.

### Reproduction

Steps to reproduce:
1. Use `mat-chip-list` with template driven forms as multi select

### Expected Behavior

I'd expect the selected property to take change. Or `ngModel` to be updated.

### Actual Behavior

Even if `selected` is set to `true` chip is never selected.

### Environment

- Angular:
- CDK/Material: ^13.3.7
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by zarend** [comment] 2022-12-12 22:42
Hello @hasancansaral,

I believe this issue was resolved in the newer MDC-based components released in v15. Does upgrading to v15 resolve this issue for you?

-Zach

**Comment by amysorto** [comment] 2023-09-14 21:48
Closing this issue due to no recent activity, if this is still an issue please create a new issue with a reproduction.

**Closed by amysorto** 2023-09-14 21:48 UTC
Labels: P4, needs: clarification, area: material/chips, Fixed in MDC
