### ISSUE TITLE
How to use CSS Variables?

### ISSUE THREAD

**Issue by astone2014** [angular/components#22759] opened 2021-05-23 00:10 UTC
#### What are you trying to do?

Use CSS variables with the [custom angular material theme](https://material.angular.io/guide/theming).

#### What troubleshooting steps have you tried?

I can successful get css variables working except the opacity doesn't apply correctly.

As stated in this comment.
https://github.com/angular/components/blob/25665dcc219fbbb76d0ba7f79982672500f78644/src/material/core/theming/_theming.scss#L79-L84

We used to be able to overwrite the function but not sure how now that scss modules `@use` are implemented.

See [angular-material-css-vars](https://github.com/johannesjo/angular-material-css-vars/blob/451225c52f6e2af8dcf1263f8068c67580d779e9/projects/material-css-vars/src/lib/_mat-lib-overwrites.scss#L1-L21)

#### Reproduction

A great library for css variables that works with Angular 11:
[angular-material-css-vars](https://github.com/johannesjo/angular-material-css-vars)

I created a simple example in Angular 12:
[material-css-vars](https://github.com/astone2014/material-css-vars)
  
#### Environment

- Angular: 12
- CDK/Material: 12
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by lqc** [comment] 2021-05-24 09:18
This is somehow connected to #4352 - if you can use MDC components, they should work with CSS vars.

That said, I think there is a very simple solution for Angular to support this case right now. As pointed out, the theming core already checks if the resolved value is an SCSS color. Angular could also check if it is an SCSS function, and if yet call it:

```
@if (meta.type-of($color) == function) { 
  @return meta.call($color, $opacity, $hue);
}
```

Then a library like ```angular-material-css-vars``` can just pass functions as palette elements that do the necessary work of creating the right CSS expressions.

**Comment by lqc** [comment] 2021-05-25 08:27
I retract my previous statement that you can use MDC components with CSS variables. The [current implementation on Angular's side](https://github.com/angular/components/blob/master/src/material-experimental/mdc-helpers/_mdc-helpers.scss#L121) does things like:

```
mdc-theme-color.$on-primary:      if(mdc-theme-color.contrast-tone(mdc-theme-color.$primary) == 'dark', #000, #fff);
```

This obviously won't work with variables in the theme. I'll try to make a PR that implements the approach I described previously.

**Comment by jelbourn** [comment] 2021-05-27 17:49
Partial duplicate of #22822 and #4352

For the time being, we don't explicitly support theming via css variables. Some people have had success putting css variables in the values of a palette, but we unfortunately can't explicitly support this because, going forward, MDC Web will be doing compile-time calculations of provided values to produce styles. 

That said, now that we're dropping IE11 support in v13, we're looking at how we can explicitly support css variables.

**Closed by jelbourn** 2021-05-27 17:49 UTC
Labels: needs triage, troubleshooting
