### ISSUE TITLE
Roboto font moves issue

### ISSUE THREAD

**Issue by moahmadeng** [angular/components#21340] opened 2020-12-13 13:49 UTC
When page loads for the first time Roboto font that has different font weight e.g 700, 900 moves or scales into place

**Comment by Totati** [comment] 2020-12-13 22:55
Duplicate of https://github.com/angular/components/issues/21118

**Comment by crisbeto** [comment] 2020-12-14 16:16
Closed as a duplicate of #21118.

**Closed by crisbeto** 2020-12-14 16:16 UTC
Labels: needs triage

**Comment by uloga** [comment] 2020-12-22 03:46
Just started a new project and the issue remains even with "block". Not only font but buttons and other components now move as well.

**Comment by uloga** [comment] 2020-12-22 03:52
https://user-images.githubusercontent.com/3988672/102846838-5b30f500-4411-11eb-8fd8-77accf77a6dd.mov

**Comment by uloga** [comment] 2020-12-22 03:55
Do you see also on transition to the next route (authentication) how it first loads navbar and then it renders the rest of the content. No issues with v8 after upgrading to 9,10,11 the ui is behaving weird, it's not visually pleasing like it was before and it's not something I'd release to public, it's a huge downgrade IMHO.

**Comment by uloga** [comment] 2020-12-22 04:15
When you look into console it's loading the font 3x compared to the rest 1x. Does it have something to do with that?
![Uploading Screenshot 2020-12-22 at 05.12.41.png…]()

**Comment by uloga** [comment] 2020-12-22 04:29
Seem to have found issue for the font: 
Don't use `em` use `px` for font size  when you use flex-box. 
The other issue I've mentioned, latency with component rendering are related to angular and sass loader.
