### ISSUE TITLE
Make Overlay service tree shakable

### ISSUE THREAD

**Issue by mertdeg2** [angular/components#11581] opened 2018-05-30 16:12 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
Overlay service is tree shakable

#### What is the current behavior?
Overlay service is NOT tree shakable

#### What is the use-case or motivation for changing an existing behavior?
This is preventing us from making our services that depend on Overlay service tree shakable.

**Comment by crisbeto** [comment] 2020-05-27 16:30
Duplicate of https://github.com/angular/components/issues/18944.

**Closed by crisbeto** 2020-05-27 16:30 UTC
Labels: area: cdk/overlay, needs discussion
