### ISSUE TITLE
Mat-autocomplete become stuck(started since i have updated my chrome version)

### ISSUE THREAD

**Issue by guyng** [angular/components#17667] opened 2019-11-11 10:20 UTC
#### Reproduction

Steps to reproduce:
1.  Populate mat-autocomplete control with few mat-optgroups and more than 15 items. then scroll down/up.
2. map-autocomplete panel get stuck
 
 
#### Expected Behavior

What behavior were you expecting to see?
autocomplete panel will not get stuck while scrolling.

#### Actual Behavior

What behavior did you actually see?
Mat-autocomplete get stuck while scrolling down/up with more than 15 items and few groups.

#### Environment

- Angular: 8.2.3
- CDK/Material: 8.2.3
- Browser(s): Chrome Version 78.0.3904.97(It works fine on older versions, such as 76 and below this bug does not exist!)
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by devversion** [comment] 2020-05-29 23:16
Hello! I was unable to reproduce this with the described scenario. Please help us by providing an actual StackBlitz reproduction. I'm closing this in the meanwhile as we could not reproduce it, and there is no  reproduction sample shared. Happy to re-open! Thanks!

**Closed by devversion** 2020-05-29 23:16 UTC
Labels: needs triage
