### ISSUE TITLE
mat-datepicker is not working in IE

### ISSUE THREAD

**Issue by Vinoth-LearningThings** [angular/components#16162] opened 2019-05-30 13:06 UTC
#### Reproduction

The issue occurs for specific users/machines in IE-11 with Windows 7 OS. When the user tries to open up the calendar, the pop-up is empty or blank. Below is the screenshot of the calendar from angular material site. The same is working well in Chrome.

![image](https://user-images.githubusercontent.com/13533124/58634535-26c68700-8309-11e9-9bc6-621a276e32c9.png)

So, when the user clicks on the input box, following is the error logged in console.

ERROR Error
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "",
      message: "",
      name: "Error",
      number: -2147418113,
      stack: "Error
   at t.prototype._format (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:975134)
   at t.prototype.format (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:973592)
   at e.prototype._formatValue (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:1281835)
   at value.set (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:1279347)
   at pc (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:582858)
   at Anonymous function (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:631193)
   at Anonymous function (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:631081)
   at Xm (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:629973)
   at Dh (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:641070)
   at Anonymous function (https://material.angular.io/main.424eb6dff99073b21ed0.js:1:2892784)"
   }

=================

 
 
#### Expected Behavior

Calendar should be populated with dates as it does in all the browsers.

#### Actual Behavior

Calendar is not populating with the dates/entries.

#### Environment

- Angular: 6.2.6
- CDK/Material: 7.1.1
- Browser(s): IE11
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 7

**Comment by crisbeto** [comment] 2019-05-30 15:25
I wasn't able to reproduce it on a Windows 10 machine.

**Comment by Vinoth-LearningThings** [comment] 2019-05-30 15:57
@crisbeto - Yes. Its working on windows 10 machine. The issue occurs in Windows 7 machine.

**Comment by coswapnil** [comment] 2019-09-17 11:37
This give these two errors in console
ERROR RangeError: Locale 'default' is not well-formed
ERROR CONTEXT [object Object]

**Comment by nithincvpoyyil** [comment] 2019-12-03 04:26
I am also facing this issue, any1 got any updates?

**Comment by jelbourn** [comment] 2020-05-27 22:52
I also couldn't reproduce this on a Windows 10 PC w/ IE11. I don't think anyone on the team has access to a Windows 7 (or 8) PC, so if someone from the community wants to debug this to find the root cause that would be helpful.

**Comment by jelbourn** [comment] 2021-07-29 00:14
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.

**Closed by jelbourn** 2021-07-29 00:14 UTC
Labels: P4, area: material/datepicker, help wanted, ie11
