### ISSUE TITLE
(Angular-Material Density): Does it support density like MDC density?

### ISSUE THREAD

**Issue by diuming** [angular/components#25257] opened 2022-07-12 10:17 UTC
### Feature Description

Angular Material(UI) too big for desktop browser for me.
Does it support density like MDC density?
If so, could you provide some examples?
thx

**Comment by crisbeto** [comment] 2022-08-12 11:20
Duplicate of https://github.com/angular/components/issues/4597.

**Closed by crisbeto** 2022-08-12 11:20 UTC
Labels: feature, needs triage
