### ISSUE TITLE
issue with mat expansion panel expansion!

### ISSUE THREAD

**Issue by 01shadowalker01** [angular/components#16740] opened 2019-08-10 08:57 UTC
I have a component with a `mat-expansion-panel` in it. The component is placed in a loop. Here is the view of the component:
<img width="648" alt="Screenshot (49)" src="https://user-images.githubusercontent.com/52736525/62126312-a7dbd380-b2e4-11e9-8fb8-87ee4b61b90b.png">
I grab it with `@ViewChild` and based on data that comes from server, I expand some of them. I do that this way:
`@ViewChild("expansionPanel") expansionPanel;`
and after that, I subscribe to response of server and inside it, based on some conditions, I do this to open the panel:
`this.expansionPanel.expanded = true;`
Everything is okey and working well.
But problem begins when I navigate with the router to another place in the app.
After coming back to the page that has this component, that line of code doesn't work anymore and does not open the `mat-expansion-panel`.
I tested it so much and it certainly reaches to this line again but does not work.
If I reload the page, everything is alright and works fine again.
I think the problem is with `mat-expansion-panel` and `angular router`.

**Comment by andrewseguin** [comment] 2019-08-13 17:33
Closing since this does not follow our issue template, especially since there is no link to a reproduction on StackBlitz for us to investigate with

**Closed by andrewseguin** 2019-08-13 17:33 UTC
