### ISSUE TITLE
bug(DragDropModule): Dragging in a horizontal list of items on multiple items doesn't really work

### ISSUE THREAD

**Issue by egonknapen** [angular/components#25714] opened 2022-09-27 11:04 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

IF you have a list with ul+li  items horizontal, and there are too many items in the list, so it will wrap to the next line, drag+drop looks ugly/chaotic.

li items are shown horizontal by using (css display:inline-block), when using (css float:left} drag+drop doesn't work at all.

By specifying: cdkDropListOrientation="horizontal", you can make the horizontal list work. But not if it's an horizontal list which wrappes in multiple lines. 

### Reproduction

Steps to reproduce:
1. javascript

items : { text: string }[];
// a list with for example 30 items.

1.  html

		<ul cdkDropList (cdkDropListDropped)="dropItem($event)" cdkDropListOrientation="horizontal">
			<li *ngFor="let item of items" class="balloon" cdkDrag>
                              <span>{{item.text}}</span>
                         </li>
                </ul>
                
2. css

li { display: block; border: 1px solid black; }

3. Now drag an item, it will show placeholder spacing on every line at the same time, if you drag an item.

### Expected Behavior

Being able to drag an item from one position to the next, and only showing placeholders on the line I'm dragging.

### Actual Behavior

With orientation=horizontal, the placeholder openings are shown on multiple lines, the placeholder element itself is only shown on the first row. 

### Environment

- Angular: v14.2.3
- CDK/Material: v14.2.2
- Browser(s): chrome/firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment] 2022-09-27 11:07
Duplicate of https://github.com/angular/components/issues/13372.

**Comment by egonknapen** [comment] 2022-09-27 11:08
![list-during](https://user-images.githubusercontent.com/43634425/192509863-1ba85c54-4374-486c-a7db-80c8b7285587.jpg)
![list-before](https://user-images.githubusercontent.com/43634425/192509882-3d352527-1c18-46fe-9ed7-38582df7d3f0.jpg)

In the pictures you can see the list before and during mouse drag.

**Closed by crisbeto** 2022-09-27 11:07 UTC
Labels: needs triage

**Comment by crisbeto** [comment] 2022-09-27 11:10
As I mentioned above, the problem is that the drag&drop module assumes that the items are oriented along one axis which is the same issue as https://github.com/angular/components/issues/13372.

**Comment by egonknapen** [comment] 2022-09-27 11:10
Problem with more than 2 lines:

![list-during-2](https://user-images.githubusercontent.com/43634425/192510422-aa9bc0a1-799a-462d-aecb-0679df52019b.jpg)
![list-during-3](https://user-images.githubusercontent.com/43634425/192510418-2af04ab9-88df-463f-aa8e-30eb474d4ad3.jpg)
