### ISSUE TITLE
 Angular material tabs Not working in IE 11

### ISSUE THREAD

**Issue by sridharjonnalagadda** [angular/components#12264] opened 2018-07-18 15:46 UTC
#### Bug:
ERROR Error: Cannot find a differ supporting object '[object Object],[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

#### What is the expected behavior?
It should display material tabs

#### What is the current behavior?
It is not displaying anything

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### What is the use-case or motivation for changing an existing behavior?
I am just displaying static example from angular material site  

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6  only in IE 11 it is working fine in Edge

#### Is there anything else we should know?
Nothing

**Comment by josephperrott** [comment] 2018-07-18 17:06
Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by sridharjonnalagadda** [comment] 2018-07-18 20:07
https://angular-material2-issue-qmzurh.stackblitz.io

![image](https://user-images.githubusercontent.com/6060499/42904939-9a75f95a-8aa4-11e8-9aa2-cd7bf75f9a23.png)

please look into it

**Comment by jwhenry3** [comment] 2018-08-02 03:16
I too am having the issue in IE11 only. My best guess is a missing polyfill but im not quite sure which.

**Comment by dillonko** [comment] 2018-09-12 18:10
you need to uncomment the following code in your polyfills.ts file. This should fix the problem:

`
  /** IE9, IE10 and IE11 requires all of the following polyfills. **/
  import 'core-js/es6/symbol';
  import 'core-js/es6/object';
  import 'core-js/es6/function';
  import 'core-js/es6/parse-int';
  import 'core-js/es6/parse-float';
  import 'core-js/es6/number';
  import 'core-js/es6/math';
  import 'core-js/es6/string';
  import 'core-js/es6/date';
  import 'core-js/es6/array';
  import 'core-js/es6/regexp';
  import 'core-js/es6/map';
  import 'core-js/es6/weak-map';
  import 'core-js/es6/set';
` 

I hope this helps!!

**Comment by crisbeto** [comment] 2020-05-25 16:42
Looks like this was a user setup error. Closing.

**Closed by crisbeto** 2020-05-25 16:42 UTC
Labels: area: material/tabs
