### ISSUE TITLE
'_applyBodyHighContrastModeCssClasses' is undefined

### ISSUE THREAD

**Issue by ojanh** [angular/components#22250] opened 2021-03-16 17:50 UTC
i've got some issues when updated angular material in 11.2.4, with removing package-lock.json
when i do ng serve or ng build, i get this error when load the web:

> TypeError: Cannot read property '_applyBodyHighContrastModeCssClasses' of undefined
>     at new MatCommonModule (core.js:101)
>     at Object.factory (core.js:11310)
>     at R3Injector.hydrate (core.js:11363)
>     at R3Injector.get (core.js:11183)
>     at core.js:11220
>     at Set.forEach (<anonymous>)
>     at R3Injector._resolveInjectorDefTypes (core.js:11220)
>     at new NgModuleRef$1 (core.js:25231)
>     at NgModuleFactory$1.create (core.js:25285)
>     at core.js:29112

i tried to trace that problem, i get the source of problem is on MatCommonModule because of some dependency inejction problem.
anyone can handle that??

**Comment by crisbeto** [comment] 2021-03-16 18:01
It's hard to tell based on the provided information, but it could be due to a version mismatch between `@angular/material` and `@angular/cdk`.

**Comment by ojanh** [comment] 2021-03-16 18:15
@crisbeto 
the version is same. but i still get that problem.

i tried to debug, then the problem is on `highContrastModeDetector` is undefined when first load. i think it's because of depedency injection problem

**Comment by crisbeto** [comment] 2021-03-16 20:12
We haven't changed any code that would have an effect on it recently. Does it still happen if you downgrade to 11.1?

**Comment by jelbourn** [comment] 2021-03-18 20:43
@ojanh without a reproduction there's not much we can really investigate here

**Comment by Lertis** [comment] 2021-03-23 09:43
I faced the same issue. For me downgrade dependencies versions help. Here is my list (from -> to):
```
"@angular/animations": "11.1.1" -> "11.0.0",
"@angular/cdk":  "11.2.4" -> "11.0.0",
"@angular/common": "11.1.1" -> "11.0.0",
"@angular/compiler": "11.1.1" -> "11.0.0",
"@angular/core": "11.2.5" -> "11.0.0",
"@angular/forms":"11.1.1" -> "11.0.0",
"@angular/material": "11.2.4" -> "11.0.0",
"@angular/material-moment-adapter":"11.1.1" -> "11.0.0",
"@angular/platform-browser": "11.1.1" -> "11.0.0",
"@angular/platform-browser-dynamic":"11.1.1" -> "11.0.0",
"@angular/router": "11.1.1" -> "11.0.0",
"@angular/cli": "11.1.4" -> "11.0.0",
"@angular/compiler-cli": "11.1.1" -> "11.0.0",
"@angular/language-service": "11.1.1" -> "11.0.6",
"typescript": "4.1.5" -> "4.0.6"
```

**Comment by angwangiot** [comment] 2021-04-01 00:38
I faced the same issue

**Comment by Nessumsar** [comment] 2021-05-03 09:25
@Lertis Thanks for the tip. I think the problem for me here was incompatible versions or some of the dependencies missing. 
If anyone else has this problem, be sure to triple-check those dependencies.  (Tip: use "npm ls <package>")

**Comment by jelbourn** [comment] 2021-05-03 15:45
Closing since it sounds like a version mismatch and there's no reproduction for investigation

**Closed by jelbourn** 2021-05-03 15:45 UTC
Labels: needs clarification
