### ISSUE TITLE
sidenav modes 'over' and 'push' break sidenav toggle in IE11

### ISSUE THREAD

**Issue by gjr-qm** [angular/components#9797] opened 2018-02-05 22:06 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Opening and closing should work in IE11 as they do in Chrome/FireFox/Safari

#### What is the current behavior?
Demo from the docs (Changing the sidenav's behavior) shows the bug. After chosing mode 'push' or 'over' the mat-sidenav does not close any more in all modes 

#### What are the steps to reproduce?
1. Start the demo: https://stackblitz.com/angular/xlxaydvqkbx in IE11
2. Choose mode 'side': toggle works as expected
3. Choose mode 'push' or 'over'
4. Click 2 times toggle and sidenav is stuck (even when you set mode back to 'side'. Developer tools show error 'access denied' in console

#### What is the use-case or motivation for changing an existing behavior?
Using sidenav in a responsive design (mode side on larger screens, push or over on smaller devices)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular and Material from the material2 docs. Browser IE11.

#### Is there anything else we should know?
Edge has some flaws too with sidenav modes (that hopefully will be solved by fixing the IE behavior), although our application is not affected.

**Comment by crisbeto** [comment] 2020-05-27 16:15
I just tried this out both against IE 11 and Edge, but it was working as expected. Given that the issue is pretty old, I'm closing it, but it can be reopened if we get more info.

**Closed by crisbeto** 2020-05-27 16:15 UTC
Labels: area: material/sidenav, cannot reproduce, ie11
