### ISSUE TITLE
docs-bug(THEME): Difference between Angular Material Theming all-component-colors and all-component-themes?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#26425] opened 2023-01-13 02:53 UTC
### Documentation Feedback

Could someone please help with this question:

[Difference between Angular Material Theming all-component-colors and all-component-themes?](https://stackoverflow.com/questions/74890266/difference-between-angular-material-theming-all-component-colors-and-all-compone)

### Affected documentation page

https://material.angular.io/guide/theming

**Comment by crisbeto** [comment] 2023-01-24 09:26
Duplicate of https://github.com/angular/components/issues/26342.

**Closed by crisbeto** 2023-01-24 09:26 UTC
Labels: docs, needs triage
