### ISSUE TITLE
mat-select's ARIA hidden attribute is confusing the screen reader from perceiving the control on the page.

### ISSUE THREAD

**Issue by kesava885** [angular/components#16369] opened 2019-06-24 14:15 UTC
#### Screenshot

![ARIAHiddenAddedIncorrectly](https://user-images.githubusercontent.com/51958621/60025858-7e39e780-9668-11e9-8967-5d221946a533.png)
 
 
#### Expected Behavior

Please remove the aria-hidden attribute from the markup so that the user using the screen reader can perceive the control and use it effectively.

#### Actual Behavior

Currently, the control includes ARIA hidden attribute which keeps the user using the screen reader from perceiving the control on the page.

#### Environment

- Angular: 7
- CDK/Material: 7
- Browser(s): Chrome/IE
-Screen Reader: JAWS 2019
- Operating System: Windows

**Comment by garrettld** [comment] 2019-10-02 13:45
I was curious why the aria-hidden attribute was added and discovered this issue, so I dug around a bit and found this PR: https://github.com/angular/components/pull/5181

Reading through the comments there, the addition of the aria-hidden attribute was an attempt to fix an issue where screen readers would treat the trigger as one of the options in the list and read out an incorrect number for the number of list items (e.g., 1 of 6 selected when there's only 5 items in the list).

This comment (https://github.com/angular/components/pull/5181#issuecomment-311161525) says that

> Setting the aria-hidden="true" all the time still works on the screen readers that I could get my hands on (VoiceOver and NVDA), because we have an aria-label on the select already

but JAWS was not tested for that change, and it's not actually true that there's always an aria-label. In the image you provided, you used aria-labelledby. You can see here (https://github.com/angular/components/blob/master/src/material/select/select.ts#L1102-L1106) that when aria-labelledby is set, the aria-label attribute is not added. I don't have access to JAWS so I can't test this for you, but if you're able to add an aria-label attribute

**Comment by jelbourn** [comment] 2020-05-27 23:08
Duplicate of #11083

**Closed by jelbourn** 2020-05-27 23:08 UTC
Labels: needs triage
