### ISSUE TITLE
MatDatepicker ngModel doesn't update from controller

### ISSUE THREAD

**Issue by PunkHaz4rd** [angular/components#16949] opened 2019-09-02 13:12 UTC
#### Reproduction

Steps to reproduce:
1. Use a Mat Date Picker with a [(ngModel)]
2. Change the value of ngModel in the controller
 
#### Expected Behavior

The input should have updated the value shown

#### Actual Behavior

The input doesn't actualize

#### Environment

- Angular: 7.0.1
- CDK/Material: 7.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment] 2019-09-02 15:19
Can you post a Stackblitz that shows the issue?

**Comment by PunkHaz4rd** [comment] 2019-09-11 09:24
This is a little bit more complicated than a Hello World, so stackblitz isn't working
Here's what I am trying to do anyway
https://angular-nqxvyh.stackblitz.io

While it's buggy on stackblitz, the only thing that's not working in my app is that when I clic on previous or next, the date in the input isn't updating.

**Comment by crisbeto** [comment] 2019-09-13 12:01
I haven't tried moving this into our demo app, but from looking at the code I think the issue is that change detection isn't firing because `subtract` mutates the original Moment object, it doesn't create a new one so as far as Angular is concerned the date is the same. You can try adding `.clone()` before the `.subtract`.

**Comment by wagnermaciel** [comment] 2020-08-13 23:10
Closing because this issue has been inactive for 2 weeks or more after follow up was requested.

**Closed by wagnermaciel** 2020-08-13 23:10 UTC
Labels: area: material/datepicker, needs clarification
