### ISSUE TITLE
Angular 9.1 PRODUCTION BUILD PROBLEM

### ISSUE THREAD

**Issue by sebrojas14** [angular/components#18992] opened 2020-04-05 05:23 UTC
#### Reproduction

Steps to reproduce:
1. Create an Angularmaterial app with moment adapter and angulasr version 9.1
2. run in prod mode
 
#### Expected Behavior

No errors

#### Actual Behavior

I got this error:

`main.6cb9af11670417f86d29.js:1 ERROR Error: Uncaught (in promise): ReferenceError: _rollupMoment__default is not defined
ReferenceError: _rollupMoment__default is not defined
    at Module.buQg (2.dfdd7d5ee32060a22704.js:formatted:20)
    at a (runtime.593c123d0fd4f9e3ffe6.js:1)
    at l.invoke (polyfills.c48ca712cce2b3fdf08b.js:1)
    at Object.onInvoke (main.6cb9af11670417f86d29.js:1)
    at l.invoke (polyfills.c48ca712cce2b3fdf08b.js:1)
    at i.run (polyfills.c48ca712cce2b3fdf08b.js:1)
    at polyfills.c48ca712cce2b3fdf08b.js:1
    at l.invokeTask (polyfills.c48ca712cce2b3fdf08b.js:1)
    at Object.onInvokeTask (main.6cb9af11670417f86d29.js:1)
    at l.invokeTask (polyfills.c48ca712cce2b3fdf08b.js:1)
    at T (polyfills.c48ca712cce2b3fdf08b.js:1)
    at T (polyfills.c48ca712cce2b3fdf08b.js:1)
    at polyfills.c48ca712cce2b3fdf08b.js:1
    at l.invokeTask (polyfills.c48ca712cce2b3fdf08b.js:1)
    at Object.onInvokeTask (main.6cb9af11670417f86d29.js:1)
    at l.invokeTask (polyfills.c48ca712cce2b3fdf08b.js:1)
    at i.runTask (polyfills.c48ca712cce2b3fdf08b.js:1)
    at m (polyfills.c48ca712cce2b3fdf08b.js:1)`

![image](https://user-images.githubusercontent.com/1771574/78467377-c8f58f00-76d1-11ea-94a4-074a1130afe6.png)

#### Environment

- Angular: 9.1
- CDK/Material: 9.2
- Browser(s): Chrome current version
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2020-04-05 07:14
Duplicate of https://github.com/angular/angular-cli/issues/17320.

**Closed by crisbeto** 2020-04-05 07:14 UTC
Labels: needs triage

**Comment by sebrojas14** [comment] 2020-04-05 08:26
My workarround was to add this line at the end of `polyfills.ts` file:
`window['_rollupMoment__default'] = null;`

**Comment by JosepAlacid** [comment] 2020-04-06 17:36
Thank you very much @sebrojas14 It worked like a charm.
But it's frustrating how depend of workarounds like these. Don't you think so?
