### ISSUE TITLE
MatMenu drop-down fails when ivy is enabled.

### ISSUE THREAD

**Issue by grahamaj** [angular/components#16041] opened 2019-05-16 17:25 UTC
This issue is similar to a recently closed issue https://github.com/angular/components/issues/15937, but with a different error.

#### What is the expected behavior?
No error

#### What is the current behavior?
Drop down fails when ivy is enabled with the following errors:
First click of the button:
```
core.js:7199 ERROR TypeError: Cannot read property 'createEmbeddedView' of undefined
    at ViewContainerRef_.createEmbeddedView (core.js:20126)
    at DomPortalOutlet.attachTemplatePortal (portal.js:343)
    at DomPortalOutlet.attach (portal.js:225)
    at OverlayRef.attach (overlay.js:926)
    at MatMenuTrigger.openMenu (menu.js:1175)
    at MatMenuTrigger.toggleMenu (menu.js:1157)
    at MatMenuTrigger._handleClick (menu.js:1501)
    at MatMenuTrigger_click_HostBindingHandler (menu.js:1565)
    at executeListenerWithErrorHandling (core.js:16065)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:16100)
```
Successive Clicks
```
ERROR Error: Host already has a portal attached
    at throwPortalAlreadyAttachedError (portal.js:30)
    at DomPortalOutlet.attach (portal.js:214)
    at OverlayRef.attach (overlay.js:926)
    at MatMenuTrigger.openMenu (menu.js:1175)
    at MatMenuTrigger.toggleMenu (menu.js:1157)
    at MatMenuTrigger._handleClick (menu.js:1501)
    at MatMenuTrigger_click_HostBindingHandler (menu.js:1565)
    at executeListenerWithErrorHandling (core.js:16065)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:16100)
    at HTMLButtonElement.<anonymous> (platform-browser.js:1803)
```

#### What are the steps to reproduce?

1. `ng new myApp --enable-ivy`
2. `cd myApp`
3. `ng add @angular/material@next`
4. Import `MatMenuModule` in `app.module.ts`
5. Add the following to `app.component.html`
```
<button [matMenuTriggerFor]="menu">Menu</button>
<mat-menu #menu="matMenu">
  <button mat-menu-item>Item 1</button>
  <button mat-menu-item>Item 2</button>
</mat-menu>
``` 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am using the latest release candidates of angular 8.  `ng version` yields the following:
```
Angular CLI: 8.0.0-rc.4
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/cdk                      8.0.0-rc.1
@angular/material                 8.0.0-rc.1
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```
Browsers:
* Chrome: 73.0.3683.103 (Official Build) (64-bit)
* Edge: 44.17763.1.0
* Firefox 66.0.5 (64-bit)

#### Is there anything else we should know?
* It appears that the the portal for the menu isn't properly initialized (`menu.js:1175`).
* Everything functions without error when not opting into using ivy.

**Comment by crisbeto** [comment] 2019-05-17 10:24
I wasn't able to reproduce it by building the Material demo app with the latest Ivy source. It's possible that this fails, because whatever code is on npm is slightly outdated.

**Comment by alexzuza** [comment] 2019-05-24 09:14
I was able to reproduce this issue. My environment is:

```
angular 8.0.0-rc.4
@angular/material 8.0.0-rc.1
```

I think the problem here is that ngcc compiler doesn't generate `ngBaseDef` static property for `_MatMenuBase` which is required by `InheritDefinitionFeature`. 
The reason on top level for that is that ngcc handles only decorated classes.

@petebacondarwin @alxhub Could you please take a look at this?

**Comment by abariatti** [comment] 2019-05-29 07:21
+1 I was able to reproduce also with latest production release 

```
    ....
    "@angular/core": "~8.0.0"
    ....
    "@angular/material": "^8.0.0",
```

**Comment by petebacondarwin** [comment] 2019-05-29 08:58
Be aware that 8.0.0 is not to be used for trying out ivy. Instead you should be using the "next" version of Angular - right now the best way to get that is to use a github dependency in your package.json. E.g.

```
"dependencies": {
  "@angular/compier-cli": "https://github.com/angular/compiler-cli-builds",  
   // etc ...
}
```

**Comment by prabhakarreddy1234** [comment] 2019-05-29 14:01
I am facing same issue with MatMenu. Any fix  for this ? I turned off `ivy`.

**Comment by josephperrott** [comment] 2019-06-04 21:54
Closing as duplicate of #16178

**Closed by josephperrott** 2019-06-04 21:54 UTC
