### ISSUE TITLE
bug(input): label  gap

### ISSUE THREAD

**Issue by amirheydari9** [angular/components#20111] opened 2020-07-28 04:17 UTC
hi 
when our direction is rtl and use outline appearance and icon with prefix directive the label get gap 
![code](https://user-images.githubusercontent.com/48507710/88618641-778d5900-d04e-11ea-889f-216014856f92.png)
![demo](https://user-images.githubusercontent.com/48507710/88618652-7e1bd080-d04e-11ea-9f1f-5400e31874f1.png)

**Comment by wagnermaciel** [comment] 2020-07-30 22:29
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment
(this is a canned response)

**Comment by wagnermaciel** [comment] 2020-08-13 22:46
Closing because no clarification was provided.

**Closed by wagnermaciel** 2020-08-13 22:46 UTC
Labels: area: material/input, i18n, needs clarification
