### ISSUE TITLE
MdSelect - md option doesn't fit the select container using dialog + flex layout

### ISSUE THREAD

**Issue by dhuallanca** [angular/components#6655] opened 2017-08-26 19:24 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Options should fit the select container

#### What is the current behavior?

Options container is smaller than select container.
#### What are the steps to reproduce?

https://plnkr.co/edit/yEtylQm2RDDrNGQu9GMI?p=preview

1. open the dialog
2. select an option
result: option container is smaller 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular v4.3
@angular/material 2.00 -beta8
@angular/flex-layout

**Comment by dhuallanca** [comment] 2017-09-28 14:27
Hi @crisbeto, any update of this bug? I want to know when it will be merged :) or maybe you can give a work around.

**Comment by crisbeto** [comment] 2021-08-18 18:30
It looks like the root cause for this issue was resolved a long time ago (https://github.com/angular/components/pull/6658#issuecomment-335253885). Closing.

**Closed by crisbeto** 2021-08-18 18:30 UTC
Labels: P3, area: material/select
