### ISSUE TITLE
Drawer: when position is set to end, focus is not trapped within the Drawer

### ISSUE THREAD

**Issue by naiduraa** [angular/components#28536] opened 2024-02-05 11:53 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When the position of the Drawer is set to end, focus is not getting trapped within the Drawer component when the mode is set to over.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/wxzwex?file=src%2Fapp%2Fsidenav-backdrop-example.html
Steps to reproduce:
1. use keyboard, press enter on the toggle drawer
2. press tab and see the focus is not getting trapped within the drawer

### Expected Behavior

Focus should be trapped

### Actual Behavior

Focus is not getting trapped

### Environment

- Angular: Version 15
- CDK/Material: Version 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOs

**Comment by zarend** [comment] 2024-02-05 18:49
Hello @naiduraa ,

I cannot reproduce this issue on version 17 https://stackblitz.com/edit/z8krdn?file=src%2Fexample%2Fsidenav-backdrop-example.html. Does upgrading to version 17 resolve the issue for you?

Best Regards,

Zach

**Comment by naiduraa** [comment] 2024-02-07 11:59
@zarend - Yes I am unable to reproduce the issue on version 17.
But right now we are using version 15..

Suggestions?

**Comment by zarend** [comment] 2024-02-07 18:46
Hello,

I believe this issue was fixed in #27355. Upgrading would be ideal, but I do know another work-around off the top of my head.

-Zach

**Comment by wagnermaciel** [comment] 2024-02-23 18:38
Closing as this issue is fixed in later versions and we have no intention of back-porting the fix

**Closed by wagnermaciel** 2024-02-23 18:38 UTC
Labels: needs: clarification, needs triage
