### ISSUE TITLE
feat(cdk/scrolling): Wish virtual scrolling would support dynamic item heights

### ISSUE THREAD

**Issue by bmwz110** [angular/components#29025] opened 2024-05-09 01:49 UTC
### Feature Description

`An autosize strategy that works on elements of differing sizes is currently being developed in @angular/cdk-experimental, but it is not ready for production use yet.`
-- from Angular Material Doc

It looks like this is exactly what the developers wanted, hope to see this support soon.

Thanks a lot!

### Use Case

In my project, mat-tables are contained in collapsible divs that are tiled on the page, and the number of such divs, once high, can cause rendering to lag, but the existing virtual scrolling, which requires a fixed height, doesn't seem to handle the situation well.

**Comment by crisbeto** [comment] 2024-05-14 07:25
Duplicate of https://github.com/angular/components/issues/10113.

**Closed by crisbeto** 2024-05-14 07:25 UTC
Labels: feature, needs triage
