### ISSUE TITLE
mat-tab-group removing dynamic content when :leave based animation on parent starts

### ISSUE THREAD

**Issue by johannesjo** [angular/components#14530] opened 2018-12-15 12:33 UTC
#### What is the expected behavior?
The content stays until the animation is finished.

#### What is the current behavior?
As soon as the ngIf value is switched to false, all dynamic tab content is removed.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material-agl2p3

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Tested with material 7.1.0, angular 7.1.0 and typescript 3.1.6 and is reproduceable for all major browsers. Earlier versions have been affected as well (ng ~6).

**Comment by andrewseguin** [comment] 2019-01-16 17:11
Bold move providing a reproduction with the beta version of Material ;)

Your intended behavior seems very similar to using dynamic height on the tabs. Is this what you are looking for?
https://stackblitz.com/edit/angular-rkxtyn?file=app/tab-group-dynamic-height-example.html

**Comment by johannesjo** [comment] 2019-01-16 19:05
I updated the blitz. Same is true for the previous stable and all the versions I used before. Actually I think this is more of an issue with angular/animations module.

**Comment by taraa62** [comment] 2019-02-13 22:32
I have the same removal problem.
In the first tab put the download of the game, the second feature for it, when I turn into the second, and turn back, all the content is recovered but the game has already worked to delete and is loaded again ..
Is there a solution to this problem?

**Comment by crystalogic-ab** [comment] 2019-11-06 13:18
the issue is still showing itself with those configs.
Angular CLI: 8.3.15
Node: 10.15.3
OS: darwin x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.15
@angular-devkit/build-angular     0.803.15
@angular-devkit/build-optimizer   0.803.15
@angular-devkit/build-webpack     0.803.15
@angular-devkit/core              8.3.15
@angular-devkit/schematics        8.3.15
@angular/cdk                      8.2.3
@angular/cli                      8.3.15
@angular/fire                     5.2.1
@angular/material                 8.2.3
@angular/pwa                      0.803.15
@ngtools/webpack                  8.3.15
@schematics/angular               8.3.15
@schematics/update                0.803.15
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

**Comment by johannesjo** [comment] 2019-11-06 14:48
I think this might be related: https://github.com/angular/angular/issues/18310

**Comment by ogrcode** [comment] 2019-12-03 11:03
Angular CLI: 8.3.19
Node: 12.13.0
Angular: 8.2.14

**Comment by johannesjo** [comment] 2019-12-04 10:22
@ogrcode I tried. Doesn't seem to solve the problem:
https://stackblitz.com/edit/angular-material-ps2zjn?file=app/app.component.html

Could you maybe provide an example?

**Comment by ogrcode** [comment] 2019-12-04 11:00
Divide the code with sections. Example:
<section>
...
</section>
<section>
Here the mat-tab-group
</section>

**Comment by johannesjo** [comment] 2019-12-04 11:05
?

**Comment by johannesjo** [comment] 2019-12-07 12:06
@ogrcode thank you for sharing your approach. It does not work however. I put wrapper elements everywhere, doesn't change the element disappearing with the animation. 

Also did you know that you can post code here by using  three backticks ` ` `?
https://guides.github.com/features/mastering-markdown/

**Comment by BoJIbFbI4** [comment] 2020-02-19 12:38
Hi, did you fix this issue? 2 days googling, only you, I and 2 more got this bug

**Comment by johannesjo** [comment] 2020-02-19 14:17
@BoJIbFbI4 I never fixed it and it's still an issue... I think many ignore it because it's only an animation.

**Comment by BoJIbFbI4** [comment] 2020-02-19 14:22
@johannesjo, oh so i got another issue. My mat-tab-content's dynamic content are losing all styles (look like cards with all functional, but 'hidden') after moving to another tab and back.

**Comment by andrewseguin** [comment] 2022-06-29 12:02
Closing since the reproduction no longer works and it seems there may be a workaround by using `preserveContent`: https://material.angular.io/components/tabs/overview#keeping-the-tab-content-inside-the-dom-while-its-off-screen

If this workaround does not work, please feel free to re-open with a latest reproduction.

**Closed by andrewseguin** 2022-06-29 12:02 UTC
Labels: P5, area: material/tabs
