### ISSUE TITLE
Chip click event should bubble 

### ISSUE THREAD

**Issue by dman777** [angular/components#20223] opened 2020-08-06 19:42 UTC
#### Expected Behavior
Allow event to bubble up

In your chip component https://github.com/angular/components/blob/master/src/material/chips/chip.ts#L387 

```html
  _handleClick(event: Event) {
    if (this.disabled) {
      event.preventDefault();
    } else {
      event.stopPropagation();
    }
  }
```

If this component is wrapped by another component, the event will not be caught. It's even more confusing that it does bubble when it is disabled. 

 It doesn't make sense to write extra code to catch the event and emit it in the wrapper. The native element should bubble. Please see Polymer components for reference. 

Also, please keep in mind that webcomponent specs/best practices are downward data through data bindings and upward data through events. If your using the mediator pattern then it's a must that the events bubble.

**Comment by jelbourn** [comment] 2020-08-06 21:51
Duplicate of #19759

**Closed by jelbourn** 2020-08-06 21:51 UTC
Labels: needs triage
