### ISSUE TITLE
Datepicker: Displaying two months when open the date picker calendar

### ISSUE THREAD

**Issue by sivaramalingam** [angular/components#23471] opened 2021-08-27 09:18 UTC
#### Feature Description
Now, the date picker is provided one month in the calendar and should give the options to two months option in the calendar. 

#### Use Case
In the Date picker range component, it will be useful to choose the date range more than one month to user

**Comment by crisbeto** [comment] 2021-09-01 16:00
Duplicate of https://github.com/angular/components/issues/18966.

**Closed by crisbeto** 2021-09-01 16:00 UTC
Labels: feature, needs triage
