### ISSUE TITLE
bug(mat-list): Button in matListItemMeta doesn't work

### ISSUE THREAD

**Issue by jefbarn** [angular/components#26070] opened 2022-11-23 22:44 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v14

### Description

Just trying to reproduce a MatNavList with a Button in the meta section. The button is not clickable.

### Reproduction

https://components-issue-hvmglf.stackblitz.io

### Expected Behavior

https://m2.material.io/components/lists#interactive-demo
After List Text -> Icon

 

### Actual Behavior

Button is not clickable.

### Environment

- Angular: 15
- CDK/Material: new mdc components
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2022-11-24 05:56
Duplicate of https://github.com/angular/components/issues/26011.

**Closed by crisbeto** 2022-11-24 05:56 UTC
Labels: needs triage

**Comment by jefbarn** [comment] 2022-11-30 22:22
Tried the fix in #26011 and it didn't work.

https://components-issue-hvmglf.stackblitz.io

Please reopen.
