### ISSUE TITLE
table matTable unresposive

### ISSUE THREAD

**Issue by b-mi** [angular/components#17281] opened 2019-10-03 13:36 UTC
#### Feature Description

Material schematic generate table component like this:

```
    <table mat-table class="full-width-table" matSort aria-label="Elements">
      <!-- Id Column -->
      <ng-container matColumnDef="id">
        <th mat-header-cell *matHeaderCellDef mat-sort-header>Id</th>
        <td mat-cell *matCellDef="let row" class='has_label_on_mobile'>{{row.id}}</td>
      </ng-container>

```
... with elements table, th, td. So this is official material table component.

There are only one example on whole internet how to make THIS material table responsive and even this example is working partially only. 

#### Use Case

Look at material table documentation - all these tables are unresponsive.
Please add information how to make responsive material table **generated by actual material schematic.**

Thank you.

**Comment by jelbourn** [comment] 2019-10-03 23:07
Duplicate of #8494

**Closed by jelbourn** 2019-10-03 23:07 UTC
Labels: feature
