### ISSUE TITLE
drag and drop with more than 2 vertical stacked lists don't always work

### ISSUE THREAD

**Issue by cmcclellen** [angular/components#18305] opened 2020-01-27 21:17 UTC
#### Reproduction

https://stackblitz.com/edit/angular-gytt6j

Steps to reproduce:
1. Drag an item from Todo down to done2.   
2. Drop the item right in the box of done2
 
 
#### Expected Behavior

Item drops to done2.

#### Actual Behavior

Item drops in the middle (wrong) list.

What seems to happen is that when you move an item out of the todo list, the various elements on the screen move up when the item leaves the drop zone of todo.  However, it appears that the drop zones for done and done2 are still in their original positions.  So, if you try to drop where done2 is now visually, it doesn't drop where its supposed to.  If you drop the item where done2 WAS before everything moved up, it will work.  

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Chrome 79
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

see gif:
![captured (1)](https://user-images.githubusercontent.com/76798/73293962-d888c100-41d2-11ea-8293-fae2ca7e8c95.gif)

edit: added gif

**Comment by cmcclellen** [comment] 2020-01-28 18:31
Also, there is other strange behavior.  If you move a single item from todo down into Done, then drag a 2nd item into done, you can get it to where you absolutely cannot drop it as the first item -- it will only let you drop it as the second item.  You have to drop it, then pick it up again if you want to move it to the top of done.

Very strange.

See attached gif:
![captured](https://user-images.githubusercontent.com/76798/73293761-762fc080-41d2-11ea-8b7c-9504560a6158.gif)

**Comment by crisbeto** [comment] 2020-07-12 09:56
Duplicate of https://github.com/angular/components/issues/14703.

**Closed by crisbeto** 2020-07-12 09:56 UTC
Labels: area: cdk/drag-drop
