### ISSUE TITLE
schematics(tree): Expected property shorthand in object literal

### ISSUE THREAD

**Issue by Splaktar** [angular/components#16086] opened 2019-05-21 23:36 UTC
#### What is the expected behavior?
Running a schematic will not result in a lint failure.

#### What is the current behavior?
Running the `tree` schematic results in this failure:
```js
ERROR: tree.component.ts:58:7 - Expected property shorthand in object literal ('{level}').
```

#### What are the steps to reproduce?
1. `ng g @angular/material:tree tree`

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```js
    "@angular/animations": "~8.0.0-rc.4",
    "@angular/cdk": "~8.0.0-rc.1",
    "@angular/common": "~8.0.0-rc.4",
    "@angular/compiler": "~8.0.0-rc.4",
    "@angular/core": "~8.0.0-rc.4",
    "@angular/forms": "~8.0.0-rc.4",
    "@angular/material": "^8.0.0-rc.1",
    "@angular/platform-browser": "~8.0.0-rc.4",
    "@angular/platform-browser-dynamic": "~8.0.0-rc.4",
    "@angular/router": "~8.0.0-rc.4",
    "hammerjs": "^2.0.8",
```
Plus `codelyzer@5.0.1`
OS: macOS Mojave

#### Is there anything else we should know?
The quick fix seems to change this:
```ts
    return {
      name: node.name,
      type: node.type,
      level: level,
      expandable: !!node.children
    };
```
to this:
```ts
    return {
      name: node.name,
      type: node.type,
      level,
      expandable: !!node.children
    };
```
This appears to be related to the [`object-literal-shorthand`](https://palantir.github.io/tslint/rules/object-literal-shorthand/) rule that is pulled in as part of `"extends": "tslint:recommended",`.

**Comment by devversion** [comment] 2019-05-22 09:03
Can't it also be the other way around where people enforce that shorthand properties are not allowed?

**Comment by Splaktar** [comment] 2019-05-22 17:18
@devversion certainly, but by default we should generate code that aligns with the default tslint rules in a new Angular CLI project.

**Comment by devversion** [comment] 2019-05-22 17:27
@Splaktar That is a fair point, but isn't the rule disabled by default in a new project? see:

https://github.com/angular/angular-cli/commit/2f262bb75f7b072237a5d14d8d10abe64aae2de1#diff-49a88607c73d1bbad7abaa45420d5882R67

**Comment by Splaktar** [comment] 2019-05-22 17:41
It was, but that appears to have been removed at some point (along with a file rename). The [latest version here](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/workspace/files/tslint.json.template) does not include that rule.

**Comment by Splaktar** [comment] 2019-05-22 17:43
Oh here it is, it was removed in https://github.com/angular/angular-cli/commit/a52fc53f0461c506c436b3a0450a2ba2984f8811.

**Comment by devversion** [comment] 2019-05-22 17:57
:+1: in that case sounds reasonable to fix that. Personally I'm surprised that this rule is now enabled by default. The shorthand properties are not always desired (at least in my opinion :smile:)

**Comment by Splaktar** [comment] 2019-05-22 18:01
I agree. I'm not a fan of this being the default, but that's what we have as of Angular CLI `7.3.0`. @alan-agius4 @cexbrayat @kyliau was this intentional?

**Comment by alan-agius4** [comment] 2019-05-22 18:14
@mgechev, was overseeing this. 

That said, maybe we should fix lint by default when generating files? At the moment this is turned off by default and users need to use the `—lint-fix` so to address all or most cases?

**Comment by devversion** [comment] 2019-05-22 18:15
@alan-agius4 AFAIK we can set up the schematic task for this on the Material/CDK side as well.. but not sure if that is a good pattern.

**Comment by alan-agius4** [comment] 2019-05-22 18:25
@devversion, I am not referring to a global lint fix, but rather a lint fix on the generated files. This is currently implemented on all of the CLI schematics, but is off by default.

https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/pipe/index.ts

**Comment by devversion** [comment] 2019-05-22 18:33
@alan-agius4 I was exactly referring to that lint fix which under-the-hood executes the `TslintFixTask`.

See: https://github.com/angular/angular-cli/blob/c319cd054e4344737e274af41f46ef4d8a1c3aab/packages/schematics/angular/utility/lint-fix.ts#L45-L48

We could use that on our end as well but I'm not sure if that is a good pattern.

**Comment by alan-agius4** [comment] 2019-05-22 18:38
Yeah I am not so sure of it either, but that will guarantee that generated code is following the user coding style. As really users are free to change the tslint rules as they see fit.

**Comment by devversion** [comment] 2019-05-24 16:32
Yeah that would be ideal. Agreed. I'm tending to just revisit this after version 8 of Angular Material is released. It sounds like the rule that enforces the shorthand property is not set for _all_ CLI projects and it depends on the version. After version 8 we could have a patch release where we sort this out by running the `TslintFix` task (or whatever we think is a good pattern)

<sup>I could also imagine the CLI just running the fix task after running a generator schematic.. seems like a common case where you want to fix the updated/generated files</sup>

**Comment by devversion** [comment] 2020-05-25 13:55
Closing this in favor of https://github.com/angular/angular-cli/issues/14532. We should update that issue to be more generic. i.e. talk about lint failures caused by schematics. The proposal should be that lint fix runs automatically after any generate schematic. That would also simplify the `--lint-fix` flag for `@schematics/angular` generate schematics.

**Closed** 2020-05-25 13:56 UTC
