### ISSUE TITLE
Request : md-option autoHeight support for <md-select> and/or <md-autocomplete>

### ISSUE THREAD

**Issue by gedclack** [angular/components#4071] opened 2017-04-13 08:25 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
option to choose between fixed height or auto-height to fit `md-option's` contents.

#### What is the current behavior?
`md-option's` height is fixed to 48px

#### What is the use-case or motivation for changing an existing behavior?
its very helpful and descriptive to have an additional text (maybe in smaller font-size) to show more information in the options, rather than having one line of text which only show one information.

#### Currently on :
Angular material 2.0.0-beta.3

**Comment by willshowell** [comment] 2017-04-13 13:10
Possible duplicate of #3883

**Comment by jelbourn** [comment] 2017-04-13 23:24
Potentially doable for autocomplete, would be much more difficult for select.

**Comment by gedclack** [comment] 2017-04-15 03:03
@jelbourn yes it will be great to have it for autocomplete, since many Web Apps will rely heavily on autocomplete to select and filter hundreds of options (and I don't think `md-select` is the right component for that -- since it has no textbox to type)

**Comment by fxck** [comment] 2017-04-16 12:44
@gedclack you are only saying that under the assumption that md-select can no do that, which is certainly can and there is pending (for two months) PR for it already https://github.com/angular/material2/pull/3211 

In fact, I think autocomplete is definitely NOT the right component for *selecting*, that's what *select* is for, as autocomplete doesn't by default (and currently not even with option) enforce the selection to be the one of the list, it simply does the *completion*.

**Comment by gedclack** [comment] 2017-04-17 03:02
@fxck well it will be great then :+1: , I am just assuming with the current version of Material2.

@jelbourn IMHO (and with current version of Material2), if we add md-autocomplete with an option to `force-select` (meaning if no option is selected by the user when onBlur fired, the value will be null, and the textbox should be emptied), and that's also the solution for PR #3211 and #3334

**Comment by PeS82** [comment] 2017-05-24 21:05
I believe having the possibility to use `ng-template` instead of  `md-option` in options list for `md-autocomplete` would be nice. Please?

**Comment by gedclack** [comment] 2017-07-20 02:18
@jelbourn is this resolved in the recent updates?
*haven't touch angular projects for a few weeks now..

**Comment by ksmirnoff** [comment] 2017-10-08 01:23
@jelbourn is there an ETA for providing multiline support for autocomplete suggestion panel?

**Comment by amitport** [comment] 2017-10-23 06:06
I'm using this workaround and it works fine for now:

```
mat-list.<<my-list-class>> ::ng-deep  .mat-list-item-content {
  height: <<new height>>;
}
```

**Comment by fxck** [comment] 2017-10-23 06:09
That's not gonna work. The height is internally hardwired so they can calculate position of the active item upon opening. Overriding the height just in css is going to mess it up.

**Comment by amitport** [comment] 2017-10-23 06:36
@fxck it worked well enough for my use case. That being said, it's definitely not a solution and this issue should be open.

In any case a have another workaround that should play nicer with other css rules:
```
<mat-list-item *ngFor="<<let something of somethings>>">
  <div style="height: <<my-height>>; width: 100%;">
    <span matLine></span><span matLine></span><span matLine></span><span matLine></span>
    <<my-line-content>>
  </div>
</mat-list-item>
```

(material applies 'mat-multi-line' class when there are more than 3 matLine) (IMHO we probably need something like MatFitContent directive on mat-list-item that does the same)

**Comment by fxck** [comment] 2017-10-23 06:38
Also apparently you are talking about mat-list, while this issue is about mat-autocomplete and mat-select.

**Comment by amitport** [comment] 2017-10-23 06:42
@fxck ohh... you're right, I thought I was writing in https://github.com/angular/material2/issues/4114 (which should be re-opened IMO)

**Comment by faelmorais** [comment] 2018-02-09 18:43
Any updates on this function?

**Comment by charlie-elverson** [comment] 2018-06-27 16:12
This takes care of my needs for displaying multiple lines of content in a single mat-option.

`    <mat-option *ngFor="let emp of empDataSource | async" style="height: 90px;" [value]="emp">
      {{emp.searchDisplay}}
      <br> Building: {{emp.thing1}}
      <br> Room: {{emp.thing2}}
    </mat-option>`

**Comment by martin-dmtrv** [comment] 2019-12-20 21:46
Adding this style to `mat-option` appears to solve the problem for us:
`style="min-height: 48px; line-height: normal; height: auto; padding: 10px 20px;"`

So final component should like something like:
```
<mat-form-field class="w-100">
    <input matInput placeholder="Role" aria-label="Role" [matAutocomplete]="auto" [formControl]="roleCtrl">
    <mat-autocomplete #auto="matAutocomplete">
        <mat-option *ngFor="let Role of Roles | async" [value]="Role.name" style="min-height: 48px; line-height: normal; height: auto; padding: 10px 20px;">
            <span>{{Role.name}}</span><br />
            <small class="text-grey">{{Role.description}}</small>
        </mat-option>
    </mat-autocomplete>
</mat-form-field>
```

**Comment by striky1** [comment] 2020-03-20 09:26
I'm using @martin-dmtrv solution but with these styles:

`min-height: 48px; line-height: 1.15; height: auto; padding: 8px 16px; white-space: normal;`

Which more following base Material styles.

**Comment by Jadamae77** [comment] 2020-06-03 20:23
Any updates?

**Comment by gedclack** [comment] 2020-06-15 10:56
for now I'm using similar workaround, adding this css below and using it on my AutoComplete's `<mat-option>`
```
.multiline-auto-complete-options {
	height: auto !important;
	line-height: normal !important;
	padding: 8px 16px !important;
}
```

**Comment by crisbeto** [comment] 2021-04-23 13:51
This is supported in the MDC-based version of `mat-autocomplete` and `mat-select` from `@angular/material-experimental`. I'll close this issue, because porting the feature back to the non-MDC version won't be practical.

**Closed by crisbeto** 2021-04-23 13:51 UTC
Labels: P5, area: material/select, feature
