### ISSUE TITLE
bug(stepper): stepper icons are not aligned properly when direction of html is changed to ltr to rtl and vice versa

### ISSUE THREAD

**Issue by Pradeep12191** [angular/components#24047] opened 2021-12-03 07:51 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

stepper icons are going outside of circle when the direction of html is changed to ltr to rtl and vice versa

### Reproduction

I have created a stackblitz example with stepper and change direction button which will change the html to rtl and ltr
https://stackblitz.com/edit/components-issue-jjfbhm

Steps to reproduce:
1. Enter some values in name input and click next button, and go to next step. 
2. Edit icon in 1st step label will appear.
3. Click on change direction button and observe edit icon
4. Edit icon is misaligned 

Try the same steps in rtl direction and observe the edit icon, Edit icon goes outside of the circle.

Below is the screen shots
 in ltr to rtl direction
![image](https://user-images.githubusercontent.com/10145706/144565930-8634fa37-b3db-44d1-a1c3-9095d43b4a28.png)

in rtl to ltr direction
![image](https://user-images.githubusercontent.com/10145706/144565808-33da0056-c8fc-4771-968c-6356a80643e6.png)

### Expected Behavior

Step icon is going outside of the circle, when direction of html  is changed

### Actual Behavior

Step icons should stay at middle of the circle, when direction of html  is changed

### Environment

- Angular: ^12.2.9
- CDK/Material: ^12.2.9 / ^12.2.9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2021-12-06 14:47
Duplicate of https://github.com/angular/components/issues/24046.

**Closed by crisbeto** 2021-12-06 14:47 UTC
Labels: needs triage
