### ISSUE TITLE
Material Datepicker -> Multiple datepicker formats in single app

### ISSUE THREAD

**Issue by Hugmungus** [angular/components#8676] opened 2017-11-27 22:30 UTC
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behavior?
Ability to support various date-picker formats at the component level (ie dd/MM/YYYY, MM/YYYY, etc)

#### What is the current behavior?
Only one format is supported per app

#### What is the use-case or motivation for changing an existing behavior?
We have different date-pickers for different requirements across our components. We are trying to migrate over to the material datepicker since we're using the Material library across our app, but we need to be able to support multiple display values on single and multiple components.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 5.0.1
Material: 5.0.0-rc0

**Comment by annieyw** [comment] 2021-03-29 21:56
Closing this as a duplicate of https://github.com/angular/components/issues/12035

**Closed by annieyw** 2021-03-29 21:56 UTC
Labels: P4, area: material/datepicker, feature
