### ISSUE TITLE
bug(mat-select): Support for selection through Alpha/Numeric keys broken

### ISSUE THREAD

**Issue by naveedahmed1** [angular/components#21343] opened 2020-12-13 23:38 UTC
#### Reproduction

It seems that the support for skipping to a select item by typing, similar to the native select in MatSelect has been removed in recent updates. This support was added in https://github.com/angular/components/pull/2907

Steps to reproduce:

Open https://stackblitz.com/edit/angular-a9vnec?file=src/app/select-custom-trigger-example.html

Set focus on the select list and quickly press few keys corresponding to a country name for example just type PAK, ideally it should set focus on Pakistan, but you will notice the focus is set to a new list item after each key press and you will end up selecting Kazakhstan from the list.
 
#### Expected Behavior

`mat-select` should support skipping to a select item by typing, a behavior similar to the native select.

It's really helpful especially in case of large lists.

#### Actual Behavior

Although pressing any key takes user to the first element of the list that starts with that key but quickly pressing subsequent key doesn't further filter the selection.

#### Environment

- Angular:11.0.3
- CDK/Material:11.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2020-12-14 16:14
Duplicate of https://github.com/angular/components/issues/21242. It should be resolved in the next minor release. If you don't want to wait until then, you can work around it by passing in a `typeaheadDebounceInterval`.

**Closed by crisbeto** 2020-12-14 16:14 UTC
Labels: needs triage
