### ISSUE TITLE
Mat Focus Indicator breaks mat-icon with font awesome

### ISSUE THREAD

**Issue by raysuelzer** [angular/components#27067] opened 2023-05-09 21:47 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

The following mat-focus-indicator  class is applied to mat-icon in chips. This class sets ::before to display: none. This breaks font libraries such as fontawesome which use the ::before psuedoselector. As it causes the icon to be hidden. Additionally, in other places, this same class appears to remove the content attribute, which is how the icons are displayed. 

<img width="412" alt="image" src="https://github.com/angular/components/assets/1176341/2f9a4838-5cfe-4a5a-889d-a7773642b028">

### Reproduction

Steps to reproduce. 

Create a mat-icon using font awesome, make it a button for example 

    <mat-chip-grid #chipGrid aria-label="Fruit selection">
      <mat-chip-row *ngFor="let fruit of fruits" (removed)="remove(fruit)">
        {{fruit}}
        <button matChipRemove [attr.aria-label]="'remove ' + fruit">
          <mat-icon fontSet="fa" fontIcon="fa-times"></mat-icon>
        </button>
      </mat-chip-row>
    </mat-chip-grid>
    
    See that the class mat-focus-indicator nukes the icon by setting ::before to display: none;

### Expected Behavior

mat-focus-indicator should not set display: none on ::before as it impacts all other ::before psuedoselectors

### Actual Behavior

Not overriding icons which use the ::before psuedoselector

### Environment

- Angular:
- CDK/Material: 16 (and 15)
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by raysuelzer** [comment] 2023-05-09 21:54
There is also a selector which overrides the content attribute thus removing the font... 

https://github.com/angular/components/blame/f0a5008b237d4bde3e8d759ca9e793c164656d7a/src/material/chips/chip.scss#L320-L322

**Comment by crisbeto** [comment] 2023-05-20 04:53
I couldn't reproduce the issue based on the provided markup. Here's what it looks like without focus indicators:
<img width="277" alt="image" src="https://github.com/angular/components/assets/4450522/7b8223bb-6318-43e3-b4a2-2d6c45884577">

And here's what it looks like with focus indicators:
<img width="277" alt="image" src="https://github.com/angular/components/assets/4450522/80cf1f24-5df5-4307-9a70-78df95fb4f4c">

Both appear to be working as expected.

**Comment by raysuelzer** [comment] 2023-07-06 19:49
We fixed this by overriding font-awesome to this. And yes the current scss is setting the display on icons inside of chips to "none" when those icons are using the ::before method and there is a mix of legacy and new components. 

```
 I needed to add display: contents here since 'mat-focus-indicator' was nuking the ::before seletor
by setting the display to none. This is a workaround to get the icons to show up. */
@each $name, $icon in $fa-icons {
  .#{$fa-css-prefix}-#{$name}::before { content: unquote("\"#{ $icon }\""); display: contents; }
}
```

**Comment by mmalerba** [comment] 2023-07-18 17:55
Closing since you've resolved the issue and we were unable to reproduce on our side.

**Closed by mmalerba** 2023-07-18 17:55 UTC
Labels: P3, needs: clarification, area: material/icon
