### ISSUE TITLE
Cannot read property "style" of null _rootElement - cdkDrag (drag-drop.es5.js)

### ISSUE THREAD

**Issue by PastoTreering** [angular/components#15827] opened 2019-04-15 21:19 UTC
#### What is the expected behavior?
Return out of _pointerMove event (and possibly others, but we're logging _pointerMove crashes only at the moment) if _this._rootElement is null or undefined when dragging without _dropContainer.

#### What is the current behavior?
_rootElement can be null in the _pointerMove method within drag-drop.es5.js. Throwing an error on line 312 of drag-drop.es5.js when attempting to access "style" of null (_root._rootElement). Possibly event is continuing to fire when parent node has been destroyed or removed?

#### What are the steps to reproduce?
Unknown, but logs show it is happening mostly on mobile devices (but not exclusively).

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular cdk 7.3.7 +

#### Is there anything else we should know?
Sorry for the lack of reproducibility, but some safety here for the existence of _rootElement wouldn't hurt imo.

**Comment by PastoTreering** [comment] 2019-04-15 21:23
Sentry log:
<img width="724" alt="Screen Shot 2019-04-15 at 2 23 06 PM" src="https://user-images.githubusercontent.com/40899110/56166265-07a6ac80-5f8a-11e9-81d6-bd217d5a8c6c.png">

**Comment by crisbeto** [comment] 2019-04-16 07:00
With the current setup I can see how there could be a case where the root element is undefined at the time the dragging starts. I can add some extra guards around it, but it's also possible that the value that is being passed in just isn't resolving to anything.

**Comment by PastoTreering** [comment] 2019-04-17 01:47
Selector looks right to me, I can't actually reproduce the error through my many tests, but we have a lot of error logs coming in reporting it from our users.

**Comment by crisbeto** [comment] 2019-04-17 05:45
Is there any information on which browser versions are running into the error?

**Comment by PastoTreering** [comment] 2019-04-18 19:31
Here's a broad overview of the usage circumstances. It's mostly on mobile devices, and chrome browser (mobile and desktop), but not exclusively.
![Screen Shot 2019-04-18 at 12 28 44 PM](https://user-images.githubusercontent.com/40899110/56386123-e0441f80-61d5-11e9-8674-8a428d04fd7a.png)

**Comment by eLeontev** [comment] 2019-04-22 14:12
Looks like I faced to the same issue. The reason that mentioned is correct. Existed item already was destroyed. 

How to reproduce it: just use any custom virtual scroller (ngx-virtual-scroller) which remove not displayed items due to performance reason.

Does anybody have any common solution to fix it?

**Comment by kernyden** [comment] 2019-05-02 11:13
+1, happens when drag moving event is on but in container u'd deleted any of item on enter event(for instance).

**Closed** 2019-05-13 04:31 UTC
Labels: P3, has pr
