### ISSUE TITLE
Long mat-hints in Form Fields invade other form fields.

### ISSUE THREAD

**Issue by joshvanallen** [angular/components#13485] opened 2018-10-08 00:16 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Prevent mat-hints from invading other inputs. 

#### What is the current behavior?
Currently, mat-input-subscript is position absolute which results in long mat-hints invading other inputs. I believe there were good intentions behind this but not too sure of them.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-rva4vq

Have an mat-hint in a mat-form-field that have at least 300 characters in text. 

#### What is the use-case or motivation for changing an existing behavior?
My use-case is building a dynamic form tool, driven entirely by the users of the system. Their description can be very long because to fill out a field might be very difficult. 

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
From my understanding, besides changing the overall class name from input-container to form-field, this has been part of the style sheet from the beginning.

**Comment by totszwai** [comment] 2020-11-20 20:17
Is there any workaround for this other than nasty CSS hack directly on individual mat-hint component...?

**Comment by Totati** [comment] 2020-11-20 20:39
The same happens with mat-error, we overcome this issue with brief messages and an icon with popup explaining the details.

**Comment by amysorto** [comment] 2022-06-27 19:51
Duplicate of #4580

**Closed by amysorto** 2022-06-27 19:51 UTC
Labels: P5, design, forms, area: material/form-field
