### ISSUE TITLE
bug(mat-icon): mat-icon names are searchable and highlited doing a ctrl + f browser search

### ISSUE THREAD

**Issue by ignaciostellino** [angular/components#23572] opened 2021-09-12 19:04 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/fork/components-issue
- Harnesses: https://stackblitz.com/fork/harness-issue

Steps to reproduce:
1. Do a browser search (ctlr+f) inside a page with mat-icon and search by the name of the icon and it will be highlited
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?
Is there a way to avoid this?

#### Environment

- Angular: 9
- CDK/Material: mat-icon
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2021-09-15 15:53
Duplicate of https://github.com/angular/components/issues/23195.

**Closed by crisbeto** 2021-09-15 15:53 UTC
Labels: needs triage
