### ISSUE TITLE
Unable to remove chips when Talkback is enabled on Android

### ISSUE THREAD

**Issue by gabrielarcos** [angular/components#12351] opened 2018-07-24 20:17 UTC
#### Bug:
Unable to remove chips from chip list when Talkback tool is enabled on Android 7.0 

#### What is the expected behavior?
Should be able to remove chip from chip list by tapping on the remove icon.

#### What is the current behavior?
The chip gets active but no way to remove

#### What are the steps to reproduce?
On the Android device go to Settings -> Accessibility, tap on Talkback and turn it on. Go to Chrome for Android an open the demo site https://material.angular.io/components/chips/overview scroll down to "Chip input example" and try to remove one of the chips

**Comment by Splaktar** [comment] 2021-05-03 17:47
Need to test this against the latest Angular Material and against MDC-based chips.

**Comment by zarend** [comment] 2023-01-12 22:18
Hello @gabrielarcos ,

Thank you for reporting this issue. I believe it has been fixed in v15. Does the issue still happen for you?

Thanks,
Zach

**Comment by amysorto** [comment] 2023-09-14 21:49
Closing this issue due to no recent activity, if this is still an issue please create a new issue with a reproduction.

**Closed by amysorto** 2023-09-14 21:49 UTC
Labels: P2, a11y, needs: clarification, area: material/chips, android
