### ISSUE TITLE
docs: add anchor to reference classes/interfaces/types

### ISSUE THREAD

**Issue by dev054** [angular/components#22815] opened 2021-05-26 18:16 UTC
#### Documentation Feedback

Currently there's no way to see some classes/interfaces/types referenced in some members. For example, I can see [**MatStep#state**](https://material.angular.io/components/stepper/api#MatStep) type is `StepState`, however there's no reference for `StepState` in this page. Instead I can find it in `cdk/stepper` page. To facilitate this, I'd like to see all non-primitive types with an anchor.

Relates to https://github.com/angular/components/issues/20408#issuecomment-849005223.

An example can be found in https://angular.io/api/router/Route#matcher:

![screenshot](https://user-images.githubusercontent.com/28629080/119711953-7972a500-be36-11eb-90ba-1c64e6c72828.png)

**Affected documentation page:**

Many, but you can see the [stepper page](https://material.angular.io/components/stepper/api#MatStep) for reference.

**Comment by jelbourn** [comment] 2021-05-26 19:17
Duplicate of #18414

**Closed by jelbourn** 2021-05-26 19:17 UTC
Labels: docs, needs triage
