### ISSUE TITLE
feature(MatTooltip): Possibility to define current tooltip position

### ISSUE THREAD

**Issue by IrisWight** [angular/components#19527] opened 2020-06-03 14:17 UTC
#### Use Case

When the element with tooltip reaches the viewport border, the tooltip automatically changes its position from the one that was originally set in **matTooltipPosition** input. In case when we add arrow to the tooltip we can’t change the position of it.

Screenshots:
<img width="556" alt="1" src="https://user-images.githubusercontent.com/14252375/83647621-c58d5f80-a5bd-11ea-9f53-a2834b0cc674.png">
<img width="557" alt="2" src="https://user-images.githubusercontent.com/14252375/83647678-d50ca880-a5bd-11ea-887c-ac9051b3c375.png">

Code: [https://stackblitz.com/edit/angular-bgbato](url)
Please add possibility to define current tooltip position so we can link the arrow to it or we’ll appreciate any help with this matter.

**Comment by crisbeto** [comment] 2020-06-03 16:16
Closing as a duplicate of https://github.com/angular/components/issues/15216.

**Closed by crisbeto** 2020-06-03 16:16 UTC
Labels: feature
