### ISSUE TITLE
bug(MATDIALOG): MatDialogConfig.id not working

### ISSUE THREAD

**Issue by diogodomanski** [angular/components#24251] opened 2022-01-21 13:38 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm trying to set custom IDs for MatDialogRef, but it is not working. Any custom ID is being overriden by default strategy (mat-dialog-<sequence>)

### Reproduction

```typescript
// loading-dialog.service.ts

@Injectable()
export class LoadingDialogService
{
    private _sequence: number = 0;
    constructor(private _dialog: MatDialog) { }

    openDialog() {
        const dialogRef = this._dialog.open(LoadingDialogComponent, {
            id: `loading-dialog-${this._sequence++}`
        });
        console.log(dialogRef.id); // mat-dialog-0 instead of loading-dialog-0
    }
}
```

### Expected Behavior

```DialogRef.id``` should contain the value passed in ```id``` property

### Actual Behavior

```DialogRef.id``` value seems to be being ignored and overwritten by default strategy

### Environment

- Angular: 13.1.3
- CDK/Material: 13.1.3
- Browser(s): Brave 1.34.80
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 21.04

**Comment by diogodomanski** [comment] 2022-01-21 17:33
I've debug MatDialog::open() method and realized that this issue is being caused by the following intructions:

```typescript
        // If there is a dialog that is currently animating open, return the MatDialogRef of that dialog
        if (this._dialogAnimatingOpen) {
            return this._lastDialogRef;
        }
```

As I am trying to open a new dialog from another one (inside ngOnInit method) it seems that the MatDialog::open() method is returning the reference for the first opening dialog in both calls.

I put the second call inside a setTimeout() to apply a delay of 1000ms, and the returns of two calls now are different. But that is a terrible workaround.

I hope there would be a more elegant way of managing dialog openings.

**Comment by crisbeto** [comment] 2022-01-22 05:28
Sounds like a duplicate of https://github.com/angular/components/issues/24037 which has a pending fix.

**Closed by crisbeto** 2022-01-22 05:28 UTC
Labels: needs triage
