### ISSUE TITLE
[Tabs] Content sometimes not visible on Edge

### ISSUE THREAD

**Issue by wuchtig** [angular/components#4562] opened 2017-05-15 13:45 UTC
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Tab-Animation should work.

#### What is the current behavior?

After upgrade to 2.0.0-beta.5, tab content sometimes unvisible.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

![15-05-_2017_15-19-40](https://cloud.githubusercontent.com/assets/1224640/26060143/69749608-3984-11e7-92a0-e8df307352b9.gif)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Windows 10
Microsoft Edge

**Comment by willshowell** [comment] 2017-05-15 14:04
Plunker?

**Comment by wuchtig** [comment] 2017-05-15 14:31
step1: open [https://goo.gl/DlHd6U](url)

step2: paste this in `app.component.html`

`<md-tab-group>`
`<md-tab label="Tab 1">Content 1</md-tab>`
`<md-tab label="Tab 2">Content 2</md-tab>`
`</md-tab-group>`

**Comment by willshowell** [comment] 2017-05-15 15:08
http://plnkr.co/edit/cyhvhciWWHpezXnWHkWI?p=preview

Hmm, seems specific to Edge. I can't reproduce in Chrome 58.0 or FF 53.0, but Safari 10.1's animations are weird, so maybe that is related?

![safari tab bug](https://cloud.githubusercontent.com/assets/6475576/26064366/c2eff2c0-395e-11e7-9ec6-a66c382a2aec.gif)
(Safari 10.1)

**Comment by wuchtig** [comment] 2017-05-15 15:29
In Windows 10 + Chrome it works fine. It's specific to MS Edge

**Comment by macjohnny** [comment] 2017-06-14 11:30
could be related to https://github.com/angular/material2/issues/4982

**Comment by macjohnny** [comment] 2017-06-15 05:52
@willshowell concerning your [comment](https://github.com/angular/material2/issues/4562#issuecomment-301504744): this is probably related to a bug in the web-animations-js polyfill, see 
https://github.com/angular/angular/issues/17239#issuecomment-306536861
https://github.com/angular/angular/issues/17239#issuecomment-308269650
https://github.com/web-animations/web-animations-js/issues/144

**Comment by macjohnny** [comment] 2017-06-15 07:49
@wuchtig Here is a plunkr example with the beta.6 version of angular material: http://plnkr.co/edit/0QHzQ4?p=preview
Here is a plunkr example with the latest master version of angular material:
http://plnkr.co/edit/6q3T5L?p=preview

The issue still remains and apparently is not related to https://github.com/angular/material2/issues/4982

**Comment by wuchtig** [comment] 2017-06-15 18:01
This css workaround works for me in 2.0.0-beta.5.

```css
.mat-tab-body-content{
    overflow: unset !important;
}
```

**Comment by dsm0880** [comment] 2017-07-17 20:01
I have found this issue to also be true on Chrome

**Comment by michael-lang** [comment] 2017-08-31 18:40
I notice this problem on Edge only using **2.0.0-beta.10** today.  No problems in IE11 and Chrome for me.

You can also see it on the official demo site, in the "basic tabs" demo:
https://material.angular.io/components/tabs/overview 

I also see the problems @willshowell mentioned with tab animations, on IE11 and Edge.

**Comment by amcdnl** [comment] 2017-09-02 15:46
I was able to reproduce both issues.  Still investigation, finds so far:

I believe the Edge issue is a reflow issue, causing any type of css change like the unset will cause it to resolve itself.

The Safari issue seems related to animations but we aren't using angular animation lib here so its likely unrelated to those angular animation specific bugs.

**Comment by amcdnl** [comment] 2017-09-06 22:33
@matsko - Any thoughts on the safari animation bug?

**Comment by LoopDLoop** [comment] 2018-05-15 12:47
Anyone has a solution? I got this exact problem on chrome version 56.0

**Comment by AshotAleqs** [comment] 2020-04-28 17:00
make sure you have 
`<!DOCTYPE html>`
in index.html file

It resolves all of the problems on edge, connected with the tabs and dialogs.

**Comment by crisbeto** [comment] 2021-12-30 14:06
Closing since we no longer support the legacy version of Edge.

**Closed by crisbeto** 2021-12-30 14:06 UTC
Labels: P3, has pr, area: material/tabs
