### ISSUE TITLE
bug(cdk): Unable to resolve migrations

### ISSUE THREAD

**Issue by bmayen** [angular/components#24862] opened 2022-05-02 14:41 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

^12.0.0

### Description

I have custom schematics that include @angular/cdk in the package.json "packageGroup". When running `ng update my-custom-schematics` I get the following error:

Unable to resolve migrations for package (@angular/cdk).  [Package subpath '././schematics/migration.json' is not defined by "exports" in [project root]/node_modules/@angular/cdk/package.json]

### Reproduction

Steps to reproduce:
1. 
2.

### Expected Behavior

When running `ng update my-custom-schematics` @angular/cdk should run any required migrations without error

### Actual Behavior

Unable to resolve migrations for package (@angular/cdk).  [Package subpath '././schematics/migration.json' is not defined by "exports" in [project root]/node_modules/@angular/cdk/package.json]

### Environment

- Angular: v13
- CDK/Material: v13
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by alan-agius4** [comment] 2022-05-02 17:46
Duplicate of https://github.com/angular/angular-cli/issues/23068

**Closed by alan-agius4** 2022-05-02 17:46 UTC
Labels: needs triage
