### ISSUE TITLE
Stop autofocus of mat-chips after some mat-chip is deleted

### ISSUE THREAD

**Issue by MinhPhuPham** [angular/components#20869] opened 2020-10-23 15:14 UTC
When I delete a certain mat-chip the next one gets focused and after pressing backspace it too gets deleted. I was not able to find anything to stop this behaviour.

Expect: i want when delete chips, it prevent event focus to previous chips and focus to the input element.
Can anyone help me? Thanks so much. 
Link overview: [https://material.angular.io/components/chips/overview](https://material.angular.io/components/chips/overview)

**Comment by crisbeto** [comment] 2020-10-23 15:33
Moving focus to another chip is required for accessibility. If we didn't do it, a screen reader user would lose their position on the page once the focused chip is removed.

**Comment by MinhPhuPham** [comment] 2020-10-24 02:40
so then you can give me a way if I want when deleted chips => press backspace then autofocus to next is broken now and focus to input element?

**Comment by annieyw** [comment] 2020-10-26 21:27
duplicate of https://github.com/angular/components/issues/18659

**Closed by annieyw** 2020-10-26 21:27 UTC
Labels: P5, area: material/chips, troubleshooting
