### ISSUE TITLE
feat(mat-date-picker): Mobile UI Touch - Allow Month / Date Swipe to navigate forward / backward

### ISSUE THREAD

**Issue by antoinecfmws** [angular/components#19757] opened 2020-06-25 12:53 UTC
#### Feature Description

Currently in the new angular 10 material on mobile device, to navigate to a next month or previous month, the only way to do it is by tapping the arrows "<" , ">" .
For mobile devices, can we add the ability to swipe right / swipe left to mimic the exact behavior of tapping the arrows? 

#### Use Case

On mobile devices, it is much more intuitive to use swiping to move from one month to another using the date picker. It would be great if we can add this small feature.

Cheers.

**Comment by jelbourn** [comment] 2020-06-25 16:44
Duplicate of #19464

**Closed by jelbourn** 2020-06-25 16:44 UTC
Labels: feature, needs triage
