### ISSUE TITLE
help(MatSelect): MatSelect .cdk-overlay-pane fixed width with Angular Material 15

### ISSUE THREAD

**Issue by Raphyyy** [angular/components#26336] opened 2022-12-28 12:30 UTC
### What are you trying to do?

I am trying to migrate a large app using Angular Material to v15 and like many of us I have to overwrite some default styles on Angular Material components.

I am facing an issue with the new MatSelect v15. It seems that now the default behavior is to make the overlay-pane use the exact same width as its `mat-select` related component, directly by setting the width to the element (.cdk-overlay-pane) styles.
If the `mat-form-field` or `mat-select` have a small width, the `mat-option` texts get word wrapped and it is pretty ugly :

https://stackblitz.com/edit/angular-sbq67h?file=src/app/select-overview-example.html

Is there any way I could prevent this fixed width on the related `.cdk-overlay-pane` for my `mat-select` component ? 

### What troubleshooting steps have you tried?

Adding `white-space: nowrap;` to `.mat-mdc-option .mdc-list-item__primary-text` prevent the wrapping issue but the `.cdk-overlay-pane` fixed width do not allow any overflow. The @Input `panelClass` can't help because `.cdk-overlay-pane` is a parent.

### Reproduction

Steps to reproduce:
1. https://stackblitz.com/edit/angular-sbq67h?file=src/app/select-overview-example.html
2.

### Environment

- Angular: 15.0.4
- CDK/Material: 15.0.4
- Browser(s): Google Chrome v108
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by tarn2206** [comment] 2022-12-29 01:48
I have a same problem and this is my css override solution

.cdk-overlay-pane:has(.mat-mdc-select-panel) {
    width: auto !important;
}

**Comment by Raphyyy** [comment] 2022-12-29 15:08
@tarn2206 good solution but the `:has` selector is still an experimental selector and it is not fully implemented in all browsers (e.g Firefox) https://caniuse.com/?search=has

**Comment by EliseoPlunker** [comment] 2023-01-12 18:17
Really you can give value to the property "_overlayPanelClass" and then use

```
.width-auto
{
   width:auto;!important
}
```

You can make using a ViewChild
```
  @ViewChild('select',{static:true}) select:MatSelect
  ngOnInit()
  {
    this.select._overlayPanelClass="width-auto"
  }

```
Or even, you create a directive
```
@Directive({
  selector: 'mat-select [auto]'
})
export class SelectWidthAutoDirective {
  @Input('auto') set _(value:string)
  {
    this.matselect._overlayPanelClass=value
  }
  constructor(private matselect:MatSelect){}
}
```
And use like
```
 <mat-select auto="width-auto">
   ...
</mat-select>

```
See [stackblitz](https://stackblitz.com/edit/angular-sbq67h-3ciaez?file=src%2Fapp%2Fselect-overview-example.html,src%2Fstyles.scss,src%2Fapp%2Fselect-overview-example.ts,src%2Fapp%2Fselect-width-auto.directive.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fselect-overview-example.scss)

**Comment by SonicReal** [comment] 2023-03-22 09:06
Thank you for the directive, however, there is a case when the input becomes wider then values, so the dropdown's width becomes smaller than host element. Can we achieve min-width = mat-select width?

**Comment by GabrielBB** [comment] 2023-04-11 12:01
@EliseoPlunker @SonicReal Angular team gave us a way to override [this](https://github.com/angular/components/blob/e2a0b9e941580e83081251889f671a572d62f245/src/material/select/select.ts#L165)

1 - Create CSS Class:

```
.expandable-overlay-panel
{
   width:auto; !important
}
```

2 - Put this on top of your component:

```
providers: [
    {
      provide: MAT_SELECT_CONFIG,
      useValue: { overlayPanelClass: 'expandable-overlay-panel' }
    }
  ],
```

**Comment by bdirito** [comment] 2023-05-08 22:07
A slight improvment on @GabrielBB's approach would be to use `min-width` over `width`. 

The advantage is if you have no long options in your list your options will still extend to the minimum of the trigger label. It is particularly helpful in cases where options are dynamically being generated.  It also allows for the removal of the `!important`.
```
.expandable-overlay-panel
{
   min-width:auto;
}
```

```
providers: [
    {
      provide: MAT_SELECT_CONFIG,
      useValue: { overlayPanelClass: 'expandable-overlay-panel' }
    }
  ],
```

**Comment by crisbeto** [comment] 2023-05-20 08:17
Duplicate of https://github.com/angular/components/issues/26000.

**Closed by crisbeto** 2023-05-20 08:17 UTC
Labels: troubleshooting, needs triage
