### ISSUE TITLE
[Datepicker] Inline mode

### ISSUE THREAD

**Issue by lobo-tuerto** [angular/components#6873] opened 2017-09-06 14:34 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the current behavior?
Right now it only shows as a popup or inside a dialog.
It would be good to be able to render it inside a section or div, and fill up it's parent container.

#### What is the use-case or motivation for changing an existing behavior?
It would be good to have a multipurpose calendar component.

The use case is to have a calendar UI element on the screen, where you can show events for a given month(s), create events, etc.

For this we need to be able to have the calendar always opened, preferably filling up it's parent container. And have a nice API to interact with it.

It would be good enough to be able to use the internal implementation already in place used for the Datepicker component (maybe as part of the CDK?)

#### Is there anything else we should know?

**Comment by lobo-tuerto** [comment] 2017-09-06 14:40
Something akin to: https://fullcalendar.io/

**Comment by willshowell** [comment] 2017-09-06 14:56
I think I remember reading that the team doesn't plan on supporting a scheduling calendar with appointments, etc. However I think `MdCalendar` is exported now (https://github.com/angular/material2/issues/4801) so you can look into using just the calendar and maybe extending it.

**Comment by jelbourn** [comment] 2020-05-25 19:30
Duplicate of #8812

**Closed by jelbourn** 2020-05-25 19:30 UTC
Labels: P3, area: material/datepicker, feature
