### ISSUE TITLE
feat(a11y): Make CdkFocusTrap and other a11y directives/components standalone 

### ISSUE THREAD

**Issue by denisyilmaz** [angular/components#27388] opened 2023-06-30 06:28 UTC
### Feature Description

Currently the full A11yModule has to be loaded for simple CdKTrapFocus feature and others.

Is there any timeline for this kind of refactoring? Or is this not possible with the current implementation of the @angular/cdk package? I can see that there are two PRs untouched since December 2022 for migrating other directives to standalone directives.

### Use Case

A standalone directive would allow attaching CdkTrapFocus to be attached to the `hostDirectives` feature introduced in Angular 15. This would reduce complexity as currently a dynamically attached component (like a context menu) needs an additional inner wrapper div to be able to attach the CdkTrapFocus directive to it.

**Comment by amysorto** [comment] 2023-06-30 22:54
Duplicate of #26036

**Closed by amysorto** 2023-06-30 22:54 UTC
Labels: feature, needs triage
