### ISSUE TITLE
Create a Date Range Picker starting from MatCalendar w 1/2 input/s for selection mechanism

### ISSUE THREAD

**Issue by liviualexandrubobocu** [angular/components#18203] opened 2020-01-17 13:36 UTC
#### Feature Description

Create a Date Range Picker component starting from using 2 MatCalendar components (fromCalendar and toCalendar) and 1/2 <mat-form-field> with inputs of type text to see the selection. MatCalendar is also used in MatDatepicker.
The Component should add the possibility to add a range selection from the 2 MatCalendar components. The range can be shown by changing the [dateClass] property of the 2 MatCalendar components with a computation describing each element from the range in css classes (first, first-only, last, last-only, in-between).
The component would keep a fromSelectedDate and a toSelectedDate, which will be updated both by selecting dates from the MatCalendar by click and from manual input in the two form fields.
Either mat-hint or mat-error should be present to validate range from manual input selection.
The mat-error should be shown via a ErrorStateMatcher for the formGroup and 2 custom validators, one for each formControl (validating the date formats), and one for the formGroup (validating the range).
minDate should be updated for the toCalendar, in order to validate the range visually. (fromDate should always be lesser or equal to toDate)
activeDate should be updated for both fromCalendar and toCalendar to update the current views.
If minDate is set to the toCalendar, minDate needs to be updated as well before activeDate in order to properly select current views, when going in the past in the fromCalendar.
When updating fromSelectedDate, toSelectedDate should be updated as well with the fromSelectedDate value. 
Everytime a date changes from fromCalendar, or toCalendar components, updateTodaysDate() should be called in order to update the state of the calendars.

#### Use Case
Would enable DateRange filtering options on lists in software that is using @angular/material, without creating such components from scratch. Node modules are not desirable in this case, since they tend to update late after the @angular upgrades and they tend to reimplement the calendars from scratch. This component would be done on top of existing MatCalendar, so no compatibility issues would stand for it.

I would like to contribute to this component (create it) since I have implemented this on the CRM software that I am currently working on in my day to day life. It would be a nice feature to have in the community, since lots of people have tried to implement this feature in their own software.
I would also like to contribute to the MatCalendar documentation that is currently under @angular/material website, since it doesn't describe how to use [dateClass] with MatCalendarCellCssClasses, activeDate and how to implement on top of MatCalendar, and not reimplement MatCalendar from scratch as several people tried.

Thanks,

Liviu Alexandru Bobocu

**Comment by crisbeto** [comment] 2020-01-17 14:33
Duplicate of https://github.com/angular/components/issues/4763.

**Closed by crisbeto** 2020-01-17 14:33 UTC
Labels: feature
