### ISSUE TITLE
[Accessibility] Close button presents in chip is not accessible via keyboard

### ISSUE THREAD

**Issue by opozo** [angular/components#11896] opened 2018-06-22 22:01 UTC
#### Bug, feature request, or proposal:

Chip close button is not accessible [1].
[1] https://material.angular.io/components/chips

#### What is the expected behavior?

Chip close button should be reached using keyboard.

#### What is the current behavior?

Close button presents in chip is not reached via keyboard.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

@angular/material: 6.3.0

**Comment by opozo** [comment] 2018-06-22 22:08
#

**Comment by EverettZ** [comment] 2018-10-09 19:04
According to [#11954](https://github.com/angular/material2/pull/11954#issuecomment-400767251) it is intended to be this way. Should this issue be closed?

**Comment by jelbourn** [comment] 2020-11-25 01:36
Duplicate of #15005

**Closed by jelbourn** 2020-11-25 01:36 UTC
Labels: G, P3, a11y, area: material/chips, has pr, needs discussion
