### ISSUE TITLE
feat(mat-color-picker): Built in color picker

### ISSUE THREAD

**Issue by ishanuda** [angular/components#21581] opened 2021-01-14 03:45 UTC
#### Feature Description

Is it possible to develop a color picker as a built in feature in the library.
Some examples are:

[md-color-picker](https://www.uplabs.com/posts/angular-material-color-picker)
[Angular Material Color Picker](https://www.npmjs.com/package/@angular-material-components/color-picker)
[Angular Color Picker](https://www.npmjs.com/package/ngx-color-picker)

#### Use Case

This will enable to use the color picker as a built in feature for developers.

Thank you very much

**Comment by crisbeto** [comment] 2021-01-18 16:52
Duplicate of https://github.com/angular/components/issues/2948.

**Closed by crisbeto** 2021-01-18 16:52 UTC
Labels: feature, needs triage
