### ISSUE TITLE
bug(mat-radio-button): Color attribute in the <mat-radio-button> can't set other mat-variant class except primary, accent & warn.

### ISSUE THREAD

**Issue by IgorKurkov** [angular/components#26781] opened 2023-03-13 16:54 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

In angular 15 we can't set color="success" or color="info" to the `mat-radio-button`

### Reproduction

<mat-radio-group aria-label="Select an option">
  <mat-radio-button value="1" color="primary">Option 1</mat-radio-button>
  <mat-radio-button value="2" color="accent">Option 2</mat-radio-button>
  <mat-radio-button value="3" color="warn">Option 3</mat-radio-button>
  <mat-radio-button value="4" color="success">Option 4</mat-radio-button> // this will not apply mat-success class
</mat-radio-group>

### Expected Behavior

To have ability to setup color with other palette names, like danger, success & setra

### Actual Behavior

didn't apply the needed class

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): windows 11 x64

**Comment by IgorKurkov** [comment] 2023-03-13 16:57
also please take a look here - it also doesn't solved https://github.com/angular/components/issues/24261

some of the fields apply class without any troubles, but here we have also an interface which disallow to apply any other color palettes - it unable to use custom palettes.

**Comment by crisbeto** [comment] 2023-03-15 10:42
Duplicate of https://github.com/angular/components/issues/11888.

**Closed by crisbeto** 2023-03-15 10:42 UTC
Labels: needs triage

**Comment by IgorKurkov** [comment] 2023-03-15 11:40
@crisbeto mat-radio-button issue with interfacing guard and impossible assigning other colors doesn't fully related to #11888, there are no mention of mat-radio, only workarounds how to make variants for mdc-button, which has no interfaces for color directive. Please link this issue or keep open as another one related to theming palette feature requests. Also #11888 locked for github users so I even can't link current one to #11888.

**Comment by crisbeto** [comment] 2023-03-15 11:50
All Material components treat the `color` input in the same way and accept the same set of palettes.

**Comment by IgorKurkov** [comment] 2023-03-16 11:43
For mat-button we have no troubles with setting variants like color="success" or color="info", but if we trying to set color="success" to mat-radio-button in this way we receive an error
```
declare (property) _MatRadioButtonBase.color: ThemePalette
Theme color of the radio button.
error TS2322: Type 'string' is not assignable to type 'ThemePalette'.

12     [color]="color"
        ~~~~~
```
which says that `mat-radio-button` already has type which unable to set other variants to `color` attribute - this is the point of current issue, they treat `color` input not in the same way unfortunately. 
In this way may I ask you to link this issue to #11888 and we need to extend ThemePalette with any other variants or remove it  because it destroys current lib flexibility @crisbeto
