### ISSUE TITLE
Bug matInput

### ISSUE THREAD

**Issue by sefasaid** [angular/components#14022] opened 2018-11-07 13:30 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
when it focused don't unfocus
#### What is the current behavior?
when i touch the mat input it focuses first. But then immediately focus will unfocuses. Here is a gif
https://i.hizliresim.com/nlv4na.gif
It happens only in android device.

#### What are the steps to reproduce?
sorry it is a project and i cant upload;

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/material                 6.4.7

#### Is there anything else we should know?
please help it's important

**Comment by josephperrott** [comment] 2018-11-07 14:33
It looks like the link you provided is not accessible.  Additionally, it is unlikely that we will be able to determine the cause of this from a gif based on the description you provided.  Without being able to make a reproduction of the issue we aren't able to verify if we are able to make a fix to the code.

Can you provide a reproduction in [StackBlitz]( https://goo.gl/wwnhMV).  This will help us to investigate the issue you are seeing.

**Comment by sefasaid** [comment] 2018-11-07 20:12
Sorry for image link
i upload 4 different service
https://ibb.co/mD71kA
https://pasteboard.co/HM6RDlC.gif
https://photoland.io/i/2ZGEWT
https://www.imageupload.co.uk/image/TgL9

i hope you can open one of them

**Comment by jelbourn** [comment] 2019-12-17 01:35
Closing for lack of reproduction

**Closed by jelbourn** 2019-12-17 01:35 UTC
Labels: cannot reproduce
