### ISSUE TITLE
Datepicker with appearance=fill renders wrong in IE11 and Edge

### ISSUE THREAD

**Issue by hblieb** [angular/components#11650] opened 2018-06-04 17:49 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
In IE11 and Edge, Datepicker should render properly when appearance is set to "fill," "standard" or "outline."

#### What is the current behavior?
In IE11 and Edge, Datepicker is significantly taller than it should be. (OK in Chrome)

#### What are the steps to reproduce?
Take the basic datepicker example from Angular material docs, Add appearance="fill" then view in IE11 or Edge.
https://stackblitz.com/edit/angular-8jkfsk?file=app/datepicker-overview-example.html

#### What is the use-case or motivation for changing an existing behavior?
When form fields are side-by-side, this throws off the alignment

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.2, Internet Explorer 11, Microsoft Edge browser.

#### Is there anything else we should know?
Looks good when appearance=legacy

**Comment by crisbeto** [comment] 2018-06-05 10:59
Spent some time looking into this one yesterday, but wasn't able to find a decent cross-browser solution. For future reference, the issue seems to come from the fact that we're using `align-items: baseline` to align the input and the prefix/suffix.

**Comment by jfox459** [comment] 2018-06-21 20:44
It's an issue in Firefox too but the height difference isn't as dramatic as in Edge and IE11.

**Comment by kolinlob** [comment] 2019-04-16 14:49
For me replacing mat-datepicker-toggle with ordinary mat-icon worked in IE and Edge
```html
<mat-form-field appearance="fill">
  <input matInput [matDatepicker]="picker" placeholder="Choose a date">
  <mat-icon matSuffix (click)="picker.open()" style="cursor:pointer; color:#777;">today</mat-icon>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
```

However, I'm not aware about possible downsides of such solution, since I'm quite new to Angular

**Comment by kctang** [comment] 2019-07-14 10:21
This issue should not be closed if Angular Material supports IE 11.

**Comment by kings100** [comment] 2019-10-10 09:48
Adding following lines into styles.css solved this issue for me:

.mat-form-field-flex {
  align-items: center !important;
}

**Comment by Splaktar** [comment] 2020-02-16 05:23
@kctang the issue isn't closed and hasn't been closed 😄

**Comment by kctang** [comment] 2020-02-17 13:17
Ops! Apologies...please ignore my earlier comment. i must have been too stressed trying to get things to work properly on IE11 at that time. 😅

**Comment by abheist** [comment] 2020-06-03 09:23
> Adding following lines into styles.css solved this issue for me:
> 
> .mat-form-field-flex {
> align-items: center !important;
> }

@kings100 are there any side-effects.
If not, you can add a pull request for it.

**Comment by starquake** [comment] 2020-09-01 14:37
This seems to fix the issues. Not sure about side-effects. Will keep my eyes open and report back.

**Comment by lupeportias** [comment] 2020-09-08 14:46
@abheist just don't put another input with a custom prefix in the same form... lol
Chrome looks like this:
![image](https://user-images.githubusercontent.com/7976603/92491567-bfb0a700-f1c8-11ea-97ec-6c073b96a080.png)

in Edge:
![image](https://user-images.githubusercontent.com/7976603/92491655-db1bb200-f1c8-11ea-8bb7-66461a35c4b7.png)

**Comment by omar306** [comment] 2020-09-30 08:41
To apply apperance="fill" style if it not working with attribute 
<mat-form-field class="full-width mat-form-field-appearance-fill">

**Comment by omar306** [comment] 2020-09-30 08:43
To apply apperance="fill" style if it not working with attribute you can add it as a class
**`<mat-form-field apperance="fill" class="full-width mat-form-field-appearance-fill">`**

**Comment by Splaktar** [comment] 2020-09-30 09:01
@omar306 FYI, you spelled appearance wrong in your attribute, that may be why it wasn't working. I've updated your comment above to use the correct spelling.

**Comment by jelbourn** [comment] 2021-07-29 00:16
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.

**Closed by jelbourn** 2021-07-29 00:16 UTC
Labels: P3, area: material/datepicker, edge, ie11, material spec
