### ISSUE TITLE
How to create dual thumb(Start and End) in MatSlider?

### ISSUE THREAD

**Issue by janasathya** [angular/components#15686] opened 2019-04-02 11:58 UTC
#### Please describe the feature you would like to request.

I want dual thumb in MatSlider for filter purpose. For example i want to filter products having rating from 2 to 4.

#### What is the use-case or motivation for this proposal?

I want to filter products having rating from 2 to 4.

#### Is there anything else we should know?

This is for POC purpose.

**Comment by andrewseguin** [comment] 2019-05-06 21:07
Duplicate of https://github.com/angular/components/issues/1331

**Closed by andrewseguin** 2019-05-06 21:07 UTC
