### ISSUE TITLE
help(mat-chips): I'm facing a black border around the chip when i click in the element.

### ISSUE THREAD

**Issue by veronesecoms** [angular/components#20128] opened 2020-07-29 17:30 UTC
#### What are you trying to do?
I'm using mat-basic-chip with custom CSS, but I see a black border around the chip. any help is appreciated
What are you trying to do?
The mat-chip has a funny black border on clicking. I'm not able to figure out what is creating the black border. here is the template and CSS
#### What troubleshooting steps have you tried?
```
<mat-chip-list>
                      <ng-container *ngFor="let opt of question.options">
                        <mat-basic-chip #lbl="matChip" (click)="chipControlOnSelect(question.key,opt.key,fi,fgi, lbl)">
                          {{opt.value}}</mat-basic-chip>
                      </ng-container>
</mat-chip-list>
```
What are you seeing that does not match your expectations? 
![image](https://user-images.githubusercontent.com/32598503/88833030-0eb9f400-d1a8-11ea-9ff9-8815f800e189.png)

**Comment by wagnermaciel** [comment] 2020-07-30 22:05
This issue doesn't have enough information for the team to investigate. Please include:
* A reproduction of the issue (preferably via StackBlitz)
* Any relevant errors and stack traces
* Any relevant details about your build environment
(this is a canned response)

**Comment by wagnermaciel** [comment] 2020-08-13 22:46
Closing because no clarification was provided.

**Closed by wagnermaciel** 2020-08-13 22:46 UTC
Labels: area: material/chips, needs clarification, troubleshooting
