### ISSUE TITLE
Ivy, cdkVirtualFor experimental (for variable height) issue

### ISSUE THREAD

**Issue by whittssg** [angular/components#18852] opened 2020-03-18 02:42 UTC
Has anyone gotten cdkVirtualFor (experemental branch for the dynamic height children) working with angular 9 (ivy enabled)
i get this error on everything that uses it "Can't bind to 'cdkVirtualForOf' since it isn't a known property of 'ng-container'" (same for divs etc).
it worked perfectly well on angular 8

Details:
experemental branch has been updated to version 9.1.3
angular 9 updated to lateset.

app moduled as 

import { ScrollingModule } from '@angular/cdk-experimental/scrolling'; 

and scrollingmodule is in the imports
i wasnt sure whether i could ask experemental stuff on github but wanted to give it a shot.

thanks

**Comment by bozolia** [comment] 2020-03-18 10:30
Same issue

**Comment by crisbeto** [comment] 2020-03-18 13:34
Both our dev app and our unit tests are running which Ivy and aren't showing any errors. It seems like you might not have imported the `ScrollingModule` in the correct place.

**Comment by whittssg** [comment] 2020-03-18 13:47
It works fine for me when i use '@angular/cdk/scrolling' but if i use the experemental branch to get autosize support i get the error i explained above.

**Comment by whittssg** [comment] 2020-03-19 01:18
@crisbeto were the test running on '@angular/cdk/scrolling' or on the experemential branch '@angular/cdk-experimental/scrolling'?

**Comment by devversion** [comment] 2020-05-26 17:19
Hello! At first glance it looks like you just imported the `ScrollingModule` from `cdk-experimental`, but the one for `experimental` has been removed completely? 

Can you please double-check that, or if possible provide a reproduction? I'm closing this in the meanwhile, but we're happy to help if there is more context.

**Closed by devversion** 2020-05-26 17:19 UTC
Labels: needs triage, troubleshooting
