### ISSUE TITLE
FR: Youtube player parameters

### ISSUE THREAD

**Issue by JanKolk** [angular/components#18379] opened 2020-02-04 08:43 UTC
#### Feature Description

Option to set the player parameters that need to be used. See documentation (https://developers.google.com/youtube/player_parameters.html?playerVersion=HTML5#Parameters)

```
new YT.Player(this.playerId, {
            playerVars: { <--- this is missing -->
                playsinline: 1
            },
            videoId: this.id,
            height: '1920px',
            width: '1080px',
            events: {
                'onReady': () => {
                },                
               'onStateChange': (event) => {
                }
            }
        })
```

**Comment by crisbeto** [comment] 2020-02-04 09:27
There's a pending PR for this already: https://github.com/angular/components/pull/17672.

**Comment by devversion** [comment] 2020-05-26 10:36
Closing this as a duplicate of https://github.com/angular/components/issues/19267. Thanks for the issue!

**Closed by devversion** 2020-05-26 10:36 UTC
Labels: feature, needs triage
