### ISSUE TITLE
bug(DatePicker): Cannot pick date when setting [max] input to a getter/method that returns new Date()

### ISSUE THREAD

**Issue by tachojelev** [angular/components#20398] opened 2020-08-24 08:36 UTC
#### Reproduction

https://stackblitz.com/angular/jaapndnmprrv?file=src%2Fapp%2Fdatepicker-min-max-example.ts

Steps to reproduce:
1. Convert the maxDate property to a maxDate getter.
```typescript
export class DatepickerMinMaxExample {
  minDate: Date;
  get maxDate(): Date {
    return new Date();
  }

  constructor() {
    const currentYear = new Date().getFullYear();
    this.minDate = new Date(currentYear - 20, 0, 1);
  }
}
```
2. Open the calendar of the datepicker and try picking a day.
 
 
#### Expected Behavior

The date is successfully picked and the calendar is closed.

#### Actual Behavior

Nothing happens and the calendar remains opened.

#### Environment

- Angular: 10.0.0
- CDK/Material: 10.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  All

**Comment by crisbeto** [comment] 2020-08-24 08:39
Duplicate of https://github.com/angular/components/issues/19907.

**Closed by crisbeto** 2020-08-24 08:39 UTC
Labels: needs triage
