### ISSUE TITLE
[Tooltip] Prevents normal scrolling

### ISSUE THREAD

**Issue by savaryt** [angular/components#4892] opened 2017-05-31 14:08 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Scrolling should work.

#### What is the current behavior?
Scrolling on a touch device doesn't work if the target of the gesture is an element using the `mdTooltip Directive`.

#### What are the steps to reproduce?
Add the `mdTooltip Directive` on any element.
Use a mobile device / emulator to scroll the document, while targeting the element on which you set the directive.
Scrolling doesn't work.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
```
"dependencies": {
    "@angular/animations": "^4.1.2",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.3",
    "@ngrx/router-store": "^1.2.6",
    "@ngrx/store": "^2.2.2",
    "angularfire2": "^4.0.0-rc.0",
    "core-js": "^2.4.1",
    "firebase": "^3.9.0",
    "hammerjs": "^2.0.8",
    "localforage": "^1.5.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  }
```

**Comment by kekel87** [comment] 2017-06-12 09:56
I've got the same problem.
I found a solution by overriding the Hammer configuration class :

`app.module.ts`
```typescript
import { HAMMER_GESTURE_CONFIG } from '@angular/platform-browser'
import { MyGestureConfig } from './config/my-gesture-config';

@NgModule({
	...
	providers: [
		{
			provide: HAMMER_GESTURE_CONFIG,
			useClass: MyGestureConfig
		}
	]
	...
})
```

`my-gesture-config.ts`
```typescript
import { Injectable } from '@angular/core';
import { GestureConfig } from '@angular/material';

@Injectable()
export class MyGestureConfig extends GestureConfig {
    buildHammer(element: HTMLElement) {
        let mc = <HammerManager>super.buildHammer(element);
        
	mc.set({ touchAction: "pan-y" });

        // Your other configurations
        mc.get('swipe').set({ velocity: 0.3, threshold: 10 });

        return mc;
    }
}
```

**Comment by speige** [comment] 2018-01-23 04:19
+1

**Comment by jpduckwo** [comment] 2018-01-30 01:12
@kekel87 thanks for the workaround. It solved it for me too.

**Comment by mackelito** [comment] 2018-05-31 19:03
is this something that will be fixed in a upcomming release? or should we handle it on our own?

**Comment by drullo** [comment] 2018-12-12 13:58
I just started having this problem with Material version 7.1.1 on apps that never had the problem before.  matTooltip is preventing scrolling on matTable data rows from touch devices.

The workaround described above does work for my apps.  But I think this bug needs to be addressed so that a workaround isn't required.

[Here's a simple sample app](https://angular-xhunpx.stackblitz.io)

**Comment by schroedermarius** [comment] 2019-07-19 10:07
Poking this issue, because its still a big problem. You can't have scrolling in responsive layout with mat-table when you also have tooltips on rows.

**Comment by mhmo91** [comment] 2019-08-14 09:41
FYI, the directive ```mat-button``` have the same behaviour too when ripples are enabled

**Comment by CAlex-Wilson** [comment] 2019-09-06 04:23
The workaround solution above does not work as of 8.0.0. The tooltips still prevent touch scrolling on all applicable components. This is a serious issue.

**Comment by jnfaerch** [comment] 2019-12-02 12:29
Just chiming in with the same issue. Should get fixed ASAP

**Comment by Ploppy3** [comment] 2019-12-04 13:17
The workaround provided by @kekel87 is not working anymore since `GestureConfig` is deprecated and will be removed, due to the removal of HammerJs from `@angular/material`.

We need a solution to this problem.

**Comment by linjie997** [comment] 2020-01-21 11:07
I'm running Angular 9.0.0-rc.9 with Material 9.0.0-rc.8.
I can confirm the override configuration can't work anymore.
I think this issue should have an higher priority since it prevents scrolling on all elements with a tooltip

**Comment by matze1234** [comment] 2020-01-27 12:37
I'm currently using this css based work around:
`touch-action: auto !important;`
Does anyone see a major downside of this?

**Comment by Ploppy3** [comment] 2020-01-28 09:25
@matze1234 I don't see any downsides yet

```css
[mattooltip] {
  touch-action: auto !important;
}
```

**Comment by agxs** [comment] 2020-03-06 09:35
In Angular 8.2 the `mattooltip` attribute didn't exist, I had to use `mattooltipposition` instead.

**Comment by bfredo123** [comment] 2020-04-12 19:29
Thanks all for these comments, however none of the [mattooltip] and [mattooltipposition] work for me. Angular 8.3.24, material 8.2.3.

Would you please have any recommendation? 
This issue is really one.

**Comment by linjie997** [comment] 2020-04-14 08:24
As a workaround, you can add a directive to the elements you have this issue with.
My current approach is adding `matRipple` directive to those elements, then declaring in the css with the selector:

```
[matripple] {
  touch-action: auto !important;
}
```

Hope this can help.

**Comment by bfredo123** [comment] 2020-04-14 18:09
@linjie997 Works great, thanks a lot for the prompt answer and the valuable workaround (even though I confess I don't understand how it makes it work, due to my ignorance). Really appreciated.

**Comment by linjie997** [comment] 2020-04-15 08:51
I'm using the directive approach because my elements are simple html tags with the directive, it's easier for me to use the `[matripple]` selector to get all the elements and adding the touch-action style.
You could just add to every element a class and do the same
I.E:
```
<div matTooltip="Bla bla bla" class="tooltip-item">
    Bla bla
</dvi>
```

This should work the same.

```
.tooltip-item {
    touch-action: auto !important;
}
```

**Comment by bfredo123** [comment] 2020-04-16 19:24
Thank you, understood! Will try that. Indeed I guess it might be a bit lighter (I guess an object is created when a directive is used, unlike with a CSS class being mentioned)

**Comment by blidblid** [comment] 2020-05-26 21:38
Another fix is to simply turn off [touch gestures](https://material.angular.io/components/tooltip/api#MatTooltip) for tooltip. Note that this will make tooltip unreachable on touch devices.

```
import { MAT_TOOLTIP_DEFAULT_OPTIONS } from '@angular/material/tooltip';

@NgModule({
  providers: [
    { provide: MAT_TOOLTIP_DEFAULT_OPTIONS, useValue: { showDelay: 250, hideDelay: 0, touchGestures: 'off' } }
  ]
})
export class MaterialOverrideModule { }
```

**Comment by ChelloApps** [comment] 2020-05-30 10:32
I'm using Angular 9 with following versions: -

    "@angular/animations": "~9.1.9",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "~9.1.9",
    "@angular/compiler": "~9.1.9",
    "@angular/core": "~9.1.9",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.1.9",
    "@angular/material": "^9.2.0",
    "@angular/material-moment-adapter": "^9.2.0",
    "@angular/platform-browser": "~9.1.9",
    "@angular/platform-browser-dynamic": "~9.1.9",
    "@angular/router": "~9.1.9",

and none of these solutions work for me, I haven't tried the Hammer.js

**Comment by visurockerr** [comment] 2020-06-11 10:50
this bug should be fixed, its highly useful if it is fixed.

**Comment by bripc** [comment] 2020-06-24 22:33
Jumping off of what @blidblid said...

I recently upgraded a project from Angular 7 to Angular 9, previously having used the HammerJS workaround mentioned on this page and having it break on upgrade. I found another workaround besides adding CSS to all of the elements that have `matTooltip` on them. Angular has a way that you can change the default behavior of tooltips to turn TouchGestures off, even mentioning that they can cause issues [in the docs](https://material.angular.io/components/tooltip/api):
> On touch devices the tooltip directive uses a long press gesture to show and hide, however it can conflict with the native browser gestures. To work around the conflict, Angular Material disables native gestures on the trigger, but that might not be desirable on particular elements (e.g. inputs and draggable elements).

To turn off the touch gestures, which seem to be the problem, you can either set `matTooltipTouchGestures="off"` on the element that has `matTooltip`, or you can change the default Material Tooltip options like so:
```typescript
import {
  MAT_TOOLTIP_DEFAULT_OPTIONS,
  MatTooltipDefaultOptions,
  MatTooltipModule,
} from '@angular/material/tooltip';

// ...

export const matTooltipCustomConfig: MatTooltipDefaultOptions = {
  showDelay: 5,
  hideDelay: 5,
  touchendHideDelay: 5,
  touchGestures: 'off',
};

// ...

@NgModule({
  imports: [
    // ...
    MatTooltipModule,
    // ...
  ],
  providers: [
      { provide: MAT_TOOLTIP_DEFAULT_OPTIONS, useValue: matTooltipCustomConfig },
    ],
  // ...
})
```
This is documented in the Angular Material docs: https://material.angular.io/components/tooltip/overview#changing-the-default-delay-behavior

(I also still have imported hammerjs elsewhere in the application.)

Note: this solution does turn off tooltips for mobile devices.

I'd be glad to hear if this worked for someone else too.

**Comment by Marax** [comment] 2020-07-28 11:42
@bripc Yes, it helped! Thanks.

**Comment by bechtold** [comment] 2020-11-26 13:33
I can confirm the same problem with Angular 10.
The fix by @linjie997 works for us. 

Since we run into issues with Angular Material on mobile quite often we consider moving to Ionic now :-/

**Comment by u053mxn** [comment] 2021-01-27 21:48
This seems to work for me in Angular 10.
But it's important to not this has to go into a css/scss file with **global scope** otherwise it won't work, like the root styles.scss file.

```
.mat-tooltip-trigger {
  touch-action: auto !important;
}
```

**Comment by jelbourn** [comment] 2021-04-02 19:33
Could someone share a StackBlitz of this happening with `matTooltip` in v11+? I would have thought that the issue would go away when we dropped HammerJS from Angular Material

**Comment by linjie997** [comment] 2021-05-05 08:37
@jelbourn here's a minimum reprodution of the issue:
https://stackblitz.com/edit/angular-ylctyk
While the scrolling works normally on the white background, if you try to scroll from the black rectangle which has a tooltip, it does not work.

**Comment by crisbeto** [comment] 2021-07-02 19:57
What browser/device are you seeing the problem on? I just tried against Chrome, Firefox and iOS Safari and they all worked.

**Comment by Ploppy3** [comment] 2021-07-03 07:50
@crisbeto I just tested and it seems to be fixed.

We need more confirmations though.

**Comment by visurockerr** [comment] 2021-07-03 09:07
yes, it has been fixed in the newer version of angular material. (material 11)

**Comment by wagnermaciel** [comment] 2021-08-05 21:54
Closing since this appears to have been fixed

**Closed by wagnermaciel** 2021-08-05 21:54 UTC
Labels: needs clarification, area: material/tooltip

**Comment by EchoBlueIo** [comment] 2021-08-23 07:00
I just loaded this Stackblitz on iPhone 11 (iOS 14.7.1) and dragging from the black square does not work on any of the big browsers (Safari, Chrome, Firefox)

> @jelbourn here's a minimum reprodution of the issue:
> https://stackblitz.com/edit/angular-ylctyk
> While the scrolling works normally on the white background, if you try to scroll from the black rectangle which has a tooltip, it does not work.
