### ISSUE TITLE
Extra drop area is created in the list even if the item is out of list area

### ISSUE THREAD

**Issue by vartikaagrawal411** [angular/components#28333] opened 2023-12-27 06:06 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

![image](https://github.com/angular/components/assets/149461813/a99d162d-78f1-4e81-a433-6b88d19a5c58)
Extra drop area is created in the list even when an item is dragged out of list area.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-cdk-drag-drop-nhvfg7?file=app%2Fcdk-drag-drop-connected-sorting-example.ts,app%2Fcdk-drag-drop-connected-sorting-example.html
Steps to reproduce:
1.  drag an item from todo list to planned item list .

### Expected Behavior

Extra space should not be created if the element is out of list area.

### Actual Behavior

 Even when item is in planned item list area, it is creating an extra space in done list.

### Environment

- Angular-cli: 15.2.8 
- CDK/Material: 15.2.9
- Browser(s): Chrome, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2023-12-27 06:48
This is an issue with how the demo is set up. You can't drag an item from the todo list to the planned list, because the planned list is only connected to the done list. What's happening is that you're moving the item into done, but it's not allowed to go into planned because it hasn't been dropped yet. An item only "belongs" to a list after it has been dropped.

**Comment by vartikaagrawal411** [comment] 2023-12-27 07:46
If I have dragged an item from todo list to planned list , and item is not allowed to be dragged in planned list then expected behavior is item should return to todo list again.. but current behavior is it is getting dropped in done list.

**Comment by crisbeto** [comment] 2023-12-27 07:59
This is working as expected. The problem is that the item might've been dragged over other containers before it got to the current one so it's unclear where it should be restored. 

If you don't want it to end up in the done list, you can ignore the dropped event which will restore the item to the initial container.

**Comment by vartikaagrawal411** [comment] 2023-12-27 11:18
Can you please explain the meaning of _ignoring_ the drop event and also how to do it **selectively**?  If I am understanding it right, you are suggesting to remove ` (cdkDropListDropped)="drop($event)"` 

But If I do so, how can I get the same event for the intended scenario i.e. dragging from _todo_ and dropping over _done_ ?

**Comment by crisbeto** [comment] 2023-12-27 13:06
In the `drop` method you can decide whether or not to move the item when it's dropped. There's a `data` property that you can use to distinguish the lists.

**Comment by dhruvishah122** [comment] 2023-12-27 17:15
I would like to work on this project. pls assign me

**Comment by crisbeto** [comment] 2023-12-27 17:38
Should also be addressed by https://github.com/angular/components/issues/13906.

**Closed** 2023-12-27 17:38 UTC
Labels: needs triage

**Comment by vartikaagrawal411** [comment] 2023-12-28 06:23
My intentions here is not to distinguish the list ,
I want to distinguish below two scenarios,
1. Item is dragged from todo list to done list and released there
2. Item is dragged from todo list to planned list and released there

**Comment by crisbeto** [comment] 2023-12-28 06:38
You can do that using the `cdkDropListData` input on `cdkDropList`. E.g. the todo drop list can be something like `[cdkDropListData]="{name: 'todo', items: todo}"` while the done list would be `[cdkDropListData]="{name: 'done', items: done}"`. Then you can change the `drop` method to something like this:

```
drop(event: CdkDragDrop<{name: string, items: string[]}>) {
  if (event.previousContainer.data.name === 'todo' && event.container.data.name === 'done') {
    // Item was dragged from todo to done.
  }
}
```

**Comment by A-Vashishth** [comment] 2024-01-25 06:49
Hi I was also facing the same issue .. and I wanted to know that is there any way to distinguish between which list the dropped item should go back once the drop is failed, in the above example - from todo-list if we drag item in done-list and do not drop it there .. then we drag it in planned-list and when we drop it there (item will not be added as we have not connected todo-list and planned-list) .. Ideally since it's prev. container was still todo-list (because we never dropped it inside the done-list) then it should go back todo-list.
