### ISSUE TITLE
docs-bug(mat-select): I can't find how to use mat-select-search

### ISSUE THREAD

**Issue by YUHAI0** [angular/components#29347] opened 2024-06-28 02:22 UTC
### Documentation Feedback

I can't find how to use mat-select-search, is it available in mat-select component ?

### Affected documentation page

https://material.angular.io/components/select/overview

**Comment by crisbeto** [comment] 2024-06-28 08:59
Duplicate of https://github.com/angular/components/issues/5697.

**Closed by crisbeto** 2024-06-28 08:59 UTC
Labels: docs, needs triage

**Comment by YUHAI0** [comment] 2024-06-28 11:18
And a question I can use mat-select-search in official angular material ( not ngx-mat-select-search), but I can't find the document in official site document. @crisbeto
