### ISSUE TITLE
Angular Material Datepicker validation error

### ISSUE THREAD

**Issue by moboylegoogle** [angular/components#23097] opened 2021-06-30 20:03 UTC
Validation errors persist on the date-range-selector, even when the date range has been changed to fix the error. It seems like it only checks the same date that caused the error, rather than checking both dates for an update in the validation. 

For example, if I set start_date = '2021-01-05' and then end_date = '2021-01-04'. This correctly gives a validation error. However, I should be able to fix the start_date to fix this Eg. setting start_date = '2021-01-03'. The error persists until I change the end_date.

See screencast: https://screencast.googleplex.com/cast/NTk4ODc5NzU1NDYyMjQ2NHwzMzlmNTE1YS0xOA

**Comment by jonahd-g** [comment] 2021-07-02 18:26
This seems like a duplicate of #21875

**Comment by crisbeto** [comment] 2021-07-02 19:49
Closing as a duplicate of #21875.

**Closed by crisbeto** 2021-07-02 19:49 UTC
Labels: needs triage
