### ISSUE TITLE
Tooltip fails to hide when changing component with component reuse

### ISSUE THREAD

**Issue by prichter98** [angular/components#20076] opened 2020-07-23 08:46 UTC
#### Reproduction
Stackblitz link:
https://stackblitz.com/edit/tooltip-stays-material

#### Steps to reproduce:

1. Have a component that is being reused have a tooltip on a button that navigates to a different component
1. Hover over button to display tooltip
2. Click button

#### Expected Behavior
The page should change and the tooltip should be hidden.

#### Actual Behavior
The tooltip stays visible. Also, when scrolling, after clicking the button and before the new component is loaded, the tooltip is no longer being updated and will stay even when moving the mouse away or scrolling.

#### Additional Information
The same behavior was reproduced with NG-ZORRO (https://github.com/NG-ZORRO/ng-zorro-antd/issues/5604), which makes me believe the issue lies within the overlay cdk.

#### Environment
Angular: 10.0.5 and 9.1.12
CDK: 10.1.0 and 9.2.4
Browser(s): Chrome and Firefox

**Comment by tomicarsk6** [comment] 2020-07-23 14:01
Possible duplicate #11478.

**Comment by jelbourn** [comment] 2020-07-23 22:16
Duplicate of #11478

**Closed by jelbourn** 2020-07-23 22:16 UTC
Labels: needs triage
