### ISSUE TITLE
bug([STEPPER]): [Wrong display of embeded vertical stepper]

### ISSUE THREAD

**Issue by przemo101** [angular/components#19138] opened 2020-04-22 07:12 UTC
#### Reproduction
Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/vertical-stepper-error

Steps to reproduce:
1. Look at displaying of this stepper
Steps 4 and 5 have no content but the shouldn't exists. They are from embeded stepper but are damaged.
Code that reproduce problem:

`
<mat-vertical-stepper>
    <mat-step>1</mat-step>
    <mat-step>2</mat-step>
    <mat-step>
        <mat-vertical-stepper>
            <mat-step>1</mat-step>
            <mat-step>2</mat-step>
        </mat-vertical-stepper>
    </mat-step>
</mat-vertical-stepper>
`

 
 
#### Expected Behavior
There should be steps 4 and 5 on page because they don't exists.
It was correctly on Angular/Material version 8.2..

#### Actual Behavior
I see 5 main steps. But step 4 and 5 come from embeded vertical stepper.  They are without content.

#### Environment

- Angular: 9.0.0
- CDK/Material: 9.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by crisbeto** [comment] 2020-04-22 07:26
Duplicate of https://github.com/angular/components/issues/18448.

**Closed by crisbeto** 2020-04-22 07:26 UTC
Labels: needs triage
