### ISSUE TITLE
CDK drag and drop: add ability to drag item in copy mode without changing initial list

### ISSUE THREAD

**Issue by karazyabko** [angular/components#17638] opened 2019-11-07 10:58 UTC
#### Feature Description

Hi, guys. I would like to propose a small enhancement for copying items from list to list. Currently copying works great, but after item is dragged to another list, initial list removes it from itself and bind it to root element (body tag in my case). But way that I see more logical is to add boolean @Input (let's name it cdkDropListCopyMode) to drop list directive to make it possible to choose conditionally whether you want to move items and leave default behavior or to copy items and avoid removing item from initial list.

#### Use Case

In my project I have list of items (initial list) and sublist constructor (destination list). Initial list is fluid, and if one item from this list is removed, items after this item seek to fill free place one by one, and after you release item it appears in initial list again, and this flickering looks odd.

P.S. I saw your comment in source code that you move the element out at the end of the body and make it hidden, because keeping it in place will throw off the consumer's `:last-child` selectors, but I believe that it shouldn't be a problem as well. Also I've been tracking #13100 until it was automatically closed, but this behavior is still not fixed. If you need help with it, just let me know.

**Comment by maknapp** [comment] 2020-01-10 18:45
This is a duplicate of #13906

**Comment by jelbourn** [comment] 2020-06-26 17:55
Duplicate of #13906

**Closed by jelbourn** 2020-06-26 17:55 UTC
Labels: area: cdk/drag-drop, feature, needs triage
