### ISSUE TITLE
Add better carousel effect

### ISSUE THREAD

**Issue by AyishikD** [angular/components#28427] opened 2024-01-16 08:52 UTC
### Feature Description

I want to add better carousel effect to featured component and guide carousel. Please assign me this issue as I want to contribute towards Angular Material and make its visibility better for other developers

**Comment by crisbeto** [comment] 2024-01-16 11:42
Duplicate of https://github.com/angular/components/issues/24649.

**Closed by crisbeto** 2024-01-16 11:42 UTC
Labels: feature, needs triage
