### ISSUE TITLE
Add spinner to mat-button

### ISSUE THREAD

**Issue by jpike88** [angular/components#15982] opened 2019-05-09 08:52 UTC
#### Please describe the feature you would like to request.
mat-button clicks often involve an asynchronous operation. Adding a progress spinner or some sort of 'waiting' function makes sense. Disabling the button isn't good enough as it can appear broken to a user.

#### What is the use-case or motivation for this proposal?
Sometimes async operations can involve a few seconds or more as the server is doing something. Users need a visual cue that they should be waiting.

**Comment by andreElrico** [comment] 2019-05-09 11:57
Cant you add a spinner into the button and disable clicking the button via css?

**Comment by andrewseguin** [comment] 2019-05-09 16:39
I don't suspect this will be on the roadmap for a while, but in the meantime you should be able to set this up  by overlaying the button with a spinner like @andreElrico suggested

Here's an example of this: https://stackblitz.com/edit/angular-k5a64z?file=app/button-overview-example.ts

**Comment by simeyla** [comment] 2019-08-18 23:56
Shame this won't be done for a while - especially since it's [part of the material spec](https://material.io/design/components/progress-indicators.html#circular-progress-indicators).

This project does it very nicely, but 'native' support would be great.

https://github.com/michaeldoye/mat-progress-buttons
Demo: https://mat-progress-buttons.firebaseapp.com/home

For simple 'Save' functionality these are a very nice touch.

**Comment by Flameforge** [comment] 2020-01-16 16:35
> Shame this won't be done for a while - especially since it's [part of the material spec](https://material.io/design/components/progress-indicators.html#circular-progress-indicators).
> 
> This project does it very nicely, but 'native' support would be great.
> 
> https://github.com/michaeldoye/mat-progress-buttons
> Demo: https://mat-progress-buttons.firebaseapp.com/home
> 
> For simple 'Save' functionality these are a very nice touch.

It does not support static i18n tags, and it has a lot of open issues still.

This MUST be supported natively, as a state of a button.

**Comment by andreElrico** [comment] 2020-01-17 05:31
@simeyla why should the Material team waste time when you can simply combine the two components yourself?
There is so much important stuff to do.

The fact its mentioned in the specs does not mean it needs to be implemented by the mat-team. Its a guide how things should look and feel. Everything the mat-team builds should meet the specs requirements.

**Comment by andreElrico** [comment] 2020-01-17 05:45
@simeyla why should the Material team waste time when you can simply combine the two components yourself?
There is so much important stuff to do.

The fact its mentioned in the specs does not mean it needs to be implemented by the mat-team. Its a guide how things should look and feel. Everything the mat-team builds should meet the specs requirements.

**Comment by simeyla** [comment] 2020-01-17 05:51
@AndreEllrich I'm not insisting on anything. I just said it was a shame. But in answer to your question

- For the same reason I use any library control! And because it's never as simple as just combining two controls
- Because I did the minimum to get it to work!
- They'd do a much better job than I could in handling things like:
   - obscure browser / device issues
   - accessibility
   - animation timing and thresholds 
   - making it with a directive vs. a component (my version below is a component)
   - current and future compatibility with other button directives
   - making it just feel 'right'

As I said a spinner button is a very useful control to have and wouldn't take a huge amount of time for an expert to create.

Anyway here's the version I ended up with - if it helps anyone then great :-)

      <rr-spinner-button [isBusy]="isSaving" buttonStyle="flat" 
                         (click)="saveChanges()">Save</rr-spinner-button>

```
import { ChangeDetectionStrategy, Component, HostBinding, Input } from '@angular/core';

@Component({
    selector: 'rr-spinner-button',

    template: `<button mat-button 

                    [color]="color"
                    
                    [class.mat-flat-button]="buttonStyle == 'flat'"
                    [class.mat-raised-button]="buttonStyle == 'raised'"
                    [class.mat-stroked-button]="buttonStyle == 'stroked'"

                    [class.busy]="isBusy"
                    [disabled]="isDisabled"
                    [type]="type">

                    <div class="content" [class.busy]="isBusy">
                        <ng-content></ng-content>
                    </div>

                    <mat-spinner [mode]="'indeterminate'" 
                                 [diameter]="19" 
                                 [class.busy]="isBusy"></mat-spinner>
               </button>

               `,

    styles: [`  :host 
                {
                    position: relative;
                }

                :host.disabled
                {
                    // outline: 1px solid red;
                    pointer-events: none;
                }

                mat-spinner 
                { 
                    position: absolute;
                    top: 25%;

                    opacity: 0;

                    transition: opacity .3s ease-in-out;
                }

                mat-spinner.busy 
                {
                    opacity: 1;
                }

                .content 
                {
                    opacity: 1;
                    transition: opacity .3s ease-in-out;
                }

                .content.busy 
                {
                    opacity: 0;
                }

                button ::ng-deep .mat-button-wrapper
                {
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }
             `
            ],

    changeDetection: ChangeDetectionStrategy.OnPush
})
export class SpinnerButtonComponent {

    // inspired by https://www.npmjs.com/package/mat-progress-buttons
    constructor() { }

    @Input("isBusy")
    isBusy = false;

    @Input("disabled")
    disabled = false;

    @Input("color")
    color!: string;

    @Input("type")
    type: 'button' | 'submit' = 'button';

    @Input('buttonStyle')
    buttonStyle: 'flat' | 'raised' | 'stroked' = 'flat';

    @HostBinding('class.disabled')
    get isDisabled() 
    {
        return this.isBusy || this.disabled;
    }
}
```
```

**Comment by Flameforge** [comment] 2020-01-17 07:51
Andre,


This is not wasting time, angular components is a bootstrap for applications, and by the 2k downloads weekly that the rogue implementation has you can see there is demand for it.


They also covered this scenario in the material specs because it is a very common use for async activities.


Combining both components is not enough, there is state management, transition, animation. It's alot of hardwork for something that should come out of the box.


Yours,



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=10.0.25&pv=9&source=email_footer_2] On Fri, Jan 17, 2020 at 6:45am, AndreEllrich < notifications@github.com [notifications@github.com] > wrote:
@simeyla [https://github.com/simeyla] why should the Material team waste time when you can simply combine the two components yourself?
There is so much important stuff to do.

The fact its mentioned in the specs does not mean it needs to be implemented by the mat-team. Its a guide how things should look and feel. Everything the mat-team builds should meet the specs requirements.

**Comment by andreElrico** [comment] 2020-01-17 10:14
Hey Simeyla,

nice try: However you are reinventing the wheels here! (which means reimplemting the mat-button api.)
I used a compound component style:

https://stackblitz.com/edit/angular-k5a64z-bfbkuw?file=app%2Fbutton-overview-example.html

```
<app-mat-spinner-btn [loading]="loading">
  <button mat-raised-button (click)="'Something'">Click me!</button>  
</app-mat-spinner-btn>
```
please note:

+ this is angular7 in 8+ you will have to tweak a few things. I think the material import need to be from material/button i believe
+ css can be improved, see if you can avoid important ... but I thinks its okay here!

**Comment by simeyla** [comment] 2020-01-17 17:15
You proved my point which is that the one in the spec looks better than
both of our attempts :)

I did not want a spinner that just faded out the button to grey. I needed
the button contents to disappear so that’s why I choose the way I did it.
Fastest way I could because yes better things to do!

Anyway still hoping one day they’ll add it and save everyone some time.

**Comment by andreElrico** [comment] 2020-01-17 22:09
This can be done very easily with css. If i have time ill update. To be honest I did not look at the specs :D

**Comment by DavidAlfonsoo** [comment] 2020-08-15 06:10
Hi, I found a simple trick 

          <button *ngIf="!this.SpinerC2" class="space-boton" mat-raised-button color="warn" (click)="getTickets()">
            Update Tickets<mat-icon><mat-progress-spinner diameter="20" mode="indeterminate" strokeWidth="11%"> 
            </mat-progress-spinner></mat-icon>
          </button>

Put your mat-progress-spiner in a mat-icon tag. it works for me!

**Comment by jmagaram** [comment] 2021-03-07 07:12
Agree this would be a super-useful addition. I'm having trouble figuring out how to implement something like this. Must be a very common scenario. @DavidAlfonsoo suggestion works but don't want to hardcode a diameter. A couple other solutions here involve hardwiring the spinner diameter which is not a good idea. I may end up using the bar progress instead simply because I can dock it to the top of the panel.

**Comment by jelbourn** [comment] 2021-03-09 23:55
Duplicate of #13667

**Closed by jelbourn** 2021-03-09 23:55 UTC
Labels: P4, area: material/button, area: material/progress-spinner, feature
