### ISSUE TITLE
bug([datepicker]): [ios bug]

### ISSUE THREAD

**Issue by bilibili244434** [angular/components#18863] opened 2020-03-19 07:32 UTC
Steps to reproduce:
1. When I used ios open datepicker component ， the default day will highlight two days (Just happens for iOS)
 2.Please look at picture as follow.

**Comment by bilibili244434** [comment] 2020-03-20 08:10
<img width="324" alt="屏幕快照 2020-03-19 下午3 25 21" src="https://user-images.githubusercontent.com/52740291/77146157-5f686480-6ac5-11ea-9c23-2d9e10c02fcf.png">

**Comment by crisbeto** [comment] 2020-03-20 18:57
I don't see it when I try the docs examples on an iOS 13 device, but I can get something similar if I hold my finger over a date and then move it away. Do you get into that state by interacting with the calendar or is it that way as soon as you open it?

**Comment by bilibili244434** [comment] 2020-03-30 07:06
By interacting. when I change the date many times, sometimes that happens.

**Comment by annieyw** [comment] 2021-03-29 21:44
We're still unable to reproduce this. Can you provide more specific instructions/information? (specific dates, version, ios version etc)

**Comment by zarend** [comment] 2022-04-11 23:20
@bilibili244434 does this issue persist for you?

I cannot reproduce either. We've made bug fixes for the date picker recently and maybe this has already been fixed.

**Comment by zarend** [comment] 2022-06-27 18:04
I am still unable to reproduce this issue on an iOS device. I'll go ahead and close this. If the issue persists please reopen this issue or file a new issue.

https://github.com/angular/components/issues/new/choose

**Closed by zarend** 2022-06-27 18:05 UTC
Labels: P5, cannot reproduce, area: material/datepicker, ios
