### ISSUE TITLE
bug(MatInputHarness): Does not properly set negative value with <input type="number">

### ISSUE THREAD

**Issue by hnuttin** [angular/components#19314] opened 2020-05-11 08:13 UTC
#### Reproduction

https://stackblitz.com/edit/mat-input-harness-negative-issue

Is this related to https://github.com/angular/components/pull/18812 ?

Steps to reproduce:
1. use an html `<input type="number">`
2. set a negative value using the MatInputHarness.setValue('-2')
3. check the value using MatInputHarness.getValue()
4. this value will be positive '2'
 
 
#### Expected Behavior

Value should be set to negative number

#### Actual Behavior

The value has a positive value

#### Environment

- Angular: 9.1.6
- CDK/Material: 9.1.6
- Browser(s): Chrome 81.0.4044.113
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 10.15.4

**Comment by crisbeto** [comment] 2020-05-11 18:31
We decided to rework #18812 and go forward with it. Closing as a duplicate of https://github.com/angular/components/issues/18790.

**Closed by crisbeto** 2020-05-11 18:31 UTC
Labels: needs triage
