### ISSUE TITLE
Incorrect item position when drag item to list above

### ISSUE THREAD

**Issue by volser** [angular/components#15227] opened 2019-02-18 17:22 UTC
If you have multi lists placed vertically and move item from list below to list above, item is positioned incorrectly.
see: http://recordit.co/xnATvWmFvk
Also then move item back to original list, position is detected incorrectly too.

#### What is the expected behavior?
Move item to correct position in list above

#### What is the current behavior?
Incorrect position

#### What are the steps to reproduce?
http://recordit.co/xnATvWmFvk
https://stackblitz.com/edit/stackoverflow-53064302

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
checked on "@angular/cdk": "^7.3.2", angular: 7.2.4

**Comment by volser** [comment] 2019-02-25 12:25
@crisbeto Do you need some info?
`_cacheOwnPosition` call on `cdkDropListEntered` and on `cdkDropListExited` should fix this issue

**Comment by crisbeto** [comment] 2020-07-12 09:37
Duplicate of https://github.com/angular/components/issues/14703.

**Closed by crisbeto** 2020-07-12 09:37 UTC
Labels: area: cdk/drag-drop
