### ISSUE TITLE
bug(MatSelectionList): Ctrl+A does not trigger selectionChange event

### ISSUE THREAD

**Issue by Totati** [angular/components#20575] opened 2020-09-15 16:32 UTC
#### Reproduction

https://stackblitz.com/edit/mat-selection-list-select-deselect-all-no-selection-change-even?file=src/app/list-selection-example.html

Steps to reproduce:
1. Select an option
2. Press ctrl+A
 
#### Expected Behavior

Selecting or deselecting all values with keyboard shortcuts should fire selectionChange event.

#### Actual Behavior

It does not.

#### Environment

- Angular: 10.1.1
- CDK/Material: 10.2.1
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

You can extract the underlying SelectionModel, but it's quite complex when using dynamic template.

Related issue: https://github.com/angular/components/issues/15696

**Comment by jelbourn** [comment] 2020-09-17 22:24
Actually going to mark as a duplicate of  #15696

**Closed by jelbourn** 2020-09-17 22:24 UTC
Labels: P2, area: material/list, help wanted
