### ISSUE TITLE
CDK drag and drop is way too slow in IE and Edge

### ISSUE THREAD

**Issue by vishesh1king** [angular/components#16687] opened 2019-08-05 11:24 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Dragging and dropping must me smother and no lag.

#### What is the current behavior?
CDK drag and drop is way too slow in IE and Edge. only 1 sec after dragging, the placeholder and preview are appearing. Moving across the drop ranges is also lagging. But in Firefox and chrome it works perfect.

I have a loop of large data, 50-100 headers each will act as a drop zone. Each item within this header acts as droppable element. All are placed under cdkDropListGroup. The functionality works perfectly in all browsers. Only the movement of dragged element across these headers are too slow in IE and Edge. Below is the code sample,

```
<div class="col-sm-6 col-sm-6 col-lg-6 right-mapping" cdkDropListGroup>
   <div class="drag-limit"
   ...
   <ul>
     <li *ngFor="let item of itemsToDrop; let ind=index">
       <div cdkDropList
          (cdkDropEntered)="entered($event)"
          [cdkDropListData]="item.children"
          (cdkDropListDropped)="drop($event,item,ind)">
        <ul>
         <li
            *ngFor="let childItem of item.children; let cind=index"
             (cdkDragStarted)="cdkDragStarted($event,childItem, ind, cind)" 
             (cdkDragReleased)="cdkDragReleased($event,ind, cind)"
             cdkDragBoundary=".drag-limit"
             cdkDrag
             vsDragScroll
             [vsDragScrollContainer]="dragLimit">
         </li>
        </ul>
       </div>
     </li>
    </ul>
   ...
  </div>
 </div>
```

When scrolling through the values in a large list the drop zone is not getting detected properly especially after scrolling. Thus i used a package [ngx-drag-scroll](https://github.com/bfwg/ngx-drag-scroll). It was perfect and the drop zone detection was working perfectly. I removed this vsDragScroll and also checked if its causing issue. But still the issue persisted.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 7.3.8
Node: 11.9.0
Angular: 7.2.12
**Browsers**
Chrome: 75.0(works)
Firefox: 68.0.1 (works)
IE: 11.22 (slow)
Edge: 38.14(slow)

**Comment by crisbeto** [comment] 2019-08-05 12:58
I've been testing it against IE and Edge from the start and I haven't noticed any issues so far. It's hard to tell what might be going on in your case purely from the HTML.

**Comment by vishesh1king** [comment] 2019-08-05 13:16
I get that. I tried to open the given todo example in IE and it worked like a charm. But when i do open my listing it is very lagging. There no errors, functionally works perfectly.

Do you have any suggestions on how i can debug it ? I tried almost all ways(silly ways too). Even enabled production mode in angular and verified if it could cause any change.

**Comment by vishesh1king** [comment] 2019-08-06 09:36
@crisbeto Under the assumption that it might be an performance issue with the application. I have changed my polyfills file. Also added service-worker and enabled production mode.

The result is, more improved movement with only negligible lag. I see that it was problem with internal events. The page has many features, though written in different components its not that pretty in IE and Edge. But i think this negligible lag might be because of animation problem with IE/Edge. So, is there any specific polyfills or CSS that i would have missed and will help in animation for IE. Below i mentioned my polyfill file.

```
/***************************************************************************************************
 * BROWSER POLYFILLS
 */

// Add global to window, assigning the value of window itself.
import 'global-shim';

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es7/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es7/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.


/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';


/** ALL Firefox browsers require the following to support `@angular/animation`. **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.
/**
 * Need to import at least one locale-data with intl.
 */
import 'intl/locale-data/jsonp/en';

```

When you were testing against IE and Edge may i know what steps you took if any, to make it smother in IE and edge?

**Comment by crisbeto** [comment] 2019-08-06 09:40
I haven't taken any special steps to make it faster. I usually test it against our dev app which can be run by cloning the repo, running `npm i && npm run dev-app`. It's possible that there's some other work being done in a different part of the app which is slowing it down.

**Comment by crisbeto** [comment] 2020-05-29 18:01
Closing since I wasn't able to reproduce it last time around and there hasn't been any new information for a while.

**Closed by crisbeto** 2020-05-29 18:01 UTC
Labels: area: cdk/drag-drop, cannot reproduce, perf
