### ISSUE TITLE
When using the datepicker and timepicker with reactive forms, the two components do not bind their values correctly.

### ISSUE THREAD

**Issue by phillipadamson** [angular/components#30182] opened 2024-12-13 17:57 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using the datepicker and timepicker together with a single reactive form control, an issue arises where updating one input does not reflect in the other. For instance, if both fields start as null and the user updates the datepicker to today, the timepicker remains null. In this case, I would expect the timepicker to display (select) 12:00 AM. Conversely, if both fields are null and the user selects 12:00 AM from the timepicker, I would expect the datepicker to show today’s date. It is important to note that when using ngModel, the functionality works as intended.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/u7xejkgt?file=src%2Fexample%2Ftimepicker-datepicker-integration-example.html
Steps to reproduce:
1. Select a date from the datepicker or a time from the timepicker. 
2. Notice how the other bound form doesn't display the change.

### Expected Behavior

I would expect the functionality to be the same for reactive forms as it works for ngModel forms. When the user begins at null if they then choose a date or time the change should be reflected on the bound input.

### Actual Behavior

When using reactive forms where the timepicker and datepicker begin at null or undefined if the user clicks a date or time the other bound input isn't updated.

### Environment

- Angular: 19.0.3
- CDK/Material: 19.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by crisbeto** [comment] 2024-12-13 21:11
Duplicate of https://github.com/angular/angular/issues/58522.

**Closed by crisbeto** 2024-12-13 21:11 UTC
Labels: needs triage
