### ISSUE TITLE
bug(mat-progress-bar): Layout affected by inherited text-align CSS property

### ISSUE THREAD

**Issue by robmv** [angular/components#27651] opened 2023-08-15 02:01 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a `mat-progress-bar` component is placed where it inherits a value of the `text-align` CSS property different than `start`, the progress bat is not properly drawn.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/kmvbnv
Steps to reproduce:
1. Compare the two `mat-progress-bar` on the example .

### Expected Behavior

Both `mat-progress-bar` should look identical.

### Actual Behavior

The top `mat-progress-bar`  isn't properly rendered. The bottom one has a workaround of adding `text-align: start` to the progress bar. The default CSS of `mat-progress-bar` should include that property in order to make it independent of the inherited value.

### Environment

- Angular: 16.2.0
- CDK/Material: 16.2.0
- Browser(s): Firefox, Chrome.
- Operating System: Independent.

**Comment by crisbeto** [comment] 2023-08-15 05:02
Duplicate of https://github.com/angular/components/issues/27613 that has a pending fix going in today.

**Closed by crisbeto** 2023-08-15 05:02 UTC
Labels: needs triage
