### ISSUE TITLE
Material Tabs break VirtualScroll

### ISSUE THREAD

**Issue by exo-pla-net** [angular/components#27229] opened 2023-06-03 09:50 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If you include a material tab in a VirtualScroll, you'll find that the scroll is glitchy. When scrolling down, it warps back to a previous part of the scroll.

### Workaround
Disable pagination as so:

<mat-tab-group [disablePagination]="true">

### Reproduction

Steps to reproduce:
1. Make a VirtualScroll
2. Put a Material Tab in there.

### Expected Behavior

No scroll glitches.

### Actual Behavior

Scroll glitches.

### Environment

Angular CLI: 16.0.0
Node: 18.15.0
Package Manager: npm 9.5.0
OS: win32 x64

Angular: 16.0.0
... animations, cdk, cdk-experimental, cli, common, compiler
... compiler-cli, core, forms, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@angular/fire                   7.6.1
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      4.9.5

**Comment by andrewseguin** [comment] 2023-06-03 17:54
Thanks for reporting this issue. I've closed it for now because it doesn't include enough information to easily reproduce the problem. As per our [contribution guidelines](https://github.com/angular/components/blob/main/CONTRIBUTING.md#-found-an-issue), please provide a link to a REPL reproduction (such as [StackBlitz](https://stackblitz.com/fork/components-issue)), or an explanation of why that is not possible, along with any other information needed to reproduce the issue.

If you could please open a new issue with the requested reproduction information, we will gladly investigate further.

**Closed by andrewseguin** 2023-06-03 17:54 UTC
Labels: needs triage
