### ISSUE TITLE
MatDialog breaks JIT compilation in ivy angular@9.0.0-rc.0

### ISSUE THREAD

**Issue by naturalfreak** [angular/components#17644] opened 2019-11-07 15:49 UTC
JIT compilation breaks when change something in dialog component.

[Reproduction files](https://github.com/angular/components/files/3820428/dialog-bug.zip)

Reproduction instructions:
npm install
npm run start
enter in ~/src/app/dialog/component.ts and change something, after compilation you will receive error in browser.

Node - v12.13.0
npm - 6.12.0
OS - Ubuntu 16.04
angular - 9.0.0-rc.0
material - 9.0.0-rc.0

> Can't bind to 'ngForOf' since it isn't a known property of 'p'.
>   | warnAboutUnknownProperty | @ | core.js:14269
> -- | -- | -- | --
>   | elementPropertyInternal | @ | core.js:14151
>   | ɵɵproperty | @ | core.js:23930
>   | AppComponent_Template | @ | app.component.html:1
>   | executeTemplate | @ | core.js:13684
>   | refreshView | @ | core.js:13543
>   | refreshComponent | @ | core.js:14828
>   | refreshChildComponents | @ | core.js:13280
>   | refreshView | @ | core.js:13597
>   | renderComponentOrTemplate | @ | core.js:13658
>   | tickRootContext | @ | core.js:14992
>   | detectChangesInRootView | @ | core.js:15027
>   | detectChanges | @ | core.js:16555
>   | tick | @ | core.js:42409
>   | _loadComponent | @ | core.js:42460
>   | bootstrap | @ | core.js:42383
>   | (anonymous) | @ | core.js:41978
>   | _moduleDoBootstrap | @ | core.js:41974
>   | (anonymous) | @ | core.js:41929
>   | invoke | @ | zone-evergreen.js:365
>   | onInvoke | @ | core.js:40986
>   | invoke | @ | zone-evergreen.js:364
>   | run | @ | zone-evergreen.js:124
>   | (anonymous) | @ | zone-evergreen.js:851
>   | invokeTask | @ | zone-evergreen.js:400
>   | onInvokeTask | @ | core.js:40964
>   | invokeTask | @ | zone-evergreen.js:399
>   | runTask | @ | zone-evergreen.js:168
>   | drainMicroTaskQueue | @ | zone-evergreen.js:570
>   | Promise.then (async) |   |  
>   | scheduleMicroTask | @ | zone-evergreen.js:553
>   | scheduleTask | @ | zone-evergreen.js:389
>   | scheduleTask | @ | zone-evergreen.js:211
>   | scheduleMicroTask | @ | zone-evergreen.js:231
>   | scheduleResolveOrReject | @ | zone-evergreen.js:841
>   | then | @ | zone-evergreen.js:967
>   | bootstrapModule | @ | core.js:41959
>   | ./src/main.ts | @ | main.ts:11
>   | __webpack_require__ | @ | bootstrap:79
>   | 0 | @ | main.ts:12
>   | __webpack_require__ | @ | bootstrap:79
>   | checkDeferredModules | @ | bootstrap:45
>   | webpackJsonpCallback | @ | bootstrap:32
>   | (anonymous) | @ | main.js:1
>

**Comment by Splaktar** [comment] 2019-11-14 22:49
I'm not able to reproduce this with the repo provided in the ZIP file. I've pushed the changes from the ZIP file plus some minor clean up to https://github.com/Splaktar/mat-dialog-ivy-17644. It looks like this was either fixed by a few minor changes (see my commit) or the latest RC versions.

I'm going to close this, but please feel free to open a PR to the above repo to help provide a reproduction if this is still and issue. Then I will reopen this issue if we can identify a bug.

**Closed by Splaktar** 2019-11-14 22:49 UTC

**Comment by naturalfreak** [comment] 2019-11-15 08:02
With repo above. And with a bigger project it gets worse
![bug](https://user-images.githubusercontent.com/11893674/68926677-c203c980-078e-11ea-8774-010524003f97.gif)

**Comment by Splaktar** [comment] 2019-11-15 08:36
So you have to make a change to the source code while `ng serve` is running in order to see the error?

**Comment by naturalfreak** [comment] 2019-11-15 09:30
Yes

**Comment by Splaktar** [comment] 2019-11-15 10:55
That looks and sounds a lot like these
- https://github.com/angular/angular/issues/32214
- https://github.com/angular/angular-cli/issues/16036
