### ISSUE TITLE
MatChip styles dependes on MatChipList

### ISSUE THREAD

**Issue by ocarreterom** [angular/components#8429] opened 2017-11-14 07:39 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Use MatChip without MatChipList.

#### What is the current behavior?
The styles applied to MatChip depends on MatChipList.

#### What are the steps to reproduce?
Demo: http://plnkr.co/edit/AFbxSJkkeCacnwKEPd2g?p=preview

#### What is the use-case or motivation for changing an existing behavior?
The ability to use MatChip inline with text since MatChipList adds a wrapper with `display: flex`.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
material@5.0.0-rc.0

#### Is there anything else we should know?
There are a weird behavior, so the styles are applied despite of MatChip is not inside MatChipList. Seems that dependes but... not depends 🤔  (show demo).

**Comment by tinayuangao** [comment] 2017-11-14 18:55
This is because `MatChip` is a Directive and not associated with any css file while `MatChipList` is a Component and has `chips.css` in `styleUrls`.

**Comment by molayodecker** [comment] 2019-03-14 16:37
This issue needs to be closed

**Comment by crisbeto** [comment] 2021-12-30 15:22
Duplicate of https://github.com/angular/components/issues/9964.

**Closed by crisbeto** 2021-12-30 15:22 UTC
Labels: P3, area: material/chips, Fixed in MDC
