### ISSUE TITLE
Drag drop- droplist not usable if position changes on drag start

### ISSUE THREAD

**Issue by WJ89** [angular/components#14648] opened 2018-12-27 07:05 UTC
#### What is the expected behavior?
A drop list that can be displayed only while an item is being dragged 

#### What is the current behavior?
.cdk-drop-list-receiving is correctly applied to a droplist container but items dragged onto it are not droppable if the list position has changed due to either changing it's display type or adding an item above that shifts it's position

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-r51wax

**Comment by techy2493** [comment] 2019-01-10 15:40
Your example seems to show the expected behavior. Can you expand on your description of the issue or your example any?

**Comment by crisbeto** [comment] 2020-07-12 09:33
Duplicate of https://github.com/angular/components/issues/14703.

**Closed by crisbeto** 2020-07-12 09:33 UTC
Labels: area: cdk/drag-drop, needs triage
