### ISSUE TITLE
[CdkDropList] Shift click multi-drag-and-drop support

### ISSUE THREAD

**Issue by The224** [angular/components#14702] opened 2019-01-02 17:21 UTC
#### Please describe the feature you would like to request.

It would be great to add "shift and click" functionality to CdkDropList such that multiple items can be selected and drag at once.

#### What is the use-case or motivation for this proposal?

Dragging multiple items from one list to another

**Comment by techy2493** [comment] 2019-01-22 22:01
How would this work if you drug to the same list? Just re-sort the whole group? That might be difficult with the existing drop event.

**Comment by GoGoris** [comment] 2019-03-21 08:35
See #13807 for a more general issue about multi drag and drop support, someone posted an example of how he implemented the dragging of multiple items.

**Comment by crisbeto** [comment] 2020-07-12 09:35
Closing as a duplicate of https://github.com/angular/components/issues/13807.

**Closed by crisbeto** 2020-07-12 09:35 UTC
Labels: P4, area: cdk/drag-drop, feature
