### ISSUE TITLE
Problem with setValue() on mat-select element

### ISSUE THREAD

**Issue by AnibalDuarte** [angular/components#18473] opened 2020-02-12 13:03 UTC
I'm trying to populate some fields on a form based on a select option: some are inputs, some are selects.

My problem is: when the event is triggered the value of any targeted mat-select changes, but the option selected visually disappears (even if there is an option with that value in the list).

I'm tryed to do like that:

```
setTimeout(() => {
              this.resourceForm.controls[target_field].setValue(target_value);
              this.resourceForm.controls[target_field].patchValue(target_value);
}, 10);
```

Where resourceForm is my form, target_field is the target select and target_value is the value that the select must receive.

**Comment by crisbeto** [comment] 2020-02-12 15:07
Can you post a Stackblitz that shows the issue? You can fork one of the examples from the docs that has everything set up.

**Comment by juane1000** [comment] 2020-02-14 22:50
Having a similar issue with MatRadioGroup assigned a FormControl and then setValue() to preselect on of the options. The component doesn't visually update to reflect the new value but a console.log shows that the FormControl does in fact have the new value set.

**Comment by crisbeto** [comment] 2021-05-06 19:35
Closing since there isn't a reproduction example and there hasn't been any clarification in more than a year.

**Closed by crisbeto** 2021-05-06 19:35 UTC
Labels: area: material/select, needs clarification, troubleshooting
