### ISSUE TITLE
bug(Theming): Unable to create a theme with CSS variables after v15 update

### ISSUE THREAD

**Issue by tutkli** [angular/components#26066] opened 2022-11-23 12:01 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

In v14 you could create a Material Theme dinamically by defining the palettes with CSS variables and later assign a color value to those variables. This is no longer possible in v15.

### Reproduction

Check this Stackblitz: https://stackblitz.com/edit/components-issue-ml4ejy

Steps to reproduce:
Define a palette with CSS variables 
Set CSS variable values in component

### Expected Behavior

Ability to assign CSS variables values when defining a palette.

### Actual Behavior

You can't define a theme with CSS variables.

### Environment

- Angular: 15.0.0
- CDK/Material: 15.0.0
- Browser(s): All
- Operating System (e.g. Windows, macOS, Ubuntu): All

**Comment by crisbeto** [comment] 2022-11-23 12:15
Duplicate of #25981.

**Closed by crisbeto** 2022-11-23 12:15 UTC
Labels: needs triage
