### ISSUE TITLE
Full-width slider in RTL mat-dialog-content causes causes horizontal scrolling

### ISSUE THREAD

**Issue by HarelM** [angular/components#6959] opened 2017-09-09 14:48 UTC
#### Bug
wrong translation in rtl mode of a slider thumbnail.

#### What is the expected behavior?
No horizontal scroll

#### What is the current behavior?
horizontal scroll appears in the dialog

#### What are the steps to reproduce?
I can probably be able to reproduce it if I could get a base plunker with dialog+slider+flexbox.

#### What is the use-case or motivation for changing an existing behavior?
Dialog scrolls without a reason

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cli: 1.3.2
node: 6.11.2
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.10
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/flex-layout: 2.0.0-beta.9
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/material: 2.0.0-beta.10
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
#### Is there anything else we should know?
See the element that is being highlighted.
![image](https://user-images.githubusercontent.com/3269297/30241182-de6106c8-9586-11e7-8281-0921d09fe0b6.png)

**Comment by josephperrott** [comment] 2017-09-27 22:43
A reproduction can be found [here](https://stackblitz.com/edit/angular-material2-issue-6959?file=app/dialog.component.html)

**Comment by HarelM** [comment] 2017-12-18 21:20
Any updates on this? I still have this bug in 5.0.0-rc.2... :-(

**Comment by HarelM** [comment] 2018-07-23 22:14
hello???? This bug is open for almost a year now... still exists in latest non beta version...

**Comment by valleyofdawn** [comment] 2018-07-23 22:45
Please prioritize fixing this, an especially annoying bug.

**Comment by HarelM** [comment] 2019-01-24 10:00
In latest version this now moves all the input inside the fields inside the dialog when dragging the slider.
A horrible user experience... :-(((
Any change to take a look at this?

**Comment by HarelM** [comment] 2020-11-08 07:50
Three years now.
Still no answer... :-(( The problem still exists in angular 8...

**Comment by jelbourn** [comment] 2021-07-22 21:10
This is _kind of_ fixed in the new MDC-based slider (currently in `@angular/material-experimental`). I say _kind of_ because there's still some horizonal scroll due to the default margin on the slider, but this margin can be easily set to zero in the app.

**Comment by HarelM** [comment] 2021-07-23 05:09
I've moved to vertical sliders in order to workaround this issue. I wish this was solved sooner...

**Comment by wagnermaciel** [comment] 2022-12-09 20:33
I'll be closing this issue as working as intended. The MDC-based slider inside of a `mat-dialog-content` still causes horizontal scrolling. The margin on the slider is necessary for the desired layout of the component (both according to the latest design spec & for backwards compatibility).

I can understand this being a frustrating experience for devs, so for anyone that runs into this issue with the latest slider, a simple to fix would be to just set the margin to 0 as Jeremy mentioned

```css
.demo-dialog-content .mat-mdc-slider {
    margin: 0;
}
```

**Closed by wagnermaciel** 2022-12-09 20:33 UTC
Labels: P3, i18n, area: material/slider, Fixed in MDC
