### ISSUE TITLE
fr([ALL OF CDK]): [what is 'private' should be 'protected']

### ISSUE THREAD

**Issue by andreElrico** [angular/components#19139] opened 2020-04-22 12:40 UTC
#### Feature Description

#14113

I would like to know your stand on making all private into protected members?

+ The cdk is meant to act as "building blocks" right? So it would be nice to extend those building blocks and change current members.

+ Im fine with protected members not being "protected " :D from breaking changes. At least I can start working without ==> `this['_somePrivateMember']` etc ...

#### Use Case

Always when you want to build cool stuff by extending CDK. To bad there is no material-drag-drop ... esp. drag-drop is completly shut down :-(

#### Current workarounds

+ Complete copy paste the repo and code duplication
+  `this['_somePrivateMember']` madness.

**Comment by crisbeto** [comment] 2022-06-29 09:14
Duplicate of #6264.

**Closed by crisbeto** 2022-06-29 09:14 UTC
Labels: feature, P5, needs discussion, area: many
