### ISSUE TITLE
bug(select): Options panel positioning does not work

### ISSUE THREAD

**Issue by fkolar** [angular/components#19620] opened 2020-06-12 08:17 UTC
#### Reproduction

Steps to reproduce:
1. here is the repo to show the problem  
     -  npm install, ng serve
2. Once you open up browser scroll down so you force select to open towards up

![Screen Shot 2020-06-12 at 10 10 05 AM](https://user-images.githubusercontent.com/17149942/84480467-e8420700-ac94-11ea-8b49-9aec163b364e.png)

3. select should open normally
4. scroll down in the option panel and select last item `Tom1ato`
5. Open up the select again and the overlay panel is completly off. 
![Screen Shot 2020-06-12 at 10 11 27 AM](https://user-images.githubusercontent.com/17149942/84480599-16bfe200-ac95-11ea-8a35-1c2e0e935621.png)

 
 
#### Expected Behavior

What behavior were you expecting to see?

I would like to maintain the behavior when you initially opened up the select. Overlay should stay on the same possition and scroll correctly to selected item

#### Actual Behavior

What behavior did you actually see?
Overlay jump all the way up, completly off from triggering select and Does not even scroll to selected item. 

#### Environment
```
Angular CLI: 9.0.7
Node: 12.0.0
OS: darwin x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2
    

```

**Comment by jelbourn** [comment] 2020-06-18 22:01
@fkolar did you mean to include a reproduction here? If so, StackBlitz would be most useful. You can quickly create a StackBlitz from the MatSelect docs: https://material2-dev.firebaseapp.com/select

**Comment by fkolar** [comment] 2020-06-19 06:52
Sorry. Getting old ;-) I though I included this link:

https://github.com/fkolar/matselecttest

**Comment by crisbeto** [comment] 2020-07-12 09:22
Looks like an issue with the logic that tries to position the option over the trigger doesn't work correctly when it's close to the bottom of the screen and the active option is around the middle of the list.

**Comment by amysorto** [comment] 2022-11-02 23:44
When upgrading to the MDC based select component which will be released in v15 soon, the panel repositions correctly for this example

**Closed by amysorto** 2022-11-02 23:44 UTC
Labels: P3, area: material/select, Fixed in MDC
