### ISSUE TITLE
help(mat-radio-button): I can't use `color` attribute in the <mat-radio-button>

### ISSUE THREAD

**Issue by jfan0888** [angular/components#24261] opened 2022-01-24 02:21 UTC
### What are you trying to do?

```
<mat-radio-group aria-label="Select an option">
  <mat-radio-button value="1" color="primary">Option 1</mat-radio-button>
  <mat-radio-button value="2" color="accent">Option 2</mat-radio-button>
  <mat-radio-button value="3" color="warn">Option 3</mat-radio-button>
  <mat-radio-button value="4" color="info">Option 4</mat-radio-button>
</mat-radio-group>
```

I want to create a custom material theme and use `info` theme palette like below.
`<mat-radio-button value="4" color="info">Option 4</mat-radio-button>`

### What troubleshooting steps have you tried?

For the other components like button, toggle, checkbox, I can use color="info" palette.

`<mat-radio-button value="4" color="info">Option 4</mat-radio-button>`

I expect `mat-info` class in the `<mat-radio-button>`, but not working :(

```
<mat-radio-button _ngcontent-csm-c296="" class="mat-radio-button example-radio-button mat-radio-checked" ng-reflect-value="Winter" id="mat-radio-2">
 ...
 ...
</mat-radio-button>
```

### Reproduction

Steps to reproduce:
https://material.angular.io/components/radio/examples
you can add color="info" in the `<mat-radio-button>`
```
<mat-radio-group aria-label="Select an option">
  <mat-radio-button value="1" color="primary">Option 1</mat-radio-button>
  <mat-radio-button value="2" color="accent">Option 2</mat-radio-button>
  <mat-radio-button value="3" color="warn">Option 3</mat-radio-button>
  <mat-radio-button value="4" color="info">Option 4</mat-radio-button>
</mat-radio-group>
```

### Environment

- Angular: v13
- CDK/Material: v13
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by geromegrignon** [comment] 2022-01-24 08:48
While not explicitly indicated in Material Design specs, I don't think such behavior is accepted from the specs as all color references are about the app theme and there is no indication about lone color theming.

This library being an implementation of these specs, a built-in solution can't be added for your use case.

**Comment by Totati** [comment] 2022-01-24 10:35
Duplicate of #11888

**Closed** 2022-01-24 11:15 UTC
Labels: troubleshooting, needs triage

**Comment by jfan0888** [comment] 2022-01-24 15:53
@geromegrignon  Thanks for your reply.

`<button mat-button color="info">Info</button>`
Then you can see **mat-info** class for the button element.


n the API doc, I can see `defaultColor` property for button, checkbox, slider etc, but not for radio button
https://material.angular.io/components/button/api
```
@Input() color: ThemePalette                                 > Theme color palette for the component.
defaultColor: ThemePalette | undefined                 > Default color to fall back to if no value is set.
```

**Comment by jfan0888** [comment] 2022-01-24 16:01
@crisbeto , @jelbourn 

Actually, I can create other color palettes like `info` or `success` and it works properly with button, checkbox, etc.
This issue only appears with the `radio` button.

**Comment by jfan0888** [comment] 2022-01-24 16:17
> Closing as a duplicate of #11888.
@crisbeto  Can you please reconsider this issue? I think it is a different issue though :)

**Comment by crisbeto** [comment] 2022-01-26 11:32
The fact that it works with `info` or `success` is a coincidence, rather than something we explicitly support. We can't support arbitrary colors, because all of our component themes would have to account for them.

**Comment by jfan0888** [comment] 2022-01-26 13:50
@crisbeto , @andrewseguin 

`@use 'sass:map';
@use "sass:meta";
@use "@angular/material" as mat;

@mixin color($config-or-theme, $variants) {

  .mat-checkbox-indeterminate, .mat-checkbox-checked {
    @each $variant, $variant-palette in $variants {
      &.mat-#{$variant} .mat-checkbox-background {
        background-color: mat.get-color-from-palette($variant-palette);
      }
    }
  }

  .mat-checkbox-checked:not(.mat-checkbox-disabled),
  .mat-checkbox:active:not(.mat-checkbox-disabled) {
    @each $variant, $variant-palette in $variants {
      &.mat-#{$variant} .mat-ripple-element {
        background: mat.get-color-from-palette($variant-palette);
      }
    }
  }
}
`

**Comment by crisbeto** [comment] 2022-01-26 14:15
These palettes aren't in the Material Design specification which we need to adhere to though. Also there's nothing stopping you from defining your own `color` directive that accepts any color:

```
@Directive({
  selector: '[color]'
})
class ColorDirective {
  @Input()
  set color(value: string) {
    if (this._color) {
      this._elementRef.nativeElement.classList.remove(`mat-${this._color}`);
    }

    this._color = value;
    this._elementRef.nativeElement.classList.add(`mat-${value}`);
  }
  private _color: string;

  constructor(private _elementRef: ElementRef<HTMLElement>) {}
}
```
