### ISSUE TITLE
bug(mat-slider): Max value not updating correctly when new value is 0

### ISSUE THREAD

**Issue by YSFKBDY** [angular/components#23913] opened 2021-11-06 11:30 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am changing slider's max value in my component while/after doing some works. And it seems it has a problem updating visually when new max value is 0. 

### Reproduction

Steps to reproduce:
1. Define slider like this: `<mat-slider min="0" [displayWith]="displayValue" [max]="maxValue" step="1" [thumbLabel]="true" [tickInterval]="1" [(ngModel)]="sliderValue" (ngModelChange)="changeSliderValue()"></mat-slider>`
2. Default sliderValue is 0, maxValue is 0.
3. Click a button and change maxValue - let's say to 6. Updates slider and ticks correctly.
4. Click another button and change maxValue to 0. Updates slider and ticks incorrectly, shows previous ticks.
5. You can see the same bug here: [https://material.angular.io/components/slider/examples](url)

### Expected Behavior

Updating slider and ticks correctly.

### Actual Behavior

Updated slider and ticks incorrectly.

### Environment

- Angular: 10.2.0
- CDK/Material: 11.0.2
- Browser(s): Chome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 x64

**Comment by jelbourn** [comment] 2021-11-18 22:57
Confirmed that the ticks do not update after setting the max to zero. This actually happens both in the current _and_ MDC-based slider (which is impressive because they're completely different implementations).

**Comment by DMezhenskyi** [comment] 2021-11-30 23:28
Hi! Is anybody working on it? Otherwise I could try to fix it if you don’t mind

**Comment by jelbourn** [comment] 2021-12-09 00:35
@DMezhenskyi Feel free to send a PR

**Comment by lukonik** [comment] 2021-12-27 13:43
@DMezhenskyi PLZ Let me know, if you are still going to work on this issue and I'll close my PR :)

**Comment by lukonik** [comment] 2021-12-27 17:52
Apologize for so many closed PRs had some troubles with source control.

**Comment by DMezhenskyi** [comment] 2021-12-27 20:26
> @DMezhenskyi PLZ Let me know, if you are still going to work on this issue and I'll close my PR :)

Hi @lukonik! I do not mind if your solution eventually will be merged. My fix is ready, however, I can deliver my pr in about 3 weeks when I get back from vacation.

P.s from what I remember in my solution, besides the case you covered in your PR, there is also a method _updateTickIntervalPercent where happens division by zero if min and max values are the same. If it happens, the result of calculation will be “Infinity” which is not a valid css value for the tick’s background-size property, so it is also a cause of wrongly repainted ticks.

**Comment by lukonik** [comment] 2021-12-28 08:32
> > @DMezhenskyi PLZ Let me know, if you are still going to work on this issue and I'll close my PR :)
> 
> Hi @lukonik! If this fix is urgent then I do not mind if your solution eventually will be merged. My fix is ready, however, I can deliver my PR in about 3 weeks when I get back from vacation.
> 
> P.s from what I remember in my solution, besides the case you covered in your PR, there is also a method _updateTickIntervalPercent where happens division by zero if min and max values are the same. If it happens, the result of the calculation will be “Infinity” which is not a valid CSS value for the tick’s background-size property, so it is also a cause of wrongly repainted ticks.

Hey, thx for your reply.
it's not urgent at all, for me at least :). I'll close my PR then and feel free to push your one .

**Closed** 2022-01-28 17:42 UTC
Labels: help wanted, P4, good first issue, area: material/slider
