### ISSUE TITLE
bug(drag-n-drop): Drop position of a draggable element located in a dialog box is calculated incorrectly if the page is scrolled down

### ISSUE THREAD

**Issue by TheLegion** [angular/components#22301] opened 2021-03-20 10:48 UTC
#### Reproduction

https://stackblitz.com/edit/angular-perask

Steps to reproduce:
1. Scroll the page down at least to the top of the input box
2. Press the "Pick one" button
3. Try to drag one of the elements from the list.
 
 
#### Expected Behavior

The "drop preview" of the element is located under cursor.

#### Actual Behavior

The "drop preview" of the element will be higher than the cursor. The lower you scroll the window, the bigger the drag offset will be.

#### Environment

- Angular: 11.1.1
- CDK/Material: 11.1.1
- Browser(s): Google Chrome 89.0.4389.82
- Operating System: Windows 10

#### Reason

DragRef._pointerMove uses method _getPointerPositionOnPage to determine the cursor position relative to viewport, which substracts the current scroll position (received from ViewportRuler) from the current cursor position. The problem is that in dialog windows (or Overlays with GlobalPositionStrategy to be exact) event coordinates are calculated without taking scroll offset into consideration.

**Comment by crisbeto** [comment] 2021-03-22 19:14
Duplicate of https://github.com/angular/components/issues/14280.

**Closed by crisbeto** 2021-03-22 19:14 UTC
Labels: needs triage
