### ISSUE TITLE
Feature Request: Close Sidenav menu on Responsive when using gesture slide/swipe left.

### ISSUE THREAD

**Issue by AsantosCandor** [angular/components#13001] opened 2018-09-06 11:18 UTC
#### What is the expected behavior?
Regarding the material sidenav, right now the current behavior is that we can close the drawer either calling the drawer.close or when backdropClicking. In Responsive mode thre should be a sliding out from the side-nav just like in the GMAIL application. We can either close by backdrop clicking, clicking outside or sliding the menu out. 
 
#### What is the current behavior?
Regarding the material sidenav, right now the current behavior is that we can close the drawer either calling the drawer.close or when backdropClicking/click outside.

#### What are the steps to reproduce?
This is one of the examples provided on the angular material page.

https://stackblitz.com/angular/pdxjaplpmav?file=app%2Fsidenav-disable-close-example.html

#### What is the use-case or motivation for changing an existing behavior?
When building the top-nav menu, or sidenav container that we use as the top-navigator for desktop, and the sidenav for responsive/mobile we have available the clickOutside close, but sliding out of the menu should also be available since it provides a better user experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6, Material 6.4.7

#### Is there anything else we should know?
If anyone has a simple solution for this I am open to it. Since right now the only solution I am getting is using hammer.js for gestures detection and close the drawer.

**Comment by crisbeto** [comment] 2022-06-29 12:37
Sounds like a duplicate of https://github.com/angular/components/issues/5712.

**Closed by crisbeto** 2022-06-29 12:37 UTC
Labels: feature, P5, area: material/sidenav
