### ISSUE TITLE
md-card-actions should align at the container's bottom

### ISSUE THREAD

**Issue by hacknaked** [angular/components#661] opened 2016-06-09 03:45 UTC
Playing with [Puppy Love Demo](https://puppy-love.firebaseapp.com/), if `card-content` have different heights and `card-container` is defined as `row`:

``` css
.card-container {
  display: flex;
  flex-flow: row wrap;
}
```

then, the `md-card-actions` are not aligned at the bottom. Looking in the Angular Material Specs, I could not find what is the "right" behavior in this case, but action buttons not aligned at bottom looks pretty wired.

![screenshot from 2016-06-09 00-31-11](https://cloud.githubusercontent.com/assets/4097945/15918157/532deb94-2dda-11e6-92f8-f2dbbda9af14.png)

**Comment by jelbourn** [comment] 2016-06-10 17:12
@kara thoughts? I'm not sure if this is something the cards should be doing.

**Comment by NCC1701M** [comment] 2016-07-05 17:52
In my opinion @hacknaked is right. It don't look very harmonic if the action position is not the same on each card in one row.

**Comment by gelidus** [comment] 2016-07-06 15:49
Is there any temp fix for this guys?

**Comment by bennyp123** [comment] 2016-07-29 10:48
md-card should be using flex. it's currently set to display:block

**Comment by Kyderman** [comment] 2017-02-15 16:17
Im still having issues with this, the buttons need to be anchored down somehow, also, it would be nice if they can move nicely when the card gets smaller rather than stacking on top of eachother really badly

**Comment by joshdevries** [comment] 2017-03-31 18:11
I was able to fix this by adding flex to md-card-content:
<md-card-content flex>

This pushes the action section to the bottom.

**Comment by spookyvale** [comment] 2017-04-18 08:56
did you find a temp solution for that? 
adding flex to the md-card-content does not fix for me. I'm using flex-layout for the container as
`<div fxLayout='row' fxLayoutWrap fxLayoutGap="10px">`

**Comment by Kyderman** [comment] 2017-04-18 09:03
@spookyvale, I just changed the css for md-card to be using display:flex, with a margin-top on the card-actions

```
.item-card-container {
  display: flex;
  flex-direction: column;
  margin:20px;
}

md-card-actions {
  margin-top:auto;
}
```

**Comment by demetrio812** [comment] 2017-05-19 18:08
I'm still having this issue with the latest version, I think this is important to solve...

**Comment by josehernandezv** [comment] 2017-11-02 06:24
Is there any solution for this?

**Comment by Shrralis** [comment] 2017-11-08 12:00
So, what is the status of this issue? Will it be fixed or any flexible solution?

**Comment by perotom** [comment] 2017-11-17 09:47
Looks especially bad if you got two cards side by side with different content length.

**Comment by EladBezalel** [comment] 2017-11-17 10:05
```html
<mat-card>
  <mat-card-actions align="end">
    ...
  </mat-card-actions>
</mat-card>
```

**Comment by EladBezalel** [comment] 2017-11-17 10:14
I misread the issues.. can you reproduce the issue in stackblitz/plunker/codepen with the latest release?

**Comment by willshowell** [comment] 2017-11-17 14:36
@EladBezalel see this,

https://stackblitz.com/edit/material2-rc0-gt2vww?file=app%2Fapp.component.html

**Comment by EladBezalel** [comment] 2017-11-17 20:27
@willshowell thanks!

This is a [quick fix](https://stackblitz.com/edit/material2-rc0-c1mb7x)

or you can come close with a simple override:
```css
.mat-card {
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
}

.mat-card-content {
  display: flex;
  flex: 1;
}
```

The problem is how card maintain `flex` internally.. we might need to wrap the inner html of a card with a flex container to handle these situations.. (as i did in the stackblitz)
@mmalerba thoughts?

**Comment by jpike88** [comment] 2019-03-19 07:55
I put in loads of effort to move to this library, and after all that effort, I can't even get simple login box to display correctly without hacking around it:

![Screen Shot 2019-03-19 at 2 54 15 pm](https://user-images.githubusercontent.com/9585787/54588927-e0c28c80-4a56-11e9-9e8e-64ab1a508a23.png)

How is this not treated with a higher priority?

**Comment by andrew-landsverk-win** [comment] 2020-08-12 17:16
Hello,

I saw there were some recent label changes to this issue and it's still present in 10.1.2. The workarounds do not seem to be working for me at least. Does anyone have any ideas for pushing these actions down in 2020? :) 

Thanks!

**Comment by tariva** [comment] 2020-08-31 11:42
@andrew-landsverk-win 
possible working solution is to add a class to the mat-card if u are using card header content and foot 
`.card-internals {
  min-height: 200px;
  justify-content: space-between;
  display: flex;
  flex-direction: column;
}`
i you rather want a spacin like this 
header
content 



buttons 
you cant adapt this solution https://stackoverflow.com/questions/29175976/move-single-element-to-the-end-of-a-flex-container
by setting 
`display: flex;
    justify-content: start;
    flex-direction: column;
    flex-wrap: wrap;`
on mat card 
and 
`margin: auto 0 0;`
on the mat card actions

**Comment by parthNJ** [comment] 2022-04-14 03:37
Here is the solution that seems to work for me: 

.card {
  display: flex;
  flex-direction: column;
}

.card_body {
  display: flex;
  flex: 1 0 auto;
  align-items: flex-end;
  justify-content: center;
}

**Closed** 2024-12-18 17:21 UTC
Labels: needs: discussion, P4, material spec, area: material/card
