### ISSUE TITLE
CDK Drag and drop does not work for moving parent elements up or down. 

### ISSUE THREAD

**Issue by sujeet-jaiswara** [angular/components#19936] opened 2020-07-10 14:45 UTC
**Scenario:**
Parent A, B
A has 5 childs A1 to A5
B has 5 childs B1 to B5

Drag and drop works fine when I drag any child element inside A or to B and vice -versa.
When I try to move parent element using drag and drop then the functionality for the child elements stops working.

Screenshot
![image](https://user-images.githubusercontent.com/45264365/87167054-0c235780-c2ea-11ea-893b-d2d6c86f5497.png)

**Comment by crisbeto** [comment] 2020-07-10 15:29
Duplicate of https://github.com/angular/components/issues/16671.

**Closed by crisbeto** 2020-07-10 15:29 UTC
Labels: area: cdk/drag-drop, troubleshooting

**Comment by sujeet-jaiswara** [comment] 2020-07-16 15:41
Thanks
