### ISSUE TITLE
Angular cdkDrag of Material table rows not working with router-outlet

### ISSUE THREAD

**Issue by wzheng2310** [angular/components#15948] opened 2019-05-03 17:38 UTC
#### What is the expected behavior?
When using CDK Drag & Drop with Material table rows, if the table is loaded via router-outlet, it should be able to drag & drop the rows.

#### What is the current behavior?
Drag & drop will fail with the following error:

`TypeError: Cannot read property '_getSiblingContainerFromPosition' of undefined`
`    at DragRef._updateActiveDropContainer (drag-ref.ts:727)`
`    at SafeSubscriber.DragRef._pointerMove [as _next] (drag-ref.ts:505)`
`    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:265)`
`    at SafeSubscriber.next (Subscriber.ts:207)`
`    at Subscriber._next (Subscriber.ts:139)`
`    at Subscriber.next (Subscriber.ts:99)`
`   at Subject.next (Subject.ts:70)`
`   at HTMLDocument.handler (drag-drop-registry.ts:127)`
`   at ZoneDelegate.invokeTask (zone.js:423)`
`   at Zone.runTask (zone.js:195)`

#### What are the steps to reproduce?
I create a stackblitz project (https://stackblitz.com/edit/angular-cdkdrag-table-row) that can reproduce the problem. Please open the debug console and you will see the following error message as soon as you try to drag a row

Take a look at app.component.html and see my comment in there.

Credit to https://stackblitz.com/edit/angular-igmugp, I followed and copied/pasted the mat-table and drag/drop code from it to create my project for the repro.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
It happens on Chrome (version 73.0.3683.86) in Ubuntu 18.04,
It also happens on Windows 10 Edge
For Angular/Material versions, you can find out from the stackblitz project.

**Comment by wzheng2310** [comment] 2019-05-03 22:15
After some debugging, I found that the difference between using router-outlet vs loading the component directly is that when loading it directly, the following piece of code will be called when the page is created and it is not called when using router-outlet. That caused the related variable not initialized hence it got the undefined error when trying to drag/drop. However, I still don't know how to fix it yet.

`
CdkDropList.prototype.ngAfterContentInit = /**
 * @return {?}
 */
function () {
    var _this = this;
    this._draggables.changes
        .pipe(startWith(this._draggables), takeUntil(this._destroyed))
        .subscribe(function (items) {
        _this._dropListRef.withItems(items.map(function (drag) { return drag._dragRef; }));
    });
};
`

**Comment by wzheng2310** [comment] 2019-05-04 00:48
Problem is solved.
The cdkDropList is moved from the table tag into the tr tag. Like below:
Before:

    <table mat-table #table [dataSource]="dataSource" class="mat-elevation-z8"
          cdkDropList
         [cdkDropListData]="dataSource"
         (cdkDropListDropped)="dropTable($event)">

      <ng-container matColumnDef="position">
       ...
      </ng-container> 
      <ng-container matColumnDef="name">
      ...
      </ng-container>
      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;" cdkDrag [cdkDragData]="row"></tr>
    </table>


After:

    <table mat-table #table [dataSource]="dataSource" class="mat-elevation-z8">
      <ng-container matColumnDef="position">
       ...
      </ng-container> 
      <ng-container matColumnDef="name">
      ...
      </ng-container>
      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;"
         cdkDropList
         [cdkDropListData]="dataSource"
         (cdkDropListDropped)="dropTable($event)"
         cdkDrag [cdkDragData]="row"></tr>
    </table>

**Comment by wzheng2310** [comment] 2019-05-04 00:49
See my previous comment.

**Comment by lukaszgodula** [comment] 2019-07-10 11:20
I have the same issue, anybody have maybe workaround?

**Comment by gleycerparra** [comment] 2019-07-15 15:30
Any solution? I have the same issue when try drag and drop between datatables.

**Comment by marcinolawski** [comment] 2019-08-16 08:02
The problem is that _DragRef._initialContainer == undefined_. This is because _DragRef._initializeDragSequence()_ is called earlier than _DragRef._withDropContainer()_. __initializeDragSequence()_ initializes the __initialContainer_ based on __dropContainer_, __dropContainer_ is initialized by __withDropContainer()_ but because __initializeDragSequence()_ is called earlier than __withDropContainer()_ __initialContainer_ is set to undefined. More info: [https://github.com/angular/components/blob/master/src/cdk/drag-drop/drag-ref.ts](url)
**Very brutal workaround**:
Find file drag-drop.js inside @angular directory, add the following line to the _withDropContainer() function:
`this._initialContainer = container;`
**I have no idea if this code has any side effects** but it solves the problem effectively.

**Comment by henrikdahl8240** [comment] 2019-08-19 09:28
Can't this problem be corrected, please? I suppose it's quite obvious, that in all non-trivial Angular apps, there will be used router-outlet(s) and drag-drop presumably just doesn't work at all as soon as you introduce a router-outlet.

**Comment by lukaszgodula** [comment] 2019-08-19 10:14
> Any solution? I have the same issue when try drag and drop between datatables.

  ngAfterViewChecked() {
    this.cdRef.detectChanges();
  }

For me only such thing worked... Ugly and not optimal but I needed this to work with any price.

**Comment by abstratmobile** [comment] 2019-10-25 08:08
I have this issue and i'm not sure exactly how I solved it

Try moving this code to the bottom of your class

`@ViewChild('table', null) table: MatTable<PeriodicElement>;
  displayedColumns: string[] = ['position', 'name', 'weight', 'symbol'];

  dropTable(event: CdkDragDrop<PeriodicElement[]>) {
    const prevIndex = this.dataSource.findIndex((d) => d === event.item.data);
    moveItemInArray(this.dataSource, prevIndex, event.currentIndex);
    this.table.renderRows();
  }`

That seems like the only change I made (that seems likely to have made a difference) that stopped the error occuring

**Comment by mshehadeh** [comment] 2020-01-21 21:04
Any updates on this?

**Comment by jadekler** [comment] 2020-02-06 21:56
> The problem is that _DragRef._initialContainer == undefined_. This is because _DragRef._initializeDragSequence()_ is called earlier than _DragRef._withDropContainer()_. __initializeDragSequence()_ initializes the __initialContainer_ based on __dropContainer_, __dropContainer_ is initialized by __withDropContainer()_ but because __initializeDragSequence()_ is called earlier than __withDropContainer()_ __initialContainer_ is set to undefined. More info: [https://github.com/angular/components/blob/master/src/cdk/drag-drop/drag-ref.ts](url)
> **Very brutal workaround**:
> Find file drag-drop.js inside @angular directory, add the following line to the _withDropContainer() function:
> `this._initialContainer = container;`
> **I have no idea if this code has any side effects** but it solves the problem effectively.

Submitted as a PR here: https://github.com/angular/components/pull/18421.

Let's see if that is the right way to fix this. :)

**Comment by jadekler** [comment] 2020-02-07 21:59
Should be fixed with https://github.com/angular/components/pull/18356 I believe.

**Comment by crisbeto** [comment] 2020-02-07 22:00
Closing as fixed. If it's not sorted out after #18356 is released I'll reopen the issue.

**Closed by crisbeto** 2020-02-07 22:00 UTC
Labels: P3
