### ISSUE TITLE
Directionality service to monitor dynamic changes to the 'dir' attribute at the top-level.

### ISSUE THREAD

**Issue by vdjhards** [angular/components#17637] opened 2019-11-07 10:27 UTC
Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/flexlayoutgap-with-rtl-with-wrong-direction

**Steps to reproduce:**
1) First Inspect the TopbarLeft div and see that it gives the margin-right 5px as it is mention in fxLayoutGap="5px" in parent div

2) Now Click On 'Toggle Direction' Button (you can see that its direction has been changed to RTL)

**Expected Behavior**

What behavior were you expecting to see?

As per the FlexLayout documentation if i use RTL on body tag then my direction will change to rtl and the fxLayoutGap="5px" will render to margin-left:5px to its child div.

**Actual Behavior**

What behavior did you actually see?

I am not getting the desired result. I can find the margin-right still present in RTL instead of margin-left. There may be some issue with the Directionality service. It looks like that the service only checks the top-level (HTML) or body-level (body) for the presence of a dir attribute.

**Default State when application loads**

![Before Click](https://user-images.githubusercontent.com/42489589/68380643-3bd7f980-0176-11ea-9061-cee9aa63d2fd.png)

**After Clicking on 'Toggle Direction' button**

![after tgl](https://user-images.githubusercontent.com/42489589/68380664-4abeac00-0176-11ea-9640-c06f936bc4d4.png)

**Comment by devversion** [comment] 2020-05-27 18:54
It looks like this is working as intended. The `Directionality` service will not monitor dynamic changes to the `dir` attribute on the document or body.

It might be best to use the `dir` directive in the dynamic toggle case. Alternatively, it might make sense to rely on #17659 that allows manual notifying when the global `dir` property is updated.

**Comment by devversion** [comment] 2020-05-27 18:56
If flex-layout recommends placing `dir` on the body element, but does not mention that it should not be updated dynamically, then this looks more like a documentation issue for flex-layout. I'm closing this one as it's working as intended.

**Closed by devversion** 2020-05-27 18:56 UTC
Labels: needs triage
