### ISSUE TITLE
Material input focus

### ISSUE THREAD

**Issue by WilliamSf** [angular/components#18113] opened 2020-01-06 15:43 UTC
When input is populated and clicked, the underline is duplicated

![Peek 06-01-2020 12-28](https://user-images.githubusercontent.com/31212064/71828375-fdc95a00-3080-11ea-9fca-cf11eb5d1351.gif).

**Environment**

Node: 10.16.3
OS: linux x64
Angular: 9.0.0-next.12

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.13
@angular-devkit/build-angular     0.803.13
@angular-devkit/build-optimizer   0.803.13
@angular-devkit/build-webpack     0.803.13
@angular-devkit/core              8.3.13
@angular-devkit/schematics        8.3.13
@angular/cdk                      8.2.3
@angular/cli                      8.3.13
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.13
@schematics/angular               8.3.13
@schematics/update                0.803.13
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

**Comment by devversion** [comment] 2020-05-28 09:49
Hello! I was unable to see this in our documentation page. Could you please provide more context on where you see this?

**Comment by devversion** [comment] 2020-07-14 07:00
Closing as no more information has been provided, and we were unable to reproduce this.

**Closed by devversion** 2020-07-14 07:00 UTC
Labels: area: material/form-field, area: material/input, cannot reproduce
