### ISSUE TITLE
v8.2.+ DragDropList has wrong information

### ISSUE THREAD

**Issue by bdevido** [angular/components#17182] opened 2019-09-24 07:34 UTC
#### Reproduction

I need to drag drop elements in a grid and found a nice workaround in this StackBlitz : https://stackblitz.com/edit/angular-nuiviw (WORKING)

When I used the same code in my project, it was not working, so I create a StackBlitz in order to understand what I was doing wrong, but the same code, with Angular 8, is not working 
https://stackblitz.com/edit/angular-dcnj2k (NOT WORKING)

I notice that the DragDropList in the method "enter" has different information from v.7 to v.8

Steps to reproduce:
1. Pick a tile to drag
2. Try to move it aorund
 
 
#### Expected Behavior

The placeholder should move and you can drop the tile around in the grid

#### Actual Behavior

The placeholder don't move, sometimes it doesn't even show up so you cannot move the tile around

#### Environment

- Angular: 8.+
- CDK/Material: 8.+
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Debian

**Comment by mhlg** [comment] 2019-12-19 02:08
Have you managed to make it work?

**Comment by bdevido** [comment] 2019-12-19 10:17
Hi, yes I made it work. I found another workaround online which work with angular 8+

https://stackblitz.com/edit/angular-dyz1eb

and also

https://stackblitz.com/edit/angular-yysvkf

**Comment by crisbeto** [comment] 2020-05-27 18:26
Duplicate of https://github.com/angular/components/issues/13372.

**Closed by crisbeto** 2020-05-27 18:26 UTC
Labels: area: cdk/drag-drop
