### ISSUE TITLE
bug([mat-fab]): [Cursor changes and mousenter event triggers even before reaching the round edges of the fab button]

### ISSUE THREAD

**Issue by mldkishore** [angular/components#19377] opened 2020-05-15 22:45 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://components-issue-x78ukx.stackblitz.io

Steps to reproduce:
1. hover closer to the fab button round edges .Before even entering into button , mouseenter event triggers and changes the cursor to pointer.
 
 
#### Expected Behavior

What behavior were you expecting to see?
Should trigger mouseenter event and change cursor only when hovered inside the fab button

#### Actual Behavior

What behavior did you actually see?
Honors mosuenter event and cursor changes before reaching the fab button

#### Environment

- Angular:9.0.2
- CDK/Material:9.1.0
- Browser(s):chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jelbourn** [comment] 2020-05-29 22:39
I can reproduce this, but it's a super minor issue we wouldn't normally tackle. However, looks like it's incidentally fixed in the MDC-based button.

**Comment by crisbeto** [comment] 2022-06-27 10:01
I had a fix for this issue at #25166 that I ran through our internal checks. The test run revealed some issues with our strong focus indicators feature which will take a larger refactor to fix. Given that this will be resolved by the MDC version of the component, it isn't worth the effort of landing the PR. You can fix the issue in your own app by adding this to your CSS:

```
.mat-fab, .mat-mini-fab {
  overflow: hidden;
}
```

**Closed by crisbeto** 2022-06-27 10:01 UTC
Labels: P5, has pr, area: material/button, Fixed in MDC
