### ISSUE TITLE
bug(mat-progress-bar): Progress jumps from 100 to 0, even if 0 was set and ngIf hides/shows the component

### ISSUE THREAD

**Issue by jpike88** [angular/components#20369] opened 2020-08-20 07:33 UTC
I'm resurrecting issue [#3502](https://github.com/angular/components/issues/3502).

We use a table component which on pagination, uses mat-progress-bar. when an API call is in progress, an ngIf shows mat-progress-bar, and progress increments to 100. When done, progress is set to 0, and ngIf hides the component.

When the first call is made, everything is fine. But on subsequent api calls, the progress bar after appearing suddenly slides down from 100 to 0 when it appears, even through progress was set to 0 before it showed. This is very jarring. It breaks UI conventions in a pretty fundamental way and I think needs at least a suggested workaround by the team so I can mitigate it somehow

**Comment by Ruslancic** [comment] 2021-04-19 14:59
Same here +1!

**Comment by rgutierrezatx** [comment] 2021-05-25 17:38
any update on this?

**Comment by Bug-Reaper** [comment] 2021-09-20 21:45
Same issue and the behavior is really strange too. I have a method on my progress bar that should cause the progress bar to appear with value 0 by toggling the boolean behind the progress bar's *ngIf. 

If I call that method from a (click) mat-button event in the component it does the 100 --> 0 jump right away.
If I call that method from a (click) mat-button event on the parent competent (which has viewchild access to progress bar component) then no weird initial jump.

My workaround solution is to use [hidden] instead of *ngIf but a real fix for this is wanted. Sorry I'm not going to have time to setup a demo which highlights the bug. Feel free to ask me more questions if you can't reproduce.

**Comment by rudolphh** [comment] 2022-01-23 21:15
Can't figure this out either.  When the parent component is constructed, I see the three progress bars in one child component jump from 100 to 0, but another child component (w/ progress bar) does not.  I'm failing to see what I'm doing differently.

**Comment by rudolphh** [comment] 2022-01-23 21:28
Not sure what made me test position in the parent template, but when the child component that jumps is above the one that doesn't, they both don't jump!  smh

**Comment by mindit-ovidiumiu** [comment] 2022-02-04 17:26
seems to be fixed in angular-13: [demo](https://stackblitz.com/edit/angular-ivy-x28jnz?file=src/app/app.component.ts)

**Comment by klofi** [comment] 2022-03-07 20:59
Had the same issue and was able to fix it in Angular 11 (haven't tried 13 yet) by adding `*ngIf`:

```
<mat-progress-bar
    *ngIf="progress !== undefined"
    mode="determinate"
    [value]="progress"
></mat-progress-bar>
```

Strangely, giving the `progress` an initial value of `0` had no effect.

**Comment by zarend** [comment] 2022-12-12 23:19
Hello [jpike88](https://github.com/jpike88),

Does the issue still happen for you in v15?

-Zach

**Closed** 2022-12-13 03:05 UTC
Labels: help wanted, P4, needs: clarification, area: material/progress-bar
