### ISSUE TITLE
bug(MatFormField): layout glitch on long mat-label

### ISSUE THREAD

**Issue by Mradmedamine** [angular/components#27989] opened 2023-10-24 16:25 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

The mat label text is not shown correctly. it exceeds the limit of the field.
![image](https://github.com/angular/components/assets/12666919/9afb9e5d-5565-4a91-a033-22fd56811052)

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. Set a long mat label text
2.

### Expected Behavior

form field label is shown correctly and ellipsis is shown if text is too long. no interference with mat-icon suffix or date-picker toggle.

### Actual Behavior

Text reachs the field end

### Environment

- Angular: 16.2.10
- CDK/Material: 16.2.9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by zarend** [comment] 2023-10-24 16:48
Hello folks,

This issue is being closed as a duplicate of issue #27952. The issue being closed is essentially the same as the issue that is referenced.

For more information, please refer to the original issue.

If you have any questions, please feel free to comment on the original issue. Commenting or reacting with :+1: on the original issue is a great way to tell us that the issue affects you.

Thank you for your understanding.

**Closed by zarend** 2023-10-24 16:48 UTC
Labels: needs triage

**Comment by GavynHolt** [comment] 2023-11-09 19:13
Try adding this to your global styles for now: 

`.mdc-button .mdc-button__label {
  overflow: hidden;
  text-overflow: ellipsis;
}`
