### ISSUE TITLE
help(GOOGLE MAPS): Map not displaying after providing options

### ISSUE THREAD

**Issue by allindex-development** [angular/components#19886] opened 2020-07-07 15:57 UTC
#### What are you trying to do?

I am showing the google maps component inside a modal component. The component is loading fine when I add it like this: 
`<google-map [center]="mapsCenter" [width]="300" [height]="300" ></google-map>`

However, when I add the [options] property with the following options the maps component just shows a gray box:
` mapsOptions: google.maps.MapOptions = {
    mapTypeId: 'hybrid',
    zoomControl: false,
    scrollwheel: false,
    disableDoubleClickZoom: true,
    maxZoom: 15,
    minZoom: 8,
  }`

What could cause this issue? If you need more information about my installation I'm happy to provide it.

#### Environment

- Angular: 9.0.7
- CDK/Material: 9.2.4
- Browser(s): Google Chrome
- Google maps: 10.0.1

**Comment by DMuellerFielddata** [comment] 2020-07-08 09:52
try it in google-maps version 9.*

**Comment by crisbeto** [comment] 2020-07-08 20:36
Looks like a duplicate of https://github.com/angular/components/issues/19908.

**Closed by crisbeto** 2020-07-08 20:36 UTC
Labels: area: google-maps, troubleshooting
