### ISSUE TITLE
CDK drag/drop 

### ISSUE THREAD

**Issue by toqeer618** [angular/components#17445] opened 2019-10-18 17:01 UTC
#### Bug, feature request, or proposal:
No support for 2D-list

#### What is the expected behavior?
it must support 2D-list

#### What is the current behavior?
Only support for 1D and one convert 2D to 1D but no solution .

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
8.2.1

**Comment by jelbourn** [comment] 2019-10-18 23:30
Duplicate of #13372

**Closed by jelbourn** 2019-10-18 23:30 UTC
