### ISSUE TITLE
bug(select): disableOptionCentering not working if control at bottom of the page

### ISSUE THREAD

**Issue by MohammedAbdulMateen** [angular/components#20163] opened 2020-08-03 12:43 UTC
#### Reproduction

Steps to reproduce:
1. https://stackblitz.com/edit/angular-8rmfbm?file=src%2Fapp%2Fselect-custom-trigger-example.ts
2. In that sample in all drop downs the Tomato option present at the last is selected on load but see the 3rd drop down it is not able to show options dialog properly
3. I tried using panelClass and keeping position: relative or absolute and giving top, left but it didn't help
 
 
#### Expected Behavior

What behavior were you expecting to see?
No matter where the mat select is placed in the page the drop down should open properly if it is at the top the drop down should open top-to-bottom (works fine) and if it's at the bottom bottom-to-top but it fails in this case bottom to top it doesn't render properly

#### Actual Behavior

What behavior did you actually see?
The selected option is not visible when the drop down present at the bottom of the page is opened it is being cut off from the view port or page due to the scroll position not going to the proper place

#### Environment

- Angular: 8,9,10
- CDK/Material: 8,9,10
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

To reproduce the issue with less drop downs I used div's with position absolute but even if we keep so many drops one after the other the same issue comes.

Also I want to position the options dialog a bit farther from the control itself for top and middle ones the options dialog should open below the control and form mat-select at the bottom of the page it should have bottom margin or come upwards for it I tried so but it is not working properly

.myPanelClass {
  position: relative;
  top: 30px;
  left: 28px;
}

<mat-select disableOptionCentering panelClass="myPanelClass" [formControl]="toppings1" multiple>

![image](https://user-images.githubusercontent.com/17563774/89183109-65626c00-d5b4-11ea-81e1-0bcd8c192b4e.png)

with myPanelClass the bottom one opens up like this

![image](https://user-images.githubusercontent.com/17563774/89183181-78753c00-d5b4-11ea-97f8-6e82a6daba9b.png)

Note: my drop downs are not only static but also dynamic in some cases so many drop downs in a page are rendered using *ngFor

**Comment by jelbourn** [comment] 2020-08-06 22:40
@crisbeto is this working as intended? If option centering is turned off, I'm not sure what else would happen

**Comment by crisbeto** [comment] 2020-08-09 08:50
I think the expectation here is that if centering is disabled, it'll align to the top of the form field when it has to invert its position. This should be resolved with the MDC implementation since that's basically how it'll behave then.

**Comment by MohammedAbdulMateen** [comment] 2020-08-18 15:16
@crisbeto what would be the fix for it? any patch fix available until the fix is applied in the next release?

what is MDC implementation? is it plain material design just HTML & CSS without Angular?

**Comment by veronesecoms** [comment] 2020-12-11 14:48
I have the same problem, someone have news for this problem?

**Comment by leoGrg** [comment] 2021-02-19 14:37
I have the same problem, someone have news for this problem?
When the last item in the mat-select is selected, he moves up.

**Comment by leoGrg** [comment] 2021-02-24 11:24
I've found this solution :
`.cdk-overlay-pane  { 
  transform:none !important; 
} `
Which is working well for me.

**Comment by amysorto** [comment] 2022-11-07 23:14
This is fixed in the new MDC based select component coming soon in v15. When I also tested the example with v14, it seemed to be fixed as well.

**Closed by amysorto** 2022-11-07 23:14 UTC
Labels: P4, area: material/select, Fixed in MDC
