### ISSUE TITLE
bug(mat-form-field): outline mat select label overlap suffixes

### ISSUE THREAD

**Issue by bsthilaire** [angular/components#30002] opened 2024-11-12 19:42 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15 (Legacy)

### Description

When using mat-form-field with the appearance **outline**, the label does not size correctly when suffixes are added to the Field.

![Image](https://github.com/user-attachments/assets/1544336f-74ed-4026-99e4-652d72b6ef03)

Work when using appearance **fill**
![Image](https://github.com/user-attachments/assets/fdeece89-c9fd-4237-854e-890f345e714f)

Getting the same bug using Angular 15 to 18 when using MDC Components. Did not have this bug with Angular 15 (not mdc)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/w7csj4

Steps to reproduce:
1. Have a form Field with appereance outline.
2. Have a long label for the form field.
3. Have a mat-select in the form field (multiple or not)
4. Add matSuffix buttons

### Expected Behavior

I would expect the **outline** appearance label to overflow and add ellipsis like the **fill** counterpart.

### Actual Behavior

The Label does not overflow and is over/under the down caret and the suffix buttons

### Environment

- Angular: 19.0.0-next.2
- CDK/Material: 19.0.0-next.2
- Browser(s): Chrome/Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by aliabodaraa** [comment] 2024-11-14 15:29
Hello,
Can i start working on it?

**Comment by crisbeto** [comment] 2024-11-15 11:53
Duplicate of https://github.com/angular/components/issues/26349.

**Closed by crisbeto** 2024-11-15 11:53 UTC
Labels: needs triage
