### ISSUE TITLE
mat-select, mat-autocomplete with virtual scroll

### ISSUE THREAD

**Issue by NitinMagdum** [angular/components#20273] opened 2020-08-12 09:22 UTC
1 -- mat-autocomplete with virtual scroll
https://stackblitz.com/edit/angular-htsgbw?file=src%2Fapp%2Fapp.component.html --- here sometimes scrolling area showing blank space

2 --mat-autocomplete with mat-select
https://stackblitz.com/edit/angular-gs4scp?file=src%2Fapp%2Fcdk-virtual-scroll-fixed-buffer-example.html
here select one item from dropdown then again click and scroll dont select any item click outside the box, the existing selected item is not visible/not bound to select box

it would be great if you provide a working example.

Thanks

**Comment by jelbourn** [comment] 2020-08-13 22:07
Duplicate of #10122

**Closed by jelbourn** 2020-08-13 22:07 UTC
Labels: needs triage
