### ISSUE TITLE
help(cdk-virtual-scroll-viewport): Drag and drop is not working with cdk-virtual-scroll-viewport

### ISSUE THREAD

**Issue by sujeetjaiswara** [angular/components#20345] opened 2020-08-17 16:24 UTC
#### What are you trying to do?
I am trying to use cdk-virtual-scroll-viewport with cdkDrag in my project which is not functioning as required when I add new data into the list. 

#### What troubleshooting steps have you tried?
I am unable to troubleshoot. 

What are you seeing that does not match your expectations? 
Drag and drop is not working.

#### Reproduction
I am providing the link for the sample of code that I am using attached below:
https://stackblitz.com/edit/drag-drop-virtual-scroll-cm6uck?file=src%2Fapp%2Fapp.component.html

#### Environment
- Angular: ^7.0.0
- CDK/Material: ^7.0.0
- Browser(s): Google chrome
- Operating System: Windows

**Comment by Achilles1515** [comment] 2020-08-18 19:57
Drag and drop + virtual scrolling is not supported.

https://github.com/angular/components/issues/19491

**Comment by crisbeto** [comment] 2020-08-19 09:39
Closing as a duplicate of https://github.com/angular/components/issues/10122.

**Closed by crisbeto** 2020-08-19 09:39 UTC
Labels: needs triage, troubleshooting
