### ISSUE TITLE
date range picker

### ISSUE THREAD

**Issue by dalaq** [angular/components#15903] opened 2019-04-25 11:48 UTC
#### i want to pick date range on the table and filter by period,

![Capture](https://user-images.githubusercontent.com/25386344/56733488-5cf47200-6771-11e9-9ffc-5ff39fc17671.PNG)

**Comment by free-easy** [comment] 2019-04-25 21:33
See https://github.com/angular/components/issues/4763

**Comment by jelbourn** [comment] 2019-04-25 21:53
Duplicate of #4763

**Closed by jelbourn** 2019-04-25 21:53 UTC
