### ISSUE TITLE
help(Material theme): Adding theme colors from tailwind to palette

### ISSUE THREAD

**Issue by IsaacSomething** [angular/components#26103] opened 2022-11-28 16:43 UTC
### What are you trying to do?

I would like to add the theme colors from tailwind's config file to the angular material theme palette using the theme() function from tailwind

### What troubleshooting steps have you tried?

First tried by declaring a root variable (was using this approach in versions before 15)

```
:root{
   --primary-500:theme(colors.primary.500);
}
```

```
$mat-primary-palette: (
  50: #ffe7e6,
  100: #ffc4c1,
  200: #ff9d98,
  300: #ff766e,
  400: #ff584f,
  500: var(--primary-500),
 ```
 
 This creates the error on the npm start
 > ./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
var(--primary-500) is not a color. Falling back to "dark" tone.

  I also tried adding it straight to the palette
  ```
  $mat-primary-palette: (
  50: #ffe7e6,
  100: #ffc4c1,
  200: #ff9d98,
  300: #ff766e,
  400: #ff584f,
  500: theme(colors.primary.500),
 ```
 This shows an inline error
 
 > identifier or variable expectedscss(css-idorvarexpected)
  

### Reproduction

Steps to reproduce:
1. Install tailwind
2. Setup the config file

```
module.exports = {
  content: ["./src/**/*.{html,ts}", "./projects/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        contrast: {
          light: "#fffffff",
          dark: "#000000",
        },
        primary: {
          50: "#ffe7e6",
          100: "#ffc4c1",
          200: "#ff9d98",
          300: "#ff766e",
          400: "#ff584f",
          500: "#ff3b30",
          600: "#ff352b",
          700: "#ff2d24",
          800: "#ff261e",
          900: "#ff1913",
          A100: "#ffffff",
          A200: "#fffafa",
          A400: "#ffc8c7",
          A700: "#ffafad",
        },
        ```
        
3. Try add custom theme colors to material theme palette

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by marzoli** [comment] 2022-11-29 09:43
I encounter the same problem. I don't use tailwind but I use a palette with css variables.

**Comment by GeorgeKnap** [comment] 2022-11-30 19:41
Dynamic theming is a problem in v15 MDC components
Many projects now face the same issue. See https://github.com/angular/components/issues/25981

**Comment by gianmd** [comment] 2023-05-08 20:52
@IsaacSomething  looking to do teh same, did you had any luck?

**Comment by GeorgeKnap** [comment] 2023-05-09 10:21
@IsaacSomething 
Have you considered binding both tailwind and material palette to css variables?

like in tailwind: 
```
   colors: {
        primary: {
          50: 'var(--palette-primary-50)',
          100: 'var(--palette-primary-100)',
          200: 'var(--palette-primary-200)',
          300: 'var(--palette-primary-300)',
          400: 'var(--palette-primary-400)',
          500: 'var(--palette-primary-500)',
          600: 'var(--palette-primary-600)',
          700: 'var(--palette-primary-700)',
          800: 'var(--palette-primary-800)',
          900: 'var(--palette-primary-900)',
        }, 
   }
```

in material palette the same:
```
$dynamic-palette-primary: (
  50: var(--palette-primary-50),
  100: var(--palette-primary-100),
  200: var(--palette-primary-200),
  300: var(--palette-primary-300),
  400: var(--palette-primary-400),
  500: var(--palette-primary-500),
  600: var(--palette-primary-600),
  700: var(--palette-primary-700),
  800: var(--palette-primary-800),
  900: var(--palette-primary-900),
);
```
This way both Tailwind and Material are completely agnostic to the real colors and allow you to somehow populate those css variable as you wish. For example I'm using tinicolor2 to generate my palette colors from 500 color.
```
export function computeColors(hex: string): Color[] {
  return [
    getColorObject(tinycolor(hex).lighten(52), '50'),
    getColorObject(tinycolor(hex).lighten(37), '100'),
    getColorObject(tinycolor(hex).lighten(26), '200'),
    getColorObject(tinycolor(hex).lighten(12), '300'),
    getColorObject(tinycolor(hex).lighten(6), '400'),
    getColorObject(tinycolor(hex), '500'),
    getColorObject(tinycolor(hex).darken(6), '600'),
    getColorObject(tinycolor(hex).darken(12), '700'),
    getColorObject(tinycolor(hex).darken(18), '800'),
    getColorObject(tinycolor(hex).darken(24), '900'),
    getColorObject(tinycolor(hex).lighten(50).saturate(30), 'A100'),
    getColorObject(tinycolor(hex).lighten(30).saturate(30), 'A200'),
    getColorObject(tinycolor(hex).lighten(10).saturate(15), 'A400'),
    getColorObject(tinycolor(hex).lighten(5).saturate(5), 'A700'),
  ];
}

function getColorObject(value: tinycolor.Instance, name: string): Color {
  const c = tinycolor(value);
  return {
    name: name,
    hex: c.toHexString(),
    darkContrast: c.isLight(),
  };
}
```

does it help?

**Comment by IsaacSomething** [comment] 2023-05-09 10:30
I havnt tried with generating the colors, I dont think i am keen to do that though as the designers want specific hex values for colors at each value. Im also not too keen to have to add another library just for this.

**Comment by GeorgeKnap** [comment] 2023-05-09 10:39
> I havnt tried with generating the colors, I dont think i am keen to do that though as the designers want specific hex values for colors at each value. Im also not too keen to have to add another library just for this.

that was just an example, you could harcode them in your css root and it will still work.

**Comment by amysorto** [comment] 2023-05-19 18:39
Duplicate of #25981.

**Closed by amysorto** 2023-05-19 18:39 UTC
Labels: troubleshooting, needs triage
