### ISSUE TITLE
Md components break inside router-outlet using hmr and ngIF

### ISSUE THREAD

**Issue by hghammoud** [angular/components#7284] opened 2017-09-25 01:35 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Component to work i.e Checkbox to animate and show a check
This also applies to triggering modal, buttons, inputs...

#### What is the current behavior?
Checkbox model changes value but no visual effect is shown class mat-checkbox-checked is not added to the md-checkbox container

#### What are the steps to reproduce?

- inside a route-outlet (routed to any any plain component) add a checkbox inside the component with an ngIf="true" on it.
- trigger HMR
- try to click on the checkbox. Ripple animates but check box stays empty. (real html checkbox inout changes value tho)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All browsers,     "@angular/cdk": "^2.0.0-beta.11",     "@angular/material": "^2.0.0-beta.11",     "@angular/core": "~4.3.1",

#### Is there anything else we should know?
----> Remove the ngIf and the issue is gone
----> Place the checkbox with ngIF outside the router-oultet and the issue is gone.

and interestingly (taken from another issue with md-progress-spinner https://github.com/angular/angular/issues/14741)
----> add a resolve to the route and the issue is gone, i.e
export class DelayResolver implements Resolve<any> {
  public resolve(route: ActivatedRouteSnapshot): Observable<any> {
    return Observable.create((observer) => {
      observer.next(true);
      observer.complete();
    })
      .delay(0);
  }
}

{ path: 'home', component: HomeComponent, resolve: { delay: DelayResolver } },

I hope you can shed a light on this issue.

**Comment by josephperrott** [comment] 2017-09-26 17:19
Can you provide a plunker reproduction showing this issue?

**Comment by hghammoud** [comment] 2017-09-26 18:17
I am not sure how can I provide a plunker that does HMR. What steps did you take?

1) If you use https://github.com/AngularClass/angular-starter that has the hmr preconfigured. 
2) Just add the @angular/material to it with cdk
3) add the material theming
3) add inside homecomponent a md-checkbox with ngIf="true" on it (or a dropdown or a modal...) . 
4) trigger hmr by changing anything in the code. 
5) try to access the component (click or open ...)

You will get the result.

As i stated the error is only when hmr is triggered. If you reload the page it works.

**Comment by jelbourn** [comment] 2018-01-17 00:10
Current Angular Material doesn't do anything specifically to support HMR

**Comment by crisbeto** [comment] 2022-06-28 12:30
We're in the process of cleaning up our issue backlog. I'm closing this issue, because there hasn't been any activity in a long time and it's referring to a really old version of the library. Feel free to open a new issue if this is still a problem.

**Closed by crisbeto** 2022-06-28 12:30 UTC
Labels: feature, P5, area: many
