### ISSUE TITLE
Nested drop targets do not work correctly.

### ISSUE THREAD

**Issue by henrikdahl8240** [angular/components#17143] opened 2019-09-19 11:41 UTC
Let's assume we take the example from the guide at https://material.angular.io/cdk/drag-drop/overview below the header "Transferring items between lists".

Here we have a div having the attribute [cdkDropListConnectedTo]="[todoList]".

We now do a very simple change, we edit that div and make a small hierarchy of drop targets by putting three divs inside each other, where they each have the attribute [cdkDropListConnectedTo]="[todoList]".

Now we should be able to drag items from the todoList and drop the items at any of the three divs making up the hierarchy.

Unfortunately it's always the outermost div which get's the drop and not the one below the mouse cursor. So, for example, if you drag an item from the todoList and release the mouse button above the innermost div, it's still the outer-most div, which gets the drop.

Shouldn't it rather be the div below the mouse pointer and not the outermost div?

I hope you may fix this, because it's rather difficult to drop at nodes in a hierarchy having the current behavior.

**Comment by henrikdahl8240** [comment] 2019-09-20 05:40
Perhaps this is actually the same problem: https://github.com/angular/components/issues/17119

**Comment by crisbeto** [comment] 2020-07-12 09:42
Duplicate of https://github.com/angular/components/issues/16671.

**Closed by crisbeto** 2020-07-12 09:42 UTC
Labels: area: cdk/drag-drop
