### ISSUE TITLE
Strict mode creates problems with Ivy and IE

### ISSUE THREAD

**Issue by M4R1KU** [angular/components#16066] opened 2019-05-20 13:49 UTC
#### What is the expected behavior?

Material components work in Internet Explorer the same way they do in Chrome/Firefox etc.

#### What is the current behavior?

The `ɵsetClassMetadata` method takes the properties of the component/directive as a parameter and with the Material components it contains duplicate properties because it uses the get and set feature of ES6 (I assume).

The output for the CdkTrapFocus looks like this.
```
ɵngcc0.ɵsetClassMetadata(CdkTrapFocus, [{
    type: Directive,
    args: [{ selector: '[cdkTrapFocus]', exportAs: 'cdkTrapFocus' }]
  }], 
  function () { ... },
   {
    _elementRef: [], _focusTrapFactory: [], _previouslyFocusedElement: [], _document: [], focusTrap: [],
    enabled: [{
      type: Input,
      args: ['cdkTrapFocus']
    }], 
  enabled: [], 
  autoCapture: [{
      type: Input,
      args: ['cdkTrapFocusAutoCapture']
    }], 
  autoCapture: [], 
  ngOnDestroy: [], ngAfterContentInit: [], ngDoCheck: []
});
```
As you can see the enabled and autoCapture properties are duplicated.
Now this is absolutely no problem with Chrome or Firefox or any other modern Browser but IE11 does not like this when running in strict mode with `"use strict"` (which is automatically added to the webpack bundle).

IE throws the following error
![image](https://user-images.githubusercontent.com/11866278/58024965-ae471580-7b13-11e9-885c-e1089efb9959.png)
Which translates to: Multiple definitions of a property are not allowed in strict mode.

#### What are the steps to reproduce?
Clone, npm install, ng s and open in Internet Explorer
https://github.com/M4R1KU/material-strict-mode

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular CLI: 8.0.0-rc.4
Node: 12.0.0
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/cdk                      8.0.0-rc.1
@angular/material                 8.0.0-rc.1
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

**Comment by jelbourn** [comment] 2019-05-20 23:38
Duplicate of https://github.com/angular/angular/issues/30569

Marking as a duplicate of that one because it's actually an issue in Angular itself rather than in components.

**Closed by jelbourn** 2019-05-20 23:38 UTC
