### ISSUE TITLE
App crashing for missing icons when using svgIcon - Possible race condition perhaps.

### ISSUE THREAD

**Issue by un33k** [angular/components#3304] opened 2017-02-25 22:15 UTC
#### Bug:
App crashes for missing icons when using svgIcon. Or during the addSvgIconInNamespace registration process.

**Problems:**

1. If an icon is missing, the app is [crashing](https://github.com/angular/material2/issues/3130)
2. If an icon is not yet ready when it is being registered via `addSvgIconInNamespace`,  the app also crashes intermittently.

```typescript
// in app.component.ts
@Component({
  selector: 'material-app',
  templateUrl: 'app.component.html'
})
export class AppComponent {
  constructor(http: Http) {
    this.http.get('/manifest.json')
      .map(res => res.json())
      .subscribe(icons => {
        for (const name in icons) {
          if (icons.hasOwnProperty(name)) {
            const path = this.sanitizer.bypassSecurityTrustResourceUrl(`/${icons[name]}`);
            this.mdIconRegistry.addSvgIconInNamespace('myIcons', name, path);
          }
        }
      });
  }
}
```

```html
<div>
  <md-icon color="warn" svgIcon="myIcons:truck"></md-icon>
  <md-icon color="primary">fingerprint</md-icon>
</div>
```

```json
# manifest.json
{
    "truck": "truck.svg"
}
```

truck.svg exists @ /.

#### What is the expected behavior?
SVG icons show properly

#### What is the current behavior?
SVG icons will not show and will crash the app, since, by the time svgIcon is accessing the icon, it might not be ready yet

#### What are the steps to reproduce?
... use as a reference only ... (not working, perhaps due to the crash itself)
http://embed.plnkr.co/RoZRDWy04qtFezxm9tFH/

#### What is the use-case or motivation for changing an existing behavior?
svgIcon can better handle the scenario where the icon is being ready ... async 

#### Which versions of Angular, Material, OS, browsers are affected?
    "@angular/common": "^2.4.5",
    "@angular/compiler": "^2.4.5",
    "@angular/core": "^2.4.5",
    "@angular/flex-layout": "^2.0.0-beta.4",
    "@angular/forms": "^2.4.5",
    "@angular/http": "^2.4.5",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^2.4.5",
    "@angular/platform-browser-dynamic": "^2.4.5",
    "@angular/router": "^3.4.5",

@angular/cli: 1.0.0-beta.32.3
node: 6.9.5
os: darwin x64

#### Is there anything else we should know?
This [issue](https://github.com/angular/material2/issues/3130) may prevent the app from crashing, but still, it would not be desirable to have icons missing due to a possible race condition on the initial load.

**Comment by padraig-meaney** [comment] 2018-01-08 21:33
Hey guys,
I wouldn't mind taking a look at this a newbie contributor. What would be the best way to solve this? 

Right now I'm thinking if an icon instance fails when calling getNamedSvgIcon(..), it could subscribe to an observable in the iconRegistry that emits when any icons are added, and use the existing subscription in ngOnCHanges to refresh it's svg once the matching icon name is emitted?

**Comment by saulotoledo** [comment] 2018-05-19 15:13
@jelbourn I think one could add the "has pr" label to this issue.

**Comment by jelbourn** [comment] 2018-05-22 18:58
#11171 is closed now since we decided not to support asynchronous loading in this way

**Comment by jelbourn** [comment] 2021-02-23 23:35
Closing this since `MatIcon` has changed a lot since 2.0.0 and we haven't received any other reports like this, making me think the issue is obsolete

**Closed by jelbourn** 2021-02-23 23:35 UTC
Labels: P3, area: material/icon, help wanted
