### ISSUE TITLE
mat-select multiple scrolling bug

### ISSUE THREAD

**Issue by ThanosAlmighty** [angular/components#18651] opened 2020-02-28 17:15 UTC
#### Reproduction

Steps to reproduce:
1. Go to https://stackblitz.com/edit/components-issue-nzdnxa
2. Open the menu by clicking "Country Code"
3. Scroll down and select "Venezuela2"
4. Scroll up and select "Peru"
 
 
#### Expected Behavior

After I click on an option, the scrollbar of mat-select should not move

#### Actual Behavior

After I click on an option, the selected option moves to top of the list

#### Environment

- Angular: 8.2.14
- CDK/Material: ^8.2.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

#### Context

This bug was opened two years ago and closed/locked without ever being resolved (https://github.com/angular/components/issues/5381). Please do not close this bug until the resolution has been confirmed.

EDIT (in case someone messes with the linked code):

I'm attaching text files with the code since I can't get the "insert code" sections to display properly.

HTML: 
[html.txt](https://github.com/angular/components/files/4268302/html.txt)

TypeScript: 
[typescript.txt](https://github.com/angular/components/files/4268305/typescript.txt)

package.json: 
[package.json.txt](https://github.com/angular/components/files/4268307/package.json.txt)

**Comment by kalyan21M** [comment] 2020-03-03 05:11
tg

**Comment by MartyHub** [comment] 2020-06-28 16:12
Hello,

I spent hours on this issue, here is my workaround so far:

```
@ViewChild(MatSelect, { static: true }) mySelect: MatSelect;

private scrollTopBeforeSelection: number;

ngOnInit() {
  this.mySelect.openedChange.subscribe((open) => {
    if (open) {
      this.mySelect.panel.nativeElement.addEventListener(
        'scroll',
        (event) => (this.scrollTopBeforeSelection = event.target.scrollTop)
      );
    }
  });

  this.mySelect.optionSelectionChanges.subscribe(() => {
    this.mySelect.panel.nativeElement.scrollTop = this.scrollTopBeforeSelection;
  });
}
```

Regards

**Comment by crisbeto** [comment] 2020-07-19 09:42
`mat-select` doesn't change the scroll position itself when you're clicking on the options. I think the problem is that you're adding options before the selected one which changes the size of the list and causes it to jump around.

**Comment by jelbourn** [comment] 2020-08-06 22:51
@ThanosAlmighty I looked at your stackblitz and it does seem like changing the items is the source of the position jumping

**Comment by junyuan** [comment] 2020-10-10 07:38
Similar issue [https://angular-1temy3.stackblitz.io](https://angular-1temy3.stackblitz.io) with version 9.2.4, looks like it has been fixed in v10
![Screencapture6](https://user-images.githubusercontent.com/49936085/95649125-8bedd780-0b0e-11eb-88ef-61b83c916d73.gif)
I use the list with selection, no matter single or multiple selection mode, when I click the scroll arrow button on the scroll bar. it always scroll from the first item (when no selection) or first selected item (may be). I guess the problem is on this method https://github.com/angular/components/blob/1e94871cda74243c5c551f5757a01c96297c34ad/src/material/list/selection-list.ts#L582
After I override this method to do nothing, the behavior is as expected

**Comment by crisbeto** [comment] 2021-03-29 16:01
This should've been resolved by https://github.com/angular/components/pull/19889.

**Closed by crisbeto** 2021-03-29 16:01 UTC
Labels: area: material/select, needs clarification
