### ISSUE TITLE
mat-drawer should come after mat-content in the DOM when position "end" is used for mode="side"

### ISSUE THREAD

**Issue by nehaabrol87** [angular/components#18100] opened 2020-01-04 05:00 UTC
#### Bug
mat-drawer with position end , still adds the drawer before the content in the DOM. This is causing issues for me as I need expect the content to be ahead of drawer when using keyboard nav or using Virtual cursor.

#### What is the expected behavior?
mat-drawer should come after mat-content when position = end.

#### What is the current behavior?
mat-drawer is before mat-content when position = end.

#### What are the steps to reproduce?
StackBlitz starter: https://stackblitz.com/angular/yvlxndmxyod?file=src%2Fapp%2Fsidenav-autosize-example.ts<br/>

Just add position="end" attr to mat-drawer and verify  the DOM

#### What is the use-case or motivation for changing an existing behavior?
Accessibility as tab order does not make sense here. Visibily its after the left side content but structurally its not.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
v7.3.7

#### Is there anything else we should know?
Seems like https://github.com/angular/components/blob/09dc4594259cf1d6b34a5a0893c0bccaa132c319/src/material/sidenav/drawer-container.html#L4 is causing the issue. Probably position in the DOM should be determined by the "position" attribute ? Full Disclosure: I have not yet played around with the code yet to see if that would fix it and if its even possible to fix. 
If there is a workaround that I am not probably missing that would be super helpful as well but I could not find anything.

**Comment by crisbeto** [comment] 2020-01-04 06:02
Closing as a duplicate of https://github.com/angular/components/issues/15247.

**Closed by crisbeto** 2020-01-04 06:02 UTC
