### ISSUE TITLE
[Table] IE has performance issues

### ISSUE THREAD

**Issue by fusionUI** [angular/components#7144] opened 2017-09-18 11:59 UTC
#### Bug, feature request, or proposal:
Its a duplicate issue of  https://github.com/angular/material2/issues/6727. The original one was closed after some discussion.

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
Plunker template: https://goo.gl/DlHd6U

**Comment by willshowell** [comment] 2017-09-18 13:41
Reproduction?

**Comment by vikas-verma** [comment] 2017-09-18 14:19
Hey WillShowell...

The Slowness issue is only coming in IE(tried on edge), otherwise, it works well for other browsers

i tried hosting the code in plunker and the response in IE is very slow(for 1000 records). Please follow below links. Also please recommend what approach to use in order to make this table responsive - Flex or Bootstarp. It seems like when we are trying to make this table responsive the slowness increases, especially in IE

https://run.plnkr.co/s93Shf2hMGUUcoBl/
https://plnkr.co/edit/LpCiKGSShFJw58eUYEwr?p=preview

**Comment by fusionUI** [comment] 2017-09-21 06:45
Any updates of this Please?

**Comment by josephperrott** [comment] 2017-09-25 20:34
@vikas-verma 

Can you provid metrics of the slowness you are seeing?  Upon loading the example you gave, I was not able to see the slowness that you referenced, though it could be a perception issue.  I loaded the example on both Chrome and Internet Explorer.

**Comment by wagnermaciel** [comment] 2020-08-13 22:38
Closing because no clarification was provided.

**Closed by wagnermaciel** 2020-08-13 22:38 UTC
Labels: P4, area: material/table, ie11, needs clarification, perf
