### ISSUE TITLE
bug(mat-slider): dragEnd event slow down Application

### ISSUE THREAD

**Issue by chathurasudarsha** [angular/components#27191] opened 2023-05-30 06:06 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

 Bug on Angular 15.  mat-slider dragEnd(), dragStart() events slow down Angular Application. It Keeps time to update Template (html). I have used async to update template. component level work fine. 

### Reproduction

Steps to reproduce:
1.  
2.

### Expected Behavior

update template when just finish the component 

### Actual Behavior

keep awaiting time to update template

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by amakhrov** [comment] 2023-05-30 17:29
It sounds like a change detection issue to (template is not updated upon event, but is updated at some point later when the next CD is scheduled)

I observed CD issues with the slider and the `(input)` event myself in v15. However, when I tried to repro in Stackblitz (which uses v16 now by default), my specific case was working fine there - so perhaps it's already resolved in v16?

**Comment by mmalerba** [comment] 2023-05-31 16:21
Please provide a reproduction link to assist the team with debugging

**Comment by wagnermaciel** [comment] 2023-08-23 22:16
Closing this issue since no repro link was provided and as far as I can tell, this was fixed in v16 as per @amakhrov 's description (thank you Alexey!)

**Closed by wagnermaciel** 2023-08-23 22:16 UTC
Labels: P3, perf, needs: clarification, area: material/slider
