### ISSUE TITLE
bug(COMPONENT): TITLE

### ISSUE THREAD

**Issue by dsl400** [angular/components#26320] opened 2022-12-23 13:19 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

click event not working properly on mobile, android, ios 
clicking on mat-card-title or mat-card-content does not fire the listener placed on mat-card

`<mat-card (click)="...">
  <mat-card-title>...</mat-card-title>
  <mat-card-content>...</mat-card-content>
 </mat-card>`

### Reproduction

Steps to reproduce:
1.  use mat-card with mat-card-title and mat-card-content
2.  use chrome on android
3.  set click listener on mat-card
4.  click on mat-card-content or on mat-card-content

### Expected Behavior

click listener should work

### Actual Behavior

click listener does not fire

### Environment

- Angular: 14.0.0
- CDK/Material: 14.2.4
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): android, ios

**Comment by Totati** [comment] 2022-12-23 13:31
For me it's working. [Stackblitz exmaple](https://stackblitz.com/edit/angular-dekxrg)

**Comment by crisbeto** [comment] 2023-01-23 08:03
I couldn't reproduce it either. Closing.

**Closed by crisbeto** 2023-01-23 08:03 UTC
Labels: needs triage
