### ISSUE TITLE
[Ivy] TemplatePortal with *ngIf directive inside the template attached to the overlay renders outside of the overlay container (ngIf, Overlay, ng-template)

### ISSUE THREAD

**Issue by sharikovvladislav** [angular/components#17356] opened 2019-10-10 13:45 UTC
### Reproduction

Steps to reproduce:
1. Add `@angular/cdk` to the project
2. Import `OverlayModule`
3. Inject Overlay to some component through DI
4. Create a portal to render the template (you should define it in the HTML + query it thourgh ViewChild)
5. Create an overlay
6. Attach portal to the overlay

I created two examples on stackblits with ivy and without ivy. Looks like stackblitz can not work in ivy mode. You can clone the example and execute `npm i` && `ng serve --open`. You will be able to reproduce the problem (links are below).

Looks like the problem is strongly connected with `NgIfDirective` since if you remove it everything works fine.

##### With Ivy:
Stackblitz example does not work in Ivy mode despite of enableIvy flags in the angularCompilerOptions section of the `tsconfig` file. Looks like Ivy is not working in stackblitz. You can check tsconfig, it is enabled. Tell me please if it can be easily fixed.

Stackblitz example: https://stackblitz.com/github/sharikovvladislav/angular-cdk-overlay-woot-with-ivy
Repo: https://github.com/sharikovvladislav/angular-cdk-overlay-woot-with-ivy
##### Without Ivy: 
This example is working. I just wanted to present what means "expected behavior".
Stackblitz example: 
https://stackblitz.com/github/sharikovvladislav/angular-cdk-overlay-ok-without-ivy
Github Repo: https://github.com/sharikovvladislav/angular-cdk-overlay-ok-without-ivy

The code of the component looks like:

```
  constructor(private overlay: Overlay, private _viewContainerRef: ViewContainerRef) {
  }

  toggle() {
    if (!this.overlayReference) {
      const overlay = this.overlay.create();
      const optionsPortal = new TemplatePortal(this.listOptionsTemplate, this._viewContainerRef);
      // there is the problem
      overlay.attach(optionsPortal);
      this.overlayReference = overlay;
    } else {
      this.overlayReference.dispose();
      this.overlayReference = null;
    }
  }
```
 
 
#### Expected Behavior

I expect, that created template will be inserted to the overlay element (body > .cdk-overlay-container > .cdk-overlay X)

#### Actual Behavior

Created element is placed somewhere near the HTML-tags of AppComponent.

This is how the DOM looks like before creating the overlay:
![image](https://user-images.githubusercontent.com/5622526/66573280-13f77500-eb7b-11e9-82f5-3667957df46d.png)

This is how the DOM looks like after creating the overlay:
![image](https://user-images.githubusercontent.com/5622526/66573480-6a64b380-eb7b-11e9-9aaf-4be03243382b.png)

Note `cdk-overlay-conatiner` has the comment about bindings, but does not have actual contents (some text).

I am trying this using 8.2.9 version of angular/core, but 9.0.0-next.10 is absolutely same. Check the image below:

![image](https://user-images.githubusercontent.com/5622526/66581146-4491db80-eb88-11e9-9454-5c8c094e24ec.png)

I also pushed the branch with latest 9.0.0-next.10 version of the repro. Here is the branch (same repo): https://github.com/sharikovvladislav/angular-cdk-overlay-woot-with-ivy/tree/with-ivy-angular-cdk-woot-latest-angular-version

#### Environment

- Angular: 8.2.9
- CDK/Material: `@angular/cdk@8.3.8`, no `@angular/material`
- Browser(s): Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

`ng --version` output:

```
Angular CLI: 8.3.8
Node: 10.16.0
OS: darwin x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.8
@angular-devkit/build-angular     0.803.8
@angular-devkit/build-optimizer   0.803.8
@angular-devkit/build-webpack     0.803.8
@angular-devkit/core              8.3.8
@angular-devkit/schematics        8.3.8
@angular/cdk                      8.2.3
@angular/cli                      8.3.8
@ngtools/webpack                  8.3.8
@schematics/angular               8.3.8
@schematics/update                0.803.8
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by pshurygin** [comment] 2019-10-16 10:29
Having the same issue. The problem comes from these lines:
![image](https://user-images.githubusercontent.com/25816676/66911237-c5cdf000-f018-11e9-90db-faf59779eb72.png)
The comment node(created by ngIf binding) is moved to the overlay instead of the actual template element.

**Comment by sharikovvladislav** [comment] 2019-10-24 12:14
@pshurygin do you have any workaround?

**Comment by sharikovvladislav** [comment] 2019-10-24 12:21
This problem affects our ui-kit. There are problems, for example, with `SelectComponent`. They are used everywhere (a lot of forms, grid filters and other places)

**Comment by pshurygin** [comment] 2019-10-24 12:37
I guess there are 2 options: remove ngIf or wrap your template into an additional div, so that ngIf appears on the nested element like this:
`<ng-template>
    <div>
        <div *ngIf="condition">...</div>
    </div>
</ng-template>`

**Comment by sharikovvladislav** [comment] 2019-10-24 12:53
@pshurygin Thanks, that worked fine. Good job.

**Comment by sharikovvladislav** [comment] 2019-10-24 14:01
@pshurygin Do you have case as I have (overlay, ng-template and stuff)?

Or is it simpler? If it is simpler, can you provide yours? Or at least describe it, please, so I can create repro. It would help to analyze the problem, I think. 

For example, I am not sure this problem is about `angular/cdk` :) Maybe it can be reproduced in simple `ng new app` without cdk.

**Comment by pshurygin** [comment] 2019-10-24 15:41
Yes, i have exactly the same issue.

**Comment by sharikovvladislav** [comment] 2019-10-25 13:08
I think there is some specific problem with `ng-container`.

This case is about ng-container. Workaround is to remove it.

My colleague will start new issue about using `ng-container` + `cdk` drag feature.

**Comment by crisbeto** [comment] 2020-05-26 15:09
I can't reproduce it in a Stackblitz running Ivy with the latest Angular version. Is this still an issue?

Here's the Stackblitz for reference: https://stackblitz.com/edit/angular-o6jep8.

**Comment by pshurygin** [comment] 2020-05-27 10:49
I also cannot reproduce this issue anymore with the latest angular 9.1.9 and cdk 9.2.4

**Comment by crisbeto** [comment] 2020-05-27 10:56
I'm closing the issue for now. It can always be reopened if new information comes up.

**Closed by crisbeto** 2020-05-27 10:56 UTC
Labels: area: cdk/overlay, area: cdk/portal, needs clarification
