### ISSUE TITLE
[mat-flat-button, mat-stroked-button] mat-icon within button doesnt align center vertically

### ISSUE THREAD

**Issue by eTallang** [angular/components#9799] opened 2018-02-06 08:55 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
To have a mat-icon element align center vertically within all material button types.

#### What is the current behavior?
A mat-icon element aligns top when using attribute mat-flat-button or mat-stroked-button.

#### What are the steps to reproduce?
https://stackblitz.com/edit/vertical-alignment-issue
Screenshot:
![image](https://user-images.githubusercontent.com/24789715/35850270-7cbc0dd2-0b24-11e8-9f35-7fe572134e05.png)

As the demo illustrates, the icon is not aligned correctly in the mat-flat-button and mat-stroked-button.
I also noticed that the height of a mat-flat-button and mat-stroked-button differs from the height of a mat-button or mat-raised-button. These should all have the same height in order to give the UI balance when combining button types.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 5.2.1
Angular Material 5.2.0
Chrome

**Comment by DevVersion** [comment] 2018-02-06 15:33
Thanks. I've already fixed this in PR #9771. This one is pending for review.

**Comment by flipZomb** [comment] 2018-02-22 11:38
Even the one where it says "The icon is aligned" looks a bit off to me. The plus is a bit too far down .... ?

**Comment by DanielHabenicht** [comment] 2018-12-21 10:04
I was about to open another Bug Report for this, but as @flipZomb already said the middle button icon is not aligned aswell. Have a look at this:

| [From Material Guide](https://material-components.github.io/material-components-web-catalog/#/component/button) | [From Angular/Material](https://stackblitz.com/edit/angular-zbyvvg?file=app/button-types-example.html) |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/13590797/50336709-1535b380-050f-11e9-9650-441a84651faf.png) | ![image](https://user-images.githubusercontent.com/13590797/50337011-16b3ab80-0510-11e9-91ad-461f13efe4f6.png) |

**Comment by devversion** [comment] 2020-05-28 23:35
Seems like this has been fixed. https://stackblitz.com/edit/vertical-alignment-issue?file=app%2Fapp.module.ts.

**Comment by DanielHabenicht** [comment] 2020-05-29 09:57
I wouldn't say so. They still look pretty off for me: 
![image](https://user-images.githubusercontent.com/13590797/83247146-6be2fa80-a1a3-11ea-923a-125559387f66.png)
(from your Stackblitz) 
Considering the angular material design guide: 
![image](https://user-images.githubusercontent.com/13590797/83247237-87e69c00-a1a3-11ea-9585-1197d5fb28db.png)

**Comment by devversion** [comment] 2020-05-29 10:41
@DanielHabenicht Yeah, looks like you're right. I'm reopening this. The general alignment problem seems to be caused by us using `line-height` for the button height. I don't have enough insight on why we use that over a plain `min-height`/`height` as done in MDC.

It looks like this will be fixed in our MDC-based version of the button though. #16196

**Comment by danlz** [comment] 2021-05-19 10:27
This works quite well:
`
.mat-button-base .mat-icon {
  display: inline-flex;
} 
`

**Comment by amysorto** [comment] 2022-10-28 19:21
Icons are vertically aligned within buttons in the new MDC based components coming soon in v15. Closing this bug.

**Closed by amysorto** 2022-10-28 19:21 UTC
Labels: P3, material spec, area: material/button, Fixed in MDC
