### ISSUE TITLE
Form field suffix not vertically aligned in outline appearance

### ISSUE THREAD

**Issue by mikee0305** [angular/components#21537] opened 2021-01-11 10:26 UTC
Closing, as it appears to be working as expected in the current release based on [this repro](https://stackblitz.com/edit/angular-1gmmlm?file=app/input-prefix-suffix-example.html)

_Originally posted by @josephperrott in https://github.com/angular/components/issues/16083#issuecomment-498859158_

Hi, this is not working if you change the appearance of form field as outline.

**Comment by crisbeto** [comment] 2021-01-11 15:10
For future reference, here's a Stackblitz that shows the issue: https://stackblitz.com/edit/angular-1gmmlm-kxfhzw?file=app/input-prefix-suffix-example.html

**Comment by Splaktar** [comment] 2021-03-18 20:00
Duplicate of https://github.com/angular/components/issues/20074.

**Closed by Splaktar** 2021-03-18 20:00 UTC
Labels: P3, area: material/form-field
