### ISSUE TITLE
Failed to load document: /docs-content/overviews/material/card.html. Error: OK

### ISSUE THREAD

**Issue by MihaiBoicu** [angular/components#16096] opened 2019-05-23 10:37 UTC
#### Documentation Feedback

Provide a brief summary of what you would like to see changed in our 
documentation at material.angular.io.

Feel free to provide any suggestions of content or examples you’d like us to include.

**Affected documentation page:** Insert a link to the affected page on material.angular.io

**Comment by MihaiBoicu** [comment] 2019-05-23 10:38
On Safari the following page is not loading:

Failed to load document: /docs-content/overviews/material/card.html. Error: OK

**Comment by devversion** [comment] 2019-05-24 09:02
I was not able to reproduce that issue on my end. https://material.angular.io/docs-content/overviews/material/card seems to exist for me and the file is properly loaded when visiting https://material.angular.io/components/card/overview. Maybe something was cached incorrectly.

**Comment by MihaiBoicu** [comment] 2019-05-24 16:32
Yes,


It was a cache problem. I cleared the cache and it worked.


However, this might reflect an angular problem, as well, as the clear of the cache must be done automatically in case of an error, or the old file to be loadable.


Mihai


________________________________

**Comment by devversion** [comment] 2020-05-25 20:07
Closing as this hasn't come up again, and I wasn't able to reproduce this now (and in the past 😄 )

**Closed by devversion** 2020-05-25 20:07 UTC
Labels: cannot reproduce, docs, needs clarification, needs triage
