### ISSUE TITLE
bug(cdk-tree && general): Keyboard navigation in cdk-tree or recursive list with FocusKeyManager not work as expected

### ISSUE THREAD

**Issue by nirkai** [angular/components#19899] opened 2020-07-08 10:02 UTC
##### The root problem
Recursive list and cdk-tree elements has correct order in DOM and display.
A `@Viewchildren` of the elements get a different order.

##### Influence
When using a `ListKeyManager` with the list of the recursive elements (from the cdk-tree or simple list) the keyboard focus order navigate in wrong order with <kbd>Arrow</kbd> keys. <kbd>Tab</kbd> order navigation is correct, as in the DOM elements order.

**BTW** the `withWrap()` function not working on the `cdk-tree`.

Here is a demo:
https://stackblitz.com/edit/angular-6ybajv-hyrkrk

The navigation option is just to illustrate the problem. as I said, the root problem is the difference between the DOM and the `Viewchildren` list.

Steps to reproduce:
As show in the [DEMO](https://stackblitz.com/edit/angular-6ybajv-hyrkrk).

 To illustrate:

1. Navigate the links with <kbd>Arrow</kbd> keys.
2. The focus will be on the `Level 0` first.
3. After `Level 0` the order is correct.
4. From start try to navigate with <kbd>Tab</kbd> key.

 This bug can be linked to this:
https://github.com/angular/components/pull/10691

#### Expected Behavior

The `@Viewchildren` and the list in the `ListKeyManager` will be in the same order as in the DOM.
Keyboard navigation will be in the order of the displayed list, and as the <kbd>Tab</kbd> order work.

#### Actual Behavior

The `@Viewchildren` and the list in the `ListKeyManager` is different from the elements order in the DOM.
Navigation with the <kbd>Arrows</kbd> is disorder.

#### Environment

- Angular: 9, 10
- CDK/Material: 9, 10
- Browser(s): Chrome Version 83.0.4103.116 (Official Build) (64-bit), FireFox 76.0.1 (64-bit), Edge (Chromium) Version 83.0.478.58 (Official build)

**Comment by jelbourn** [comment] 2020-07-09 21:55
Duplicate of #13018 (adding keyboard navigation support for tree; outside of `tree`, nested lists would be invalid)

**Closed by jelbourn** 2020-07-09 21:55 UTC
Labels: needs triage
