### ISSUE TITLE
FormControl updateOn blur mode not working properly only for datepicker control.

### ISSUE THREAD

**Issue by sudd03** [angular/components#16461] opened 2019-07-05 14:46 UTC
#### Reproduction

**FormControl updateOn blur mode not working properly only for datepicker control.**

Steps to reproduce:

**1. Use following stackblitz links to reproduce issue. In that, the form control is SET as to update only on blur. Also I added alter message on valueChange event.**
2. Use both link and change date by removing from input box using 'Backspace/Delete' keyword.
3. You can see in version @angular/material 7.2.2 it respecting blur event and will not show alert of change event.
4. For @angular/material 7.3.1, you will see the alert message after the removing or modifying dates using 'Backspace/Delete' keyword.
5. As focus is not change from control so it should not emit the change event because it set as to change on blur.
 

Here is example with @angular/material 7.3.1 version in which have issue.

https://stackblitz.com/edit/datepicker-issue-with-angularmaterial-731

Earlier version (@angular/material 7.2.2), the blur event was working fine.

https://stackblitz.com/edit/datepicker-issue-with-angularmaterial-722

This issue exist in @angular/material 8.0.2 as well.
 
#### Expected Behavior

formControl blur event should work properly and it emit change event only if we focus out from control.

#### Actual Behavior

Form Control datepicker triggering the change event while modifying the date on control even it set as updateOn blur.

#### Environment

- Angular: 8.0.1
- CDK/Material:8.0.1 and latest
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows 10

**Comment by jerome-nelson** [comment] 2019-07-08 15:31
Still investigating but this specifically seems to occur when attempting to delete the `/` after deleting a date section.

Able to reproduce on local build as well

**Comment by sudd03** [comment] 2019-07-09 10:49
Yes, it occur when we are deleting the date.

**FYI, I found issue with following code from datepicker.es5.js ('node_modules\@angular\material\esm5')**

```
/**
     * @param {?} value
     * @return {?}
     */
    MatDatepickerInput.prototype._onInput = /**
     * @param {?} value
     * @return {?}
     */
    function (value) {
        /** @type {?} */
        var date = this._dateAdapter.parse(value, this._dateFormats.parse.dateInput);
        this._lastValueValid = !date || this._dateAdapter.isValid(date);
        date = this._getValidDateOrNull(date);
        if (!this._dateAdapter.sameDate(date, this._value)) {
            this._value = date;
            this._cvaOnChange(date);
            this._valueChange.emit(date);
            this.dateInput.emit(new MatDatepickerInputEvent(this, this._elementRef.nativeElement));
        }
        else {
            **this._validatorOnChange();**
        }
    };

```

I attached the files with debug information and found that the 'this._dateAdapter.sameDate' failing for when you remove '/' and earlier one character. Since the years and date is coming as same. See screenshot.

![1](https://user-images.githubusercontent.com/6922390/60882292-26ed6700-a265-11e9-9b82-72be454a544d.png)

![2](https://user-images.githubusercontent.com/6922390/60882291-2654d080-a265-11e9-8099-3fa77dff3d55.png)

![3](https://user-images.githubusercontent.com/6922390/60882290-2654d080-a265-11e9-8cb0-f12145486e9c.png)




Due to this in else part it triggering the '_validatorOnChange' and emitting value change.

Sharing with you so it will help for fix. 


--
Sudhir.

**Comment by jerome-nelson** [comment] 2019-07-11 08:34
Good catch @sudd03 - it seems simply adding a 'hasFocus' condition preventing the validateOnChange from firing would be the way to go. 

You're welcome to contribute

**Comment by sudd03** [comment] 2019-07-11 10:57
Sure, I'd love to do contribution for fix.

Thanks.

**Comment by jerome-nelson** [comment] 2019-07-11 11:15
Check here
https://github.com/angular/components/blob/master/CONTRIBUTING.md

**Comment by jerome-nelson** [comment] 2019-07-17 16:48
@sudd03  any luck? I can take this otherwise

**Comment by sudd03** [comment] 2019-07-19 15:30
Hi, Jerome,

I fixed it locally but unable to publish due to permission issue on git master branch.

Getting following error. Any suggestion do you have how to resolve permission on master branch? 

_Permission to angular/components.git denied to sudd03._

**Comment by jerome-nelson** [comment] 2019-07-20 17:35
@sudd03 We are not allowed to create branches on `angular/components`. You need to fork the repo, not clone and then do a PR from your fork to `angular/components` :-)

**Comment by sudd03** [comment] 2019-07-21 10:47
Thank you. I submitted the pull request for review. :)

**Comment by jerome-nelson** [comment] 2019-07-22 08:40
Nice going. Ok so you need to commit these changes on a new branch not on master. And then you add that branch for PR against angular/components master branch

Like this:
https://github.com/angular/components/pull/16579

You'll know you did it correctly when the `angular/components` CI starts to test your PR

**Comment by sudd03** [comment] 2019-07-23 09:21
Hi,

There is issue with CLA getting. Even I singed it and reply as well with comments. Other tests are passed but two test are failed due to CLA.

![cla-issue](https://user-images.githubusercontent.com/6922390/61699729-12c36280-ad59-11e9-9aaf-fc5e239b8a0a.png)

Any suggestion have here?

**Comment by SleekPanther** [comment] 2019-07-23 21:03
https://github.com/angular/components/blob/master/CONTRIBUTING.md#-signing-the-cla has information about the CLA
It also looks like you're missing some labels for what kind of code change it is, this case it's probably a **fix**

**Comment by sudd03** [comment] 2019-07-24 08:37
Yes, the labels was about CLA agreement. I signed that CLA but won't resolve.  It maybe due to git.config settings on my system vs git account email/name.

**Comment by ThomasBoersma** [comment] 2019-11-18 09:59
I am still facing this issue and I saw that the PR still needs to be merged. What is the update on this? Is there maybe a workaround?

Thanks.

**Comment by SleekPanther** [comment] 2019-11-19 03:59
@ThomasBoersma Unfortunately I still don't think it will let him submit the pull request. I haven't tried myself.
The code change was minor but the bug definitely still exists and we are forced to stay on Angular 7 for this reason.
If you want to try and get the pull request approved yourself, please do. We just want to get the issue fixed and passing the pull requests commit checks is the blocker.

**Closed** 2019-12-29 22:33 UTC
Labels: P3, has pr
