### ISSUE TITLE
bug(DragDropModule): Dropping element to child cdkDropList adds the element to parent cdkDropList

### ISSUE THREAD

**Issue by mureedhussain1** [angular/components#24150] opened 2022-01-01 09:54 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Dropping the element in child cdkDropList is adding the element to the parent cdkDropList and the CdkDragDrop event is called for parent cdkDropList with data of parent's cdkDropList

There is need for alternative of event.stopPropagation() or $event.preventDefault() in the DragDropModule.

Check the drop behavior in child cdkDropList (Section) on https://stackblitz.com/edit/angular-ivy-wmgqoh

### Reproduction

https://stackblitz.com/edit/angular-ivy-wmgqoh

Steps to reproduce:
1. Drag section element from left cdkDragList to the black dotted cdkDropList
2. A child cdkDropList with the green dashed border should be added inside the parent cdkDropList
3.  Drag section element from left cdkDragList and Drop it in the child cdkDropList

### Expected Behavior

The element should be added to the child cdkDropList with the green dashed border

### Actual Behavior

The element is added to the parent cdkDropList with the black dashed border

### Environment

- Angular: 13.1.1
- CDK/Material: 13.1.1
- Browser(s): Chrome, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by crisbeto** [comment] 2022-01-03 05:27
Duplicate of https://github.com/angular/components/issues/16671.

**Closed by crisbeto** 2022-01-03 05:27 UTC
Labels: needs triage
