### ISSUE TITLE
feat(mat-slide-toogle): Add matPrefix and matSuffix to toggle

### ISSUE THREAD

**Issue by oneclickwebstudio** [angular/components#19956] opened 2020-07-13 08:37 UTC
#### Feature Description
It would be great if you add this feature
```
<mat-slide-toggle> 
    <mat-label matPrefix>Negative</mat-label> 
    <mat-label matSuffix>Positive</mat-label> 
</mat-slide-toggle>
```

#### Use Case

Both labels could be clickable from left and right
![image](https://user-images.githubusercontent.com/5783161/87282522-2ccff500-c516-11ea-9f58-079ae17001be.png)

**Comment by andreElrico** [comment] 2020-07-13 11:35
this can be achieved very easily

https://stackblitz.com/edit/angular-tvc3kw?file=src%2Fapp%2Fslide-toggle-overview-example.html

**Comment by oneclickwebstudio** [comment] 2020-07-13 17:22
> this can be achieved very easily
> 
> https://stackblitz.com/edit/angular-tvc3kw?file=src%2Fapp%2Fslide-toggle-overview-example.html

Thx! before posting this feature request I did it the same way as you wrote.

I think it would be better if owner adds `matPrefix` and `matSuffix` to the labels inside the `mat-slide-toggle`

**Comment by devversion** [comment] 2020-07-14 06:58
Hello! Thanks for this feature request! Definitely seems like a reasonable use-case.

Though, I haven't seen such pattern in the Google Material Design specification, and given that this is easily achievable with basic text nodes before the slide-toggle, it seems like something we won't be able to support.

This is also related to accessibility. At first glance it seems problematic to have two labels attached to the same slide-toggle. i.e. there would need to be a third label that describes the control as a whole. That is actually the intended behavior of the text label in a Material Design switch. The spec only mentions a single inline label for a control such as a switch.

Happy to discuss this more, but I'm closing this as it seems undesirable for the slide-toggle (given spec and accessibility).

**Closed by devversion** 2020-07-14 06:58 UTC
Labels: feature, needs triage
