### ISSUE TITLE
mdInput type="date" should be easier to interchange with dates

### ISSUE THREAD

**Issue by dstone760** [angular/components#3848] opened 2017-03-30 15:12 UTC
#### Bug, feature request, or proposal:

Proposal: mdInput should be easier to use with javascript date objects, and should not require formatting to set

#### What is the expected behavior?

If mdInput is a date type, then I would expect that setting its ngModel to a date would easily recognized and handled.

#### What is the current behavior?

If you pass in a date to an mdInput with type date, then the data is not displayed until the thing being passed in is EXACTLY the format the mdInput is in (by default, yyyy-MM-dd)

#### What are the steps to reproduce?

Code similar to this should be demonstrative enough
`
<md-input-container>
  <input mdInput [(ngModel)]="yourDate" placeholder="Some Date" type="date">
</md-input-container>
`
while in your TS/JS
`
this.yourDate = new Date();
`

#### What is the use-case or motivation for changing an existing behavior?

The motivation for the change is that, instead of working directly with JS date objects, we have to work with date strings, and any changes have to formatted to the mdInput format and remade to a JS Date object to work with many other technologies. Like, currently, we bring in a date for a database, and to set it on the page I have to say

`
this.yourDate = databaseDate.toISOString().split("T")[0]
`

which just seems incredibly silly. 

#### Is there anything else we should know?

Seeing as this is incredibly silly, there might be an already existing solution or easy fix. Could easily be missing something here.

**Comment by dstone760** [comment] 2017-04-02 16:42
I wouldn't consider this closed, but I at least found an easier way to handle this than what I was doing:

`<md-input-container">
     <input mdInput [ngModel]="myDate | date:'yyyy-MM-dd'"
         (ngModelChange)="myDate=formatToDate($event); otherStuffToDo()"
        placeholder="Some Date"
        type="date">
</md-input-container>`

and in the TS

`
private formatToDate(stringDate){
        let dateParts = stringDate.split("-");
        let date = new Date(dateParts[0], dateParts[1]-1, dateParts[2]);
        return date;
}
`
It still seems like I shouldn't have to do this, but for now, this is probably the best solution.

**Comment by lengtche** [comment] 2017-08-30 15:59
Could you maybe get away by using a directive to format your date?

I'm using Moment.js and created the following directive to format date times.

```
import {
    Directive,
    ElementRef,
    HostListener
} from '@angular/core';

@Directive({
    selector: '[dateTime]'
})
export class MomentDirective {
    constructor(private elemRef: ElementRef) {

    }

    @HostListener('ngModelChange', ['$event']) onInputChange(value: any) {
        this.elemRef.nativeElement.value = 'potato'
    }
}
```

**Comment by shrutigramopadhye30** [comment] 2018-03-23 10:29
Bug, feature request, or proposal: Feature request
What is the expected behavior?: In mat-datepicker, if user inputs the date manually, it should be auto formatted to 'MM/dd/yyyy'
What is the current behavior?: ngx-mask cannot be used with Angular Material.
I tried inserting '/' after date and month by calculating length.
But format is not getting inserted.

What are the steps to reproduce?
Providing a StackBlitz reproduction is the best way to share your issue. 

StackBlitz starter: https://goo.gl/wwnhMV

What is the use-case or motivation for changing an existing behavior?: If user enters a date without using datepicker, it should be viewed in date format MM/dd/yyyy
Which versions of Angular, Material, OS, TypeScript, browsers are affected?: Angular 5 with Angular Material

**Comment by jelbourn** [comment] 2020-04-28 17:41
Closing this since I think it's obsolete.

**Closed by jelbourn** 2020-04-28 17:41 UTC
Labels: feature, needs discussion
