### ISSUE TITLE
Angular Material snack-bar Direction Type aliases is missing

### ISSUE THREAD

**Issue by anieshvishnu** [angular/components#16148] opened 2019-05-29 11:27 UTC
#### Documentation Feedback

MatSnackBarConfig propert 'direction: Direction' the type Direction are not explained. It would be help full if it is defined in the Type Aliases like mentioned below.

*Direction*

**Possible values for direction on MatSnackBarConfig.**

**type Direction = 'ltr' | 'rtl' ;**

**Affected documentation page:** Insert a link to the affected page on material.angular.io

https://material.angular.io/components/snack-bar/api#type_aliases

**Comment by jelbourn** [comment] 2021-05-25 23:59
Duplicate of #18414

**Closed by jelbourn** 2021-05-25 23:59 UTC
Labels: P3, area: material/snack-bar, docs
