### ISSUE TITLE
bug(CdkVirtualScroll + CdkDragDrop): Drag item and scroll inside a virtual scroll viewport | items get messed up

### ISSUE THREAD

**Issue by kichnan** [angular/components#22900] opened 2021-06-05 05:16 UTC
#### Reproduction

Drag an item in a CDK Drop List which is contained inside a CDK Virtual Scroll Viewport. After a certain point when auto-/manual-scrolling the viewport (while the item is still being dragged), the items in the main drop list view start to overlap and break out of their layout.

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-ivy-kmwblc?file=src/app/app.component.ts
- Harnesses: NA

Steps to reproduce:
1. Add a <cdk-virtual-scroll-viewport style="height: 500px"> element.
2. Add a <div *cdkVirtualFor="loop data here">
3. Start dragging any item, say you start dragging item no. 5.
4. Reach till end of the viewport so that auto-scrolling starts or do manual-scrolling using mouse middle wheel. Either way...
5. After certain point, say item 21, the list view gets messed up/garbled. There is overlap of data items in the screen.
 
#### Expected Behavior

What behavior were you expecting to see?

Items in the background list view should not overlap.

Also, after the item is dropped, depending on the drop logic, the messed up view either _resets_ back to normal (no issue), or _sticks_ (the messed up view persists).

#### Actual Behavior

What behavior did you actually see?

The list view gets messed up/garbled -- some data items overlap each other. _Data item being dragged_ appears in the background list view too, even though it is still being dragged.

![image](https://user-images.githubusercontent.com/1217487/120880673-4e801200-c5e9-11eb-8151-139486e86dd7.png)

#### Environment

- Angular: 11, 12
- CDK/Material: 11, 12
- Browser(s): Chrome, Firefox, Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, macOS

**Comment by kichnan** [comment] 2021-06-05 10:59
Found an older issue stating the exact same issue. #19003, which makes this issue a duplicate. Please advise.

**Comment by crisbeto** [comment] 2021-06-08 05:23
Closing as a duplicate of https://github.com/angular/components/issues/10122. It's not something that we support at the moment.

**Closed by crisbeto** 2021-06-08 05:23 UTC
Labels: needs triage
