### ISSUE TITLE
bug(mat-tab): iframe reloads on tab change

### ISSUE THREAD

**Issue by hoanghuynh** [angular/components#22993] opened 2021-06-16 08:30 UTC
#### Reproduction

1. Embed an iframe in a tab content
2. Move to another tab and switch back
3. The iframe is reset

Preview : https://stackblitz.com/edit/tab-iframe-reset?file=src/app/app.component.html

(This is reported previously as #5239.)
 
#### Expected Behavior

The iframe doesn't reload.

#### Actual Behavior

The iframe reloads.

**Comment by crisbeto** [comment] 2021-06-16 16:06
Duplicate of https://github.com/angular/components/issues/19480.

**Closed by crisbeto** 2021-06-16 16:06 UTC
Labels: needs triage

**Comment by hoanghuynh** [comment] 2021-06-17 10:53
Thank for the quick triage and the MR @crisbeto!
