### ISSUE TITLE
[mat-tab-nav-bar] does not set active following the documentation example 

### ISSUE THREAD

**Issue by Warriormuffin** [angular/components#15316] opened 2019-02-26 16:33 UTC
#### What is the expected behavior?
Documentation has a usuable code version of a feature the website is claiming works

#### What is the current behavior?
Bring the example code from the website and the rla.isActive is never set.

#### What are the steps to reproduce?
Have an Angular 7 project and try and use the example from the website for [mat-tab-nav-bar] it is incomplete and doesn't work

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.1.0

**Comment by paesku** [comment] 2019-05-24 08:12
Sure you've setup your tabs correctly? To me the docs seems right and it's all working fine:

```typescript
interface TabNavigationTab {
  routerLink: any[];
  label: string;
}

@Component({
  selector: 'app-tab-navigation',
  template: `
    <nav mat-tab-nav-bar>
      <a *ngFor="let tab of tabs"
         mat-tab-link
         [routerLink]="tab.routerLink"
         routerLinkActive
         #RouterLinkActive="routerLinkActive"
         [active]="RouterLinkActive.isActive">
        {{tab.label}}
      </a>
    </nav>
   <router-outlet></router-outlet>
  `,
})
export class TabNavigationComponent {
 tabs: TabNavigationTab[];
}
``

**Comment by jkyoutsey** [comment] 2019-09-10 15:10
I'm seeing the same thing and wondering if this has to do with relative paths and redirects?
I have routing configuration:
```
const routes: Routes = [
	{
		path: '',
		component: ResidencyComponent,
		children: [
			{
				path: '',
				redirectTo: 'home'
			},
			{
				path: 'home',
				component: DashboardComponent
			},
			{
				path: '*',
				redirectTo: 'home'
			}
		]
	}
];
```
The tabs live in ResidencyComponent since they'll be present for all of the child routes.  I think the problem is that the mat nav tab thinks the route should be /residency/home, but on the Residency component the route is always just /residency.

I've tried every possible setting for the route in my tab config: `home`, `/home`, `./home`, `residency/home`, `/residency/home`, `./residency/home`.  None of these will set the link to active.

The docs do not link to a stackblitz that actually routes. It's pretty "faked".  Enough so that it's really not a valid example.

**Comment by jkyoutsey** [comment] 2019-09-10 17:57
A simple workaround is to import router into your component and then use this in the template:
```
[active]="rla.isActive || router.url === '/residency/' + link.path"
```

**Comment by StefanChristou** [comment] 2020-04-06 15:23
I just wanted to chime in that sometimes the issue could be caused by the activated route being true for more than one route.

If you've hit this issue try adding `[routerLinkActiveOptions]="{ exact: true }"` inside your `a` tag, for example:

```<div class="content mat-tab-full-height">
  <nav mat-tab-nav-bar>
    <a mat-tab-link *ngFor="let linkItem of linkItems"
       [routerLink]="linkItem.route"
       routerLinkActive #rla="routerLinkActive"
       [routerLinkActiveOptions]="{ exact: true }"
       [active]="rla.isActive"> {{ linkItem.name }} </a>
  </nav>
</div>```

**Comment by jelbourn** [comment] 2020-05-26 22:13
(revisiting older issues as part of a triaging fix-it)

Closing this because AFAICT it's working as intended. You may need to specify `routerLinkActiveOptions` to get the behavior you want, but the example on the docs works for most cases.

**Closed by jelbourn** 2020-05-26 22:13 UTC
Labels: docs, needs triage
