### ISSUE TITLE
Rounding Error with scrollToIndex - Looks like an extra pixel is added when using scrollToIndex

### ISSUE THREAD

**Issue by christo8989** [angular/components#18388] opened 2020-02-04 19:47 UTC
#### Reproduction

https://stackblitz.com/edit/material-scroll-rounding-error

Steps to reproduce:
1. Keep clicking "NEXT"
 
 
#### Expected Behavior

What behavior were you expecting to see?
Moving next shouldn't make the item look like it moved down. In essence, a pixel is being added at the top and so the view is not on the next item but still on the previous item.

#### Actual Behavior

What behavior did you actually see?
The scroll should be at the top of the next item.

#### Environment

- Angular: 7
- CDK/Material: 7
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**EDIT**
This only breaks on my laptop. When I plug into the ThinkPad station, the StackBlitz doesn't break. Maybe the issue has to do with screen size as well.

Material Scroll Error (Laptop only)
https://i.imgur.com/cTzlSrk.mp4

**Comment by christo8989** [comment] 2020-02-04 19:48
I should note that I am changing the item size to fix the problem in the meantime. 
So, this bug might be low priority.

**Comment by christo8989** [comment] 2020-02-04 22:36
Maybe related to #15259

**Comment by wagnermaciel** [comment] 2020-08-06 23:17
@jelbourn and I tested this on a few different machines with various screen sizes and couldn't get it to reproduce. Do you have more information about the environment for which this happens?

**Comment by jelbourn** [comment] 2020-10-09 18:35
Closing since we haven't been able to reproduce this on our end.

**Closed by jelbourn** 2020-10-09 18:35 UTC
Labels: P4, area: cdk/scrolling, cannot reproduce, needs clarification
