### ISSUE TITLE
mat-form-field with appearance outline doesn't work well

### ISSUE THREAD

**Issue by AlirezaPhf** [angular/components#17797] opened 2019-11-23 11:33 UTC
#### Bug, feature request, or proposal:
i change body direction to rtl
dir="rtl" 
and mat-form-field with appearance"outline" doesn't work well
you can try it in https://material.angular.io site, in examples of Form field appearance variants
section and edit on stack,and change body direction to rtl.
you see which It doesn't work properly

#### What is the expected behavior?
![current](https://user-images.githubusercontent.com/48950088/69477977-4515c700-0e02-11ea-940e-83c74011bbee.JPG)

#### What is the current behavior?
![01](https://user-images.githubusercontent.com/48950088/69477934-98d3e080-0e01-11ea-843b-dcdaf9adef27.JPG)

pls help me!

**Comment by PerezArmando** [comment] 2019-11-23 13:02
Could you please add a `https://stackblitz.com/` sample?

**Comment by AlirezaPhf** [comment] 2019-11-23 13:10
> Could you please add a [(StackBlitz)](https://stackblitz.com/) sample? Thanks!

of course
[Stackblitz](https://angular-stsmay.stackblitz.io)

**Comment by crisbeto** [comment] 2019-11-24 07:07
Closing as a duplicate of https://github.com/angular/components/issues/17390.

**Closed by crisbeto** 2019-11-24 07:07 UTC
