### ISSUE TITLE
bug(MAT-SELECT): value of select is not updated

### ISSUE THREAD

**Issue by gianlucaUlivo** [angular/components#24340] opened 2022-02-02 15:42 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

if ther are 2 mat-select binded with formControl on the same field, and i change the value of one select, the displayed value is not updated in other select, but the mat-hint yes

### Reproduction

Steps to reproduce:
1. go to https://stackblitz.com/edit/angular-uk6pdr?file=src%2Fapp%2Fselect-hint-error-example.html
2. change the value of one select

### Expected Behavior

the other select value is updated

### Actual Behavior

only the hint change in other select

### Environment

- Angular:13
- CDK/Material:13.2
- Browser(s):chrome
- Operating System : Windows

**Comment by crisbeto** [comment] 2022-02-08 14:14
This has come up in the past, but I'm having trouble digging up the issue. The problem is that the `ReactiveFormsModule` doesn't propagate the changes back to the `ControlValueAccessor` so `mat-select` doesn't know that the value has changed. Here's an example that doesn't with a plain `input` either: https://stackblitz.com/edit/angular-uk6pdr-9h44oa?file=src%2Fapp%2Fselect-hint-error-example.html

Closing since we can't do much about it.

**Closed by crisbeto** 2022-02-08 14:14 UTC
Labels: needs triage
