### ISSUE TITLE
mat-slider thumb briefly disappears on touch release (iOS 13 Safari)

### ISSUE THREAD

**Issue by tlangmo** [angular/components#17581] opened 2019-11-01 22:08 UTC
#### Reproduction

Steps to reproduce:
1. Using any iOS 13 device, go to  https://material.angular.io/components/slider/overview
2. Drag the slider around. 
 
 
#### Expected Behavior

The slider thumb should stay visible all the time when dragging and releasing it.

#### Actual Behavior

On release of the slider, the thumb briefly disappears. This flickering is very distracting. It happens not all the time, but about 70%. It seems to be also more likely to happen when the slider is dragged towards the end. iOS 12 and previous worked fine.

#### Environment

- Angular: 8.2.2
- CDK/Material: 8.2.2, 7.3.7
- Browser(s): iOS 13 Mobile Safari
- Operating System (e.g. Windows, macOS, Ubuntu): iOS 13
![mat-slider-ios13-flicker](https://user-images.githubusercontent.com/11821291/68059027-671f9c00-fcd1-11e9-9c38-023ffde5bc82.gif)

**Comment by crisbeto** [comment] 2020-05-26 15:42
I couldn't reproduce it against a couple of iOS 13 devices. Closing the issue since the slider has gone through some refactoring that may have fixed the issue.

**Closed by crisbeto** 2020-05-26 15:42 UTC
Labels: needs triage
