### ISSUE TITLE
Can't find stylesheet to import: @use '~@angular/material' as mat;

### ISSUE THREAD

**Issue by angelaki** [angular/components#23889] opened 2021-11-04 08:33 UTC
Using the latest Angular Material version (13.0.0) the first line of my theme.scss throws an error:

```
SassError: Can't find stylesheet to import.
  ╷
2 │ @use '~@angular/material' as mat;
```

I've checked the `next-versions`: it was working with `13.0.0-next.7` and stopped working from `13.0.0-next.8` on.

**Comment by crisbeto** [comment] 2021-11-04 09:44
You should change the `@use '~@angular/material'` to `@use '@angular/material'`. We have an automated migration that should've cleaned it up for you. Did you update manually or through `ng update`?

**Comment by angelaki** [comment] 2021-11-04 10:54
Wasn't set automatically via `ng update` but works just fine! 👍

The current build literally warns a million times

`Warning:  > styles.39057a08ff4d2181.css:9051:0: warning: "@charset" must be the first rule in the file
    9051 │ @charset "UTF-8";` while it only occurred once with the previous version. Is this normal?

**Comment by crisbeto** [comment] 2021-11-04 11:25
I haven't seen that warning before, but it seems like it's coming from a Webpack loader, rather than Sass.

**Comment by devversion** [comment] 2021-11-04 11:32
@angelaki From what version did you run `ng update`? was your project already on a v13 next or RC release?

**Comment by angelaki** [comment] 2021-11-04 12:10
Yeah, it was already - guess that's the problem. Do you want me to simulate a clean update?

Grüße

Tristan Sprößer
________________________________

**Comment by Heatmanofurioso** [comment] 2021-11-04 13:18
I updated through `ng update` from v12 and I also get the charset warning across everywhere when I run my prod build

**Comment by devversion** [comment] 2021-11-04 13:44
> Yeah, it was already - guess that's the problem. Do you want me to simulate a clean update?

Not necessarily needed. We have an integration test that runs `ng update` for `@angular/material` and the CDK. It's a known "issue" that `ng update` will not re-run migrations when your project is already on a next version.

The charset warnings are surprising and I'm unsure if this is something caused on our end? are there any signs that made you think this is caused by Angular Material? happy to look more into this.

**Comment by Kralone** [comment] 2021-11-05 14:48
Have the same issue after updated my angular cli with material. An issue as been raised here : https://github.com/angular/angular-cli/issues/22097 and here : https://github.com/angular/angular-cli/pull/22098
Hope that can bring some help !

**Comment by devversion** [comment] 2021-11-05 15:06
Thanks @Kralone, let's track this with the CLI. it seems like there is even an fix from the CLI side for that.

Closing because:

* The charset issue is tracked with: https://github.com/angular/angular-cli/issues/22097. 
* The stylesheet import issue only surfaced because the `ng update` migration did not run. 
   * All tilde imports with Webpack will no longer with Angular CDK/Material v13.
   * Re-run the migration with `ng update @angular/cdk --migrate-only --from 12.0.0 --to 13.0.0` if you already were on v13, and the migration did not re-run.

**Closed by devversion** 2021-11-05 15:06 UTC
Labels: needs clarification, needs triage

**Comment by hheexx** [comment] 2021-11-05 18:00
@devversion I have rerun the migration but it just nooped

**Comment by devversion** [comment] 2021-11-05 18:03
@hheexx when you ran `ng update`, was your project already on a v13 next or RC release?

**Comment by devversion** [comment] 2021-11-05 19:28
that's interesting. We have an integration test for this, so I'm surprised. The original poster of this issue was on a v13 next release already, so that explains this scenario.

If you have more details, a new issue would be appreciated. If others also run into this, and are not on v13 when running ng update, please also submit an issue.

(it looks like we haven't gotten any other reports so far)

**Comment by devversion** [comment] 2021-11-05 20:52
Just re-tested, the migration ran as expected on the `material.angular.io` v12 app:

```
$ ng update @angular/material @angular/material-experimental @angular/cdk-experimental
Using package manager: 'yarn'
Collecting installed dependencies...
Found 61 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cdk @ "13.0.0" (was "12.2.12")...
    Updating package.json with dependency @angular/cdk-experimental @ "13.0.0" (was "12.2.12")...
    Updating package.json with dependency @angular/material @ "13.0.0" (was "12.2.12")...
    Updating package.json with dependency @angular/material-experimental @ "13.0.0" (was "12.2.12")...
    Updating package.json with dependency @angular/material-moment-adapter @ "13.0.0" (was "12.2.12")...
    Updating package.json with dependency material-components-web @ "14.0.0-canary.1af7c1c4a.0" (was "12.0.0-canary.5f00e454a.0")...
  UPDATE package.json (4221 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cdk' **

> Updates the Angular CDK to v13.

      ✓  Updated Angular CDK to version 13

  UPDATE scenes/src/styles.scss (1167 bytes)
  UPDATE src/styles.scss (485 bytes)
  UPDATE src/_app-theme.scss (2514 bytes)
  UPDATE src/app/pages/component-category-list/_component-category-list-theme.scss (1178 bytes)
  UPDATE src/app/pages/component-sidenav/_component-sidenav-theme.scss (1612 bytes)
  UPDATE src/app/pages/component-viewer/_component-viewer-theme.scss (569 bytes)
  UPDATE src/app/pages/guide-list/_guide-list-theme.scss (778 bytes)
  UPDATE src/app/pages/homepage/_homepage-theme.scss (1537 bytes)
  UPDATE src/app/pages/not-found/_not-found-theme.scss (657 bytes)
  UPDATE src/app/shared/carousel/_carousel-theme.scss (448 bytes)
  UPDATE src/app/shared/cookie-popup/cookie-popup.scss (538 bytes)
  UPDATE src/app/shared/cookie-popup/_cookie-popup-theme.scss (606 bytes)
  UPDATE src/app/shared/example-viewer/_example-viewer-theme.scss (1036 bytes)
  UPDATE src/app/shared/footer/_footer-theme.scss (392 bytes)
  UPDATE src/app/shared/navbar/_navbar-theme.scss (686 bytes)
  UPDATE src/app/shared/table-of-contents/_table-of-contents-theme.scss (666 bytes)
  UPDATE src/assets/stack-blitz/src/styles.scss (211 bytes)
  UPDATE src/assets/stack-blitz-tests/src/styles.scss (298 bytes)
  UPDATE src/styles/_api-theme.scss (1506 bytes)
  UPDATE src/styles/_markdown-theme.scss (1113 bytes)
  UPDATE src/styles/_svg-theme.scss (1775 bytes)
  UPDATE src/styles/_tables-theme.scss (661 bytes)
  UPDATE src/styles/custom-themes/deeppurple-amber.scss (345 bytes)
  UPDATE src/styles/custom-themes/indigo-pink.scss (339 bytes)
  UPDATE src/styles/custom-themes/pink-bluegrey.scss (362 bytes)
  UPDATE src/styles/custom-themes/purple-green.scss (378 bytes)
  Migration completed.

** Executing migrations of package '@angular/material' **

> Updates Angular Material to v13.

      ✓  Updated Angular Material to version 13

  Migration completed.

Done in 57.97s.

paul@paul-windows MINGW64 ~/projects/material.angular.io (12.x)
$ yarn start
yarn run v1.22.11
$ ng serve
✔ Browser application bundle generation complete.

```

As said, if anybody faces an issue where `ng update` did not run properly (while your app was not on v13 already), please create another issue and we'll do our best looking into it! Thanks!

**Comment by hheexx** [comment] 2021-11-05 21:59
If anybody else reports the problem I will create the issue. Thanks!

**Comment by 6ygga** [comment] 2021-11-07 06:22
I had the same issue after migration from 12 to 13 ver:

Build at: 2021-11-07T06:12:19.257Z - Hash: 238020893e14045d - Time: 327ms

./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].rules[0].oneOf[1].use[1]!./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[
4].rules[0].oneOf[1].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[4].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].rules[1].use[1]!./src/styles.scss - Error: Module build failed (
from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @use '~@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\assets\theme.scss 1:1  @import
  src\styles.scss 1:9        root stylesheet

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
6 │ @use '~@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\assets\theme.scss 6:1  @import
  src\styles.scss 2:9        root stylesheet
    at tryRunOrWebpackError (D:\Projects\SP\node_modules\webpack\lib\HookWebpackError.js:88:9)
    at __webpack_require_module__ (D:\Projects\SP\node_modules\webpack\lib\Compilation.js:4963:12)
    at __webpack_require__ (D:\Projects\SP\node_modules\webpack\lib\Compilation.js:4920:18)
    at D:\Projects\SP\node_modules\webpack\lib\Compilation.js:4991:20
    at symbolIterator (D:\Projects\SP\node_modules\neo-async\async.js:3485:9)
    at done (D:\Projects\SP\node_modules\neo-async\async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (D:\Projects\SP\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Projects\SP\node_modules\tapable\lib\Hook.js:18:14)
    at D:\Projects\SP\node_modules\webpack\lib\Compilation.js:4898:43
    at symbolIterator (D:\Projects\SP\node_modules\neo-async\async.js:3482:9)
-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
6 │ @use '~@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\assets\theme.scss 6:1  @import
  src\styles.scss 2:9        root stylesheet
    at Object.<anonymous> (D:\Projects\SP\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[4].rules[0].oneOf[1].use[1]!D:\Projects\SP\node_modules\@angular-devkit\build-angular\node_modules\postcss-loader\dist\cjs.js??ruleSet[1
].rules[4].rules[0].oneOf[1].use[2]!D:\Projects\SP\node_modules\resolve-url-loader\index.js??ruleSet[1].rules[4].rules[1].use[0]!D:\Projects\SP\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[4].rules[1].use[1]!D:\Projects\SP
\src\styles.scss:1:7)
    at D:\Projects\SP\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:432:11
    at Hook.eval [as call] (eval at create (D:\Projects\SP\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (D:\Projects\SP\node_modules\tapable\lib\Hook.js:14:14)
    at D:\Projects\SP\node_modules\webpack\lib\Compilation.js:4965:39
    at tryRunOrWebpackError (D:\Projects\SP\node_modules\webpack\lib\HookWebpackError.js:83:7)
    at __webpack_require_module__ (D:\Projects\SP\node_modules\webpack\lib\Compilation.js:4963:12)
    at __webpack_require__ (D:\Projects\SP\node_modules\webpack\lib\Compilation.js:4920:18)
    at D:\Projects\SP\node_modules\webpack\lib\Compilation.js:4991:20
    at symbolIterator (D:\Projects\SP\node_modules\neo-async\async.js:3485:9)

Generated code for D:\Projects\SP\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[4].rules[0].oneOf[1].use[1]!D:\Projects\SP\node_modules\@angular-devkit\build-angular\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[
4].rules[0].oneOf[1].use[2]!D:\Projects\SP\node_modules\resolve-url-loader\index.js??ruleSet[1].rules[4].rules[1].use[0]!D:\Projects\SP\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[4].rules[1].use[1]!D:\Projects\SP\src\sty
les.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: Can't find stylesheet to import.\n  ╷\n6 │ @use '~@angular/material' as mat;\r\n  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  ╵\n  src\\as
sets\\theme.scss 6:1  @import\n  src\\styles.scss 2:9        root stylesheet");

It was solved by deleting ' ~ '
@use '~@angular/material' as mat;
@use '@angular/material' as mat;

but my linter didn't like it)

**Comment by oneclickwebstudio** [comment] 2021-11-20 10:28
Without tilda sign works but stylint error occuring. 
![image](https://user-images.githubusercontent.com/5783161/142723016-7a1ef162-5608-4376-972c-c3d1c937fb95.png)
![image](https://user-images.githubusercontent.com/5783161/142723038-ee4de878-3c52-43d7-94b3-b8fa6101ad43.png)

**Comment by ecruz165** [comment] 2021-11-28 14:40
Adding the following to angular.js resolved this issue
```
"stylePreprocessorOptions": {
  "includePaths": [
    "src/assets/styles",
  ]
```

**Comment by davidecampello** [comment] 2021-12-01 16:35
> I no longer saw this issue once i added the following to angular.json
> 
> ```
> "stylePreprocessorOptions": {
>   "includePaths": [
>     "node_modules",
>     "src/assets/styles"
>   ]
> ```

This is working! Thank you

**Comment by richardsengers** [comment] 2021-12-07 13:53
Ok, but I've got a large mono repo...should I include this:

```
"stylePreprocessorOptions": {
  "includePaths": [
    "node_modules",
  ]
```

to all my projects?I've got a material theme  as a library included in all my projects. It doesn't feel it makes sense to remember I need to add the code above everytime I create a new project just because the ~has been deprecated

**Comment by ecruz165** [comment] 2021-12-09 16:43
It will likely be added to the script for upgrade and/or new project script when adding @angular/material. So, there is a need for this to be added until then if you are looking to use angular/material 13.
________________________________
