### ISSUE TITLE
Drag And Drop Connected Lists Issue

### ISSUE THREAD

**Issue by rudineymc** [angular/components#19360] opened 2020-05-14 17:24 UTC
## Bug, enhancement request, or proposal

Bug

# Demo and steps to reproduce the issue

https://stackblitz.com/edit/angular-9-material-drag-drop?file=src%2Fapp%2Fapp.component.html

#### Detailed Reproduction Steps
1. Add the cdkDrag item inside another tag whose parent is not the cdkList.
2. Grab an element in the above list.
3. Drag it to the second connected list

### Explain the expected behavior

In angular material V8. Version 9 should behave the same way.

### Explain the current behavior

Error in /turbo_modules/@angular/cdk@9.2.3/bundles/cdk-drag-drop.umd.js (1676:29)
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### List the affected versions of AngularJS, Material, OS, and browsers

- Angular: 9.1.4
- Angular Material: 9.2.2
- OS: MacOS Catalina
- Browsers: Chrome

#### Screenshots

![image](https://user-images.githubusercontent.com/48571822/81965546-71521980-95d5-11ea-9263-dd46ec15c340.png)

**Comment by crisbeto** [comment] 2020-05-14 19:05
Duplicate of https://github.com/angular/components/issues/19359.

**Closed by crisbeto** 2020-05-14 19:05 UTC
Labels: needs triage
