### ISSUE TITLE
Ripple Effect Still Present After Click, Despite disableRipple Being Set

### ISSUE THREAD

**Issue by cfoxy17** [angular/components#22962] opened 2021-06-11 21:07 UTC
Steps to reproduce:
1. Click the calendar icon
2. Click away from the calendar icon
3. See that the ripple effect is still there after

https://stackblitz.com/edit/angular-material-disable-ripple-animation-taekj8?file=app%2Fapp.component.html
 
 
![image](https://user-images.githubusercontent.com/50955085/121748789-91555480-cad7-11eb-94bc-0e99b4855ca8.png)

**Comment by devversion** [comment] 2021-06-12 14:26
Unless I miss something, your demo currently only shows a select. I've tried to reproduce in my own StackBlitz using a datepicker with the toggle button and `[disableRipple]="true"`. The "persistent" ripple effect shows when closing the datepicker to indicate that focus is on the button. This would be expected for accessibility.

Could you please provide more information if you are referring to something else?

**Comment by crisbeto** [comment] 2021-09-15 16:43
Closing due to inactivity. The issue can be reopened if we get more information.

**Closed by crisbeto** 2021-09-15 16:43 UTC
Labels: needs clarification, area: material/datepicker
