### ISSUE TITLE
feat(MatSelect): Add an option to search from the beginning of the options when typing

### ISSUE THREAD

**Issue by JohnKis** [angular/components#20199] opened 2020-08-05 10:56 UTC
#### Feature Description

Add an option to MatSelect to search the entire option list when typing.

#### Use Case

MatSelect allows jumping to an option when the list is open and the user starts typing. This is great however the current implementation only tries to match options after the currently selected option. While this may be useful in some cases, in others it might force the user to use the mouse or arrow keys and it also differs in behaviour from the native `<select>` tag.

The following example has both a MatSelect and a native select with options going from 0 to 150: [https://stackblitz.com/edit/angular-rb2rje?file=src%2Fapp%2Fselect-overview-example.ts](https://stackblitz.com/edit/angular-rb2rje?file=src%2Fapp%2Fselect-overview-example.ts)

The following steps highlight the expected scenario:
- Open select
- Type '1'
- Wait a little
- Type '5'
- Wait a little
- Type '1' again 

The active option will be '10' on MatSelect (since it only searches in options that are after the currently selected option) and '1' on the native select.

In this scenario, the only way to go back to values before 10 is either using the arrow keys or the mouse.

It'd be great if MatSelect had an option to mimic the native select's behaviour and search the entire list.

**Comment by crisbeto** [comment] 2020-08-05 11:30
The current logic is actually meant to mimic the native select, but I'm guessing that its behavior differs based on the OS. I was basing it on the one in Windows which will go to `10`. 

![demo](https://user-images.githubusercontent.com/4450522/89407793-b347b300-d71f-11ea-9a4c-71ff969dca7f.gif)

**Comment by JohnKis** [comment] 2020-08-05 12:15
You're right. I just checked it on Windows and it does indeed go to 10. On macOS though in Chrome and Safari it goes to 1.

**Comment by jelbourn** [comment] 2020-08-06 22:14
Just did some testing- the native select behaves the same on Windows, Linux (cinnamon), and ChromeOS, with macOS being the odd one out. This makes sense since the feature here is type_ahead_, implying it should be from the current position. Closing as working as intended.

**Closed by jelbourn** 2020-08-06 22:14 UTC
Labels: feature, needs triage

**Comment by JohnKis** [comment] 2020-08-07 07:06
I'm not disputing that the feature works as intended, however I still think it'd be useful to have an option to change it's behaviour.
