### ISSUE TITLE
bug(mat-list): form controls inside mat-list are not interactive

### ISSUE THREAD

**Issue by davidshen84** [angular/components#26035] opened 2022-11-20 05:29 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

```html
<mat-list role="list">
  <mat-list-item role="listitem">
    <mat-checkbox [formControl]="check">Check</mat-checkbox>
  </mat-list-item>
  <mat-list-item role="listitem">
    <input matInput readonly type="text" value="{{ result$ | async}}">
  </mat-list-item>
  <mat-list-item>
    <mat-slider min="0" max="100"><input matSliderThumb/></mat-slider>
  </mat-list-item>
</mat-list>
```

With Angular 14, the above code work as expected. I can interact with each form control in that list. But with Angular 15, the *checkbox* and the *input* are not interactable, but the *slider* is still interactable.

### Reproduction

Steps to reproduce:
1. Install ng 15
2. Create a new ng project, `ng new mat-list-test`
3. Replace the content of the `app.component.html` with the code above
4. Import necessary modules

### Expected Behavior

All the form controls inside the `mat-list` should be interactable.

### Actual Behavior

Some of the controls are not interactable.

### Environment

- Angular: 15
- CDK/Material: 15
- Browser(s): Chrome 107.0.5304.110 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Linux

**Comment by crisbeto** [comment] 2022-11-20 12:33
Duplicate of https://github.com/angular/components/issues/26010.

**Closed by crisbeto** 2022-11-20 12:33 UTC
Labels: needs triage
