### ISSUE TITLE
bug(COMPONENT): Dialog launched from a menu

### ISSUE THREAD

**Issue by Aisrah** [angular/components#29682] opened 2024-09-03 10:55 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When a dialog is launched from Menu Button click the following accessibility error appears in the console => “Blocked aria-hidden on a <button> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor.”

### Reproduction

Steps to reproduce:
1. Go to => https://material.angular.io/components/dialog/examples
2. Go to 'Dialog launched from a menu' example
3. When you open the dialog from menu button, this error appears in the console.

### Expected Behavior

The focus on menu button should be handled for non root triggers.

### Actual Behavior

The focus stays on the menu button and aria-hidden attribute gets applied at root of the DOM.  But the dialog opens up in non root DOM. Hence hiding the focussed element from assistive technology and throwing this error. 

### Environment

- Angular: 18.0.1
- CDK/Material: 18.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, macOS
![Uploading Screenshot 2024-09-03 at 12.55.54 PM.png…]()

**Comment by Aisrah** [comment] 2024-09-03 10:56
![Uploading Screenshot 2024-09-03 at 12.55.54 PM.png…]()

**Comment by crisbeto** [comment] 2024-09-03 15:15
Duplicate of https://github.com/angular/components/issues/29578.

**Closed by crisbeto** 2024-09-03 15:15 UTC
Labels: needs triage
