### ISSUE TITLE
Menu divider margins out of spec

### ISSUE THREAD

**Issue by thw0rted** [angular/components#14912] opened 2019-01-22 09:27 UTC
#### What is the expected behavior?
The [menu spec](https://material.io/design/components/menus.html#specs) shows that a divider in a menu is supposed to have an 8px top/bottom margin.  

#### What is the current behavior?
In the current implementation, the margin is zero.

#### What are the steps to reproduce?
[StackBlitz](https://stackblitz.com/edit/angular-material2-issue-menu-divider)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All? I guess?

#### Is there anything else we should know?
Trackback to #2017, where the feature was introduced.

**Comment by devversion** [comment] 2020-05-29 13:28
Ideally we'd fix this for our MDC-based menu (#16247). It seems like it would be good to figure out how that menu implementation plays together with the standalone `@angular/material/divider`.

MDC fixed this, and their demo's show this correctly.. Though our MDC-based menu currently still uses the non-mdc divider.

**Comment by jelbourn** [comment] 2020-05-29 22:51
Going to close this as a duplicate of #19248 since I already commented on that one; I don't think this is automatically fixed by MDC because the way we use `mat-divider`.

**Closed by jelbourn** 2020-05-29 22:51 UTC
Labels: Fixed in MDC, P3, area: material/divider, area: material/menu, material spec

**Comment by devversion** [comment] 2020-05-29 22:58
@jelbourn Sounds good. I didn't realize we had another issue for this. FWIW: I added `Fixed in MDC` as MDC has this fixed in _their_ menu-surface implementation, but just not we in our MDC version. The label might be slightly ambiguous.
