### ISSUE TITLE
MatTabGroup - Add ability to intercept tab changes

### ISSUE THREAD

**Issue by kenielsen** [angular/components#17506] opened 2019-10-25 16:29 UTC
#### Feature Description

As a developer, I would like a way to intercept tab changes in mat-tab-group and prevent the change under certain conditions

#### Use Case

This feature would enable us to stop tab changes if a form in the tab is dirty or invalid, show a pop-up, and prevent the tab change based on the user decision.

**Comment by jelbourn** [comment] 2019-10-31 17:15
Duplicate of #2013

**Closed by jelbourn** 2019-10-31 17:15 UTC
Labels: feature
