### ISSUE TITLE
bug(HarnessLoader): Including mat-tab-group in a template breaks getAllHarnesses

### ISSUE THREAD

**Issue by jacobweber** [angular/components#19368] opened 2020-05-15 04:37 UTC
#### Reproduction

Steps to reproduce:
1.  Create a new project with `ng new my-app`
2. Add material with `ng add @angular/material`
3. Drop the attached component [error.zip](https://github.com/angular/components/files/4632231/error.zip) into `app`.
4. Run the tests with `ng test`.

The component template just includes a `mat-tab-group` and a `mat-button`:
```
<mat-tab-group>
  <mat-tab label="test">test</mat-tab>
</mat-tab-group>
<button mat-button>test</button>
```

The test uses `loader.getAllHarnesses` to get the button. But for some reason, the presence of `mat-tab-group` in the template prevents this from ever resolving. If you remove `mat-tab-group`, it resolves.

The same behavior happens with any component, not just buttons.

#### Expected Behavior

Test passes

#### Actual Behavior

Test fails with error:
```
Chrome 81.0.4044.138 (Mac OS 10.14.6) ErrorComponent should create FAILED
	Error: Timeout - Async function did not complete within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
	    at <Jasmine>
Chrome 81.0.4044.138 (Mac OS 10.14.6): Executed 1 of 4 (1 FAILED) (0 secs / 5.18 secs)
```

Remove `mat-tab-group` and it passes.

#### Environment

- Angular: 9.1.7
- CDK/Material: 9.2.3
- Browser(s): Chrome 81.0.4044.138
- Operating System (e.g. Windows, macOS, Ubuntu): Mac OS 10.14.6

**Comment by jacobweber** [comment] 2020-05-15 14:35
Even moving the tab group into a child component doesn't prevent this issue.

**Comment by crisbeto** [comment] 2020-05-15 15:08
It's probably hanging because something is throwing an error. I saw this error when I transferred it to our local testing setup:

```
 Error: Found the synthetic listener @translateTab.start. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
```

Can you try adding `BrowserAnimationsModule` or `NoopAnimationsModule` to the `imports` of your testing module?

**Comment by jacobweber** [comment] 2020-05-15 15:11
@crisbeto Hmm, the spec.ts file in that zip does import `NoopAnimationsModule`. Not sure why you're seeing that.

**Comment by crisbeto** [comment] 2020-05-15 15:13
I may have missed it when I was copying things over into our test runner.

**Comment by devversion** [comment] 2020-05-25 12:22
Hello! I tried reproducing this issue locally and on StackBlitz, but wasn't able to. I tried moving your reproduction into a StackBlitz: https://stackblitz.com/edit/repro-19368?file=app/app.component.spec.ts so that it can be tested more conveniently.

Can you please check if I missed anything here?

**Comment by jacobweber** [comment] 2020-05-25 16:18
Thanks for looking into this. I'm having some trouble figuring out how to run that example on my local machine, in the same way it runs on StackBlitz.

If I download the project from StackBlitz, upgrade all of the dependencies using [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) `ncu -u` (it fails otherwise), run `npm install`, and then run `ng test`, it passes.

But if I add a second component, identical to your app.component, and repeat that process, it fails as expected locally. It [doesn't fail on StackBlitz](https://stackblitz.com/edit/repro-19368-sbzaxs) though.

**Comment by devversion** [comment] 2020-06-03 10:04
@jacobweber Thanks for replying so quickly. I pulled the StackBlitz with the `error` component included, updated all dependencies and ran `yarn ng test` a couple of times. Re-run the tests from within the browser multiple times, but never saw the mentioned issue.

I'm afraid to say that I think we won't be able to spend a lot of time on it, given that it seems like this issue hasn't been surfaced in other reports. I can't think of a reason why the test would exceed, other than that the application's `NgZone` is not drained/stable for more than 5 seconds (which seems unlikely; unless there is something trigger CD accidentally repeatedly).

**Closed** 2020-06-03 10:04 UTC
Labels: P3, area: cdk/testing, needs clarification
