### ISSUE TITLE
bug(mat-form-field): mat-form-field appearance outline mat-label text is missing top portion

### ISSUE THREAD

**Issue by jmars2030** [angular/components#26449] opened 2023-01-18 04:57 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Environment:  Angular material 15 mac m1max macOS Ventura 13.1. Chrome version 109.0.5414.87 (Official Build) (arm64) and Safari Version 16.2 (18614.3.7.1.5) browsers experience the same issue. 

When you click on a form input field build with mat-from-field appearance "outline", the mat-label text misses the top portion of the text. 

Code Snippet: 
<div mat-dialog-content>
    <mat-form-field appearance="outline">
        <mat-label>Outline form field</mat-label>
        <input matInput placeholder="Placeholder">
        <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        <mat-hint>Hint</mat-hint>
      </mat-form-field>
</div>

https://user-images.githubusercontent.com/122946246/213086425-77d8931b-672c-4d7d-9350-3c6f7609dbde.mov

### Reproduction

Steps to reproduce:
1. Generate a dialog component and add a mat-form-field with appearance = "outline" as below: 
<div mat-dialog-content>
    <mat-form-field appearance="outline">
        <mat-label>Outline form field</mat-label>
        <input matInput placeholder="Placeholder">
        <mat-icon matSuffix>sentiment_very_satisfied</mat-icon>
        <mat-hint>Hint</mat-hint>
      </mat-form-field>
</div>
2. Open the form in browser and click on the input field and will notice the mat-label text missing the top portion as shown on this screenshot
<img width="752" alt="Screenshot 2023-01-17 at 11 51 56 PM" src="https://user-images.githubusercontent.com/122946246/213087276-e642bc61-d9e9-4abb-afcd-f4580496407b.png">

### Expected Behavior

I expect to see the label text not chopped off at the top.

### Actual Behavior

The mat-label text get chopped at the top.

<img width="752" alt="Screenshot 2023-01-17 at 11 51 56 PM" src="https://user-images.githubusercontent.com/122946246/213087360-a6145f22-c406-4f00-815d-94b74aeb5a18.png">

### Environment

- Angular:
Angular CLI: 15.0.5
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.1
@angular-devkit/build-angular   15.1.1
@angular-devkit/core            15.1.1
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
- CDK/Material:
- Browser(s): Chrome  and Safari
- Operating System (e.g. Windows, macOS, Ubuntu): masOS M1MAX Ventura 13.1

**Comment by iraviguggilam** [comment] 2023-01-23 15:06
![image](https://user-images.githubusercontent.com/118201312/214073670-eb3527e4-ab7f-458d-a81c-75d273419d04.png)
Getting like this without label.

**Comment by twobiers** [comment] 2023-02-15 16:17
> ![image](https://user-images.githubusercontent.com/118201312/214073670-eb3527e4-ab7f-458d-a81c-75d273419d04.png) Getting like this without label.

Had a similar issue and solved it using the following style:
```css
.mat-mdc-form-field .mdc-notched-outline__notch {
  border-right: 0px !important;
}
```

**Comment by AlexElin** [comment] 2023-02-18 10:15
Look like the duplicate of https://github.com/angular/components/issues/26352

**Comment by awdorrin** [comment] 2023-03-28 14:39
I worked around this with:
```
.mat-form-field-appearance-outline {
  padding-top: 6px;
}
```

**Comment by amysorto** [comment] 2023-05-26 20:26
Duplicate of #26352

**Closed by amysorto** 2023-05-26 20:26 UTC
Labels: needs triage
