### ISSUE TITLE
Slide toggle's button hover action doesn't change cursor to 'grab'

### ISSUE THREAD

**Issue by jindrichruzicka** [angular/components#18474] opened 2020-02-12 13:54 UTC
#### Reproduction

Steps to reproduce:
1. visit https://material.angular.io/components/slide-toggle/examples
2. hover over the slide toggle's button - observe the cursor didn't change to 'grab'
  
in version 8.2.3. it is working fine

#### Expected Behavior

Hovering over slide toggle's button should set cursor to 'grab'.

#### Actual Behavior

Hovering over slide toggle's button didn't change it to 'grab', instead it's 'pointer'.

#### Environment

- Angular: 9
- CDK/Material: 9
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by devversion** [comment] 2020-02-12 14:55
This is intentional because we removed the drag gesture from the slide-toggle. 

cc. @crisbeto for confirmation.

**Comment by crisbeto** [comment] 2020-02-12 14:57
Yes, that's expected since the toggle can't be dragged anymore.

**Comment by devversion** [comment] 2020-02-12 14:58
👍 Closing as this is the expected behavior as of version 9.

**Closed by devversion** 2020-02-12 14:58 UTC

**Comment by jindrichruzicka** [comment] 2020-02-12 15:46
I couldn't find this in a changelog.
