### ISSUE TITLE
feat(mat-tabs): mat-tabs active indicator does not follow M3 specs

### ISSUE THREAD

**Issue by shimonsalamon** [angular/components#29506] opened 2024-07-29 16:10 UTC
### Feature Description

The mat-tabs component should be updated to follow the Material 3 (M3) specifications. Specifically, the active indicator for primary tabs should match the design shown in the M3 guidelines. Currently, Angular Material only supports the secondary active indicator style.

https://m3.material.io/components/tabs/overview#34192702-8a18-4da7-b2cf-d1579632cb96

Reference:

See the attached image for the M3 specifications comparison.

<img width="1024" alt="unnamed" src="https://github.com/user-attachments/assets/43e465f3-8632-4a40-b2cc-6bf7f87dc95c">

**Comment by amysorto** [comment] 2024-07-29 16:25
Duplicate of #28261

**Closed by amysorto** 2024-07-29 16:25 UTC
Labels: feature, needs triage
