### ISSUE TITLE
bug(MatSlider): Can not be used as a progress bar after updating to Angular 10

### ISSUE THREAD

**Issue by bollerdominik** [angular/components#21041] opened 2020-11-13 15:22 UTC
#### Reproduction

See https://stackblitz.com/edit/components-issue-f9bocm

A MatSlider that updates every 100ms should allow adjustment of the current position. This used to work on Angular <= 9. Does not work any longer on Angular >= 10
 
 
#### Expected Behavior

What behavior were you expecting to see?

When moving the slider the current position should jump to the selected position

#### Actual Behavior

What behavior did you actually see?

When moving the slider the position does not change.

#### Environment

- Angular:
- CDK/Material: Does not work with 10 & 11. Works on 9
- Browser(s): Chrome, Firefox
- Operating System: Windows

**Comment by crisbeto** [comment] 2020-11-16 17:30
Duplicate of #19842.

**Closed by crisbeto** 2020-11-16 17:30 UTC
Labels: needs triage
