### ISSUE TITLE
The label on a mat form field with Outline with a prefix not aligning inside a dialog

### ISSUE THREAD

**Issue by abannsunny** [angular/components#15027] opened 2019-01-30 23:45 UTC
Bug:

Form-Field-Outline-Label-Gap does not reposition correctly when it is opened in a dialog and the Form-Field has a prefix.

This bug still exists in the latest version

there is an existing issue which is closed:
https://github.com/angular/material2/issues/13769

![image](https://user-images.githubusercontent.com/27024161/52020283-c17b9a00-24be-11e9-8a6b-a4ce3c4229be.png)

What is the expected behavior?
The Form-Field-Outline-Label-Gap should be positioned correctly with or without a prefix. Inside a dialog.

What is the current behavior?
The Form-Field-Outline-Label-Gap does not reposition itself away from the form field prefix like the label does when it is opened in a dialog.

What are the steps to reproduce?

I edited the stackblitz
https://stackblitz.com/edit/form-field-outline-label-gap-position-error-in-dialog

Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7.2.3
Angular Material 7.0.3
chrome: 71

**Comment by kklimczak** [comment] 2019-02-25 12:57
![Imgur](https://i.imgur.com/6PtV7Dp.png)

**Comment by kklimczak** [comment] 2019-02-25 13:01
I noticed the same problem:
![Imgur](https://i.imgur.com/6PtV7Dp.png)

The problem occurs when I refresh page.

only Windows 8.1 (on the same version of Chrome in Ubuntu 18.04 don't occurs)
Chrome 72.0.3626.119

**Comment by danbord** [comment] 2019-02-28 13:00
Same problem here

**Comment by lucasferreiralsf** [comment] 2019-03-15 12:39
Same problem: 

![image](https://user-images.githubusercontent.com/35882258/54431816-248b5e00-4706-11e9-99f0-64d78d0ef177.png)

**Comment by gazsiadam** [comment] 2019-04-01 13:19
I encountered the same issue. It can be reproduced with the Dialog example form the official Angular Material website.
Steps to reproduce
1. Make the add appearance="outline" to "the mat-form-field" element
2. Add <mat-icon matPrefix class="icon-prefix-padding">person</mat-icon> inside the "the mat-form-field" element

![image](https://user-images.githubusercontent.com/10939943/55330515-e5953080-5499-11e9-8292-68044fd7bf8e.png)

If lazy, use this [stackblitz](https://stackblitz.com/edit/angular-myphcj) :)

**Comment by jelbourn** [comment] 2019-05-12 03:20
@mmalerba is this addressed by one of the open form-field PRs?

**Comment by mmalerba** [comment] 2019-05-13 16:46
I don't think so, there's an open one for a similar issue with RTL (https://github.com/angular/components/pull/15415), but I don't think its related to this one

**Comment by ivibe** [comment] 2019-11-15 17:15
When using embedded view from a prepared TemplateRef, the same issue appears
```html
<ng-template #prefixRef>
  <button mat-icon-button *ngIf="switch">
    <mat-icon>check</mat-icon>
  </button>
  <mat-icon *ngIf="!switch">check</mat-icon>
</ng-template>

<p>
  <mat-form-field appearance="outline" floatLabel="always">
    <mat-label>Outline form field</mat-label>
    <ng-container matPrefix [ngTemplateOutlet]="prefixRef"></ng-container>
    <input matInput placeholder="Placeholder" />
    <mat-icon matSuffix>
      {{ switch ? 'sentiment_very_dissatisfied' : 'sentiment_satisfied' }}
    </mat-icon>
    <mat-hint>Weird behavior</mat-hint>
  </mat-form-field>
</p>
```
Example on [stackblitz.com](https://stackblitz.com/edit/angular-sgaizo?embed=1&file=src/app/form-field-appearance-example.html)

**Comment by donmccurdy** [comment] 2020-06-01 20:48
Seeing what I think may be the same issue here. The outline is initially correct, but when mobile device orientation is changed (e.g. landscape -> portrait), changing the width of the input, the outline will overlap the label text.

**Comment by raw3** [comment] 2020-06-08 13:53
Setting a fixed width globally on `.mat-form-field-prefix` is a temporary fix we are rolling with at the moment. The issue was visible when using a custom element with `matPrefix` even without a dialog in our case. Very situational, but figured I'd share.

**Comment by lsrsilva** [comment] 2020-10-08 17:52
Any update about this?

**Comment by shubhamseth29** [comment] 2020-11-23 07:40
Please provide a permanent fix for these, temporary fixes are not reliable !!

**Comment by shubhamseth29** [comment] 2020-11-23 08:04
Add #outlineFieldRef before in mat-form-field tag

In component file write
@ViewChild('outlineFieldRef')
 outlineFieldRef: MatFormField;

Then call this function based on your use case -> updateOutlineGap()
Example:
add focus in input field and call
(focus)="outlineFieldRef.updateOutlineGap()"

**Comment by farah111** [comment] 2020-12-07 16:30
any updates on this issue?

**Comment by gtranter** [comment] 2020-12-07 17:07
@farah111 @abannsunny you can work around the problem using the fix provided by @shubhamseth29 above. Add the following to the `DialogComponent` in the [stackblitz](https://stackblitz.com/edit/form-field-outline-label-gap-position-error-in-dialog-pd8j1j?file=src%2Fapp%2Fdialog%2Fdialog.component.ts):
```
  @ViewChildren(MatFormField) formFields: QueryList<MatFormField>;

  ngAfterViewInit(): void {
    setTimeout(() => this.formFields.forEach(ff => ff.updateOutlineGap()), 100);
  }
```

**Comment by marlinverhulst** [comment] 2021-02-23 11:51
We have seen the same issue, are there any updates on when it would be fixed ?

Angular version: 10.1.0
Angular Material: 10.2.7

**Comment by Jackques** [comment] 2021-02-23 11:52
@marlinverhulst facing the same issue here, and on the same versions.
Anyone knows if this will be fixed in a future update of Angular Material theme?

**Comment by psenechal** [comment] 2021-03-09 00:06
Same issue here using just a standard mat-input inside a mat-form-field...no prefix or suffix and the label aligns all the way to the left while the opening for it in the outline is near the center of the input. No styling applied at all...this is just out-of-the-box functionality. Definitely shouldn't have to rely on running something in a settimeout method to fix an issue. The material.angular.io website is displaying it correctly...not sure how they're doing that.

**Comment by joedoublev98** [comment] 2021-03-14 13:44
Same issue here,  just the default mat select. Please respond with a better solution than a timeout fix...

**Comment by johnohrenberger** [comment] 2021-04-24 22:12
Same issue here. Hoping it will be fixed soon.

**Comment by avinashkgit** [comment] 2021-05-21 02:02
Here is the screenshot on iphone safari browser. 
Its working fine on web safari and chrome.
<img width="337" alt="Screenshot 2021-05-21 at 10 01 09 AM" src="https://user-images.githubusercontent.com/22341729/119070942-78e3a400-ba1b-11eb-9f3a-9d930b08423e.png">

**Comment by lundmikkel** [comment] 2021-05-21 07:22
@avinashkgit That seems to a completely different issue, not related to this one.

**Comment by shadowzeng** [comment] 2021-06-22 02:27
I have met the same issue, solved by using `NoopAnimationsModule`.

**Comment by guchhaitprasun** [comment] 2021-07-07 06:22
![Screenshot 2021-07-07 113955](https://user-images.githubusercontent.com/34638276/124709378-08d0a500-df19-11eb-9707-2762d44eb52d.png)

Hi Team do we have any fix for this issue, Same issue persist with Angular Material 11.2.1. I tried `NoopAnimationModule` as suggested by [shadowzeng](https://github.com/angular/components/issues/15027#issuecomment-865472653) and I have also tried the solution provied by [shubhamseth29](https://github.com/angular/components/issues/15027#issuecomment-731996069) without any luck.

P.S. settimeout don't seens to be a valiid solution.

**Dependencies**
Angular v.11.2.1
Angular Material v11.2.1
Node v14.17.1
NPM v6.14.13

**Dev Env.**
Browser: Chrome v91.0.4472.124 
OS: Windoews 10 Pro v20H2

**Comment by BaptisteMPro** [comment] 2021-07-08 09:01
> `NoopAnimationsModule`

This solves my issue. Thank you.
If you don't want the placeholder/label animation and use outline rendering in your mat-form-field.

First, set floatLabel to always :

```typescript
{ provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: { floatLabel: 'always' } },
```

Then, import `NoopAnimationsModule` after `BrowserAnimationsModule` in your app module.

This label was misaligned and it's fix now

![image](https://user-images.githubusercontent.com/86654733/124894361-dc319180-dfdb-11eb-98e3-6669b0bc1111.png)

**Comment by BaptisteMPro** [comment] 2021-07-08 13:06
The problem with my "solution", is that `<mat-spinner>` does not work anymore, which sucks...

**Comment by astone2014** [comment] 2021-09-08 13:31
Confirmed simply importing `NoopAnimationsModule` fixes the issue. I didn't even change the `MAT_FORM_FIELD_DEFAULT_OPTIONS`.
https://github.com/angular/components/issues/15027#issuecomment-876264942

**Comment by krem06** [comment] 2022-02-24 16:59
Hi,

I added a small piece of css and it seems to do the trick:

`.mat-form-field-label {
	z-index: 1000;
	background-color: #ffffff;;
	width: auto !important;
	padding: 0 10px;
}`

**Comment by MikeJerred** [comment] 2022-03-06 17:01
> @farah111 @abannsunny you can work around the problem using the fix provided by @shubhamseth29 above. Add the following to the `DialogComponent` in the [stackblitz](https://stackblitz.com/edit/form-field-outline-label-gap-position-error-in-dialog-pd8j1j?file=src%2Fapp%2Fdialog%2Fdialog.component.ts):
> 
> ```
>   @ViewChildren(MatFormField) formFields: QueryList<MatFormField>;
> 
>   ngAfterViewInit(): void {
>     setTimeout(() => this.formFields.forEach(ff => ff.updateOutlineGap()), 100);
>   }
> ```

This is the workaround I am using, note if you don't have a dialog component (e.g. you are just using a template) you can also do:

```typescript
@ViewChildren(MatFormField) formFields: QueryList<MatFormField>;

const dialogRef = this.dialog.open(templateRef);
dialogRef.afterOpened().subscribe(() => {
  this.formFields.forEach(formField => {
    formField.updateOutlineGap();
  });
});
```

**Comment by poveu** [comment] 2022-12-02 12:10
Another workaround:
1. add `#inputField` to your `mat-form-field` element
2. add `(focus)="inputField.updateOutlineGap()"` to the input element

**Comment by meblum** [comment] 2022-12-29 18:30
Seems to be fixed in mdc

**Comment by mmalerba** [comment] 2023-01-10 19:37
Confirmed that this is fixed with the latest version: https://stackblitz.com/edit/angular-vsud9k

**Closed by mmalerba** 2023-01-10 19:37 UTC
Labels: P3, area: material/dialog, area: material/form-field
