### ISSUE TITLE
Scrolling by clicking mouse wheel doesn't scroll to the top of the list in Virtual scrolling

### ISSUE THREAD

**Issue by mishotek** [angular/components#13681] opened 2018-10-19 08:36 UTC
## Current behavior
When clicking a mouse wheel in the virtual scroll in [example](https://material.angular.io/cdk/scrolling/overview) and scrolling down with it, it scrolls to an end as it's supposed to, but when scrolling up it scrolls just by a chunk and then stops instead of rendering a new chunk of items.

## Expected behavior
Scrolling by clicking mouse wheel and dragging the cursor to the top should make list scroll to the top, even if more chunks have to be rendered.

## Minimal reproduction of the problem with instructions
Scroll down by rotating a mouse wheel, then inside of the virtual scroll component click a mouse wheel and drag it to the top to start scrolling in that direction. After scrolling some items, the scroll will stop event tho it hasn't reached the top of the list.

## What is the motivation / use case for changing the behavior?
The current behavior is unexpected. Especially when it is possible to scroll down by clicking a mouse wheel, but impossible to scroll down.

## Environment
I caught this bug in an official example on [Angular material website](https://material.angular.io/cdk/scrolling/overview)

Browser:
Chrome (desktop) Version 69.0.3497.100 (Official Build) (64-bit)

## Additional info
In the comment of the [same issue](https://github.com/angular/angular/issues/26571#issuecomment-431283100), I have opened in the Angular repo, it was mentioned that the same bug doesn't occur in the Firefox

**Comment by skreborn** [comment] 2018-10-19 08:37
This might be connected to the view recycling logic, because setting `templateCacheSize` to `0` produces the exact same results when scrolling downwards. The example is available on the official documentation under *View recycling*.

**Comment by skreborn** [comment] 2018-10-19 08:42
Okay, now I'm baffled. I can't reproduce the same behavior in [StackBlitz](https://stackblitz.com/edit/angular-k9yuem?file=material-module.ts). Perhaps it's an issue with how the documentation's scroll behavior is implemented?

**Comment by yusijs** [comment] 2018-11-23 13:30
Noticed a fun thing which seems related:
When templateCacheSize is set to 0, scrolling down works perfect and loads the items it should, while scrolling up breaks and doesn't load new items (rather, it just goes back down to show the same rows over).
When templateCacheSize is untouched, the behaviour above is reversed, and scrolling up works fine.

**Comment by maciejduda1** [comment] 2019-04-20 11:20
I just can add, that this behaviour is not happening in firefox or edge. I also wasn't able to reproduce this bug myself. It made me think that's because of some css maybe, but I didn't find anything that could mess around with the auto scroll (I was also trying to add/remove some css stuff in devtools). 

For me It looks like somehow the scroll reaches the "top" of the list before it acknowledges that new positions has been added. I'm sorry I cannot be much of a help here at my current skill level.

**Comment by crisbeto** [comment] 2020-07-26 09:13
Is this still a problem? I can't reproduce it on Chrome 84.

**Comment by wagnermaciel** [comment] 2020-08-13 22:52
Closing because no clarification was provided.

**Closed by wagnermaciel** 2020-08-13 22:52 UTC
Labels: area: cdk/scrolling, cannot reproduce, needs clarification
