### ISSUE TITLE
Valid year showing insted the year it was selected.

### ISSUE THREAD

**Issue by JaegerCaiser** [angular/components#11702] opened 2018-06-07 13:43 UTC
#### Bug, feature request, or proposal:
Building datepicker with max and min validates and with startView="multiyear", when the range dates valids is, for example, 2011-06-01 to 2011-09-30, selecting a year out of the range, for example year 2000, the months that appears is the valid year setted in the valids ranges.
![image](https://user-images.githubusercontent.com/29993026/41103233-0201c2a6-6a3f-11e8-94cd-265f1aafddc7.png)
![image](https://user-images.githubusercontent.com/29993026/41103334-4667d48a-6a3f-11e8-8339-e947794dcab8.png)

#### What is the expected behavior?
Show the that was selected in the view muitiyear

#### What is the current behavior?
Showing the year that not select previously

**Comment by himanshubansal1** [comment] 2018-06-22 12:09
I have the same issue. someone, please help me.

**Comment by molayodecker** [comment] 2019-03-12 16:29
Do you have a working example to show? On stackBlitz??? @himanshubansal1 @JaegerCaiser

**Comment by mmalerba** [comment] 2020-05-27 22:29
It's tough to tell without a reproduction link, but this _looks_ like a duplicate of https://github.com/angular/components/issues/11914 which I have confirmed has been fixed

**Closed by mmalerba** 2020-05-27 22:29 UTC
Labels: needs triage
