### ISSUE TITLE
Mat Flat Tree removing children nodes from DOM on collapse of parent node.

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/components#15436] opened 2019-03-11 06:03 UTC
#### What is the expected behavior?
Node should be present in DOM regardless of expand or collapse of parent node like mat-nested-tree-node.
#### What is the current behavior?
Mat Flat Tree removing children nodes on collapse of parent node.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>
https://stackblitz.com/angular/vnpmjrvjaky?file=app%2Ftree-flat-overview-example.css

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
7.3.1

#### Is there anything else we should know?
If this is the expected behaviour then what can i do so, it does not remove the children node on collapse

**Comment by josephperrott** [comment] 2019-06-04 17:53
Closing as this is the intended behavior to prevent the cost of keeping these many nodes in the DOM tree.

**Closed by josephperrott** 2019-06-04 17:53 UTC
