### ISSUE TITLE
bug(COMPONENT): Angular Material styles not loading consistently when production is optimized

### ISSUE THREAD

**Issue by davidtlee** [angular/components#25087] opened 2022-06-16 06:29 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

10

### Description

I'm not sure if I should be posting this issue in `angular/components` or `angular/angular-cli`, so I should mention that I posted it in angular-cli repo too as the issue seems to be somewhere at the intersection of the two: [optimization/minify in production makes Angular Material styles not load consistently](https://github.com/angular/angular-cli/issues/23384).

1. In Angular 13, when I click a dropdown for the Angular Material MatMenu, it will sometimes position the dropdown options underneath the bottom of the page. I can get it to do it reliably by clicking "Refresh" in my browser over and over (it happens roughly 50% of the time so I can usually get the behavior to come out with the 4th refresh or so).

2. When I inspect the css in DevTools, I see that `cdk-overlay-container` does not have the styles like `position: fixed;` that place it in the right location. In other words, the material styles do not seem to have loaded.

3. This bug does **not** occur in development, only when building (`ng build`) or serving in production (`ng serve --configuration production`). Moreover, if I set `optimization: false` within `angular.json` for `production`, the bug also disappears. This is why I am also suspecting it may relate to some part of the minification or optimization process.

4. In looking around, a lot of other people who have experienced the same Angular Material issue experience it when they do not load the prebuilt themes (e.g. https://github.com/angular/components/issues/1387), but I do have the prebuilt themes loaded correctly (which is why for me it works around 50% of the time, but doesn't work 50% of the time). I was able to find one other case in which others experienced "random" occurrences of missing styles like what I'm experiencing. In that issue (links below), it was found that "Chrome loads styles for Material later then application starts rendering in Angular". So my **guess** is that the bug I'm experiencing is also related to the timing of when styles are being loaded.

* https://supportcenter.devexpress.com/ticket/details/t915721/devextreme-material-theme-doesn-t-load-properly-in-production-build
* https://supportcenter.devexpress.com/ticket/details/t917577/devextreme-does-not-attach-additional-classes-to-dx-viewport-in-chrome-84-on-the-first

Any chance all of those clues mean something to someone?

### Reproduction

I haven't quite been able to create a simple reproduction in Stackblitz, but I got pretty close with this Stackblitz: https://stackblitz.com/edit/components-issue-afy6ka?file=src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.css,src%2Fstyles.scss,angular.json. When I first created that stackblitz and started working towards a reproduction, I recreated the problem by just removing the `aot: true` from `angular.json` and adding a simple example of a mat-menu within a page with `height: 100%;` for `html`, `body`, and all containers. However, once I used the "Share" link from the Stackblitz, the problem wasn't there anymore. I created a screen recording to show that I really did create the effect in this Stackblitz, but it somehow disappeared when I Shared it and also after I refreshing the browser

https://user-images.githubusercontent.com/863081/174004841-7edb886f-f8dc-4085-8bc5-3dea3fc883c2.mov

I'm hoping that the combination of all these clues will give someone an idea of what the issue is.

### Expected Behavior

The dropdown should be right underneath the button that I clicked

### Actual Behavior

The dropdown is at the very bottom of the page (because there are somehow no styles for `cdk-overlay-container` and probably other styles too).

### Environment

<pre><code>
Angular CLI: 13.2.5
Node: 16.10.0
Package Manager: npm 7.24.2
OS: darwin x64

Angular: 13.2.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/fire                   7.2.1
@schematics/angular             13.2.5
ng-packagr                      13.2.1
rxjs                            7.4.0
typescript                      4.5.5
webpack                         5.70.0
</code></pre>

**Comment by alan-agius4** [comment] 2022-06-16 06:59
Duplicate of https://github.com/angular/angular-cli/issues/23384. Let's keep tracking this in a single issue.

**Closed by alan-agius4** 2022-06-16 06:59 UTC
Labels: needs triage
