### ISSUE TITLE
Bug: cannot drop in connected cdkDropList inside element that has a ngIf

### ISSUE THREAD

**Issue by theo2354** [angular/components#15139] opened 2019-02-10 10:23 UTC
#### What is the expected behavior?

If a cdkDropList is inside an html element that has a ngIf, when the ngIf is at true state, you can drop elements inside the drop list if it is correctly connected to the origin list.

#### What is the current behavior?

You can't.

#### What are the steps to reproduce?

[Stackblitz](https://stackblitz.com/edit/angular-material-drag-and-drop-bug).

As you can see, there are event handlers in cdk-drag-drop-connected-sorting-example so that the second-component's drop list container is visible only when you are dragging an element.
If you drag an element from the first list, you can't drop it in the second one, but if you remove the ngIf in second-component, you will be able to. There is no wiring for drop events, however you can see if you can drop (or not) as the list splits (or not) to leave space for the new element.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

I am running Angular 7.2.2, CDK 7.3.0, TypeScript 3.2.4, I have reproduced the issue on Firefox 65 and Chrome 71 on Ubuntu 18.04.1.

#### Is there anything else we should know?

This issue seems related to #13998, as you can see, I was careful to use string ids like said.

**Comment by theo2354** [comment] 2019-02-22 09:04
Hello,
It would be awsome if I could have some news about this, this is a blocking bug for my product and if it won't be fixedand has no workaround I need to look for another solution now.
Thank you.

**Comment by volser** [comment] 2019-03-04 16:36
https://github.com/angular/material2/issues/15343

**Comment by theo2354** [comment] 2019-03-04 17:38
I understand my issue is a specific case of yours. Thank you a lot for linking it to me, thanks to your analysis of the problem I could find [a workaround](https://stackblitz.com/edit/angular-material-drag-and-drop-bug-fix) using mouse events.

**Comment by josephperrott** [comment] 2019-06-04 16:48
Closing as a duplicate of #15343 as #15343 encompasses this situation.

**Closed** 2019-06-04 17:22 UTC
