### ISSUE TITLE
Dispatching MouseEvents is broken after upgrade from version 13.1.2 to 13.1.3

### ISSUE THREAD

**Issue by HWouters** [angular/components#24577] opened 2022-03-11 14:14 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.1.2

### Description

After upgrading from 13.1.2 to 13.1.3 our drag and drop tests are failing. It looks like nothing is happening and the events are ignored.
We are using Cypress in similar approach to here: https://stackoverflow.com/questions/55361499/how-to-implement-drag-and-drop-in-cypress-test/55436989#55436989

### Reproduction

Steps to reproduce:
Upgrade from 13.1.2 to 13.1.3

### Expected Behavior

Able to test drag drop behavior by disptaching mouseevents

### Actual Behavior

Mouse events are ignored

### Environment

- Angular: 13
- Browser(s): chrome

**Comment by crisbeto** [comment] 2022-03-15 09:58
There haven't been any fundamental changes in `cdk/drag-drop` in a while and I don't see any at all between 13.1.2 and 13.1.3. Could it be something that has changed in your setup?

**Comment by HWouters** [comment] 2022-03-15 17:44
@crisbeto the problem is probably not in drag drop, but in handling mouseevents. I saw some changes related to that, but don't know if they are causing the issue.

**Comment by crisbeto** [comment] 2022-03-15 22:17
Handling of mouse events by which module?

**Comment by HWouters** [comment] 2022-03-16 13:58
I don't know the codebase and I might be completely wrong, but I was referring to #23493

**Comment by crisbeto** [comment] 2022-03-16 14:03
If #23493 broke anything, it would've only prevented focus indication from showing up on some components. It wouldn't affect any other event listeners.

**Comment by HWouters** [comment] 2022-03-16 15:11
Then it has to be something else, bumping the installed version from 13.1.2 to 13.1.3 (@angular/cdk & @angular/material) breaks our drag/drop tests. It looks like mouseevents are ingored, nothing moves anymore after the update.

**Comment by crisbeto** [comment] 2022-03-16 16:34
Is it possible that Cypress changed how they're dispatching events?

**Comment by HWouters** [comment] 2022-03-16 19:24
No, I narrowed it down to only this version update. If I install 13.1.2 it works, if I install 13.1.3 it doesn't.

**Comment by crisbeto** [comment] 2022-03-17 10:30
I'm looking through the changelog between 13.1.2 and 13.1.3, and I really don't see anything that could break event handling.

**Comment by HWouters** [comment] 2022-03-17 12:50
@crisbeto thank you for looking into this. I double checked it again, but it is really this version. I could narrow it even further to only @angular/cdk package. Here is a screenshot of my changes: only updating this single version breaks drag an drop testing.
![image](https://user-images.githubusercontent.com/1986905/158811920-c8291a0c-3ef4-4ee5-bde0-50bb890b2a6d.png)

**Comment by HWouters** [comment] 2022-03-17 13:36
@crisbeto I think the issue is related to #23493. If I add buttons: 1 to my mouse events it works.
`
          element.dispatchEvent(<any>new MouseEvent('mousedown', { **buttons: 1**, bubbles: true }));
          element.dispatchEvent(<any>new MouseEvent('mousemove', { **buttons: 1**, clientX: 10, clientY: 0 }));
          element.dispatchEvent(<any>new MouseEvent('mousemove', { **buttons: 1**, clientX: rect.x + 10, clientY: rect.y + 10 }));
          element.dispatchEvent(<any>new MouseEvent('mouseup', { **buttons: 1** }));
`

**Comment by crisbeto** [comment] 2022-03-17 13:38
Interesting, I wonder if your test depends upon the extra change detection that is triggered by focus monitor. If that's the case, you may end up broken again by #15077 which is close to being merged.

**Comment by miluoshi** [comment] 2022-04-04 17:54
I can confirm that it also broke our Cypress tests related to drag-n-drop after upgrading from 13.1.2 to 13.1.3 without any other changes.

**Comment by jobinsam** [comment] 2022-08-17 15:43
This upgrade broke our drag & drop tests too.

**Comment by miluoshi** [comment] 2023-11-23 11:19
I've just discovered, that from version [@angular/cdk@16.2.12](https://github.com/angular/components/releases/tag/16.2.12) you need to set both of those properties (`buttons` and `detail`) when creating `MouseEvent`:
```ts
MouseEvent(eventName, {
  bubbles: true,
  buttons: 1, // Primary button (https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons#value)
  cancelable: true,
  clientX: coords.x,
  clientY: coords.y,
  detail: 1, // This needs to be added since @angular/cdk@16.2.12
});
```

**Comment by crisbeto** [comment] 2023-12-12 12:28
Closing since there appears to be workaround.

**Closed by crisbeto** 2023-12-12 12:28 UTC
Labels: P3, needs: clarification, area: cdk/drag-drop
