### ISSUE TITLE
help(checkbox): why checkbox is not part of form-field

### ISSUE THREAD

**Issue by alexanderPastornicky** [angular/components#21863] opened 2021-02-10 09:29 UTC
#### What are you trying to do?

Implement checkbox

#### What troubleshooting steps have you tried?

I can't implement checkbox as part of form field (for consistency) 

#### Environment

- Angular: latest
- CDK/Material: latest
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by Totati** [comment] 2021-02-10 13:29
Duplicate of https://github.com/angular/components/issues/12072

**Comment by crisbeto** [comment] 2021-02-15 17:00
Closing as a duplicate of #7891.

**Closed by crisbeto** 2021-02-15 17:00 UTC
Labels: needs triage, troubleshooting
