### ISSUE TITLE
Datepicker: mat-datepicker-toggle messes up the input's styles in IE11

### ISSUE THREAD

**Issue by christianlundberg** [angular/components#15155] opened 2019-02-11 23:14 UTC
#### What is the expected behavior?
It should look the same on all major browsers

#### What is the current behavior?
The mat-datepicker-toggle component messes up the input's styles to the point where it looks like a textarea.

#### What are the steps to reproduce?
This is what it looks like using the mat-datepicker-toggle component on Chrome:
![image](https://user-images.githubusercontent.com/29963339/52600201-7ba8c500-2e20-11e9-847b-d6406391f782.png)

And here it is on IE11:
![image](https://user-images.githubusercontent.com/29963339/52600143-48663600-2e20-11e9-9f04-d0ef681f70bc.png)

**Comment by evanliomain** [comment] 2019-04-25 12:28
I reproduce the same bug.
Here a StackBlitz to reproduce : https://stackblitz.com/edit/angular-nkkkq2?file=app%2Fdatepicker-overview-example.html

**Comment by starquake** [comment] 2020-09-01 14:37
This seems to be a duplicate of #11650. There is a workaround that works for me.

**Comment by jelbourn** [comment] 2021-07-29 00:16
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.

**Closed by jelbourn** 2021-07-29 00:16 UTC
Labels: P3, area: material/datepicker, ie11
