### ISSUE TITLE
mat-menu doesn't try to return to its original height on window resize

### ISSUE THREAD

**Issue by meelkor** [angular/components#11682] opened 2018-06-05 18:43 UTC
#### Bug, feature request, or proposal:
bug

#### What is the expected behavior?

Menu shouldn't get unnecessarily shrinked after resizing window to height smaller than menu's content height and then back.

#### What is the current behavior?

Menu's size (height) remains limited by the former window size, even though the window's height is larger than menu's content again.

#### What are the steps to reproduce?
It can be easily reproduced on the official menu example from docs. https://stackblitz.com/angular/vrrbgbpjore

1. Open the menu in provided example
2. while menu is still open, resize browser's height so the menu's container needs to reduce its height
3. enlarge the browser window again
4. the keeps its reduced height

#### What is the use-case or motivation for changing an existing behavior?

Albeit it's kind of corner-case, it may get menu into unusable state and re-opening the menu doesn't solve the issue.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Tried chrome and firefox and both behaved the same way.

#### Is there anything else we should know?

For some reason it doesn't happen every time. Sometimes I can resize the window however I want and it still works fine, sometimes it shrinks and stays shrinks on every resize.

![image](https://user-images.githubusercontent.com/9664601/40995964-f0d48fca-6900-11e8-8b5a-01b3810a7524.png)
![image](https://user-images.githubusercontent.com/9664601/40995976-f699afbc-6900-11e8-930b-9d964e966d35.png)
![image](https://user-images.githubusercontent.com/9664601/40995982-fc8873ae-6900-11e8-9d8e-e9be9464a21a.png)

**Comment by julianobrasil** [comment] 2018-06-06 13:54
I've tried your stackblitz demo on Chrome **66.0.3359.181** and also **67.0.3396.62** (64 bits). I could not reproduce it. I'm using a Windows 10 machine. Any specificity?

**Comment by meelkor** [comment] 2018-06-06 14:14
I am on 66.0.3359.139 Arch Linux (64-bit), but my colleagues were able reproduce it on both Windows 10 and Mac OS machines as well. We just noticed it gets fixed when you resize the window so much that the menu disappears. Could you try to resize the window only so the scrollbar appears and resize the window back to the original size? Other than that we are doing the same thing as you in your screencap. We'll also provide screencap in a moment.

**Comment by julianobrasil** [comment] 2018-06-06 14:36
Ok, no matter what I do, I'm not able to reproduce it on Chrome on my machine. But I was able to easily reproduce it on Firefox (also, notice an awkward focus outline when the menu is opened):

![image](https://media.giphy.com/media/euMcD48Ea9zRRWV7Af/giphy.gif)

**Comment by contact2mayurkukadiya** [comment] 2019-04-15 11:06
I Have same issue. if any solution is exist then please help.

**Comment by mojesto** [comment] 2019-07-09 08:53
::ng-deep .cdk-overlay-connected-position-bounding-box {
  min-height: 300px; // or whatever min height you need
}

**Comment by crisbeto** [comment] 2020-05-27 16:42
This was fixed in master a while ago. Closing.

**Closed by crisbeto** 2020-05-27 16:42 UTC
Labels: area: material/menu
