### ISSUE TITLE
feat(date-picker): add time selection in date-picker component

### ISSUE THREAD

**Issue by nicolasguilhem** [angular/components#26064] opened 2022-11-23 10:34 UTC
### Feature Description

Add feature to permit selection of hours and minutes in the date picker component (and in date-range-picker too).

### Use Case

Sometimes, users need to select in a form a date and a time associated to this date.

For example a start and end moment for an event.
Event period : from 10/10/2022 at 09:30 AM to 10/12/2022 at 06:00 PM

**Comment by crisbeto** [comment] 2022-11-23 12:25
Duplicate of https://github.com/angular/components/issues/5648.

**Closed by crisbeto** 2022-11-23 12:25 UTC
Labels: feature, needs triage
