### ISSUE TITLE
bug(mat chips): mat-chips with mat-autocomplete and input combined, adds an extra chip when selecting from list

### ISSUE THREAD

**Issue by elazarza** [angular/components#19805] opened 2020-06-30 09:18 UTC
#### Reproduction

stackblitz demo:
https://components-issue-eyb6jo.stackblitz.io

Steps to reproduce:
1. create mat chips as shown in the example section in the docs
2.  use the autocomplete example
3. add the Input example neccessary parts - [matChipInputAddOnBlur]="addOnBlur" in template and addBlur= true in TS
4. start typing one of the items in the autocomplete, i.e: Apple - start typing Ap, then click Apple
 
 
#### Expected Behavior

What behavior were you expecting to see?

only the item Apple is added to the chips list and the input is cleared

#### Actual Behavior

What behavior did you actually see?

both "Ap" that is the input value at the moment and "Apple" that is the clicked item are added to the chips list

#### Environment

- Angular: 8.2.3
- CDK/Material: cdk - 7.3.7 material - 7.0.1
- Browser(s): tested on Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by mariojsnunes** [comment] 2020-07-01 17:49
Same issue here, I'm on
Material/CDK: 9.2.0
Angular 9.1.0

**Comment by mariojsnunes** [comment] 2020-07-02 17:59
I upgraded to @angular/material 10.0.1 and I still have the the same issue.
Also happening with matChipInputAddOnBlur set to false.
Happens if click or if you press enter with the option selected.

**Comment by mariojsnunes** [comment] 2020-07-03 11:09
Found a workaround that involves storing the autocomplete active option state.

`(optionActivated)="activated($event)"`

`activated(event: MatAutocompleteActivatedEvent) {
    this.active = event.option?.value;
  }`

Then validate if there is an active option before adding the chip.

**Comment by elazarza** [comment] 2020-07-03 13:30
@mariojsnunes thanks man i'll check it out adn see if it works for me, do you check for an active blur event option or click event option?

**Comment by mariojsnunes** [comment] 2020-07-03 14:18
@elazarza I didn't need any blur event logic.
The (optionActivated) event also triggers when it is deselected (option is null)

**Comment by aeslinger0** [comment] 2020-07-15 11:40
Duplicate of https://github.com/angular/components/issues/13574

**Comment by elazarza** [comment] 2020-07-15 13:33
> Duplicate of #13574

seems to be it.
working solution from there by "zzzaaa":

https://github.com/angular/components/issues/19279#issuecomment-627263513

**Comment by crisbeto** [comment] 2020-07-19 08:45
Closing as a duplicate of https://github.com/angular/components/issues/13574.

**Closed by crisbeto** 2020-07-19 08:45 UTC
Labels: area: material/chips
