### ISSUE TITLE
bug(mat-autocomplete): Ensures ARIA input field has an accessible name (#mat-autocomplete).

### ISSUE THREAD

**Issue by mahesh-shinde-13** [angular/components#20999] opened 2020-11-10 05:17 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior

ARIA input field should be present.

#### Actual Behavior

![image](https://user-images.githubusercontent.com/74227921/98630772-e2367c00-2341-11eb-8ddf-cac4f329adb3.png)

#### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2020-11-10 15:43
Duplicate of https://github.com/angular/components/issues/20888.

**Closed by crisbeto** 2020-11-10 15:43 UTC
Labels: needs triage
