### ISSUE TITLE
[Sort] Programatically setting active/direction does not update UI

### ISSUE THREAD

**Issue by shahmirn** [angular/components#10242] opened 2018-03-02 17:41 UTC
#### Bug, feature request, or proposal:
I'm programmatically setting the active and direction on matSort, but it's not updating the UI

#### What is the expected behavior?
programmatically setting the active and direction on matSort updates the UI

#### What is the current behavior?
programmatically setting the active and direction on matSort, but it's not updating the UI

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-material2-issue-mc4cve?file=app/app.component.ts

#### What is the use-case or motivation for changing an existing behavior?
I believe this is a regression. This was working in 5.1.0

**Comment by Hotell** [comment] 2018-05-29 08:27
Same issue here, it's kinda deal breaker, as you cannot set values dynamically or imperatively. I'm currently implementing a data table which reflects state to URL via query params, everything works ( even pagination set dynamically, cannot say the same for sort )

doesn't work with 5.2.5 nor 6.x

demo:
https://stackblitz.com/edit/github-issue-ng-material-sorting-10242

**Comment by Ian5015** [comment] 2018-05-31 16:55
Encountering this as well in 6.0.0.

**Comment by ericbae** [comment] 2018-06-25 11:08
Has there been any update to this?

**Comment by sergidt** [comment] 2018-06-28 14:13
same here!!

Is a very important feature and is not working. 
I attach and example where I change the sort field dynamically after two seconds and yo can see what undesired behavior is shown

**Comment by jansivans** [comment] 2018-07-11 07:52
6.3.3 - bug still here: https://stackblitz.com/edit/angular-a4yakd

**Comment by ThierryLehoux** [comment] 2018-08-06 10:12
Could be usefull when reflect state to URL via query params.

**Comment by sherkhanz** [comment] 2018-08-10 15:54
Any update on this?

**Comment by adgoncal** [comment] 2018-09-14 21:37
I spent some time debugging this. Here are my observations:

When you click on a `mat-sort-header` that is not currently active, eventually it will call `_setAnimationTransitionState({fromState: '<direction>', toState: 'active'})` on the clicked `mat-sort-header`.

However, when you programmatically call `matSort.sort({...})`, the `mat-sort-header` that should become active never calls `_setAnimationTransitionState()`.

I believe this is an issue on `_rerenderSubscription()`.

https://github.com/angular/material2/blob/9ab2c905e2e81999347742f880bfd851f9e32022/src/lib/sort/sort-header.ts#L230

https://github.com/angular/material2/blob/9ab2c905e2e81999347742f880bfd851f9e32022/src/lib/sort/sort-header.ts#L145-L159

https://github.com/angular/material2/blob/9ab2c905e2e81999347742f880bfd851f9e32022/src/lib/sort/sort-header.ts#L204-L212

**Comment by adgoncal** [comment] 2018-09-14 23:48
I think something like this would solve the issue, but not sure if there are any side-effects. I tried it locally and 3 unit tests failed, including the one I added. I am not sure why they are failing.

```diff
diff --git a/src/lib/sort/sort-header.ts b/src/lib/sort/sort-header.ts
index a6d93b02..82d5aa9c 100644
--- a/src/lib/sort/sort-header.ts
+++ b/src/lib/sort/sort-header.ts
@@ -146,6 +146,13 @@ export class MatSortHeader extends _MatSortHeaderMixinBase
         .subscribe(() => {
           if (this._isSorted()) {
             this._updateArrowDirection();
+
+            if (this._viewState && this._viewState.toState === this._arrowDirection) {
+              this._setAnimationTransitionState({
+                fromState: this._arrowDirection,
+                toState: 'active',
+              });
+            }
           }
 
           // If this header was recently active and now no longer sorted, animate away the arrow.
diff --git a/src/lib/sort/sort.spec.ts b/src/lib/sort/sort.spec.ts
index ffe8e34e..e43b5819 100644
--- a/src/lib/sort/sort.spec.ts
+++ b/src/lib/sort/sort.spec.ts
@@ -189,6 +189,19 @@ describe('MatSort', () => {
       component.expectViewAndDirectionStates(expectedStates);
     });
 
+    it('should be correct when sort has changed programmatically while a header is active', () => {
+      // Sort the first header to set up
+      component.sort('defaultA');
+      expectedStates.set('defaultA', {viewState: 'asc-to-active', arrowDirection: 'active-asc'});
+      component.expectViewAndDirectionStates(expectedStates);
+
+      // Sort the second header and verify that the first header animated away
+      component.sort('defaultB');
+      expectedStates.set('defaultA', {viewState: 'active-to-asc', arrowDirection: 'asc'});
+      expectedStates.set('defaultB', {viewState: 'asc-to-active', arrowDirection: 'active-asc'});
+      component.expectViewAndDirectionStates(expectedStates);
+    });
+
     it('should be correct when sort has been disabled', () => {
       // Mousing over the first sort should set the view state to hint
       component.disabledColumnSort = true;
```

```
MatSort checking correct arrow direction and view state for its various 
states should be correct when cycling through a default sort header FAILED
	Expected 'active' to equal 'asc-to-active'.

MatSort checking correct arrow direction and view state for its various 
states should be correct when sort has changed while a header is active FAILED
	Expected 'active' to equal 'asc-to-active'.

MatSort checking correct arrow direction and view state for its various 
states should be correct when sort has changed programmatically while 
a header is active FAILED
	Expected 'active' to equal 'asc-to-active'.
```

**Comment by ms-dosx86** [comment] 2018-10-27 04:00
Does not work with v7.0.0

**Comment by ms-dosx86** [comment] 2018-11-07 05:29
v7.0.3 works perfectly

**Comment by franklopez** [comment] 2018-11-14 16:00
Angular V.6.1.9, Material: 6.4.7
In my case it always show the ^ arrow regardless of the direction and when hoover the arrow goes off.

**Comment by literalpie** [comment] 2018-11-27 15:58
I believe the original intent of this issue was that mat-sort does not respond to programatic changes in _active and direction_. The discussion on this issue seems to be assuming that the sorting is done by calling the `sort` function, not changing the two attributes.

[stackblitz](https://stackblitz.com/edit/mat-sort-code-update-reproduction) that shows the issue I am talking about

has this issue been fully changed to just be about the header not updating? If so, I will create a new issue for updating sort via `active` and `direction`

**Comment by marcusadrian** [comment] 2018-12-26 16:37
Still not working in version 7.1.0, arrows doesn't update showing the wrong sort column.
Strangely disappears on wrong column when hovering over without appearing on right column.

**Comment by rzubrycki** [comment] 2019-01-08 19:35
Hi guys, any update on this one?

**Comment by austin5456** [comment] 2019-01-12 21:06
The work around I'm currently using is forcing it to check the state change and that calls the animation if it's different than the initial.
```
    this.sort._stateChanges.next();
```

**Comment by soldierdi** [comment] 2019-01-12 21:52
Hello everyone,

does anyone know how the input properties "matSortActive" and "matSortDirection" for the matSort directive work. When I set them the respective sort arrow is not updated. It would be nice to update the sort arrows with the help of observables using these two input properties.

**Comment by DmitryEfimenko** [comment] 2019-02-07 08:51
v7.1.1 - still not working.

**Comment by LautaroLorenz** [comment] 2019-02-07 19:34
not working y.y

**Comment by Nikkio** [comment] 2019-02-09 06:23
```
this.sort.active = ''; this.sort.direction = 'asc' as SortDirection;
this.sort.sortChange.emit();
```
this resets matSort UI without triggering server requests.

**Comment by Anderman** [comment] 2019-03-07 22:38
The ArrowIcon is set in the clickhandler of matSortHeader. Is sees only two ugly hacks.
add a stylesheet entry
```
::ng-deep .mat-sort-header-sorted .mat-sort-header-arrow {
     opacity: 1 !important;
}

```
or call
`this.matSortHeader._setAnimationTransitionState({ toState: 'active' });`

You can use something like this.
```
@ViewChild(MatSort) public matSort: MatSort;
@ViewChild(MatSortHeader) public matSortHeader: MatSortHeader;

```
and
```
      this.matSort.start = null;
      this.matSort.active = null;
      this.matSort._stateChanges.next();
      this.matSortHeader._setAnimationTransitionState({ toState: 'asc' });
```

or
```
      this.matSort.start = 'asc';
      this.matSort.active = 'productCode';
      this.matSort._stateChanges.next();
      this.matSortHeader._setAnimationTransitionState({ toState: 'active' });
```

**Comment by adgoncal** [comment] 2019-03-08 14:37
@Anderman that is very similar to what I have been using for a few months:

```typescript
import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { Sort, MatSort, MatSortHeader } from '@angular/material';

import { Subject, Observable, of } from 'rxjs';
import {
  catchError,
  distinctUntilChanged,
  map,
  takeUntil,
  withLatestFrom,
} from 'rxjs/operators';

@Component({
  // ...
})
export class MyComponent implements AfterViewInit, OnDestroy {
  @ViewChild(MatSort) matSort: MatSort;

  private destroyed$ = new Subject<void>();

  private sort$: Observable<Sort>;

  ngAfterViewInit() {
    // HACK: fix sort header arrow after programmatically changing sort order
    // https://github.com/angular/material2/issues/10242
    // TODO: Remove this hack when the bug is fixed on @angular/material
    this.matSort._stateChanges
      .pipe(
        withLatestFrom(this.sort$),
        map(([_, sort]) => sort),
        takeUntil(this.destroyed$),
        catchError(error => {
          return of(error);
        })
      )
      .subscribe((sort: Sort) => {
        const sortables = this.matSort.sortables;
        const activeSortHeader = <MatSortHeader>(
          sortables.get(sort.active)
        );

        activeSortHeader._setAnimationTransitionState({
          fromState: activeSortHeader._arrowDirection,
          toState: 'active',
        });
      });
  }

  ngOnDestroy() {
    this.destroyed$.next();
    this.destroyed$.complete();
  }
}
```

**Comment by Anderman** [comment] 2019-03-08 14:58
@adgoncal  In some messages the problem seems to be solved or suggests other solutions that do not work. I spent to much time on this problem by trying some of those solutions. At least it was not clear for me how to make a workarond.

**Comment by iamFujiYama** [comment] 2019-04-01 09:15
Hi all,  sorry for my poor English skill ,
but I wanted to sharing my solution.

 I also encountered  this bug and tried use  _setAnimationTransitionState Func,
But I found the UI transition is not smooth, ( U need mouse focus then the arrow will change ...)

and then , I tried use _handleClick() function
( it seems can trigger click target column's click event )

so , i provider another dirty hack :
The point is set "_opposite direction_" which you want the arrow be
```
           this.sort.active = <i>TARGET_HEADER_NAME</i>
           // I want set the arrow as 'asc', so  set the direction 'desc' once, 
           // then call _handleClick to trigger click event
           this.sort.direction  = 'desc' as SortDirection
           const _SortHeader =  this.sort.sortables.get('<i>TARGET_HEADER_NAME</i>') as MatSortHeader
           _SortHeader._handleClick()
         
```

If your sort using server , need add a flag to control server communication
like this : 

```
// _doNotRequestToServer is the flag 

 this.sort.sortChange.subscribe(
        () => {
          return doSort([ {
            [this.sort.active]: this.sort.direction
          } ], this._doNotRequestToServer);
        }
    );
```

I wish maybe it can help u :)

**Comment by keatkeat87** [comment] 2019-06-11 11:10
any update on this issue ? 
8.0 problem same...

**Comment by KK220794** [comment] 2019-09-19 06:17
using 8.1.1 still getting the same issue

**Comment by sharan-zweck** [comment] 2019-09-26 11:18
> The ArrowIcon is set in the clickhandler of matSortHeader. Is see only two ugly hacks.
> add a stylesheet entry
> 
> ```
> ::ng-deep .mat-sort-header-sorted .mat-sort-header-arrow {
>      opacity: 1 !important;
> }
> ```
> 
> or call
> `this.matSortHeader._setAnimationTransitionState({ toState: 'active' });`
> 
> You can use something like this.
> 
> ```
> @ViewChild(MatSort) public matSort: MatSort;
> ```
> 
> and
> 
> ```js
>    public setSort(id: string, start?: 'asc' | 'desc') {
>     start = start || 'asc';
>     const matSort = this.dataSource.sort;
>     const toState = 'active';
>     const disableClear = false;
>     
>     //reset state so that start is the first sort direction that you will see
>     matSort.sort({ id: null, start, disableClear });
>     matSort.sort({ id, start, disableClear });
> 
>     //ugly hack
>     (matSort.sortables.get(id) as MatSortHeader)._setAnimationTransitionState({ toState });
>   }
> ```

This is the best workaround for the timebeing

**Comment by JayAhn2** [comment] 2019-11-25 13:56
We can simply do this just reassign this.dataSource.sort with this.matSort as below.

```
  orderData(id: string, start?: 'asc' | 'desc') {
    const matSort = this.dataSource.sort;
    const toState = 'active';
    const disableClear = false;

    matSort.sort({ id: null, start, disableClear });
    matSort.sort({ id, start, disableClear });

    this.dataSource.sort = this.matSort;
  }
```

**Comment by trubit** [comment] 2020-02-18 22:03
Hi Andrew @andrewseguin :)
Can we prioritize this issue a little more? According to reactions, this is most wanted FIX for `Sort` component (https://github.com/angular/components/issues?utf8=%E2%9C%93&q=project%3Aangular%2Fcomponents%2F18+is%3Aopen+sort%3Areactions-%2B1-desc+)

API reveals `sort` method, which works fine, the only thing missing is call for updating animation state - so actual arrow is hidden after sorting programaticaly.

In SortHeaderComponent, there are two places, where UI is updated.
1. click handler https://github.com/angular/components/blob/198911f5c0dd198f42ee0476a3291ec9858a0660/src/material/sort/sort-header.ts#L243
2. sort change subscription - which is called also from click handler (1.) https://github.com/angular/components/blob/198911f5c0dd198f42ee0476a3291ec9858a0660/src/material/sort/sort-header.ts#L162

To fix this, we just need to move most of the click handler logic to subscription logic, as it is also called, becase click handler calls that `sort` method.
This way everything is handled in subscription and click handler only calls `sort` method.

So we can move this logic from click handler:
```typescript
   // Do not show the animation if the header was already shown in the right position.
    if (this._viewState.toState === 'hint' || this._viewState.toState === 'active') {
      this._disableViewStateAnimation = true;
    }

    // If the arrow is now sorted, animate the arrow into place. Otherwise, animate it away into
    // the direction it is facing.
    const viewState: ArrowViewStateTransition = this._isSorted() ?
        {fromState: this._arrowDirection, toState: 'active'} :
        {fromState: 'active', toState: this._arrowDirection};
    this._setAnimationTransitionState(viewState);
```

To subscription handler after these lines
```typescript
   if (this._isSorted()) {
        this._updateArrowDirection();
   }
```
and run it only when condition `this._sort.active == this.id` is met.

There propably needs to be one more condition or something. but the main idea is that this is actually really easy fix for the most wanted issue of Sort component.

Thanks for considering this and thanks for your hard work at Angular team, this product is amazing! :)

**Comment by joshcomley** [comment] 2020-04-28 11:56
This problem still persists. Pinging to get it attention.

**Comment by WhiteStarLine** [comment] 2020-05-30 13:28
Just spent 2 days trying to get a server-side change to update the UI.  It only worked if the user clicked on a sort arrow.  JayAhn2's code describes the problem as I see it and provides a workaround that worked immediately.  Hope this gets addressed at some stage.  Cheers.

**Comment by lukekroon** [comment] 2020-06-03 11:22
`<table matSort (matSortChange)="sortData($event)" [matSortActive]="sortActive" [matSortDirection]="sortDirection" matSortDisableClear>`

Setting the variables sortActive and sortDirection in the component does the job for me. It updates the arrow as well.

https://github.com/angular/components/issues/7838#issuecomment-380380985

v9.1+

**Comment by shahmirn** [comment] 2020-06-03 15:35
@lukekroon It doesn't work in the same scenario as the original bug, which is code in the callback of .subscribe()

https://stackblitz.com/edit/angular-material2-issue-qjaqm4?file=app%2Fapp.component.ts

**Comment by NanduSurendranNair** [comment] 2020-07-08 07:27
I have tried with the below snippet and it is working as expected. Once the state of the material table is set, then executing it made the UI to update the sort arrow.

Using angular material version 7.3.7
Here id refers to the current active sort column name.

`(matSort.sortables.get(id) as MatSortHeader)._updateArrowDirection();`

**Comment by binson1989** [comment] 2020-08-07 07:51
Still facing this issue with angular v10.0.3.

 @andrewseguin  any update on a possible fix?

**Comment by ccamba** [comment] 2020-09-01 13:09
@Nikkio in my case only with using this.sort.sortChange.emit(); works. Thanks

**Comment by codemile** [comment] 2020-10-10 14:35
Hi everyone,

I've found probably the easiest workaround for this issue. The only side effect is that it requires the table to be redrawn when sort changes, but it's extremely simple to implement and works in most cases.

```
<table *ngFor="let hack of [sort]"
            mat-table
            matSort
            [matSortActive]="sort.active"
            (matSortChange)="setSort($event)"
            [matSortDirection]="sort.direction">
```

When ever you change the `sort: Sort` property on the component in an immutable way, then it will trigger the `<table>` to be recreated and the `matSort` component renders the active sort header correctly, because it does render it correctly the first time.

I find this solution is better future proofed, because when they later fix this issue, then you can just remove the `*ngFor` and it should continue to work without the performance lag.

I tried many of the above hacks, but suffered from many other side effects in my source code from trying to handle both external and internal sort change events. The above hack solves those issues, because `(matSortChange)` does not emit a value for the first time the table is rendered. So it only fires when the user clicks on a header, and doesn't suffer from feedback loops some of the higher solutions introduced in my source code.

**Comment by telb99** [comment] 2020-12-29 22:20
Still an issue in 10.2.4
Wasted several hours before finding this issue...

**Comment by Melmoth-the-Wanderer** [comment] 2021-02-20 12:54
Can someone confirm this works in v11?

**Comment by rudzikdawid** [comment] 2021-03-19 11:47
angular 11.2.6
material 11.2.5 

works better but still there is a little problem with refresh ui after model `matSortActive`, `matSortDirection` change:  
https://stackblitz.com/edit/angular-i8z8ny

there is a button `reset filter` below the table, this button triggers method `onResetFilter` from parent controller.  
```
onResetFilter() {
  this.matSortActive = "name";
  this.matSortDirection = "asc";
}
```
calling this method sometimes triggers ui changes, sometimes not.

**Comment by stnor** [comment] 2021-10-06 08:41
This solved it for me:
````
        const sortHeader: MatSortHeader = this.sort.sortables.get(this.sort.active) as MatSortHeader;
        sortHeader._setAnimationTransitionState({fromState: sortHeader._arrowDirection, toState: 'active'});
        this.dataSource.sort.sortChange.emit(sort);
````

**Comment by enekonieto** [comment] 2022-02-10 15:09
Still an issue in 13.1.3

**Comment by erksmaas** [comment] 2022-04-15 00:58
Would be great if this could be fixed

**Comment by PhilippMeissner** [comment] 2022-04-15 11:58
Hold your horses, it's only been 4 years.

**Comment by BruneXX** [comment] 2022-06-24 20:15
Wow, this is still an issue.. :´(

**Comment by technbuzz** [comment] 2022-06-28 14:00
I have a table with sorting, filtering, tabs, pagination with server where it is run by URL being source of truth. Everything works but this bug is ruining all it's potential. I wonder what's stopping its implementation.

**Comment by chacabuk** [comment] 2022-11-01 16:29
setTimeout(() => { this.dataSource.sort = this.sort; }, 100);

**Comment by PhilippMeissner** [comment] 2022-11-02 07:08
> 

If you really want to rely on `setTimeout` you may as well set the delay to `0`. The callback will still be put in the appropriate queue and called, but without the assumingly unneeded delay.

**Comment by hunterlan** [comment] 2022-12-16 17:37
Guys, any plans for this bug? 👀

**Comment by daviekr** [comment] 2022-12-28 15:19
bump

**Comment by mgremm** [comment] 2024-02-26 03:56
Upgrading from Angular 7 to 15 broke my mat-table's programmatically determined sort. I tried many things, but in the end I fixed my programmatically generated sort by changing 

```
 @ViewChild(MatSort)
 matSort: MatSort = new MatSort;
```

to

`@ViewChild(MatSort, { static: true }) matSort: MatSort; `

No `this.sort.sortChange.emit(sort);` needed.

**Comment by ludobegins** [comment] 2024-11-05 20:50
when you scroll through a 6-year old bug imagining it would be solved by now but you slowly get closer and closer to the current date and realize it's not 😂 (and then realize the issue is still open)

**Closed** 2024-11-27 11:45 UTC
Labels: P3, area: material/sort

**Comment by sup3rcow** [comment] 2024-12-15 10:55
> I had a repaint issue. This solved it for me:
> 
> ```
> const sortHeader: MatSortHeader = this.sort.sortables.get(this.sort.active) as MatSortHeader;
> sortHeader._setAnimationTransitionState({fromState: sortHeader._arrowDirection, toState: 'active'});
> this.sort.sortChange.emit(sort);
> ```

material 2 v19.0.3, this solution doesn't work anymore.
Is it fixed by material team?

**Comment by crisbeto** [comment] 2024-12-15 11:04
The _setAnimationTransitionState part shouldn't be necessary anymore.
