### ISSUE TITLE
Angular material formfield label bug with density -2 or -3 (and appearance="fill")

### ISSUE THREAD

**Issue by StephanHoo** [angular/components#28435] opened 2024-01-17 16:05 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When changing the density to -2 or -3 with appearance="fill" results in labels not showing in mat-form-field

![image](https://github.com/angular/components/assets/156934166/0ade6a25-7976-4346-a817-b4aa41cdfe70)

![image](https://github.com/angular/components/assets/156934166/5772f4de-4cfd-4310-bff4-b3d3c318b62c)

### Reproduction

StackBlitz link: https://stackblitz.com/edit/tptcsx?file=src%2Ftheme.scss
Steps to reproduce:
1. Go to theme.scss and add density: -1 --> labels are showing
2. Go to theme.scss and add density: -2 --> labels are **not** showing
3. Go to theme.scss and add density: -3 --> labels are **not** showing
4. Go to theme.scss and add density: -2 with _mat-form-field appearance="outline"_ added in select-overview-example.html --> labels are showing
5. Go to theme.scss and add density: -3 with _mat-form-field appearance="outline"_ added in select-overview-example.html --> labels are showing

### Expected Behavior

Labels showing with appearance="fill" with density to -2 or -3

### Actual Behavior

Labels are not showing with appearance="fill" with density to -2 or -3

### Environment

- Angular: 17.0.5
- CDK/Material: 17.0.5
- Browser(s): Chrome (119.0.6045.200)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by json-derulo** [comment] 2024-01-17 20:08
Looks like a duplicate of #26579

**Closed** 2024-01-18 03:54 UTC
Labels: needs triage

**Comment by StephanHoo** [comment] 2024-01-18 03:56
Closed because of duplication #26579
