### ISSUE TITLE
Mat-Form-Field not rendering properly

### ISSUE THREAD

**Issue by Utsav-Sharma33** [angular/components#22563] opened 2021-04-25 19:09 UTC
![Screenshot (1)](https://user-images.githubusercontent.com/32520700/115921603-5781ad80-a499-11eb-87ea-981ddc5c769c.png)
![Screenshot (2)](https://user-images.githubusercontent.com/32520700/115921609-59e40780-a499-11eb-844e-d644c7d76509.png)

![Screenshot (3)](https://user-images.githubusercontent.com/32520700/115922142-248be980-a49a-11eb-8d5f-74a60dda7a83.png)

**### Github repository url : Utsav-Sharma33/material**

I added a mat-form-field tag in my component but it is not rendering correctly. When not focussed, float-label is not showing. But on selection of matInput input tag , float label is showing. I am attaching screenshots.
`
const mat_modules = [
  MatFormFieldModule, MatInputModule, MatIconModule
]

const components = [
  FormFieldComponent,
]

@NgModule({
  declarations: [
    ...components
  ],
  imports: [
    CommonModule,
    ...mat_modules
  ],
  exports: [
    ...components
  ]
})
export class ComponentsModule { }
`

**Comment by annieyw** [comment] 2021-04-26 21:42
Closing as duplicate of https://github.com/angular/components/issues/22554

**Closed by annieyw** 2021-04-26 21:42 UTC
Labels: needs triage
