### ISSUE TITLE
open dialog button get cdk-fokus class after closing the dialog.

### ISSUE THREAD

**Issue by yantrab** [angular/components#17031] opened 2019-09-10 11:29 UTC
[this ](https://stackblitz.com/angular/odalkvrpxod?file=app%2Fdialog-overview-example.ts)is the official example of dialog.

open dialog and close it by  clicking somewhere  give to open dialog button focus style.

**Comment by Totati** [comment] 2019-09-11 09:06
It's by design. you can turn of this befaviour by setting `restoreFocus: false` when opening the dialog. Here's the documentation: https://material.angular.io/components/dialog/api#MatDialogConfig, you can default this to false with setting the [MAT_DIALOG_DEFAULT_OPTIONS](https://material.angular.io/components/dialog/api#MatDialogConfig) injection token

**Comment by crisbeto** [comment] 2019-09-11 12:14
@Totati is correct. Closing since it works as intended.

**Closed by crisbeto** 2019-09-11 12:14 UTC
