### ISSUE TITLE
Marker Collision Feature

### ISSUE THREAD

**Issue by BaidY1** [angular/components#26413] opened 2023-01-12 06:13 UTC
### Feature Description

As per request by many users in StackOverflow and couldn't find any documentation or implementation in angular for marker collision. 

### Use Case

As Markers could collide or overlap it should make that marker clusterer by not making it clusterer but by single marker on zooming out. This feature was in superclustererplus but not having in this make my projects so slow because of huge data.

**Comment by amysorto** [comment] 2023-05-05 21:49
Duplicate of #24978.

**Closed by amysorto** 2023-05-05 21:49 UTC
Labels: feature, needs triage
