### ISSUE TITLE
error (Angular Material - datepicker): Type MatDatepicker is not assignable to type MatDatepickerPanel<MatDatepickerControl

### ISSUE THREAD

**Issue by EliseiNicolae** [angular/components#24572] opened 2022-03-11 09:36 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I got this error when I tried to add a [max] value to my mat-datepicker:
<img width="785" alt="image" src="https://user-images.githubusercontent.com/43387542/157841335-af88b86e-a25a-490d-b8b4-7a88655a0b44.png">

### Reproduction

Steps to reproduce:
HTML:
```
        <mat-form-field appearance="outline" class="date-picker">
            <mat-label>Select Date</mat-label>
            <input matInput
                   [matDatepicker]="datePicker"
                   formControlName="dateOfAppointment" readonly [max]="today"
            >
            <img class="calendar-icon" src="assets/icons/Calendar.svg" (click)="datePicker.open()" alt="Datepicker">
            <mat-datepicker #datePicker></mat-datepicker>
        </mat-form-field>
```

TS:
`    today = new Date();`

### Expected Behavior

To work without that error.

### Actual Behavior

I got the error on my .html page.

### Environment

- Angular: 13.2.3
- CDK/Material: 13.2.3
- Browser(s): Brave
- Operating System (e.g. Windows, macOS, Ubuntu): Windows.

**Comment by crisbeto** [comment] 2022-03-11 09:54
The error seems weird, but it's worth noting that the `min` and `max` are set on the `input`, not the datepicker.

**Comment by crisbeto** [comment] 2022-03-15 09:58
Closing since this looks like a user error. The issue can be reopened if there's new information.

**Comment by EliseiNicolae** [comment] 2022-03-16 09:25
@crisbeto Hmm, but how can I set a [max] date value to my datepicker.

With [max] value I mean, the user will not be able to pick dates after that max date.

**Comment by crisbeto** [comment] 2022-03-16 09:35
What I meant with the comment above is that you're supposed to put the `[max]` on the `input`, not the `mat-datepicker`. It's still going to apply to the datepicker once it is opened.

**Comment by EliseiNicolae** [comment] 2022-03-16 09:42
@crisbeto But it is in the <input> tag: 

![image](https://user-images.githubusercontent.com/43387542/158561707-3b5d2e86-da48-42a8-9bbc-2d6f3a86358f.png)

**Comment by crisbeto** [comment] 2022-03-16 09:44
Oh, I'm sorry, I must've misread it. Reopening.

**Comment by zarend** [comment] 2022-03-30 16:34
Hmm I can't seem to reproduce this. Here's my [stackblitz using 13.3.0](https://components-issue-blxhx1.stackblitz.io).

**Comment by crisbeto** [comment] 2022-03-30 21:17
It sounds like an issue with Webstorm which we can't do anything about. Re-closing the issue.

**Closed by crisbeto** 2022-03-30 21:17 UTC
Labels: needs triage, area: material/datepicker
