### ISSUE TITLE
Virtual scroll within mat-menu don't work correctly

### ISSUE THREAD

**Issue by avgalon** [angular/components#17594] opened 2019-11-03 09:13 UTC
#### Reproduction
Try to put cdk-virtual-scroll-viewport within mat-menu.
I implemented the issue on stackblitz and also showed that it works within a plain div but don't work properly within mat-menu: https://stackblitz.com/edit/components-issue-zjhrcj

Steps to reproduce:
1. Open the menu
2. Scroll to about a quarter of the data
3. Close the menu
4. Open the menu again
5. There is no data till you scroll
 FYI: There are also some cases that the data is not filling the whole mat-menu height. I think there is a problem with the calculated translate of cdk-virtual-scroll-content-wrapper.
 
#### Expected Behavior

I expect to see the data after i close & open the menu again and i also expect that the data will fill all height all the time.

#### Actual Behavior

I can't see any data after following the repro. steps and there are times that the data is not filling the whole container height.

#### Environment

- Angular: 8.2.11
- CDK/Material: 8.2.3/8.2.3
- Browser(s): Chrome 78.0.3904.87
- Operating System (e.g. Windows, macOS, Ubuntu): 18.04.3 LTS

**Comment by jelbourn** [comment] 2019-11-06 02:13
Duplicate of #10122

**Closed by jelbourn** 2019-11-06 02:13 UTC
