### ISSUE TITLE
help(DragDrop): How to adjust scroll speed when dragging item to top or bottom

### ISSUE THREAD

**Issue by aavelyn** [angular/components#19816] opened 2020-07-01 07:47 UTC
#### What are you trying to do?

When dragging an item to the top or bottom, I expect to scroll the list the faster the further up/down I drag the item.
In Firefox on macOS it behaves as expected, scrolling faster the further down I drag the item. In Chrome and Safari there seems to be only one speed.

For me the behavior in Chrome would be most important, since I plan to use drag drop in an ionic project.

Does anybody know if the scoll is a custom javascript implementation in the cdk or some native browser feature?

#### What troubleshooting steps have you tried?

-

#### Reproduction

[Stackblitz](https://stackblitz.com/edit/angular-drag-drop-autoscroll?file=src%2Fapp%2Fapp.component.html)

Steps to reproduce:
1. Open in Chrome/Safari and try dragging an item. It scrolls only in 1 speed
2. Open in Firefox, scrolls faster the further down I drag the item
  
#### Environment

- Angular: 10
- CDK/Material: 10
- Browser(s): Chrome, Safari, Firefox 
- Operating System:  macOS

**Comment by crisbeto** [comment] 2020-07-01 14:25
Duplicate of https://github.com/angular/components/issues/19401.

**Closed by crisbeto** 2020-07-01 14:25 UTC
Labels: needs triage, troubleshooting
