### ISSUE TITLE
feat(sidenav): [ACCESSIBILITY] focus should not be allowed on elements placed "behind" the opened sidenav in over mode (at least)

### ISSUE THREAD

**Issue by GregoireLgt** [angular/components#26189] opened 2022-12-06 13:36 UTC
### For accessibility purposes,

When you open a sidenav in over mode, focus should not be allowed on elements placed behind the sidenav.

ng-bootstrap has a similar offcanvas component : https://ng-bootstrap.github.io/#/components/offcanvas/examples

Focus is restricted to the opened offcanvas until you explicitly dismiss it by pressing escape or the close button.

**Comment by amysorto** [comment] 2023-05-11 23:00
I am closing this bug because there is not enough context here. If there is a specific situation you are referring to, please [open a new issue](https://github.com/angular/components/issues/new/choose) and provide a reproduction. Thanks!

**Closed by amysorto** 2023-05-11 23:00 UTC
Labels: feature, needs triage
