### ISSUE TITLE
CDK Drag and Drop: Nested Drag and Drop does not allow sorting on same level

### ISSUE THREAD

**Issue by mmuehlich** [angular/components#18503] opened 2020-02-14 14:56 UTC
#### Reproduction

StackBlitz: https://stackblitz.com/edit/angular-wfrzq9

Steps to reproduce: 
1. Switch 'child a' and 'child b'
2. Directly switching a and b will fail
* Workaraound in the example: Drag child b after Parent_2 and drag it again into the list before child a

 
 
#### Expected Behavior

Dragging within the inner cdkDropList should work, the outher cdkDropList should only fire if the element is moved out of its list.

#### Actual Behavior

The inner cdkDropList does listen to the drag - the outer list is called.

might be caused by 
_components/src/cdk/drag-drop/directives/drop-list.ts 304:_
`ref.connectedTo(siblings.filter(drop => drop && drop !== this).map(list => list._dropListRef))`

#### Environment

- Angular: 9.0.0
- CDK/Material: 9.0.0
- Browser(s): Chrome  80.0.3987.87
- Operating System (e.g. Windows, macOS, Ubuntu): Win 10

**Comment by crisbeto** [comment] 2020-02-15 16:40
I spent a bit of time on this, but it looks like it'll be tricky if we want to cover all the cases. I have a solution that somewhat works [here](https://github.com/crisbeto/material2/commit/308ed6767e67446b398df1c40b551bdb237de820), but there are definitely edge cases that it won't cover.

**Comment by stefanomiccoli** [comment] 2020-04-29 10:31
any news on this? got the very same problem and still struggling to find a decent workaround

**Comment by mmuehlich** [comment] 2020-05-02 20:18
@stefanomiccoli - thanks for the update!

I ended up changing my DOM structure and avoiding any nested Drag and Drop. I needed Drag and Drop in and between trees, but finally used flat lists of DIVs instead (+several Divs outside the actual tree). CSS and JS make it look like an actual tree but in fact, it is just a flat list.

**Comment by james-logan** [comment] 2020-06-30 19:24
+1

**Comment by crisbeto** [comment] 2020-07-12 09:42
Duplicate of https://github.com/angular/components/issues/16671.

**Closed by crisbeto** 2020-07-12 09:42 UTC
Labels: area: cdk/drag-drop
