### ISSUE TITLE
bug(Material Checkbox): MAT_CHECKBOX_DEFAULT_OPTIONS doesn't work with [checked] attribute

### ISSUE THREAD

**Issue by ChrisBauer** [angular/components#19999] opened 2020-07-15 21:18 UTC
#### Reproduction

Stackblitz with repro: https://angular-pwkkbn.stackblitz.io

Steps to reproduce:
1. Open stackblitz
1. CIick on the checkbox or within the div with the green border 
 
#### Expected Behavior

The state of the checkbox should stay in sync with the displayed value of `shouldBeChecked`

#### Actual Behavior

The state of the checkbox never changes. It is always unchecked.

#### Workaround

Can be worked around using the deprecated MAT_CHECKBOX_CLICK_ACTION provider. In checkbox-configurable-example.ts in the linked Stackblitz (https://angular-pwkkbn.stackblitz.io), if you uncomment line 16 and comment out lines 19-22, it behaves properly.

#### Environment

- Angular: 10.0.4
- CDK/Material: 10.0.2
- Browser(s): Chrome, likely others
- Operating System: macOS

**Comment by jelbourn** [comment] 2020-07-16 21:50
Duplicate of #18465

**Closed by jelbourn** 2020-07-16 21:50 UTC
Labels: needs triage
