### ISSUE TITLE
Support dynamic theming

### ISSUE THREAD

**Issue by sebakerckhof** [angular/components#1460] opened 2016-10-10 09:03 UTC
#### Bug, feature request, or proposal:

Feature request. In angular material 1 it is possible to generate/swap themes dynamically.
The design guide of angular material 2 only mentions static theming.
However, for multi-tenant systems, where each tenant has a custom theme, this dynamic theming is very useful.
#### What is the expected behavior?

Similar to angular material 1
#### What is the current behavior?

Only static theming is possible, where you have to generate your css files from sass in advance.
#### What is the use-case or motivation for changing an existing behavior?

Multi-tenant systems.

**Comment by mbeckenbach** [comment] 2016-11-03 11:16
This use case not quite common and should be supported.
@sebakerckhof I was also thinking about creating a node js webservice that compiles the sass files, so i would only have to pass some parameters, let it compile and then include the correct compiled css file for each tenant. Not sure if the theme would really have to be generated at runtime.

**Comment by james-knerr** [comment] 2017-01-11 17:41
Any updates on this? My team is also looking for a way to theme components for a multi-tenant application so this would be incredibly helpful.

**Comment by mbeckenbach** [comment] 2017-01-23 08:49
@james-knerr Have a look at the multple themes section in docs. With a simple host binding you can easyly add a theme based on the tenant

**Comment by sebakerckhof** [comment] 2017-01-24 00:33
@mbeckenbach 
What do you mean with host binding?
The way I understand that section is that you would need to include all the CSS for all the tenants. This is exactly what we want to avoid.

+ tenants can usually be dynamically added/changed. This is still a build step, so not something we can modify at runtime.
Maybe tenants can choose their theme colors which are then stored to the databse. All of these use cases are neatly handled in angular material 1.

**Comment by bederman** [comment] 2017-02-20 03:44
Is there any update on this? The theming documentation is fairly vague and hasn't been updated in a couple of months. Specifically the @mixins talk. I'm unsure where to put what, and when I define multiple themes inside a file with classes I can't seem to dynamically switch them unless I add in some hacky ngIf statements into my component templates.

**Comment by IagoBarboza** [comment] 2017-03-07 16:53
Any update on this? [2]

**Comment by jelbourn** [comment] 2017-04-09 03:27
This is a "maybe someday" feature that we don't have any plans to work on in the near future.

**Comment by Noah1989** [comment] 2017-11-08 14:55
I see a possible solution for those who absolutely need to generate themes at runtime, for example to allow users to tweak the colors themselves.

As per the official documentation, it is possible to:

> `node-sass src/unicorn-app-theme.scss dist/unicorn-app-theme.css`
> and then include the output file in your index.html.

So it should also be possible to 

- put together the theme.scss using the user's custom preferences, 
- then use sass.js to compile it in the browser 
- and finally just put the result into a <style> tag 

and it should work, albeit with serious implications for application size and startup performance.

**Comment by Noah1989** [comment] 2017-11-21 11:52
This approach works:

`package.json`:
```json
    "dependencies": {
        ...
        "sass-js": "git://github.com/medialize/sass.js#master"
    }
```

`.angular-cli.json`:
```json
            "assets": [                
                ...
                {
                    "glob": "sass.worker.js",
                    "input": "../node_modules/sass.js/dist/",
                    "output": "./"
                },
                {
                    "glob": "_theming.scss",
                    "input": "../node_modules/@angular/material",
                    "output": "./"
                }
            ]
```

`sass-test.ts`:
```typescript
declare const Sass: any;

const sass = new Sass();
/* build your dynamically generated custom theme here */
const scss = `@import 'theming';
              // Plus imports for other components in your app.
              
              // Include the common styles for Angular Material. We include this here so that you only
              // have to load a single css file for Angular Material in your app.
              // Be sure that you only ever include this mixin once!
              @include mat-core();
              
              // Define the palettes for your theme using the Material Design palettes available in palette.scss
              // (imported above). For each palette, you can optionally specify a default, lighter, and darker
              // hue.
              $candy-app-primary: mat-palette($mat-pink);
              $candy-app-accent:  mat-palette($mat-indigo, A200, A100, A400);
              
              // The warn palette is optional (defaults to red).
              $candy-app-warn:    mat-palette($mat-red);
              
              // Create the theme object (a Sass map containing all of the palettes).
              $candy-app-theme: mat-light-theme($candy-app-primary, $candy-app-accent, $candy-app-warn);
              
              // Include theme styles for core and each component used in your app.
              // Alternatively, you can import and @include the theme mixins for each component
              // that you are using.
              @include angular-material-theme($candy-app-theme);`;

sass.preloadFiles('', '', ['_theming.scss'], () => {
    sass.compile(scss, result => {
        const css = result.text;
        const head = document.head;
        const style = document.createElement('style');
        style.type = 'text/css';
        style.appendChild(document.createTextNode(css));
        head.appendChild(style);
    });
});
````

**Please beware that this solution is about as elegant and efficient as this:**

![photo5390970000375916587](https://user-images.githubusercontent.com/161117/33071075-81931626-ceba-11e7-8483-f62537f62cbb.jpg)

**Comment by shaniqwa** [comment] 2017-12-03 19:19
how about doing that on the server side ? thats what i'm trying to do.... I was wondering if all I need to change a theme is simply include a new theme.css file to index.html ?

**Comment by USPTraining** [comment] 2018-08-10 02:47
I am trying to achieve using css custom variables

on my theme service I get the primary,  accent colours from my api;
then 

```
 var style = document.createElement('style');
style.type = 'text/css';
style.innerHTML = ':root { --primary: '+reasult.primary+'; --accent:'+reasult.accent+'}';
document.getElementsByTagName('head')[0].appendChild(style);  
```
Now on my theme.scss
i was trying to read it using css variable like 
$primary: var(--primary);
if I set this variable to any any of my class it sets properly
but unable to dynamically set up the color palette

What we need to do is 
$primary: mat-palette(#{$mat}-var(--primary));
$accent: mat-palette($mat-orange);
$warn: mat-palette($mat-red);
$theme: mat-light-theme($primary, $accent, $warn);
i tried with sass functions as well but no luck. may be i am doing something wrong.
nearly spent good 5 hours to solve but not able to achieve. 

but works well with this
on the same file
.topbar.mat-toolbar {
        box-shadow: none;
        background: var(--primary); / toolbar background color to blue because this blue comes from my db
        color: mat-contrast($primary, 600) !important;
    }

**Comment by USPTraining** [comment] 2018-08-12 06:41
I achieved it in a different way to avoid the time delay of saas compilation, I built the colour json file something like below. But this is a little bit of manual work. 
this is not the best approach but it not causing any delay for me. but you need to override the colours every single component. 
{
    "theme": {
        "50": {
            "background-color": "#FFEBEE",
            "color": "#000000"
        },
        "100": {
            "background-color": "#ffcdd2",
            "color": "#000000"
        },
        "200": {
            "background-color": "#ef9a9a",
            "color": "#000000"
        },
        "300": {
            "background-color": "#e57373",
            "color": "#000000"
        }
}

2. Read my primary, accent, warning colours from database. and wrote it as a css variable. Follow this step for all there colours.
 palette += ':root{';
 for (var key in data.theme) {
                        if (data.theme.hasOwnProperty(key)) {
                            palette += '--mat-primary-background-' +key +':' +data.theme[key]["background-color"]+';';
                            palette += '--mat-primary-color-' + key + ':' + data.theme[key]["color"] + ';';
                            ////        console.log(key + "->"+this.theme[key]["background-color"]);
                        }
                    }
 palette += '}';
                            const head = document.head;
                            const style = document.createElement('style');
                            style.type = 'text/css';
                            style.appendChild(document.createTextNode(palette));
                            head.appendChild(style);

--------------
and then override your 
 on your theme file use the variable. 
 @include angular-material-theme($theme); ////////////////////////Primary////////////////////////
    //#TopToolbar//
    .topbar.mat-toolbar {
        box-shadow: none;
        background: var(--mat-primary-background-600) !important;
        color: var(--mat-primary-color-600) !important;
    }

**Comment by bryanrideshark** [comment] 2018-12-11 14:59
@USPTraining , that ain't half bad....

I wonder if dynamic theming could be a separate module which is included, similar to how we have to import modules per component; Maybe if you want dynamic theming, you have to import a "dynamic theming" module.

**Comment by mdewell** [comment] 2019-04-04 12:08
Still nothing for this?  For the heck of it, I tried building a SCSS file that had all 500 level combinations  of colors using the following code:

    colorPalette: ColorPalette[] = [
      {colorName: 'red',         colorValue: 'red',     colorAbbreviation: 'Rd'},
      {colorName: 'pink',        colorValue: 'pink',    colorAbbreviation: 'Pi'},
      {colorName: 'purple',      colorValue: 'purple',  colorAbbreviation: 'Pu'},
      {colorName: 'deep-purple', colorValue: '#673ab7', colorAbbreviation: 'DpPu'},
      {colorName: 'indigo',      colorValue: 'indigo',  colorAbbreviation: 'In'},
      {colorName: 'blue',        colorValue: 'blue',    colorAbbreviation: 'Bl'},
      {colorName: 'light-blue',  colorValue: '#03a9f4', colorAbbreviation: 'LiBl'},
      {colorName: 'cyan',        colorValue: 'cyan',    colorAbbreviation: 'Cy'},
      {colorName: 'teal',        colorValue: 'teal',    colorAbbreviation: 'Tl'},
      {colorName: 'green',       colorValue: 'green',   colorAbbreviation: 'Grn'},
      {colorName: 'light-green', colorValue: '#8bc34a', colorAbbreviation: 'LiGrn'},
      {colorName: 'lime',        colorValue: 'lime',    colorAbbreviation: 'Lm'},
      {colorName: 'yellow',      colorValue: 'yellow',  colorAbbreviation: 'Ye'},
      {colorName: 'amber',       colorValue: '#ffc107', colorAbbreviation: 'Am'},
      {colorName: 'orange',      colorValue: 'orange',  colorAbbreviation: 'Or'},
      {colorName: 'deep-orange', colorValue: '#ff5722', colorAbbreviation: 'DpOr'},
      {colorName: 'brown',       colorValue: 'brown',   colorAbbreviation: 'Br'},
      {colorName: 'grey',        colorValue: 'grey',    colorAbbreviation: 'Gry'},
      {colorName: 'blue-grey',   colorValue: '#607d8b', colorAbbreviation: 'BlGry'}
    ];

    /* following is used to generate mat-theme.scss entries */
    developThemeClassText (){
      let theme-map = '';
      let themeAbbreviationCombination = '';
      let primaryColorName = '';
      // let primaryColorValue = '';
      let primaryColorAbbreviation = '';
      let accentColorName = '';
      // let accentColorValue = '';
      let accentColorAbbreviation = '';
      let warnColorName = '';
      // let warnColorValue = '';
      let warnColorAbbreviation = '';
      let foregroundColorValue = '';
      let foregroundColorAbbreviation = '';
      let backgroundColorValue = '';
      let backgroundColorAbbreviation = '';

      for ( let primaryCount = 0; primaryCount < this.colorPalette.length; primaryCount++) {
        primaryColorName = this.colorPalette[primaryCount].colorName;
        // primaryColorValue = this.colorPalette[primaryCount].colorValue;
        primaryColorAbbreviation = this.colorPalette[primaryCount].colorAbbreviation;
        for ( let accentCount = 0; accentCount < this.colorPalette.length; accentCount++) {
          accentColorName = this.colorPalette[accentCount].colorName;
          // accentColorValue = this.colorPalette[accentCount].colorValue;
          accentColorAbbreviation = this.colorPalette[accentCount].colorAbbreviation;
          for ( let warnCount = 0; warnCount < this.colorPalette.length; warnCount++) {
            warnColorName = this.colorPalette[warnCount].colorAbbreviation;
            // warnColorValue = this.colorPalette[warnCount].colorValue;
            warnColorAbbreviation = this.colorPalette[warnCount].colorAbbreviation;
            for ( let foregroundCount = 0; foregroundCount < this.colorPalette.length; foregroundCount++) {
              foregroundColorValue= this.colorPalette[foregroundCount].colorValue;
              foregroundColorAbbreviation = this.colorPalette[foregroundCount].colorAbbreviation;
              for ( let backgroundCount = 0; backgroundCount < this.colorPalette.length; backgroundCount++) {
                backgroundColorValue= this.colorPalette[backgroundCount].colorValue;
                backgroundColorAbbreviation = this.colorPalette[backgroundCount].colorAbbreviation;

                // tslint:disable-next-line:max-line-length
                themeAbbreviationCombination = primaryColorAbbreviation +  accentColorAbbreviation + warnColorAbbreviation + foregroundColorAbbreviation + backgroundColorAbbreviation;
                // tslint:disable-next-line:max-line-length
                theme-map += '$custom-' + themeAbbreviationCombination + '-ThemeMap:(primary: $' + primaryColorName + ', accent:$' + accentColorName + ', warn:$' + warnColorName + ', foreground-color: "' + foregroundColorValue +'", background-color: "' + backgroundColorValue + '");\n'
                // tslint:disable-next-line:max-line-length
                theme-map += '$custom-' + themeAbbreviationCombination + '-Theme: create-wonky-theme($custom-' + themeAbbreviationCombination + '-ThemeMap);\n'
                theme-map += '.custom-' + themeAbbreviationCombination + '-Theme {\n';
                theme-map += '  @include angular-material-theme($custom-' + themeAbbreviationCombination + '-Theme);\n';
                console.log('}\n';
              }
            }
          }
        }
      }
    }

It created about a 748MB file, and I don't think that's a good size for the user to open a page with 😃   Why can't an Angular Material switch the container backgrounds more dynamically?  You can do the primary, accent, and warn, "fairly" easily, but getting a background and other items is really involved.  If I'm not mistaken, simple JS can do the background-color switch without much trouble, but maybe that's a lot of overhead to deal with.

Maybe it's just a future wish and hopefully not a pipe dream.

**Comment by Rodrigo54** [comment] 2019-04-04 12:16
is there a way to make this work with css vars.
try this https://github.com/angular/material2/issues/4352#issuecomment-475755403

**Comment by mdewell** [comment] 2019-04-04 12:18
sorry forgot this wonderful item to enter in the scss:

    @function create-wonky-theme($wonkyThemeSettings)
    {
      $background: (
        background: unquote(map-get($wonkyThemeSettings, background-color))
      );

      $foreground: (
        base: unquote(map-get($wonkyThemeSettings, foreground-color)),
        text: unquote(map-get($wonkyThemeSettings, foreground-color))
      );

      @return (
        primary: map-get($wonkyThemeSettings, primary),
        accent: map-get($wonkyThemeSettings, accent),
        warn: map-get($wonkyThemeSettings, warn),
        is-dark: false,
        foreground: $foreground,
        background: $background,
      );
    }

**Comment by epelc** [comment] 2019-04-22 04:17
Any chance of switching the theme system to use css variables with a fallback to a single default theme? This would support ie11 + everything else and give an easy way to switch themes in a modern way.

https://caniuse.com/#feat=css-variables

**Comment by jpike88** [comment] 2019-05-28 10:07
This framework has gone backwards in some pretty fundamental ways. We serve our client to many different tenants, which have different themes.

So now I either have to do some hacky workaround, or build a bunch of different client apps that literally only differ by some css. wtf...

**Comment by clark-stevenson** [comment] 2019-09-02 09:19
Did anyone here have success with their chosen work around?

I am in the same position where basically, only the colours change on a white label app.  I am not a CSS guy so forgive my ignorance. 

When I generate a build,  I get `dist/some.css`.    

I am aware how primitive my suggestion is, but, if I choose a hideous theme with unique colours and build,  can I ask the server to find/replace those colours before shipping `/dist/some.css` to the browser?

Would that magically work for now and if so, is the road ahead bleak for compatibility issues going forward?

I would appreciate anyones thoughts/experience.

**Comment by crysislinux** [comment] 2019-09-02 10:08
`css-variables` seems pretty promising these days. even ie11 can work with it with a polyfill.

We override the colors with `css variables`  to support our simple theme solution in our company, and it actually works.

I used to create a solution with `jss`, which generate CSS dynamically, and created a package to override the theme from `material`. This also works and is much more powerful than `css variable` solution, but it's way more complex and maybe doesn't worth it.

**Comment by njifares** [comment] 2020-01-08 13:03
I don't understand that this is a P5 feature request that has been open for quite some time. Whitelabeling a product is a common case and creating a separate theme file for each customer is not a scaleable approach as it required a new build for each new customer. It also makes the final css file way too large. Unless I didn't read the comments correctly, a proper workaround doesn't exists yet, am I correct?

**Comment by maku** [comment] 2020-01-08 13:31
@njifares Using css variables - see https://blog.angularindepth.com/build-truly-dynamic-theme-with-css-variables-539516e95837 - Works really good...

**Comment by njifares** [comment] 2020-01-08 14:59
@maku Thanks! 

I need to look into a bit further so apologies if my question is obsolete but would this allow me to fetch the  customer specific colors from a database and create a material theme with it?

**Comment by clark-stevenson** [comment] 2020-01-08 16:29
@njifares 

https://github.com/johannesjo/angular-material-css-vars  allows you to do what you are after too although still figuring it out personally.

**Comment by njifares** [comment] 2020-01-08 16:37
@clark-stevenson awesome, many thanks!

**Comment by akvaliya** [comment] 2020-01-20 06:41
I also have requirement to detect domain & use colors pallet based on that from json file. This could easily done with material 1 But i am stuck in material 2+. Is there any way to achieve this?

**Comment by richardsengers** [comment] 2020-01-20 16:10
It looks like the Material team doesn't know this issue still exists ... it's probably on page 300 and since no one is assigned, it's not being picked up (Just my two cents)

**Comment by jelbourn** [comment] 2021-04-02 19:56
Duplicate of #4352

Closing this as a duplicate of #4352 since our approach theming will eventually shift to CSS variables. We won't ever be going down the path of run-time theming like AngularJS Material.

**Closed by jelbourn** 2021-04-02 19:56 UTC
Labels: P5, area: many, feature
