### ISSUE TITLE
Does mat-tree support MatNestedTreeNode.level property?

### ISSUE THREAD

**Issue by Ernio3** [angular/components#17945] opened 2019-12-12 10:14 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-dew9or

Steps to reproduce:
1. Just look at console log after it (tree) loads. Contents of the tree are not a subject of the issue - only the console error.

`ERROR TypeError: "_co.treeControl.getLevel is not a function"`
 
#### Expected Behavior

API notes presence of level property - for both flat and nested nodes.
https://material.angular.io/components/tree/api#MatNestedTreeNode
`treeControl.getLevel(dataNode)` should be able to retrieve it, right?

#### Actual Behavior

Using:
```
{{treeControl.getLevel(dataNode)}}
```
...is apparently broken? Or not documented well.
I've also tried accessing "level" property through:
```
@ViewChildren(MatNestedTreeNode)
nestedNodes: QueryList<MatNestedTreeNode<Privilege>>;
```
...but it always returns 0, no matter when or what node You ask.

It seems like level property is never set, nor supported by treeControl.

Should or will level property be supported in nested nodes?

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): Any/All (tested on Firefox)
- Operating System (e.g. Windows, macOS, Ubuntu): Any/All

**Comment by tommyc38** [comment] 2020-03-02 08:52
I can't get this to work either.  All I get is zero for my depth level.   

https://stackblitz.com/angular/xvqvbgonbbq

https://github.com/angular/components/issues/10872

**Comment by jasedwards** [comment] 2020-07-27 22:42
This is actually a regression I think.  Not having level as a property in the previous version of the cdk allowed me to create a pipe to add it myself.  Once I upgraded to version 9.x my pipe was overwritten with 0 for all of the levels.  Since the aria-level is used to style the tree in my repo this broke all styling. For a11y puposes it should not matter if this is 'nested' or 'flat'.  The correct level is still preferred.

**Comment by crisbeto** [comment] 2020-08-02 10:26
@jasedwards what was the last version where `aria-level` worked correctly for you? Looking through the git blame, the `aria-level` related code hasn't been touched in at least 2 years.

**Comment by jasedwards** [comment] 2020-08-04 13:17
@crisbeto  I know it worked for 8.2.0 so I am assuming it was in the change to 9.x

**Comment by crisbeto** [comment] 2020-08-09 09:10
@annieyw do you know if your changes from https://github.com/angular/components/pull/20226 will resolve this issue too?

**Comment by annieyw** [comment] 2020-08-10 16:44
https://github.com/angular/components/pull/20226 should resolve this issue and add `aria-level` for nested nodes too

**Comment by annieyw** [comment] 2020-10-19 20:45
Closing because it seems like the issue was resolved.

**Closed by annieyw** 2020-10-19 20:45 UTC
Labels: P2, area: material/tree, has pr
