### ISSUE TITLE
fr([BUTTON]): [BUTTON SIZES?]

### ISSUE THREAD

**Issue by MisterJ936** [angular/components#18774] opened 2020-03-10 06:41 UTC
#### Feature Description

I would like to see a new properties for button the determines their sizes, from extra small, small, default, large, and extra-large. 

#### Use Case

Using a css styling with button is a bad Idea, because if their is a new update on the button component, the css style would ignore some important styling for the button.

**Comment by geromegrignon** [comment] 2020-03-10 09:11
It would break [Material Design guidelines](https://material.io/components/buttons/#specs).

**Comment by jelbourn** [comment] 2020-03-11 00:13
Duplicate of #18241

**Closed by jelbourn** 2020-03-11 00:13 UTC
Labels: feature, needs triage
