### ISSUE TITLE
ivy: stepper component does not render when being used in a web component

### ISSUE THREAD

**Issue by GXGOW** [angular/components#18561] opened 2020-02-20 13:32 UTC
#### Reproduction

A minimal reproduction is available on [this repository](https://github.com/GXGOW/material-stepper-elements-ivy). Just run `npm install` and `npm test`.

You will notice that it will render properly when you add `enableIvy: false` property to `angularCompilerOptions` in `tsconfig.json`

Steps to reproduce:
1. Import `MatStepperModule` in you web component module
2. Create a `<mat-vertical-stepper>` or `<mat-horizontal-stepper>` component inside your component.
3. Build with Ivy enabled
4. Import the generated scripts in another HTML file
5. Serve the files using any web server
 
 
#### Expected Behavior

The stepper should render properly.

![image](https://user-images.githubusercontent.com/14166923/74937661-cb837a00-53ec-11ea-8a84-8c7c50261bb0.png)

#### Actual Behavior

Only the root element is being rendered. Lifecycle hooks are not being executed either.

![image](https://user-images.githubusercontent.com/14166923/74937919-595f6500-53ed-11ea-861d-60916df8aa81.png)

#### Environment

- Angular: 9.0.1
- CDK/Material: 9.0.1
- Browser(s):
  - Chromium 80.0.3987.116
  - Firefox Developer Edition 74.0b4
- Operating System: Arch Linux with Linux kernel 5.5.4-arch1-1

**Comment by devversion** [comment] 2020-05-31 00:15
Hello! Looks like this works for me with Angular v9.0.7. Could it be possible that this just didn't work in the past due to a bug in Angular? (I haven't searched for related issues/commits).

On my end, I just cloned your repro, ran `yarn` and ran `yarn test `. The stepper renders as expected w/ ripples and behavior. Can you double-check and update the reproduction if needed? Please keep us updated here. I'm closing this in the meanwhile, but we're happy to re-open. Thanks!

**Closed by devversion** 2020-05-31 00:15 UTC
Labels: needs triage

**Comment by GXGOW** [comment] 2020-06-01 18:52
It is indeed rendering properly with Ivy enabled on the latest version (9.1.9) of Angular. Thanks!
