### ISSUE TITLE
Bug: Drag and Drop not working inside MatDialog (wrong previous and current index)

### ISSUE THREAD

**Issue by betancourtc** [angular/components#15880] opened 2019-04-23 09:06 UTC
#### What is the expected behavior?
Reorder items in a list inside Mat-dialog using Angular Material Drag and Drop.

#### What is the current behavior?
Drag and drop does not work properly on the last items of the list. Previous and current index are the same in the **_moveItemInArray_** function

#### What are the steps to reproduce?
I have an array, where each item contains a list of colors. Clicking the edit button opens an Angular Material Dialog with the list of colors (for that item). The colors can be reordered using drag and drop. The list of colors from the first items of the list work fine, but when trying to reorder the list of colors in the last items of the list, drag and drop does not work. I did some debugging and found out that for the items not working, the event passed to the **_moveItemInArray_**, has the same number for the current and the previous index.

As previously mentioned, click on the edit button for one of the first items in the list and try reordering the colors, it works fine, choose the last item in the list and you will see the colors cannot be reordered, take a look at the console to get the previous and current indexes.

StackBlitz starter: https://stackblitz.com/edit/angular-u6dt7a<br/>

Not sure whether this is a CDK or a Mat-Dialog dialog.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7, Angular Material 7.3.7
Chrome, Firefox

#### Is there anything else we should know?
When reducing the list of items to just a couple of them, then all list of colors for all items work fine. Problem starts when the list of items starts to grow in number.

**Comment by Airblader** [comment] 2019-04-24 18:21
I'm having the suspicion that this somehow has to do with MatDialog. I've also observed that sometimes the indices are different, but still not correct. It also seems to only happen in combination with cdkDropList, a standalone cdkDrag works fine.

For the record, the data passed to the dialog doesn't matter – you can even pass a static array and observe the same effect.

What I've noticed is that where it doesn't work, the `transform: translate3d` doesn't get applied.

**Comment by betancourtc** [comment] 2019-04-26 08:26
I wasn't sure either where the problem was, but as you mentioned it might be on the MatDialog side and not the CDK. Any ideas on how to get this working? I don't see any errors on the console, so don't really know where to start looking to get a fix for this.

**Comment by Airblader** [comment] 2019-04-26 08:38
It seems to correlate of the combination of opening a dialog when you have scrolled the page. 

Try this: make the window as big as possible, load the app and open the dialog for the most bottom item without scrolling; it works fine. Now make the window smaller, reload the app, scroll to the same item and edit it again; it will now break.

As you can also see, when a dialog opens, somehow the body scroll disappears, which I assume is intended behavior for dialogs. I think this somehow interferes with the calculations done for the drag/drop translate styles.

**Comment by Airblader** [comment] 2019-04-26 08:43
Disabling the `cdk-global-scrollblock` class applied to the `<html>` tag when modals open makes the issue disappear.

**Comment by Airblader** [comment] 2019-04-26 08:46
@betancourtc I think a workaround would be to inject a `MAT_DIALOG_SCROLL_STRATEGY` that does not use the block scroll strategy. This is of course suboptimal since you probably do not want to allow scrolling while a modal is open – it should make the drag and drop work for now, though.

**Comment by Airblader** [comment] 2019-04-26 09:33
This is about as far as I was able to get. I think it would be good if the people working on drag and drop could weigh in now, at least we identified that the issue is the scrollblock.

**Comment by betancourtc** [comment] 2019-05-03 12:17
@Airblader Thanks a lot for your help. I hope too the people working on the drag and drop module take a look at this. Cheers

**Comment by andrewseguin** [comment] 2019-05-07 22:09
I'm unable to reproduce the issue, the drag and drop seems to be working correctly. Can you confirm it is breaking and let me know what browser and version you are using?

**Comment by betancourtc** [comment] 2019-05-08 06:40
@andrewseguin I was able to reproduce the issue trying to drag and drop the colors on the last theme (number 50) from my example in StackBlitz on Chrome Version 73.0.3683.103 (64-bit) and on Firefox Version 66.0.3 (64-bit). Both on Windows 10.

**Comment by Airblader** [comment] 2019-05-08 06:48
@andrewseguin The problem only occurs when you click "Edit" on one of the items on the bottom if you had to scroll (significantly). If you have a big monitor, make sure to resize the window to something small so you need to scroll down first.

I am absolutely able to reproduce with the provided StackBlitz (as can be seen by my previous research efforts).

**Comment by Airblader** [comment] 2019-05-08 06:50
BTW, I somewhat disagree with the P4 label. Drag and drop in a modal is no edge-case, and this is part of the CDK flat-out breaking in its core functionality.

**Comment by striky1** [comment] 2019-07-02 19:33
Hi here,

I can confirm that it is not working also on:

<pre><code>
Angular CLI: 8.0.3
Node: 10.16.0
OS: darwin x64
Angular: 8.0.1
</code></pre>

If I was scrolled down on site and then I opened dialog with Drag&Drop two lists, order in them or move item from list to another list is not working. Event of drop function returns same container for previous or current container property, with same indexes.

Can u take a look on that, pls? :)

**Comment by DeonduPreez** [comment] 2019-08-21 14:15
I ran into the same problem as @striky1 described [here](https://github.com/angular/components/issues/15880#issuecomment-507814905), the way I got around this was by scrolling the window to the top before opening the view and scrolling back down by subscribing to the afterClosed event of the modal like below:
`const doc = document.documentElement;`
`const left = (window.pageXOffset || doc.scrollLeft) - (doc.clientLeft || 0);`
`const top = (window.pageYOffset || doc.scrollTop) - (doc.clientTop || 0);`

    if (top != 0 || left != 0)
    {
      window.scrollTo({
                        top : 0,
                        left: 0
                      });
    }

`const modal: MatDialogRef = this.dialog.open(ModalComponent);`
modal.afterClosed().subscribe(() =>
                                         {
                                           if (top != 0 || left != 0)
                                           {
                                             window.scroll({
                                                             top     : top,
                                                             left    : left,
                                                             behavior: "smooth"
                                                           });
                                           }
                                         });

Sorry about the styling of this. I did it in a rush.

**Comment by endlessxaura** [comment] 2019-09-18 16:35
Just to weigh in, I'm having this problem as well.

**Comment by mksmtn** [comment] 2019-10-22 06:24
DnD does not work inside MatDialog for me with angular 9. It only drags an item, but dropping the item does not change its order.

**Comment by larqitos** [comment] 2019-11-01 16:37
@andrewseguin I have the issue as well and occurs when you scroll down on the page and enable a dialog with drag and drop functionality present. 

When the dialog is present the cdk-scroll logic modifies the head in the following way: 
<html lang="en" class="cdk-global-scrollblock" style="left: 0px; top: -2133px;"><head>

Setting top to 0 or creating a css override with top equal to 0 solves the problem but does cause the page to scroll in the background. Scrolling is still disabled so this is a bit better solution than the other suggested workaround. 

html.cdk-global-scrollblock {
    top: 0px !important;
}

If you implement this fix in a global style this will affect all dialog boxes, so I suggest you inject this in a component css class. You may need to leverage ::ng-deep (which I read will eventually go away but it still works in Angular 7)

**Comment by larqitos** [comment] 2019-11-01 18:02
Digging further into this the drag drop library adds an html element with fixed position to the bottom of the body tag. This is the item that you are actually dragging. This item updates its translate3d value as the user drags the item around. 

`<div _ngcontent-c34="" cdkdrag="" class="component-box cdk-drag ng-star-inserted cdk-drag-preview" style="touch-action: none; -webkit-user-drag: none; -webkit-tap-highlight-color: transparent; user-select: none; width: 422.188px; height: 46px; transform: translate3d(311px, 655px, 0px); pointer-events: none; position: fixed; top: 0px; left: 0px; z-index: 1000;" dir="ltr"><div _ngcontent-c34="" class="component-title">`

The translate3d value needs to be offset with the calculated scroll position of the page. This way the items will take into account the negative scroll implemented by the dialog and should allow drag and drop to work with the dialog. 

To confirm this scroll a small amount (around 10pxs) down the page and open the dialog with drag and drop items and if you drag down if you pull down enough you'll see the drag and drop have the offset and react as if the item were higher up when it really is further down.

**Comment by sumpton** [comment] 2019-11-01 22:23
If there is a way for the Drag and Drop component is inside mat-dialog, it would be helpful to console.log a warning. This is the first time I have used this component and spent too much time wondering where I went wrong, before hunting for bugs and finding this issue.

I can confirm that this works for the first item card in a listing page, but not after scrolling down the page.

Are there plans to fix this, or should it be avoiding in dialogs?

**Comment by ENM1989** [comment] 2019-11-26 11:02
Same problem here with mat-dialog and drag and drop.

**Comment by uvcreation** [comment] 2019-12-09 12:40
Same problem here, is someone got the solution for this issue?

**Comment by larqitos** [comment] 2019-12-11 00:54
@uvcreation  you can take a look at my quick fix here: https://github.com/angular/components/issues/15880#issuecomment-548856967

**Comment by uvcreation** [comment] 2019-12-11 17:11
@larqitos I have already tried your fix, it seems not working for me.

**Comment by kotsopoulosd** [comment] 2019-12-20 12:58
Same problem here but derives from different actions. (It has nothing to do with scrolling in my case)

The drag and drop lists are inside matDialog. The first time I open the dialog works fine in Chrome and IE. No matter how many times I open the same matDialog everything works fine.

However if I open another matDialog and then try to open the MatDialog with the drag and drop list, it does not work. The event.container is the same as the event.previousContainer.
The funny thing is that works fine with IE but not with Chrome.

Angular CLI: 8.3.8
Node: 10.16.3
OS: win32 x64
Angular: 8.2.9

**Comment by Hydhen** [comment] 2020-05-12 12:00
I have the same problem, but just with a single dialog, that contains a drag'n'drop directives, the directive works fine within my parent component, but doesn't react to drag inside a dialog
I have no scroll into my parent nor my dialog

**Comment by Tourist2010** [comment] 2020-06-08 09:57
adding the NoopScrollStrategy as a scroll strategy while opening the dialog seems to solve this issue.
```
const dialogRef = this.dialog.open(DialogComponent, {
     scrollStrategy: new NoopScrollStrategy()
}
```
Dont forget to import it 

`import { NoopScrollStrategy } from '@angular/cdk/overlay';`

**Comment by crisbeto** [comment] 2020-08-16 07:47
Duplicate of https://github.com/angular/components/issues/14280.

**Closed by crisbeto** 2020-08-16 07:47 UTC
Labels: P4, area: cdk/drag-drop, needs triage
