### ISSUE TITLE
bug(material/button): mdc unelevated button not getting custom theme color

### ISSUE THREAD

**Issue by BenGrn** [angular/components#26179] opened 2022-12-05 01:12 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When creating custom themes flat buttons revert to default font color instead of using theme contrast colors.

### Reproduction

Steps to reproduce:
1. Create a new Angular project with Material
2. Apply custom theme

https://stackblitz.com/edit/angular-jixnhd

### Expected Behavior

![image](https://user-images.githubusercontent.com/55842503/205528155-9d9a2fd2-99bf-484c-92da-1f0414b00ebc.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/55842503/205528188-a7ea1156-775c-431b-926d-8ce261fb3b70.png)

### Environment

- Angular: 15.0.2
- CDK/Material: 15.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MikaStark** [comment] 2023-01-05 15:30
Same here,
Buttons theme do not use contrast colors. It seems they are computed by mdc :/

**Comment by inlym** [comment] 2023-01-06 01:54
I got same problem!!!

**Comment by inlym** [comment] 2023-01-06 01:56
Notify me if resolved.

**Comment by NicholaAlkhouri** [comment] 2023-01-10 16:01
It looks that in the new mdc components, the button label text color is computed 

`$on-primary: if(contrast-tone($primary) == 'dark', #000, #fff) !default;`

while in version 14 it comes directly form the color palette

`color: var(--color-contrast-500);`

**Comment by richardsengers** [comment] 2023-01-20 11:34
Same problem here .... unable to update if those bugs don't get fixed :-(

**Comment by swierzbicki** [comment] 2023-01-27 14:25
Same problem. It would be nice to have a fix for that. We use orange color for my company and Angular Material sets the font color as black. So it breaks our company branding.

**Comment by the-ult** [comment] 2023-04-12 09:09
It seems like the contrast color is indeed (mostly) to dark.
The same with `on-secondary`

**Comment by NicholaAlkhouri** [comment] 2023-04-12 09:35
> 

I believe that is because the toggle-slider bg color is darker than the button. so the white color will create a sufficient contrast.

**Comment by wagnermaciel** [comment] 2023-04-19 19:46
Based on the team's current understanding, this _should_ be resolved when we complete the new token based theming api, which will grant **fully supported** finer-grained control over component styles

I say "should" because I'm afraid of promising this based on something that hasn't been finalized. If at any point it becomes clear that this will not be resolved by the new api, I will raise this issue again to make sure it gets handled

**Comment by ProjectBay** [comment] 2023-05-06 14:45
Same with checkboxes

**Comment by jpduckwo** [comment] 2023-05-10 07:16
This issue has broken our apps theming when trying to migrate to mdc components. We generate a generic theme using css vars and set those vars at run time. We have user-defined themes... However after trying the migration, we'd need to manually set an overriding style that pulls in the colour. Fingers crossed the token-based theming api will fix it!

**Comment by AlvaroP95** [comment] 2023-05-10 13:41
Angular 16 is already live, and this is not fixed. Any news on this?

**Comment by jpduckwo** [comment] 2023-05-12 01:57
@AlvaroP95 see @wagnermaciel's comment above from 3 weeks ago - the solution hasn't been developed yet so it won't be available in v16. If anyone knows the 'token based theming' issue / feature links can they please tag them here so we can track progress?

**Comment by jpduckwo** [comment] 2023-05-14 23:03
I also want to note that basic themed buttons have a hardcoded black text rather than inheriting the text color (previous behaviour), so if you put a basic button on darker background then the text colour might not be the correct contrast. Since the button background is clear and not white, I would think the previous behaviour makes more sense. (this is when generating a light theme - but I guess it's the same but opposite for dark however I haven't tested that)

**Comment by p3pp8** [comment] 2023-07-04 08:19
I had to override text color for raised button as custom contrast palette wasn't applied! Version 16.1.3, that's a shame!

**Comment by BenGrn** [comment] 2023-10-06 07:12
This is still impacting our applications when using custom palettes. Is there a road map for theming issue resolution?

**Comment by Tntpot** [comment] 2023-11-06 21:30
Just joining in to this thread, but this is an issue I've recently ran into also.

@wagnermaciel any update for this issue following the token-based theming updates?

**Comment by wagnermaciel** [comment] 2023-11-06 21:43
I tried this out on the latest which has the buttons partially swapped to using tokens, but the issue persists :( I'm going to dedicate some time to this tomorrow to see why this bug is so sticky

Here's the latest stackblitz for reference
https://stackblitz.com/edit/z7ywyp?file=src%2Ftheme.scss

**Comment by Tntpot** [comment] 2023-11-06 21:57
Much appreciated 😀

I actually came across this bug whilst trying to figure out why some of my accented buttons are coming out with darker text than I thought they should have, but now concerned I might also just not be fully understanding how to develop a colour palette...

Is the intention that these are calculated against the button colour so that the text contrasts appropriately?

**Comment by wagnermaciel** [comment] 2023-11-07 17:57
Ok! Took a look into this and confirmed that the text/icon color is being set to white or black based on a11y contrast ratios.

**This is working as intended** and has not changed in the latest implementation because we still want to encourage best practices for a11y when using our library

_But_ with the new tokens API, there is a **supported & maintainable** way to manually override this. Just override the css variables corresponding to the button text color (you can find these by looking through devtools - we're hoping to make these tokens easier to find in the future on our docs site)

https://stackblitz.com/edit/z7ywyp?file=src%2Ftheme.scss

```scss
.mat-primary {
  &.mat-mdc-button-base {
    --mat-fab-foreground-color: #fff;
    --mdc-filled-button-label-text-color: #fff;
    --mdc-protected-button-label-text-color: #fff;
  }

  &.mat-mdc-fab,
  &.mat-mdc-mini-fab {
    --mat-icon-color: #fff;
  }
}
```

P.S. The button tokens have just landed and overriding this is kinda janky atm. Once these are polished up, you should be able to just override all these css variables at the `.mat-primary` level (no need for `&.mat-mdc-button-base` or `&.mat-mdc-fab`, etc

P.S. P.S. We're still working on this "token" system and considering different ways to surface a cleaner interface for these types of overrides

**Closed** 2023-11-07 17:57 UTC
Labels: P2, area: theming
