### ISSUE TITLE
bug(form-field): New line added when entering text on form field on iOS 17 (actual phone - not simulator)

### ISSUE THREAD

**Issue by hisham** [angular/components#28511] opened 2024-01-31 16:57 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Legacy angular material

### Description

On iPhone 15, when entering text in a form field with a suffix, a new line is added even though there's enough room for the text. This only happens on a real phone. I can't reproduce it on a simulator or desktop browser responsive mode. 

See below

![IMG_2023](https://github.com/angular/components/assets/81853/cac73a4c-929d-4566-99f1-828798ee4991)

### Reproduction

Go to https://material.angular.io/components/form-field/overview#prefix--suffix on an iPhone 15 running iOS 17.2 (other iPhones may work too) and enter an amount in the dollar text field. 

### Expected Behavior

No empty line should be added. 

### Actual Behavior

Empty line is added. See above screenshot. 

### Environment

- Angular: 16 or 17
- CDK/Material: 16 or 17
- Browser(s): Safari
- Operating System (e.g. Windows, macOS, Ubuntu): iOS 17.2

**Comment by hisham** [comment] 2024-01-31 17:19
Actually this has nothing to do with suffix. It happens with all input boxes: 

![IMG_2024](https://github.com/angular/components/assets/81853/602ef9d3-2f15-4ab0-aec7-e4003259e4cf)

**Comment by hisham** [comment] 2024-01-31 17:33
If I make the input of type 'password' then it doesn't happen.

**Comment by hisham** [comment] 2024-01-31 17:50
I'm able to reproduce as well on an iPhone 12 running iOS 17.2 but not an iPad running iOS 16.

**Comment by hisham** [comment] 2024-01-31 17:59
note it only happens if you press backspace on a text field to clear text then type again.

**Comment by hisham** [comment] 2024-01-31 18:22
Tested on an iPhone X running iOS 16.5 - does not happen there.

**Comment by hisham** [comment] 2024-01-31 19:17
I upgraded the iPad above from iOS 16 to iOS 17 and can now repro on the iPad as well. So looks like this bug occurs only in iOS 17.

**Comment by crisbeto** [comment] 2024-02-01 05:02
Duplicate of https://github.com/angular/components/issues/28228.

**Closed by crisbeto** 2024-02-01 05:02 UTC
Labels: needs triage
