### ISSUE TITLE
bug(mat-input): floating label is cut off

### ISSUE THREAD

**Issue by BenGrn** [angular/components#26083] opened 2022-11-25 00:34 UTC
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v14

### Description

The floating label for mat-input components is cut off, a container appears to have overflow: hidden applied which cannot be overridden from CSS

### Reproduction

Steps to reproduce:
1. Copy example from material.angular.io/components/input/overview
2. Create standalone component.
3. Include component within application.
4. build in latest angular with latest material as of 25/11/22

### Expected Behavior

floating label to be visible when data entered into input

### Actual Behavior

floating label is cut off

### Environment

- Angular: 15.0.1
- CDK/Material: 15.0.0
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by geromegrignon** [comment] 2022-11-25 09:36
Hi @BenGrn, I followed your instructions, and I can't reproduce it.

GitHub project: https://github.com/geromegrignon/angular-float-label-bug
Deployed app: https://beamish-souffle-b927af.netlify.app/

Please provide a reproduction.

**Comment by BenGrn** [comment] 2022-11-25 09:49
Hi @geromegrignon it only appears to happen in an existing nx monorepo that was upgraded from nx14 to 15.
A new ng project outside of the nx monorepo behaved as expected. Inputs worked inside nx prior to updates.

**Comment by BenGrn** [comment] 2022-11-25 09:55
manually adding "./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css" to styles within project.json rectifies the issues of missing styles. Is this the intended use?

**Comment by RobinKamps** [comment] 2022-11-25 10:01
@BenGrn floating labels and cards work in my monorepo. Seems, that in your project are some css rules causing your issues. Besides this, the v15.0.0 material release sadly has a lot of bugs - not uncommon, because the whole underlaying architecture changed, but sadly this feels more like a beta or rc.

**Comment by geromegrignon** [comment] 2022-11-25 10:03
That's more likely related to how nx handles stuff and nothing this project can fix directly.
As long as I remember (my oldest project being with Angular 6), `ng add @angular/material` always added the theme in the angular.json file.

**Comment by crisbeto** [comment] 2022-11-28 11:41
Closing since it looks like an issue with the specific app.

**Closed by crisbeto** 2022-11-28 11:41 UTC
Labels: needs triage
