### ISSUE TITLE
bug(MAT-SELECT): View Value does not reflect ngModel, one way data binding is ignored, view does not truly reflect model changes. 

### ISSUE THREAD

**Issue by raysuelzer** [angular/components#27768] opened 2023-09-06 23:14 UTC
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version 

### The previous version in which this bug was not present was 

14.x

### Description

MatSelect, MatButtonToggleGroup (likely more) no longer allow a user to "cancel" a selection.  If you have a model that does not change, matSelect will still apply the change to the view. I.e. The option will be selected (even though that is not the model selection). 

Note: **ONE WAY** binding to ngModel (this also is the same for value).

```
<mat-form-field class="col__ compact">
  <mat-select
    placeholder="Connection Status"
    name="connectionStatus"
    [ngModel]="modelTest"
    (selectionChange)="modelTestChanged($event)"
    [disableRipple]="true"
  >
    <mat-option [value]="'active'">Active</mat-option>
    <mat-option [value]="'inactive'">Inactive</mat-option>
  </mat-select>
</mat-form-field>
```

```export class ExampleComponent {
  modelTest = 'active';

  constructor(private _cd: ChangeDetectorRef) {}

  modelTestChanged(event: any) {
    if (event.value === 'inactive') {
      const okay = confirm('Are you sure?');
      if (!okay) {
        this.modelTest = 'active';
        alert(`Okay, the model is now ${this.modelTest} and the select is not for some reason.`)
        this._cd.markForCheck();
        return;
      }
    }

    this.modelTest = event.value;
  }
}
```

I would expect the above to have 'active' selected when the user presses cancel on the Are You Sure Prompt? Nope, it is 'inactive' that is selected, no matter how many times I run detectChanges, or markForCheck.  The underlying model is 'active', but yet the select is showing 'inactive' as selected? This is fundamentally broken. 

### Reproduction

StackBlitz link:  https://stackblitz.com/edit/components-issue-7rgxn6?file=src%2Fapp%2Fexample-component.html,src%2Fapp%2Fexample-component.ts
Steps to reproduce:
1.  Create mat-select with two options and one way data binding to either ngModel or value. 
2. Create (ngModelChange) or (selectionChange) event handler.
3. Use this to update the model to something other than what was selected. 
4. Watch Material COmpletely ignore the underlying model and do what it wants.

### Expected Behavior

MatSelect MatToggles shoudl respect one way data bindings. 

### Actual Behavior

MatSelect and MatButtonToggleGroup update the view and disregard the model value. 

### Environment

- Angular: 16
- CDK/Material: 16.2.1
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu):Windows

**Comment by raysuelzer** [comment] 2023-09-06 23:51
The only workaround is to call .writeValue directly to get the mat-select, toggle, radio-group (etc) to reflect the reality of the model. The problem is that ngModel / value no longer working broke a ton of our code where we need to apply a transformation or cancel a selection based upon the user input.  i.e. we cannot use two way bindings.

**Comment by ajafff** [comment] 2023-09-07 07:55
this is not specific to mat-select. that's just how property binding works in Angular. if the binding value doesn't change between change detections, the property is not updated and the receiver is not notified.

I'm sure there exist duplicate issues in angular/angular. The root cause is that `ngModel` has an internal state and is not completely dependent on the input property. But that is intentional so that you can use ngModel without two-way binding.

**Comment by raysuelzer** [comment] 2023-09-07 16:02
The thing is you can no longer use one way bindings. This worked fine with version 14, and now breaks. One way binding should work as follows

component with ngModel internal state triggers change --> function picks up the changed value and updates model (or not) and triggers change detection --> component with ngModel updates to reflect model changes. 

What is currently happening as of version 15.  component triggers internal state changes --> component fires event --> function picks up change and updates model, triggers change detection --> component does not update internal state based upon the binding. 

It is literally impossible to now update using a one way binding after ngOnInit is called...

**Comment by raysuelzer** [comment] 2023-09-07 16:25
Here is another example with two buttons to manually set the value of ngModel. Note, that after you change the option to inactive and press cancel, the two buttons no longer cause any updates to the select.  The model is no longer bound to mat-select via one way binding. The two buttons do work fine before you use the select (i.e. before the internal state stops listening for model changes). 

https://components-issue-dtbkuj.stackblitz.io

**Comment by AshishKumar409** [comment] 2023-09-12 13:27
Hey @raysuelzer, I saw your code in stackblitz and implemented changed some code in it.

could you take a look into it. 

https://stackblitz.com/edit/components-issue-rzu9hf?file=src%2Fapp%2Fexample-component.ts

**Comment by mmalerba** [comment] 2023-09-25 18:04
Closing since this is working as Angular intends. Thanks for fixing the example @AshishKumar409!

**Closed by mmalerba** 2023-09-25 18:04 UTC
Labels: needs triage
