### ISSUE TITLE
schematic(table): Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by b-mi** [angular/components#15788] opened 2019-04-11 08:02 UTC
#### What is the expected behavior?
Do not work, ends with error "Cannot read property 'data' of undefined"

#### What is the current behavior?
Without error

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

Bad generated code:
```ts
  ngAfterViewInit() {
    this.dataSource = new InfoOProgDataSource(this.paginator, this.sort);
  }

Correct code:
  ngOnInit() {
    this.dataSource = new InfoOProgDataSource(this.paginator, this.sort);
  }
```

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Updated angular, material 7.3.7

#### Is there anything else we should know?
Better testing?

**Comment by Splaktar** [comment] 2019-04-11 20:29
Do you have a full stack trace to share?

**Comment by Splaktar** [comment] 2019-04-11 20:35
OK, I was able to reproduce this:
```js
ERROR TypeError: Cannot read property 'data' of undefined
    at TableComponent_Template (template.html:20)
    at checkView (core.js:8963)
    at componentRefresh (core.js:8772)
    at refreshChildComponents (core.js:7896)
    at refreshDescendantViews (core.js:7836)
    at checkView (core.js:8964)
    at componentRefresh (core.js:8772)
    at refreshChildComponents (core.js:7896)
    at refreshDescendantViews (core.js:7836)
    at renderComponentOrTemplate (core.js:8099)
```

**Comment by devversion** [comment] 2019-04-11 20:46
Issue can be fixed by using Angular's safe navigation operator when accessing the `dataSource` property.

https://github.com/angular/material2/blob/309d5644aa610ee083c56a823ce7c422988730e8/src/lib/schematics/ng-generate/table/files/__path__/__name%40dasherize%40if-flat__/__name%40dasherize__.component.html#L19-L24

Right now the `[length]` binding fails because `dataSource` is undefined until the view is initialized completely.

**Closed** 2019-05-17 23:50 UTC
Labels: P3, has pr
