### ISSUE TITLE
matInput / mat-form-field not working under FormArray

### ISSUE THREAD

**Issue by silentsnooc** [angular/components#16000] opened 2019-05-10 17:55 UTC
#### What is the expected behavior?

The default behavior of `matInput` inside a `mat-form-field`.

#### What is the current behavior?

It is not possible to modify/edit the `input`.

#### What are the steps to reproduce?

Two examples:
https://stackblitz.com/edit/angular-ckpey4?file=app/form-field-label-example.html
https://stackblitz.com/edit/angular-form-array-example-btww2s?file=src/styles.css

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

```json
   "@angular/cli": "7.2.3",
   "@angular/material": "^7.1.0",
   "typescript": "3.1.6",
```

**Comment by jelbourn** [comment] 2019-05-10 22:11
Something strange is definitely happening here, and I suspect it has something to do with the forms module and not the form-field.

**Comment by Airblader** [comment] 2019-05-11 05:20
I'm only on mobile right now, but I believe this is because the ngFor iterates over the value rather than the controls array itself. Maybe the value of an FormArray is just a getter, which would recreate the DOM nodes in every CD cycle and making it impossible to actually focus the input.

Iterating over the controls directly rather than the value, which is also how the forms guide does it, probably fixes the issue.

**Comment by Airblader** [comment] 2019-05-11 07:00
Got to my laptop now, and indeed switching from `offers.value` to `offers.contros` works: https://stackblitz.com/edit/angular-ckpey4-ffmokt

**Comment by silentsnooc** [comment] 2019-05-11 07:26
@Airblader Indeed. I guess this actually makes sense too. So it's probably not a bug but I used it wrong? If so I guess this issue can be closed?

fyi: I also got an answer on stackoverflow [1] regarding this issue. It also works using `trackBy`: https://stackblitz.com/edit/angular-ckpey4-c8yigk?file=app/form-field-label-example.ts

[1] https://stackoverflow.com/a/56083879/826983

**Comment by Airblader** [comment] 2019-05-11 10:54
Yeah, trackBy prevents that the DOM nodes get thrown away. I believe this should be closed as working as intended, yes.

**Closed** 2019-05-11 12:26 UTC
Labels: P3
