### ISSUE TITLE
bug(mat-menu): Smooth dropdown animation only works for first click only

### ISSUE THREAD

**Issue by Kirubelabr** [angular/components#20451] opened 2020-08-29 06:40 UTC
#### Reproduction

Steps to reproduce:
1. Create basic mat-menu following the official documentation
2. Click on menu trigger button
3. Click outside of menu options or lists
4. Click on menu trigger button again then it loses the smooth animation and just pop those options 
 
This issue is also visible on the official https://material.angular.io/ page too. 

#### Expected Behavior
Whenever there's a click on `menu-trigger` button, `mat-menu` options or lists should be animated smoothly than just popped on screen. This behavior works fabulously in `mat-select` component.

#### Actual Behavior

Smooth animation works only for the first click on `menu trigger button` then it loses the smooth animation and just pop menu content.

#### Environment

- Angular: Angular 10.0.9
- CDK/Material: 10.1.3
- Browser(s): Mozila Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Win 10

**Comment by crisbeto** [comment] 2020-08-30 08:15
Duplicate of https://github.com/angular/components/issues/20379 which has a pending fix.

**Closed by crisbeto** 2020-08-30 08:15 UTC
Labels: needs triage
