### ISSUE TITLE
DatePicker "matDatepickerParse" validator not working on first time value change.

### ISSUE THREAD

**Issue by keatkeat87** [angular/components#11523] opened 2018-05-26 09:11 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
it will run validate all the time.

#### What is the current behavior?
it will run validate only after i select a date.

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://stackblitz.com/edit/angular-szevpj?file=app/datepicker-filter-example.html<br/>

step to fail : 
1. keyin value 'abc' in datepicker input 
2. unblur the input 
3. you should see the 'required' and 'matDatepickerParse' error, but 'matDatepickerParse' missing.

step to success :  
1. select a date first
2. change input value to 'abc'.
3. you will see the 'required' and 'matDatepickerParse' error. it is expected behavior.

#### What is the use-case or motivation for changing an existing behavior?
In Material 5.x, it work as expected.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.3
Material 6.1.0

**Comment by micobarac** [comment] 2018-07-03 07:18
Is this issue officially fixed, or waiting for pull request?

**Comment by crisbeto** [comment] 2018-07-03 08:15
The pull request is still open.

**Comment by DavidMarquezF** [comment] 2018-08-02 15:45
When do you belive this issue will be fixed/closed? It would be really nice to have this fixed.

**Comment by aeslinger0** [comment] 2018-10-04 16:04
Any update? Will this fix #10861 as well?

**Comment by timby** [comment] 2018-11-19 18:14
This needs to either be merged ASAP or a workaround needs to be given, as the severity of this issue is high. This both prevents valid values and allows invalid values.

**Scenario 1: Field is shown as invalid when no value is present even though there is no required validator**

Steps to reproduce:

1. Enter a valid value
2. Change it to an invalid value.
3. Change it to an empty value.

Expected behaviour:

matDatepickerParse error does not exist

Actual behaviour:

matDatepickerParse error exists

Since it does not believe the value has been changed since it was invalid, the matDatepickerParse error is not removed.

**Scenario 2: Field is shown as valid even though an invalid value has been entered**

Steps to reproduce:

1. Enter a valid value
2. Change it to an empty value.
3. Change it to an invalid value.

Expected behaviour:

matDatepickerParse error exists

Actual behaviour:

matDatepickerParse error does not exist

Since it does not believe that the value has been changed since it was valid and empty, the matDatepickerParse error is not added.

**Comment by ienzam** [comment] 2018-12-01 02:04
Is there any progress on this?

**Comment by KlausHans** [comment] 2019-01-03 15:30
I stumbled over this too when the date invalid message did not disappeared if i delete the invalid date. 
A possible workaround that worked for me:
Use
```
@ViewChild('datepicker', { read: MatInput })
public datepicker: MatInput;
```
and 
```
<mat-form-field>
  <input #datepicker="ngModel" matInput [matDatepicker]="picker" placeholder="Choose a date">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
```
To delete or change the value:
```
this.datepicker.value = '';
```

If you want to check for errors in the date input you'll need a second viewchild:
```
@ViewChild('datepickerModel')
public datepickerModel: NgModel;
```
and
```
<mat-form-field>
  <input #datepickerModel="ngModel" #datepicker="ngModel" matInput [matDatepicker]="picker" placeholder="Choose a date">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
```

**Comment by damoe86** [comment] 2019-02-08 03:02
Has there been any progress with this issue? We are unable to use the above workaround as the value change is being triggered by the Reactive Forms Framework formGroup.patch() operations. 

The validation errors appeared correctly in Material 5.0. The DatePicker is the only control with this issue.

**Comment by erwindemoel** [comment] 2019-04-10 08:33
+1, we are having the same issue. When will this be fixed?

**Comment by anbiniyar** [comment] 2019-11-02 20:39
> looks to be working in version 8.
> 
> https://stackblitz.com/edit/angular-bmrxem
> 
> `@angular/material: 8.2.1`
> `@angular/core: 8.2.10`

I tried your suggestion but I am still running into the same issues. I am using 

`@angular/material 8.2.3` 
`@angular/core 8.2.13`

**Comment by tthrash** [comment] 2020-04-06 19:14
This is back again in `"@angular/material": "^9.2.0",`

**Comment by snehagodbole** [comment] 2020-06-17 17:46
To fix the issue i have implemented custom validator and in that added following code to skip matDatepickerParser validator :) . It worked like a chirm for me.
 if (control.errors && control.errors['matDatepickerParse'] && control.errors['matDatepickerParse'].text !== '') {
      return null;
    }

**Comment by logineimer** [comment] 2020-10-13 14:10
Got this bug in angular 10. @snehagodbole workaround is not working for me.

**Comment by jeler** [comment] 2021-02-03 19:45
This is still an issue. I've tried suggestions here and they haven't worked.

**Comment by astik** [comment] 2021-02-04 19:08
FWIW, i just test with angular 11 (11.1.2), building from @Shank09 code with Angular 8. It works as expected: https://stackblitz.com/edit/angular-ivy-gzzh5d

**Comment by sanjaypts** [comment] 2021-06-04 02:29
> To fix the issue i have implemented custom validator and in that added following code to skip matDatepickerParser validator :) . It worked like a chirm for me.
> if (control.errors && control.errors['matDatepickerParse'] && control.errors['matDatepickerParse'].text !== '') {
> return null;
> }

can you please share, the whole validator class code with us.
Greatly appreciate.

**Comment by sanjaypts** [comment] 2021-06-04 02:30
> FWIW, i just test with angular 11 (11.1.2), building from @Shank09 code with Angular 8. It works as expected: https://stackblitz.com/edit/angular-ivy-gzzh5d

We are still using angular 10 and still having same issue.

**Comment by Danielliudov** [comment] 2021-06-15 19:47
Any update on this one I am facing the same issue and can't find a workaround?

**Comment by sanjaypts** [comment] 2021-07-01 19:19
> Any update on this one I am facing the same issue and can't find a workaround?

Sorry for later reply.

But i am still stuck with it. No solution. Hope someone help.

**Comment by sanjaypts** [comment] 2021-07-01 19:47
> Got this bug in angular 10. @snehagodbole workaround is not working for me.

Did you find any issue about this?

Please help

**Comment by elharony** [comment] 2021-08-08 19:54
Any update? I am still facing the same issue on Angular 11

**Comment by TroyLDay** [comment] 2021-09-02 16:39
I have also run into this error when initializing component with an iso1861 date string in ng11.

**Comment by tmjeee** [comment] 2022-01-28 03:26
Seeing this in Angular 13 as well.

**Closed** 2022-02-26 16:26 UTC
Labels: P3, has pr, area: material/datepicker
