### ISSUE TITLE
virtual-scroll: mat-select with virtual scroll loses selection state

### ISSUE THREAD

**Issue by aalbericio** [angular/components#16352] opened 2019-06-21 09:32 UTC
#### Reproduction

https://stackblitz.com/edit/angular-2rtvdn

This stackblitz demos 2 mat-selects. 

The one on the left is a standard mat-select. This one works fine on every situation (despite the performace issues that may arise when using large dataproviders)

The one on the right is a mat-select using virtual-scroll. This one has several issues. I will just describe one here which I believe it's not been filed yet.

Steps to reproduce:

1. Select an option from the mat-select on the Right. The option is displayed fine once the selector gets closed.

2. Now open again the mat-select on the right. The selector shows nothing (#15902) but we let's continue working.

3. With the "blank" selector opened, scroll down using the mouse wheel. You will see options are displayed again. Scroll to some position where the "selected" value is not longer visible (outside the MatOption instances used by the virtual scroll). Now Press "ESC". 

4. Boom! The selector goes away (expected) but, despite the mat-select has a "value" set, the component shows nothing.
 
 
#### Expected Behavior

If we hit "ESC" o "click outside the mat-select", the control should always display the selected value, no matter if it's using default or virtual scroll.

#### Actual Behavior

The selected option is no longer displayed (but it's still set).

Obs:

1) "mat-select" seems to re-calculate its internal "selectionModel" and "empty" states once the selector is closed. It calculates this state using the available MatOptions which, of course, are not the full-set of options when using virtual scroll.

2) I don't know if this is a "virtual-scroll" bug or a "mat-select" bug but, anyway, the combination of both is crashing (somehow).

#### Environment

- Angular: 8.0.1
- CDK/Material: 8.0.1
- Browser(s): Chrome 74
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by jelbourn** [comment] 2019-06-21 20:18
Duplicate of #10122

**Closed by jelbourn** 2019-06-21 20:18 UTC
