### ISSUE TITLE
Angular Material: allow to define specified container for MatSnackBar

### ISSUE THREAD

**Issue by sophy8** [angular/components#18329] opened 2020-01-29 13:07 UTC
What is the current behavior?

Material SnackBar is always shown in the bottom(top) of whole page. It would be nice to have opportunity to define where the snack bar should appear

What is the expected behavior?

Angular Material  SnackBar  should have a setting to define a container in which the snackbar is positioned in.

**Comment by manklu** [comment] 2020-01-29 22:04
@sophy8 Quotation from the material style guide

> Snackbars provide brief messages about app processes at the bottom of the screen.

https://material.io/components/snackbars/#

**Comment by jelbourn** [comment] 2020-01-30 06:48
Duplicate of #7764

**Closed by jelbourn** 2020-01-30 06:48 UTC
Labels: feature
