### ISSUE TITLE
bug(Timepicker): With changing the time, date is changing too

### ISSUE THREAD

**Issue by horesse** [angular/components#30135] opened 2024-12-05 20:30 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In FormControl, when the time changes, the date also changes

### Reproduction

StackBlitz link: https://stackblitz.com/edit/czbajk-h7xm7v?file=src%2Fexample%2Ftimepicker-datepicker-integration-example.ts
Steps to reproduce:
1. Add FormControl
2. Add DatePicker and TimePicker
3. Change Date
4. Change Time
5. See formControl value and value in DatePicker

### Expected Behavior

Change only time in value

### Actual Behavior

Change date

### Environment

- Angular: latest
- CDK/Material: latest
- Browser(s): Chrome 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2024-12-05 20:52
Are you referring to the date _object_ being replaced?

**Comment by horesse** [comment] 2024-12-06 05:12
I expected DatePicker to change only date and TimePicker to change only time as implemented in your example using ngModel (https://rc.material.angular.io/components/timepicker/overview#timepicker-datepicker-integration).

**Comment by horesse** [comment] 2024-12-06 05:13
> Are you referring to the date _object_ being replaced?

I expected DatePicker to change only date and TimePicker to change only time as implemented in your example using ngModel (https://rc.material.angular.io/components/timepicker/overview#timepicker-datepicker-integration).

**Comment by horesse** [comment] 2024-12-06 05:13
> Are you referring to the date _object_ being replaced?

I expected DatePicker to change only date and TimePicker to change only time as implemented in your example using ngModel (https://rc.material.angular.io/components/timepicker/overview#timepicker-datepicker-integration).

**Comment by crisbeto** [comment] 2024-12-06 06:00
Ah okay now I see. This is an issue with `FormControl`, our demo works because it's using `ngModel`. Closing as a duplicate of https://github.com/angular/angular/issues/58522.

**Closed by crisbeto** 2024-12-06 06:00 UTC
Labels: needs triage
