### ISSUE TITLE
bug(google-maps): Identifier 'ɵngcc0' has already been declared 

### ISSUE THREAD

**Issue by danielehrhardt** [angular/components#22243] opened 2021-03-16 01:23 UTC
#### Reproduction
I am getting the Error when i am importing:
`import { GoogleMap, MapInfoWindow } from '@angular/google-maps';`
![image](https://user-images.githubusercontent.com/19570043/111241907-6190d080-85fe-11eb-917e-7dde7150c83c.png)

```
Error: ./node_modules/@angular/google-maps/__ivy_ngcc__/fesm2015/google-maps.js 16:12
Module parse failed: Identifier 'ɵngcc0' has already been declared (16:12)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
| import * as ɵngcc0 from '@angular/core';
| 
> import * as ɵngcc0 from '@angular/core';
| const _c0 = ["*"];
| class MapEventManager {
```

#### Environment

- Angular:
 "@angular/core": "^11.2.4",
 "@angular/google-maps": "^11.2.3",

**Comment by crisbeto** [comment] 2021-03-16 06:44
Duplicate of https://github.com/angular/angular/issues/41221.

**Closed by crisbeto** 2021-03-16 06:44 UTC
Labels: needs triage
