### ISSUE TITLE
Docs site is not working sometimes

### ISSUE THREAD

**Issue by anjmao** [angular/components#11745] opened 2018-06-11 12:21 UTC
#### Bug, feature request, or proposal:
Hi, I noticed what Docs Site is not working properly some times. I'm not sure if it as an issue of firebase cache or ServiceWorkers, after I terminate registered service workers it works just fine but hard refresh ctrl + F5 doesn't help.

<img width="1094" alt="material-site-404" src="https://user-images.githubusercontent.com/3028012/41230677-611a12aa-6d89-11e8-8f24-3a6c2d3579ec.png">

**Comment by amcdnl** [comment] 2018-06-11 13:20
That looks more like service workers. Can you reproduce it consistently?

**Comment by guschnwg** [comment] 2018-06-11 14:31
Sometimes I enter the website and a blank page appears.
If I ctrl+F5 the page it works normally.

**Comment by jotatoledo** [comment] 2018-06-11 18:47
Same experience as @guschnwg
Sometimes not even hard refreshs work for me

**Comment by amcdnl** [comment] 2018-06-12 13:45
Perhaps we should log a bug on angular/angular for this if you are seeing it too?

**Comment by m-henderson** [comment] 2018-07-21 15:23
it is because of the service worker

**Comment by amcdnl** [comment] 2018-07-22 13:44
I have made a PR to material docs site that should resolve the issue.

**Comment by m-henderson** [comment] 2018-07-23 14:29
@amcdnl could you link to the PR?

**Comment by jotatoledo** [comment] 2018-08-01 09:29
Any updates on this? This issue is ridiculously annoying.

**Comment by alex7egli** [comment] 2018-08-14 16:50
+1 same issue

**Comment by crisbeto** [comment] 2020-05-25 16:40
It looks like this has been resolved. Closing.

**Closed by crisbeto** 2020-05-25 16:40 UTC
Labels: area: dev-infra, docs, has pr, needs triage
