### ISSUE TITLE
The placeholder of mat-chip-grid-input couldn't always show

### ISSUE THREAD

**Issue by gailiwei** [angular/components#27785] opened 2023-09-13 06:36 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

![image](https://github.com/angular/components/assets/109653528/3e7874b4-43ba-4a3e-8046-78f625778642)
see this picture, I just want the New fruit.... placeholder always show, which is the default behavior in Angular 13.0, so do you have any solutions to make this always show in Angular 15?

### Reproduction

StackBlitz link: 
Steps to reproduce:
1. 
2.

### Expected Behavior

Always show the placeholder

### Actual Behavior

only shows if I focus the input text.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2023-09-22 03:46
Duplicate of https://github.com/angular/components/issues/16380.

**Closed by crisbeto** 2023-09-22 03:46 UTC
Labels: P4, area: material/chips
