### ISSUE TITLE
bug(mat-accordeon): mat-accordeon-title shows cursor on click

### ISSUE THREAD

**Issue by salvajavier** [angular/components#24753] opened 2022-04-08 14:22 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12

### Description

When creates a mat-accordion and clicks over the title a cursor shows. 

### Reproduction

Steps to reproduce:
1. Create a mat-accordeon with a header and a title
```
2. <mat-accordion>
      <mat-expansion-panel>
        <mat-expansion-panel-header>
          <mat-panel-title>Test</mat-panel-title>
        </mat-expansion-panel-header>
        Some Content
      </mat-expansion-panel>
    </mat-accordion>
```
3. Click over the title

### Expected Behavior

Expand accordeon without showing a cursor on the title.

### Actual Behavior

Expands accordeon showing a cursor on the title.

### Environment

- Angular: 13.3.0
- CDK/Material: 13.3.0
- Browser(s): Chrome Versión 100.0.4896.60 (Build oficial) (64 bits)
- Operating System (e.g. Windows, macOS, Ubuntu): alpine

**Comment by salvajavier** [comment] 2022-04-08 14:23
In Firefox 98.0.2 (64-bit) works as expected.

**Comment by crisbeto** [comment] 2022-04-08 17:01
This is intentional since the cursor indicates that the element is clickable.

**Comment by salvajavier** [comment] 2022-04-11 14:33
Maybe I missused the word "cursor". What appears is the indicator that you can write. A blinking vertical bar.

**Comment by crisbeto** [comment] 2022-04-13 14:37
I can't reproduce it on Firefox 99. Could it be some style override from your app that is changing the cursor?

**Comment by salvajavier** [comment] 2022-04-18 12:47
I tryied in Firefox 98.0.2 (64-bit) and it  works as expected.

Chrome updated to Versión 100.0.4896.75 (Build oficial) (64 bits) and now it works fine.

**Comment by crisbeto** [comment] 2022-04-22 09:31
Closing since it sounds like it was resolved.

**Closed by crisbeto** 2022-04-22 09:31 UTC
Labels: needs triage
