### ISSUE TITLE
Problem Overriding Angular material components styles

### ISSUE THREAD

**Issue by mrw007** [angular/components#24038] opened 2021-12-01 08:56 UTC
### What are you trying to do?

I have built a custom Web Application theme based on Angular Material UI Components. I'm overriding styles using @mixins and it was working in previous version of Angular/Angular Material (7 and up to 9). The problem occured after upgrading from Angular 9 to Angular 12. 

This how my styles.scss looks like:

``` scss
@use "~@angular/material" as mat;
 @include mat.core();

// Themes
@import "./themes/default-theme.scss";
@import "./themes/dark-theme.scss";

// Colors
@import "./scss/colors.scss";

// Main Mixin
@mixin custom-components-theme($theme, $colors) {
  @include app-style-theme($theme, $colors);
  @include secondary-sidenav-theme($theme, $colors);
  @include yes-no-theme($theme, $colors);
  @include skeleton-loader-theme($theme, $colors);
  @include avatar-bar-theme($theme, $colors);
  @include bottom-nav-theme($theme, $colors);
}

@include mat.all-component-themes($actulite-light-theme);

.default-theme {
  @include custom-components-theme(
    $actulite-light-theme,
    $colors-default-theme
  );
}

.black-theme {
  @include custom-components-theme($actualite-dark-theme, $colors-dark-theme);
}
```

### What troubleshooting steps have you tried?

- I was suspecting that Angular Material didn't load properly but it is working perfectly fine.
- The mixin override works on Angular 9 (Last stable version of the project).

### Reproduction

Steps to reproduce:
1. Load Angular Material theme.
2. Override Styles using mixins.

### Environment

- Angular: 12.2.13
- CDK/Material: 12.2.13
- Browser(s): Goggle Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Ubuntu (Using Docker containers)

**Comment by crisbeto** [comment] 2021-12-06 09:56
This isn't enough information to investigate the issue. How do the styles break? Do you get any build errors?

**Comment by mrw007** [comment] 2021-12-07 08:44
> This isn't enough information to investigate the issue. How do the styles break? Do you get any build errors?

The Application is successfully built, yet no sign of custom classes and mixins in the browser.
I tried another solution : 
- created a new angular 12 last week project and dropped all the files and dependencies in it. Same issue.
- Yesterday I created another one (Angular 12 too) and I did the same. This time it worked! 
Is it a peer dependency problem? I tried to trace down the issue comparing dependencies ( in package.json/package-lock.json) but still not luck. It's a weird bug because the source of the issue is unknown.

**Comment by crisbeto** [comment] 2021-12-07 09:02
Maybe your theme is included in a component that has view encapsulation?

**Comment by zarend** [comment] 2022-04-13 22:37
@mrw007 does the issue persist for you?

**Comment by mrw007** [comment] 2022-09-02 09:42
@zarend Sorry for the late response. So I decided to recreate another project and take the time importing dependencies individually. The project still working fine for now but technically the root cause is still unknown. I suspect that it was a peer dependency that caused the style not to load properly.

So I guess that you can close this issue for now if you want.

**Comment by zarend** [comment] 2022-09-02 21:08
Thanks for getting back to me @mrw007 . I'll go ahead and close this issue. Feel free to open another issue if you can find the root cause or have other issues.

**Closed by zarend** 2022-09-02 21:08 UTC
Labels: needs clarification, troubleshooting, area: theming
