### ISSUE TITLE
An unhandled exception occurred: Schematic "navigation" not found in collection "@angular/material".

### ISSUE THREAD

**Issue by Rajdeep-Das** [angular/components#18433] opened 2020-02-07 16:18 UTC
#### Reproduction

Steps to reproduce:
1. ng add @angular/material
2. ng generate @angular/material:navigation nav
 
#### Expected Behavior

What behavior were you expecting to see?
The navigation schematic will create a new component that includes a toolbar with the app name and a responsive side nav based on Material breakpoints.

#### Actual Behavior

What behavior did you actually see?
An unhandled exception occurred: Schematic "navigation" not found in collection "@angular/material".

#### Environment
- Angular:8
- CDK/Material:8.2.3
- Browser(s):Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 64bit

**Comment by jelbourn** [comment] 2020-02-07 17:27
Duplicate of #18435

**Closed by jelbourn** 2020-02-07 17:27 UTC

**Comment by Splaktar** [comment] 2020-02-07 17:45
You can find the Angular Material version 8 docs here:
https://v8.material.angular.io/guide/schematics#navigation-schematic
