### ISSUE TITLE
`ng generate @angular/material:navigation jnav` yields "... unhandled exception ..."

### ISSUE THREAD

**Issue by JoeCodeswell** [angular/components#18435] opened 2020-02-07 00:45 UTC
What am I doing wrong? According to my interpretation of [Navigation schematic](https://material.angular.io/guide/schematics#navigation-schematic) the following `ng generate ...` command should have worked.

``` powershell
PS rbeNgMat>  ng generate @angular/material:navigation jnav
An unhandled exception occurred: Schematic "navigation" not found in collection "@angular/material".
See "C:\Users\joeco\AppData\Local\Temp\ng-KACyoy\angular-errors.log" for further details.
PS rbeNgMat>
```

Thanks in advance.
Love and peace,
Joe
[angular-errors.log](https://github.com/angular/material.angular.io/files/4168456/angular-errors.log)

**Comment by Splaktar** [comment] 2020-02-07 16:53
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for docs infrastructure only.

I've transferred this issue to the correct repository.

**Comment by devversion** [comment] 2020-02-07 17:41
I looked into reproducing this, but wasn't able to. Based on the error being reported, it looks like an old version of the `@angular/material` is still installed. The schematic has been renamed to `navigation` from `nav` in v9. Can you please check if the latest version of Angular Material is used? 

#18433 reported the same issue but the issue explicitly mentioned Angular Material version 8 being used. For versions below v9, the schematic is named `nav`.

**Comment by JoeCodeswell** [comment] 2020-02-07 17:42
Hi Folks. I was in the middle of documenting the steps i took to generate the app when the issue was transferred & i lost my edit. I still suspect this may be a documentation issue because
- [v6 docs](https://v6.material.angular.io/guide/schematics) say
`ng generate @angular/material:material-nav --name <component-name>`
- [current docs](https://material.angular.io/guide/schematics) say `ng generate@angular/material:navigation <component-name>`

I'll append my app creation log at the end. 
RE "Can you please include the output of ng -v"
The creation log says:
``` powershell
PS system32> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.3.25
Node: 12.14.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.25
@angular-devkit/core         8.3.25
@angular-devkit/schematics   8.3.25
@schematics/angular          8.3.25
@schematics/update           0.803.25
rxjs                         6.4.0

```
Thanks for the help.
Love and peace,
Joe

[appCreateLog.md.txt](https://github.com/angular/components/files/4172188/appCreateLog.md.txt)

**Comment by Splaktar** [comment] 2020-02-07 17:43
You can find the Angular Components version 8 docs here:
https://v8.material.angular.io/guide/schematics#navigation-schematic

**Comment by JoeCodeswell** [comment] 2020-02-07 18:03
Hi @Splaktar  and @devversion , 
Thanks for the help.
So I got 3 things from this.
1. The current docs are for Angular Material version 9
2. The correct command for Angular Material version 8, looking it up on [https://v8.material.angular.io/guide/schematics](https://v8.material.angular.io/guide/schematics),  **is**
 `ng generate @angular/material:nav <component-name>`
3. The correct place for me to post this kind of issue is [https://github.com/angular/components](https://github.com/angular/components)

I can report that this WORKED LIKE A CHAMP!
``` powershell
PS rbeNgMat> ng generate @angular/material:nav jnav
CREATE src/app/jnav/jnav.component.html (931 bytes)
CREATE src/app/jnav/jnav.component.spec.ts (1234 bytes)
CREATE src/app/jnav/jnav.component.ts (582 bytes)
CREATE src/app/jnav/jnav.component.css (193 bytes)
UPDATE src/app/app.module.ts (1045 bytes)
PS rbeNgMat>
```
Thanks SO MUCH.
Love and peace,
Joe

**Comment by devversion** [comment] 2020-02-07 18:11
@JoeCodeswell Awesome. Thanks for reporting back, and glad that it works now!.

**Closed by devversion** 2020-02-07 18:11 UTC
Labels: P2, needs clarification
