### ISSUE TITLE
bug(MatTabs): Inkbar has incorrect position and flickers inside MatDialog

### ISSUE THREAD

**Issue by twjacobsen** [angular/components#19619] opened 2020-06-12 06:31 UTC
#### Reproduction

I have not been able to reproduce this in a stackblitz, so I hope that some screenshots are enough.
 
When the content of the tabs is wider than the tabs, the ink bar is off and flickers when animating from one tab to another. Calling `realigInkBar` from the debugger realigns, but I haven't found a place in my code where I can get that effect. And it would not remove the flickering. The flickering appears as if the ink bar animates to the correct position, but then gets readjusted to be off.

<img width="539" alt="image" src="https://user-images.githubusercontent.com/555812/84472007-cccfff80-ac86-11ea-9c50-78b3d5990f6b.png">

When the number of tabs overflows the width of the content (ie. pagination shows), there's no flicker and the ink bar is positioned correctly.

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/555812/84472065-e6714700-ac86-11ea-9b10-85f9b9e7ccac.png">

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.2.4
- Browser(s): Chrome 83
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by twjacobsen** [comment] 2020-06-12 06:36
A little more details: I appears that the ink bar is only badly positioned when the `mat-align-tabs` property is different from default (`start`) - it's `center` in my case.

**Comment by amysorto** [comment] 2024-05-07 19:08
Closing this issue since there is no Stackblitz to reproduce and this issue refers to the legacy tabs, which no longer exist.

**Closed by amysorto** 2024-05-07 19:08 UTC
Labels: P4, area: material/dialog, area: material/tabs, Fixed in MDC
