### ISSUE TITLE
Implement a stable sorting algorithm

### ISSUE THREAD

**Issue by jmeberlein** [angular/components#14412] opened 2018-12-06 19:49 UTC
The Javascript standards do not specify which sorting algorithm to use. Google Chrome and several other browsers are known to use Introsort, which is an [unstable](https://stackoverflow.com/questions/1517793/what-is-stability-in-sorting-algorithms-and-why-is-it-important) sorting algorithm. This matters from a UX perspective in any app, because it precludes multi-level sorting. The user can't just click on two columns in order and expect the first column to still be sorted for any given value of the second, because Introsort treats equal elements as interchangeable. 

As an example of this behavior, look at the Dessert table on [the overview page](https://material.angular.io/components/sort/overview) for mat-sort. If you sort by Calories, then Protein, the four entries with 4 g protein are all still sorted by calories. But if you sort by Fat, then Protein, the four entries with 4 g protein are no longer sorted by calories. The former, in my opinion, is the expected behavior.

To solve this issue, all you would have to do is add a stable sorting algorithm, even as simple as a bottom-up merge sort, then replace calls to sort() with calls to the new, internal algorithm.

**Comment by CaerusKaru** [comment] 2018-12-07 14:08
The instability for sorting was patched in V8 and landed in Chrome 70 (see [here](
https://v8.dev/blog/array-sort)). If it wasn’t already, Opera will pick up the patch in due course. Since Angular Material only supports the previous two versions of evergreen browsers, it likely isn’t worth the time to implement a well-tested solution only to deprecate it a few months later.

**Comment by jmeberlein** [comment] 2018-12-09 14:51
Wouldn't that only apply to Chrome, though? Or at least I just checked on Firefox 63.0.3, and it also has an unstable sort. But more importantly, it had *different* unstable behavior, with Calories > Protein being (coindicentally) in reverse order, and Fat > Protein being a different order. Implementing a stable sort for real, instead of relying on new versions of V8 and Spidermonkey, would also allow us to standardize sort orders across browsers, instead of test cases needing to have different expected outcomes depending on browser.

**Comment by CaerusKaru** [comment] 2018-12-09 15:14
Firefox has had a stable sort since Firefox 3, see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=224128)

**Comment by jmeberlein** [comment] 2018-12-09 17:10
All I know is that in Firefox Quantum, version 63.0.3, as running on Ubuntu 18.10, it is very much not a stable sort, as tested by attempting multi-level sorting in the sample mat-sort table. So at some point, it must be switching back to an unstable sort, for whatever reason.

**Comment by CaerusKaru** [comment] 2018-12-09 17:18
The example you linked to is broken. If you notice, the "sort" doesn't actually even work correctly. Just anecdotally, I tried sorting and received this as the "ascending" list for Carbs: [24, 37, 24, 67, 49].

Therefore, this issue should really be that the docs need to be updated with a working example.

**Comment by jmeberlein** [comment] 2018-12-09 19:01
The only *required* behavior is "Click to sort the column ascending, click again to sort descending, click again to deactivate". The problem is when you click multiple columns in sequence. If you click the Calories column, then the Protein column, you're guaranteed to have the four rows with 4 g protein above the one row with 6 g protein, but the order of the four is unspecified. On Chrome 70.0.3539.77 on Ubuntu 18.10 (cosmic), the (Calorie, Protein) pairs go (159, 4), (237, 4), (305, 4), (356, 4), (262, 6). But on Firefox 63.0.3 on the same, they go (356, 4), (305, 4), (237, 4), (159, 4), (262, 6). Similarly, if you click Fat, then Protein, you get (6, 4), (9, 4), (4, 4), (16, 4), (16, 6) on Chrome, or (16, 4), (4, 4), (9, 4), (6, 4), (16, 6) on Firefox.

Thus, the expected result of test cases varies depending on the environment. Sorting has different behavior depending on browser. 

This feature request would be defining the expected behavior to be a stable sort, which would allow test cases to be standardized across browsers and would allow multilevel sorting regardless of which browser a site is being accessed in.

**Comment by CaerusKaru** [comment] 2018-12-09 19:09
Ok, so we're back to the example being flawed. If you change the comparison function to be the following:
```ts
function compare(a: number | string, b: number | string, isAsc: boolean) {
  if (a < b) {
    return isAsc ? -1 : 1;
  } else if (a > b) {
    return isAsc ? 1 : -1;
  }
  return 0;
}
```
it should work as expected.

**Comment by jelbourn** [comment] 2021-03-23 22:50
Closing since, since this issue was posted, the native Array.prototype.sort function has become a stable sort.

(duplicate of #15714)

**Closed by jelbourn** 2021-03-23 22:50 UTC
Labels: P5, area: material/sort, feature
