### ISSUE TITLE
[Tooltip] Rendering many tooltips is slow

### ISSUE THREAD

**Issue by alexsapps** [angular/components#5369] opened 2017-06-27 02:42 UTC
Hello, I just wanted to report that using mdTooltip too much seems to slow down rendering time of my Angular app by a lot compared to adding many other components or *ngIfs.

I had a table that make <tr>s in an *ngFor and had 3 tooltips per row, and each row had a component tree with 15 ngIfs (transitively) and the component subtrees were of size ~10, but those 3 mdTooltips accounted for half of the change detection rendering time. (Removing the tooltip reduced rendering time in half. Computation of the tooltip text was trivial.)

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
At least Chrome

**Comment by julianobrasil** [comment] 2017-06-27 19:23
Can you provide a plunker example?

**Comment by alexsapps** [comment] 2017-06-28 03:00
Here's a plunker, but in the plunker it's fast. Yet in my project, I double checked again simply adding an mdTooltip="0" attribute is slowing it way down. I can't tell if the plunker is using the latest Angular / Material code. Is there an up-to-date starter plunker with Angular Material already set up?

https://plnkr.co/edit/HtEUoZ28ti3xILgxpyFJ?p=info

**Comment by alexsapps** [comment] 2017-06-28 03:34
Ok, updated the plunker, please see previous message. (I made a mistake and timed the same thing twice.)

In my browser, 1000 ngIfs renders in 50-90ms, whereas 1000 mdTooltips renders in 390-450ms.

**Comment by julianobrasil** [comment] 2017-06-28 05:45
I see it... but I don't think it's so unexpected. Not sure, but suposing the mdTooltip is based on mousein and mouseout events, it has to register them. Registering an event is a considerable time consuming task (and you're doing it a lot in the plunker).

To see the **`if`** component rendering time increase two times the actual value in your plunker, just register a click event in the spans: **`(click)="compute(2)"`**. Over here, it jumps from 63ms to 140ms just because of this. With two events handlers, it jumps to 225ms.

But I think the material guys will give you a more accurate answer.

**Comment by alexsapps** [comment] 2017-08-10 19:14
I heard Angular is now using native addEventListner for better performance.

However now it seems even slower, taking over 600ms to render 1000 tooltips, and each time I click it goes slower and slower.

Updated plunker since the old one stopped working:
https://plnkr.co/edit/q3w43vEFOQukzWuuRGJb?p=preview

**Comment by ztgluis** [comment] 2017-11-07 22:41
Just encountered this issue while adding matTooltips to large arrays of data

Here is a simplified version in a stackblitz, it will initially load a little slow but not too bad, uncommenting lines 14 and 17 in app.component.ts will make it significantly slower:

https://stackblitz.com/edit/angular-4x8ama?file=app%2Fapp.component.ts

**Comment by SaturnTeam** [comment] 2018-02-14 01:28
I get this lag too. If on of my function (even parent) have a `console.log` I see it's output on EVERY mosemove on tooltip of any (even child) components

**Comment by tuanjinn** [comment] 2018-07-25 15:08
I get this too.
Say I have 20 blocks, which has header block which contains 2 div with tooltips (each div).

When I reduced to 1 for each header block, the performance noticeably improved...

**Comment by nickwinger** [comment] 2018-08-29 10:36
same here...

**Comment by CNicolas** [comment] 2019-06-06 14:23
Hello,

I know the issue is old, but I'm having the same issue with Angular Material ^8.0.0.

The guys in my team found a work around by using SVG : create ONE custom tooltip and moving it on the hovered element (with a mess of absolute x and y calculation).

**Comment by julianobrasil** [comment] 2019-06-06 14:39
@CNicolas, you can try https://github.com/ncstate-sat/popover. It's very flexible, based on `cdkOverlay` and you can have just one instance (and anchors all over de place).

**Comment by CNicolas** [comment] 2019-06-21 06:49
Thank you @julianobrasil, it worked perfectly !

**Comment by jelbourn** [comment] 2021-04-02 19:36
There have been a handful of perf improvements for tooltips since this was opened:
https://github.com/angular/components/pulls?q=is%3Apr+tooltip+is%3Aclosed+perf

Going to close, but feel free to open a new issue if anyone has an example of excessive perf cost.

**Closed by jelbourn** 2021-04-02 19:36 UTC
Labels: P4, area: material/tooltip
