### ISSUE TITLE
Tooltip triggers have `user-select: none` due to HammerJS

### ISSUE THREAD

**Issue by alexw10** [angular/components#16850] opened 2019-08-23 03:16 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/angular-xbczsf

Steps to reproduce:
1. Try to select the text in the above stackblitz
 
 
#### Expected Behavior

What behavior were you expecting to see?
I think just because the tooltip is disabled on an element such does not mean the text behind it should not be selectable...

For example in a data table we have tooltips which we disable if the text is less than a certain amount of characters but as soon as it grows to that we enable the tooltip and put an ellipses on it. The problem is the text behind it when the tooltip is disabled is not selectable.

Work around I guess would be to have two divs for this text for example one with tooltip one without but this is very annoying to have to do.

#### Actual Behavior

What behavior did you actually see?
Text is not highlightable/selectable.

**Comment by jelbourn** [comment] 2019-08-23 22:18
This is caused by HammerJS adding inline styles to the tooltip trigger due to using Hammer's longpress for tooltips. The good news is that we're actively removing hammer from the components now (will be part of v9).

**Closed** 2019-10-01 20:34 UTC
Labels: P4, has pr
