### ISSUE TITLE
Material Chip Input Autocomplete not clearing

### ISSUE THREAD

**Issue by Venipa** [angular/components#15689] opened 2019-04-02 15:49 UTC
#### What is the expected behavior?
Clearing form control input after submit/adding

#### What is the current behavior?
Does not clear input, stays the same

#### What are the steps to reproduce?
- Type smth in
- Select the option
- Input should be cleared but it wont clear
Stackblitz: https://stackblitz.com/edit/angular-material2-issue-bhjklv

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Latest, Latest Material, Windows 10, ~3.1.1

#### Is there anything else we should know?
Noticed this last year tried this year again its still happening.
Am i missing smth?

Regards

**Comment by Venipa** [comment] 2019-04-16 07:55
error/bug exists still on the latest (7.3.7)

**Comment by jelbourn** [comment] 2020-05-27 22:34
Duplicate of #10968

**Closed by jelbourn** 2020-05-27 22:34 UTC
Labels: needs triage
