### ISSUE TITLE
bug(MatTabGroup): Pagination for tabs isn't properly re-initialized when underlying tab contents gets changed

### ISSUE THREAD

**Issue by nakhodkin** [angular/components#21945] opened 2021-02-18 11:28 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: 
- Components: https://stackblitz.com/edit/angular-xucgvn

Steps to reproduce:
1.  Navigate to [https://stackblitz.com/edit/angular-xucgvn](https://stackblitz.com/edit/angular-xucgvn)
2. Select the "Sixth" or "Seventh" tab
3. Put the tick next to "Switch between pages" which causes the contents within the MatTabGroup component to change. 
 
#### Expected Behavior
_What behavior were you expecting to see?_
I do expect that pagination-related chevrons won't appear in case if tab contents dynamically get reduced from greater to lesser like in the provided case.

#### Actual Behavior
_What behavior did you actually see?_
![material](https://user-images.githubusercontent.com/14351638/108344622-0974d300-71e6-11eb-9714-9470e722fb9d.gif)
I see that the tab pagination block is rendered with pagination controls 

#### Environment

- Angular: "^11.0.0"
- CDK/Material: "^11.0.0"
- Browser(s): Google Chrome Version 90.0.4417.0 (Official Build) canary (x86_64), Firefox 86.0b9
- Operating System (e.g. Windows, macOS, Ubuntu): OS X 11.2

**Comment by jelbourn** [comment] 2021-02-19 20:44
Duplicate of #13539

(I believe it's the same underlying issue)

**Closed by jelbourn** 2021-02-19 20:44 UTC
Labels: needs triage
