### ISSUE TITLE
bug(MatLegacyFormField): TypeError: Cannot read properties of undefined (reading 'pipe')

### ISSUE THREAD

**Issue by richardsengers** [angular/components#26335] opened 2022-12-28 11:07 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.7

### Description

For some reason after upgrading to version 15, the legacy **custom** form field control does not work anymore. (based on https://v14.material.angular.io/guide/creating-a-custom-form-field-control)
this._control is an empty object

<img width="310" alt="_control" src="https://user-images.githubusercontent.com/810038/209801460-0c8d3483-258f-4039-9cb3-fe798bb52154.PNG">

This is the setup, not very special

```
import { ChangeDetectorRef, Component, ElementRef, HostBinding, Input, OnDestroy, ViewChild } from '@angular/core';
import { ControlContainer, NgControl, NgForm, NgModel } from '@angular/forms';
import { MatLegacyFormFieldControl as MatFormFieldControl } from '@angular/material/legacy-form-field';
import { UntilDestroy } from '@ngneat/until-destroy';
import { Align, AnswerLabelPosition, RadiobuttonList, RepeatDirection } from '@shared/util/response-model';
import { Subject } from 'rxjs';

@UntilDestroy({ checkProperties: true })
@Component({
  selector: 'tsra-form-field-radiobutton-list',
  templateUrl: './form-field-radiobutton-list.html',
  providers: [{ provide: MatFormFieldControl, useExisting: FormFieldRadiobuttonlistComponent }],
  viewProviders: [{ provide: ControlContainer, useExisting: NgForm }],
})
export class FormFieldRadiobuttonlistComponent implements MatFormFieldControl<string>, OnDestroy {
  static nextId = 0;
  @ViewChild(NgModel, { static: true }) ngModel: NgModel = null!;
  readonly answerLabelPosition = AnswerLabelPosition;
  readonly answerAlign = Align;
  readonly repeatDirection = RepeatDirection;
  readonly ngControl: NgControl | null = null!;
  readonly shouldLabelFloat = false;
  readonly required = false;
  readonly disabled = false;
  readonly placeholder: string = null!;
  readonly focused = false;
  readonly empty = false;
  readonly stateChanges = new Subject<void>();

  @HostBinding() id = `radiobuttonlist-${FormFieldRadiobuttonlistComponent.nextId++}`;

  private _radiobuttonlist!: RadiobuttonList;

  // This one contains only the last radiobutton list on the page.
  @Input() set radiobuttonlist(radiobuttonlist) {
    this._radiobuttonlist = radiobuttonlist;
  }
  get radiobuttonlist() {
    return this._radiobuttonlist;
  }

  get errorState() {
    return this.radiobuttonlist.errorsAndWarnings.length > 0 && this.form.submitted;
  }

  private _value: string | null = null;
  get value() {
    return this._value;
  }
  @Input() set value(value: string | null) {
    this._value = value;
    this.stateChanges.next();
  }

  constructor(
    private elementRef: ElementRef,
    private changeDetectorRef: ChangeDetectorRef,
    private form: NgForm,
  ) {}

  // eslint-disable-next-line @typescript-eslint/no-empty-function
  setDescribedByIds(): void {}

  // eslint-disable-next-line @typescript-eslint/no-empty-function
  onContainerClick(): void {}

  ngOnDestroy() {
    this.stateChanges.complete();
  }
}

```

### Expected Behavior

It should have worked the same like in 14.2.7

### Actual Behavior

Getting an error after upgrading
Error message:
```
<root> TypeError: Cannot read properties of undefined (reading 'pipe')
    at MatLegacyFormField.ngAfterContentInit **(legacy-form-field.mjs:308:30)**
```

### Environment

- Angular: 15.0.4
- CDK/Material: 15.0.3
- Browser(s): Chrome 108.0.5359.125
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jordandh** [comment] 2023-01-02 19:30
I get the same error but it only happens when the app is built with `"aot": true`. It fails on `control.stateChanges.pipe(startWith(null)).subscribe(() => {`. `control` is defined but `stateChanges` is not. Its in the `MatLegacyFormField` class for this method:
```typescript
ngAfterContentInit() {
    this._validateControlChild();
    const control = this._control;
    if (control.controlType) {
        this._elementRef.nativeElement.classList.add(`mat-form-field-type-${control.controlType}`);
    }
    // Subscribe to changes in the child control state in order to update the form field UI.
    control.stateChanges.pipe(startWith(null)).subscribe(() => {
        this._validatePlaceholders();
        this._syncDescribedByIds();
        this._changeDetectorRef.markForCheck();
    });
    // Run change detection if the value changes.
    if (control.ngControl && control.ngControl.valueChanges) {
        control.ngControl.valueChanges
            .pipe(takeUntil(this._destroyed))
            .subscribe(() => this._changeDetectorRef.markForCheck());
    }
    // Note that we have to run outside of the `NgZone` explicitly,
    // in order to avoid throwing users into an infinite loop
    // if `zone-patch-rxjs` is included.
    this._ngZone.runOutsideAngular(() => {
        this._ngZone.onStable.pipe(takeUntil(this._destroyed)).subscribe(() => {
            if (this._outlineGapCalculationNeededOnStable) {
                this.updateOutlineGap();
            }
        });
    });
    // Run change detection and update the outline if the suffix or prefix changes.
    merge(this._prefixChildren.changes, this._suffixChildren.changes).subscribe(() => {
        this._outlineGapCalculationNeededOnStable = true;
        this._changeDetectorRef.markForCheck();
    });
    // Re-validate when the number of hints changes.
    this._hintChildren.changes.pipe(startWith(null)).subscribe(() => {
        this._processHints();
        this._changeDetectorRef.markForCheck();
    });
    // Update the aria-described by when the number of errors changes.
    this._errorChildren.changes.pipe(startWith(null)).subscribe(() => {
        this._syncDescribedByIds();
        this._changeDetectorRef.markForCheck();
    });
    if (this._dir) {
        this._dir.change.pipe(takeUntil(this._destroyed)).subscribe(() => {
            if (typeof requestAnimationFrame === 'function') {
                this._ngZone.runOutsideAngular(() => {
                    requestAnimationFrame(() => this.updateOutlineGap());
                });
            }
            else {
                this.updateOutlineGap();
            }
        });
    }
}
```

**Comment by jordandh** [comment] 2023-01-04 00:51
I believe I've figured out what triggers this error to happen but I'm still not sure why its happening. Just like @richardsengers I have a second decorator on my class besides `@Component`. If I remove the second decorator then the error goes away.

**Comment by hisham** [comment] 2023-01-16 18:45
+1. Upgraded to v15 and Sentry reported this error at the control.stateChanges line in webpack:/./node_modules/@angular/material/fesm2020/legacy-form-field.mjs in MatLegacyFormField.ngAfterContentInit at line 308:30:

```
        const control = this._control;
        if (control.controlType) {
            this._elementRef.nativeElement.classList.add(`mat-form-field-type-${control.controlType}`);
        }
        // Subscribe to changes in the child control state in order to update the form field UI.
       control.stateChanges.pipe(startWith(null)).subscribe(() => {
            this._validatePlaceholders();
            this._syncDescribedByIds();
            this._changeDetectorRef.markForCheck();
        });
        // Run change detection if the value changes.
```

**Comment by hisham** [comment] 2023-01-16 18:56
And just like @jordandh says - removal of ```@UntilDestroyed`` decorator resolves the issue.

**Comment by philmayfield** [comment] 2023-02-02 00:34
We are also experiencing this issue, and just to throw out another bit of info, in part of the migration the `target` line of `tsconfig.json` changes:

```json
- "target": "ES2020",
+ "target": "ES2022",
```

When we changed it back to `ES2020` the error also goes away.  I'm not sure what other ramifications that has however.

**Comment by philmayfield** [comment] 2023-02-02 01:12
May also be related, but I happened to notice where we're importing the `MatLegacyFormFieldControl` (components that are affected by this issue) that IDEs (both intellij and vscode) are seeing the import as the new one: 

![image](https://user-images.githubusercontent.com/8093223/216206403-7d95e96c-0236-451b-b358-8aac925415c8.png)

**Comment by crisbeto** [comment] 2023-05-20 07:51
Closing since this appears to be caused by the `UntilDestroy` decorator which interferes with the framework.

**Closed by crisbeto** 2023-05-20 07:51 UTC
Labels: needs triage
