### ISSUE TITLE
 Multi Select

### ISSUE THREAD

**Issue by kurubavinodkumar** [angular/components#15350] opened 2019-03-01 07:13 UTC
#### What is the expected behavior?
should trigger the button on  fist click only

#### What is the current behavior?
it triggering on 2nd click 

#### What are the steps to reproduce?
Providing a StackBlitz reproduction is the *best* way to share your issue. <br/>
StackBlitz starter: https://goo.gl/wwnhMV<br/>

select option from multi select and try to click on button

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
latest

**Comment by vinodn4** [comment] 2019-03-01 07:23
after selecting option from select and click on button not working for first time

**Comment by agpreynolds** [comment] 2019-03-01 07:40
It looks like you've sent the link to the stackblitz template rather than your own version

**Comment by vinodn4** [comment] 2019-03-01 08:03
> It looks like you've sent the link to the stackblitz template rather than your own version

@agpreynolds please download and run code 

[nknanbljxbk.angular.zip](https://github.com/angular/material2/files/2918493/nknanbljxbk.angular.zip)

**Comment by agpreynolds** [comment] 2019-03-01 08:16
Looks like this is a focus issue. When you select from the multi-select the overlay remains open as you may want to select a second option.

While the overlay is visible other events cannot be triggered. However if you click somewhere else on the page then click the button it works as expected.

I'm sure someone from the material team will confirm, but this looks like the control is behaving as designed.

**Comment by josephperrott** [comment] 2019-06-04 15:36
Closing as this is working as intended.  When an overlay is open, as it is while making a selection from the select list, any click outside the list is captured to close the overlay.  This is consistent with how the native `select` implementation works.

**Closed by josephperrott** 2019-06-04 15:36 UTC
