### ISSUE TITLE
Mat-menu incorrectly calculating its render position.

### ISSUE THREAD

**Issue by binson143** [angular/components#16455] opened 2019-07-05 03:44 UTC
#### What are you trying to do?

What are you trying to do?

Render a menu item `below` of a button
#### What troubleshooting steps have you tried?

What are you seeing that does not match your expectations? 
The menu item shifting its position to `above`, if its height > current view port height.
Expected: The menu should render below

### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: 
https://stackblitz.com/edit/angular-dsccj4

Steps to reproduce:
1. Click on the button. The menu shift its position to above, even though parent has enough space to accommodate .  
  
#### Environment

- Angular: 8
- CDK/Material:8
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  MacOs

**Comment by Airblader** [comment] 2019-07-05 05:04
Seems to be working as intended to me. It doesn't matter if the parent has enough space, if the menu would be outside the viewport, the fallback position applies so that the menu is visible without scrolling.

**Comment by binson143** [comment] 2019-07-05 07:07
@Airblader  you can see the issue after scrolling up a bit & try to click on the button  also is there any way that i can configure the menu render below if viewport has some estate than applying fallback

**Comment by andrewseguin** [comment] 2019-08-19 18:17
I'm not sure I understand the issue. When there is room, the menu shows up below the trigger. When there is not enough room, it shows up above the trigger. I can't reproduce a case where the menu is showing up in an unexpected place

**Comment by jelbourn** [comment] 2020-05-28 22:06
Closing this since we haven't been able to reproduce. Feel free to open a new issue if you can provide more reproduction details.

**Closed by jelbourn** 2020-05-28 22:06 UTC
Labels: cannot reproduce, needs triage, troubleshooting
