### ISSUE TITLE
bug(google-maps): Map won't load after assigning new options

### ISSUE THREAD

**Issue by Akxe** [angular/components#22082] opened 2021-03-02 15:17 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: (maps are not in stackblitz, unable to create sample there)

```ts
@Component({
  selector: 'rita-inquiry',
  template: `
    <button (click)="draggable.next(!draggable.value)">toggle</button>
    <google-map width="100%" height="100%" [options]="(mapOptions | async)!"></google-map>
  `,
  styleUrls: ['./inquiry.component.scss']
})
export class InquiryComponent {
  @ViewChild(GoogleMap) readonly map!: GoogleMap;

  readonly draggable = new BehaviorSubject(true);
  readonly mapOptions: Observable<google.maps.MapOptions> = combineLatest([
    this.draggable.pipe(
      map((draggable): Pick<google.maps.MapOptions, 'draggable' | 'draggableCursor'> => {
        return {
          draggable,
          draggableCursor: draggable ? undefined : 'default',
        };
      }),
    ),
  ]).pipe(
    map(([draggable], index) => {
      let initialMapOptions: Pick<google.maps.MapOptions, 'center' | 'zoom'> = {};
      if (!index) {
        initialMapOptions = {
          center: { lat: 49.8037633, lng: 15.4749126 },
          zoom: 8,
        };
      } else {
        initialMapOptions = {
          center: this.map.getCenter(),
          zoom: this.map.getZoom(),
        };
      }

      return {
        ...initialMapOptions,
        panControl: false,
        zoomControl: false,
        mapTypeControl: true,
        scaleControl: true,
        streetViewControl: true,
        streetViewControlOptions: {
          position: google.maps.ControlPosition.LEFT_BOTTOM,
        },
        fullscreenControl: false,
        //overviewMapControl: false,
        ...draggable,
      };
    }),
  );
}
```

Steps to reproduce:
1. Have an app with google maps included
2. Create a component with the code above
3. Click button 2 times
4. Move map (and observe how no tiles are loading)
 
 
#### Expected Behavior

When re-enabling dragging, I would assume, the map would work once again

#### Actual Behavior

No tiles are loading any more

#### Environment

- Angular: 11.2.3
- CDK/Material: 11.2.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2021-03-03 17:08
The issue seems to be caused by us passing in `undefined` as the `mapTypeId`. It'll be fixed by https://github.com/angular/components/pull/22098, but until it gets released, you should be able to fix it by passing in `mapTypeId` yourself.

**Closed** 2021-03-23 19:13 UTC
Labels: P3, area: google-maps, has pr
