### ISSUE TITLE
bug(material.io): CdkScrollable reference links broken

### ISSUE THREAD

**Issue by twerske** [angular/components#23569] opened 2021-09-10 18:43 UTC
Links to CdkScrollable seem to be broken across the site. 
Example: https://material.angular.io/cdk/scrolling/api#CdkVirtualScrollViewport links to https://material.angular.io/

Looks like cdk changes in docs may have broken linking?

**Comment by crisbeto** [comment] 2021-09-15 16:01
Duplicate of https://github.com/angular/components/issues/21114.

**Closed by crisbeto** 2021-09-15 16:01 UTC
Labels: docs, needs triage
