### ISSUE TITLE
Mat-Tree with nested tree nodes & custom trackBy not working as expected

### ISSUE THREAD

**Issue by llorenspujol** [angular/components#18534] opened 2020-02-18 11:25 UTC
#### Reproduction

To reproduce it just press the button 'Remove childrens'.

StackBlitz: https://stackblitz.com/edit/angular-nspdpz
 
 
#### Expected Behavior

I expect to remove all the childrens and keep only the nodes 'Fruit' and 'Vegetables'

**Note**: If trackBy function is not used, it works as expected.

#### Actual Behavior

Node childrens are removed from the tree.

#### Environment

- Angular: ~9.0.0
- CDK/Material: ~9.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2020-02-18 18:07
Sounds similar to https://github.com/angular/components/issues/15872.

**Comment by tommyc38** [comment] 2020-03-08 08:05
@llorenspujol and @crisbeto 

update the following function and it works.

```ts
 removeChildrens() {
    this.dataSource.data = null;  // add this
    this.dataSource.data = TREE_DATA_NO_CHILDRENS;
  }
```

**Comment by crisbeto** [comment] 2020-08-09 09:56
Closing as a duplicate of #15872.

**Closed by crisbeto** 2020-08-09 09:56 UTC
Labels: area: material/tree, needs triage
