### ISSUE TITLE
Document limitation of matRipple on native table rows and possible solutions

### ISSUE THREAD

**Issue by jchafik** [angular/components#11883] opened 2018-06-21 19:40 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?

The ripple effect should be contained within the table row.

#### What is the current behavior?

When using `<tr mat-row>` in Angular 6 instead of `<mat-row ...>`, the ripple effect isn't contained within its parent container. I believe this is caused by the fact that `div` (the container used for the ripple) is not a valid child of the `tr` element it's applied to.

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-myteuk

#### What is the use-case or motivation for changing an existing behavior?

N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Angular 6.x

**Comment by DevVersion** [comment] 2018-07-24 10:29
Actually that's a different issue than #11165. The issue seems to be that `position: relative` on elements with display `table-row`  does not have any effect.

Meaning that the ripples won't have the proper positions. Also `overflow: hidden` does not work. Both things are the foundation for the ripples.

**Comment by Chris2011** [comment] 2018-08-28 14:35
Have exactly the same problem. Any workrounds here?

**Comment by DevVersion** [comment] 2018-08-28 14:38
A workaround would be using `<mat-row>` instead of the native `<tr>` element.

**Comment by julien-vonoetinger** [comment] 2018-09-04 15:08
I have faced the same problem too and it would be nice to have a fix for this.

**Comment by daniel-mckenna** [comment] 2018-09-10 06:44
Also have the same issue.

**Comment by rocos-yishi** [comment] 2018-11-22 02:38
```
  <table mat-table [dataSource]="items">
    <!-- Name Column -->
    <ng-container matColumnDef="name">
      <mat-header-cell *matHeaderCellDef> Name </mat-header-cell>
      <mat-cell *matCellDef="let item"> {{item.name}} </mat-cell>
    </ng-container>

    <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;" matRipple></mat-row>
  </table>
```

That works for me. :)

**Comment by theunreal** [comment] 2019-01-02 14:44
Using Material 7.0.1 - I still experience this issue.

**Comment by MatthiasKunnen** [comment] 2019-01-07 23:14
I believe this is because `<tr>` may only contain `<td>` and `<th>` [(See spec)](https://html.spec.whatwg.org/multipage/tables.html#the-tr-element). The `overflow: hidden` on the `<tr>` is simply not respected by the browser (Chrome nor Firefox). Using a ripple on `mat-row` works, contrary to @glains' comment. I tested using 7.0.1.

**Opinion**  
After trying out the ripple on a table I came to the conclusion that, in my case, it's not a good idea due to the following reasons:

1. The row is far larger horizontally compared to vertically, this makes the ripple quite ugly
2. The ripple distracts when selecting text

**Comment by nalexander50** [comment] 2019-02-08 04:31
@rocos-yishi solution worked for me. It would be nice if it were added to the Examples section for Table on the Angular Material website.

**Comment by glains** [comment] 2019-02-24 09:38
@MatthiasKunnen Using the `mat-row` element, the ripple effect indeed works now.

**Comment by simeyla** [comment] 2019-04-04 22:04
Still not working?

You probably forgot `imports: [ MatRippleModule ]`

**Comment by gautamkrishnar** [comment] 2019-04-07 17:52
@simeyla thats the exact cause.. ripple is working fine for me even on tr.

**Comment by ccjmne** [comment] 2019-04-22 13:41
@gautamkrishnar It's not working for me either, and @MatthiasKunnen's comment does make sense to me.
Would you be able to share a working StackBlitz using `<tr mat-row matRipple>` please? We can't get it to work wit the "plain" `<table mat-table><tr mat-row><td mat-cell>` model :(

**Comment by MicMicMon** [comment] 2020-02-26 15:17
Any valid workaround on the `<table mat-table><tr mat-row><td mat-cell>` scenario?

**Comment by spyter** [comment] 2020-02-26 15:29
@MicMicMon, have you tried using the flex version of the table?

I'm using that in a project and matRipple works for me. If you have buttons in the row, you need to work some magic to disable the ripple effect from being propagated by the buttons, but other than that it seems to work. 

See this link for more info:

https://material.angular.io/components/table/overview#tables-with-code-display-flex-code-

**Comment by MicMicMon** [comment] 2020-02-26 15:53
Thanks @spyter 

Actually, because of the warning in the docs, and [all the good reasons listed here](https://github.com/angular/components/pull/10594), I wanted to stick with the `<table mat-table>` scenario - but indeed, moving to `<mat-table>` makes ripple work out of the box.

**Comment by alicanertop** [comment] 2020-03-03 15:03
> Thanks @spyter
> 
> Actually, because of the warning in the docs, and [all the good reasons listed here](https://github.com/angular/components/pull/10594), I wanted to stick with the `<table mat-table>` scenario - but indeed, moving to `<mat-table>` makes ripple work out of the box.

When i used like u said then sticky scenario will broken

Sorry for bad english

**Comment by QuickScoP3s** [comment] 2020-05-04 14:49
2 years later, Angular 9 still has this issue...
Luckily the workaround by @rocos-yishi still works, thanks!

**Comment by devversion** [comment] 2020-05-27 21:12
@QuickScoP3s Do you have any proposal in mind? This is obviously a limitation in browsers we are hitting due to our ripple implementation. `tr`, `td` elements are not displayed as blocks, hence `overflow: hidden` does not work. he incorrect position is also caused by a limitation of these table elements. See: https://bugs.chromium.org/p/chromium/issues/detail?id=417223.

There is not much we can do about this. Given there is a reasonable solution of using the non-native table when needing ripples, I'm closing this issue.

I'd love chatting more about this, but given our current situation, I believe there is no good way to make this work for native tables.

Here is an alternative example that shows how to make ripples work for native table-rows: https://stackblitz.com/edit/comp-11883?file=app/app.component.html.

**Comment by QuickScoP3s** [comment] 2020-05-27 21:34
I didn't mean to sound rude (apologies if I did), but since the issue was still open, so I though the team was still working on it. I've been using the <mat-table> approach to work around the problem, as suggested, with the downside being the sticky headers not working...  I'd loved seeing a solution as I originally wanted to use sticky headers 😉 I had no idea that the table itself was the limiting factor, but thanks for clearing this up!

**Comment by devversion** [comment] 2020-05-27 21:49
@QuickScoP3s No worries at all! Sorry if the state of the issue was unclear. I think we failed communicating clearly why this hasn't been resolved yet. Hopefully my latest message is clear enough. I've also created a demo StackBlitz that shows how ripples can be used together with native tables. That might be helpful to some people.

**Comment by Spencer-Easton** [comment] 2020-05-29 04:30
@devversion StackBliz demo works as advertised.  If this issue is not easily solvable your work around should be discoverable from the docs. Would save a bit of hair pulling ;)

**Comment by devversion** [comment] 2020-05-29 11:00
@Spencer-Easton Sounds reasonable. I'll re-open this as we could certainly have this documented in the ripple overview. Any help on this would be appreciated as it's most likely low-priority for us.

**Closed** 2021-05-26 02:46 UTC
Labels: P4, area: material/core, docs, has pr, help wanted
