### ISSUE TITLE
Tab header swipe

### ISSUE THREAD

**Issue by knoxjoseph** [angular/components#2291] opened 2016-12-20 09:12 UTC
#### Bug, feature request, or proposal:
Swipe enabled Tab header in mobiles instead of arrows when there are more tabs than the screen can show.

#### What is the expected behavior?
Left  to the author/creators. Just wanted to know if swipe is possible.

#### What is the current behavior?
Arrows for pagination/navigation

#### What are the steps to reproduce?

Providing a Plunker (or similar) is the *best* way to get the team to see your issue.
http://plnkr.co/edit/LIUdYpxboddsykFz34D0?p=preview

#### What is the use-case or motivation for changing an existing behavior?
Arrows for pagination on mobiles has usability problems.

#### Which versions of Angular, Material, OS, browsers are affected?
Angular 2 material

**Comment by ktersius** [comment] 2017-08-21 12:06
Maybe a start would be to just expose the MdTabHeader so developers can implement a "pan" solution themselves. 

https://github.com/angular/material2/issues/6569

**Comment by amcdnl** [comment] 2017-08-21 22:22
FYI - This is being addressed https://github.com/angular/material2/pull/6294

**Comment by jelbourn** [comment] 2019-10-31 17:23
Duplicate of #2209

**Closed by jelbourn** 2019-10-31 17:23 UTC
Labels: P4, feature
