### ISSUE TITLE
Dialog causes memory leak when dialog component contains a <button>

### ISSUE THREAD

**Issue by benelliott** [angular/components#10188] opened 2018-02-28 12:52 UTC
#### Bug, feature request, or proposal:

Instantiating a dialog with a component that contains a regular HTML `<button>` element causes a DOM node memory leak.

#### What is the expected behavior?

No memory leak

#### What is the current behavior?

Memory leak

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-dhmjle?file=app/app.module.ts

1) Open Chrome performance monitor
2) Click Memory > Garbage collect
3) Note the initial DOM node count (around 53)
4) Click the "No leaks on div" button a few times and watch the DOM node count climb
5) Close any open dialogs and press the "Garbage collect" button again
6) Watch the DOM node count decrease to around the initial value (plus some "sticky" dialog nodes that intentionally stick around)
7) Click the "Leaks on button" button a few times and watch the DOM node count climb
8) Close any open dialogs and press the "Garbage collect" button
9) Note that the DOM node count _does not_ decrease to the initial value

![memleak](https://user-images.githubusercontent.com/4996462/36788521-27fa06fa-1c86-11e8-8df9-9ec11f5819e8.PNG)

#### What is the use-case or motivation for changing an existing behavior?

Performance

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest StackBlitz (Material 5.1.0, Angular 5.2.1), Windows 10, Chrome v64.0.3282.186 64-bit

#### Is there anything else we should know?

Could be related to https://github.com/angular/angular/issues/20228

**Comment by StoneMorKnight** [comment] 2018-06-27 14:12
Any movement on this?

**Comment by letrim** [comment] 2018-07-17 17:53
Exact same behavion on Angular 6

**Comment by tesseris** [comment] 2019-08-03 18:35
The issue still persists in version 8.2.

**Comment by Splaktar** [comment] 2019-12-13 21:31
This is likely also caused by https://github.com/angular/angular/issues/25744.

**Comment by crisbeto** [comment] 2019-12-16 20:57
Should be fixed in `core` by https://github.com/angular/angular/pull/34409.

**Closed by crisbeto** 2019-12-16 20:57 UTC
Labels: P2, animation, perf
