### ISSUE TITLE
feat(material): Support CSP, headers with style-src 'self'

### ISSUE THREAD

**Issue by Rugshtyne** [angular/components#24633] opened 2022-03-21 14:35 UTC
### Feature Description

Our current CSP implementation contains `style-src 'self'` which is not compatible with Angular Material. It would be great that Angular Material would support such CSP headers and, for example, as a solution have a possibility to add CSP nonces or would disable such inline injections. There was already an [issue](https://github.com/angular/components/issues/12139) created before but was closed due to inactivity.

We have used 'unsafe-hashes' for some of the styles attributes but now, according to Dutch government, which we have to comply to, these should be removed.

If you think some workaround is possible or a minor fix in a code would do, it would be great to get that information. We could then maybe provide a pull request ourselves.

### Use Case

This would enable use of strict CSP headers regarding styles.

**Comment by jelbourn** [comment] 2022-03-24 15:22
Angular itself has this problem: https://github.com/angular/angular/issues/6361

That issue being addressed would be a prereq for components to tackle this.

**Comment by Rugshtyne** [comment] 2022-03-24 15:36
@jelbourn I have seen this but having in mind that it's open for around 6 years already is quite concerning. Am I right by saying that Angular Material is using Angular style injection infrastructure? Maybe it's possible to add, for example, nonces as attributes from Angular Material side?

At the moment we're using a custom shared_styles_host implementation but it is a hacky and not future proof way to tackle the issue, especially given the fact that Angular themselves have made some workarounds where they just inject style node into the DOM, bypassing the mentioned host.

**Comment by jelbourn** [comment] 2022-04-18 16:13
> Am I right by saying that Angular Material is using Angular style injection infrastructure

Yes, Angular Material is built with Angular and shows this issue, the same as any other Angular-authored components. The issue is old, but it has never been a high priority because Google's security engineering team doesn't deem `default-src self; style-src unsafe-inline;` particularly risky.

**Comment by Rugshtyne** [comment] 2022-04-19 08:40
> > Am I right by saying that Angular Material is using Angular style injection infrastructure
> 
> Yes, Angular Material is built with Angular and shows this issue, the same as any other Angular-authored components. The issue is old, but it has never been a high priority because Google's security engineering team doesn't deem `default-src self; style-src unsafe-inline;` particularly risky.

How about possibility to add, for example, nonces as attributes from Angular Material side?

**Comment by jelbourn** [comment] 2022-04-19 15:32
The component library would have to stop using Angular's `styles` / `styleUrls` API and manually handle loading component styles, which is really outside the scope of what a component library should be doing.

**Comment by Rugshtyne** [comment] 2022-04-20 06:40
> The component library would have to stop using Angular's `styles` / `styleUrls` API and manually handle loading component styles, which is really outside the scope of what a component library should be doing.

Can you maybe point me to the place where such APIs are used in Angular Material? Maybe I could see some solution or a workaround

**Comment by jelbourn** [comment] 2022-04-20 19:46
> Can you maybe point me to the place where such APIs are used

It's in every component's `@Component` decorator. It's the standard way of including styles with an Angular component. There very likely is not an alternative here that will work in the OSS web ecosystem and for our build system inside Google.

**Comment by wagnermaciel** [comment] 2022-04-27 16:57
@jelbourn Is this something we would even consider changing on our end? Seems like if this were to be done it would be handled by the framework, right?

**Comment by jelbourn** [comment] 2022-04-27 19:59
Yeah, I would really consider this a duplicate of that framework issue.

**Comment by wagnermaciel** [comment] 2022-04-27 20:06
Closing as a duplicate of https://github.com/angular/angular/issues/6361

**Closed by wagnermaciel** 2022-04-27 20:06 UTC
Labels: feature, needs triage, under consideration
