### ISSUE TITLE
bug(button): Palette contrast values are not applied

### ISSUE THREAD

**Issue by mlimones-pensare** [angular/components#26056] opened 2022-11-22 12:32 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.x

### Description

When using a custom theme the contrast values from a custom palette are not applied

### Reproduction

# steps
- define a custom palette with a "slightly light" color and a white contrast color

``` css
$md-secondary: (
  ...
  500 : #f86072,
  ...
contrast: (
  ...
    500 : #ffffff
  ...
  )
);
```
- Apply the theme
```css
$theme-primary: mat.define-palette($md-primary,500);
$theme-accent: mat.define-palette($md-secondary,500);
$theme-warn: mat.define-palette(mat.$red-palette);
$theme: mat.define-light-theme((
  color: (
    primary: $theme-primary,
    accent: $theme-accent,
    warn: $theme-warn,
  ),
  typography: mat.define-typography-config(),
));
@include mat.all-component-themes($theme);
```
# example: 

https://stackblitz.com/edit/angular-5b8rw5?file=src/theme.scss

### Expected Behavior

Text in accent button should be white (contrast color) as specified in the palette

### Actual Behavior

Text in accent button is black

### Environment

- Angular:15.0.0
- CDK/Material:15.0.0
- Browser(s):chrome, safari
- Operating System (e.g. Windows, macOS, Ubuntu):Ubuntu

**Comment by GeorgDangl** [comment] 2022-11-27 11:18
We're having the same issue, using the cyan 600 color as primary, button color (text and icons) is black. It used to be white before.

However, I've noticed that using a slightly darker cyan 700, the color seems to work again. But, then the primary color is off, of course😀

**Comment by sergidt** [comment] 2022-12-19 10:30
Same issue, and breaking all my product styles and need to be overwritten, forcing colors hardcoding rules

**Comment by inlym** [comment] 2023-01-06 06:43
Notify me if resolved.

**Comment by davidpawar** [comment] 2023-01-09 15:52
Also facing the same issue.

**Comment by johnnygerard** [comment] 2023-01-09 20:51
Same issue.

**Comment by pqt-tmeitz** [comment] 2023-01-30 08:55
are there any updates yet?

**Comment by Frankitch** [comment] 2023-02-01 14:49
Same issue for me, my workaround:
```
.mat-mdc-unelevated-button.mat-primary,
.mat-mdc-unelevated-button.mat-accent {
  --mdc-filled-button-label-text-color: var(--player-primary-contrast-500);
}

.mat-mdc-raised-button.mat-primary,
.mat-mdc-raised-button.mat-accent {
  --mdc-protected-button-label-text-color: var(--player-primary-contrast-500);
}
```

**Comment by MichalK6677** [comment] 2023-02-02 09:08
The problem is still there. The Angular Material v15 is not usable for more than 2 months.

**Comment by bjoernboehnke** [comment] 2023-02-06 00:49
Just as an information for others facing an issue like this:
There seems to be a change affecting "unthemed" buttons. A button in my application changed text-color after upgrading to angular material 15 from white to black. It is placed on a dark background. I found this issue and assumed it was caused by this. Just give it a try and give your button a color attribute if it has none and select primary, accent or warn depending on your background. You can use mat-flat-button and then the correct contrast color is selected.
Definitely not a solution for everybody but worked for me.

**Comment by angelaki** [comment] 2023-02-17 08:58
Any chance this will get fixed soon? I need my contrast color to get used because our CI uses a white font on a pretty light blue. Now all the buttons etc. have a black text.

**Comment by mvanderlee** [comment] 2023-02-17 20:39
More details here: https://github.com/angular/components/issues/26153

**Comment by sonphnt** [comment] 2023-02-23 21:51
the same issue to me as well, contrast color does not work.

**Comment by Geniewave** [comment] 2023-03-16 21:58
same issue here

**Comment by ChristianKohler** [comment] 2023-03-22 08:04
Same issue. As @beckerjohannes mentioned above, the issue is that for buttons the contrast color is not used. Instead the `on-primary` color from material/theme is applied. 

The `on-primary` color is used for the button text color.

https://github.com/angular/components/blob/96aadaa411a3af93626af9aa73fb4abd6600d0b3/src/material/button/_button-theme.scss#L50

Now `on-primary` is defined here:

https://github.com/material-components/material-components-web/blob/cedffb44c0c5e2b6aeca591b4e5d19346a52983c/packages/mdc-theme/_theme-color.scss#L137

```

@function tone($color) {
  $minimumContrast: 3.1;

  $lightContrast: contrast($color, white);
  $darkContrast: contrast($color, rgba(black, 0.87));

  @if ($lightContrast < $minimumContrast) and ($darkContrast > $lightContrast) {
    @return 'light';
  } @else {
    @return 'dark';
  }
}

@function contrast-tone($color) {
  @return if(tone($color) == 'dark', 'light', 'dark');
}


$on-primary: if(contrast-tone($primary) == 'dark', #000, #fff) !default;
```

As you can see, the minimal contrast is hardcoded. Depending on the contrast the tone is set to `light` or `dark` and depending on the tone the text color is set to white or black.

**Comment by jnain** [comment] 2023-04-04 08:47
Same issue here. Hope it'll get fixed soon! :)

Thank you @Frankitch for the workaround!

**Comment by ProjectBay** [comment] 2023-05-06 14:45
Same with checkboxes

**Comment by AlvaroP95** [comment] 2023-05-10 13:40
Angular 16 is already live, and this is not fixed. Any news on this?

**Comment by aponski** [comment] 2023-05-12 10:01
I have the same problem with buttons and checkboxes. Contrast color of my custom theme is not applied correctly.

**Comment by Leccho** [comment] 2023-06-01 00:30
Most of the Angular Material Components don't work properly for the color. I don't know how this as not been fix already. Should have been fix first week after the release of v15, yet here we are at v16 and the problem persist.

**Comment by marc-wilson** [comment] 2023-07-19 20:18
Same thing in 16.1.5 with chips

**Comment by DeanPDX** [comment] 2023-07-23 18:15
> Same thing in 16.1.5 with chips

Yeah - it doesn't appear to be getting fixed (I think they might view it as a feature rather than a bug; because it DOES enforce a certain level of contrast, which helps with accessibility). I just targeted the elements I cared about with CSS in my global styles and moved on.

**Comment by sebastianhaberey** [comment] 2023-07-25 20:21
Same issue. Just posting here as a vote to fix this.

**Comment by Davidihl** [comment] 2023-08-03 12:04
I set up a fresh angular in the newest version in combination with material.
While trying to setup a custom theme, I noticed that the issue still persists :(

**Comment by danieljohnson107** [comment] 2023-08-25 23:08
I'm having the same issue using `angular 16.1.0` and `angular material 16.2.1`. This only an issue when defining your own palette, the contrast colors work correctly if you use one of the predefined palettes from angular material.

**Comment by AlirezaEbrahimkhani** [comment] 2023-08-26 10:07
Same issue using `angular material 16.2.1` and `angular 16.0.4`

**Comment by sanurah** [comment] 2023-09-17 12:20
Same issue. Can someone tell us if this is not considered as a bug?

**Comment by WasiakSzymon** [comment] 2023-09-28 15:39
Same issue here using `angular material 16.2.5`

**Comment by sergidt** [comment] 2023-09-28 18:44
It looks like they are not supporting it. I am thinking to change the UI kit.

**Comment by Bernoulli-IT** [comment] 2023-10-02 11:12
Sadly 😢 mat-flat-button as well as mat-raised-button still have this, fairly easy to fix imho, issue. Please get back to us with an explanation and/or fix. Greatly appreciated 👍🏼

**Comment by josegomez** [comment] 2023-10-04 01:06
Is there any update on this? Having the same issue. Anyone have a work-around that doesn't require me to hard code css?

**Comment by mKoranae** [comment] 2023-10-05 06:09
Would love to know as well. I've been looking for workarounds for days and none really seem to work for all components that the primary color doesn't get used at anymore. Super frustrating :(... Angular 17 will get released soon, I'd hate not to be able to use that version either.

**Comment by PhilippeMorier** [comment] 2023-10-05 13:10
Same issue. Similar to https://github.com/angular/components/issues/26056#issuecomment-1412183516 but I am reading the contrast value from the specific palette of the theme.

```scss
@mixin theme($theme) {
  button,
  a {
    @include -colors($theme);
  }
}
```

```scss
@mixin -colors($theme) {
  $color-config: mat.get-color-config($theme);
  $primary-palette: map.get($color-config, primary);
  $accent-palette: map.get($color-config, accent);
  $nominal-palette: map.get($color-config, nominal);
  
  $colors: (
    primary: $primary-palette,
    accent: $accent-palette,
    nominal: $nominal-palette
  );
  
  &[mat-flat-button],
  &[mat-raised-button],
  &[mat-fab],
  &[mat-mini-fab] {
    @each $color, $palette in $colors {
      &.mat-#{$color} {
        // https://github.com/angular/components/issues/26056
        --mdc-protected-button-label-text-color: #{mat.get-color-from-palette($palette, '500-contrast')};
        --mdc-filled-button-label-text-color: #{mat.get-color-from-palette($palette, '500-contrast')};
        --mat-mdc-fab-color: #{mat.get-color-from-palette($palette, '500-contrast')};
      }
    }
  }
}
```

**Comment by Davidihl** [comment] 2023-10-05 14:17
> Would love to know as well. I've been looking for workarounds for days and none really seem to work for all components that the primary color doesn't get used at anymore. Super frustrating :(... Angular 17 will get released soon, I'd hate not to be able to use that version either.

Only workaround I know of so far is manually fixing it e.g. by overwriting the affected classes in global `styles.scss`. Keep in mind to not only change the text-color, you also need to target the ripple effect color.

```scss
// *** Contrast fix example of custom accent color ***
.mat-mdc-raised-button.mat-accent,
.mat-mdc-unelevated-button.mat-accent,
.mat-mdc-fab.mat-accent,
.mat-mdc-mini-fab.mat-accent {
  color: mat.get-color-from-palette(
    $custom-theme-accent,
    default-contrast
  ) !important;
  --mat-mdc-button-persistent-ripple-color: mat.get-color-from-palette(
    $custom-theme-accent,
    default-contrast
  ) !important;
  --mat-mdc-button-ripple-color: rgba(255, 255, 255, 0.1); //insert custom rgba contrast color
}

.mat-mdc-fab.mat-accent,
.mat-mdc-mini-fab.mat-accent {
  --mdc-fab-icon-color: mat.get-color-from-palette(
    $custom-theme-accent,
    default-contrast
  );
  --mat-mdc-fab-color: mat.get-color-from-palette(
    $custom-theme-accent,
    default-contrast
  );
}
``` 

So far I found that checkboxes are also affected, but I was able to fix it by overwriting like this:

```scss
* {
  --mdc-checkbox-selected-checkmark-color: #fff !important; //using mat.get-color-from-palette() doesn't work for me so I hardcoded the color
}
```

I hope this helps as it did for me.

Bugged:
![image](https://github.com/angular/components/assets/111972510/03a5671e-b3aa-4e0f-a2bc-3eeb0b301ef6)

Fixed:
![image](https://github.com/angular/components/assets/111972510/a4e7bc60-52d9-4ca2-a374-db192a3d4e3f)

**Comment by Leccho** [comment] 2023-10-06 19:36
@Davidihl Thank you for that! I'd add this for all the buttons color (primary, accent and warn).

**Comment by bitsagarob** [comment] 2023-10-19 12:24
This is a major issue especially when running multiple themes where most of the proposed workarounds don't work and overwrites get even messier.. How come this does work with the preshipped themes on the demo page? 🤔

**Comment by ZahidSaeed7** [comment] 2023-10-20 19:11
Guys, do we have any fix for this?

**Comment by djdam** [comment] 2023-11-20 17:34
argh.. I tried to upgrade but now I'm keeping my project at version 14 for the time being until things look more stable. It's a shame!

**Comment by marc-wilson** [comment] 2023-11-22 13:43
Going from 14 to 15+ is big PITA if you're using Angular Material. I'd suggest starting that adventure sooner rather than later as the "migration" is a very involved process.

**Comment by sergidt** [comment] 2023-11-22 16:19
Seeing they are not solving this and other important bugs, investigating angular material alternatives.

**Comment by Plabbee** [comment] 2023-11-28 10:29
@Davidihl Will have a look at updating later on today - Can see you've raised it in this thread before and I've overlooked it - Will use your fix for reference 👍

**Comment by Davidihl** [comment] 2023-12-04 10:29
I tested @Plabbee npm package in a fresh angular 17 project. easily to implement and works like a charm. I hope the Angular team picks it up

**Comment by sebastianhaberey** [comment] 2023-12-12 15:41
@Plabbee I am using your npm package in our Angular 17 project. It integrates easily and works fine so far. Good work!

**Comment by worthy7** [comment] 2023-12-13 22:59
The issue here is because of using variable/dynamic colors.
The "on-primary" calculation assumes a raw value, and for some reason if a `var` is passed, it calculates the tone to white and therefore always outputs the black text.
I tested this by manually defining my palette with exactly the same color in hue 500 as a string instead and it correctly gave me the white text.

**Comment by nandomegale** [comment] 2024-01-07 14:40
Same here with v17.0.4

The contrast for 600 is white.

![image](https://github.com/angular/components/assets/25829011/65e36999-15c4-42c4-8d62-17fdefe178ce)

But the raised-button applys black

![image](https://github.com/angular/components/assets/25829011/273705ad-ff88-402d-96a2-fa64b06b0b83)

**Comment by rom111419** [comment] 2024-01-28 15:09
The same error. I want assign my theme and don`t want rewriting initial vars, cause it`s bad idea or crutch

**Comment by mrctrifork** [comment] 2024-01-30 14:12
Same here. I've been hitting myself in the head for the past two hours… thank god I found this issue

**Comment by Iancovski** [comment] 2024-01-31 00:54
Same problem in Angular Material 17.1.0. I'm using the package from @Plabbee for workaround, it works perfectly!

**Comment by Blafasel3** [comment] 2024-02-20 11:29
Pls fix this. There is actually a forked repo with a fix. This bug is super painful, because even if you got a workaround, it breaks on every major update eventually and one has to find a new workaround. This is the 3rd time i'm stumbling over this.

**Comment by marcguillemdev** [comment] 2024-02-20 11:42
I'm exactly at this points and the same problem:

> Same here with v17.0.4
> 
> The contrast for 600 is white.
> 
> ![image](https://private-user-images.githubusercontent.com/25829011/294765249-65e36999-15c4-42c4-8d62-17fdefe178ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0Mjk1MTcsIm5iZiI6MTcwODQyOTIxNywicGF0aCI6Ii8yNTgyOTAxMS8yOTQ3NjUyNDktNjVlMzY5OTktMTVjNC00MmM0LThkNjItMTdmZGVmZTE3OGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDExNDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNDBmYWM3YTc2NGNjY2RlZjZkZjQwNWU3ZmQ1N2Q4Mzg1MmU3MWJiZGMyYjEwMGI3OTA1NmI0YmY0YWMyYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yICcW0MlMyoi8v_C041nvLw6Iqn9WL23qBkkNrjoPQw)
> 
> But the raised-button applys black
> 
> ![image](https://private-user-images.githubusercontent.com/25829011/294765320-273705ad-ff88-402d-96a2-fa64b06b0b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0Mjk1MTcsIm5iZiI6MTcwODQyOTIxNywicGF0aCI6Ii8yNTgyOTAxMS8yOTQ3NjUzMjAtMjczNzA1YWQtZmY4OC00MDJkLTk2YTItZmE2NGIwNmIwYjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDExNDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1M2U3NDc1NmFiMmM0MDY2NmI4NDEwOTU4MGQ3MWJmOGFiYjc0YmMxOWQ2OWVjYjMyYmFiZDM1ZDNjMWE0NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iU7V7HUx6ETH0Ulz-tpu9ERSGXwG2_KUCEn7E3Ct2uI)

**Comment by MichalK6677** [comment] 2024-02-20 12:14
This is a real show stopper for version 17. This version should be considered as beta. I am not able to update without destroyed branding and I have to stay on v16 with legacy components.

**Comment by marc-wilson** [comment] 2024-02-20 17:49
The legacy component issue was 14 -> 15 I believe. I will agree that is a huge PITA. I have seen multiple projects that are basically stuck in the tracks because upgrading is far too much effort. The MDC Component Migrator tool in the CLI isn't helpful at all. Just screws things up even more.

Used to be a huge champion of Angular but with the frequent overhauls and spending more time keeping angular "upt to date" it's starting to not make any sense to stay with Angular.

**Comment by timneil** [comment] 2024-02-26 11:24
Why are the Angular Material team not reponding to this issue?!

**Comment by noel-invonto** [comment] 2024-02-29 14:55
This is really painful. Is there no hope? The fact I need a bazooka  to change the text color of a button after creating a palette is actually insane. The additional tech debt I need to add to my project for a button text color is really frustrating.

**Comment by mvanderlee** [comment] 2024-02-29 14:59
@noel-invonto I was about to say "No there is no hope" as it's been ignored for over a year. And I get an email at least once a week from the various tickets on this. 
BUT I see that crisbeto has started work on this today, so yes.. there is definitely hope!

**Closed** 2024-02-29 22:00 UTC
Labels: P2, area: material/button

**Comment by nandomegale** [comment] 2024-03-01 15:13
when the fix will be avaible?
