### ISSUE TITLE
Getting HierarchyRequestError when opening google map in full screen view within a dailog.

### ISSUE THREAD

**Issue by tanviriitju** [angular/components#29818] opened 2024-10-03 10:39 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am using @angular/google-maps package in my angular app within a dialog(see the image below). However, when I pressed the fullscreen button of the map to show in full screen view, the map is viewed properly but we are getting a console error:

```typescript
ERROR HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at FullscreenOverlayContainer._adjustParentForFullscreenChange (overlay.mjs:3071:16)
    at HTMLDocument.<anonymous> (overlay.mjs:3063:54)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26261:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1704:33)
    at HTMLDocument.globalZoneAwareCallback
``` 

### Reproduction

Opening a dialog from a component and showing google map in the dialog. Then when I press the full screen button to show the map in full screen view the getting this console error though the map is showed perfectly.

### Expected Behavior

Console error should not be generated.

### Actual Behavior
```typescript
ERROR HierarchyRequestError: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at FullscreenOverlayContainer._adjustParentForFullscreenChange (overlay.mjs:3071:16)
    at HTMLDocument.<anonymous> (overlay.mjs:3063:54)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26261:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1704:33)
    at HTMLDocument.globalZoneAwareCallback
``` 

### Environment

![Image](https://github.com/user-attachments/assets/33fcc312-57b3-4a65-856b-6a3592a296b2)

**Comment by crisbeto** [comment] 2024-10-04 07:15
Closing since you're using a really old version of Angular. I also tried reproducing it in our local dev app and I wasn't able to.

**Closed by crisbeto** 2024-10-04 07:15 UTC
Labels: needs triage
