### ISSUE TITLE
bug(cdk stepper test): Test error by using cdk stepper

### ISSUE THREAD

**Issue by IamRenZHOU** [angular/components#20872] opened 2020-10-23 17:37 UTC
#### Reproduction

Steps to reproduce:
1. get code source from here: https://github.com/mainawycliffe/ng-cdk-stepper-example
2. npm install
3. npm run test
 
 
#### Expected Behavior

No error by running test

#### Actual Behavior

`
MyStepperComponent > should create
TypeError: Cannot read property 'content' of undefined
    at <Jasmine>
    at MyStepperComponent_Template (ng:///MyStepperComponent.js:72:58)
    at executeTemplate (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:12169:1)
    at refreshView (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:12008:1)
    at refreshComponent (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13458:1)
    at refreshChildComponents (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11729:1)
    at refreshView (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:12064:1)
    at renderComponentOrTemplate (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:12142:1)
    at tickRootContext (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13665:1)
    at detectChangesInRootView (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13699:1)
    at RootViewRef.detectChanges (http://localhost:9877/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15408:1)
`

#### Environment

- Angular: 9.1.6
- CDK/Material: 9.2.3
- Browser(s): Chrome 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows WSL 2 - Ubuntu

**Comment by crisbeto** [comment] 2020-10-29 18:49
I tried following the reproduction instructions, but they failed with this error which seems unrelated:

```
ERROR in src/app/app.component.spec.ts:22:16 - error TS2339: Property 'title' does not exist on type 'AppComponent'.

22     expect(app.title).toEqual('ng-cdk-stepper-forms-example');
```

**Comment by crisbeto** [comment] 2021-05-06 19:56
Closing the issue, because there hasn't been any new information in a long time.

**Closed by crisbeto** 2021-05-06 19:56 UTC
Labels: area: cdk/stepper, cannot reproduce, needs clarification
