### ISSUE TITLE
bug(table): Transparent gap between the 2 first sticky columns

### ISSUE THREAD

**Issue by JessyParis** [angular/components#18636] opened 2020-02-27 09:41 UTC
#### Expected Behavior

There should be no gap between the firsts sticky columns

#### Actual Behavior

There is a transparent gap between the 2 firtsts sticky columns where we can see the other columns data when scrolling horizontaly

#### Environment

- Angular: 9.0.2
- CDK/Material: 9.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10
![P0UMQybd8m](https://user-images.githubusercontent.com/44050341/75431506-384ac700-594d-11ea-8904-79e353f7680f.gif)

**Comment by j1myx** [comment] 2020-04-16 06:20
I have the same problem, but it happens to me when I work only with a ** "sticky" ** column and adding padding to the parent tag of the table. 
Duplicate of #

**Comment by JessyParis** [comment] 2020-04-21 14:59
Thank you for your comment.
In my case:
- I don't have any padding neither on the table, nor its parent, or the cells.
- It happens only I there are more than one sticky columns at the beginning

**Comment by JessyParis** [comment] 2020-04-28 07:54
Additional information:
The issue is only on first data load. If I re-load data (by sorting, or going to next page), then everything is ok.

**Comment by JessyParis** [comment] 2020-04-28 07:54
There is the same issue with multiple sticky columns at the end of the table.

**Comment by andrewseguin** [comment] 2020-05-26 18:23
Please provide a reproduction in StackBlitz so that we can help you diagnose the issue

**Comment by wagnermaciel** [comment] 2020-08-13 22:38
Closing because no clarification was provided.

**Closed by wagnermaciel** 2020-08-13 22:38 UTC
Labels: area: cdk/table, needs clarification

**Comment by JoshuaKemmerer** [comment] 2020-08-31 17:23
@JessyParis Hey, were you able to figure out this issue with the first two sticky columns? The bug has been closed but I do not see any resolution.

**Comment by JessyParis** [comment] 2020-08-31 18:03
Unfortunatly, no.
And I have no time to make a StackBlitz for now.
The bug remains with Material v10
