### ISSUE TITLE
bug(CdkDragDrop): preview position is incorrect when inside of a popover using translate

### ISSUE THREAD

**Issue by JeffMosaic** [angular/components#28889] opened 2024-04-16 16:43 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Currently if you are using cdk drag with a preview attached to its parent, and the parent is inside of a popover type element that uses absolute positioning and translate transformation then the preview artifact appears in the wrong location.

This appears to be happening because the fixed position is unable to break out of its container due to a parent element having a transform property attached. [Based on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed_positioning) this appears to be the expected behavior.

Switching to use the global cdkDragPreviewContainer position works around this issue but then breaks styling because the preview element is removed from the DOM structure controlling style.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/stackblitz-starters-1zhux8?file=src%2Fmain.ts
Steps to reproduce:
1. Click on one of the items
2. Start dragging

### Expected Behavior

Preview element should be at the same position as the mouse pointer

### Actual Behavior

Preview element is several pixels to the right and bottom on the cursor.

### Environment

- Angular: ^17.2.0
- CDK/Material: ^17.3.4
- Browser(s): Chrome (maybe others)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS (probably others)

**Comment by crisbeto** [comment] 2024-04-16 17:13
I think that this is a duplicate of https://github.com/angular/components/issues/28864. I have it my TODO to add a note for `transform` being problematic.

**Comment by JeffMosaic** [comment] 2024-04-16 20:23
@crisbeto It does look like this is a duplicate of that issue. I agree that browser vendors have not given cdk a good way to solve this problem. Unfortunately to apply the workaround of attaching to body would result in breaking the cascade and requires the consumer of this API to do its own set of hacks to apply what would otherwise be inherited styles.

**Comment by crisbeto** [comment] 2024-04-17 09:53
Would it be an option to put a container for the inside the list and then have the preview be projected into it? Something like

```
<div cdkDropList>
  <div style="position: fixed; top: 0; bottom: 0; left: 0; right: 0;" #previewContainer></div>
  <div cdkDrag [cdkDragPreviewContainer]="previewContainer"></div>
</div>
```

**Comment by crisbeto** [comment] 2024-04-18 12:25
The example is more or less what I was imagining. I was also thinking if it wouldn't be possible to put the transform on something else that's not a parent of the preview container, but I realize that it might be tricky. 

And yeah, it's unfortunate that this is the way they implemented the stacking context for fixed elements... I think the only viable workaround would be to create a native popover element dynamically (e.g. `<dialog>`), project the preview into it and then destroy that element.

**Comment by crisbeto** [comment] 2024-04-18 12:35
I'll reopen this so we can try to use native popovers for the preview element.

**Closed** 2024-04-24 16:11 UTC
Labels: P3, area: cdk/drag-drop
