### ISSUE TITLE
new component suggestion: date range picker

### ISSUE THREAD

**Issue by luguiant** [angular/components#18029] opened 2019-12-23 16:40 UTC
Personally, I see that there is a need for a component of dates, which allows to select ranges of dates, I saw myself in this need some time ago, finding the following project;

https://fetrarij.github.io/ngx-daterangepicker-material

As the material already has a lot of inputs, it is in my opinion it would be easier for them to create this new component, which would facilitate some developments, without having to rely on external projects to material

**Comment by crisbeto** [comment] 2019-12-23 21:24
Duplicate of https://github.com/angular/components/issues/4763.

**Closed by crisbeto** 2019-12-23 21:24 UTC
Labels: feature
