### ISSUE TITLE
It would be nice if mat-datepicker support time selection as well. 

### ISSUE THREAD

**Issue by ofirrifo** [angular/components#19818] opened 2020-07-01 10:59 UTC
#### Feature Description
It would be nice if the new mat-datepicker can support time selection + time zone  in addition to the date selection.
Current when the mat-datepicker popup is just let me chose the date.

Example can be found in this package >> https://www.npmjs.com/package/@angular-material-components/datetime-picker

but I want to use the original angular material date picker.

in addition it would be nice to add slot to add my template 
```
 <mat-datepicker #picker>
    <my-time-picker></my-time-picker>
  </mat-datepicker>
```

#### Use Case
When user need to select date and time + time zone is much more easy to user to select the date and time in one place

**Comment by crisbeto** [comment] 2020-07-01 14:30
Duplicate of https://github.com/angular/components/issues/5648.

**Closed by crisbeto** 2020-07-01 14:30 UTC
Labels: feature, needs triage
