### ISSUE TITLE
MatProgressBar flickering in Chrome

### ISSUE THREAD

**Issue by joshcomley** [angular/components#18008] opened 2019-12-19 11:57 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
1. Open this demo in Chrome: https://stackblitz.com/edit/angular-jptrft?file=src/app/progress-bar-determinate-example.ts
2. Watch
 
 
#### Expected Behavior

The progress bar should smoothly increase.

#### Actual Behavior

The progress bar jumps back and forward.

![ezgif-7-e8a9d95b0da7](https://user-images.githubusercontent.com/820534/71171772-83ae6e00-2256-11ea-9aff-0c6ee2fa4d55.gif)

It looks related to the combination of the speed of the increments and the animations on the bar. If you slow down the progress the problem goes away.

#### Environment

- Angular: 8.2.9
- CDK/Material: 8.2.2
- Browser(s): Chrome 79.0.3945.88
- Operating System: Windows 10

**Comment by josephperrott** [comment] 2020-05-27 18:25
Closing as duplicate of #15138

**Closed by josephperrott** 2020-05-27 18:25 UTC
