### ISSUE TITLE
Material Angular v10 Datepicker not working with min and max

### ISSUE THREAD

**Issue by alaksandarjesus** [angular/components#20550] opened 2020-09-12 06:11 UTC
I have a working datepicker working on v 9.x. The project was upgraded to v10 and now in the datepicker the dates are non-selectable

[https://stackblitz.com/edit/angular-ivy-ghliws](stackblitz link)

If i remove the

`[min]="min.startDate" [max]="min.endDate"`

i was able to select dates.

I did cross verify with their api documentation and no change i could notify on their api.

https://material.angular.io/components/datepicker/api

Please let me know what am i missing out on the update.

**Comment by crisbeto** [comment] 2020-09-13 10:50
Duplicate of https://github.com/angular/components/issues/19907 which has a fix that should come out in the next patch release.

**Closed by crisbeto** 2020-09-13 10:50 UTC
Labels: needs triage
