### ISSUE TITLE
bug(drag-drop): withScrollableParents gets overridden and breaks scrolling

### ISSUE THREAD

**Issue by jecraig** [angular/components#19274] opened 2020-05-07 07:38 UTC
#### Reproduction

When setting withScrollableParents manually it gets overwritten on the first drag action. The code responsible is https://github.com/angular/components/commit/3e984c77fb709e22bcd01ba7c6adb58e6ec78835
It looks for any cdkScrollable parents and blows away anything that was there. If you set withScrollableParents again after the first scroll, it won't get blown away again due to _scrollableParentsResolved being set true.

I need to use withScrollableParents because I'm using a third party library that allows me to have nicer scrollbars. I cannot set cdkScrollable to the third party scroll body.

I've provided an example project of the issue, interestingly though, I cannot reproduce this issue using stackblitz because the package version that is used does not contain the error. Here's the proof of that
![image](https://user-images.githubusercontent.com/20190406/81267423-b25d9300-9003-11ea-95f7-61b2ebe3ec0d.png)

Regardless, downloading the source and running it will repro the issue
https://stackblitz.com/edit/drag-drop-scroll-v4tty8

Steps to reproduce:
1. Set a scroll parent higher up the dom than the cdkDropList using withScrollableParents but don't use cdkScrollable
2. Try to drag an item to the edge, notice it doesn't scroll
 
 
#### Expected Behavior

I would expect that if I set withScrollableParents, it wouldn't be overwritten.

#### Actual Behavior

withScrollableParents gets called again by the drag-drop library and I have no way to intercept or prevent this.

#### Environment

- Angular: 9.1.3
- CDK/Material: 9.2.2
- Browser(s): Chromium
- Operating System (Windows):

**Comment by crisbeto** [comment] 2020-05-07 08:13
It looks like you're calling `withScrollableParents` through the `_dropListRef` which is a private API. In general anything that's prefixed with an underscore is meant to be private to the library, even if it may be marked as public in TS.

You could work around it by calling `withScrollableParents` in a subscription to `beforeStarted`, but that's still technically an implementation detail and we can't guarantee that it won't change in the future.

Another approach could be to register your element through the `ScrollDispatcher`, but that may be cumbersome to maintain, because you'd have to implement the same interface as `CdkScrollable`.

**Comment by jecraig** [comment] 2020-05-07 08:19
I noticed that it was an underscore property, but I have seen it recommended a few times in the issues comments. Problem is, if I'm not allowed to call that, then there's no legitimate way for me to use the drag-drop with unless I also control the scroll container. I understand that usually you would, but it would leave out the functionality to apps that use scrollbar styling libraries.

**Comment by crisbeto** [comment] 2020-05-07 08:22
`withScrollableParents` is a public API of the `DropListRef`, but the problem is that `CdkDropList._dropListRef` is private. You can also build your own wrapper around the `DropListRef` and have full control over all the inputs (that's basically what the CDK directive does), but it may involve duplicating some of the logic.

**Comment by jecraig** [comment] 2020-05-07 20:08
What if we made an interface for CdkScrollable and use it in ScrollDispatcher. That would allow me to make my own ScrollableLike object and register it to the ScrollDispatcher. Then the DropList will be able to just attach to it like it was a regular CdkScrollable.

**Comment by crisbeto** [comment] 2020-05-08 07:13
You can do that already. Passing in something that matches this should work:

```
register({
  getElementRef: () => new ElementRef(element),
  elementScrolled: () => fromEvent(element, 'scroll')
} as CdkScrollable);
```

**Comment by crisbeto** [comment] 2020-05-29 19:16
Closing since the issue is using a private API and there are a couple of suggested workarounds.

**Closed by crisbeto** 2020-05-29 19:16 UTC
Labels: area: cdk/drag-drop
