### ISSUE TITLE
fr([Date-range picker]): [Calendar System]

### ISSUE THREAD

**Issue by azerafati** [angular/components#19137] opened 2020-04-22 06:38 UTC
#### Feature Description

Having an abstract layer of Calendar system in Date-range picker which does enable a possible support for [Jalali](https://en.wikipedia.org/wiki/Jalali_calendar) ,[Hijri](https://en.wikipedia.org/wiki/Islamic_calendar) and other calendar systems.

#### Use Case

I see the team is working on a Date-range picker. I'm not aware of the current design but I always see this feature missing in other libraries, It would be great that the component implement a `CalendarSystem Class` that provides calendar-related calculations. This way there would be a possibility in future to extend that class and make the Date picker component provide support for other calendar systems, and not just hard-code Gregorian.

I see a similar design currently being implemented in [NgbDatepicker](https://ng-bootstrap.github.io/#/components/datepicker/calendars).

**Comment by jelbourn** [comment] 2020-05-29 01:53
Duplicate of #2519

**Closed by jelbourn** 2020-05-29 01:53 UTC
Labels: feature, needs triage
