### ISSUE TITLE
feat(all): Material 3 / Material You

### ISSUE THREAD

**Issue by hartmair** [angular/components#26630] opened 2023-02-16 08:36 UTC
### Feature Description

Add [Material 3](https://m3.material.io/) support as [Material 2](https://m2.material.io/) is considered legacy. The [Material Web](https://github.com/material-components/material-web) team is doing the same right now.

**Comment by crisbeto** [comment] 2023-02-18 06:34
Duplicate of https://github.com/angular/components/issues/22738.

**Closed by crisbeto** 2023-02-18 06:34 UTC
Labels: feature, needs triage
