### ISSUE TITLE
Scrolling inside a section is disabled when a cdk overlay is open

### ISSUE THREAD

**Issue by karlboulos** [angular/components#15447] opened 2019-03-12 13:01 UTC
**Bug, feature request, or proposal?**
Bug, I think.

**What is the current behavior?**
When opening an angular cdk overlay configured to use a backdrop and any scrolling strategy, inside a page that is scrollable from a subsection which is different from the main body section, the scroll is blocked on the entire page (even if the directive cdkScrollable is set on this subsection).
If the page is scrollable from its main body section, the scroll is always active when the overlay is open regardless of its configuration.

**What is the expected behavior?**
When the overlay is open, I expect the scroll to be active on any scrolling section, regardless the config of the overlay (with or without a backdrop and the scrolling strategy)

**What are the steps to reproduce?**
Open a cdk overlay in a page that scrolls from its main body section:
https://stackblitz.com/edit/angular-overlay-scrolling-page
The scroll should work when the overlay is open in this case.

Open a cdk overlay in a page that scrolls from a subsection different from the body section: https://stackblitz.com/edit/angular-overlay-scrolling-section
The scroll should be blocked when the overlay is open in this case.

**Environment**
Angular 7, Chrome

**Comment by josephperrott** [comment] 2019-06-04 18:11
Can you expand a bit on what your expectation is?  Without the backdrop, we cannot detect when a click outside of the overlay occurs to inform when it should close (or at least this is the typical pattern).

There are cases where you don't want this pattern, for example in `MatAutocomplete` which opens an overlay with the options, but does not prevent interactions elsewhere nor scrolling.

**Comment by josephperrott** [comment] 2020-05-27 18:31
Closing out this issue as we were not able to reproduce it and it is outdated at this point.

**Closed by josephperrott** 2020-05-27 18:31 UTC
