### ISSUE TITLE
feat(google-maps): Provide a mechanism to lazy load the Maps API multiple times with different libraries

### ISSUE THREAD

**Issue by MonocleKelso** [angular/components#21797] opened 2021-02-03 20:26 UTC
#### Feature Description

It would be nice to be able to lazy load the Maps API in different modules with different libraries.

#### Use Case

Currently we wrap `GoogleMapsModule` in our own feature module so that it can be configured with an API key and optional list of libraries. We store when the map is available via an injection token so google-map components don't try to render before the API is ready -
```ts
export const MAP_API_KEY = new InjectionToken<string>('Google Maps API Key');
export const MAP_API_LOADED = new InjectionToken<Observable<boolean>>('Google Maps API Loaded');
export const MAP_CONFIGURATION = new InjectionToken<IMapConfiguration>('Map Feature Configuration');

function loadMapApi(httpClient: HttpClient, apiKey: string, config: IMapConfiguration) {
  let url = `https://maps.googleapis.com/maps/api/js?key=${apiKey}`;
  if (config?.libraries) {
    const libParams = config.libraries.join(',');
    url = `${url}&libraries=${libParams}`;
  }

  return httpClient.jsonp(url, 'callback').pipe(
    shareReplay({bufferSize: 1, refCount: true}),
    map(() => true),
    catchError(e => {
      console.log(e);
      return of(false);
    })
  );
}

@NgModule({
  imports: [HttpClientModule, HttpClientJsonpModule],
  exports: [GoogleMapsModule]
})
export class MapFeatureModule {

  static forRoot(apiKey: string, config?: IMapConfiguration): ModuleWithProviders<MapFeatureModule> {
    return {
      ngModule: MapFeatureModule,
      providers: [
        {provide: MAP_API_KEY, useValue: apiKey},
        {provide: MAP_CONFIGURATION, useValue: config},
        {provide: MAP_API_LOADED, useFactory: loadMapApi, deps: [HttpClient, MAP_API_KEY, MAP_CONFIGURATION]}
      ]
    }
  }
}
```
This works great for lazy loading into any given module -
```
// no libraries, just maps
import: [MapFeatureModule.forRoot(key)]
// maps with libraries
import: [MapFeatureModule.forRoot(key, {libraries: ['drawing]})]
```
This is a handy use case for us because only a small portion of our app needs to be able to draw shapes on maps, the rest of it is just for displaying. However, if the user routes to the module with drawing after having already routed to another module with maps the console logs an error that the Maps API has been included multiple times. While the components appear to function correctly this is obviously not desirable. It would be nice to be able to lazy load different API configurations like this even if it meant unloading and re-loading the API.

**Comment by jelbourn** [comment] 2021-02-04 21:48
Duplicate of #21797

I'm going to expand #21797 to cover both Google Maps and YouTube Player, since the same philosophy goes into both. My current stance is that the app should stay responsible for loading the underlying API, since the app should be very deliberate about which dependencies it loads and how.

**Closed by jelbourn** 2021-02-04 21:48 UTC
Labels: feature, needs triage

**Comment by MonocleKelso** [comment] 2021-02-08 22:02
@jelbourn This is #21797, so you closed this issue because you said it was a duplicate of this issue :)
