### ISSUE TITLE
docs-bug(mat-calendar): Document mat-calendar component

### ISSUE THREAD

**Issue by balteo** [angular/components#20031] opened 2020-07-17 17:20 UTC
#### Documentation Feedback

Please document the **mat-calendar** component.

Blog posts have been written about this component (e.g. https://onthecode.co.uk/angular-material-calendar-component/) but the official documentation has nothing about the **mat-calendar**.

Many app designers and developers require for the calendar to be always displayed on the page and don't need to resort to a date picker toggle. Therefore, an official documentation entry would be great.

**Comment by jelbourn** [comment] 2020-07-17 22:11
Duplicate of #15353

**Closed by jelbourn** 2020-07-17 22:11 UTC
Labels: docs, needs triage
