### ISSUE TITLE
bug(@angular/youtube-player): "ready" event isn't fired

### ISSUE THREAD

**Issue by Eraldo** [angular/components#28834] opened 2024-04-06 00:11 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

don't know

### Description

Similar issue from the past: https://github.com/angular/components/issues/20462
https://github.com/angular/components/issues/20462#issuecomment-684730811 claims the problem was solved.
It seems to be there again.

After migrating from the NgModule version to using the `YouTubePlayer` component, I don't get a ready event fired anymore. Meaning I don't have access to the player object anymore. 😢 

I am getting the following error, that might or might not be related.
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://example.com').
```
Similar to: https://github.com/angular/components/issues/22835
I mention this here because similarly it could be that the error prevents the event from being emitted now that the code has been refactored (regression bug).

### Reproduction

StackBlitz link: https://stackblitz.com/edit/angular-youtube-player-responsive-issue?file=src%2Fmain.ts
Steps to reproduce:
1. Open the console.
2. Verify that the console does not show the log message which according to the code would get written when the ready event is dispatched.

### Expected Behavior

The ready event fires when the youtube player (video) loads.

### Actual Behavior

The component event does not fire at all.

### Environment

- Angular: 17.3.3
- Browser(s): Stackblitz

**Comment by crisbeto** [comment] 2024-04-06 11:39
Duplicate of https://github.com/angular/components/issues/28619.

**Closed by crisbeto** 2024-04-06 11:39 UTC
Labels: needs triage

**Comment by Eraldo** [comment] 2024-04-06 13:31
@crisbeto I see. Thanks for pointing me there. 🙏 

My challenge is that I have a play button somewhere else in the ui and clicking it will not work as the YouTubePlayer is not yet loaded and calling `youtubePlayer.playVideo()` throws the following error:
```ERROR ReferenceError: YT is not defined```

Since the `_load` method is private, is there a way to load the video programmatically even when using the placeholder feature?

**Comment by Eraldo** [comment] 2024-04-08 14:37
https://github.com/angular/components/issues/28844

**Comment by crisbeto** [comment] 2024-04-08 14:47
The feature request is valid. I just wanted to mention that you can turn off the placeholder to get back the old behavior.
