### ISSUE TITLE
dialog: tab key from address bar, when dialog open, does not move focus to dialog

### ISSUE THREAD

**Issue by manu-058** [angular/components#18360] opened 2020-01-26 18:42 UTC
**1) Bug, feature request, or proposal:**

Bug

**2) What is the current behavior?**

when the dialog box is opened, click on the address bar, next when "tab" key is pressed , _focus is going inside the application_.

**3) What is the expected behavior?**

when the dialog box in opened, click on the address bar , next when "tab" key is pressed , _focus should enter the dialog box_.

**4)What are the steps to reproduce?**
https://material.angular.io/components/dialog/examples

![oie_oie_animation (2)](https://user-images.githubusercontent.com/38914354/73140191-03bcc480-409c-11ea-9a07-347e6c417c05.gif)

**5) What is the use-case or motivation for changing an existing behavior?**

Motive is for better User experience.

**6) Which versions of Angular, Material, OS, TypeScript, browsers are affected?**

Angular 8
Angular Material 8.2.2
Windows 10 64 bit
TypeScript 3.5.3
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**7) Is there anything else we should know?**

in IE 11 bug is not there ( from address bar focus is shifting to dialog).

**Comment by jelbourn** [comment] 2020-05-28 23:05
Duplicate of #9035

The current strategy traps focus using tab stops that redirect focus back to the other side of the dialog. We would need to provide the heavier approach of disabling everything else on the page in order to accomplish this.

**Closed by jelbourn** 2020-05-28 23:05 UTC
Labels: needs triage
