### ISSUE TITLE
bug(material): unable to use css variable for colors

### ISSUE THREAD

**Issue by volovikoff** [angular/components#26085] opened 2022-11-25 09:06 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

Cannot use css variables,
for v15.0.0
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: var(--cs-mat-theme-primary-500) is not a color.
16 │     track-color: color.adjust(mdc-theme-color.prop-value($color), $alpha: -0.75),

### Reproduction

Steps to reproduce:
1. create theme with variables for colors:
 $my-primary: ( color: (
    primary: (
      50: var(--cs-mat-theme-primary-50),
      100: var(--cs-mat-theme-primary-50,
      200: var(--cs-mat-theme-primary-50,
      300: var(--cs-mat-theme-primary-50,
      // ... continues to 900
      contrast: (
        50: var(--cs-mat-theme-primary-contrast-50),
        100: var(--cs-mat-theme-primary-contrast-100),
        200: var(--cs-mat-theme-primary-contrast-200),
        300: var(--cs-mat-theme-primary-contrast-300),
        // ... continues to 900
        )
    )
  )
)
$my-accent: mat.define-palette(mat.$pink-palette, A200, A100, A400);
$my-theme: mat.define-light-theme((
 color: (
   primary: $my-primary,
   accent: $my-accent,
 ),
 typography: mat.define-typography-config(),
 density: 0,
));
2. build theme
@include mat.all-component-themes($my-theme);
3. build/serve application

3.

### Expected Behavior

Build success

### Actual Behavior

Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: var(--cs-mat-theme-primary-500) is not a color.
   ╷
16 │     track-color: color.adjust(mdc-theme-color.prop-value($color), $alpha: -0.75),
   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 16:18  -palette-styles()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 28:7   @content
  node_modules\@angular\material\core\mdc-helpers\_mdc-helpers.scss 176:5     @content
  node_modules\@angular\material\core\mdc-helpers\_mdc-helpers.scss 216:3     disable-mdc-fallback-declarations()
  node_modules\@angular\material\core\mdc-helpers\_mdc-helpers.scss 175:3     using-mdc-theme()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 26:3   color()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 53:7   @content
  node_modules\@angular\material\core\theming\_theming.scss 402:3             private-check-duplicate-theme-styles()
  node_modules\@angular\material\progress-bar\_progress-bar-theme.scss 47:3   theme()
  node_modules\@angular\material\core\theming\_all-theme.scss 47:5            @content
  node_modules\@angular\material\core\theming\_theming.scss 402:3             private-check-duplicate-theme-styles()
  node_modules\@angular\material\core\theming\_all-theme.scss 44:3            all-component-themes()
  projects\csui\src\lib\material-ui\styles.material.scss 17:1                 @import
  src\styles.scss 2:9                                                         root stylesheet

### Environment

- Angular: 15
- CDK/Material: 15
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 pro

**Comment by crisbeto** [comment] 2022-11-25 09:13
Duplicate of https://github.com/angular/components/issues/25981.

**Closed by crisbeto** 2022-11-25 09:13 UTC
Labels: needs triage
