### ISSUE TITLE
bug(MatDatepicker): When using Moment Adapter, Dates Autocorrect Incorrectly

### ISSUE THREAD

**Issue by JaxonWright** [angular/components#21867] opened 2021-02-10 16:19 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/angular/bqnjldggjqp?file=src%2Fapp%2Fdatepicker-moment-example.ts

Steps to reproduce:
1. Replace the first `/` in the date with a `-`
2. Click out of the input
3. Observe that it now took the first half of the year and made it the day
 
This seems to be related to [issue #21459](https://github.com/angular/components/issues/21459)
 
#### Expected Behavior

It should just replace the `-` with a `/` without changing the numbers

#### Actual Behavior

It now takes the first half of the year and makes it the day

See this StackBlitz of a non-moment Datepicker working correctly:
https://stackblitz.com/angular/gjvgryamrbjd?file=src%2Fapp%2Fdatepicker-value-example.ts

#### Environment

- Angular: 11.2.0
- CDK/Material: 11.2.0
- Browser(s): Chrome 88
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by crisbeto** [comment] 2021-02-15 16:55
Closing since the issue isn't something that we control, it's up to the date adapter's `parse` method. If the parsing doesn't match your requirements, you can implement a custom `DateAdapter`. Docs: https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

**Closed by crisbeto** 2021-02-15 16:55 UTC
Labels: needs triage
