### ISSUE TITLE
bug(dialog): chrome 111.0.* crashes on dialog close. 

### ISSUE THREAD

**Issue by yanivfa** [angular/components#26796] opened 2023-03-15 14:59 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

After closing mat-dialog, chrome crashes with an 11 error status.
The bug is reproducing in chrome version 111.0.*.
We have multiple apps that use mat-dialog, and the issue is reproduced across all of the dialogs in our systems.

I tried to reproduce the issue on different chrome users (all had identical versions), and it was reproduced in about 50% of the users.

### Reproduction

Steps to reproduce:
1. upgrade chrome to 111.0.5563.64
2. add a close button to some dialog with mat-dialog-close directive (or close by the dialogRef manually).
3. click on the close button. 

### Expected Behavior

The dialog should be closed successfully.

### Actual Behavior

Chrome will crash with an 11 error status.

### Environment

- Angular: 14
- CDK/Material: 14.2.7
- Browser(s): chrome 111.0.5563.64.
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by zarend** [comment] 2023-03-15 16:44
Hello @yanivfa ,

hank you for reporting. I am unable to reproduce with the [dialog examples on the v14 documentation site](https://v14.material.angular.io/components/dialog/examples). I was wondering if we could check with you if this issue requires further action. We are not able to take action if we cannot reproduce. Could you please provide a Stackblitz reproduction of the issue or a link to a running app where this can be reproduced?

**Environment**
 - Chrome Version 111.0.5563.64 (Official Build) (x86_64)
 - macOS 13.2.1 (22D68)
 - https://v14.material.angular.io/components/dialog/examples
 
Best,

Zach

**Comment by crisbeto** [comment] 2023-03-16 07:07
I also wasn't able to reproduce it on the docs site with Chrome 111.

**Comment by xumepadismal** [comment] 2023-04-18 15:54
I can't reproduce it myself but 2 of my colleagues complain about this exact error. Both confirmed that issue had gone once they disabled the Grammarly extension for the Chrome browser. The problem is that I installed this extension to my MacBook but still can't reproduce the bug...

@yanivfa do you think in your case it's also related to some Chrome extension(s)? Or have you solved it somehow?

**Comment by codebreach** [comment] 2023-04-20 10:24
We are also getting reports of this from our customers. Anything we can do to help track it or debug it?

**Comment by xumepadismal** [comment] 2023-04-20 13:27
After some investigation I figured out that it's somehow related `position: fixed;` on `<html>` tag which is set by `.cdk-global-scrollblock`. I added this workaround to my project the issue is gone:

```css
html.cdk-global-scrollblock {
  position: static;
  overflow: hidden;
}
```

Please be aware, that probably this workaround will introduce another issues (I'm pretty sure `position: fixed` was there for a good reason)

...but for my particular case, crashing the whole browser tab is more critical thing.

**Comment by xumepadismal** [comment] 2023-04-20 13:30
And you won't be able to reproduce this bug on material.angular.io because this site doesn't use scroll on `<html>` tag

**Comment by crisbeto** [comment] 2023-05-03 17:09
Closing since we can't do much about what the Grammarly extension is doing. You can disable the scroll blocking in the dialog using the `scrollStrategy` config option.

**Closed by crisbeto** 2023-05-03 17:09 UTC
Labels: needs: clarification
