### ISSUE TITLE
Add search to material.angular.io

### ISSUE THREAD

**Issue by tomastrajan** [angular/components#20853] opened 2020-10-22 15:09 UTC
#### Documentation Feedback

It would be amazing if there would be a search field at the top toolbar where I could search for `button` or `card` and it would list links to relevant components (could also provide links directly to their API doc and Example page) so that I can quickly get the info I am interested in.

**Affected documentation page:**  Such a search input could be in the top toolbar and hence available on every page. Again this would be similar to what angular.io is doing already !

Thank you!

**Comment by jelbourn** [comment] 2020-10-22 20:47
FWIW we've discussed this multiple times over the years, but it's a pretty low priority addition since it is ultimately under 40 components and Google Search works pretty well for the content.

**Comment by tomastrajan** [comment] 2020-10-23 09:00
@jelbourn thank you for providing the additional context

**Comment by crisbeto** [comment] 2021-05-24 06:57
Looks like this is a duplicate of https://github.com/angular/components/issues/19821.

**Closed by crisbeto** 2021-05-24 06:57 UTC
Labels: P4, area: material.angular.io, docs, feature
