### ISSUE TITLE
bug(CDK - cdkDragPreview): SVG masks are not shown in the drag preview

### ISSUE THREAD

**Issue by BuZZ-dEE** [angular/components#20720] opened 2020-10-05 14:48 UTC
#### Expected Behavior

I expect to see the applied SVG mask in the drag preview.

#### Actual Behavior

The element drag preview without the applied SVG mask.

#### The problem

It seems that the dragged element with SVG mask definition is set to `display:none;`, also there seems to be a clone without the mask id the in DOM.
For that reason the SVG mask is not found and not applied in the drag preview.

#### Environment

- Angular: v10.1.4
- CDK/Material: v10.2.3
- Browser(s): all
- Operating System (e.g. Windows, macOS, Ubuntu): all

**Comment by wagnermaciel** [comment] 2020-10-05 20:51
Hi @BuZZ-dEE, could you supply us with a stackblitz and some steps to reproduce so we can better understand your issue.

@crisbeto Maybe you can better understand this than me. For now I'm marking as needs clarification

**Comment by crisbeto** [comment] 2020-10-05 21:45
It is a legitimate issue. When we clone the element to create the preview we strip all IDs so that we don't generate duplicates which can break SVG since we hide the original element.

**Closed** 2020-10-16 19:02 UTC
Labels: P3, area: cdk/drag-drop, has pr
