### ISSUE TITLE
bug(Youtube player): Gtm.video event keeps emitting even after component is destroyed

### ISSUE THREAD

**Issue by mattiLeBlanc** [angular/components#27333] opened 2023-06-20 16:21 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am having issues in Angular with the youtube video player and GTM integration.
I know the issue most likely is caused in GTM, but  I have no access to that for support.

What happens is that when I play a video, I am seeing `gtm.video` events. But when I navigate away from the videoplayer page (and the components get destroyed), I am still seeing `gtm.video: progress` events being emitted from the last video.

I have tried loading GTM via an angular plugin, directly as instructed on the GTM website, I have tried adding youtube via this youtube component and manually used and Iframe or create it myself using the YT class.

All these efforts have the same end result; I keep getting `gtm.video` events in my analytic debugger.

I found something on stackoverflow: 
`https://stackoverflow.com/questions/66569432/tag-manager-youtube-progress-trigger-continues-after-iframe-removed-from-dom`
and people seem to confirm the issue.

Pausing the video, wait for 500ms and then do a Route navigation is not really an option in my app.
How do I get this under the attention of the GTM team?
Or can Angular do anything for this issue?

### Reproduction

It is hard for me to create a copy of our app in stackblitz, or create an example where you can navigate away from the youtube player to another client side url.

To reproduce, I use `angular-google-tag-manager` and `@angular/youtube-player` and setup my GTM and use a chrome plugin called Analytics Debugger to see the events pushed to the DataLayer.
Then I start playing a video, and navigate to another client side url in the app and after 1 minute or so, I see another `gtm.video` event appear in the debugger.

### Expected Behavior

When video is destroyed, all GTM related events should stop.

### Actual Behavior

GTM progress events are still being emitted even when the video is no longer playing, buffering or even exists in the Dom.

### Environment

- Angular: 16
- CDK/Material: 16
- Browser(s): Chrome
- Operating System : Macos

**Comment by andrewseguin** [comment] 2023-06-21 11:13
Thanks for reporting this issue. I've closed it for now because it doesn't include enough information to easily reproduce the problem. As per our [contribution guidelines](https://github.com/angular/components/blob/main/CONTRIBUTING.md#-found-an-issue), please provide a link to a REPL reproduction (such as [StackBlitz](https://stackblitz.com/fork/components-issue)), or an explanation of why that is not possible, along with any other information needed to reproduce the issue.

If you could please open a new issue with the requested reproduction information, we will gladly investigate further.

**Closed by andrewseguin** 2023-06-21 11:13 UTC
Labels: needs triage
