### ISSUE TITLE
bug: (Mat-Table) multiple header rows and sticky creates a gap between columns

### ISSUE THREAD

**Issue by Woogielicious** [angular/components#25225] opened 2022-07-05 09:30 UTC
### Description

I created a table with multiple headers, after set some columns to sticky i had a gap between one of my columns, it happens if you use multiple headers and sticky together. Multiple Headers works fine without sticky and also sticky works fine without using multiple headers. 

![image](https://user-images.githubusercontent.com/21121442/177297561-6ab7833f-fa10-4a29-94eb-173ad3b212e8.png)

### Reproduction

Steps to reproduce:
1. Add a multiple Header to a table
2. add sticky to first and second column

Happens in any Version, i tried 14 and also 7.3.1 from table examples

Angular VS: 14
https://stackblitz.com/edit/angular-gvv7uw?file=src%2Fapp%2Ftable-basic-example.html,src%2Fapp%2Ftable-basic-example.ts

Angular VS: 7.3.1
https://stackblitz.com/edit/angular-material-table-multiple-header-rows-icpxfz?file=app%2Ftable-basic-example.html

### Expected Behavior

There should be no gap between the columns

### Actual Behavior

You get a big gap between Columns if you set some columns to sticky.

### Environment

- Angular: 14.0, 7.3.1
- CDK/Material: 14.0, 7.3.1 
- Browser(s): Chrome
- Operating System (e.g. Windows):

**Comment by Woogielicious** [comment] 2022-07-20 00:30
Is there really no solution?!

**Comment by andrewseguin** [comment] 2023-05-07 11:54
Seems to be a duplicate of #25396 - the scheduler is not running correctly

**Closed** 2023-05-07 11:54 UTC
Labels: needs triage
