### ISSUE TITLE
using single-spa and angular8 to develop micro front-end application,the cdk overlay is not working correct

### ISSUE THREAD

**Issue by DavidYangLin** [angular/components#16972] opened 2019-09-04 14:28 UTC
#### Reproduction

when I use single-spa to develop micro front-end application,one page has two applications,both of them used overlay(eg.select,modal),when I triggered a overlay component at one application,another one application's overlay component can't be shown when I  trigger. A div element which class name is "cdk-overlay-container" and wrap my conponent  was created when trigger the overlay component I found,but when I trigger another one overlay component in another application,the component can't be created. Is there any one can help me
many thanks!
 
 
#### Expected Behavior

What behavior were you expecting to see?
all overlay components of  two applications at one page could work properly

#### Actual Behavior

What behavior did you actually see?

one application's overlay components could work correctly,but another one couldn't work correctly

#### Environment

- Angular:angular8
- CDK/Material:@angular/cdk: 8.1.3
- Browser(s):chorme
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jelbourn** [comment] 2019-09-04 20:06
Can you share a reproduction? There's nothing really for the team to look at without one.

**Comment by DavidYangLin** [comment] 2019-09-05 03:41
Sorry,I have made a demo and upload to my github,this is the demo's link https://github.com/DavidYangLin/microfrontends-demo,could you download it and run the bat file,the reproduction step I have writen in README.md,you can see the bug,many thanks.

**Comment by jelbourn** [comment] 2019-09-05 19:00
No plans to work on this at least through 2020.

**Comment by DavidYangLin** [comment] 2019-09-06 13:39
Very thanks for a email reply message,the email said "No plans to work on this at least through 2020",that's okay.But I found a piece of source code of overlay cdk like this:
  protected _createContainer(): void {
    const containerClass = 'cdk-overlay-container';
    const previousContainers = this._document.getElementsByClassName(containerClass);
    // Remove any old containers. This can happen when transitioning from the server to the client.
    for (let i = 0; i < previousContainers.length; i++) {
      previousContainers[i].parentNode!.removeChild(previousContainers[i]);
    }
    const container = this._document.createElement('div');
    container.classList.add(containerClass);
    this._document.body.appendChild(container);
    this._containerElement = container;
  }
The problem could be resolved when I commented the following code in my demo I found:
  //  for (let i = 0; i < previousContainers.length; i++) {
  //   previousContainers[i].parentNode!.removeChild(previousContainers[i]);
  // }
It works,So I wan to kown is there any problem when I comment this code and does it matter?
many thanks for your answer

**Comment by jelbourn** [comment] 2019-09-06 14:04
That comment was meant for another issue; I accidentally made it in the wrong tab.

**Comment by saisandeepEunimart** [comment] 2019-11-22 06:27
I have same issue please help me out @jelbourn

**Comment by Darth-Alex** [comment] 2019-12-05 15:25
I can confirm that issue. Is there a better Workaround out?

**Comment by Megadesty** [comment] 2019-12-05 15:38
I also have the same issue in the same scenario (multiple Angular apps as microfrontends are loaded in one shell site and each microfrontend creates overlays in comboboxes, datepickers, etc.). The problem seems to be that CDK expects exactly one global `div` tag with the class `cdk-overlay-container`, which is somehow bound to the Angular instance. If another Angular instance from another Microfrontend is removing the `div`-tag, the first Angular instance has lost its container and can't open it anymore.

I can confirm that after removing the for-loop in all Angular instances the overlays are functional (each Angular instance has its own div-tag then):
![image](https://user-images.githubusercontent.com/5328560/70249780-2ce86500-177d-11ea-97d1-6627df0b69aa.png)

I'd be happy for any ideas how to resolve this problem properly. For example, can I configure the CDK somehow to not use the global `body` but a shadow root node for such `div`s instead?

**Comment by knightsub7** [comment] 2019-12-06 08:03
I've the same problem. I ship multiple microfrontends bundled with their own copy of Angular.
So each Angular instance creates a new cdk-overlay-container and which will be deleted by the next Angulare instance. So the reference is goes to nothing and no new container is creating.
At the end I can't go back to a microfrontend and change anything that is using overlay.

Perhaps a check is missed wether the referenced element exists or not?

**Comment by cpasslack** [comment] 2020-01-15 19:31
I can confirm the issue. Yikes, no update since december! :( At the day we decided it is a good idea to have multiple angular apps on one page we were doomed :scream:

Any workarounds are welcome, we are running a bit out of time ...

**Comment by Megadesty** [comment] 2020-01-15 20:25
@cpasslack We found a workaround, which also considers the Angular Universal scenario (which was the reason why the `for`-loop [is there](https://github.com/angular/components/blob/d550e4ef97a83534f9b9b0914dc27a3ad46734ec/src/cdk/overlay/overlay-container.ts#L59-L61), see also #11817). We are not sure, is this so mature that it could be a PR candidate @jelbourn?

Create a custom `OverlayContainer` and overwrite the problematic function:
```typescript
import { OverlayContainer } from '@angular/cdk/overlay';

export class MicrofrontendOverlayContainer extends OverlayContainer {
  protected _createContainer(): void {
    const containerClass = 'cdk-overlay-container';
    const previousContainers = this._document.getElementsByClassName(containerClass);

    // If there is already a container (can happen in a Microfrontend scenario with
    // multiple self-contained Angular apps on the same website), reuse that. But
    // clean it up because it could be created while transitioning from server
    // to client (Angular Universal) and may be stale. Remove any additional containers.
    for (let i = 0; i < previousContainers.length; i++) {
      while (i === 0 && previousContainers[i].firstChild) {
        previousContainers[i].removeChild(previousContainers[i].firstChild);
      }

      if (i > 0 && !!previousContainers[i].parentNode) {
        previousContainers[i].parentNode.removeChild(previousContainers[i]);
      }
    }

    if (previousContainers.length > 0) {
      this._containerElement = previousContainers[0] as HTMLElement;
      return;
    }

    const container = this._document.createElement('div');
    container.classList.add(containerClass);
    this._document.body.appendChild(container);
    this._containerElement = container;
  }
}
```
Then in your `.module.ts`:
```typescript
@NgModule({
    providers: [
        { provide: OverlayContainer, useClass: MicrofrontendOverlayContainer }
    ]
})
export class YourModule {}
```

**Comment by jelbourn** [comment] 2020-01-16 00:39
@crisbeto this looks like the same issue as a couple of others- do you remember the main one?

**Comment by cpasslack** [comment] 2020-01-16 10:36
@Megadesty Thanks! I will definitely check this out! I already scratched my head how it could be possible to overwrite the Overlay behavior, but this looks very promising 😃

**Comment by crisbeto** [comment] 2020-01-16 11:06
Here's the original issue: https://github.com/angular/components/issues/16851. Closing as a duplicate.

**Closed by crisbeto** 2020-01-16 11:06 UTC
Labels: needs clarification

**Comment by aecz** [comment] 2020-02-03 19:18
@crisbeto #16851 is not a complete duplicate because it mentions the use case of Angular Universal when this one is with micro-frontends.
Moreover, https://github.com/angular/components/pull/17006 only fixes the Universal case not the other case which I am experiencing also using Angular Elements.

Please reopen this issue or advise if we should create a new one but the title of this issue is pretty clear in my opinion.

**Comment by topperCao** [comment] 2020-02-19 03:16
i have the same issue, please help me @jelbourn
