### ISSUE TITLE
Change Input appearance for mat-paginator

### ISSUE THREAD

**Issue by andreElrico** [angular/components#16910] opened 2019-08-29 09:59 UTC
I use Token:

```
  providers: [
    { provide: MAT_FORM_FIELD_DEFAULT_OPTIONS, useValue: { appearance: 'outline'}}
  ],
```

This will make the input in `mat-paginator` look bad:

[STACKBLITZ](https://stackblitz.com/edit/angular-k972vf?file=app/paginator-overview-example.ts)

The formfield appearance should be configurable in mat-paginator.

1. Via InjectionToken Value and/or
2. Via Input <mat-paginator appearance="standard"></mat-paginator>

```
@Input()
appearance: MatFormFieldAppearance
```
Is there any workaround to this?

**Comment by rafaelss95** [comment] 2019-08-30 01:21
Duplicate of #16266?

**Comment by jelbourn** [comment] 2019-08-30 21:07
Duplicate of #16266

**Closed by jelbourn** 2019-08-30 21:07 UTC
Labels: feature
