### ISSUE TITLE
bug(Datepicker): Date range selection only - dateChange event doesn't emit unless Ivy is enabled

### ISSUE THREAD

**Issue by chrissfa** [angular/components#20305] opened 2020-08-13 20:33 UTC
#### Reproduction

Using Date range selection, if enableIvy is set to false in tsconfig.base.json then (dateChange) event will never fire, whereas the single date pickers will still emit this event.

Steps to reproduce:
1. Set ```"enableIvy": false``` in ```tsconfig.base.json```
2. Setup ```(dateChange)="onDateChange()"``` event on an input within ```<mat-date-range-input>```.
3. Note how this method within in the component is never hit.
4. Set ```"enableIvy": true``` in ```tsconfig.base.json``` and repeat steps above, now dateChange will work.
 
 
#### Expected Behavior

(dateChange) should trigger with Ivy disabled.

#### Actual Behavior

(dateChange) does not trigger with Ivy disabled.

#### Environment

- Angular: 10.0.9
- CDK/Material: 10.1.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by wagnermaciel** [comment] 2020-08-13 21:47
@chrissfa I was not able to reproduce this. Here is the stackblitz where I followed the steps you provided
https://stackblitz.com/edit/angular-hkd2jd-xddknk?file=src%2Fapp%2Fdate-range-picker-overview-example.html

Can you share a reproduction.

**Comment by crisbeto** [comment] 2020-08-14 06:36
The `dateChange` event is on `matStartDate` and `matEndDate`, not on `mat-date-range-input`.

**Comment by chrissfa** [comment] 2020-08-14 08:34
> The `dateChange` event is on `matStartDate` and `matEndDate`, not on `mat-date-range-input`.

Yeah, aware of this, as mentioned in the steps provided, the dateChange was on an input within <mat-date-range-input>.

I spent 10 hours debugging this yesterday, deconstructing my app and comparing to a fresh CLI build to work out what the problem was, enableIvy needs to be false to reproduce this which I'm not sure works within stackblitz.

**Comment by wagnermaciel** [comment] 2020-08-14 16:46
Hey, in the stackblitz I provided you can toggle ivy on or off through the settings (see the gear button on the left panel). Again, I tried to see if I could reproduce the issue and couldn't but please let us know if you are able to.

![Screen Shot 2020-08-14 at 9 41 34 AM](https://user-images.githubusercontent.com/25158423/90272789-bd01a280-de12-11ea-998b-e4ce09445b70.png)

**Comment by harloveleen** [comment] 2020-10-14 12:57
I have the same issue ! been struggling with finding a reason why the event is not getting fired just for mat date range while works the other way round and it looks like it works if Ivy is enabled

**Comment by jelbourn** [comment] 2021-08-05 21:55
Closing this since non-Ivy applications won't be supported much longer.

**Closed by jelbourn** 2021-08-05 21:55 UTC
Labels: cannot reproduce, needs clarification
