### ISSUE TITLE
bug(drag-drop): Not working with web component

### ISSUE THREAD

**Issue by KyDenZ** [angular/components#25023] opened 2022-06-03 17:56 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I created a web component from an Angular component with the function: `createCustomElement`.

This component can receive draggable elements. However the drag and drop doesn't seem to be common between a web component and an angular component

### Reproduction

Steps to reproduce:
Drag an element from the Angular component section to web component section

https://stackblitz.com/edit/angular-drag-and-drop-example-z3dzqg

### Expected Behavior

Drag and drop must work between the web component and the angular components.

### Actual Behavior

Drag and drop does not work between the web component and the angular component.

It is impossible to drop an element from the web component to the element list of the angular component or vice versa

### Environment

- Angular: `13.1.0`
- CDK/Material: `13.1.0`
- elements: `13.1.0`
- Browser(s): `Chrome 102.0.5005.61`
- Operating System: `macOS`

**Comment by crisbeto** [comment] 2022-06-15 12:50
Closing this since we can't do much about it. The problem is that `cdkDropListGroup` works using DI (each list injects its closest group), but the web component is in a different DI tree which doesn't contain the group directive instance.

**Closed by crisbeto** 2022-06-15 12:50 UTC
Labels: needs triage
