### ISSUE TITLE
bug([@angular/cdk/drag-drop]): [`Failed to execute 'removeChild' on 'Node` and `Cannot read property 'clientRect' of undefined`]

### ISSUE THREAD

**Issue by PolinaGurinovich** [angular/components#18913] opened 2020-03-25 15:44 UTC
#### Reproduction
Error: when quickly dragging an item between two `cdkDropList` two errors sometimes occur 
 
#### Expected Behavior
 
What behavior were you expecting to see?
No error should occur.

#### Actual Behavior

What behavior did you actually see?
1.  
```
polyfills-es2015.7334d7c49db06a58f6f3.js:1 Uncaught TypeError: Cannot read property 'clientRect' of undefined
    at Ee._sortItem (12-es2015.57b2cc973d6f19b5358e.js:1)
    at ve._updateActiveDropContainer (12-es2015.57b2cc973d6f19b5358e.js:1)
    at c._pointerMove [as _next] (12-es2015.57b2cc973d6f19b5358e.js:1)
    at c.__tryOrUnsub (main-es2015.83cbb10447d7abc76ea5.js:1)
    at c.next (main-es2015.83cbb10447d7abc76ea5.js:1)
    at u._next (main-es2015.83cbb10447d7abc76ea5.js:1)
    at u.next (main-es2015.83cbb10447d7abc76ea5.js:1)
    at e.next (main-es2015.83cbb10447d7abc76ea5.js:1)
    at HTMLDocument.handler (12-es2015.57b2cc973d6f19b5358e.js:1)
    at a.invokeTask (polyfills-es2015.7334d7c49db06a58f6f3.js:1)
```
2.  
```
main-es2015.83cbb10447d7abc76ea5.js:1 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
#### Environment

- Angular: `8.2.5`
- CDK/Material: `8.2.3`
- Browser(s): `Google Chrome 80.0.3987.132 `
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 10

**Comment by crisbeto** [comment] 2020-03-25 16:27
Can you elaborate what you mean by "quickly dragging an item between two cdkDropList"? I wasn't able to reproduce it against our dev app. Also it might be worth trying to update to the latest version of the CDK.

**Comment by crisbeto** [comment] 2020-07-19 07:33
Closing since there hasn't been any activity in a while.

**Closed by crisbeto** 2020-07-19 07:33 UTC
Labels: area: cdk/drag-drop, needs clarification
