### ISSUE TITLE
bug(mat-radio-button): value of mat-radio-button without radio-button-group is null after selection

### ISSUE THREAD

**Issue by michahell** [angular/components#25883] opened 2022-10-27 15:19 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

when having 3 `mat-radio-buttons` _without_ a `mat-radio-button` group, yet with a given `name` **@Input** so they belong to one group, listening to their change events and observing their `MatRadioChange` objects, their values remain `null` after selection.

### Reproduction

example:
https://stackblitz.com/edit/components-issue-qqftgq?file=src/app/example-component.ts

### Expected Behavior

I expect the event$.value of each radiobutton to be true or false

### Actual Behavior

the event$.value s of each radiobutton are null

### Environment

- Angular:  @latest in example (in my own case, v13.3.9)
- CDK/Material: @latest in example (in my case, v13.3.9)
- Browser(s): chrome latest
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by zarend** [comment] 2022-10-27 16:01
That's because the individual radio buttons don't have a value. I tried the stackblitz and it works when adding a value property to the radio button. If we were using an `<input type="radio"/>`, we would also need to assign a value. For that reason, I'm closing this as working as intended.

```html
 <mat-radio-button
    name="main-activity"
    color="primary"
    (change)="onSelectMainActivity($event, radio)"
    [value]="radio"
  >
    radio button {{radio}}</mat-radio-button
  >
  ```

**Closed by zarend** 2022-10-27 16:01 UTC
Labels: needs triage

**Comment by michahell** [comment] 2022-10-29 16:24
Thanks, I guess I was looking for a `checked` @output, but I see that this is not the way standard radiobuttons work.
What a brainfart, I guess this is what happens if you spend too much time in web-app-framework-land as opposed to good-old-standard-html-land
