### ISSUE TITLE
feat(OverlayModule): Multiple OverlayContainer instances

### ISSUE THREAD

**Issue by mezhik91** [angular/components#19903] opened 2020-07-08 12:32 UTC
#### Feature Description

Now we have only 1 overlay container where all overlays are being created but it would be great to have a possibility to have multiple containers because of:

#### Use Case

Let's say I have an input and on focus I show my custom Overlay panel which has a backdrop. To be able to further type in this input I apply for it z-index which is higher than overlayContainer has. It works fine until we add mat-select inside the custom overlay panel. Then if we open mat-select the mat-select's panel might be overlapped by the input because it will always have z-index higher. So if I had an option to create another overlay container I would be able to place this layers in proper order. As example:
-  Container 1 with custom overlay panel and z-index: 10000
-  Input  with z-index: 10001
-  Container 1 with mat select overlay panel and z-index: 10002

Or maybe I am missing something and there is some way to handle it? Thanks!

I have created example on Stackblinz to demonstrate the issue:
https://stackblitz.com/edit/angular-drdhwt?file=src%2Fapp%2Fcdk-overlay-basic-example.html

**Comment by jelbourn** [comment] 2020-07-09 21:49
Duplicate of #4612

**Closed by jelbourn** 2020-07-09 21:49 UTC
Labels: feature, needs triage
