### ISSUE TITLE
 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'id') TypeError: Cannot read properties of undefined (reading 'id')     at registerNgModuleType (vendor.js:61233)     at vendor.js:61244TLE

### ISSUE THREAD

**Issue by Pertrick** [angular/components#23862] opened 2021-10-30 09:08 UTC
vendor.js:41296 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
    at registerNgModuleType (vendor.js:61233)
    at vendor.js:61244
    at Array.forEach (<anonymous>)
    at registerNgModuleType (vendor.js:61244)
    at new NgModuleFactory$1 (vendor.js:61341)
    at Compiler_compileModuleSync__POST_R3__ (vendor.js:64126)
    at Compiler_compileModuleAsync__POST_R3__ [as compileModuleAsync] (vendor.js:64131)
    at MergeMapSubscriber.project (vendor.js:84366)
    at MergeMapSubscriber._tryNext (vendor.js:130722)
    at MergeMapSubscriber._next (vendor.js:130712)
    at resolvePromise (polyfills.js:3904)
    at resolvePromise (polyfills.js:3856)
    at polyfills.js:3966
    at ZoneDelegate.invokeTask (polyfills.js:3505)
    at Object.onInvokeTask (vendor.js:64524)
    at ZoneDelegate.invokeTask (polyfills.js:3504)
    at Zone.runTask (polyfills.js:3273)
    at drainMicroTaskQueue (polyfills.js:3675)
    at ZoneTask.invokeTask [as invoke] (polyfills.js:3590)
    at invokeTask (polyfills.js:4727)

Node -v v16.3.0
NPM -v

Angular CLI: 10.0.8
Node: 16.3.0
OS: win32 x64

Angular: 10.0.14
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@angular/fire                     6.1.3
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

**Comment by devversion** [comment] 2021-10-30 13:04
hey @Pertrick, are you actually using Angular CDK/Material? your issue does not mention anything about it, and the error seems unrelated, or rather related to tooling/build pipeline.

**Comment by Pertrick** [comment] 2021-10-30 14:17
Thank you for the response  @devversion

This is a link to an exact issue I am currently facing
https://github.com/angular/angular/issues/37661
This should help

**Comment by devversion** [comment] 2021-10-30 18:19
Thanks, although this issue still doesn't provide the necessary information for the current version combination you are mentioning. It's still unclear to what extent / if you use Angular CDK/Material at all.

Also this looks like an framework issue instead / an issue where ngcc did not run properly so the Angular definitions are missing. I'm closing this, but feel free to resubmit with more details. For these type of issues, an reproduction would also be helpful. The current information is not sufficient at all.

**Closed by devversion** 2021-10-30 18:19 UTC
Labels: needs clarification, troubleshooting
