### ISSUE TITLE
Angular Material DatePicker: Allow option to show two months in the date picker

### ISSUE THREAD

**Issue by tkbaca** [angular/components#27441] opened 2023-07-12 20:21 UTC
### Feature Description

This feature was requested 5 years ago so I figured it would be worth asking if circumstances have changed to be able to have the option to show two months in the date picker as requested earlier in this issue [Git Hub Issue 14586](https://github.com/angular/components/issues/14586).

![image](https://github.com/angular/components/assets/113653924/440ce3c4-2ad6-4a76-8664-c25115da8ccb)

I think the original requestor has provided a pretty decent description of the feature.

A couple of suggestions would be

a) It would be available both in single date picker and date range picker.
b) It would be an opt-in setting, which by default would be off so it's backward compatible.
 ` <mat-datepicker [multimonth]="true #picker></mat-datepicker>`
   
and

`<mat-date-range-picker [multimonth]="true #picker #picker></mat-date-range-picker>`

But if feedback is needed I'd be happy to provide more details.

### Use Case

Most users now prefer a two month date picker which there are other options to choose from, but we've invested into the material components so it'd be nice if this was available natively.

**Comment by zarend** [comment] 2023-07-13 04:01
Duplicate of #18966

**Closed by zarend** 2023-07-13 04:01 UTC
Labels: feature, needs triage

**Comment by zarend** [comment] 2023-07-13 04:04
This feature request is a duplicate of #18966. The two feature requests are similar in terms of what they are asking for. Please refer to the duplicate feature request for more information.
