### ISSUE TITLE
[mat-menu] programmatic openMenu should not focus first menu option

### ISSUE THREAD

**Issue by FritzHerbers** [angular/components#16275] opened 2019-06-12 15:11 UTC
#### Reproduction

https://stackblitz.com/edit/angular-cxsudr?file=app/nested-menu-example.html

Steps to reproduce:
1. Click "Open Menu"
2. First menu option gets focused (wrong)
3. Hovering over the other menu options does not release the first focused menu option
4. After hovering within a sub menu the first menu option's focus is removed
 
 
#### Expected Behavior

When using the programmatic openMenu(), no menu option should get focused.

#### Actual Behavior

First menu option gets focused (and is also not removed during hovering of other menu options).

#### Environment

- Angular: 8.1.0
- CDK/Material: 8.0.2
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by AliKalkandelen** [comment] 2019-10-09 13:29
+1

**Comment by markbirenbaum** [comment] 2020-04-16 19:27
This is a defacto duplicate of https://github.com/angular/components/issues/15936

which requests the ability to specify the behaviour.

**Comment by Totati** [comment] 2020-04-17 09:25
What's the use case for this behaviour? The focus needs to be moved inside the menu, otherwise people using screen readers won't get notified, and can't navigate with keyboard inside the menu.

**Comment by jelbourn** [comment] 2020-05-27 23:03
Duplicate of #15936

**Closed by jelbourn** 2020-05-27 23:03 UTC
Labels: needs triage

**Comment by FritzHerbers** [comment] 2020-05-28 05:26
@jelbourn 
I accept your explanation in https://github.com/angular/components/issues/15936#issuecomment-634989803 that the first item has to be selected.

There is another issue, which is explained in:

3. Hovering over the other menu options does not release the first focused menu option
4. After hovering within a sub menu the first menu option's focus is removed

First menu option gets focused (**and is also not removed during hovering of other menu options**).

**Comment by jelbourn** [comment] 2020-05-28 14:24
In general, hoving doesn't change browser focus. IMO this is working as intended.
