### ISSUE TITLE
mat-form-field have vertical align issue on FF and Chrome using Prefix & suffix on appearance="outline"

### ISSUE THREAD

**Issue by darxx** [angular/components#22280] opened 2021-03-18 12:58 UTC
Originally taken from:
https://material.angular.io/components/form-field/overview

More information in stackblitz example.

[Example](https://stackblitz.com/edit/angular-3uwa6d?file=src/app/form-field-prefix-suffix-example.html)

**Comment by Splaktar** [comment] 2021-03-18 19:59
Duplicate of https://github.com/angular/components/issues/20074.

**Closed by Splaktar** 2021-03-18 19:59 UTC
