### ISSUE TITLE
bug(Table): Sticky column loses the bottom border

### ISSUE THREAD

**Issue by OGLara** [angular/components#21839] opened 2021-02-08 16:20 UTC
#### Reproduction

- Components: https://material.angular.io/components/table/examples

Steps to reproduce:
1. Go to the material examples website and go to the example Table with sticky columns
 

 
#### Expected Behavior

What behavior were you expecting to see?
Display the bottom border in the sticky column in Chrome as it does in Firefox.
![imagen](https://user-images.githubusercontent.com/32096599/107247871-07668380-6a32-11eb-9344-5ef3fbfb9490.png)

#### Actual Behavior

What behavior did you actually see?
The bottom borders disappear
![imagen](https://user-images.githubusercontent.com/32096599/107247170-4a742700-6a31-11eb-87b9-e662e6165b25.png)

#### Environment

- Angular: 11
- CDK/Material: 11.1.1
- Browser(s): Chrome 88.0.4324.150 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment] 2021-02-08 17:07
Did you have to do anything in order for the border to disappear? It seems to be working for me on Chrome 88.

![Table__Angular_Material_-_Google_Chrome_2021-02-08_18-06-54](https://user-images.githubusercontent.com/4450522/107255364-819a0680-6a38-11eb-8ab1-73e5c7050c10.png)

**Comment by OGLara** [comment] 2021-02-08 17:51
No, it's the default. I have tried Microsoft Edge 88 and the same thing happens to me.

![errorborder](https://user-images.githubusercontent.com/32096599/107259896-dab86900-6a3d-11eb-96cb-b4072be113ff.gif)


If I change the color of the border, you can see that it is thinner.

![imagen](https://user-images.githubusercontent.com/32096599/107260214-32ef6b00-6a3e-11eb-9b7e-ef55095976b5.png)

**Comment by crisbeto** [comment] 2021-02-08 18:20
I couldn't reproduce it on a different machine either. My suspicion is that this could be some weird artifact due to a particular OS/driver/browser combination.

**Comment by OGLara** [comment] 2021-02-09 07:54
Yesterday I was testing on another computer, it has a resolution of 1080p, and it looks fine. I think the problem comes from the combination of screen resolution and browser.

The screen that gives me problems has a resolution of 3840x2160 and a text increase of 150% (This is what Windows recommends).

**Comment by crisbeto** [comment] 2021-02-09 16:21
That makes sense, we've had similar reports about other components. The problem is that when the border is that thin, the browser has to approximate it when accounting for zoom. At some point it may approximate it closer to 0px than to 1px. I'm not sure whether we can do much about it without making the border thicker.

**Comment by OGLara** [comment] 2021-02-09 16:54
So, it's a bug in the Chrome approximation, or in general Chromium because it also happens in Edge, since it doesn't happen in Firefox.

**Comment by wagnermaciel** [comment] 2022-06-24 16:46
@crisbeto Can we close this issue if this is due to browser behavior & outside of our control?

**Comment by crisbeto** [comment] 2022-06-25 08:01
Yes, I don't think that we can do much about it.

**Closed by crisbeto** 2022-06-25 08:01 UTC
Labels: needs triage, area: material/table
