### ISSUE TITLE
fr(virtual scroll): Support for a tree structure

### ISSUE THREAD

**Issue by ArielGueta** [angular/components#19162] opened 2020-04-24 05:44 UTC
#### Feature Description

Currently, as far as I know, we can't use `cdkVirtualFor` with a tree structure. 

#### Use Case

A common case is where we have a grouped list. For example:

```ts
this.items = [{
  groupName: '',
  children: [{ label: '' }]
}, {
  groupName: '',
  children: [{ label: '' }]
}]
```

```html
<cdk-virtual-scroll-viewport itemSize="50" class="example-viewport">
  <div *cdkVirtualFor="let item of items" class="example-item">
      <h4>{{ item.groupName }}</h4>
      <div *cdkVirtualFor="let child of item.children" class="example-item">
           {{ child.label }}
       </div>
   </div>
</cdk-virtual-scroll-viewport>
```

**Comment by jelbourn** [comment] 2020-05-27 22:57
Duplicate of #10122

**Closed by jelbourn** 2020-05-27 22:57 UTC
Labels: feature, needs triage
