### ISSUE TITLE
Filter not working in mat table with form array

### ISSUE THREAD

**Issue by neilnikkunilesh** [angular/components#22654] opened 2021-05-10 11:24 UTC
#### Reproduction

**Here is the stack blitz link of my code**
[https://stackblitz.com/edit/angular-custom-pagination-mat-table](url)

For more clarity on my question please refer StackOverflow question:
[https://stackoverflow.com/questions/67466876/filter-is-not-working-in-angular-material-editable-table-using-formarray](StackOverflow ) 
 

 
#### Expected Behavior

What behavior were you expecting to see?
I want the form fields along with the same data I'm showing.

#### Actual Behavior

What behavior did you actually see?
It shows the filtered form fields not the alongside data

**Comment by jelbourn** [comment] 2021-05-13 20:53
@neilnikkunilesh can you distill down what you're trying to do in a smaller reproduction? Your code is pretty complicated and it's not clear what this specific issue is referring to.

**Comment by neilnikkunilesh** [comment] 2021-05-15 12:26
@jelbourn In the demo, I was working on an in-place CRUD operation in the mat-table. But anywhere I didn't found any example for this. So, I create this example as per my understanding of angular.

1. I create the mat-table with dynamic data and the **dataSource** of the type of AbstractControl(FormGroup). 
2. Then I display the data to the user on the table. behind every row, we also have FormGroup so that we can do in-place edit, delete, update operation
3. After implementing the filter on the table, I found that the filter is applied on FormGroup (that is currently hidden until we click on the edit button).
4. So when we filter for "**neon**" on the table it displays the data of index 0, 1 (Image added into StackOverflow question.).

**Actual Behavior I want**
1. On a load of component first it should display the data to the user into mat-table instead of Form that currently I'm showing into example.
2. On the filter of the table it should show data into the table that I have entered instead of the FormGroup.
3. On click of edit button the edited row form should be displayed.

**Current Behavior**
1. Currently in mat-table I'm displaying Forms to the user instead of normal data into span tag line below code
   `<span>
              {{VOForm.get('VORows').value[i].position}}
            </span>`
2. On the Click on the edit button it's only changing the `appearance` of the mat-input tag `none` to `legacy` and vice versa. So that I can show filter data that applied on FormGroup.

Form code and Image of this example pls follow the StackOverflow question [https://stackoverflow.com/questions/67466876/filter-is-not-working-in-angular-material-editable-table-using-formarray](url)

I tried to found any example of in-place editing in angular but didn't get any example. 
Please help me out of this trouble.


Thanks

**Comment by neilnikkunilesh** [comment] 2021-05-17 08:29
Hi, @jelbourn I have modified the Stackblitz example posted by @Snæbjørn on StackOverflow [https://stackoverflow.com/questions/48648800/formarray-inside-angular-material-table](url) 

I have modified this example a little bit to get the required functionality but the problem remains the same filter is not working.
[https://stackblitz.com/edit/angular-material-table-with-form-rrdv2k?file=app/app.component.ts](url)

**Comment by andrewseguin** [comment] 2021-07-22 18:06
It's not clear what you mean when you say

> On a load of component first it should display the data to the user into mat-table instead of Form that currently I'm showing into example.

When I load the example, I see data displayed. Is it not the right data to display?

The provided stackblitz still shows a lot of code that seems not relevant to the issue. Is it possible to make it simpler to make it clear your objective?

**Comment by neilnikkunilesh** [comment] 2021-07-27 06:21
**Functionality Required**
Inline editing in the Angular Material data table.

**Current Behavior**
On Click of pen icon row become editable fields. Filtering is not working properly.

**Expected Behavior**
Filter not working properly over the **datasource** of the  type FormArray(AbstractControl). If you enter the "distinctio" in filter, it will not show row (having id 9).
How to apply filtering over **datasource** of the type FormArray?

**Comment by andrewseguin** [comment] 2023-05-07 11:17
Closing since the issue is not clear - the filtering works and the editing works. I don't see any problems with the interactions between filter and table

**Closed by andrewseguin** 2023-05-07 11:17 UTC
Labels: needs triage, area: cdk/table, area: material/table
