### ISSUE TITLE
bug(TYPOGRAPHY): mat-typography css class only working after mat.typography-hierarchy($theme)

### ISSUE THREAD

**Issue by anschm** [angular/components#26184] opened 2022-12-05 17:26 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.1.3

### Description

The css class .mat-typography on the body html tag does only work if the following line of code was executed at the theming:

$theme: mat.define-light-theme((
  color: (
....
  ),
  typography: mat.define-typography-config()
));

@include mat.all-component-themes($theme);
@include mat.typography-hierarchy($theme);

In angular 14 the typography was generated by default and provided by the css class mat-typography to the content. This is described at the documation for angular material 15 at the same way. But the typography style is not provided to the content. All p HTML-Tags have font family Times. After doing mat.typography-hierarchy($theme) all works. I don't know whether this is new and the documentation should changed or it is a bug.

### Reproduction

1.) Create a angular project with angular material
2.) Create a custom theme
3.) Add mat-typography ass css class to the body tag

### Expected Behavior

All elements have the same font familiy

### Actual Behavior

Different font-families on different elements.

### Environment

- Angular: 15.0.1
- CDK/Material: 15.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MAC M1

**Comment by sergidt** [comment] 2022-12-19 10:27
same issue here!

**Comment by youpage** [comment] 2023-01-05 11:54
good catch @anschm 
I can confirm, it only works as expected after adding:
@include mat.typography-hierarchy($theme);

**Comment by crisbeto** [comment] 2023-05-04 08:46
Duplicate of https://github.com/angular/components/issues/26524.

**Closed by crisbeto** 2023-05-04 08:46 UTC
Labels: needs triage
