### ISSUE TITLE
CDK Overlay Container is not re-created/re-appended when removed from the DOM

### ISSUE THREAD

**Issue by Tanemahuta** [angular/components#18519] opened 2020-02-17 07:10 UTC
#### Reproduction

Steps to reproduce:
1. Use a framework like single-spa which can load one application after another
2. E.g. open menus from two different angular apps
 
 
#### Expected Behavior

The menus open and the overlay container is being used/recreated by each app.

#### Actual Behavior

The cdk overlay container gets set when first opening it for each app.
The last app will always win and have the correct overlay container, while the other app will reach for an element which has removed from the dom

#### Environment

- Angular: 8.2.14
- CDK/Material: 8.2.3
- Browser(s): ALL
- ALL

**Comment by Tanemahuta** [comment] 2020-02-17 10:45
See https://github.com/angular/components/pull/18522

**Comment by Gaurav-enest** [comment] 2020-02-26 06:49
@Tanemahuta I'm getting same kind of issue 
https://github.com/angular/components/issues/18616

**Comment by devversion** [comment] 2020-05-26 10:08
I've tried reproducing this in a StackBlitz, but it looks like this has been fixed? 

https://stackblitz.com/edit/comp-18519?file=src%2Fapp%2Felement%2Felement.module.ts

Closing this for now. Please post here if you still think that this is an issue. Please update the StackBlitz if possible.

**Closed by devversion** 2020-05-26 10:08 UTC
Labels: needs triage
