### ISSUE TITLE
coerceBooleanProperty falsy value handling

### ISSUE THREAD

**Issue by ludwhe** [angular/components#20052] opened 2020-07-21 09:20 UTC
#### Reproduction

Steps to reproduce:

1. Create a component using a `mat-slide-toggle` with `[checked]="0"` (or any non-boolean falsy value ([reference here](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)) for which the `!= null` check shown below does not pass).

https://github.com/angular/components/blob/4a1b24c42eed23647a65776840ef5f6f83de461e/src/cdk/coercion/boolean-property.ts#L17

#### Expected Behavior

What behavior were you expecting to see?

The `mat-slide-toggle` should be unchecked.

#### Actual Behavior

What behavior did you actually see?

The `mat-slide-toggle` is checked.
This leads to awkward code in templates with boolean checks in interpolations not matching the same checks in the `mat-slide-toggle [checked]` input.

#### Environment

- Angular:  `~8.1.1`
- CDK/Material: `~8.1.1`
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Linux Mint

**Comment by devversion** [comment] 2020-07-21 18:05
This is actually similarly to what I tried landing with https://github.com/angular/components/pull/9283. Maybe we should reconsider this. Native controls behave differently than our controls using the `coerceBooleanProperty` function.

**Comment by devversion** [comment] 2020-07-21 18:07
cc. @jelbourn as we chatted about this on the original PR #9283. I do not recall why I have closed it.

**Comment by jelbourn** [comment] 2020-07-21 20:36
IMO this is working as intended and expected. The intent of `coerceBooleanProperty` is to align as closely with the native HTML boolean-attribute behavior with the very limited exception of the string `"false"`. If you have a native text input like `<input disabled="0">` or `<input disabled="">`, the input is still disabled because the mere _presence_ of the attribute turns the boolean flag on. `coerceBooleanProperty` makes a special exception for the `"false"` string because we can safely assume that the user _intended_ to set the value to `false`, and because adding a binding like `<input [disabled]="false">` is overkill.

**Closed by jelbourn** 2020-07-21 20:36 UTC
Labels: P5, area: cdk/coercion, area: many, needs discussion
