### ISSUE TITLE
mat-vertical-stepper is not working as expected in angular

### ISSUE THREAD

**Issue by venkateswarannraja** [angular/components#15935] opened 2019-05-02 08:59 UTC
I am using mat-vertical-stepper with multiple steps. I searched from google. Unfortunately, i am not able to get it.

My requirement is that initially other than first step all steps should be in disabled mode. I can achieve by using linear property. Once when i complete first step i need to open second step as well first step should be in enable mode. Not with disable mode. Similarly it should work for all steps

**Comment by andrewseguin** [comment] 2019-05-07 21:23
Sounds like you are on the right track with the linear mode. If you need more help, feel free to reach out to our community on StackOverflow and ask your questions there. Be sure to provide as much context as possible with a minimal reproduction of what you have. Closing since this is neither an issue or feature request.

**Closed by andrewseguin** 2019-05-07 21:23 UTC
