### ISSUE TITLE
Please Support column resize on table!!! PLEASEEEEEE

### ISSUE THREAD

**Issue by mikila85** [angular/components#21514] opened 2021-01-07 16:40 UTC
#### Feature Description

COLUMN RESIZE

Please Support column resize on table!!! PLEASEEEEEE

#### Use Case

EVERY DAY EVERY ONE ALWAYS ASKING FOR THIS, Please please stop doing experimental and do column resize as part of mat-table <3 <3 <3

**Comment by michaelnem** [comment] 2021-01-07 16:41
Yes we need this!!!s

**Comment by mikila85** [comment] 2021-01-07 16:41
+1

**Comment by mycwacc** [comment] 2021-01-07 16:42
+1

**Comment by jelbourn** [comment] 2021-01-07 21:32
Duplicate of #8312

**Closed by jelbourn** 2021-01-07 21:32 UTC
Labels: feature, needs triage
