### ISSUE TITLE
mat-drawer-inner-container with scrollbar shows different widths in Firefox and Chrome

### ISSUE THREAD

**Issue by kakins** [angular/components#15999] opened 2019-05-10 14:34 UTC
#### What is the expected behavior?

mat-drawer-inner-container width should be rendered consistently irrespective of Chrome or Firefox.

#### What is the current behavior?

Currently the sidenav width is being sized 17px higher in Chrome compared to Firefox, which corresponds to the width of the scrollbar.    

Chrome
![image](https://user-images.githubusercontent.com/14915247/57534380-85e63c80-7305-11e9-9241-7e16f2d655c0.png)

Firefox
![image](https://user-images.githubusercontent.com/14915247/57534398-93032b80-7305-11e9-8697-796a7d7ba492.png)

This can cause strange issues like this where the right padding appears to be displayed incorrectly in Firefox.  

![image](https://user-images.githubusercontent.com/14915247/57534849-94812380-7306-11e9-90dc-108ab84389f9.png)

#### What are the steps to reproduce?
https://angular-mat-sidenav-scrollbar-width-firefox-issue.stackblitz.io

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 7
Material 7.3.7
Windows
Typescript 3
Browsers: Chrome/Firefox

#### Is there anything else we should know?
I'm not sure if this is related or not:
https://github.com/angular/components/issues/11176

**Comment by jelbourn** [comment] 2019-05-12 02:41
@kakins which version of Firefox? I just tried Chrome and FF on macOS and they behave the same way. If it's only on Windows, it may be an OS thing.

**Comment by kakins** [comment] 2019-05-12 15:27
This was using the latest version of Firefox, 66.0.5 (64-bit).

**Comment by kakins** [comment] 2019-05-12 15:41
Another interesting view of this behavior, side by side using the Stackblitz mentioned above -- Chrome on the left and Firefox on the right.  Browser zoom is at 100% for both.

You can see that the Firefox rendering seems to produce an overflow, resulting in horizontal scrolling.  I trace this back to the aforementioned sizing issues related somehow to the width of the vertical scrollbar.

![image](https://user-images.githubusercontent.com/14915247/57584525-1e192880-74a2-11e9-8272-b2d0ff353998.png)

If this is a Browser and/or OS issue, it should would be nice if the framework could handle it for us so that we don't have to introduce custom CSS hacks per project.

**Comment by andrewseguin** [comment] 2019-05-15 20:51
Unfortunately this is due to a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=764076

It seems that firefox does not account for its scrollbar when determining the container's intrinsic width.

Here's a minimal reproduction of the issue: https://stackblitz.com/edit/typescript-muahrr

Closing since it depends on a fix from firefox and I cannot determine a workaround that would make sense for all browsers. Definitely open to suggestions if you can think of a solution.

**Closed by andrewseguin** 2019-05-15 20:51 UTC
Labels: needs clarification

**Comment by kakins** [comment] 2019-05-15 22:46
@andrewseguin Thanks!  It's at least good to know that this is a known bug in Firefox.
