### ISSUE TITLE
bug(cdk/scrolling): Virtual scrolling is broken in Chrome

### ISSUE THREAD

**Issue by seb-mtl** [angular/components#24199] opened 2022-01-13 02:37 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am using the virtual scroll view `cdk-virtual-scroll-viewport`. I am in Chrome and the content is flickering at high-speed scrolling. It can be reproduced either through a trackpad or with an infinite scroll mouse wheel.

I slowed down the animation to make the issue more apparent:

![chrome](https://user-images.githubusercontent.com/12844423/149255281-63a680e9-8eec-4f9f-93f3-aa9263b99905.gif)

This issue doesn't happen in Firefox:

![firefox](https://user-images.githubusercontent.com/12844423/149255331-a53eb804-8b30-4368-bee5-508b5ba3f375.gif)

### Reproduction

Visit https://stackblitz.com/edit/angular-ivy-k3hmzh?file=src%2Fapp%2Fapp.component.ts

### Expected Behavior

The view should not flicker.

### Actual Behavior

The scrollview flickers

### Environment

- Angular: 12.2.15
- CDK/Material: 13.1.2
- Browser(s): Chrome Version 97.0.4692.71
- Operating System (e.g. Windows, macOS, Ubuntu): MacBook Pro (13-inch, 2020) with 2GHz i5 and 16GB memory

**Comment by crisbeto** [comment] 2022-01-24 11:25
I couldn't reproduce it on a couple of different machines. This looks like the browser is struggling to keep up with the rendering.

**Comment by seb-mtl** [comment] 2022-01-24 16:10
I did some more digging and found that the issue is related to #20971 and can be fixed with the following workaround, see https://github.com/angular/components/issues/20971#issuecomment-722210932

```html
<div style="position: absolute; top:0; left:0; width:100%; height:100%; pointer-events:none"></div>
```

**Comment by wagnermaciel** [comment] 2022-03-16 16:25
Closing as duplicate of https://github.com/angular/components/issues/20971

**Closed by wagnermaciel** 2022-03-16 16:25 UTC
Labels: needs triage
