### ISSUE TITLE
PendingCopy moves focus to top of FocusTrap

### ISSUE THREAD

**Issue by tristanhale** [angular/components#18538] opened 2020-02-18 19:44 UTC
#### Bug, feature request, or proposal:
Bug: When using a `PendingCopy` via `xapCopyToClipboard` inside a `cdkTrapFocus` element, the focus gets moved to the first focusable element of the FocusTrap area.

#### What is the expected behavior?
I expect the focus to remain on the `xapCopyToClipboard` element, as it does when not in a `cdkTrapFocus` element.

#### What is the current behavior?
The focus moves to the first focusable element of the FocusTrap area when the `xapCopyToClipboard` element is clicked.

#### What is the use-case or motivation for changing an existing behavior?
The existing behavior is confusing and unexpected. It causes focus to move without reason and can cause the page to scroll significantly.

#### Is there anything else we should know?
The issue is caused by the `_textarea` element of [PendingCopy](https://github.com/angular/components/blob/master/src/cdk/clipboard/pending-copy.ts#L36), which is appended to the `<body>`. Naturally, the body element will be outside of any `cdkTrapFocus` element, so the `cdkTrapFocus` gets triggered whenever the `copy()` method gets called.

**Comment by crisbeto** [comment] 2020-02-18 20:29
Can you post an example of your code? I'm unable to reproduce it against this: https://stackblitz.com/edit/angular-3jnvrz.

**Comment by crisbeto** [comment] 2020-02-18 20:54
Also which focus trap implementation are you using @tristanhale? Is it the `ConfigurableFocusTrap` or the regular `FocusTrap`.

**Comment by crisbeto** [comment] 2020-02-20 21:21
Should've been resolved by https://github.com/angular/components/commit/c704d17e6a343f3f07d152d2afa64c25635f565f.

**Closed by crisbeto** 2020-02-20 21:21 UTC
Labels: G, P3, cannot reproduce
