### ISSUE TITLE
bug(mat-typography): mat-typography changes styles of material components

### ISSUE THREAD

**Issue by epelc** [angular/components#19236] opened 2020-05-03 04:09 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

See https://stackblitz.com/angular/lpojxbrykxj

Steps to reproduce:
1. Compare text height of title/subtitle in the first card vs the second
2. Notice they are different due to `.mat-typography` on the second card
 
 
#### Expected Behavior

What behavior were you expecting to see?

Adding `.mat-typography` should not override styles of material components. It is meant to allow you to get sensible defaults for the native components(h1,h2, p, etc). ie you should be able to add `.mat-typography` to your `body` element to enable material like typography styles for everything. But this should not change the styles of material components like `mat-card` since they should already have material typography on their elements like title/subtile.

#### Actual Behavior

What behavior did you actually see?

At least the title and subtitle components for material cards are changing styles when `mat-typography` is enabled. They should already have these styles taken into account when it is disabled and therefore should not change.

In this specific instance it looks like `mat-typography` sets a default `line-height: 20px`(fonts 14px/20) while the `mat-card-title` and subtitle do not have line height by default.

#### Environment

- Angular: latest
- CDK/Material: 9.2

**Comment by crisbeto** [comment] 2020-05-03 08:46
I had a PR for this a while ago, but we never managed to land it in g3 for some reason. https://github.com/angular/components/pull/10217

**Comment by jelbourn** [comment] 2020-05-26 20:30
Duplicate of #10215

**Closed by jelbourn** 2020-05-26 20:30 UTC
Labels: needs triage
