### ISSUE TITLE
Datepicker: year 2017 duplicated twice when year view selected

### ISSUE THREAD

**Issue by baroudihassan** [angular/components#17787] opened 2019-11-22 14:25 UTC
#### Reproduction

Steps to reproduce:
1. Open datepicker
2. Select year view

#### Expected Behavior

Years are displayed normally

#### Actual Behavior

2017 is displayed twice and 2018 isn't displayed

#### Environment

- Angular: 6.1.9
- CDK/Material: 6.4.7
- Browser(s): IE 11
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by crisbeto** [comment] 2019-11-22 17:03
I couldn't reproduce it against the examples on the docs site. Can you post an example of your code? Also you're running an old version of Material, have you tried updating it?

**Comment by crisbeto** [comment] 2020-05-28 17:45
Closing since I wasn't able to reproduce it last time around and there hasn't been any new activity in a long time.

**Closed by crisbeto** 2020-05-28 17:45 UTC
Labels: area: material/datepicker, cannot reproduce
