### ISSUE TITLE
bug(mat-select): Mat Select crashes Chrome tab and edge 

### ISSUE THREAD

**Issue by rschulz-scisys** [angular/components#28928] opened 2024-04-22 12:34 UTC
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

unknown

### Description

We have a problem with the angular 15 select component, crashing the current chrome browser (124) at least on macos (intel and arm64 build) and also happens on current edge, but not on safari. In our component wrapper this only happens with multi select values, but on the official demo page the normal component also crashes the browser.  The browser crashes as soon as you want to select on option and click to open the list

### Reproduction

Go to the official angular15 docs at https://v15.material.angular.io/components/select/overview

click on any list that is not using native with a current chrome browser or edge
see directly the "Aw snap" page

### Expected Behavior

show selection list when clicking in the list drop down

### Actual Behavior

browser crash "Aw snap"

### Environment

- Angular: latest 15
- CDK/Material: latest 15 (legacy and mdc)
- Browser(s): Chrome 124, Edge 124
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS 

Hint: Demo pages for Angular 16 and 17 work, only 15 crashes

**Comment by iangus** [comment] 2024-04-22 14:26
Been seeing this issue as well, but unable to reproduce it on the `64-bit` chrome build. We have been able to reproduce it on `arm64` builds as described in the issue details.

**Comment by WillPoulson** [comment] 2024-04-22 15:20
Also seeing this issue for any user who updates to the latest chrome.

**Comment by vtachkov** [comment] 2024-04-22 18:33
Also happening for us, same situation as mentioned above.

**Comment by mateusduraes** [comment] 2024-04-22 18:46
Also happening for me.
I was able to replicate it on both chrome and edge.
However, on firefox, everything works fine.

**Comment by danielcornock** [comment] 2024-04-23 09:52
We are having the same issues on Angular 16 using the legacy mat-select. Seems to not effect all instances but does effect most. Have attempted to upgrade to the latest minor version but no luck.

**Comment by fgfernandez0321** [comment] 2024-04-23 15:18
There is an open discussion and solution [here](https://github.com/angular/components/issues/28905)

**Comment by ErikZA** [comment] 2024-04-23 17:34
The same problem happens in angular version 14.3.0.
Chrome version 124.0.6367.61 (official version) 64-bit

Workaround to deal with the error!

```
export class AppComponent implements OnInit {
  public ngOnInit(): void {
    document.addEventListener('DOMNodeInserted', function () {
      const elements = document.querySelectorAll('[aria-owns]');

      elements.forEach(element => {
        element.removeAttribute('aria-owns');
      });
    });
  }
}
```

**Comment by IslamElKassas** [comment] 2024-04-26 06:54
> The same problem happens in angular version 14.3.0. Chrome version 124.0.6367.61 (official version) 64-bit
> 
> Workaround to deal with the error!
> 
> ```
> export class AppComponent implements OnInit {
>   public ngOnInit(): void {
>     document.addEventListener('DOMNodeInserted', function () {
>       const elements = document.querySelectorAll('[aria-owns]');
> 
>       elements.forEach(element => {
>         element.removeAttribute('aria-owns');
>       });
>     });
>   }
> }
> ```

DOMNodeInserted is deprecated. 
Instead use this code:

```
const ariaOwnsRemover$ = new MutationObserver((mutationsList) =>
        {
            for (const m of mutationsList) 
                if (m.attributeName === 'aria-owns')
                    (m.target as Element).removeAttribute('aria-owns');
        });

        ariaOwnsRemover$.observe(document, { attributes: true, subtree: true });
```

Tested with Angular 14 and Chrome 124

**Comment by qannoufoualid** [comment] 2024-04-29 10:03
i vote to close this because fixed in chromium, https://issues.chromium.org/issues/335553723#comment148

**Closed** 2024-05-03 07:02 UTC
Labels: needs triage
