### ISSUE TITLE
bug(MatDateRangePicker): date range emits changes to form

### ISSUE THREAD

**Issue by zehavibarak** [angular/components#20432] opened 2020-08-27 07:04 UTC
#### Reproduction

https://stackblitz.com/edit/angular-ki1fyd?file=src/app/date-range-picker-overview-example.ts

Steps to reproduce:
1. ngOnInit patches form values using emitEvent: false;
2. The form dirty is true;
 
should have been false.

**Comment by zehavibarak** [comment] 2020-08-28 08:32
To my understanding, date-range-input.ts calls _registerModel() in ngAfterContentInit() after the value is set, causing it to trigger changes to form control.

**Comment by crisbeto** [comment] 2020-08-30 08:33
Duplicate of https://github.com/angular/components/issues/20213.

**Closed by crisbeto** 2020-08-30 08:33 UTC
Labels: needs triage
