### ISSUE TITLE
ng update Migration Failed when migrating from 8.2.3 to 9.2.2

### ISSUE THREAD

**Issue by ceoaliongroo** [angular/components#19270] opened 2020-05-06 14:43 UTC
Reproduction
Steps to reproduce:

```ng update @angular/material --migrate-only --from=8.2.3 --verbose```

Because there is not enough information provided by the migration, I am unable to provide a reproduction stackblitz.

Expected Behavior
Successful migration to v9, or at least a meaningful error message that tells me where something might be wrong.

Actual Behavior
What behavior did you actually see?
```bash
x Migration failed: Path "/../../../app/common/fwa/fwa-modals/fwa-modal-confirma
tion-with-message/fwa-modal-confirmation-with-message.component.html" is invalid
.
  See "C:\Users\carlosm\AppData\Local\Temp\ng-Tj2o0T\angular-errors.log" for fur
ther details.
```
Environment
Angular: 9.1.4
CDK/Material: 8.2.3 -> 9.2.2
Browser(s): N/A
Operating System (e.g. Windows, macOS, Ubuntu): Windows
I add the console an then the error log 

# console
```bash
D:\Dev\WEB\FWAClient>ng update @angular/material --allow-dirty --migrate-only  -
-from=8.2.3 --verbose
Locating potential npmrc files:
Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
Trying 'C:\Users\carlosm\.npmrc'...found.
Trying 'D:\Dev\.npmrc'...not found.
Trying 'D:\Dev\WEB\.npmrc'...not found.
Trying 'D:\Dev\WEB\FWAClient\.npmrc'...not found.
Repository is not clean. Update changes will be mixed with pre-existing changes.

Using package manager: 'npm'
Collecting installed dependencies...
Found 59 dependencies.
** Executing migrations of package '@angular/material' **

> Updates Angular Material to v9
x Migration failed: Path "/../../../app/common/fwa/fwa-modals/fwa-modal-confirma
tion-with-message/fwa-modal-confirmation-with-message.component.html" is invalid
.
  See "C:\Users\carlosm\AppData\Local\Temp\ng-xYx591\angular-errors.log" for fur
ther details.

```

# error log
```bash
[error] Error: Path "/../../../app/common/fwa/fwa-modals/fwa-modal-confirmation-with-message/fwa-modal-confirmation-with-message.component.html" is invalid.
    at noCacheNormalize (D:\Dev\WEB\FWAClient\node_modules\@angular-devkit\core\src\virtual-fs\path.js:224:23)
    at Object.normalize (D:\Dev\WEB\FWAClient\node_modules\@angular-devkit\core\src\virtual-fs\path.js:188:21)
    at HostTree._normalizePath (D:\Dev\WEB\FWAClient\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:82:23)
    at HostTree.exists (D:\Dev\WEB\FWAClient\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:198:45)
    at DevkitFileSystem.exists (D:\Dev\WEB\FWAClient\node_modules\@angular\cdk\schematics\ng-update\devkit-file-system.js:49:31)
    at componentMetadata.properties.forEach.property (D:\Dev\WEB\FWAClient\node_modules\@angular\cdk\schematics\update-tool\component-resource-collector.js:119:43)
    at Array.forEach (<anonymous>)
    at ComponentResourceCollector._visitClassDeclaration (D:\Dev\WEB\FWAClient\node_modules\@angular\cdk\schematics\update-tool\component-resource-collector.js:65:42)
    at ComponentResourceCollector.visitNode (D:\Dev\WEB\FWAClient\node_modules\@angular\cdk\schematics\update-tool\component-resource-collector.js:38:22)
    at visitNodeAndCollectResources (D:\Dev\WEB\FWAClient\node_modules\@angular\cdk\schematics\update-tool\index.js:64:35)
    at visitNodes (D:\Dev\WEB\FWAClient\node_modules\typescript\lib\typescript.js:18440:30)
    at Object.forEachChild (D:\Dev\WEB\FWAClient\node_modules\typescript\lib\typescript.js:18673:24)
    at visitNodeAndCollectResources (D:\Dev\WEB\FWAClient\node_modules\@angular\cdk\schematics\update-tool\index.js:63:20)
    at sourceFiles.forEach.sourceFile (D:\Dev\WEB\FWAClient\node_modules\@angular\cdk\schematics\update-tool\index.js:73:21)
    at Array.forEach (<anonymous>)
    at UpdateProject.migrate (D:\Dev\WEB\FWAClient\node_modules\@angular\cdk\schematics\update-tool\index.js:68:25)

```

There is some config file to skip this file from the migration? Until detect the error.

Something like this:
https://github.com/angular/angular/issues/33718#issuecomment-552518850

**Comment by devversion** [comment] 2020-05-14 13:58
I looked into this and tried reproducing it. I was able to reproduce similar errors, but not necessarily in scenarios where they are undesired:

1. If a component referenced a HTML or CSS file through an accidental absolute path. e.g. `/my-component.html` is used in the `templateUrl`
2. A relative path exceeds the Angular project (e.g. too many parent directory path segments).

I'm planning on improving paths anyway in the schematics since there is a lot ambiguity with regards to Angular devkit paths and absolute file system paths. Can you check if any of the two scenarios above match in your project?

If not, would you be able to check if the component that relies on `fwa-modal-confirmation-with-message.component.html` does anything unexpected? A reproduction would be great.

**Comment by devversion** [comment] 2020-05-25 13:14
Closing as we think that this has been fixed with recent changes, but it's not guaranteed due to an insufficient reproduction.

**Closed by devversion** 2020-05-25 13:14 UTC
Labels: needs clarification
