### ISSUE TITLE
feat(TimePicker?): add new component for TimePicker from Material Design

### ISSUE THREAD

**Issue by AlexElin** [angular/components#28059] opened 2023-11-06 10:14 UTC
### Feature Description

The Material Design spec contains the [definition of TimePicker component](https://m3.material.io/components/time-pickers/overview).
However, the Angular Material lacks of it. 
It would be helpful to add this new component into the library.

**Comment by crisbeto** [comment] 2023-11-06 10:26
Duplicate of https://github.com/angular/components/issues/5648.

**Closed by crisbeto** 2023-11-06 10:26 UTC
Labels: feature, needs triage
