### ISSUE TITLE
mat-horizontal-stepper: Unable to set linear=true

### ISSUE THREAD

**Issue by pyle** [angular/components#7699] opened 2017-10-11 00:19 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behaviour?
Stepper is linear and doesn't produce the below error.

#### What is the current behavior?
Stepper component throws errors when linear parameter is set to true. 
Tested with dynamically generated steps and non-dynamic steps and same error occurs.
```
ERROR TypeError: Cannot read property 'invalid' of undefined
    at eval (VM808 cdk-stepper.umd.js:375)
    at Array.some (<anonymous>)
    at MatHorizontalStepper.CdkStepper._anyControlsInvalid (VM808 cdk-stepper.umd.js:375)
    at MatHorizontalStepper.set [as selectedIndex] (VM808 cdk-stepper.umd.js:206)
    at MatHorizontalStepper.set [as selected] (VM808 cdk-stepper.umd.js:230)
    at MatStep.CdkStep.select (VM808 cdk-stepper.umd.js:125)
    at Object.eval [as handleEvent] (VM994 MatHorizontalStepper.ngfactory.js:26)
    at handleEvent (VM801 core.umd.js:12055)
    at callWithDebugContext (VM801 core.umd.js:13525)
    at Object.debugHandleEvent [as handleEvent] (VM801 core.umd.js:13113)
    at dispatchEvent (VM801 core.umd.js:8647)
    at eval (VM801 core.umd.js:9258)
    at HTMLElement.eval (VM791 platform-browser.umd.js:2685)
    at e.invokeTask (VM1088 zone.min.js:1)
    at Object.onInvokeTask (VM801 core.umd.js:3913)
```

#### What are the steps to reproduce?
Recreated basic Stepper component in this plunker with a few example: 
http://plnkr.co/edit/mES0H2nKfYjfcrUOHexz

#### What is the use-case or motivation for changing an existing behavior?
N/A

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
angular/material 2.0.0-beta.12

**Comment by christinakayastha** [comment] 2017-10-11 02:26
Looks like the issue you are seeing is because you haven't setup the `stepControl` attribute. With the linear flow the stepControl is checked for validity before allowing the user to proceed to the next step. More info at the docs here: https://material.angular.io/components/stepper/overview#linear-stepper

I initially stumbled on this as well-would it be possible to catch the error when stepControl is not specified in linear flow and throw a more descriptive message?

**Comment by pyle** [comment] 2017-10-11 08:23
Ahh I see. 
So in my case, I don't want to treat the stepper as a form but rather listen to the `selectionChange` events and use routes; I could just create a dummy `AbstractControl` for this but it seems a little wasteful.

**Comment by Toub** [comment] 2017-10-12 12:49
Interesting component, but very complex to use for custom behaviors.

Need to be able to change step and "completed" value manually.

**Comment by yusijs** [comment] 2017-10-25 19:57
I'm seeing the same (or at least a similar) issue. I want some steps to be mandatory, and others to be optional. However, optional=true does nothing, and I still get the error described in the OP. Am I completely misreading the docs, or is there something off here?

**Comment by smlee** [comment] 2017-11-20 17:41
So based on what I am reading does the completed and optional attributes don't work? Because I am having trouble using completed and optional attributes. I have a dynamic form group where one of the control validators changes based on a checkbox value. It doesn't seem to properly update stepControl or errorState.

**Comment by realharry** [comment] 2017-11-30 08:31
I'm having the same issue. I include two forms (each as a component) from a different module as two separate steps in a stepper control. Everything I've tried with this setup ("matStepperNext", etc.) all works well except for this `linear=true`. 

![screenshot from 2017-11-30 00-25-08](https://user-images.githubusercontent.com/28793852/33420840-fca646a2-d564-11e7-8043-e0d7fcc59f11.png)

As shown in the screenshot, the form validation works. As indicated by the red label (and the grayed-out Next button), the first step form is currently not valid, and yet I can still click the second step.

**Comment by mmukkara** [comment] 2018-10-21 16:14
> I'm having the same issue. I include two forms (each as a component) from a different module as two separate steps in a stepper control. Everything I've tried with this setup ("matStepperNext", etc.) all works well except for this `linear=true`.
> 
> ![screenshot from 2017-11-30 00-25-08](https://user-images.githubusercontent.com/28793852/33420840-fca646a2-d564-11e7-8043-e0d7fcc59f11.png)
> 
> As shown in the screenshot, the form validation works. As indicated by the red label (and the grayed-out Next button), the first step form is currently not valid, and yet I can still click the second step.

I know this is an old post.  I don't see any updates on Stepper component for a long time. Are you able to fix this issue? I am in a similar situation.

Thanks for the help

**Comment by silver-stack** [comment] 2019-03-17 20:35
Hello, I know that this is an old post, however I am also having this issue.  I am also using the mat-vertical-stepper.  My errors trigger, however I am able to move onto the next step.

I am also using the mat-dialog so not sure if this is related or not?  Example step:

<mat-dialog-content class="modal customer">
<mat-vertical-stepper [linear]="isLinear" #stepper>
  <mat-step [stepControl]="customerFormGroup">    
      <form [formGroup]="customerFormGroup">

 <div>
      <mat-form-field class="full-width modal-field-width">
         <input formControlName="emailFormControl" readonly matInput placeholder="Customer Email" id="emailFormControl" name="emailFormControl">
       </mat-form-field>          
    </div>   
<div>

  <button 
  [disabled]="!customerFormGroup.valid"
  matStepperNext mat-raised-button color="primary" type="submit" name="butt"> 
    <mat-icon class="secondary-colour link-button">arrow_downward</mat-icon>Next
  </button>

    </form>
  </mat-step>

**Comment by nicolae-olariu** [comment] 2020-04-08 19:12
Hi guys, same error here. Trying to use a mat-vertical-stepper but linear input doesn't work. It always treats it as `false` no matter if I set it to `true`. I've even copy/pasted the mat-vertical-stepper from [official docs](https://stackblitz.com/angular/nvvbodoxdlrb?file=src%2Fapp%2Fstepper-vertical-example.html) into my project with the same result. Any ideas?

Thank you in advance!

**Comment by nicolae-olariu** [comment] 2020-04-08 19:43
Never mind guys. Once I made one of the formControls inside that specific step (formGroup) `required`, it started to work as designed: it no longer lets you click to the next step until you fix the validation. Thanks and sorry!

**Comment by amysorto** [comment] 2024-05-08 20:36
Closing this issue since it seems it should have been closed before

**Closed by amysorto** 2024-05-08 20:36 UTC
Labels: P3, area: material/stepper, area: docs
