### ISSUE TITLE
bug(COMPONENT): Change Detection triggered on mat-table header cell hover

### ISSUE THREAD

**Issue by JeanMeche** [angular/components#24806] opened 2022-04-20 14:02 UTC
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm having performance problems with a mat-table triggering change detections despite using OnPush.

When hovering the header cells, you will see the random number change.

Why would hovering on the table header trigger a change detection on the parent components ?

### Reproduction

Here is a working example : https://stackblitz.com/edit/angular-bjouzc?file=src%2Fapp%2Fapp.component.ts

### Expected Behavior

Hovering on the header cells should not trigger the change detection on OnPush parents. 

### Actual Behavior

A OnPush parent should not have its change detection triggered. 

### Environment

- Angular: 13.3
- CDK/Material 13.3:
- Browser(s): Chrome 100

**Comment by volvachev** [comment] 2022-04-20 17:29
Hi, I looked at the code, it responds to display(start and finish animation) a sorting arrow when  you triggers `mouseenter|mouseleave` on the `mat-sort-header`.

**Comment by crisbeto** [comment] 2022-04-22 09:22
Duplicate of https://github.com/angular/components/issues/19441.

**Closed by crisbeto** 2022-04-22 09:22 UTC
Labels: needs triage
