### ISSUE TITLE
bug(COMPONENT): Fab buttons not using correct theming

### ISSUE THREAD

**Issue by passee** [angular/components#28803] opened 2024-03-31 23:21 UTC
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.14

### Description

With Angular v17.3.1 and Material 3 it seems like the FAB buttons dont use the correct theming colors.
Edit: Just noticed its even more visible on mat-icon-buttons

Difference between Angular v17.3.1 and v16.2.14 (where it was correct)
v17:
![image](https://github.com/angular/components/assets/115150084/0c16068a-683e-4cb9-b0cc-04eb4d465387)
v16:
![image](https://github.com/angular/components/assets/115150084/30795456-8e68-4d46-8f82-afd80af6ae5c)

### Reproduction

StackBlitz links provided via angular website.

### Expected Behavior

Same color theming on fab buttons like on all other buttons, like in angular v16

### Actual Behavior

Primary and accent are a bit off and warn is completely off

### Environment

- Angular: v17.3.1
- CDK/Material: 17.3.1
- Browser: Chrome
- Operating System: Windows 11

**Comment by crisbeto** [comment] 2024-04-01 02:56
It's showing the M3 versions of the FAB. Closing as a duplicate of https://github.com/angular/components/issues/28787.

**Comment by passee** [comment] 2024-04-01 15:01
So M3 just doesnt style fab and icon buttons in the correct color?

**Comment by crisbeto** [comment] 2024-04-01 15:11
The color should be correct, it's just different in this version of the spec.

**Comment by crisbeto** [comment] 2024-04-01 18:01
That being said, I just noticed that the warn color isn't showing up.

**Comment by crisbeto** [comment] 2024-04-02 13:38
Looks like the warn color was intentionally dropped from the FABs: https://github.com/angular/components/blob/main/src/material-experimental/theming/_color-api-back-compat.scss#L78.

**Closed by crisbeto** 2024-04-02 13:38 UTC
Labels: needs triage
