### ISSUE TITLE
Mat form field input tag placeholder bug in Internet Explorer

### ISSUE THREAD

**Issue by bdutgu** [angular/components#16026] opened 2019-05-14 12:57 UTC
#### Bug, feature request, or proposal:
Mat form field input tag placeholder bug in Internet Explorer

#### What is the expected behavior?
Using the form field without getting in a state where you cannot type in the input field

#### What is the current behavior?
When clicking on the placeholder in top of the form field after focusing on the form field you are not able to type in the input field

#### What are the steps to reproduce?
HTML code which provides the bug:
![HTML input field not working](https://user-images.githubusercontent.com/50622252/57699049-4eee8e80-7657-11e9-809d-4138f5302614.PNG)
The behavior can be tried on https://material.angular.io/components/form-field/overview
A work around is the following HTML code:
![HTML input field working](https://user-images.githubusercontent.com/50622252/57699081-63cb2200-7657-11e9-8362-14cf169b3623.PNG)

#### What is the use-case or motivation for changing an existing behavior?
The code getting around the problem will be deprecated in later versions so it is necessary to get this bug fixed. Info about the deprecation can be found on https://material.angular.io/components/form-field/overview

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular: 7.2.3
Material: 7.3.1
OS: Windows 7 Enterprise - Service Pack 1
TypeScript: 3.1.6
Browsers affected: Internet Explorer

**Comment by macjohnny** [comment] 2019-05-16 06:29
I think this is a duplicate of https://github.com/angular/components/issues/15093

**Closed** 2019-05-16 10:14 UTC
Labels: P4, ie11
