### ISSUE TITLE
Snack Bar Actions Not Being Displayed

### ISSUE THREAD

**Issue by kwright02** [angular/components#17553] opened 2019-10-31 14:33 UTC
#### What are you trying to do?

Display a snackBar with an action

#### What troubleshooting steps have you tried?

The action button is not displayed, and upon inspection of the html I discovered the text color is the same as the snackBar background. I am unable to change either color as the panelClass property seems to be ignored.

#### Reproduction

https://stackblitz.com/edit/components-issue-o2hjx6

Steps to reproduce:
1. Try to open a snackBar with an action text
2. See that the text for the action does not display
  
#### Environment

- Angular: 8.3.0
- CDK/Material: 8.2.3
- Browser(s): Safari, Chrome, Firefox, Opera, Brave
- Operating System (e.g. Windows, macOS, Ubuntu): macOS 10.14.6

**Comment by crisbeto** [comment] 2019-10-31 18:04
The Stackblitz that you linked works for me:
![rEDEQBB](https://user-images.githubusercontent.com/4450522/67973707-498afd80-fc11-11e9-9d52-efca973a428b.png)

**Comment by kwright02** [comment] 2019-11-01 12:57
I know it works on stack blitz, it doesn't work in my project though.

**Comment by ccjmne** [comment] 2019-11-01 18:21
@kwright02, it sounds to me like the problem doesn't come from the component itself then. Or at least, not the version you've used in your sample Stackblitz app.

You yourself proved that it works pretty well on a bare project: I have an inkling that it is some styling property in your own, bigger project that is overriding the default one. It is quite hard for us to lend a hand without being able to reproduce the problem you're facing!

The style inspector of your web browser should have the capabilities to tell you exactly where the overriding style comes from; I would start looking there if I were in your position.

**Comment by kwright02** [comment] 2019-11-05 19:12
So I've done extensive digging through the project, and this is the color property for the action button:
`css

color: rgb(38, 50, 56);
inherit.mat-button,…oked-button	Author Stylesheet
buttontextinput:matche…ton, button	User Agent Stylesheet
initialinput, texta…ect, button	User Agent Stylesheet
#263238.mat-simple-…kbar-action	Author Stylesheet
rgba(255, 255, 255, 0.7).mat-snack-bar-container	Author Stylesheet
white !importantsnack-bar-container	Author Stylesheet
texthtml`

It seems to override my !important css class to make the text white, and rgb(38, 50, 56) seems to be the background color of the snackBar.

Someone has also built a custom theme for the project and that is as follows:

`css

@import '~@angular/material/theming';
@include mat-core();

$messaging-app-primary: mat-palette($mat-green, 900);
$messaging-app-accent: mat-palette($mat-blue-gray, 900);
$messaging-app-warn: mat-palette($mat-red);
$messaging-app-background: mat-palette($mat-grey, A100);
$messaging-app-text: #FFFFFF;
$messaging-app-font: "Source Sans Pro";
$messaging-app-font-family: sans-serif;
$messaging-app-font-size: 20px;
$messaging-app-font-size-heavy: 25px;
$messaging-app-font-weight: 300;
$messaging-app-theme: mat-light-theme($messaging-app-primary, $messaging-app-accent, $messaging-app-warn);
@include angular-material-theme($messaging-app-theme);`

I'm really stumped here

**Comment by ccjmne** [comment] 2019-11-05 20:18
Hey,

I'm not on my computer right now but I'll take a look at it soon.

I really think a Stackblitz reproducing your issue would go a long way,
however.

I think you understand that an `! important` rule can't be overridden by a
non-important one, and that is what is puzzling you -- understandably so!

The root of your problem probably lies there -- Angular may use shadow DOMs
for its components. That is configurable! Maybe you could switch to a
different style encapsulation technique an see whether your style still
mysteriously aren't applied.

Alternatively, try putting the style into your main, global stylesheet
instead of that of your component (styles.(s)css probably).

NB: that wouldn't be a proper fix, but getting this to work would mean that
we figured what is going on. I would encourage you to read up on [Angular's
view encapsulation] (https://angular.io/api/core/ViewEncapsulation) if any
of these recommendations does work :)

**Comment by devversion** [comment] 2020-05-26 12:42
We don't use `!important` for the color of the snackbar action buttons. This looks like an issue specific to your project. Most likely related to custom styling in your project.

Closing as there is no issue we can see on our end. If you think there is one, please help us providing a reproduction that we can look at.

**Closed by devversion** 2020-05-26 12:42 UTC
Labels: needs triage, troubleshooting
