### ISSUE TITLE
IE11 Support & Performance in general

### ISSUE THREAD

**Issue by mbeckenbach** [angular/components#4342] opened 2017-05-01 15:14 UTC
#### Bug, feature request, or proposal:
Feature request

#### What is the expected behavior?
As soon as the library detects IE it should disable everything that can cost performance like animations.

#### What is the current behavior?
Mostly performance, sometimes layout issues

#### What are the steps to reproduce?
Open any real world MD2 application on IE11.

#### What is the use-case or motivation for changing an existing behavior?
Provide a degraded but still working user experience in IE.

#### Which versions of Angular, Material, OS, browsers are affected?
Everything as long as you use IE

#### Is there anything else we should know?
Even edge is much slower that chrome and ff. Maybe even deliver a degraded experience their, but i guess ms would not like this. :-)

**Comment by mbeckenbach** [comment] 2017-05-16 07:04
I found out, that changedetection onPush helps IE a lot. But the animations like dialog open animation are killing its performance. Maybe the animations module could turn into a noop animation module as soon as it detects an IE?

**Comment by SebastianSchenk** [comment] 2017-06-12 16:51
I think turning off animations is not really the right solution. Why can't this be fixed in an other way?

**Comment by david-gang** [comment] 2017-06-26 13:53
This is really a pitty. I hoped that performance will get better in material2, but it looks like the problem is the interaction of the css itself with ie11. Here is the thread from angular material 1 https://github.com/angular/material/issues/8616 Maybe this can help.

**Comment by RaulRG** [comment] 2017-09-13 10:36
This is important for us too. Our developers all work with Chrome, but we must support IE or at least Edge as many of our customers use them. Of course we could ignore animations, but even the ripple effects on buttons are slooooooow.

**Comment by mbeckenbach** [comment] 2017-09-15 06:07
@RaulRG 
We're in the same situation. Edge seams to be a bit faster. But IE.....
In edge - at least on my machine - I can see a huge performance issue when F12 tools are open. 

In both browsers it looks like it's doing all the rendering and animations by CPU not by GPU.
Javascript is quite fast in Edge, but you can see a high CPU usage when something is getting re-rendered.

Also I can see that the same application using something like plain css or bootstrap (so, no material) is fast in IE. So yes, there is something inside material which causes this.

One thing we changed to improve performance in IE was not using the angular flex layout library and setup flex on our own by css.

**Comment by Gorniv** [comment] 2018-07-20 14:35
any solutions?

**Comment by jelbourn** [comment] 2020-04-28 17:53
I'm going to close this issue since, realistically, improving IE11 performance is never going to get close to the top of our priority list.

**Closed by jelbourn** 2020-04-28 17:53 UTC
Labels: P5, feature, ie11, needs discussion
