### ISSUE TITLE
feat(docs): Search for docs

### ISSUE THREAD

**Issue by Adam-Michalski** [angular/components#19821] opened 2020-07-01 12:44 UTC
#### Feature Description

Search which runs all documentation and content to find desired input

#### Use Case

Many times I need to use google with site param to search trought material docs and still results are not satisfying.

As an example bootstrap docs search serves lookup in titles at pages content
https://getbootstrap.com/docs/

**Comment by crisbeto** [comment] 2021-05-28 05:43
I just noticed that this is a duplicate of https://github.com/angular/components/issues/12446. Closing.

**Closed by crisbeto** 2021-05-28 05:43 UTC
Labels: P3, area: material.angular.io, feature
