### ISSUE TITLE
ivy compilation problems: Can't bind to 'matRippleDisabled' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by leon** [angular/components#15261] opened 2019-02-21 08:11 UTC
#### What is the expected behavior?
When running angular 8 beta 5 with material 7.3.2 and compiling using ivy, the project should work without errors

#### What is the current behavior?
When I start the project I'm getting `Can't bind to 'matRippleDisabled' since it isn't a known property of 'div'.`

and yes, I have included the matRippleModule

#### What are the steps to reproduce?
As soon as I remove all buttons (which i guess use the matRippleModule) everything works.

As stackblitz doesn't do ivy compilation yet, i've created a minimal repo to show the error.

https://github.com/leon/bug-angular-material-ripple

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 8 beta 5
Material 7.3.2

**Comment by leon** [comment] 2019-03-08 12:09
I've tried updating to Angular 8 beta 7, but still the same problem

**Comment by josephperrott** [comment] 2019-06-04 16:26
@leon This should be sorted out now, can you confirm if you are still seeing this issue?

**Comment by crisbeto** [comment] 2020-05-25 19:22
I couldn't reproduce it against the latest version. Closing.

**Closed by crisbeto** 2020-05-25 19:22 UTC
Labels: area: material/core
