### ISSUE TITLE
[Datepicker] MatLuxonDateAdapter

### ISSUE THREAD

**Issue by FrankiePo** [angular/components#12321] opened 2018-07-22 21:23 UTC
#### Bug, feature request, or proposal:
Feature request
#### What is the expected behavior?
Luxon Date Adapter for datepicker, like the moment one.

#### What is the current behavior?
There is no built-in support for luxon date library.

#### What is the use-case or motivation for changing an existing behavior?
The use case is to have built-in Luxon support for datepicker

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.0.9, Newest Material, etc
#### Is there anything else we should know?

**Comment by babeal** [comment] 2018-11-27 07:47
I think we are going to build this for our project.  Is this something that the material team would like contributed back?

**Comment by alexxxxOG** [comment] 2018-12-07 14:31
This is a duplicate of #10427.

**Comment by kdrvn** [comment] 2019-01-25 11:03
What is the status on this feature? Is it still being considered?
I wrote an implementation with proper testing for a project, I could wrap it in a PR.

**Comment by mmalerba** [comment] 2019-01-25 17:05
This has been implemented and is waiting to be merged: #14681

**Comment by jelbourn** [comment] 2020-09-17 22:17
Tracking this in #20599 going forward

**Closed by jelbourn** 2020-09-17 22:17 UTC
Labels: P5, area: material/datepicker, feature, has pr
