### ISSUE TITLE
help(cdk stepper): how template ref component in stepper

### ISSUE THREAD

**Issue by SrgGs** [angular/components#24970] opened 2022-05-25 11:25 UTC
### What are you trying to do?

I try

<img width="484" alt="image" src="https://user-images.githubusercontent.com/6164822/170251957-b37802ed-f9ba-452f-b647-631add8201be.png">

  error:
  
  ` NG8002: Can't bind to 'content' since it isn't a known property of 'cdk-step'.
1. If 'cdk-step' is an Angular component and it has 'content' input, then verify that it is part of this module.
2. If 'cdk-step' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

15       [content]="name"`

### What troubleshooting steps have you tried?

google

### Reproduction

Steps to reproduce:
1. 
2.

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by zarend** [comment] 2022-05-27 16:47
Hello @SrgGs , I believe this is intended behavior as `content` is a normal property on `MatStep`, and it's not an `@Input` ([MatStep API documentation](https://material.angular.io/components/stepper/api#MatStep)). `content` is available to access programmatically.

It seems to me that putting the `<ng-template>` inside the `<cdk-step>` would do what you're trying to accomplish. Does this resolve the issue for you @SrgGs ?

```
<cdk-step
  *ngFor="let item of steps"
  label="{{ item.label }}"
>
  <ng-template #name>text</ng-template>
</cdk-step>
```

**Comment by zarend** [comment] 2022-06-22 22:40
@SrgGs I am going to close this as I believe it has been resolved. If the issue persists, please reopen this issue or file a bug report https://github.com/angular/components/issues/new/choose

**Closed by zarend** 2022-06-22 22:40 UTC
Labels: troubleshooting, needs triage, area: cdk/stepper
