### ISSUE TITLE
bug(table) stickyness of header-cell is ignored in sticky header-row when on Edge using flex-style table

### ISSUE THREAD

**Issue by IlCallo** [angular/components#13665] opened 2018-10-18 14:41 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Sticky columns in a sticky row should behave as both stickyness rules applies

#### What is the current behavior?
Once the header is set as sticky, the header-cells behave as they don't have `position: sticky`.
Happens only with flex-style table, runs fine with native table (except all the others horrible GUI problems with it).
Happens only on Edge, runs fine on Chrome and Firefox.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-1jas2g

#### What is the use-case or motivation for changing an existing behavior?
It's broken

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Angular 6.1.1
Angular Material 6.4.7
Edge: 17.17134
Windows 10
Typescript 2.9.x

#### Is there anything else we should know?
Hi ❤️

**Comment by IlCallo** [comment] 2018-11-05 14:19
Seems related [to this](https://stackoverflow.com/questions/44446671/my-position-sticky-element-isnt-sticky-when-using-flexbox), I'm investigating further

**Comment by IlCallo** [comment] 2018-11-05 17:40
[This](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16462235/) is not directly related, but is sure is a pain in the ass to debug and fix this issue.

An Edge bug (apparently related to buggy sticky position implementation) makes it crash every time you try to inspect the element.
Problem is: the crash happens in the exact same conditions in which this issue heppens.
Any idea on how can I try to debug it further or any quirks/known problems with position sticky mixed with flexbox (which seems the interaction causing this issue)?

**Comment by IlCallo** [comment] 2018-11-05 17:56
Important note: stickyness works correctly if only columns are sticky or only the header row is sticky, so the issue probably is in the interaction between the two sticky features

**Comment by manklu** [comment] 2018-11-05 18:12
Duplicate of https://github.com/angular/material2/issues/1192?

Your columns and rows are sticky, but total misplaced.

**Comment by IlCallo** [comment] 2018-11-05 18:33
What you linked doesn't seems related to what I'm doing... Maybe you typed the wrong reference?

Anyway, they are not misplaced at all, they are right where they would be if no sticky rule was applied to them...

**Comment by IlCallo** [comment] 2018-11-06 13:48
Even with the edited reference, the problem is not the same.
That applies to sticky header **with native table** version.
Mine applies **only** on the flexbox version,

Check out the stackblitz I put in the first message to understand what's going on :)

**Comment by IlCallo** [comment] 2018-11-06 15:41
I apparently found [the culprit](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18940617/)

Edge ignores sticky elements inside other sticky elements.

@andrewseguin any idea on how this can be managed or worked around?
I'm available to work on a PR to fix this behaviour, if there is some kind of intelligent idea to put a patch to this when on Edge, until we wait for Edge to fix the problem.

A disclaimer in the documentation is probably a good idea, sticky header + sticky columns seems a really common scenario to me when using table component

**Comment by IlCallo** [comment] 2018-11-06 17:45
I'll try to toss out a workaround.

Given that sticky positioning works (more or less) well on Edge until you get to nesting, an idea could be to detect if this conditions applies and only put into action the workaround in those cases:
- we are on Edge
- we are managing a sticky row
- the sticky row contains at least one sticky column

First idea I got was to fallback to the complex method used by other table implementations: put sticky columns of every sticky row into an absolute positioned div or even better change positioning of all sticky columns in that case to `absolute` and manage all columns separately.

This unfortunately isn't easy as I wished.

Just changing positioning of the sticky column will still bind it to the first not-static element, which is it's sticky parent, and it won't resolve a thing.

This probably needs to be addressed via JS in every aspect.
Sticky-in-sticky columns cells must be copied (or extracted leaving a placeholder?) and attached into absolutely positioned divs directly inside the `mat-table` element, which must get their height from the sticky row and copy the sticky columns width from the normal cells.

This absolutely positioned div will cover the original ones and must be managed via JS to emulate sticky position. A valid idea could be to use [sticky-js](https://github.com/rgalus/sticky-js) for this.

Looks good enough?

**Comment by IlCallo** [comment] 2018-11-12 17:40
My explorations continues.
We need these informations in one place to make the fix consistent:
1. list of sticky rows
2. rows native elements references
3. list of sticky columns inside every row
4. type of the table (flex or native)
5. browser in use (to target only Edge)

Edge can be detected from pretty much everywhere using feature detection so that's not a problem.

I studied a bit the CDK table code and I'm not sure which would be the best place to put the fix, but I have a couple of ideas:

- `stickRows` in **sticky-styler**: it has access to all rows native elements and knows which ones must be sticky (`1`, `2`). It has an internal property to keep track if the type of table (`4`). Only problem, it cannot check in an easy and fast way if a row have inside at least one sticky column (**not** `3`);
- `updateStickyColumns` in **sticky-styler**: it has access to all rows native elements (`2`), it can access the table type (`4`) and has information about which columns are sticky (`3`). We don't have here information about the stickyness of the rows (**not** `1`);

We probably should keep the fix code inside **sticky-styler**, but we never have all the info we need.
The last method which knows all the info we need is `_addStickyColumnStyles` in **table.ts**. The problem here is that it define as parameter a type `BaseRowDef`, because it takes as assumption that stickyness isn't needed here, instead of keeping `CdkHeaderRowDef` and `CdkFooterRowDef` which extends the base class keeping into account the stickiness.

A possible solution would be to add a `isSticky` parameter at the end of the `updateStickyColumns` method call which defaults to false, then change `_addStickyColumnStyles` second parameter type to an union type with all row types (`CdkHeaderRowDef | CdkFooterRowDef | CdkRowDef`) and pass in the sticky property (with a not-null assertion).

```typescript
/** Adds the sticky column styles for the rows according to the columns' stick states. */
  private _addStickyColumnStyles(rows: HTMLElement[], rowDef: CdkHeaderRowDef | CdkFooterRowDef | CdkRowDef) {
    const columnDefs = Array.from(rowDef.columns || []).map(c => this._columnDefsByName.get(c)!);
    const stickyStartStates = columnDefs.map(columnDef => columnDef.sticky);
    const stickyEndStates = columnDefs.map(columnDef => columnDef.stickyEnd);
    this._stickyStyler.updateStickyColumns(rows, stickyStartStates, stickyEndStates, rowDef.sticky!);
  }
```

```typescript
  updateStickyColumns(
      rows: HTMLElement[], stickyStartStates: boolean[], stickyEndStates: boolean[], isSticky = false) {
   // [...]
  }
```

In this way, when the sticky property is not present we'll get an undefined which will default to false while, when it's present, the actual value will be passed on allowing us to get the stickyness of a row inside `updateStickyColumns`.

This is possible because header and footer rows are passed one by one to the `_addStickyColumnStyles` method, if this changes the fix will break and a comment (and an automatic test) must be put in place to prevent random code failule.

All this changes will be documented with instruction to rollback when nested sticky elements problem is solved by Edge team.

Tomorrow I'll try to define the code to actually put in place the fix inside **sticky-styler** class.

@andrewseguin what do you think about this?

**Comment by andrewseguin** [comment] 2022-03-29 21:50
Closing since Edge has switched to Chromium since 2020 and this is likely obsolete

**Closed by andrewseguin** 2022-03-29 21:50 UTC
Labels: P4, area: material/table
