### ISSUE TITLE
help(markerclusterer): TypeScript motzt das es im Objekt “b” kein Objekt “g"

### ISSUE THREAD

**Issue by l10rdev** [angular/components#23935] opened 2021-11-10 10:32 UTC
### What are you trying to do?

As the the @googlemaps/markerclustererplus library is marked as deprecated i wanted to use the recomended version @googlemaps/markerclusterer but when there i get an error W\when i close the component with the map

`TypeError: b.g.remove is not a function`

### What troubleshooting steps have you tried?

Moving back to @googlemaps/markerclustererplus works again.

### Reproduction

Steps to reproduce:
1. Chagne @googlemaps/markerclustererplus to @googlemaps/markerclustererplus in the script import

### Environment

- Angular:
- CDK/Material:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by crisbeto** [comment] 2021-11-17 13:15
Duplicate of https://github.com/angular/components/issues/23695.

**Closed by crisbeto** 2021-11-17 13:15 UTC
Labels: troubleshooting, needs triage
