### ISSUE TITLE
Tabs text is overlapping each other on switch, content is not visible.

### ISSUE THREAD

**Issue by tarasbobak** [angular/components#6946] opened 2017-09-08 14:41 UTC
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Tabs are switched without overlapping of their content and we don't get empty tab body after switching between them.

#### What is the current behavior?
1. Tabs body is overlapping each other on switch between them.
2. We get empty tab body after quickly switching between them.

#### What are the steps to reproduce?

http://plnkr.co/edit/YFfGIeqn9AyBsKcRWNuL?p=preview
Quickly switch between tabs.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Edge, IE11.

**Comment by donroyco** [comment] 2017-09-08 15:11
I could reproduce the issue (first step) in IE11. I think it's related to the animation. It doesn't stop the current one.
![tab-ie11](https://user-images.githubusercontent.com/1763537/30218096-6cf6a516-94b8-11e7-93fb-ed5965e5a812.gif)

**Comment by tarasbobak** [comment] 2017-09-11 07:25
Second issue. Windows 10, Edge.
https://i.imgur.com/pioI45E.gifv

It looks like part of the DOM inside initially hidden tab is not being repainted.

**Comment by jelbourn** [comment] 2021-07-29 00:18
Closing this issue because Angular is dropping support for IE11 in the upcoming version 13. We don't plan to fix any further IE11 bugs going forward.

**Closed by jelbourn** 2021-07-29 00:18 UTC
Labels: P3, area: material/tabs, ie11, needs investigation
