### ISSUE TITLE
Tab label opacity does not correspond to Material spec

### ISSUE THREAD

**Issue by benelliott** [angular/components#10061] opened 2018-02-21 10:43 UTC
#### Bug, feature request, or proposal:

Tab labels are given `opacity: 0.6` unless focused as per https://github.com/angular/material2/blob/master/src/lib/tabs/_tabs-common.scss#L13

#### What is the expected behavior?

The [Material design spec](https://material.io/guidelines/components/tabs.html#tabs-specs) makes no mention of this opacity. The closest thing I can find is the mention of "Unfocused tab color: #fff 70%", however based on the screenshots I believe they are using "unfocused" to mean "inactive", as there is no suggestion that the active tab will not have full opacity when the user is interacting with the content. This is supported [later in the spec](https://material.io/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior) (see "App bar with tabs") where an animation shows the user interacting with tab content without the tab label opacity changing. 

#### What is the current behavior?

Active tab labels are translucent when not focused. 

#### What are the steps to reproduce?

https://stackblitz.com/edit/angular-material2-issue-yxcskn

#### What is the use-case or motivation for changing an existing behavior?

The implementation is not aligned with the spec, and the opacity rule can cause legibility issues when using a lighter font than Roboto.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?

Latest StackBlitz, Chrome 64, Windows 10

#### Is there anything else we should know?

I would suggest applying `opacity: 1` on any active tab label.

**Comment by gtranter** [comment] 2018-04-19 17:01
IMO, the [fix](https://github.com/angular/material2/pull/10064) being implemented is still wrong. All tab labels should be fully opaque (opacity: 1), not just that active tab.

The spec only describes colors for tab groups with a colored background (i.e. 'mat-background-*'). In this light, "#fff 70%" should be recognized as the 'secondary-text' foreground color for dark themes. Therefore, for light themes, the unfocused tab text color should also the secondary text color - 54% black. At present, the color is 'text' or 87% black combined with .6 opacity. This is close to but not quite as dark as 54%.

My recommendation is to **remove the .6 opacity setting** from all tab labels and set the text color appropriately: theme color for active/focused, 'secondary-text' for other tabs, 'disabled-text' for disabled tabs.

Additionally, the _active_ tab text color is not properly implemented according to the spec. It should be the theme's primary color, and be assignable as accent or warn color using color="accent" (or "warn") on mat-tab-group. It is currently just the foreground 'text' color, and does not respond to the color assignment. The ink bar and active highlight background seem to have this done properly.

**Comment by jelbourn** [comment] 2020-10-22 21:28
Duplicate of #2058

**Closed by jelbourn** 2020-10-22 21:28 UTC
Labels: P4, area: material/tabs, has pr
