### ISSUE TITLE
MatDrawer: Have to tap list-item in sidenav twice on mobile when opened with HammerJS gesture

### ISSUE THREAD

**Issue by lukfel** [angular/components#20419] opened 2020-08-26 10:13 UTC
I have a material sidenav in my web-app which I can also open with the HammerJS swipe-right gesture. However, when openend with the gesture, I have to tap twice on a list-item in the sidenav to perform the attached action (click, routerLink).

#### Reproduction
I tried to reproduce this problem on stackblitz with a similar setup, but for some reasons it seems to work in the stackblitz.
[Stackblitz](https://stackblitz.com/edit/components-issue-mdnx12?file=src/app/example-component.css)
But maybe someone has a similar setup and experienced the same problem.

Steps to reproduce:
1. Import MatDrawerModule
2. Import HammerJS
3. Create mat-sidenav
4. Attach swipe-right gesture to mat-sidenav-content
4. Swipe the mat-sidenav open and tap on a list-item with a click-event or routerLink
 
 
#### Expected Behavior

Performing the action on the list-item with a single tap, even when the sidenav is opened through gestures

#### Actual Behavior

Having to tap twice on the list-item to perform the attached event

#### Environment

- Angular: 10.0.1
- CDK/Material: 10.0.0
- Browser(s): Chrome, Chrome-Android
- Operating System (e.g. Windows, macOS, Ubuntu): Windows, Android

This problem occurs on Android phones with Chrome as well as on Chrome for Windows when simulating phone behaviour in the developer tools.

**Comment by crisbeto** [comment] 2020-08-30 09:21
I wasn't able to reproduce it on an iOS device, but the fact that it doesn't fail for you on Stackblitz makes me think that there might be something else (CSS or JS) in your app that's interfering with it. The problem also sounds like it could be an issue with sticky `:hover` or `:focus` styling. Does it happen if you replace the `mat-list-item` instances with plain `a` tags? Another possibility is that the styles which are set by Hammer.js could be messing with it.

**Comment by RegniBlef** [comment] 2020-08-30 15:48
It never happens when I open the sidenav with the menu-button, only when I open it with a gesture from HammerJs.
I updated the stackblitz ([link](https://stackblitz.com/edit/components-issue-mdnx12?file=src/app/example-component.html)) and managed to reproduce it.

1) Open the application url of the stackblitz with Chrome ([link](https://components-issue-mdnx12.stackblitz.io))
2) Open developer tools (F12)
3) Enable responsive mode (see image below)
![image](https://user-images.githubusercontent.com/37081720/91663316-58b83180-eae8-11ea-86b1-a4d7343df5dc.png)
4) Swipe to the right and select an item after the sidenav is opened
5) Repeat multiple times until there is no console output and the sidenav doesn´t close

**Comment by zarend** [comment] 2022-01-07 22:21
Can't repro on my desktop. I tried swiping right 20 times.

macos version 12.1 (21C52)
chrome Version 97.0.4692.71 (Official Build) (x86_64)


I also tried on my phone but the demo never loads.

iPhone SE (1st gen)
iOS 15.2

<img src="https://user-images.githubusercontent.com/7720245/148614868-7993be94-594b-478b-8edf-e2f5bbbf042b.PNG" width=300 alt="Connecting to dev server..."/>

**Comment by wagnermaciel** [comment] 2022-03-16 16:41
Closing as we have been unable to reproduce this and there has been no follow-up since Jan 7

**Closed by wagnermaciel** 2022-03-16 16:41 UTC
Labels: cannot reproduce, needs triage, area: material/list, area: material/sidenav
