### ISSUE TITLE
error TS-998003: No directive found with exportAs 'matMenu'

### ISSUE THREAD

**Issue by mac4manu** [angular/components#17983] opened 2019-12-17 06:57 UTC
#### Reproduction
Upgraded to Angular 9.0. After upgrade getting -  "No directive found with exportAs 'matMenu' " issue -
Followed below steps -
https://update.angular.io/#7.2:9.0

Package JSON like below -

    "@angular/animations": "9.0.0-rc.6",
    "@angular/cdk": "9.0.0-rc.5",
    "@angular/common": "9.0.0-rc.6",
    "@angular/compiler": "9.0.0-rc.6",
    "@angular/core": "9.0.0-rc.6",
    "@angular/flex-layout": "8.0.0-beta.27",
    "@angular/forms": "9.0.0-rc.6",
    "@angular/material": "9.0.0-rc.5",
    "@angular/material-moment-adapter": "9.0.0-rc.5",
 
 
#### Expected Behavior

matMenu should render

#### Actual Behavior

No directive found with exportAs 'matMenu' 
No directive found with exportAs 'cdkOverlayOrigin'
No directive found with exportAs 'matAutocomplete'

#### Environment

- Angular: 9.0.0-rc.6
- CDK/Material: 9.0.0-rc.5
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by devversion** [comment] 2019-12-19 19:49
@mac4manu Thanks for the issue! I'm marking this as duplicate of #17984 since I've been adding comments there already. Could you please jump over and help providing a reproduction/or more details? Thanks!

**Closed by devversion** 2019-12-19 19:49 UTC
