### ISSUE TITLE
drag-drop: Dropping into nested ChildList

### ISSUE THREAD

**Issue by ked1** [angular/components#14093] opened 2018-11-12 09:51 UTC
#### Bug, feature request, or proposal:
Bug, Feature depending on the expectation, which isn't totally clear in this case. 

I would tend to say, it is a bug, because my use case seams to be quite common.

#### What is the expected behavior?
It should be possible to drag and drop from a parent list into a nested child list.

#### What is the current behavior?
No placeholder is displayed in the child list and the received container in the drop event method is always the parent list. The placeholder moves only in the parent list, which is consistent to the described drop event data.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-dragdrop-from-parent-to-nested-childlist
Drag parent item into the subitem list.

(From subitem list to parent list works correctly)

#### What is the use-case or motivation for changing an existing behavior?
We have a component to configure menu structure by drag and drop. It should be possible to move menu items to a sub menu.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
@angular/cdk 7.0.3

#### Is there anything else we should know?
In our use-case we have only one element with a child list, which could be possible to solve with the current implementation assuming it is a bug. I'm struggling by the imagination with multiple child lists according to the concept with template variables.

**Comment by michaelbromley** [comment] 2018-11-26 12:51
I've also run into this when working on a drag-drop category tree editor component.

As you can see in this video, it *is* possible to drag into a nested list, but it is just exceedingly difficult. There's probably a 1-pixel window which you must land on in order for it to work.

![ezgif-1-542fe60bba71](https://user-images.githubusercontent.com/6275952/49014937-f2b7b100-f181-11e8-9c48-fd7f96227314.gif)

I've not looked at the implementation, but visually it looks like the lower `cdkDrag` will switch position as soon as the `cdkDragPlaceholder` crosses its top boundary. Perhaps allowing the reordering to occur after <x pixels/percent> overlap of that item might make it possible to ergonomically drag into a nested list?

**Comment by ked1** [comment] 2018-11-27 08:58
I just recognized, that my stackblitz has an issue. The parentList is connected to non-existing childList property. But still I'm not sure how to fix it and if it would work.

**Comment by michaelbromley** [comment] 2018-11-27 10:04
@ked1 Sure, here you go: https://stackblitz.com/edit/material2-14093

**Comment by FritzHerbers** [comment] 2018-12-25 09:37
Noticed the merged https://github.com/angular/material2/pull/14257 into master/7.2.0.
The above stackblitz examples look better. Moving items into other child's still shows issues.

**Comment by MarkPieszak** [comment] 2018-12-30 16:08
7.2.0 seems to get us in the right direction (if you update @michaelbromley stackblitz for example), it gets us less jittery, but unfortunately it seems we're still unable to move something _inside_ of a Nested Child.

**Comment by FritzHerbers** [comment] 2019-01-03 16:57
@MarkPieszak 
Tried to identify the problem with the above example, but couldn't find it.

The example generates nested cdkDropListGroup. This might only work for the DropList's in the group not transfering to one List from another Group. Deleted the cdkDropListGroup in app-product-category-tree and made one in app.html, still didn't work.

[cdkDropListEnterPredicate] does not show any events in @7.2.0. 

With @7.2.0 in my application (WYSIWIG ngx-formly based form designer) where I use nested childs to group form fields and for horizontal layouting I can move and transfer between all lists.

Still jitter exists, when setting up `cdkDropListEnterPredicate` and moving over a parent and child many calls are made. Here material should only take the child into account.

**Comment by FritzHerbers** [comment] 2019-02-11 16:32
I adapted @michaelbromley example [https://stackblitz.com/edit/material2-14093-qwaobp](https://stackblitz.com/edit/material2-14093-qwaobp?file=src%2Fapp%2Fcomponents%2Fproduct-category-tree-node%2Fproduct-category-tree-node.component.ts) to use a drag registration service.

Removed `cdkDropListGroup` in product-category-tree.
Each tree-node wraps a `CdkDropList`, with `AfterContentInit` it registers to the drag registration service.
In the html `[cdkDropListConnectedTo]="dropListConnectedTo"` is used for allowed list to drag into, the method returns all registered  `CdkDropList`.

Now items can be transferred, although it needs some mouse moving to accomplish a transfer.

There is still a lot of jitter, as the CDK enables all  `CdkDropList` under the mouse, instead of only offering the deepest (highest z-index) child.

I think, transfers are failing because of the size of draggable and the destination. Therefor moving to the deepest child is not possible.

In my own application, I don't have problems transferring to the first/last position, in this example I have problems, especially to the first position.

tested with cdk@7.3.1

Hoping to get some feedback and pin-pointing the remaining problems for fixing.

**Comment by volser** [comment] 2019-04-14 08:57
Any news here?

**Comment by SantiagoIlli** [comment] 2019-05-21 14:00
Check this stack blitz solution, it may help you to find a work around in the mid time.
https://stackblitz.com/edit/nested-connected-lists

**Comment by djcurfew** [comment] 2019-06-19 13:16
We are willing to offer a bounty if anyone can get this done, $500 to do it.

**Comment by BradleyHarper** [comment] 2019-06-27 18:50
> We are willing to offer a bounty if anyone can get this done, $500 to do it.

Challenge accepted

**Comment by Kayes-Islam** [comment] 2019-06-30 16:24
We need exactly this so that we can drag items in and out of grouped list in our app. Looking forward for a solution.

**Comment by dylanfricks** [comment] 2019-07-01 17:15
Not a solution, but an alternative is [ngx-drag-drop.](https://www.npmjs.com/package/ngx-drag-drop) It's demo link has nested lists.

**Comment by ipakhomov** [comment] 2019-07-02 12:33
Guys, please check out my solution - I was able to achieve described behavior using the latest (8.0.x) version of Angular CDK:
https://stackblitz.com/edit/angular-cdk-nested-drag-drop-demo
Try to nest items in other ones.

**Comment by michaelbromley** [comment] 2019-07-02 12:51
@ipakhomov It certainly works for nesting 👍

But I cannot seem to reorder. Is it just that you didn't implement reordering logic?

**Comment by ipakhomov** [comment] 2019-07-02 12:59
@michaelbromley yup, reordering is not handled right now, but I suppose it's possible to implement. I just tried to reproduce expected in the issue behavior:
>It should be possible to drag and drop from a parent list into a nested child list.

**Comment by bradtaniguchi** [comment] 2019-07-02 18:11
@ipakhomov So I guess you could say with version 8 all the funky glitches have been fixed, so nested drag and drop is totally viable without any unusual hacks right? (I'm checking out the stack-blitz now, looks great :D)

**Comment by ipakhomov** [comment] 2019-07-02 20:56
@bradtaniguchi Yes, it seems that described by @michaelbromley [issue](https://github.com/angular/components/issues/14093#issuecomment-441628059) was fixed in the last updates, so we don't need to do anything hacky to implement nested drag-n-drop :wink:

**Comment by ked1** [comment] 2019-07-03 05:53
> Guys, please check out my solution - I was able to achieve the described behavior using the latest (8.0.x) version of Angular CDK:
> https://stackblitz.com/edit/angular-cdk-nested-drag-drop-demo
> Try to nest list items in other ones.

Yes indeed, your example seems to work well. I can't proof it on my original "real world" case, because the project is not on my todo list anymore.

@michaelbromley @FritzHerbers @MarkPieszak @djcurfew @johannesheucher Do you agree with me to close this issue?

@crisbeto Thanks for your great contributions on the Angular CDK!

**Comment by michaelbromley** [comment] 2019-07-11 08:39
@ked1 I just tested with @angular/cdk v8.0.2 and following the example from @ipakhomov I can indeed get nesting to work! 

Now I just need to wait for automatic scrolling to land and I can implement this in my app 🎉

**Closed** 2019-07-15 07:08 UTC

**Comment by Kayes-Islam** [comment] 2019-07-19 02:36
Thanks @ipakhomov, I'll check out your solution. I wish though something simple as this worked out of the box:
https://stackblitz.com/edit/angular-drag-and-drop-child-groups

**Comment by Priemar** [comment] 2019-07-19 07:32
Hey,
after reading the comments here i was optimistic to get nested drag and drop to work with material drag and drop. For me drag drop between parent and nested lists with sorting did not work. Whenever i try to sort inside a nested list, the placeholder appears in the parent list.

I would love to use the default material drag and drop implementation, because its working great in other usecases for me. If someone managed to get this case working with material drag and drop, it would be nice to get the info how?!

Anyway i needed an implementation asap for our project, thats why i wrote yesterday my own drag and drop implementation, which is working with nested lists.
(i created a POC showcase. this code is not polished or tested etc.  today) 

if someone has also the same usecase watch the demo, the is a contact link. (if there is enough inter. ill investigate the time to extract the code and create a public library)

[https://priemar.github.io/pri-ng-dragdrop-showcase/](url)

@djcurfew is that what you need ?!

**Comment by pavlovandreyka** [comment] 2019-07-23 11:15
@Priemar it looks like good.

**Comment by fatalcaron** [comment] 2019-07-27 14:47
The solution of @Priemar resolve this issue I agree. 
But that came with a lot of complexity to handle the reordering.  Has someone come to a solution?

**Comment by Priemar** [comment] 2019-07-28 16:35
@fatalcaron my implementation is similar to the material implementation.

You can set a data object for the dragItem and a dataItem for the droplist.

In the dropList -> dropEvent you will get the 
 - sourcelist data item
-  targetlist data item
- target list drop index
- drag item data". 

So you can simply remove the item from the sourcelist and add it in to the target list at the given drop index.

I think thats straight forward and not complex.

For a good performance i recommend using trackBy for the *ngFor and onPush changedetection. With those mechanisms the performance is good (sure it depends on the scenario).

Anyway at the moment there is not much need for this libarary as it looks like. So i currently will not investigate the time to extract and put the library to npm. (maybe it changes in the future, then i can contact you @fatalcaron )

cheers

**Comment by fatalcaron** [comment] 2019-07-28 20:57
Really sorry, I wanted to mention the solution of @ipakhomov

**Comment by SRINIVAS-16** [comment] 2019-08-13 09:03
> @michaelbromley yup, reordering is not handled right now, but I suppose it's possible to implement. I just tried to reproduce expected in the issue behavior:
> 
> > It should be possible to drag and drop from a parent list into a nested child list.

This solution resolved my use case, but sorting needs to be implemented. 
@ipakhomov , Could you provide some clue regarding how to integrate reordering with your solution.

**Comment by Priemar** [comment] 2019-09-04 13:01
As i wrote above i created a lib. for nested drag and drop: (bec. of time issues its currently not a release version) but maybe someone needs an alternative until the angular/material drag drop is working correctly.

https://www.npmjs.com/package/pri-ng-dragdrop

**Comment by tulioFcastro** [comment] 2019-09-20 11:24
> We are willing to offer a bounty if anyone can get this done, $500 to do it.

Are you still paying for it? I got the solution.
