### ISSUE TITLE
Using [ngmodel] turns toolbar white

### ISSUE THREAD

**Issue by Nanoboss** [angular/components#18466] opened 2020-02-11 18:37 UTC
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/components-issue-fqdwcq (line 22  and line 33 of the exemple component.html)

Steps to reproduce:
1. replace Ngmodel by [Ngmodel]="something"
 
#### Expected Behavior

I'm expecting nothing to change.

#### Actual Behavior

The toolbar turns white.

#### Environment

- Angular:
- CDK/Material: 6.13.6
- Browser(s): 
Chrome Version 79.0.3945.130 (Build officiel) (64 bits) 
Safari Version 13.0.4 (15608.4.9.1.3)

- Operating System (e.g. Windows, macOS, Ubuntu):  MacOS Catalina 10.15.2 (19C57)

**Comment by crisbeto** [comment] 2020-02-11 20:01
There are a bunch of errors being logged in the console. Most likely they're the cause of the color not being applied.

**Comment by jelbourn** [comment] 2020-02-14 02:37
Closing since this seems unrelated errors

**Closed by jelbourn** 2020-02-14 02:37 UTC
Labels: needs clarification
