### ISSUE TITLE
[MatSort] sort function doesn't render sorting arrow

### ISSUE THREAD

**Issue by vadjs** [angular/components#15715] opened 2019-04-04 09:26 UTC
#### What is the expected behavior?
`sort` function in `MatSort` should update sorting arrow rendering state.

#### What is the current behavior?
Currently `sort` function in `MatSort` not updating sorting arrow rendering state.

#### What are the steps to reproduce?
https://stackblitz.com/edit/angular-cfcugl-17fxat
If you click "sort by name" button you will see this bug.
"Sort with fix" button shows the easiest way to fix this bug.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
All

**Comment by jonathanRinciari** [comment] 2019-05-11 17:44
I am going to look into this because I have run into the same thing in projects!

**Comment by jysoo** [comment] 2019-05-12 11:12
@jelbourn  If no one is working on this, perhaps I can give it a go next weekend or so? :)

**Comment by jelbourn** [comment] 2019-05-12 15:34
@jysoo go for it

**Comment by francescodist** [comment] 2019-05-16 13:46
@jysoo The solution you proposed doesn't work properly for me, when the arrow is supposed to be cleared.
Calling the _handleClick() function, instead, solves it for me. Probably we could have a function on MatSort that basically does what "sortByNameFixed" is doing, provided an id (string) for a sortable
```
sortByNameFixed() {
    const sortHeader = this.sort.sortables.get('name');
    sortHeader['_handleClick']();
  }
```

**Comment by ovk** [comment] 2019-05-28 13:17
Should `MatSort` also react to changes to `active` and `direction` properties and update sort header arrows state automatically to match the current state? This would be consistent with how paginator behaves.

**Comment by jysoo** [comment] 2019-07-16 13:38
@jelbourn @andrewseguin  May I ask if the team intends to incorporate a fix for this issue some time in the future? (There's a PR #16413) Thanks.

**Comment by rothsandro** [comment] 2022-06-27 10:54
I just tested this again with Angular 13 and I cannot reproduce the bug anymore. I guess this has been fixed by some other changes. @vadjs Can you confirm that?

**Comment by jelbourn** [comment] 2022-08-10 20:01
Thanks for commented- seems like this was incidentally fixed somewhere along the way. Feel free to reopen if someone can reproduce it still happening with a new version.

**Closed by jelbourn** 2022-08-10 20:01 UTC
Labels: P3, help wanted, good first issue, area: material/sort
