### ISSUE TITLE
The selectionChange event does not fire when completed is false

### ISSUE THREAD

**Issue by fireflysemantics** [angular/components#18080] opened 2020-01-01 05:49 UTC
#### Reproduction
https://stackblitz.com/edit/angular-mat-stepper-demo-ao844t?file=src%2Fapp%2Fapp.component.html

Steps to reproduce:
1.Toggle step 1 to be incomplete 
2. Try firing the selection change event by click on the step 1 or step 2 `mat-step` elements
 

The event will not fire.  

In my use case I want it to fire such that I can peform the toggle using that event.  So for example if Step 2 is clicked, then the event handler will perform the check that toggles the completed state of step one to true.
 
#### Expected Behavior

What behavior were you expecting to see?

The event should fire and report the correct index regardless of whether the stepper will allow progress to the step clicked on.

#### Actual Behavior

What behavior did you actually see?

No event is reported at all.

#### Environment
Stackblitz

**Comment by fireflysemantics** [comment] 2020-01-01 06:21
Related SO Post:

https://stackoverflow.com/questions/59549423/adding-a-click-event-handler-directly-to-mat-step

**Comment by prashantpimpale93** [comment] 2020-01-01 08:37
@fireflysemantics Why don't you use `optional` for step 1? I mean if it is mandatory then why we should entertain the user to check for step 2 and step N?

**Comment by fireflysemantics** [comment] 2020-01-01 11:25
@prashantpimpale93 

My design goal is to eliminate the need for next and previous buttons.  The user should just be able to click on the `mat-step` elements (Which are rendered as `mat-step-header` elements I believe.

In this case the step indexed as `0` has a form in it.  That form has to be valid before step 1 can be selected.

So when the user clicks on step one (The `mat-step` for step one` that triggers the `selectionChange` handler which checks to see whether step 0 is complete.

If step zero is complete then the `[complete]` observable signals true and step 1 can be navigated to.

Except the `selectionChange` handler does not report the correct index, so I can't check which step the user clicked on.

**Comment by fireflysemantics** [comment] 2020-01-01 11:29
This is a screenshot of the app.  I want the users to be able to click directly on the next steps.  In this case since the form is not valid, none of the other steps can be navigated to.

![Screenshot from 2020-01-01 05-27-37](https://user-images.githubusercontent.com/25155787/71640839-a7f74b00-2c57-11ea-9867-95df66d2f9da.png)

**Comment by prashantpimpale93** [comment] 2020-01-01 11:30
@fireflysemantics Yes, got it!

**Comment by prashantpimpale93** [comment] 2020-01-01 11:46
@fireflysemantics  The problem is `linear` attribute! If you remove it then it just work fine!

**Comment by fireflysemantics** [comment] 2020-01-01 20:17
@prashantpimpale93 I seems to work at first, but when linear mode is turned off, the `completed` attribute no longer blocks a user from proceeding.

**Comment by villanuevacarlos14** [comment] 2020-05-03 13:51
Any solutions on this? I am having the same issue.

**Comment by mmalerba** [comment] 2020-07-10 20:43
Closing as a dup of #19918 since that issue more clearly captures this as a feature request rather than a bug

**Closed by mmalerba** 2020-07-10 20:43 UTC
Labels: area: material/stepper, needs triage
